### ISSUE TITLE
OSM notes with comments are displayed twice

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1000]
## Vespucci Version
13.1.8

## Download source
Not sure, probably F-Droid.

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
7.1.2 (Fairphone Open OS (not the default OS))

## Behaviour/Symptoms
When selecting a OSM note with comments (e.g. https://www.openstreetmap.org/note/1702676 ), the note is not immediately displayed. Instead a menu appears that lets the user choose between different entries. In the given example the menu shows the text `Note: check maxspeed  - Open` twice. (The menu seems to be the same menu which is shown when multiple elements, e.g. nodes are too close together to be properly selected.) When the first entry is selected, only the first note text (`check maxspeed`) is displayed. When the second entry is selected, both note texts (`check maxspeed` and `maxspeed is 20 ...`) appear. This behaviour is confusing since it gives users the impression that there are two notes.

## Expected Behaviour
A selected note should be displayed immediately.

Additionally, different comments and the original note text should have a stronger visual separation, e.g. using a horizontal line or an alternating background colour. (I can open a separate issues for this if necessary.)

## How to recreate
Open the mentioned note in Vespucci.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
The URLs created in the first comment of the note return HTTP 404 errors. This seems to be a problem of StreetComplete. I will check this separately...

**Comment by simonpoole** [comment]
I can't directly recreate the issue, but I suspect this may be due to the note being in storage twice due to an issue with merging notes. Did you have data from pre the comment was added on device?

**Comment by ltog** [comment]
I'm not 100% sure but it's quite realistic that I downloaded the data (including notes) before, then added the note via StreetComplete and then downloaded data again using Vespucci.

Furthermore, I can see notes and osmose tasks from places where I have been days ago. Is that to be expected?

**Comment by simonpoole** [comment]
> 
> 
> I'm not 100% sure but it's quite realistic that I downloaded the data (including notes) before, then added the note via StreetComplete and then downloaded data again using Vespucci.

I did a quick test: create a note, upload, add a comment outside of vespucci, re-download
in vespucci and everything worked as expected. 

> 
> Furthermore, I can see notes and osmose tasks from places where I have been days ago. Is that to be expected?

Yes, the default for notes and osmose tasks is simply to add/merge any new data (in 14.0 this is the case for data too). If you want to reset/clear you need to do that explicitly.

PS: I believe the issue with the images stored via SC is that they are considered stale after a while and then deleted.

**Comment by ltog** [comment]
> If you want to reset/clear you need to do that explicitly.

@simonpoole : How do I do that?

The StreetComplete issue was reported here: https://github.com/westnordost/StreetComplete/issues/1588

**Comment by simonpoole** [comment]
> 
> 
> > If you want to reset/clear you need to do that explicitly.
> 
> @simonpoole : How do I do that?
> 
Transfer menu -> Tasks (Aufgaben) -> Clear (Zurücksetzen)

**Comment by simonpoole** [comment]
Stale, closing.
