### ISSUE TITLE
Difficult to upload in portrait

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1001]
Description:
---

Can't easily get to DONE button when try to submit in portrait mode on Motorola G6

Device info:
---
<table>
<tr><td>App version</td><td>13.1.8.0</td></tr>
<tr><td>App version code</td><td>1211</td></tr>
<tr><td>Android build version</td><td>f1bdc</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPSS29.55-37-4-3</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>ali_n</td></tr>
<tr><td>Device model</td><td>moto g(6)</td></tr>
<tr><td>Device product name</td><td>ali_n</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>ndm</td></tr>
</table>

**Comment by simonpoole** [comment]
Simply pressing the "enter" button on the keyboard twice should step through the text fields and then dismiss the keyboard.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/ead9c8266ae7f85d92afe1b62b89916cedf19e6b attempts to stop gratuitous appearances of the keyboard after pressing the "enter" key.
