### ISSUE TITLE
amenity=outdoor_seating ist unknown

### ISSUE THREAD

**Issue by chatelao** [MarcusWolschon/osmeditor4android#1002]
How can I add the amenity=outdoor_seating tag to the repository

**Comment by HolgerJeromin** [comment]
https://github.com/simonpoole/beautified-JOSM-preset is the repo you are searching for

**Comment by simonpoole** [comment]
Note that amenity=outdoor_seating has essentially no usage see https://taginfo.openstreetmap.org/search?q=amenity%3Doutdoor_seating and not even a wiki page, so it sound more like something that you would want to create a custom preset for.

**Comment by chatelao** [comment]
Sorry folks, my mistake: it is LEISURE, not amenity:

https://wiki.openstreetmap.org/wiki/DE:Tag:leisure%3Doutdoor_seating

This one exists (and is nicely rendered in OSM-Carto).

Simon Poole <notifications@github.com> schrieb am So., 29. Sep. 2019, 20:40:

**Comment by chatelao** [comment]
And it is missing in Vespucchi, aus far als I can judge.

Olivier Chatelain <olivier.chatelain@gmail.com> schrieb am Mo., 30. Sep.
2019, 12:54:
