### ISSUE TITLE
MapRoulette task "explanation"

### ISSUE THREAD

**Issue by govvin** [MarcusWolschon/osmeditor4android#1003]
## Vespucci Version
Vespucci 13.1.7
Flavor: current
Maximum avaliable memory 536870912
Total memory used 24412138
Tile Cache MAXAR-STANDARD usage Size 38797312 of maximum 67108864 #entries 148
Tile Cache OSM_INSPECTOR-GEOMETRY usage Size 0 of maximum 67108864 #entries 0
State file size 16182 last changed 2019-10-04 22:52:20
Bug state file size 412700 last changed 2019-10-04 22:52:20
Relations (current/API): 0/0
Ways (current/API): 6/0
Nodes (current/Waynodes/API): 109/113/0
Available location providers
passive enabled true
gps enabled true
network enabled true

## Download source
FDroid

## Device (Manufacturer and Model)
Samsung Tab S3, SMT830

## Android Version 
9.0

## Behaviour/Symptoms
When an available MapRoulette (MR) task is clicked, a dialog box will open. Click on the Explanation link to display the task instruction text from the MR Challenge. The text displayed in Vespucci renders the mustache tags (e.g. {{name}} ) literally, rather than the expected values from MR.

## Expected Behaviour
MR mustache tag should be rendered correctly, Let's say the value of {{name}} is "FOO", then the string, "This is {{name}}" from the description or task instruction should render as  "This is FOO"

## How to recreate
Try this [task](https://maproulette.org/challenge/9413) in this area https://openstreetmap.org/?mlat=10.8383581&mlon=-93.7263498#map=17/10.8383581/-93.7263498

**Comment by simonpoole** [comment]
Is this documented any where? In particular how to get the placeholder values from the API?

**Comment by simonpoole** [comment]
OK the problem seems to be that if you retrieve the tasks per bounding box you don't get the per-task property information (matter of fact the data returned is significantly different than for an individual task query. Go figure.
