### ISSUE TITLE
UI for upload

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1004]
Description:
---

Hello, in the ui for uploading the changes the second tab with the user comment is not very prominent and one might hit the upload button before reviewing it. BUT it is still prefilled with the previous content which might not be appropriate this time. So if this prefill function is kept, the user should be forced to see it before uploading. 

Device info:
---
<table>
<tr><td>App version</td><td>13.1.8.0</td></tr>
<tr><td>App version code</td><td>1211</td></tr>
<tr><td>Android build version</td><td>G903FXXU1BQC1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29K.G903FXXU1BQC1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>s5neolte</td></tr>
<tr><td>Device model</td><td>SM-G903F</td></tr>
<tr><td>Device product name</td><td>s5neoltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7580</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>J_Schneider</td></tr>
</table>

**Comment by simonpoole** [comment]
You will always be shown the 2nd tab once before upload, even if you press the upload button in the first tab.

**Comment by j-schneid** [comment]
Oh, you're right. I believed I had realized this behaviour during a previous use (probably months ago) but either I'm wrong or this has been changed. Anyway, thanks for the nice app!
