### ISSUE TITLE
Background image shifts at at different zoom levels

### ISSUE THREAD

**Issue by govvin** [MarcusWolschon/osmeditor4android#1006]
## Vespucci Version
Vespucci 13.1.7
Flavor: current
Maximum avaliable memory 536870912
Total memory used 59863368
Tile Cache MAXAR-STANDARD usage Size 45088768 of maximum 67108864 #entries 172
Tile Cache OSM_INSPECTOR-GEOMETRY usage Size 0 of maximum 67108864 #entries 0
State file size 74608 last changed 2019-10-05 23:35:11
Bug state file size 410271 last changed 2019-10-05 23:35:11
Relations (current/API): 1/0
Ways (current/API): 33/5
Nodes (current/Waynodes/API): 855/891/47
Available location providers
passive enabled true
gps enabled true
network enabled true

## Download source
FDROID

## Device (Manufacturer and Model)
Samsung Tab S3

## Android Version 
Android 9

## Behaviour/Symptoms
When I zoom  in an area, using the Maxar standard imagery, the background shifts while the data remain in place.

here are screenshots
![Screenshot_20191006-073451_Vespucci](https://user-images.githubusercontent.com/5821688/66262101-8a5b4680-e80c-11e9-95f0-8f6ed4917aef.jpg)
![Screenshot_20191006-073429_Vespucci](https://user-images.githubusercontent.com/5821688/66262118-eb831a00-e80c-11e9-88b7-dc4dacc30484.jpg)
![Screenshot_20191006-073415_Vespucci](https://user-images.githubusercontent.com/5821688/66265890-396d4180-e850-11e9-996c-916362092924.jpg)

## Expected Behaviour
Background shouldn't shift at all

## How to recreate
Tested [here](https://openstreetmap.org/?mlat=14.1331629&mlon=-94.1688297#map=20/14.1331629/-94.1688297) using Maxar Standard

## Crash dump submitted (no or yes + date)
no

**Comment by HolgerJeromin** [comment]
This is most probably a problem with the tile server. Please test with the "openstreetmap (standard)" background. 
Should be ok, when there is no bug in the editor.

**Comment by simonpoole** [comment]
There are multiple reasons why you might be seeing this:

- different zoom layers being generated from different data sources (the slightly different roof colour would indicate this is likely) with different orthorectification by the mosaic provider
- new tiles in the area in question and you still have some old ones in the on device cache (clearing the cache will resolve the issue if that is the case)
- imagery offset set for some of the zoom levels and not for others

**Comment by simonpoole** [comment]
Stale, closing.

**Comment by jidanni** [comment]
In current Vespucci, set an offset, draw a building, 

![Screenshot_20250128_103151_Vespucci.jpg](https://github.com/user-attachments/assets/b5320d7a-5c41-4218-9a04-81b2f27b990b)

After you are finished drawing, tap the "+" zoom button,

![Screenshot_20250128_103304_Vespucci.jpg](https://github.com/user-attachments/assets/01e57054-ad52-45d3-b2df-fda2e9fc3600)

**Comment by jidanni** [comment]
P. S., I won't get notifications if you block me.
