### ISSUE TITLE
Replace upload/download icon depending on whether there is something to upload

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1007]
I propose to dynamically adjust the icon for the upload/download menu:

![upload-download](https://user-images.githubusercontent.com/4726277/66273440-5156bc80-e874-11e9-90d5-24ce370cf8e1.png)

It should indicate, if there are changes to upload or not: I could look something like this if there aren't any changes to upload:

![upload-download-mockup](https://user-images.githubusercontent.com/4726277/66273447-692e4080-e874-11e9-8de2-0be89fcd0262.png)

**Comment by contrapunctus-1** [comment]
Colorize the upload arrow more strongly as the number of unuploaded edits increase, a la iD.

**Comment by simonpoole** [comment]
Addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/7c5d67ac48e3783b63668e05b56c39e583fee1d5
