### ISSUE TITLE
Upload dialog reappears aggressively after cancelling it once

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1008]
## Vespucci Version
13.1.8

## Download source
F-Droid (?)

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
7.1.2 (Non-standard Fairphone Open OS)

## Behaviour/Symptoms
After cancelling an upload the upload dialog reappears aggressively.

## Expected Behaviour
The dialog should only reappear when selected again through the upload menu.

## How to recreate

1. Open an arbitrary Android app
2. Open Vespucci
3. Download some data
4. Move a node
5. Choose `Upload data to OSM server`
6. Choose `NO`
7. Switch to other app
8. Switch back to Vespucci
9. Upload dialog reappers >:-(
10. Undo change using undo menu
11. Switch to other app
12.  Switch back to Vespucci
13. Upload dialog reappers. WTF‽
14. Try to upload the non-existing change. Vespucci reports: `You have not changed anything yet...` Well, at least Vespucci didn't crash... :-\

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
no

**Comment by simonpoole** [comment]
This was fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/2c2b7a6ffd45380b238b663d67d99c3dc122beea in 14.0 however it wasn't backported to 13.1 for 13.1.8 by accident (it was added at the end of last month so will turn up in 13.1.9 or so if there is another 13.1 release).

**Comment by simonpoole** [comment]
I've tagged a 13.1.9 release that should appear on FDroid in a couple of days https://github.com/MarcusWolschon/osmeditor4android/releases/tag/13.1.9.0
