### ISSUE TITLE
Osmose settings are not in validator settings group in optiond

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1009]
Description:
---

I am also unable to find them anywhere else, I remember that there was somewhere option to not show minor osmose options

In case of XY problem: I want to hide certain classes of reports that I consider as invalid to report (for example parking without service road inside) or not worth fixing (public transport route without version tag). Disabling minor osmose issue was hiding most of that useless spam (at cos of hiding some useful reports).

Device info:
---
<table>
<tr><td>App version</td><td>14.0.0.1</td></tr>
<tr><td>App version code</td><td>1300</td></tr>
<tr><td>Android build version</td><td>V10.0.14.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.14.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
http://vespucci.io/help/en/Introduction/#filtering

**Comment by matkoniecz** [comment]
> separate 3rd party data source (which they are).

Still, for user it is (probably) a part of a validator no matter where, how and by whom report is generated. Thanks for pointing me where I can find it.
