### ISSUE TITLE
Units not shown for unknown preset

### ISSUE THREAD

**Issue by Mannivu** [MarcusWolschon/osmeditor4android#1010]
Description:
---

After a user asked some help, I've found that when you add an unknown preset (in my case was "Physical restrictions") the default units are not shown.

 Screenshot
---
![Screenshot](https://i.imgur.com/bk9cdTo.png)

**Comment by simonpoole** [comment]
This is intended behaviour. 

Utility presets, that is presets that simply add some tags are not (and can't be sensibly) matched, and as a result the app doesn't have access to the descriptions that are associated with the tags. 

The way to address this is to first apply the preset for the object itself, for example highway=residential

![Screenshot_1570645677](https://user-images.githubusercontent.com/1011860/66509489-709f5500-ead3-11e9-8af2-4faaa0908f53.png)

Then apply the utility preset, which should be available as a "linked preset" if it makes sense in the context of the object.

![Screenshot_1570645828](https://user-images.githubusercontent.com/1011860/66509592-ad6b4c00-ead3-11e9-8136-f04516b11c8f.png)

Technically it matches the "object" preset and then treats all tags that are present in linked presets as if they had been in the "object" preset.

**Comment by Mannivu** [comment]
Ok, I see now that this particular preset should be used with another preset. I should warn the user that's the incorrect use of the preset.
