### ISSUE TITLE
Deselected multipolygon remains highlighted

### ISSUE THREAD

**Issue by taranarmo** [MarcusWolschon/osmeditor4android#1014]
## Vespucci Version
13.1.9

## Download source
f-droid

## Device (Manufacturer and Model)
Xiaomi A1

## Android Version 
9 stock

## Behaviour/Symptoms
In multiselect mode when selecting multipolygon and then deselecting it, it remains highlighted as if it is selected

## Expected Behaviour
Highlighting disappeares when deselecting

## How to recreate
In multiselect mode select and deselect any multipolygon

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
![Screenshot_20191015-092402](https://user-images.githubusercontent.com/11619234/66805403-9db59280-ef2d-11e9-8137-db291abdc669.png)
![Screenshot_20191015-090105](https://user-images.githubusercontent.com/11619234/66805426-a9a15480-ef2d-11e9-9308-95318c4929ba.png)

**Comment by simonpoole** [comment]
Thanks for the report! 

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/855be7e6296bcd0502d5b70755009ed9f749d0e5
