### ISSUE TITLE
Oauth causes net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by doublah** [MarcusWolschon/osmeditor4android#1016]
## Vespucci Version
13.1.9

## Download source
F-Droid

## Device (Manufacturer and Model)
LG K350n

## Android Version 
6.0

## Behaviour/Symptoms

Trying to login with Oauth causes net::ERR_NAME_NOT_RESOLVED, then if trying again all user sees is a blank white screen.

## Expected Behaviour
Log in as normal.

## How to recreate
Clear all app local data
Open app and press Tools > Authorize OAuth
See error message pop up at top of screen.

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
This sounds as if the DNS lookup failed which wouldn't be a Vespucci issue except if the domainname was misspelled.. 

Is the behaviour repeatable? And which API entry are you using?

**Comment by doublah** [comment]
Happens every time using the default OpenStreetMap API, it works with the sandbox (well, it atleast gets to the login screen but I dont have a sandbox login).

**Comment by simonpoole** [comment]
Can you make a screenshot of the contents of the default OSM API entry and add it to the issue? And could you test in an on device browser https://api.openstreetmap.org/api/capabilities

**Comment by doublah** [comment]
![Capture_2019-10-21-02-53-44](https://user-images.githubusercontent.com/11699874/67171442-9d424f00-f3a6-11e9-9bf5-1d9457ccb9f2.png)

api capabilities seems normal
`<osm version="0.6" generator="OpenStreetMap server" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/%22%3E<api><version minimum="0.6" maximum="0.6"/><area maximum="0.25"/><note_area maximum="25"/><tracepoints per_page="5000"/><waynodes maximum="2000"/><changesets maximum_elements="10000"/><timeout seconds="300"/><status database="online" api="online" gpx="online"/></api><policy><imagery><blacklist regex="..google(apis)?../(vt|kh)[?/].([xyz]=.){3}."/><blacklist regex="http://xdworld/.vworld/.kr:8080/."/><blacklist regex="..here.com[/:]."/></imagery></policy></osm>`

**Comment by simonpoole** [comment]
That was just a test to see if your device could resolve api.openstreetmap.org properly, which it can.  

The only way I can see to get more information on this is for you to send in a manual crash dump, Debug menu item in the main menu. However in 13.1 the log excerpt submitted is probably too short to be useful, 14.0 should however be available on f-droid soon. I still suspect that something is caching the negative DNS result and would suggest before doing anything else to restart your device if you haven't done so yet.

**Comment by simonpoole** [comment]
PS: have you recently added browser apps or anything similar?

**Comment by doublah** [comment]
Turns out one of my blokada adblocking lists was blocking piwik.openstreetmap.org, and it seems to work now with that domain whitelisted, don't know why the piwik subdomain would be needed though.
