### ISSUE TITLE
Failed to enable GPS

### ISSUE THREAD

**Issue by stephengmatthews** [MarcusWolschon/osmeditor4android#1018]
## Vespucci Version
13.1.9

## Download source
google play store

## Device (Manufacturer and Model)
Manufacturer: Planet Computers
Model: Gemini PDA (Mobile+Wifi)

## Android Version 
7.1.1

## Behaviour/Symptoms
I don't want to use GPS, because it take a long while to localise and drains battery. I keep GPS disabled in Android. A "Failed to enable GPS" message appears in the bottom of the app and covers up the buttons. I have to wait 5-10 seconds for it to disappear, so I can view and use the buttons that the message obscures. I have the FAQ, but it doesn't help me (https://vespucci.io/tutorials/faq/#why-do-i-have-to-have-gps-turned-on).

## Expected Behaviour
No message temporarily prevents me from using the buttons.

## How to recreate
1. Disable GPS in Android
2. Open Vespucci
3. Minimise Vespucci
4. Bring Vespucci to the foreground

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
The message in question is only displayed when checking if GPS is enabled throws an exception. This should normally not happen, normal behaviour is that it will show you the screen to re-enable GPS which you can suppress with a setting in the preferences. How are you "turning off GPS" on the device?

**Comment by stephengmatthews** [comment]
Thanks for speedy reply.

I'm "turning off GPS" in Android. Settings > Location > Off. I've attached
a screenshot.

"Leave GPS/GNSS turned off" is checked/enabled in Vespucci's preferences.

**Comment by simonpoole** [comment]
The screenshot didn't seem to work. In any case it looks very much like a device/manufacturer specific issue (that's why we all love Android :-)), could you try to, immediately after the error, manually submit a crash dump via the Debug menu entry in the main menu (up to and including 13.1 the log is limited to 200 lines, so we need to be lucky to see the error log for the specific problem, the beta for 14.0 submits 500 lines which should be more than enough).

**Comment by stephengmatthews** [comment]
Thanks. I've just sent a debug report through the app. I added the title of
this email and my email address in the notes.

**Comment by simonpoole** [comment]
As expected the logcat exceprt is a bit too short,, could you upgrade to the 14.0 beta? You simply need to enable that in your play store account, please finish any edits you may still have pending before upgrading.

**Comment by stephengmatthews** [comment]
I've now upgraded to beta and sent a debug report. Cheers.

**Comment by simonpoole** [comment]
Interesting, it seems as if you've removed the permission to access the GPS location, could you enable that again (leaving GPS off), and see if the issue still persists?

**Comment by stephengmatthews** [comment]
I enabled the location permission for the app and the "Failed to enable
GPS" no longer appears. Thank you!

**Comment by simonpoole** [comment]
Seems as if there is a slight behaviour difference compared to most devices when GPS is disabled. In any case your issue seems to be solved. Closing.

**Comment by Janokisu** [comment]
Hi,
I had the same error and it also works for me when you give the permission.
And as long as you either give the permission or have the GPS on everything is fine. 
But as soon as both do not apply, it sucks without end. Is there no way that it does not suck when both are off?

**Comment by simonpoole** [comment]
Why wouldn't you give the permission if you have GPS turned off anyway?

**Comment by Janokisu** [comment]
Because sometimes I do have the GPS on for certain apps and then it can happen that I forget to deactivate it again. That's why I don't allow other apps to use GPS, so that energy isn't wasted unnecessarily and the battery is drained too quickly.
