### ISSUE TITLE
Change border colour for "Probably outdated" POIs

### ISSUE THREAD

**Issue by Mannivu** [MarcusWolschon/osmeditor4android#1023]
I think that the border that indicates that a POI's infos might be outdated shouldn't be the same as the one that indicates that some important tags are missing.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/904608d08256cc42e412ed2358f2098bc2a48603

**Comment by Mannivu** [comment]
Thank you!
