### ISSUE TITLE
"Provide feedback" form loses contents when no network connection is available

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1026]
## Vespucci Version
14.0.1

## Download source
F-Droid

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
7.1.2 (Fairphone Open OS, not the default one)

## Behaviour/Symptoms
I tried to report a bug using the menu "Provide feedback". I didn't have a network connection, so an error was printed ("couldn't send form" or similar) and the form was closed. After reopening the content of the form was gone.

## Expected Behaviour
If a feedback form can't be sent, its content should be stored for sending it later.

## How to recreate
Not sure if it suffices to disable mobile data and try to send the form. My mobile data connection was automatically disabled by Android some time before due to exceeding the specified data usage limit. I also might have been connected to a (possibly non-working) wifi, can't remember exactly.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
The situation reminds me of the mouseover text of https://www.xkcd.com/1163/

**Comment by simonpoole** [comment]
The library that we are using doesn't provide such functionality, the only short term fix would be to disable the form when there is no network available.

**Comment by simonpoole** [comment]
BTW what was the original problem?

**Comment by ltog** [comment]
> the only short term fix would be to disable the form when there is no network available.

Hmm, is it possible to detect a missing networking functionality to give the user a chance to enable it? Whatever is implemented, it should prevent users from typing and then loosing their text. That is quite frustrating...

The original report was about Esri World Imagery (Clarity) not properly displaying. However it also happens on JOSM, so it probably isn't Vespucci's fault. Here's URL if you want to take a look: https://clarity.maptiles.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/tile/13/2875/4296 Requests partially give timeouts and 504 errors...

**Comment by simonpoole** [comment]
The ESRI issue (nothing to do with Vespucci) has been reported widely.

**Comment by ltog** [comment]
Ok, good to know. Thank you.

**Comment by simonpoole** [comment]
A proper fix would require adding a queuing mechanism which is likely too much work for a seldomly used feature (and would have to be built in to the upstream lib in any case).

https://github.com/MarcusWolschon/osmeditor4android/commit/95b3d0d4b2f4e44a41a0bdc28ec2b95c62d71168 disables the menu entries if network connectivity isn't present as a partial solution.
