### ISSUE TITLE
Missing seperator in notification

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#1029]
## Vespucci Version

Latest store beta

## Device (Manufacturer and Model)

New phone! :-) 
Motorola g7 power

## Android Version 

9

## Behaviour/Symptoms
After _fehlt_ should be a period and a space:
![rps20191031_063808_617](https://user-images.githubusercontent.com/2410353/67921752-0c8b2080-fba9-11e9-9de5-23c304cc0ce6.jpg)

**Comment by simonpoole** [comment]
Thanks for the report, Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/d1e50dbc6543e0dbdb16cc2de131c92551df41eb
