### ISSUE TITLE
Status NSI

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1034]
@matkoniecz what's the current status of the NSI, can I simply download the generated minified file now again, or do you believe the contents still need some preprocessing?

**Comment by matkoniecz** [comment]
Do you want to include `brand:wikidata` and `brand:wikipedia`  fields? If yes, then it should be fine to use.

If not I can make PR with versions that strips out this tags.

(my motivations for making PR without this fields were that (1) NSI was a bit unstable with some errors found (2) `brand:*` tags are unverifiable duing survey and anyway not worth adding in my opinion)

**Comment by simonpoole** [comment]
I'm a bit on the fence wrt the brand fields, but I can easily filter them out when reading the file, or get  rid of them in another way. The thing is iD will just add them in any case and it is questionable if going against the stream is worth it.

**Comment by matkoniecz** [comment]
In my case I am not against them to block them from appearing in OSM (I am even running in Poland community-approved bot mass adding `wikidata`, based on `wikipedia` tags).

I dislike adding them myself. In Vespucci it goes like this

1) I start adding name

2) I autocomplete name, other matching tags appear

3) but I have also `wikidata=QH7J8kHAHAHAHA` weird thing

I strongly dislike adding myself unverifiable alphanumeric gibberish, with Wikipedia tags I can at least look whatever article name makes sense (though sometimes it is not working anyway).

**Comment by simonpoole** [comment]
Resolved in https://github.com/MarcusWolschon/osmeditor4android/commit/a89c954d8bb07f4ebac106e4d686a144b7d47b4b
