### ISSUE TITLE
Different icon for OSM notes

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1038]
Description:
---

I think that having the same icon for both Osmose and OSM notes can be misleading the users. I think that the app could use the default red OSM icon for the notes.

Device info:
---
<table>
<tr><td>App version</td><td>14.0.3.0</td></tr>
<tr><td>App version code</td><td>1305</td></tr>
<tr><td>Android build version</td><td>V11.0.6.0.PEAMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180729.001</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>dipper</td></tr>
<tr><td>Device model</td><td>MI 8</td></tr>
<tr><td>Device product name</td><td>dipper</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mannivu</td></tr>
</table>

**Comment by Mannivu** [comment]
That's me, I couldn't send the bug using my Github account. However, I think that using the default icon (![Default icon](https://wiki.openstreetmap.org/w/images/d/d0/Open_note_marker.png)) it's easier to differentiate OSMose issues from OSM notes.

**Comment by simonpoole** [comment]
I hate pins (and the icon is GPLed or CC BY-SA 2.0). But there might be a suitable replacement that doesn't look awful.

**Comment by Mannivu** [comment]
How about something like this:
![NoteOSM](https://user-images.githubusercontent.com/42747216/68790895-7e06ac80-0648-11ea-98b6-eccd42395b41.png)

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/ff24f44ff13768bdb1898eef304c98bd43f494e3 adds a Note specific icon (might need some further work wrt visibility).
