### ISSUE TITLE
Doesn't download data 

### ISSUE THREAD

**Issue by bigfatfrog67** [MarcusWolschon/osmeditor4android#1039]
Description:
---

I can no longer download data, it just says it's downloading but doesn't. 

Device info:
---
<table>
<tr><td>App version</td><td>14.0.3.0</td></tr>
<tr><td>App version code</td><td>1305</td></tr>
<tr><td>Android build version</td><td>1877064199</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>48.1.A.2.112</td></tr>
<tr><td>Device brand</td><td>Sony</td></tr>
<tr><td>Device manufacturer</td><td>Sony</td></tr>
<tr><td>Device name</td><td>G3121</td></tr>
<tr><td>Device model</td><td>G3121</td></tr>
<tr><td>Device product name</td><td>G3121</td></tr>
<tr><td>Device hardware name</td><td>mt6757</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
Can you try to download and then send a manual crash dump from the debug menu?

Are you simply not seeing any data after the download is complete? Then you may have a filter turned on.

**Comment by bigfatfrog67** [comment]
It just shows its downloading but never finishes.

**Comment by simonpoole** [comment]
> 
> It just shows its downloading but never finishes.
The I would suggest sending a crash dump (you can click away the spinner). I would further suggest checking the API entry that is active.

**Comment by bigfatfrog67** [comment]
I have sent a crash dump, I think?

**Comment by bigfatfrog67** [comment]
How do I check the API?

**Comment by simonpoole** [comment]
> 
> How do I check the API?

layer button -> OpenStreetMap data entry -> menu -> info

That will display the API url in use.

**Comment by bigfatfrog67** [comment]
Https://API.Openstreetmap.Org/api/0.6/

Why is copy not enabled on those fields! 🙄

**Comment by bigfatfrog67** [comment]
All seemed normal and disabling tasks didn't help.
Anyway, I gave in and reinstalled it and that's fixed it!
Thanks for your help.

Jonathan
