### ISSUE TITLE
Add driveway like parking aisle, as an independent preset entry

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1040]
Description:
---

Currently searching driveway will find service road

It would be nice to have ability to apply driveway preset in one click, like it is possible with parking aisle

Device info:
---
<table>
<tr><td>App version</td><td>14.0.3.0</td></tr>
<tr><td>App version code</td><td>1305</td></tr>
<tr><td>Android build version</td><td>V10.0.15.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.15.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
Well there are multiple ways to skin a cat:

- it could be added to the default preset (wrong repo for that btw)
- you could simply create an additional preset for it
- or you could simply create a custom preset in vespucci  see http://vespucci.io/help/en/14.0.0%20Release%20notes/#on-the-fly-custom-presets

**Comment by simonpoole** [comment]
Closing as no response and in wrong repo.
