### ISSUE TITLE
Tag filters do not work

### ISSUE THREAD

**Issue by charlesmillet** [MarcusWolschon/osmeditor4android#1042]
## Vespucci Version
14.0.6

## Download source
f-droid

## Device (Manufacturer and Model)
Samsung Galaxy S7

## Android version
8.0.0

## Behaviour/Symptoms
Tag filters do not work. It seems objects in relation appear only if relation are displayed.

## How to recreate
I think any attempt to filter highways should recreate.

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
None

**Comment by simonpoole** [comment]
Thanks for the report, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/f604ab6440ca0a366b2b6336341bb2ccd702f9fe
