### ISSUE TITLE
Can't hide the keyboard on the Add Note to the map

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1044]
Description:
---

While adding a note I can't hidey keyboard meaning that i can't hit OK and send it

Device info:
---
<table>
<tr><td>App version</td><td>14.0.3.0</td></tr>
<tr><td>App version code</td><td>1305</td></tr>
<tr><td>Android build version</td><td>5899767</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.191105.003</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>sargo</td></tr>
<tr><td>Device model</td><td>Pixel 3a</td></tr>
<tr><td>Device product name</td><td>sargo</td></tr>
<tr><td>Device hardware name</td><td>sargo</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>pantufla</td></tr>
</table>

**Comment by simonpoole** [comment]
This is a Google bug, you should actually be able to dismiss the keyboard with the back button. The only workaround is to disable fullscreen mode. 

See http://vespucci.io/tutorials/faq/#fullscreen-mode-doesnt-work-properly

**Comment by simonpoole** [comment]
No response. Closing
