### ISSUE TITLE
Provide way to tag parcel drop/pickup vending machine

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1045]
Description:
---

Called pakstation in Germany (IIRC), paczkomat in Poland.

Device info:
---
<table>
<tr><td>App version</td><td>14.0.3.0</td></tr>
<tr><td>App version code</td><td>1305</td></tr>
<tr><td>Android build version</td><td>V10.0.15.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.15.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
Entering "packstation" (if the devices language is set to German) will return the amenity=vending_machine preset which has entries for vending=parcel_mail_in and vending=parcel_pickup

With other words it is completely possible to tag them with the current presets (and this is the wrong repo to ask for a specific one).

**Comment by matkoniecz** [comment]
> Entering "packstation" (if the devices language is set to German) will return the amenity=vending_machine preset which has entries for vending=parcel_mail_in and vending=parcel_pickup

What should be entered in English? "packstation" is not finding it and it seems that there is no better word in English - see https://en.wikipedia.org/wiki/Packstation

"paczkomat" is not finding it in Polish presets (I changed system language and searched again)

https://www.transifex.com/openstreetmap/presets/translate/#pl/presetpot/167831741?q=translated%3Ano - I went through the entire list (adding all what I could translate) and encountered no translatable string there that would be about this feature

**Comment by simonpoole** [comment]
> What should be entered in English? "packstation" is not finding it and it seems that there is no better word in English 

_Parcel_ will find the vending machine preset

**Comment by simonpoole** [comment]
Closing as in wrong repo in any case.
