### ISSUE TITLE
Can't log into GitHub to send bugs if 2FA active

### ISSUE THREAD

**Issue by Mannivu** [MarcusWolschon/osmeditor4android#1048]
## Vespucci Version
14.0.3

## Download source
Google Play Store

## Device (Manufacturer and Model)
Xiaomi Mi8

## Android Version 
MIUI Global 11.0.6 Stable (Android version: 9PKQ1.180729.001)

## Behaviour/Symptoms
Log in GitHub account gives an error if the User has the 2 Factor Authentication active

## How to recreate
Activate 2FA on GitHub and try to log in when sending a feedback.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
I think the app should open an external browser window to let the user insert the Authentication code or add an OAuth login button (I don't know if this could be implemented in Vespucci, but I've seen that multiple GitHub apps on Android such as [OpenHub](https://github.com/ThirtyDegreesRay/OpenHub), [FastHub ](https://github.com/k0shk0sh/FastHub) and [OctoDroid](https://github.com/slapperwan/gh4a) have the OAuth ability)

**Comment by simonpoole** [comment]
This is a limitation of the library we use to provide the functionality.
