### ISSUE TITLE
Fenêtres modales se ferment toutes seules

### ISSUE THREAD

**Issue by remontees** [MarcusWolschon/osmeditor4android#1049]
Description:
---

Lorsque j'ouvre une fenêtre modale type recherche, lorsque je masque le clavier avec le bouton en bas à gauche précédent, la fenêtre modale se ferme en même temps. 

Device info:
---
<table>
<tr><td>App version</td><td>14.0.7.0</td></tr>
<tr><td>App version code</td><td>1309</td></tr>
<tr><td>Android build version</td><td>V11.0.3.0.PEIMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180904.001</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>whyred</td></tr>
<tr><td>Device model</td><td>Redmi Note 5</td></tr>
<tr><td>Device product name</td><td>whyred</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
Hi, if I recreated the issue correctly it happens only with the result window?

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/08e6c75663fcfa8cd2e2c260a2bc4a7e7899d445 dismisses the keyboard automatically if the search was successful.
