### ISSUE TITLE
Recycling containers parameters

### ISSUE THREAD

**Issue by Mannivu** [MarcusWolschon/osmeditor4android#1050]
Description:
---

Recycling containers don't have opening time, but collection times. Also, I'm not sure if the lack of a "wheelchair access" should be a problem for a container.

Device info:
---
<table>
<tr><td>App version</td><td>14.0.3.0</td></tr>
<tr><td>App version code</td><td>1305</td></tr>
<tr><td>Android build version</td><td>V11.0.6.0.PEAMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180729.001</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>dipper</td></tr>
<tr><td>Device model</td><td>MI 8</td></tr>
<tr><td>Device product name</td><td>dipper</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
Wrong repo, but: while recycling containers in principle could have collection times I've never seen them signed at such a facility, opening hours are literally however the norm here.

Wheelchair access: there are containers where the openings are too high, or have other barriers that make them impossible to use in a wheelchair.

**Comment by Mannivu** [comment]
> opening hours are literally however the norm here
So you have containers that are not accessible at some time of the day?

> Wheelchair access: there are containers where the openings are too high, or have other barriers that make them impossible to use in a wheelchair.
This is why I wasn't sure about wheelchair access.

**Comment by simonpoole** [comment]
> 
> 
> > opening hours are literally however the norm here
> 
> So you have containers that are not accessible at some time of the day?
> 
Sure.

**Comment by Mannivu** [comment]
I'm sorry, maybe we are talking about different objects. I'm talking about this kind of containers:
![Japan recycling bins](https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Recycling_bins_Japan.jpg/640px-Recycling_bins_Japan.jpg) or this:
![Germany recycling bins](https://wiki.openstreetmap.org/w/images/8/80/Altglas.jpg)
In Italy (and I think everywhere else) they are found near the streets and are accessible any time of the day.

**Comment by simonpoole** [comment]
Did you actually look at your German example?

![container-example](https://user-images.githubusercontent.com/1011860/69497912-3272bf00-0ee2-11ea-8147-1a837bc5231d.jpg)

**Comment by Mannivu** [comment]
No, I didn't notice the advice in German. Sorry for wasting your time.

**Comment by simonpoole** [comment]
Well "advice" is being nice, if you throw in bottles here outside of hours it's ~200 Euros per offence.

**Comment by Mannivu** [comment]
Ugh, that's expensive.
