### ISSUE TITLE
Нет выхода из программы - «закрыть программу»

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1051]
Description:
---

Нет выхода из программы - «закрыть программу»

Device info:
---
<table>
<tr><td>App version</td><td>14.0.3.0</td></tr>
<tr><td>App version code</td><td>1305</td></tr>
<tr><td>Android build version</td><td>C579B101</td></tr>
<tr><td>Android release version</td><td>5.1</td></tr>
<tr><td>Android SDK version</td><td>22</td></tr>
<tr><td>Android build ID</td><td>TIT-U02C579B101</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWTIT-U6582</td></tr>
<tr><td>Device model</td><td>HUAWEI TIT-U02</td></tr>
<tr><td>Device product name</td><td>TIT-U02</td></tr>
<tr><td>Device hardware name</td><td>mt6582</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>buddisk559c017</td></tr>
</table>

**Comment by simonpoole** [comment]
Pressing the back button will show you a dialog asking you if you want to exit (or you can click the notification that indicates that Vespucci is running).
