### ISSUE TITLE
external location: doesn't work (perhaps only on newer Android)

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#1057]
## Vespucci Version

14.0.10

## Download source

f-droid

## Device (Manufacturer and Model)

pixel xl

## Android Version 

Lineage 15.1

## Behaviour/Symptoms

Configuring an alternate GPS source is confusing.  I am trying to use an external receiver which is receiving corrections over ntrip, currently in dgps mode, but which is in theory RTK-capable.   Without running adb, I can't tell what is going on.

I know my receiver is ok because I can telnet to the addr/port and see NMEA.   I also am running gpsd to display that (on a computer, not the phone).   I am not really sure I am applying the ntrip corrections, but I am seeing 1) sane positions and 2) the minor kind of wandering that is normal.  Everything is on the same LAN.  (Yes, I know I need to pivot to hotspot to make this work in the field, but am working on simpler first.)

## Expected Behaviour

I would like there to be some way to know if I have a current position or not.  I see the position icon, but it isn't moving.

It seems a restart is required after changing from internal to tcp.  I guessed this but didn't get a notification or see it in the help.

## How to recreate

Set up a TCP NMEA  server on another host on the LAN.  Configure TCP client to it.  Guess that it isn't being used and restart.   Enable logging and notice that you don't get trackpoints.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information

I'm not sure exactly what to suggest, but I'll try anyway:
 * Make the position red instead of blue if it's more than 5s old
 * display a notification if the configured connection fails, and leave it there until dismissed or success
 * display a notification if a restart is needed because of config change

**Comment by gdt** [comment]
I should say that my host:port looks like "192.168.100.130:1234" (with different values, but it's an RFC1918 numeric address).   I was able to "telnet 192.168.100.130:1234" from the phone (termux) and see NMEA.    I also noticed a toast about a null value on startup.   (I wonder if there is resolution of name but not handling of numeric addresses.  I also find that foo.local, which works from another system, does not work on the phone.)

**Comment by simonpoole** [comment]
Could you exit the app completely and then as first action go to the debugging page and send a report (with some kind of indication that it relates to this issue)? If we're lucky there should be enough in hte logfile to determine what is going wrong. I have to admit that the code has gone a bit stale, but I wouldn't be aware of any problems.

**Comment by gdt** [comment]
I have run adb and read the code and figured it out, I think.  The Socket() constructor is called and it is documented to take a name, not an IP address.   I then get in the log
```
12-16 12:18:18.572 13749 22263 E NmeaTcpClient: failed to open/read 192.168.100.131:1958
12-16 12:18:18.572 13749 22263 E NmeaTcpClient: java.lang.NullPointerException: Attempt to invoke interface method 'void android.location.GpsStatus$NmeaListener.onNmeaReceived(long, java.lang.String)' on a null \
object reference
12-16 12:18:18.572 13749 22263 E NmeaTcpClient:         at de.blau.android.services.a.g.run(NmeaTcpClient.java:57)
12-16 12:18:18.572 13749 22263 E NmeaTcpClient:         at java.lang.Thread.run(Thread.java:764
```

**Comment by gdt** [comment]
What I am trying to do is hike with my phone and an external GPS receiver, in this case an Emlid Reach RTK.  This GPSr is a computer with a ublox chip, and it has firmware to connect to an NTRIP server and get corrections, for DGPS or for RTK.   My plan is to use my phone's hotspot to connect the GPSr over wifi, and then have vespucci connect to obtain NMEA over TCP.   I am hoping that the hotspot will assign the same IP address to the GPSr every time.   Obviously there's a lot of things to get through, but I'm starting simpler.

What I don't understand is how people would use this feature with a host name, as opposed to an IP address, since it seems useful to get better GPS accuracy when one is out and about.   Perhaps there is some way to have the zeroconf-style name resolvable, but that didn't seem to work.

**Comment by simonpoole** [comment]
For whatever reason the crash dump doesn't seem to have made it to the server yet (the library does queue these so maybe it is just a question of not having connectivity). In any case I should have some time tomorrow to investigate.

**Comment by simonpoole** [comment]
Just some short feedback, it clearly isn't an issue with hostname vs. ip address, there is something going wrong when reading. I need to replicate your setup quickly here for testing though (most of what I did when the feature was introduced was with RTKLIB on tte device itself).

**Comment by simonpoole** [comment]
Looking at the code jogged my mind and the reason for the issue is clear. For Android N google for no apparent reason deprecated one of the interfaces we use internally to support this, and the code to support Android N and later simply hasn't been written, in the process of doing that now.

**Comment by simonpoole** [comment]
So support for Android N and higher added in https://github.com/MarcusWolschon/osmeditor4android/commit/a8b11d374d7e32a7714c3c06909039d5a815974d additional I build in a small hack so that if it detects gpsd as server it will attempt to switch it to NMEA output (without that it wouldn't have worked in your setup in any case). 

As to user feedback if something goes wrong when connecting you should always get an error message, but maybe some kind of further user feedback could make sense.

I'm leaving this issue open for now for further input etc.

**Comment by simonpoole** [comment]
Stop the press :-). I found another issue that crept in when the network location support was added, which essentially led to the apps idea of the current location being split and the "follow GPS" button not working with an external source. Track recording should still work fine with 14.0.11 however you need to use the "goto current location" to actually center on the externally provided position.

**Comment by gdt** [comment]
Thanks very much for looking into this.  I will test when it hits an f-droid release or I manage to build it, whichever comes first.

I am using a device which sends NMEA on a TCP port, which is not gpsd (it is RTKLIB based).  But that sounds good about flipping gpsd to NMEA mode, since I may try that.

**Comment by gdt** [comment]
I built git master about 12h ago and that works.  I configured to use a tcp server, <lanaddr>:1958, and when backing out of the location config got a  toast that it was being used.   I am seeing a tracklog that matches what's coming out of the RTK device, wandering between fix/float 9indoors), and the phone's GPS is off.

Thanks very much for fixing the issues and also for making this switchable without a restart.

**Comment by simonpoole** [comment]
Just a note wrt building yourself: the relevant commits were cherry picked on to the 14.0-MAINT branch which is where currently releases are tagged. master, while I try to keep it "deployable" comes without any guarantees and is what is 14.1 will eventually be built from.
