### ISSUE TITLE
GPX track recording interacts badly with application being killed - persist track state

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#1058]
(Up-to-date vespucci from f-droid, but unless I'm confused this is a feature request.)

I was recording a track while walking, and made the mistake of opening an unrelated application that I believe to be very piggy with memory, such that the OS often stops other programs when the piggy one runs.   When I returned to Vespucci it gave the startup screen and my track was apparently gone.

I haven't read the code, but I wonder if the current track, as well as the notion that it's being recorded, should be persisted within private storage, either always, or as part of what I hope is the window the app has to save when the OS is telling it to stop.

**Comment by simonpoole** [comment]
It already does all of that (and has done that way before I was engaged in the project so literally years ago), the only way it wouldn't save is if you have an aggressive app killer installed, normal pausing, removing from memory and restarting should just work as expected (this happens all the time even if the app in the end is not actually destroyed).

With other words this probably needs a bit of debugging too.

**Comment by gdt** [comment]
Thanks.  I will see if I can figure this out.   This is Lineage, with no app killers.   I do have "long press on back to kill" turned on, but I am 98% sure that I just hit home and opened the pesky app.  (I am guessing from your comment that "long press to kill" is like "kill -9" and thus the saving code won't run, and that's not a bug.)

**Comment by gdt** [comment]
I'm going to declare that it is more likely than not that this is an issue with me accidentally long-pushing back while hiking.  I'll re-open if I have real evidence.
