### ISSUE TITLE
Vespucci adds preset data without possibility to delete

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#1059]
Vespucci Version
14.0.9

## Download source
play store beta

## Device (Manufacturer and Model)
Motorola G7 Power 

## Android Version 
9

## Behaviour/Symptoms
Add node
swipe right to details
add `amenity=bank` via keyboard
save
reopen

## Expected Behaviour
`amenity=bank` should be the only osm key.
`atm=yes` is added (on reopen, seen the bug on an existing bank)

I am not able to delete `atm=yes` (Perhaps yes, but I can not check withhin vespucci, as it is added on edit.

Probably this is a preset issue, but IMO viewing an element should never add key=values. With the ABC+ this is desputable.

**Comment by simonpoole** [comment]
This is a preset issue as you suspect, wrt auto-applying presets, see the release notes for 14.0 http://vespucci.io/help/en/14.0.0%20Release%20notes/#automatically-apply-preset-when-property-editor-is-invoked (the property editor is an editor not a pure tag viewer, you can use the info dialog for that).

**Comment by HolgerJeromin** [comment]
I wanted to take a peek what features are tagged at a bank 200 meters away from me.
Should I tag yes or no? I have no idea! 
And further more:
Who tells a vespucci user, that he is not allowed to open the editor if he has no possibility to survey the feature?
No information is shown that and what tag is set. 

> Automatically applying the preset has some dangers as, depending on the preset, existing values could be overwritten, if that happens a warning will be shown.

Tagging wrong values without knowing that I will upload unknown data reduced the osm data quality.

**Comment by simonpoole** [comment]
You don't -have- to save the edits in the property editor (I'm changing
the behaviour slightly anyway so this wont be an issue)..

Simon

Am 16.12.2019 um 21:51 schrieb Holger Jeromin:

**Comment by simonpoole** [comment]
Behaviour changed in https://github.com/MarcusWolschon/osmeditor4android/commit/8b084f9119f1542dcf630fa6cf052df0bf22e3e1
