### ISSUE TITLE
Aller à ma position ne fonctionne pas

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1060]
Description:
---

Cliquer sur aller à ma position

Device info:
---
<table>
<tr><td>App version</td><td>14.0.3.0</td></tr>
<tr><td>App version code</td><td>1305</td></tr>
<tr><td>Android build version</td><td>00WW_4_08B</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>00WW_4_08B</td></tr>
<tr><td>Device brand</td><td>Nokia</td></tr>
<tr><td>Device manufacturer</td><td>HMD Global</td></tr>
<tr><td>Device name</td><td>CTL_sprout</td></tr>
<tr><td>Device model</td><td>Nokia 7.1</td></tr>
<tr><td>Device product name</td><td>Crystal_00WW</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>jseigneuret</td></tr>
</table>

**Comment by simonpoole** [comment]
As this in general works you will need to provide more information (did you actually already have a GPS fix)?

**Comment by simonpoole** [comment]
No response, closing.
