### ISSUE TITLE
Roof shape icon remains after clearing value field

### ISSUE THREAD

**Issue by Mannivu** [MarcusWolschon/osmeditor4android#1063]
Description:
---

I've noticed that if you "clean" the value of the roof shape, the little roof image remains in the field instead of disappearing.

![With roof shape](https://i.imgur.com/AlPwxGZ.jpg)

![Without roof shape](https://i.imgur.com/JU9VUJI.jpg)

Device info:
---
<table>
<tr><td>App version</td><td>14.0.9.0</td></tr>
<tr><td>App version code</td><td>1311</td></tr>
<tr><td>Android build version</td><td>V11.0.6.0.PEAMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180729.001</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>dipper</td></tr>
<tr><td>Device model</td><td>MI 8</td></tr>
<tr><td>Device product name</td><td>dipper</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
Thanks for the report.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/ba3513bbd9fb177c240bb7e69f3cc0910fe3cb66
