### ISSUE TITLE
Github API to be deprecated soon

### ISSUE THREAD

**Issue by Mannivu** [MarcusWolschon/osmeditor4android#1064]
After sending my latest issue directly from the app, I've got an email from GitHub stating:

> You recently used a password to access an endpoint through the GitHub API using GitHubJava/2.1.5. We will deprecate basic authentication using password to this endpoint soon: https://api.github.com/repositories/32623844/issues
We recommend using a personal access token (PAT) with the appropriate scope to access this endpoint instead. Visit https://github.com/settings/tokens for more information.

**Comment by simonpoole** [comment]
There's probably no real way to fix this short term outside of using the pseudo-anonymous access that the UI currently provides.

**Comment by simonpoole** [comment]
Using login/password disabled in https://github.com/MarcusWolschon/osmeditor4android/commit/c1b066a97d2da9fbdd754e856c5be1f743e01c5e (use of the feedback activity can be disabled and the github website be used instead).
