### ISSUE TITLE
Feature: disable automatic phone formatting

### ISSUE THREAD

**Issue by fansanelli** [MarcusWolschon/osmeditor4android#1065]
## Vespucci Version
Vespucci 14.0.9

## Download source
google play store

## Device (Manufacturer and Model)
LG G6

## Android Version 
Stock android 9 (no root)

## Behaviour/Symptoms
Vespucci auto-format phone numbers on tag editor opening. I'd like to be able to skip this step

## Expected Behaviour
Nothing

## How to recreate
Insert a phone number longer than 13 numbers:
+39 0171 1234567
Will become:
+39 0171 123 4567

## Crash dump submitted (no or yes + date)
No

**Comment by simonpoole** [comment]
Adding this as an option is obviously possible, the question is more what is the issue with the formatting (this uses a library that is fairly good in replicating the formatting in use for a specific country).

**Comment by fansanelli** [comment]
Thanks @simonpoole for the prompt reply. Afaict is not correct in Italy current behaviour. So I prefer to apply it manually

**Comment by simonpoole** [comment]
Independent of an option to disable the functionality, this would be an upstream issue and should be reported at https://github.com/google/libphonenumber (we are actually using https://github.com/MichaelRocks/libphonenumber-android so the issue may be fixed in the original already).

**Comment by fansanelli** [comment]
Well, until it's not fixed and pulled in, it's better to allow users to disable the feature

**Comment by simonpoole** [comment]
Btw what would the correct formatting be in your opinion and would you consider what I'd does wrong too?

**Comment by fansanelli** [comment]
Hi Simon,

Please see:

https://issuetracker.google.com/146753418

I tried to ask to libphone maintainer why the space has been added... They resolved as won't fix without actually explain anything...

**Comment by simonpoole** [comment]
Preference added in https://github.com/MarcusWolschon/osmeditor4android/commit/3f595d752ff6aa1f2cd4c26374cbbc0fe618ea02 Note btw that we use the "INTERNATIONAL" format in the library not E164 (but that would be an even better reason that it should work for Italy).

**Comment by fansanelli** [comment]
Thank you for your time and consideration

**Comment by simonpoole** [comment]
Note that the fix is in master wich will become 14.1 sometime (it is running a bit late compared to schedule but hopefully latest next month).
