### ISSUE TITLE
Term divison "Speciality" for translation

### ISSUE THREAD

**Issue by debyos** [MarcusWolschon/osmeditor4android#1066]
Hi,

please, make two separate entries for "[Speciality](https://www.transifex.com/openstreetmap/presets/translate/#hu/presetpot/123477725)", i.e. one for healthcare and another for butcher meat because in Hungarian they are very different.
Thank you!

Gábor

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/181b7ce11a598e7fe46df691087570bebfbf8b2b

Thanks! Please report issues in the preset repo instead of here, it makes tracking things much easier.
