### ISSUE TITLE
Wayside shrines should not be armenian apostolic by default 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1067]
Description:
---

To reproduce: create node, search "shrine" in presets server Wayside Shrine

Note that denomination is Armenian Apostolic, what seems to not be a good default - I would expect no set denomination

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>14.0.9.0</td></tr>
<tr><td>App version code</td><td>1311</td></tr>
<tr><td>Android build version</td><td>V10.0.17.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.17.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
They aren't (the actual preset default is catholic), Armenian apostolic isn't even a denomination value in the preset, Vespucci is simply using what you last used as default, which makes complete sense in this case (as in the same area they will tend to be the same).

**Comment by matkoniecz** [comment]
In my case I entered tag derail and removed denomination tag hoping that it will be remembered.

Next wayside shrine also got this denomination.

**Comment by simonpoole** [comment]
Why would that change things? Last used values are stored on a preset by preset base, not using a tag will simply have no effect as expected. To get a different value you simply need to set it, and the next time you will get that one, and so one.

**Comment by matkoniecz** [comment]
> Why would that change things?

I expected that deleting tag and leaving this value empty will be remembered as "no value used for this preset"

> To get a different value you simply need to set it, and the next time you will get that one, and so one.

Not so useful in area with a more complex history resulting in leaving `denomination` tag empty.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/commit/27c3eebf84482de542be2b2008a956fb5dd3b5c1
