### ISSUE TITLE
"back" button in relation creation menu is weird

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1068]
Description:
---

I would expect back button (top left screen corner) to cancel creating relation rather than to create it.

Ideas: replace back icon by something else or add button with more obvious meaning so people new to this interface will be less confused.

@matkoniecz

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>14.0.9.0</td></tr>
<tr><td>App version code</td><td>1311</td></tr>
<tr><td>Android build version</td><td>V10.0.17.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.17.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
The "arrow" is the standard Android button for finishing/exiting an action mode not the "Back" button.

**Comment by matkoniecz** [comment]
In this case it probably can be closed. Though for me it still feels like exitt/cancel.

Maybe because that is one of stages in relation creation?

**Comment by simonpoole** [comment]
So I had another look at this.

My point was not so much that I disagree with that the arrow is weird in these situations, it is just that there is no API provided way of changing it. 

I've just experimented with using reflection to access the field and that seems to at least work for the current version of the support lib., but naturally this implies that it might break on any platform/support lib change.

**Comment by simonpoole** [comment]
This was addressed in https://github.com/MarcusWolschon/osmeditor4android/pull/1257
