### ISSUE TITLE
Make Vespucci available in a location where it won’t be censored

### ISSUE THREAD

**Issue by AndrewHain** [MarcusWolschon/osmeditor4android#1070]
F-droid has [removed some social network apps](https://gitlab.com/fdroid/fdroiddata/issues/1861) from their repository. ([complaint](https://gitlab.com/fdroid/fdroiddata/issues/1886)) It is unclear whether proprietary platforms are any better. Relying on platforms that censor content risks demands on editing presets that would make Vespucci subject to control from outside the OSM community.

**Comment by simonpoole** [comment]
The current play store release is, signed with the same key, always available from this repository too.
