### ISSUE TITLE
add way to ask about current osm data layer

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#1075]
(This is a feature request.)

There is download and upload, but I have not figured out how to ask about the current osm data layer.  I want to know how many items are uploadable, and how many items exist that are simply copies of data from the OSM API (or how many total).   I would guess this might be a count of relations/ways/nodes.

Perhaps it's just me, and perhaps others want this.

**Comment by simonpoole** [comment]
A workaround for this is currently to look at the debug page. But this is actually something that should be included on the data layer info display (I actually thought I had done that, but seems not).

**Comment by simonpoole** [comment]
Added to info dialog in https://github.com/MarcusWolschon/osmeditor4android/commit/68b3a155dbe8f4125bb203d68fced6227e27f446
