### ISSUE TITLE
Crash on loss of external TCP server for location

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#1076]
## Vespucci Version
14.1.0.1

## Download source
f-droid

## Device (Manufacturer and Model)
google pixel xl

## Android Version 
lineage 15.1 (8.1)

## Behaviour/Symptoms
When using external NMEA from a tcp server, shutting down the tcp server causes vespucci to crash.   I probably was not recording a track, but probably did have 'follow' enabled.
I got a prompt about sending a report, and that request-for-prompt seemed to be stuck in an infinite loop until I long-pressed back to hard kill vespucci.

## Expected Behaviour
I get a useful message that the tcp server has gone away.

## How to recreate
Set up with an external TCP server.   enable track recording, and follow.  walk around for a few hours.  stop track, export it.  export changes (which were not uploaded).   Then click 'stop' on the external RTK gui which I think closes the TCP connection.   This has happened multiple times to me.

## Crash dump submitted (no or yes + date)
I think so.   2019-01-07  approximately 1930UTC.

**Comment by simonpoole** [comment]
Somehow had brain in neutral when I coded the changes last time, crash fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/6ff8e33287e25dd31edab87833da4bee3d8ff624 I've further added a disconnect message. You should simply be able to build from master to replace your current version.

**Comment by simonpoole** [comment]
Note I reverted an inadvertent change to the saved data format that caused a crash between 14.0 and this, with other words you will need to clean out any data you have in memory before installing a fresh build.
