### ISSUE TITLE
convey whether location is currently working

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#1077]
(This is a feature request.)

I am using external tcpserver location (to a computer on my phone's hotspot running rtklib), and this generally works (thanks for the earlier fixes!).

However, sometimes i have problems.  One is that if I start vespucci and then start the rtklib computer, it doesn't seem to connect, but it's really hard to tell.  The other is that i have no confidence sometimes that it's still working, until I move enough.

So, I'd like to have a way to show the status.   I'm going to express this in color, realizing that color has issues, but there's still the list of statuses.

I am going to assume that people want frequent updates and that position sources will report at 1 Hz or better.

  * black: no connection to tcpserver, or some complete internal API failure
  * red: no fix for 15s (perhaps due to loss of fix from GPS even if plumbing is ok)
  * orange: no fix for 5s
  * green: no fix for 2s
  * blue: fix within 2s

(Perhaps also a  persistent notification is in order if the connection to the provider (tcp server) is down, with a retry button, but perhaps not.)

**Comment by simonpoole** [comment]
This needs a bit of thinking as it impacts use of the internal GPS source too (though providing feedback wrt fix status in general is good).

**Comment by simonpoole** [comment]
Stale location indication added in https://github.com/MarcusWolschon/osmeditor4android/commit/5b42b24ce5ebf64ac9d5c0962520daf1c8d5965d (not with all the bells an whistles you suggested though).
