### ISSUE TITLE
Add "departures_board" key to platforms or stations

### ISSUE THREAD

**Issue by Mannivu** [MarcusWolschon/osmeditor4android#1078]
The key `departures_board` is a "[de facto](https://wiki.openstreetmap.org/wiki/Key:departures_board)" key for public_transport=platform and public_transport=station, so it would be useful to have it while editing platforms or stations.

**Comment by simonpoole** [comment]
This is the wrong repo for requesting changes to the presets (as pointed in in multiple places) could you open the issue here https://github.com/simonpoole/beautified-JOSM-preset so that it doesn't get lost? Unluckily I can't more issues from this repo there. 

Thanks

**Comment by Mannivu** [comment]
Sure no problem. I've opened https://github.com/simonpoole/beautified-JOSM-preset/issues/175
