### ISSUE TITLE
Ability to force Android navigation bar to always show

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1079]
Description:
---

Switching to and from Vespucci is annoying because I have to swipe up the navigation bar. So it'd prefer it to be always on screen like in many other apps

Device info:
---
<table>
<tr><td>App version</td><td>14.0.9.0</td></tr>
<tr><td>App version code</td><td>1311</td></tr>
<tr><td>Android build version</td><td>6031801</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QQ1A.200105.002</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>walleye</td></tr>
<tr><td>Device model</td><td>Pixel 2</td></tr>
<tr><td>Device product name</td><td>walleye</td></tr>
<tr><td>Device hardware name</td><td>walleye</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Thibaultmol</td></tr>
</table>

**Comment by simonpoole** [comment]
See http://vespucci.io/tutorials/faq/#fullscreen-mode-doesnt-work-properly

**Comment by thibaultmol** [comment]
I tried that session, but only realised now that I had to restart the app
for it to take affect. Maybe add a prompt in the app about it?

**Comment by simonpoole** [comment]
The on-device and online help does mention this: http://vespucci.io/help/en/Advanced%20preferences/#user-interface-settings in any case I've aded a toast now https://github.com/MarcusWolschon/osmeditor4android/commit/c11bba54063db26a6c4f0fa9d542f44c9ac2afb1
