### ISSUE TITLE
Map views 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1080]
Description:
---

Where is the option to change the map? I need the satellite view and can't find it anywhere. 

Device info:
---
<table>
<tr><td>App version</td><td>14.0.9.0</td></tr>
<tr><td>App version code</td><td>1311</td></tr>
<tr><td>Android build version</td><td>1</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>ODN27.76-12-30-8-1</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>addison</td></tr>
<tr><td>Device model</td><td>XT1635-01</td></tr>
<tr><td>Device product name</td><td>addison_verizon</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>MountainAddict</td></tr>
</table>

**Comment by simonpoole** [comment]
See http://vespucci.io/help/en/Main%20map%20display/#layer-control or the corresponding on device help.
