### ISSUE TITLE
Disambiguation dialog does not update unless one reselects

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#1082]
Description:
---

1. Select a node near other nodes at a given zoom level
2. Try to merge nodes to get the disambiguation dialog. If your choice isn't offered because of the zoom level...
3. Without deselecting the node, zoom in further.
4. Try joining again. The options aren't updated to reflect the zoom - you have to deselect and select again.

Device info:
---
<table>
<tr><td>App version</td><td>14.0.14.0</td></tr>
<tr><td>App version code</td><td>1316</td></tr>
<tr><td>Android build version</td><td>00WW_3_54Q</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>00WW_3_54Q</td></tr>
<tr><td>Device brand</td><td>Nokia</td></tr>
<tr><td>Device manufacturer</td><td>HMD Global</td></tr>
<tr><td>Device name</td><td>PL2_sprout</td></tr>
<tr><td>Device model</td><td>Nokia 6.1</td></tr>
<tr><td>Device product name</td><td>Plate2_00WW</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
The actual issue is that the action mode was not being invalidated on zoom, which goes back to before I had anything to do with the app, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/e8e10d86fe9e14935e250a0c4a7b04b281c8cad6
