### ISSUE TITLE
No background settings

### ISSUE THREAD

**Issue by amilopowers** [MarcusWolschon/osmeditor4android#1083]
## Vespucci Version
 14.0.9

## Download source
  Play Store

## Device (Manufacturer and Model)
 Motorola One Hyper

## Android Version 
 10

## Behaviour/Symptoms
There are no options to change background imagery such as satellite images.

**Comment by simonpoole** [comment]
The selection of background imagery etc was moved to the layer control in version 11 see http://vespucci.io/help/en/11.0.0%20Release%20notes/, http://vespucci.io/help/en/Introduction/#customizing-vespucci and http://vespucci.io/help/en/Main%20map%20display/#layer-control

**Comment by amilopowers** [comment]
Okay thanks. Then I have to find an old version. Very bad choice you made here as settings are not intuitive find and use at all.

**Comment by amilopowers** [comment]
And by the way they do not poad in my case.

**Comment by simonpoole** [comment]
?

You are the first to find that changing layers in the layer control is not obvious, the added advantage that it now possible to change to a previously used layer with two clicks.

**Comment by amilopowers** [comment]
Yes you are right I am sure. For everyone else here is an old APK: https://vespucci.de.uptodown.com/android/download/1865438

**Comment by simonpoole** [comment]
Note you shouldn't be using any version prior to 13.02  (with exception of 12.1.9) due to relation handling issues.

**Comment by amilopowers** [comment]
Okey here are versions before 14 with the old background menu: https://m.apkpure.com/de/vespucci-an-osm-editor/de.blau.android/versions

**Comment by simonpoole** [comment]
Note: all layer related settings with one exception have been moved to the layer control, with one exception (adding of custom layers), which will be moved in a future version. The whole point of this is to have all setting related to a specific layer in one place and not spread out over multiple locations.
