### ISSUE TITLE
Missing new road from Kabugao to Calanasan

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1084]
Description:
---

There is a new build road from Calanasan to Kabugao, tracks are in the row datas, its two way, concride, for motobike and car, maybe trucks too.
Maps and Earth show the road, there are new build bridges and tracks was made and uploaded.
please check and complete !!!
This is saving 1/2 day driving. 

Device info:
---
<table>
<tr><td>App version</td><td>14.0.9.0</td></tr>
<tr><td>App version code</td><td>1311</td></tr>
<tr><td>Android build version</td><td>G390FXXU4CSF9</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.G390FXXU4CSF9</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>xcover4lte</td></tr>
<tr><td>Device model</td><td>SM-G390F</td></tr>
<tr><td>Device product name</td><td>xcover4ltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7570</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Palawan-Taucher</td></tr>
</table>

**Comment by simonpoole** [comment]
Hi, I'm not quite sure what you want. I had a quick look and it seems as if there is quite a significant stretch which has two roads in parallel now which doesn't look correct.
