### ISSUE TITLE
Blue/blueish/brown would be nice for wetlands instead of generic green

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1086]
Description:
---

Obviously blue should not be as strong as for for water and waterways

@matkoniecz - see #895 - appears to be a good first issue PR

Device info:
---
<table>
<tr><td>App version</td><td>14.0.9.0</td></tr>
<tr><td>App version code</td><td>1311</td></tr>
<tr><td>Android build version</td><td>V10.0.18.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.18.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
It would likely make more sense to use a pattern for filling such areas see https://developer.android.com/reference/android/graphics/BitmapShader

**Comment by simonpoole** [comment]
@matkoniecz this is getting stale.

**Comment by matkoniecz** [comment]
I send #1521 to check is this kind of contribution is welcome
