### ISSUE TITLE
Issues in layer menu with custom backgrounds

### ISSUE THREAD

**Issue by mstock** [MarcusWolschon/osmeditor4android#1088]
## Vespucci Version
14.0.14, self-compiled, also had this in 14.0.13 and likely a related issue on an even older version on a different device, and not with custom backgrounds.

## Download source
Private f-droid repo where I upload self-compiled `.apk` files.

## Device (Manufacturer and Model)
FairPhone2

## Android Version 
FairPhone Open 7.1.2

## Behaviour/Symptoms

1. Overlay menu item may disappear from layer menu and doesn't even show up under the `+`
2. Changing to a different overlay layer may change background layer

## Expected Behaviour

1. Menu item doesn't disappear or can be added again
2. Changing an overlay layer doesn't change the background layer

## How to recreate

1. 
    - Add custom background to Vespucci, eg. via an MBTiles file
    - Mark it as 'Overlay' layer
    - Open layer menu, select this new layer as overlay, close menu
    - Delete the custom background in the settings
    - When opening the layer menu now, the overlay layer item should have disappeared, and is not even visible in the `+` submenu
    - This can be 'fixed' by adding the same MBTiles file again (the 'Overlay' layer checkbox value does not even matter in this case, the item appears again even if the layer is not marked as overlay)
1. 
    - Based on the above state, make sure the custom background layer is not marked as 'Overlay'
    - Open layer menu
    - The custom background layer should now still be selected as overlay layer
    - Select a different overlay layer
    - Open selection again, the custom background layer should still be in there
    - Select the custom background layer as overlay again, this should leave the old overlay setting in effect, but change the background layer setting instead. However, the same effect can also be triggered by marking another custom background as 'Overlay' and tapping 'Save and use', and then deleting the 'Overlay' flag again and going through the above steps, so this is not necessarily directly related to the first issue.

## Crash dump submitted (no or yes + date)
No, there was no crash, and I did not see anything interesting in the `logcat` output, either.

## Any other potentially relevant information
The MBTiles files were generated by myself.

**Comment by simonpoole** [comment]
Fixed with https://github.com/MarcusWolschon/osmeditor4android/commit/733a0a7cb7024906a49adc379dcc416e83cf82f0 and https://github.com/MarcusWolschon/osmeditor4android/commit/9091151607493191ec0ff9b7236e9f66ae922b95
