### ISSUE TITLE
Resurvey validator: Days entered with keyboard aren't saved

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1094]
## Vespucci Version
14.0.15

## Download source
f-droid

## Device (Manufacturer and Model)
Samsung Galaxy A7 (2018)

## Android Version 
Android 9

## Behaviour/Symptoms
When editing the validator options and changing the number of days when data should be marked as old, numbers entered with the keyboard are not saved. Only numbers entered with the plus/minus buttons are.

## Expected Behaviour
Both editing options should work.

## How to recreate
Enter the resurvey validator options. Open one item (e.g. amenity=bar). Change the number of days with the keyboard. Press 'save'.

## Crash dump submitted (no or yes + date)
No.

**Comment by simonpoole** [comment]
This is an upstream issue see https://github.com/simonpoole/NumberPicker/issues/1 (and was already present in the original component).

**Comment by simonpoole** [comment]
Updated version of the widget was added in https://github.com/MarcusWolschon/osmeditor4android/commit/31084a93f883a2d2276bee733e09a5b0f4dd410a
