### ISSUE TITLE
Add some kind of location history

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1103]
Maybe add some kind of location history, allowing the user to fly/zip/zoom back to a previous location he was "working on all last week" without needing to pan and zoom in all over again as if it was some faraway island he had never visited.

**Comment by simonpoole** [comment]
There is already a feature to go back to the last position that was edited, and there is https://github.com/MarcusWolschon/osmeditor4android/issues/951 that will expand it in roughly the way you will suggest, planned for 15.0 (it was actually originally intended for 14.1 but time ran out).
