### ISSUE TITLE
 The Help menu is gray

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1104]
For some reason the help menu has a gray background, making it more difficult to read than if it had a white background.
Current Google Play beta version.

**Comment by HolgerJeromin** [comment]
What is your device, android version?
Can you add a screenshot?

**Comment by simonpoole** [comment]
IIRC leaving the drawer completely white was a bit confusing. But we can definitely make the drawer a lighter color.

**Comment by simonpoole** [comment]
Addressed in https://github.com/MarcusWolschon/osmeditor4android/issues/1104

**Comment by jidanni** [comment]
> Addressed in #1104

But that is just this issue.

**Comment by jidanni** [comment]
You mean addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/6e9019822b37d50b4eedf1e61ff44a32b008bdc4
