### ISSUE TITLE
vespucci.io/tutorials/faq menu too wide

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1105]
Here I have  pinched the screen in order to show you  how the menu is too wide  compared to the column of text containing the FAQ, on http://vespucci.io/tutorials/faq .
![Screenshot_20200227-163735](https://user-images.githubusercontent.com/1230959/75426639-0b63d780-5980-11ea-8ee1-aa8a9a965a90.jpg)

**Comment by jidanni** [comment]
The problem is, the user cannot find the way to get back to the home screen of the website. Because if he scrolls all the way up to the top he won't see the three bars for the menu, because they were too far over to the right. Off the screen.

**Comment by simonpoole** [comment]
This is likely an issue with the style provided with the system we use for generating the website (https://www.mkdocs.org/).

**Comment by simonpoole** [comment]
This was actually far simpler than expected there was simply a long unbreakable string (a directory path) that was causing the issue, reformulating the text made it a bit shorter and made the problem go away (naturally latent it is still there and IMHO mkdocs should allow horizontal scrolling in this case).
