### ISSUE TITLE
 add query only mode

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1106]
Add a mode, call it query only mode, that although the screen stays locked, the user can still nonetheless tap features and the complete details of the features will be available for him to see, without him having to worry about messing up the map.

**Comment by jidanni** [comment]
Currently to see all details of any feature he must be in unlocked editing mode.

**Comment by jidanni** [comment]
The idea is, with one tap, I could be able to find out what the reference number of a telephone pole is (ref=WXY123), therefore upon tapping a node I don't want to see the node number, I instead want to see all the tags. That would be a great help for a new query only mode.

**Comment by simonpoole** [comment]
This already exists, long press on the object when the screen is locked, see http://vespucci.io/help/en/Introduction/  "Vespucci in locked mode"

**Comment by jidanni** [comment]
I see. okay, then perhaps next to the words unlock to edit, please add: long press for details.
![Screenshot_20200229-081126_copy_270x480](https://user-images.githubusercontent.com/1230959/75596675-8d611700-5acc-11ea-94e1-71a1815fc6b6.jpg)
