### ISSUE TITLE
FAQ item: is screen delay normal?

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1107]
(Just curious if I am seeing normal behavior:)
Download say a square kilometer or two of some city.
Now in locked or unlocked mode, put your finger on some empty spot, say a city park.
Now drag you finger in some direction.

Does the whole map move smoothly along? Or does it have trouble catching up and needs a second or two?

Also for zooming + and -. Does the map zoom right away, or is there delay?

I'm talking about using the latest version of everything, and top of the line cellphones.

Perhaps mention in some FAQ if such delay is expected.

**Comment by jidanni** [comment]
One side effect of such delay is the user thinking his actions were not read by the program, only to suddenly find that they were indeed read, and now he is zoomed much more than he expected.

**Comment by simonpoole** [comment]
It is not buttery smooth and that shouldn't be expected (just as it isn't with iD and JOSM), as editors need to construct and render the element geometries on the fly. 

In general it depends on amount of data downloaded, number of active layers and what else is turned on or off (for example areas with a large number of multi-polygons will be slow to render, but you can use a style without MP-rendering if necessary). Definitely in a highly detailed area 1km^2 is a lot of data and is going to be slow when zoomed out (try the same area in iD as a comparision). 

Without more details (output on the debug screen for example), a video etc. it isn't really possible to say if you are seeing normal or not.

**Comment by jidanni** [comment]
OK! I thought maybe it was just me.
Yes, iD is slow for me too.
Well on cellphones I don't know of any other slow program... so maybe a FAQ is needed. But I am the only person who asked, so no F of FAQ yet.
As far as overzooming goes, maybe there should be a default reasonable limit setting that experts could change.

**Comment by simonpoole** [comment]
If it is simply an amount of data / zoomed out too far issue: loading less data and zooming in will help.  
Further there is a limit at which, when zooming out, the data will stop rendering (and that can be refined in the style), still there is always a bit of a conflict between enabling zoomed out views in low density areas and having to zoom in in high density ones.

**Comment by jidanni** [comment]
All I know is on osm.org one cannot zoom any higher than level 19.
However with this app even in locked mode I didn't test it but I be the sky's the limit.

**Comment by simonpoole** [comment]
But that is zooming -in- not out which should always improve performance not worsen it. 

For zooming in the limit is roughly 3 meters map display width at the equator, a limit where the maximum resolution of coordinates in OSM becomes noticeable.

**Comment by jidanni** [comment]
I had delay in doing the zooming itself. Anyway, especially in locked mode, do most users (need to) zoom that far? (For me it was always hitting + + +++++ and nothing happening. And then suddenly finding myself overzoomed and having to zoom back out.)

**Comment by simonpoole** [comment]
That really sounds like having far too much data loaded, have you checked?

**Comment by jidanni** [comment]
OK, with only about 25 hectares on my screen, I pushed this button:
> Clear and download current view - clear any data in memory and then download the area visible on the screen (requires network connectivity)

 The I went offline. However I was still able to query nodes several km away, even though now offline.

Therefore, apparently something isn't being cleared.

**Comment by jidanni** [comment]
Also for suddenly getting into the most extreme zoom level: I found that it is due to a certain finger action. Apparently sliding your finger in a certain way causes you to fly into the most extreme Zoom mode possible.

**Comment by jidanni** [comment]
Indeed, it all depends on how much data you loaded. So you were right. Closing.

**Comment by simonpoole** [comment]
Note: turning off the display of the tolerance/touch areas will have a positive effect on rendering speed in general if you are still experiencing problems.
