### ISSUE TITLE
Selecting shops with validator complaints is confusing

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1108]
Description:
---

Selecting shop=clothes with a validator complaint is confusing, as there is no feedback for selection and icons remains exactly the same

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>14.1.0.3</td></tr>
<tr><td>App version code</td><td>1401</td></tr>
<tr><td>Android build version</td><td>V10.0.18.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.18.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
What does the element information say (best include a screen shot)?

**Comment by matkoniecz** [comment]
![Screenshot_20200302-161825](https://user-images.githubusercontent.com/899988/75689578-b686d080-5ca1-11ea-8c96-89c43577b6d1.png)

I now noticed toast appearing on selection, but I missed when I was fighting with the pnone during mapping. And pausing mapping for bit leaves you confused about which object was selected.

**Comment by simonpoole** [comment]
The reason for the selection confusion is that the beta is more consistent in highlight validation errors, I'm working on a solution for this, see https://github.com/MarcusWolschon/osmeditor4android/issues/1123 for progress.
