### ISSUE TITLE
Add back, in addition to done,  to element info box

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1109]
Let's say the user wants to investigate many of these items,
![Screenshot_20200229-080837_copy_270x480](https://user-images.githubusercontent.com/1230959/75596419-8554a780-5acb-11ea-9597-e39c4634f03a.jpg)
Okay he clicks one of them and sees this,
![Screenshot_20200229-080918_copy_270x480](https://user-images.githubusercontent.com/1230959/75596433-9b626800-5acb-11ea-8095-e67945717b29.jpg)
At the bottom all you can choose is the word done. But that will blast them all the way back to the map. Therefore please add another entry in addition to done, which we should call back. Thank you

**Comment by jidanni** [comment]
Currently he is back on the map and has to do another very approximate long press on the map.

**Comment by jidanni** [comment]
Indeed, one would think that tapping the cell phone's back button would work already, However unfortunately that is the equivalent of pressing done here.

**Comment by simonpoole** [comment]
Continued in https://github.com/MarcusWolschon/osmeditor4android/issues/1235
