### ISSUE TITLE
Offline help should be independent of the program

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1111]
The Help menu item is great, except for every paragraph we read... then want to go back to the program and try it out, then we want to go back to the help menu and read the next paragraph, well that's a lot of digging back in to find our place. Therefore I propose that the the help menu should launch a browser browsing a local help file from the SD card or something so the user doesn't have to go all the way back out of help to get back into the program, and go all the way out of the program to get back in to help.

**Comment by simonpoole** [comment]
It wouldn't work "with a browser" as all the topic logic etc would be missing. However the help viewer is for all practical purposes already a separate program and maybe there's a way to package it as a separately executable app together with the main one.

**Comment by simonpoole** [comment]
Test (As in, if it doesn't work reliably in real life this will be reverted) implementation in https://github.com/MarcusWolschon/osmeditor4android/commit/f7b9fb4f98bae6a2ea184cb2badf8e6b0d5d4c88
