### ISSUE TITLE
Allow excluding way nodes beyond the box when downloading

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1112]
The button:
> Clear and download current view - clear any data in memory and then download the area visible on the screen (requires network connectivity)

_potentially_ also includes thousands of miles long interstate expressways that go beyond our very small bounding box.

Therefore perhaps add an additional choice to really exclude any node beyond the edges of the box.

However this is probably too difficult to implement.

_Originally posted by @jidanni in https://github.com/MarcusWolschon/osmeditor4android/issues/1107#issuecomment-592796449_

**Comment by simonpoole** [comment]
Ways contain a maximum of 2'000 nodes, and the distance itself isn't an issue. While it would be in principle possible to support incomplete ways (as we do with relations), it would add lots of complications, and would confuse users.

Not going to happen.
