### ISSUE TITLE
Prevent certain unpinches from being over interpreted

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1113]
Certain very fast unpinches will zoom to the max unintentionally.

Very fast pinches however don't do the opposite, thankfully.

_Originally posted by @jidanni in https://github.com/MarcusWolschon/osmeditor4android/issues/1107#issuecomment-592796948_

**Comment by simonpoole** [comment]
Please don't create lots of duplicate issues, there is already one on the topic here: https://github.com/MarcusWolschon/osmeditor4android/issues/1047

**Comment by jidanni** [comment]
(Actually on a cellphone it is sometimes harder to check. As you see this bug already shows editing disasters, and a behind the scenes loss of everything I typed in. Maybe I should write my bugs on a piece of paper for later entry on desktop. Yes the app has a direct bug report function, I know.)
