### ISSUE TITLE
Next to the words "Unlock to edit" add: "long press for details".

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1115]
Next to the words "Unlock to edit", please add: ", long press for details".
![Screenshot_20200229-081126_copy_270x480](https://user-images.githubusercontent.com/1230959/75596675-8d611700-5acc-11ea-94e1-71a1815fc6b6.jpg)
Otherwise the user assumes that is all that can be done, and will give up going on to try pressing a little longer.

_Originally posted by @jidanni in https://github.com/MarcusWolschon/osmeditor4android/issues/1106#issuecomment-592789230_

**Comment by jidanni** [comment]
Or "long press to query features".

**Comment by simonpoole** [comment]
There is obviously no way that will fit, not to mention in languages that tend to be more verbose than English.

**Comment by jidanni** [comment]
Well then perhaps make it two stories tall... being that the message only stays on the screen briefly.

**Comment by simonpoole** [comment]
> Well then perhaps make it two stories tall... being that the message only stays on the screen briefly.

Which would require at least a  custom snackbar layout if even possible without re-reacting from scratch, aka hours of work in not man weeks.

**Comment by jidanni** [comment]
OK, man weeks to make any message that is longer than one line.

Maybe it might wrap on its own anyway.

**Comment by jidanni** [comment]
#1116 has a slider.
