### ISSUE TITLE
Show more information, not cut off

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1116]
Here, less black screen could be traded for more information: especially just showing the user more of each line instead of cutting it off. Yes, even if the user rotates his screen 90° you're not going to get much more information currently.
![Screenshot_20200302-141600](https://user-images.githubusercontent.com/1230959/75650510-0741fd80-5c91-11ea-81a5-23127dc49e01.jpg)

**Comment by jidanni** [comment]
There is a good chance the information that the user is looking for lies beyond the edge of the box, so he has to go all the way back and get into unlocked mode to finally read what it said.

**Comment by simonpoole** [comment]
We use the standard Android context menu for this, which provides limited options for styling etc. It is naturally possible to change this to something custom, but would require a significant effort.

**Comment by jidanni** [comment]
Actually you already have such methods in place here

**Comment by jidanni** [comment]
There is a slider, above the word done but it disappears after 1 second, but at least one can still slide.

**Comment by simonpoole** [comment]
Except that the information dialog has absolutely nothing to do with the android context menu,

**Comment by simonpoole** [comment]
Continued in https://github.com/MarcusWolschon/osmeditor4android/issues/1235
