### ISSUE TITLE
Warn user he's trying to edit an incomplete point because it's out of the downloaded area

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1119]
At geo:24.1744429,120.8623651
There's a three-way Junction of electrical transmission lines. I want to simply edit the node  at that junction, however all I can select is one of five choices, and all five are ways. I just want to select the node.

**Comment by jidanni** [comment]
Same place as #1116.

**Comment by simonpoole** [comment]
No problem at all selecting it here (actually its the other way around the app essentially always selects the node without the disambiguation menu). In general the answer to all selection issues is to zoom in more

**Comment by jidanni** [comment]
actually, it turns out This spot was simply a little behind the edge of the downloaded area. Therefore, I recommend the default setting for shading the non download the areas should be on, instead of off that way beginners wouldn't encounter this mystery. furthermore when attempting to add in a. Non downloaded area, there should be a warning Saying you're  editing a non downloaded area. Therefore you are
Not playing with a full deck. This morning could be placed inside the list of nodes and ways I posted, at the end,

**Comment by simonpoole** [comment]
> 
> 
> actually, it turns out This spot was simply a little behind the edge of the downloaded area. Therefore, I recommend the default setting for shading the non download areas should be on, instead of off that way beginners wouldn't encounter this mystery. furthermore when attempting to edit in a. Non downloaded area, there should be a warning Saying you're editing a non downloaded area. Therefore you are
> Not playing with a full deck. This warning could be placed inside the list of nodes and ways I , at its end,
> Sorry about the bad punctuation, I'm using voice input to type this.

Both of this is already the case (the default is to shade non-downloaded areas, and you get a warning when you try to edit outside of them).

**Comment by jidanni** [comment]
OK, but in varying lighting conditions, the shading might not be obvious, unless the boundary is within the screen, or a new //// XXXX \\\\\ etc. very visible shading pattern is used.

Anyway in my case a node icon is there, but it is for the node of the way, but not the contents of the node (saying the ref of the tower.) So the user thinks he must be editing the tower...

Anyway I don't recall any warning. Perhaps I hadn't fully selected something to edit. Anyway the warning should come the moment a person long or short presses on any place on the screen that is outside of the downloaded area...
