### ISSUE TITLE
Help index should highlight current selection

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1120]
here
![Screenshot_20200302-194543](https://user-images.githubusercontent.com/1230959/75678833-71769480-5cc9-11ea-81c0-27e54046aac6.jpg)
 we see after pressing an item in the help index, it isn't highlighted.

**Comment by jidanni** [comment]
Sure, you can say well, it's name is at the top of the screen, why do we also need to highlight it below? Well, that's the way most other programs do it.

**Comment by simonpoole** [comment]
Added https://github.com/MarcusWolschon/osmeditor4android/commit/5734b20655dde7e6e0afe2b016af5204faebf05e
