### ISSUE TITLE
Second tap to turn back off the GPS button on the middle left

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1121]
The GPS button, in the middle of the left side of the screen, shouldn't a second tap turn it back off?

**Comment by simonpoole** [comment]
Not necessary as editing or panning the map will turn it off.

**Comment by jidanni** [comment]
> Not necessary as editing or panning the map will turn it off.

But it still leaves the app in a very different state from before we pushed it. There still is a purple wedge left on the screen and our GPS is still turned on excetera excetera. I was just hoping to restore everything just like the  way it was before we pushed the GPS button.

**Comment by simonpoole** [comment]
The "GPS" button turns on centering the screen on the current location, turned off that is disabled.

**Comment by jidanni** [comment]
Okay, I have determined that if one taps the left Bullseye icon, one needs to tap the bottom Bullseye icon, once to uncheck the first box, and then again to uncheck the second box. Apparently that makes the situation back to the way it was before we tapped the left Bullseye icon.

Now wouldn't it be great if we could just instead just tap the left Bullseye icon one more time ...

Yes, the screen is now in a different position then when we started but at least the other effects have been reversed.

**Comment by simonpoole** [comment]
Moving (aka panning) the screen will turn the centring on the position off (as expected), I'm not quite sure what use case you have for anything else.

**Comment by jidanni** [comment]
About panning: perhaps, but
it still leaves a big blue triangle on the screen.
Clearly not what the user started with!

**Comment by jidanni** [comment]
The user tries something (hitting the left bullseye.)
The user sees what that action has done (putting a big blue triangle in the center etc.)
The user says, "OK, I now know what that does."
The user wishes to end his experiment, and go back to the way things were, so he can do a different experiment, say.
The user, quite reasonably, would expect a second press of that button would turn whatever is going on off, and return him to the beginning state.

**Comment by simonpoole** [comment]
> 
> 
> About panning: perhaps, but
> it still leaves a big blue triangle on the screen.
> Clearly not what the user started with!
Which big blue triangle?

**Comment by jidanni** [comment]
![Screenshot_20200408-140632_1](https://user-images.githubusercontent.com/1230959/78750602-2d02a680-79a3-11ea-877e-77d901a28f9c.jpg)

**Comment by simonpoole** [comment]
Thats the marker for the current GPS position. As said the button centers the screen on the current position and turns following on, there is no value in "undoing" that except by moving the map to a different position, which you do by moving the map to a different position.

**Comment by jidanni** [comment]
Well I guess I would need an hour long video conference to explain what
I'm saying. So I had better give up.
