### ISSUE TITLE
Add a way to mark POI as "up to date"/"not outdated"

### ISSUE THREAD

**Issue by Mannivu** [MarcusWolschon/osmeditor4android#1122]
I've noticed that there is no way to let Vespucci know that a POI is still up to date. I'm taking about those POI the app warns about "Object may be out of date".

**Comment by simonpoole** [comment]
The validator will either use the time the element was last modified or a "check_date" tag that is present. There is even a scripted preset in "Annotations" that will automatically generate a check_date tag with the current date.

**Comment by Mannivu** [comment]
Yeah, but it's a bit unclear on user-side. I mean: if the POI's infos are correct and I don't change anything the validator won't be able to know that that POI is up to date. Moreover, there is no suggestion to add a "check_date" tag (a tag that I (and I suppose a lot of "casual" users) was not aware of until you mentioned it). I think that a simple "Up to date button" that automatically adds a "check_date" tag could be useful.

**Comment by alex9099** [comment]
Yeah, it would be nice to have an accessible button to quickly mark the node as checked (my use case would be resurveying  addr:housenumber, so opening the node tags is kinda useless and time consuming).
