### ISSUE TITLE
Selection not always visible

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1123]
Description:
---

When an object is "not complete" (for example missing Wheelchair) the icon outline of an restaurant is pink.
So the selection yellow is invisible. 

Device info:
---
<table>
<tr><td>App version</td><td>14.1.0.3</td></tr>
<tr><td>App version code</td><td>1401</td></tr>
<tr><td>Android build version</td><td>d9234</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPOS29.114-134-7</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>ocean</td></tr>
<tr><td>Device model</td><td>moto g(7) power</td></tr>
<tr><td>Device product name</td><td>ocean_reteu</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
This is a known issue in the beta and is being worked on.

**Comment by HolgerJeromin** [comment]
This is my issue. 
But my osm name is missing!

**Comment by simonpoole** [comment]
It only adds the name if it can determine it, aka it needs to connect or have at least once connected in the current session to the OSM api. Nothing is stored local on the device with the exception of your specific OAuth keys.

**Comment by simonpoole** [comment]
While not perfect, I believe https://github.com/MarcusWolschon/osmeditor4android/commit/d8f3627f45497cc3efe76ba2ed7508a9a3e7668d is an acceptable solution.

**Comment by HolgerJeromin** [comment]
Perhaps swapping the order of yellow and pink is another solution.
With this we would have only "selected" OR "validator is unhappy".
But I am looking forward to test the commit you have done.

**Comment by simonpoole** [comment]
> 
> 
> Perhaps swapping the order of yellow and pink is another solution.
> With this we would have only "selected" OR "validator is unhappy".
> 
Well that was how it was. The big downside of that is you then don't see the validation highlighting when moving an end node of a way, which is why I changed it in the 1st place.
