### ISSUE TITLE
 Show current zoom level number

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1126]
Perhaps show the current magnification number somewhere on the screen. I guess you would call it the zoom level number.

Maybe make it a preference check box: "always show current zoom number'.
When using iD, we can always see the current magnification up there in the URL bar. Same with when browsing the OSM website.

**Comment by simonpoole** [comment]
Vespucci allows continuous zoom so the number would not be very helpful, not to mention that there simply isn't any reasonable place to put it.

**Comment by jidanni** [comment]
I was just thinking of something like
https://www.offline-maps.net/_media/en/help/maps/maps-submenu.jpg
where he shows zoom level "3/19".

**Comment by Lee-Carre** [comment]
@jidanni
In the `Advanced preferences`, `Miscellaneous`, enable `Show stats`. One of the metrics is the current zoom level.
