### ISSUE TITLE
 remind user that the second touch is not a long press

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1128]
When the user does the second touch, he will think it should be just like the first touch. In other words he thinks he needs to do a long press. Therefore the following text should emphasize that the second touch is just a touch and not a long press.

> New
> After a long press on the map on the main screen you will enter the "New" mode (also see Introduction). This is the main way to add new nodes, ways and OSM Notes in Vespucci. At the place where you touched the screen you will see a cross marker.
> 
> You can now do one of three things:
> 
> touch in the same place again - this will add a node at the location and start the tag editor. If the location is within the tolerance zone of a way it will be added as a new node to that way.
> touch some other place on the screen - this will create a way from the initial location to the current location, the way can be extended by adding further nodes

**Comment by jidanni** [comment]
The above text has two spots where you need to remind the user of this issue. Thanks.

**Comment by simonpoole** [comment]
"patches", ... that is a PR, welcome.

**Comment by simonpoole** [comment]
Changed in https://github.com/MarcusWolschon/osmeditor4android/commit/fb30505174f5947bfa0e2f1735f7985adbf2e5cd
