### ISSUE TITLE
Many preset names don't fit into their boxes

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1129]
![Screenshot_20200304-135308](https://user-images.githubusercontent.com/1230959/75849359-a39a0a80-5e1f-11ea-8619-38512a88e838.jpg)

**Comment by simonpoole** [comment]
Do you have an accessibility feature or other way of increasing the scaling of text turned on?

**Comment by jidanni** [comment]
I recall in Android settings I usually side the text size sliders higher because I'm so old.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/151ea22c4144824df45d48b69f88474c87bd4f40 adds scaling of the "buttons" proportional to the accessibility "fontScale" value.

Note: we currently don't scale anything on the actual map display.
