### ISSUE TITLE
 add pending edit list

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1130]
Add a pending edit list. Currently the user has no way to tell if there are some edits of his that are awaiting to be sent to the server. In fear that he might have some wrong edits he could potentially send to the server he is forced to clear all everything and download data again. Therefore there should be list of all his pending edits somewhere accessibe so he can delete the ones that he thought might be made a mistake.

(You see it's very easy to accidentally make an bad edit and be not sure if you made it or not.)

**Comment by jidanni** [comment]
Okay if it says upload data to osm server in Gray that means one has zero edits. Okay but let's say we have one at it that's good I wanted it that's a bad and we want to get rid of the bad one before we send it to the server.

**Comment by jidanni** [comment]
OK,  this is probably what I want:
> Undo Undo
> Tapping the icon once will undo the last operation. A long press will display a list of the operations since the last save, if you have undone anything a corresponding "redo" action will be displayed. If the undo results in the current selected object being removed you will be returned to the main screen. Some operations consist of multiple simpler actions that will be listed as individual items.

**Comment by simonpoole** [comment]
I would not use the undo list for that, simply use the upload to server function and then cancel.

**Comment by jidanni** [comment]
Say, it would be neat when we are being shown the list of things we are about to upload, if we could individually pause some of them...

**Comment by jidanni** [comment]
Also regarding the "upload data to osm server" menu item: one needs to turn Wi-Fi etc. to tell its state. Whether one is actually connected or not is not important. Anyway, a count number of pending uploads should be attached to this menu item, visible no matter if, or if not, connected to the network.
