### ISSUE TITLE
Label Simple Mode new button "+." to avoid being the same label as the zoom button

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1132]
I can't find the exact article,
https://uxmovement.com/category/buttons/
but still, it is bad to have two "+" buttons,
the zoom button, and the bigger Simple Mode "+" new button.

Yes everybody knows the difference but it is still bad.

Therefore perhaps make the latter "+."... off the top of my head.

**Comment by simonpoole** [comment]
It might be theoretically bad, but given they are -very- distinctive, not something that is going to be changed at this point in time.
