### ISSUE TITLE
Cannot tell order of undo list

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1134]
Various presses of curved Undo buttons reveal lists.
But one cannot tell if the list is ordered oldest item on top, or oldest item on bottom.

E.g., one sees messages "Undo all latter checkpoints (safe)", but unless one has a great personal memory, one cannot tell which ones are older and which ones are newer, just by looking at the screen.

Perhaps number the items, or add timestamps or "x seconds, y minutes" ago timestamps.

**Comment by johantiden** [comment]
It might be enough to style the "latest" item differently, making it seem more important. This could save some screen space.

**Comment by simonpoole** [comment]
Addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/902662e222402513e37e8c922dd07a38cfda13b3
