### ISSUE TITLE
Undo when items are selected

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1135]
With a node selected, the user might think the Undo button only applies to changes he made to that node ("An easy way to allow me to just undo changes I made to that node.") But alas it might affect things kilometers away.

**Comment by simonpoole** [comment]
This solves the "km away" issue https://github.com/MarcusWolschon/osmeditor4android/commit/38cec4d0c7c6d1133e68ee125e5cd66fb8d6b2c0
