### ISSUE TITLE
Can't open osc file

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1136]
Description:
---

App crashes when I try to open an osc file

Device info:
---
<table>
<tr><td>App version</td><td>14.0.17.0</td></tr>
<tr><td>App version code</td><td>1319</td></tr>
<tr><td>Android build version</td><td>A750FNXXS4BTB1</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.A750FNXXS4BTB1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a7y18lte</td></tr>
<tr><td>Device model</td><td>SM-A750FN</td></tr>
<tr><td>Device product name</td><td>a7y18ltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7885</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
This is "good" we've been seeing this happen on and off, but it hasn't been reproducible here. Can you remember actually -when- it crashed?

**Comment by simonpoole** [comment]
After many attempts I've been able to recreate this locally so you don't need to investigate further at this time.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/6d95a9fc6cbbf61d82a70be67753da4fa9e180d3 the crash was dependent on the OSC file not being able to be applied completely (as you need to have all the relevant data loaded 1st), that left a reference  to a non-serializable class that caused issues when the app tried to save its state.
