### ISSUE TITLE
Long press in locked mode does not work properly

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1142]
Description:
---

When long pressing in locked mode, a tooltip appears and immediately disappears providing no opportunity to interact.

Device info:
---
<table>
<tr><td>App version</td><td>14.1.0.4</td></tr>
<tr><td>App version code</td><td>1402</td></tr>
<tr><td>Android build version</td><td>56480</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QSA30.62-24</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>kane_sprout</td></tr>
<tr><td>Device model</td><td>motorola one vision</td></tr>
<tr><td>Device product name</td><td>kane_reteu</td></tr>
<tr><td>Device hardware name</td><td>exynos9610</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Chris Hills</td></tr>
</table>

**Comment by simonpoole** [comment]
Chris can you check it the issue you are seeing isn't the same as https://github.com/MarcusWolschon/osmeditor4android/issues/750 ?

**Comment by Chaz6** [comment]
I will check and report back.

**Comment by simonpoole** [comment]
This was fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/6942dc9a962b1e6fb5184b4603f7a6284d34bb7a
