### ISSUE TITLE
Fall back to network provider needs a seconds parameter

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1144]
The fall back to network provider for location, needs a additional parameter. A number of seconds, default 5, for GPS to not provide a location before falling back to network provider. Otherwise many cell phones might not give you the statistic for one second but if you wait 2 seconds then it will, so there shouldn't be any falling back to network provider too soon.

**Comment by simonpoole** [comment]
The time after which the last position is considered stale is 20 x the GPS/GNSS sample interval, so typically 20x1s, 20s before switching.

**Comment by jidanni** [comment]
Well all I know is with my ASUS Zenfone 3, Android 8.0, every few
(five>) seconds I was seeing what I was looking at rapidly fly a kilometer or so
away, then rapidly fly back to the right spot, until I changed the
this setting to use only GPS, finally curing the problem.
