### ISSUE TITLE
Characters don't fit the box

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1149]
![Screenshot_20200325-081113](https://user-images.githubusercontent.com/1230959/77490568-2d188780-6e76-11ea-8b9e-8f7a08fc03a9.jpg)
This is from one of the anonymous sub menus of #1145 .

It characters are cut off with no way to see the full meaning. There's plenty of room left on the screen however. All I have might have done is made the font size bigger in Android settings for the whole cellphone years ago.

**Comment by simonpoole** [comment]
This seems to be an issue with Androids ListView.

**Comment by simonpoole** [comment]
This specific issue was addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/ad22e6b23cfbf006889abb9069b22ab199b4d192
