### ISSUE TITLE
 simple mode has no easy way to enter areas

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1150]
In simple mode, after pressing the big plus button, one can see how to enter a way, but one cannot see how to enter areas. An area for instance like a building.  In the help manual , in the section "Creating new objects in simple actions mode" one does also not find how to enter areas, only ways. If areas are somehow to be assumed a subset of ways and it should be mentioned. Because as we know in osm there are four primary types, points, ways, areas, and relations.

**Comment by jidanni** [comment]
perhaps areas and relations are not simple enough to be entered in simple mode. Okay that should be mentioned on the help page then.

**Comment by simonpoole** [comment]
> Because as we know in osm there are four primary types, points, ways, areas, and relations.

That will come as a surprise to many people, including those that designed the OSM data model. 

One of the big differences between OSM and other GIS systems is that OSM -doesn't- have an area type, instead we have three convention based ways of modelling areas. 

There is a section in the Introduction on areas here http://vespucci.io/help/en/Introduction/#adding-an-area

**Comment by jidanni** [comment]
Yes that's why in the manual in the section "Creating new objects in simple actions mode" I would repeat the mention of Vespucci's peculiarity, as 100% of all the GIS and OSM stuff do it differently, so it perhaps needs to be mentioned every spot were entering ways is mentioned.

**Comment by jidanni** [comment]
In fact in all the command menus where  it says "add a way", I would say "add a way / area".

**Comment by jidanni** [comment]
I mean you are using a very special OSM jargon, "way". So users would expect to find the other ones. If you said add a path or add a line excetera then things might be a little different.
