### ISSUE TITLE
Tapping the notification should switch to the app

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1153]
Tapping this notification does nothing.
![Screenshot_20200407-184435](https://user-images.githubusercontent.com/1230959/78660824-55859480-7900-11ea-8cad-ed2932746fe9.jpg)
It should switch to the app.

**Comment by simonpoole** [comment]
Tapping a notification will start the app and center on the relevant position, tapping the group entry will expand the notification group (standard android functionality), which is what you seem to have done.

**Comment by simonpoole** [comment]
Actually you need to touch the group first and then touch an expanded notification which will then take you the location in Vespucci. The details are a bit Android version dependent, but nothing that is under our control.

**Comment by jidanni** [comment]
Well perhaps all other apps' notifications that are in this state have an additional failsafe hyperlink or whatever to take the user to that app.

I tried touching many ways. No amount of touching could expand this more or in fact do anything. Perhaps this was a ASUS ZenFone3 specific problem. (But that's the only phone I got to test on.)

**Comment by johnjohndoe** [comment]
# Request for re-open

I also noticed in the recent version `19.3.4.0` does **not** open the app when I tap the following notification:

> Daran denken, die Arbeit hochzuladen  
> Du hast eine ungesicherte Änderung

It would be very convenient if this reminder notification would launch the app.

# Separate feature request / feel free to extract from here

If the user decides to launch the app without tapping the reminder notification and upload all changes then this particular notification should be automatically cleared. I implemented a similar mechanism in the [EventFahrplan](https://github.com/EventFahrplan/EventFahrplan) app when visiting the schedule changes screen.

**Comment by simonpoole** [comment]
Iirc tapping the reminder notification has never started the app. 

With other words this should be in a new issue as it is a question of adding new functionality
