### ISSUE TITLE
data style dialog: style names are not translateable

### ISSUE THREAD

**Issue by iriman** [MarcusWolschon/osmeditor4android#1156]
Preferences > Data style
Vespucci: 14.1.3 from github

![۲۰۲۰۰۴۱۴_۱۹۲۲۲۷](https://user-images.githubusercontent.com/8467903/79361834-120fd380-7f5b-11ea-959e-edf3317e189c.jpg)

**Comment by simonpoole** [comment]
Actually the translations are missing (in any language) because the style name strings are actually embedded in the style configuration files and are currently not translatable (outside of copying the file and changing the name).

**Comment by simonpoole** [comment]
Support added in https://github.com/MarcusWolschon/osmeditor4android/commit/ed929ebb0acd3167473f5b0d46e98695dbe296c9

**Comment by iriman** [comment]
Thank you for the work! :heart:
