### ISSUE TITLE
Rotate multiple objects

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1157]
Description:
---

Hi. A great program. You could use the function of rotating several selected objects.
Regards

Device info:
---
<table>
<tr><td>App version</td><td>14.1.3.0</td></tr>
<tr><td>App version code</td><td>1406</td></tr>
<tr><td>Android build version</td><td>6</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NPPS26.102-50-5</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>montana_n</td></tr>
<tr><td>Device model</td><td>Moto G (5S)</td></tr>
<tr><td>Device product name</td><td>montana_n</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Sierżant York</td></tr>
</table>

**Comment by simonpoole** [comment]
Thanks!

**Comment by simonpoole** [comment]
While this is being done it would be a good idea to use the "check" button UI to exit instead of the "up/home" button in the action bar.
