### ISSUE TITLE
Allow text copy of device info in github issue

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1160]
Description:
---

Create github issue
Look at the device info (geräteinfo).
Would be nice if I could select and copy the device details.

Device info:
---
<table>
<tr><td>App version</td><td>14.1.3.0</td></tr>
<tr><td>App version code</td><td>1406</td></tr>
<tr><td>Android build version</td><td>21fefe</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPOS29.114-134-10</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>ocean</td></tr>
<tr><td>Device model</td><td>moto g(7) power</td></tr>
<tr><td>Device product name</td><td>ocean_reteu</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>HolgerJeromin</td></tr>
</table>

**Comment by simonpoole** [comment]
This is an upstream issue see https://github.com/heinrichreimer/android-issue-reporter

**Comment by HolgerJeromin** [comment]
reported as https://github.com/heinrichreimer/android-issue-reporter/issues/135

**Comment by simonpoole** [comment]
Fixed (hackish) in https://github.com/MarcusWolschon/osmeditor4android/commit/c1b066a97d2da9fbdd754e856c5be1f743e01c5e
