### ISSUE TITLE
Ansicht Bearbeitung zu dunkel

### ISSUE THREAD

**Issue by SprickW** [MarcusWolschon/osmeditor4android#1166]
Description:
---

nach Entsperren wird das Bild so dunkel, dass man damit im Tageslicht nicht mehr gescheit arbeiten kann. Ich habe keine Einstellungsmöglichkeit gefunden. 

Device info:
---
<table>
<tr><td>App version</td><td>14.1.4.0</td></tr>
<tr><td>App version code</td><td>1407</td></tr>
<tr><td>Android build version</td><td>P2a42_S251_171107_ROW</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>P2a42_S251_171107_ROW</td></tr>
<tr><td>Device brand</td><td>Lenovo</td></tr>
<tr><td>Device manufacturer</td><td>LENOVO</td></tr>
<tr><td>Device name</td><td>P2a42</td></tr>
<tr><td>Device model</td><td>Lenovo P2a42</td></tr>
<tr><td>Device product name</td><td>kuntao_row</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
Nicht heruntergeladene Gebiete sind im "Unlocked" Modus immer abgedunkelt (ausser man zoomt soweit heraus dass man nicht mehr editieren kann). Sprich die Lösung ist im jeweiligen Gebiet Daten zu laden.

Der Grund für das Verhalten ist das man in irgendeiner Form anzeigen muss ob in einem Gebiet Daten fehlen, oder ob sie einfach, noch, nicht geladen wurden.

**Comment by simonpoole** [comment]
No ask from OP, closing.
