### ISSUE TITLE
Nur ein Wunsch: ein „nicht mehr anzeigen”-Kästchenh

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1167]
Description:
---

Hallo,

seit gut sechs Wochen verwende ich Ihre phantastische App täglich.

Dabei ist mir bislang nur eine Kleinigkeit aufgefallen, die mich ärgert:
ich ziehe den „einfachen Modus” vor.
Als ich nun erstmals versuchte, einen „node” ein winziges Stück zu verschieben (langsam und präzise), interpretierte die App dies als „langes Drücken”, gab völlig korrekt einen Warnhinweis aus und blockierte solange den Bildschirm - genau wie beim zweiten, dritten, vierten, ..., zehnten... Mal.

Ich WEIẞ  spätestens seit dem gefühlt hundertsten Warnhinweis, dass langes Drücken im einfachen Modus nicht funktioniert.

Darum wäre ich SEHR dankbar für eine wie auch immer gestaltete Möglichkeit, diesen Hinweis zu deaktivieren (oder alternativ für einen Schieberegler in den Einstellungen, mit dem festgelegt werden kann, ab wann ein Drücken „lang” ist).

Mit freundlichen Grüßen,
Jochen Konietzko 

Device info:
---
<table>
<tr><td>App version</td><td>14.1.4.0</td></tr>
<tr><td>App version code</td><td>1407</td></tr>
<tr><td>Android build version</td><td>9ba98ad4b7</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>lineage_starlte-userdebug 8.1.0 OPM7.181205.001 9ba98ad4b7 test-keys</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>starlte</td></tr>
<tr><td>Device model</td><td>SM-G960F</td></tr>
<tr><td>Device product name</td><td>lineage_starlte</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos9810</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Marabu_Too</td></tr>
</table>

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/f095dd5eebde5636d762c41a1796cbc564ce45f5 ersetzt den toast mit einem einmaligen Dialog und einem "Piep",
