### ISSUE TITLE
Geoportal 2 imagery is not working

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1171]
Description:
---

It is working in iD

Geoportal 2 is serial available in Poland, provided by government

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>14.1.4.0</td></tr>
<tr><td>App version code</td><td>1407</td></tr>
<tr><td>Android build version</td><td>V10.0.20.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.20.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by matkoniecz** [comment]
serial -> aerial

**Comment by simonpoole** [comment]
Have you updated the imagery configuration? (Nore iD is no longer relevant).

**Comment by matkoniecz** [comment]
How can I do this? I tried (manually) searching in preferences, searching through website etc.

I only found that Geoportal 2 aerial is not considered as aerial by Vespucci (not listed among "Aerial imagery") but it is probably unrelated.

Flush tile cache is unlikely to be what I was supposed to do, but I tried it anyway,

> Note iD is no longer relevant

I know that they did something strange with imagery, but it still confirms that I am not reporting outage of gov.pl servers.

**Comment by simonpoole** [comment]
Main menu / Tools / More imagery tools / Update imagery layer configuration

**Comment by matkoniecz** [comment]
Done. Not sure is it a result of this change but at least some tiles on lower zoom levels loaded.

High zoom level is still without tiles or loading empty tiles.

**Comment by simonpoole** [comment]
You will likely  need to flush the tile cache.

**Comment by matkoniecz** [comment]
Flushed again. For some reason Geoportal behaves iike overloaded (or with heavy rate-limit applied) server.
