### ISSUE TITLE
No way to add the same member to a relation multiple times

### ISSUE THREAD

**Issue by dead10ck** [MarcusWolschon/osmeditor4android#1173]
There doesn't seem to be a way to add the same object to a relation more than once. This is necessary, for example, with bus routes which travel over the same way(s) more than once. It would be great if this capability could be added, although I'm not really sure that the UX would be like. Perhaps when in the "add members" mode, if the user clicks on something that is already a member, a pop up could ask if they want to add it again. Maybe it could also be highlighted a slightly different color.

**Comment by simonpoole** [comment]
Hi, this is a a restriction in the normal "add element to relation" UI (it does for example work though for turn restrictions). The medium term fix will be to have a specific "build route mode".

The workaround for now is to 

- select the element you want to add to the relation
- start the property editor
- go to the "Relations" tag
- select the "Add to relation" entry from the overflow menu
- select the relation you want to add the relation to (you can repeat the previous step and this as many times as you need)

Note: there is an UI hiccup that I just fixed, in that the first relation in the list will be preselected when the new membership row is added, so you need to be careful to not inadvertently add something you don't want to. 

See also https://github.com/MarcusWolschon/osmeditor4android/issues/195

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/pull/1253 adds dedicated "Create route" and "Add to route" functions, that allow adding the same way twice. They are not necessarily ideal for PT routes as they don't allow adding nodes, but that might be added later as a variant.

The create relation mode is going to be modified to allow this too.
