### ISSUE TITLE
Way to pivot from relation members to location on map

### ISSUE THREAD

**Issue by dead10ck** [MarcusWolschon/osmeditor4android#1174]
When editing the members of a relation, the identifiers shown are often too vague to know exactly which object it refers to (e.g. there could be 15 ways that just say Some Avenue, or worse, `highway=service`).

It would be nice if you could click on the name in the right column and have it take you to the object and select it for you, and then be able to press the back button to go right back to the same relation member menu, so you can select others. This would significantly improve the ability to analyze a relation.

**Comment by simonpoole** [comment]
This is currently not feasible as the PropertyEditor is a separate Android activity, and switching back and forward between it and the map view is everything but definitely not light weight (for example it potentially entails saving all of the app state). 

Re-factoring the PropertyEditor to be more light weight (at the penalty of less robustness) is planned (not the least to enable such functionality as you are suggesting here). 

See https://github.com/MarcusWolschon/osmeditor4android/issues/808
