### ISSUE TITLE
Change keyboard type for certain OSM tags

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1177]
Values of certain OSM tags only use a restricted set of characters consisting of numbers and characters to display phone numbers (spaces, plus sign):

Examples:

- `contact:phone=`
- `building:levels=`
- `capacity=`
- `seats=` (for benches)
- etc.

Would it be possible when entering the content (value) of these tags, that instead of the normal keyboard, a phone number keyboard with a reduced number of buttons would be displayed? This would make it easier/faster to type and prevent typos.

**Comment by simonpoole** [comment]
We definitely already use the phone keyboard for fax, phone, contact:phone and contact:fax. building:levels and seats normally don't show any keyboard at all (you get a popup menu).

So this would seem to be a bit of a no-op.

**Comment by ltog** [comment]
I wasn't sure if I have seen the phone keyboard in Vespucci before, but according to what you write, I probably have. However, it currently isn't visible in my case. I have two phones, both showing the same symptoms:

Add tagged node -> Switch to tab "Details" -> type "fax -> tap into field "value" -> on the left half of the screen appears an empty list, keyboard is still the full one, which perfectly types values on the right hand side.

Phone A: Fairphone 2, Android 7.1.2, Vespucci 14.1.4
Phone B: Samsung Galaxy A51, Android 10, Vespucci 14.1.4

**Comment by simonpoole** [comment]
In the details tab, as you need to be able to enter "anything", we show the normal keyboard.

But in the normal "Properties" tab we provide the keyboard as described.

**Comment by ltog** [comment]
@simonpoole : I can only partially reproduce what you say.

If I do the following steps, there is no phone keyboard: Add tagged node -> Switch to tab "Details" -> typing value = "fax" -> Switch to tab "Properties" -> tap into field "Type value" -> Full keyboard :-(

However, there is a phone keyboard when I do the following:
Add tagged node -> (will open dialogue in tab "Presets") -> tap into "Preset search string" -> write "restaurant" -> choose "Restaurant" icon -> Switch to tab "Details" -> Add key "fax" -> (while still being in the tab "Details") type into value field of key "fax" -> Phone keyboard appears :-) -> Switch into tab "Properties" -> Type into value Field of key "Fax Number" -> Phone keyboard appears as well. :-)

**Comment by simonpoole** [comment]
For the app to know what a tag "is" it needs to have matched the object to a preset (because the presets contain all this information). A lone "fax" tag matches with nothing and so there is no way to know that is is a phone number like field.

**Comment by simonpoole** [comment]
Closing as stale
