### ISSUE TITLE
Remove proposal of key `self-service=`

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1178]
When typing `self` as key, Vespucci proposes two keys:

- [`self_service`](https://taginfo.openstreetmap.org/keys/self_service): 19k uses, described at https://wiki.openstreetmap.org/wiki/Key:self_service
- [`self-service`](https://taginfo.openstreetmap.org/keys/self-service): 0 uses, no wiki description at https://wiki.openstreetmap.org/wiki/Key:self-service

I therefore propose to remove the proposal of key `self-service=`

**Comment by simonpoole** [comment]
Wrong repo, but anyway https://github.com/simonpoole/beautified-JOSM-preset/commit/d77ccd9475e07645c15e8bc1cb09d71289273dd7

The confusion btw is due to the OSM tag actually being written wrong (the correct English -is- self-service).

**Comment by ltog** [comment]
Cool, thanks!
