### ISSUE TITLE
Support Mapsforge/OsmAnd/other vector format background

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#118]
```
As suggested in comments at the end of issue 66, use Mapsforge to support tiles 
based on data stored on the Android device itself. This would assist surveying 
offline.
```

Original issue reported on code.google.com by `andrew.g...@gmail.com` on 9 Sep 2012 at 4:02
- Blocking: #272

**Comment by simonpoole** [comment]
We now support mapbox vector tiles, while not particularly performant, with a style specifically targeted for our renderer it should be good enough. See https://github.com/MarcusWolschon/osmeditor4android/commit/91bf7cbbcba8a19eebdacbf34879f18b51700e99
