### ISSUE TITLE
Uploaded items stay after API switch

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1184]
Description:
---

I tested loading an OSC file I made and uploading it to the dev API, but when I switched back to the live API, the new nodes remained on the map, I couldn't get rid of them by reloading the view, I had to clear all of Vespucci's data to do that. 

Device info:
---
<table>
<tr><td>App version</td><td>14.1.4.0</td></tr>
<tr><td>App version code</td><td>1407</td></tr>
<tr><td>Android build version</td><td>V11.0.9.0.PCXEUXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.190616.001</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>willow</td></tr>
<tr><td>Device model</td><td>Redmi Note 8T</td></tr>
<tr><td>Device product name</td><td>willow_eea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>IByte</td></tr>
</table>

**Comment by simonpoole** [comment]
Thanks. This was fixed for 15.0 in https://github.com/MarcusWolschon/osmeditor4android/commit/eadea3b4f61d92de47d955c4c71f4d7270654374

**Comment by IByte** [comment]
Thanks, I'll wait for the update to land on Google Play Store. (I reported this issue, by the way, but I didn't use my GitHub account in Vespucci.)
