### ISSUE TITLE
Help menu - white entries on light vacuous

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1185]
Description:
---

Using app in a dark mode. System dark mode turned on as well.

Language: cs_CZ

reported by @kudlav

Device info:
---
<table>
<tr><td>App version</td><td>15.0.0.1</td></tr>
<tr><td>App version code</td><td>1500</td></tr>
<tr><td>Android build version</td><td>A405FNXXU3BTD4</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.A405FNXXU3BTD4</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a40</td></tr>
<tr><td>Device model</td><td>SM-A405FN</td></tr>
<tr><td>Device product name</td><td>a40eea</td></tr>
<tr><td>Device hardware name</td><td>exynos7904</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>kudlav</td></tr>
</table>

**Comment by kudlav** [comment]
![Screenshot_20200625-162902_Vespucci](https://user-images.githubusercontent.com/11516259/85741895-17c82900-b703-11ea-80ea-9d4ebcdf67d3.png)

**Comment by simonpoole** [comment]
Thanks for the report, note this was not actually a BETA specific defect.

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/38cbd4e5ad40420b09d78c8305252e3b297a9bfa
