### ISSUE TITLE
Locales with "," as decimal point  crash current position info dialog

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1186]
Description:
---

1. Open Vespucci
2. Download data
3. Start editing mode
4. Press Current position info
5. Vespucci crashing

language: cs_CZ

reported by: @kudlav

Device info:
---
<table>
<tr><td>App version</td><td>15.0.0.1</td></tr>
<tr><td>App version code</td><td>1500</td></tr>
<tr><td>Android build version</td><td>A405FNXXU3BTD4</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.A405FNXXU3BTD4</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a40</td></tr>
<tr><td>Device model</td><td>SM-A405FN</td></tr>
<tr><td>Device product name</td><td>a40eea</td></tr>
<tr><td>Device hardware name</td><td>exynos7904</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>kudlav</td></tr>
</table>

**Comment by kudlav** [comment]
reported via in-app crash reporting tool 3 times 25.6. ~16:40 UTC, included my [email](https://github.com/kudlav)

**Comment by simonpoole** [comment]
Thanks, this is due to your device being set to Polish which uses a "," as decimal point, this causes an issue when re-parsing coordinates.

Fixed in https://github.com/MarcusWolschon/osmeditor4android/runs/808506725
