### ISSUE TITLE
RTL for help documents

### ISSUE THREAD

**Issue by iriman** [MarcusWolschon/osmeditor4android#1187]
Hi, 

The RTL issue with introduction text ( mentioned in #445 ) is not solved yet on 14.1.16:

> Direction of Persian help docs need to be rtl. Of course not translated ones should remain ltr:

Screenshot from Vespucci 14.1.16 (Play Store) on android 7.1.1:

![image](https://user-images.githubusercontent.com/8467903/85848261-19a2f280-b7be-11ea-8abe-b83bbc884720.png)

**Comment by simonpoole** [comment]
This is fixed but hasn't been back ported to 14.1.

**Comment by iriman** [comment]
Yes, I tried per-release version 15 and it is fixed there. So I can close this issue.
