### ISSUE TITLE
Split translations for "branch"

### ISSUE THREAD

**Issue by debyos** [MarcusWolschon/osmeditor4android#1189]
Dear Developers,

please duplicate the translation for "branch" ([in the presets](https://github.com/MarcusWolschon/osmeditor4android/tree/7dc733fd9472d7db960b7b4bc04367b6ee0e2065/src/main/assets)): one for **railways** and another for **banks**.
Thanks

Gábor, a keen translator

**Comment by simonpoole** [comment]
As you correctly note this is a preset issue (separate translation contexts need to be set) and the issue should be opened there. Unluckily I can't move issues, so could you open it in the preset repo https://github.com/simonpoole/beautified-JOSM-preset or even better create a pull request with the changes in question?

**Comment by simonpoole** [comment]
Translation context added in https://github.com/simonpoole/beautified-JOSM-preset/commit/ab79ae59790eacc588695c3943d1cb6e2857b110
