### ISSUE TITLE
Feature request: option to select a colour (or opacity) for the grid layer

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1191]
Quite recently I discovered the configure command in the grid layer to turn on a grid (not only a scale)... And I like to have the grid turned on as a help for creating new objects in the right size or positioning something in the right distance.

But the grid of black lines is very **dominant** on the screen, it's a little painful for the eyes ... Would be nice to be able to choose another colour (e.g. light gray) or reduce the opacity of the black lines or another colour. (Or choosing dotted lines perhaps.)

In the GPX layer, you have the "Change style" option (very nice!) ... perhaps something like that.

And the best solution would be to be able the choose **two different styles** for the scale and the grid (but also choosing one style for both would be OK ...).

Would that be hard to implement?

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/d71edb2511901b0a5738833fb0808bb93a3424a3
