### ISSUE TITLE
Straße endet in Sackgasse

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1192]
Description:
---

Straße hat Verbindung mit Hauptstraße per Fußweg

Device info:
---
<table>
<tr><td>App version</td><td>14.1.6.0</td></tr>
<tr><td>App version code</td><td>1409</td></tr>
<tr><td>Android build version</td><td>G950FXXS9DTEA</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.G950FXXS9DTEA</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dreamlte</td></tr>
<tr><td>Device model</td><td>SM-G950F</td></tr>
<tr><td>Device product name</td><td>dreamltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>obsalius</td></tr>
</table>

**Comment by simonpoole** [comment]
Kannst du erklären was genau das Problem ist?

**Comment by Obsquad** [comment]
Ich hatte eine OSM-Korrektur durchgeführt, warum daraus ein Issue geworden ist, verstehe ich nicht. Der Upload der Korrektur hatte allerdings nicht geklappt.
Somit ist der Issue ungültig bzw Gegenstandslos. Bitte löschen.
