### ISSUE TITLE
Long-Press in Locked Mode does not show Contextual Menu

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1193]
Description:
---

Hi, in Locked Mode I am not able to select pictures , and the Contextual Menu appears on Long Press 
only super-briefly (split second). I already changed the Long Press duration in System Settings to 1.5 
and even 2.0 and back to 0.5, but with no effect. In Edit Mode Long Press works just fine and shows 
the Contextual Menu, where I can select pictures and objects normally. Is there a way to solve this? 
BR, Stephan

Device info:
---
<table>
<tr><td>App version</td><td>14.1.6.0</td></tr>
<tr><td>App version code</td><td>1409</td></tr>
<tr><td>Android build version</td><td>G973FXXU7CTF1</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.G973FXXU7CTF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>beyond1</td></tr>
<tr><td>Device model</td><td>SM-G973F</td></tr>
<tr><td>Device product name</td><td>beyond1lteeea</td></tr>
<tr><td>Device hardware name</td><td>exynos9820</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>peppone84</td></tr>
</table>

**Comment by simonpoole** [comment]
I believe I've fixed this in https://github.com/MarcusWolschon/osmeditor4android/commit/6942dc9a962b1e6fb5184b4603f7a6284d34bb7a which addresses an, at least, nine year old issue.
