### ISSUE TITLE
“Minimum GPS/GNSS-distance” to less than 1 meter?

### ISSUE THREAD

**Issue by okkei** [MarcusWolschon/osmeditor4android#1195]
I tried a) b) c) and d) features but current location cursor point do not move on the map unless more than 1 m from the previous location. At least I didn't succeed. Easy to test with my external RTK device.

a) "New node at GPS position"  b) "The "on-map" GPS button" c) "Go to current location" d) "Follow GPS position" set.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/1664003d9b2a66b6ba0ec5926bbc9493fb0ba89c allows setting these values to zero. However the settings are only used for the device internal GNSS receiver anyway, so I'm curious as to how you have your RTK device connected to the phone.

**Comment by okkei** [comment]
Many thanks. I am using the Lefebure NTRIP Client application where the settings are "External via Bluetooth" and "GPS Mock Locations". In Vespucci, "GPS / GNSS source" is "internal".
Hopefully a version with a zero setting will be available soon on Google Play.

**Comment by simonpoole** [comment]
Just a note: Android doesn't guarantee any specific behaviour when you set the minimum interval/distance values so settign them to 0 may or may not work.
