### ISSUE TITLE
Support OsmAnd proprietary file formats (extensions to OSC or GPX file) to import notes

### ISSUE THREAD

**Issue by jg110** [MarcusWolschon/osmeditor4android#1196]
## Vespucci Version

14.1.4

## Download source

F-Droid

## Device (Manufacturer and Model)

BlackBerry KeyONE

## Android Version 

7.1.1

## Behaviour/Symptoms

Importing notes fails with both OSC and GPX files. Files were generated with OsmAnd.

If using File... > Apply changes from OSC file, nodes will be imported but notes are not.

If using File > Read JOSM File, an error appears:
```
No connection to server
Could not connect to the OSM server now.
Please check that you are connected to the
Internet, or try again later.

Couldn't construct a bounding box from
data.
```

If using Tasks... > File... > Load custom tasks... nothing is imported.

## Expected Behaviour

Notes should appear after importing.
## How to recreate

Attempt to import notes via any of the methods mentioned in the Behavior/Symptoms section.

## Crash dump submitted (no or yes + date)

No
## Any other potentially relevant information

Here is a test OSC file I generated with OsmAnd to demonstrate this problem:
```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?> 
<osmChange generator="OsmAnd" version="0.6"> 
  <create>
    <note lat="30.231580441382448" lon="-88.11393710757413" id="-214"> 
      <comment text="here is my cool note on Dauphin Island" /> 
    </note> 
  </create> 
  <modify /> 
  <delete /> 
</osmChange>
```

**Comment by jg110** [comment]
It's also worth noting that I'm unable to import notes exported from Vespucci either.

**Comment by simonpoole** [comment]
The standard OSC file format has no support for Notes, this seems to be an OsmAnd specific proprietary extension (and the same goes for embedding them in a GPX file).

Notes need to exported/imported in the .osn format nothing else will work at the current time.

**Comment by jg110** [comment]
I'm also unable to import notes from an osn file. If I generate one with Vespucci, clear all notes on the map, and try to import from the osn file, nothing happens.

**Comment by simonpoole** [comment]
> 
> 
> I'm also unable to import notes from an osn file. If I generate one with Vespucci, clear all notes on the map, and try to import from the osn file, nothing happens.

But that is no surprise as there is no OSN import facility (the export is mainly intended for situations where you want to do some work in JOSM on the exported Notes). See also http://vespucci.io/help/en/Main%20map%20display/#available-actions

**Comment by simonpoole** [comment]
See also https://josm.openstreetmap.de/ticket/11086

**Comment by simonpoole** [comment]
After looking at the relevant code, the reason for no import facility existing up to now is that the JOSM/OSN format uses a different XML encoding than the API 0.6 delivers. With other words implementing this requires a further parser.

**Comment by simonpoole** [comment]
Note this should als clean up the string constants for tasks and notes.

**Comment by simonpoole** [comment]
Done in https://github.com/MarcusWolschon/osmeditor4android/pull/1306
