### ISSUE TITLE
Sharing GPX file can list Vespucci

### ISSUE THREAD

**Issue by niccokunzmann** [MarcusWolschon/osmeditor4android#1197]
I would like to export my GPX traces from other applications to Vespucci.
The app usually has a share-button to share the GPX trace.
When I click this share button, I would like Vespucci to also show up.

- [ ] sharing GPX files with Vespucci

Which other file types could be imported/imported? They could also get a sharing menu.

**Comment by simonpoole** [comment]
Could you indicate which Vespucci version you are using, as this used to work and may be a regression?

**Comment by simonpoole** [comment]
Seems as if on some devices intent filters based on file type do not work (even though they work just fine on AOSP devices), I've added support for mime type based intent filters in https://github.com/MarcusWolschon/osmeditor4android/commit/4c5a57a8e5f64915731e219f6f1d621c4492443d

**Comment by contrapunctus-1** [comment]
Vespucci v18.1.5 from F-Droid does not show up in the share list when I share a GPS trace from OsmAnd~ 4.3.8 from F-Droid, on LineageOS 20 (Android 13).

**Comment by simonpoole** [comment]
@contrapunctus-1 could you open a separate issue. This had to do with directly sharing gpx files for example from a file explorer. OsmAnd uses (for whatever reason) ACTION_SEND instead of ACTION_VIEW for sharing gpx files which we currently only support for images.
