### ISSUE TITLE
Extreme performance regression

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#1198]
## Vespucci Version
15.0.0 BETA 1

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Mi A2 Lite

## Android Version 
10, standard

## Behaviour/Symptoms
Recently (weeks? month?) I started getting Vespucci freezes. Selecting line works fine, then I select tag buttons and it enters into menu for five minutes. I edit tags, leave menu and it takes next 3 minutes.

Recently I reinstalled Vespucci because it was frozen on loading data (on opening app), later I needed to do three more times.

My current plan is to install Vespucci from source (maybe it will somehow fix the issue?) and if problem is reproducible start bisecting from version say 1 year old.

If there is something more productive that I can do - let me know.

## Expected Behaviour
No freezes/crashes.

## How to recreate
??? It sometimes happens on application startup (also with small loaded dataset) on starting to edit tags (rarely, but with extreme freeze), finish tag edits (the same).

## Crash dump submitted (no or yes + date)
no, I would be happy to do this if that is possible

## Any other potentially relevant information
???

**Comment by simonpoole** [comment]
Before doing anything exotic, you should check how much data you have loaded, in particular, but not only relations. You can check either in the "Info" menu item for the data layer or in the Debug screen.

All the symptoms you are describing would point to (far) too much data loaded (starting the property editor causes the in memory data to be saved and potentially be re-read after closing it).

The fix is to either prune the data (which in 14.X will however not help with relations), or simply reload completely after uploading any edits.

**Comment by matkoniecz** [comment]
I know this, and I have no exact numbers from freeze but I am almost sure that dataset was pretty small. I am no longer trying to download big areas into Vespucci.

Next time I will try to wait for freeze to end rather than reinstall Vespucci and check what I loaded.

**Comment by simonpoole** [comment]
Just to be clear Vespucci behaves no worse than iD or other editors and you can download a reasonably sized chunk. Things simply get slow if you for example have a 1000 longish public transport relations and similar.

**Comment by matkoniecz** [comment]
> no worse than iD

That is quite low bar, as far as performance goes[0] :) Vespucci is much better than iD, but far less capable than JOSM (though it is hard to compare iD/JOSM on PC with Vespucci on smartphone)

[0] Maybe it got significantly better in latest release?

> Things simply get slow if you for example have a 1000 longish public transport relations and similar.

I often have noticeable slowndown (especially on dragging viewport) far earlier.

**Comment by simonpoole** [comment]
> > Things simply get slow if you for example have a 1000 longish public transport relations and similar.
> 
> I often have noticeable slowndown (especially on dragging viewport) far earlier.

While rendering performance is, naturally, dependent on the amount of data loaded, it also depends on many many other factors: how far zoomed out/is you are, how many layers are enabled, the data style, if there are many MPs or not, and so on.

The issue you are reporting is not dependent on any of those outside of the data volume, it is simply how long it takes to serialize and write the state out to on device storage (btw in the debug screen you can see how large the current state file is).

In any case the relevant state saving code hasn't changed for a long time, essentially the last major change was using FST for serialisation, which was a clear performance gain.

**Comment by matkoniecz** [comment]
Multiple seconds of freeze on ending tag edit. 159 relations, 907 ways, 7586 current nodes, 9054 "waynodes". Bug state file size 20336.

Fun fact: clicking "send debug info" brings up vespucci crashed message, but maybe it is hacky way to submit this info. I now did it with "#1198" description.

**Comment by simonpoole** [comment]
IMHO could be a corrupted install or other similar issue. The send debug info uses the crash reporting mechanism, for obvious reasons.

**Comment by matkoniecz** [comment]
> IMHO could be a corrupted install or other similar issue.

Either my phone has problem or Vespucci is self corrupting its data, because I reinstalled Vespucci already multiple times recently due to this freeze issues.

**Comment by matkoniecz** [comment]
I reinstalled again, this time it reliably crashes on finishing tag editing.

I submitted report with "I ended tag editing (green duck for making this unique)" description

**Comment by simonpoole** [comment]
That is an unrelated issue see https://github.com/MarcusWolschon/osmeditor4android/issues/1203 however it doesn't happen for me, just retagged the area with no issue, but pls discuss the specific issue there. 

Do you have any developer options turned on on the device? In particular the "Don't keep activities" option?

**Comment by matkoniecz** [comment]
Nothing interesting.

Developer options themselves are enabled. I Enabled USB debugging, my PC fingerprint(?) added to trusted installation source (? - I do not remember exact phrasing), mobile data always active.

**Comment by matkoniecz** [comment]
I will retest it further, but it seems to be easiest to trigger with ways that belong to many relations. Way with 12 bus line relations freezes for 3-5 seconds on almost every attempt.

**Comment by simonpoole** [comment]
How large are the relations? Or better, a link to one of the ways in question.

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/way/372635877 takes about 3 seconds to enter/leave tag menu what is noticeable lag

entering https://www.openstreetmap.org/relation/9106255 feels instant

**Comment by simonpoole** [comment]
~3 seconds is not an extreme performance regression though. The reason for the delay in this case is simply that the PropertyEditor doesn't work directly on the elements but on a copy (there are some, at least historically, good reasons for this), this is quite lightweight for tags, but is rather complex for elements that are members on many large relations (the relations need to be passed to the Activity as you can remove and add them in the property editor). And when the PropertyEditor is exited essentially the same thing in reverse happens. 

I do have plans for refactoring the code (which however will make it less robust vs issues in the PropertyEditor), but that is 1-2 man months and for version 15 the androidx migration was a priority. But in any case it would seem unlikely that this is your issue with freezing.

**Comment by matkoniecz** [comment]
> ~3 seconds is not an extreme performance regression though. 

I agree, and I am still trying to reliably replicate hanging for multiple minutes. It is the best what I can reliably replicate for now.

**Comment by simonpoole** [comment]
Any further input?

**Comment by matkoniecz** [comment]
No, Vespucci now works fine.
