### ISSUE TITLE
java.util.Base64 doesn't exist pre Android 26

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1200]
@simon04 1st thank you for working on signpost.

But https://github.com/mttkay/signpost/commit/6a43cc7ab0742b569b60790e43e1e3d866462979#diff-35e06e987973ab4357aadacfb0b20c83 and https://github.com/mttkay/signpost/commit/9cd425629900190e2f07ced369bfc0d609041a34 breaks signpost on pre-Android SDK 26 devices (that's Android 8 so very recent) as java.util.Base64 doesn't exist on those devices. Any chance you could revert the commits? 

Reporting here as issues are not enabled on the signpost repo.

This causes a crash on authorisation or re-authorisation, if the issue can't be fixed upstream, best fix for now would be to revert to the old signpost version (longer term fix unclear).

**Comment by simonpoole** [comment]
Reverted to https://github.com/MarcusWolschon/osmeditor4android/commit/b08383fdc646562d99345ed90430c270b1d657d0 for 15.0, if this gets addressed upstream either in signpost of desugaring support by google we can switch in 15.1 or later.

**Comment by simon04** [comment]
Sorry for my summer hibernate… I've added a minimal Base64 implementation and released [signpost 2.1.1](https://github.com/mttkay/signpost/releases/tag/oauth-signpost-2.1.1)

**Comment by simonpoole** [comment]
I was assuming so much :-) Thanks.

**Comment by simonpoole** [comment]
Re-upgraded in https://github.com/MarcusWolschon/osmeditor4android/commit/4c73fb89c1ed40f4b5180f4809912332422d587d
