### ISSUE TITLE
onFocusChange called after onDestroyView

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1203]
07-28 09:10:32.758 D/PropertyEditor(13044): onStop
07-28 09:10:32.759 D/PropertyEditor(13044): onDestroy
07-28 09:10:32.761 D/TagFormFragment(13044): onDestroyView
07-28 09:10:32.766 D/TagEditorFragment(13044): onFocusChange value

this crashes because getView returns null in the onFocusChange listener.

@matkoniecz where you doing anything special, rotating the device and exiting the PropertyEditor at the same time for example?

**Comment by matkoniecz** [comment]
No. I tried again at home and it crashed again in one case (way that I linked) and on second area it worked this time.

I also tried with disabled autorotation, it also crashed.

**Comment by simonpoole** [comment]
After some fiddling I was able to recreate the issue semi-repeatable, seems to be an issue with androidx as I was unable to recreate with 14.1. 

Unluckily the change in https://github.com/MarcusWolschon/osmeditor4android/commit/52a9f46b676419cb511994548007a4fc867d1f16 doesn't seem to stop the onFocusChange Listener from being called so I've added a specific to this crash fix in https://github.com/MarcusWolschon/osmeditor4android/commit/c3b2f3598c7f568e0c02076811f151dab87748f5 which is not satisfactory.

**Comment by matkoniecz** [comment]
Thanks for quaick! So for now temporarily leaving beta and reinstalling again should be used as a workaround in my case?

**Comment by simonpoole** [comment]
> 
> 
> Thanks for quick fix! So for now temporarily leaving beta and reinstalling again should be used as a workaround in my case?

Yes, or simply not using the key-value editor I suspect will work too.

**Comment by simonpoole** [comment]
Note: you can always install the debug version which is signed with my dev key https://drive.google.com/file/d/1fuvcYWk8bEyBGS8n9mI-PhkJpWLW3-Cs/view?usp=sharing this has the advantage that the crash dumps are more legible (theoretically they are a bit slower too, but I doubt that that is really noticeable). You will have to uninstall the currently installed version though.

**Comment by matkoniecz** [comment]
I can confirm that this version works well.
