### ISSUE TITLE
Modif

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1206]
Description:
---

Modif pour installation d'arrêt de bus sur la maps 

Device info:
---
<table>
<tr><td>App version</td><td>14.1.6.0</td></tr>
<tr><td>App version code</td><td>1409</td></tr>
<tr><td>Android build version</td><td>C432B136</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>JMM-L22C432B136</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWJMM</td></tr>
<tr><td>Device model</td><td>JMM-L22</td></tr>
<tr><td>Device product name</td><td>JMM-L22</td></tr>
<tr><td>Device hardware name</td><td>mt6755</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Alan56230</td></tr>
</table>

**Comment by simonpoole** [comment]
Could you explain what you exactly want to do? You can naturally already add bus stops with the corresponding presets and you can even add a filter just to see them.

**Comment by simonpoole** [comment]
Stale
