### ISSUE TITLE
Replace deprecated github auth

### ISSUE THREAD

**Issue by johantiden** [MarcusWolschon/osmeditor4android#1210]
## Vespucci Version
15.0.0.6

## Download source
github code

## Device (Manufacturer and Model)
Pixel 3 XL crosshatch

## Android Version 
10

## Behaviour/Symptoms
Trying to use the "Provide feedback" feature results in an email to the user, saying this:

"
Hi @johantiden,

On August 7th, 2020 at 21:12 (UTC) you used a password to access an endpoint through the GitHub API using GitHubJava/2.1.5:

https://api.github.com/repositories/32623844/issues

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.

Thanks,
The GitHub Team
"

Also, in the app I get a wrong password warning and the reports is not sent. 

## Expected Behaviour
The reports is suvcessfully sent. 

## How to recreate
Try sending a Provide feedback report. 

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
I have 2FA enabled, which doesn't seem to be supported.

**Comment by simonpoole** [comment]
There currently isn't a solution for this as this is a 3rd party component, that simply doesn't support anything else.

The workaround for now is to use the semi-anonymous way of submitting issues.

One possible workaround would be to allow setting of a users github personal access token, instead of using the generic one.

**Comment by simonpoole** [comment]
See also https://github.com/MarcusWolschon/osmeditor4android/issues/1064

**Comment by johantiden** [comment]
I suggest closing this one then, since #1064 already covers it.

**Comment by simonpoole** [comment]
Using login/password disabled in https://github.com/MarcusWolschon/osmeditor4android/commit/c1b066a97d2da9fbdd754e856c5be1f743e01c5e (use of the feedback activity can be disabled and the github website be used instead).
