### ISSUE TITLE
Crash when downloading data

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1215]
Description:
---

Trying to download data of following area:
https://www.openstreetmap.org/#map=17/49.20628/16.15459&layers=N

Actually I want to download  "Lipová" street.

Vespucci crashing every time when trying to download this area. When I start app after the crash data is not downloaded.

Crash report send two times, ~14:50 9.8.2020 (GMT+2)

reported by @kudlav

Device info:
---
<table>
<tr><td>App version</td><td>15.0.0.6</td></tr>
<tr><td>App version code</td><td>1501</td></tr>
<tr><td>Android build version</td><td>A405FNXXU3BTD4</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.A405FNXXU3BTD4</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a40</td></tr>
<tr><td>Device model</td><td>SM-A405FN</td></tr>
<tr><td>Device product name</td><td>a40eea</td></tr>
<tr><td>Device hardware name</td><td>exynos7904</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>kudlav</td></tr>
</table>

**Comment by simonpoole** [comment]
This looks like it is https://twitter.com/vespucci_editor/status/1291722743629647880 as it doesn't crash on startup, simply replacing the data when downloading should resolve the issue.

**Comment by kudlav** [comment]
Download and replace data option solved the problem. Thanks a lot, I wasn't
on Twitter for a while.

Feel free to close the issue.

--
Vladan Kudláč

Dne ne 9. 8. 2020 15:05 uživatel Simon Poole <notifications@github.com>
napsal:
