### ISSUE TITLE
Trop de beeps au démarrage de lapp

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1216]
Description:
---

J'ai eu au moins une vingtaine de beeps au démarrage, très peu discret et ennuyant!

Device info:
---
<table>
<tr><td>App version</td><td>14.1.7.0</td></tr>
<tr><td>App version code</td><td>1410</td></tr>
<tr><td>Android build version</td><td>G930FXXS8ETC6</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>R16NW.G930FXXS8ETC6</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>herolte</td></tr>
<tr><td>Device model</td><td>SM-G930F</td></tr>
<tr><td>Device product name</td><td>heroltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8890</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>HB9DTX</td></tr>
</table>

**Comment by johantiden** [comment]
Semi-related: https://github.com/MarcusWolschon/osmeditor4android/pull/1214

**Comment by simonpoole** [comment]
@johantiden except that they are running 14.1.7 which doesn't beep at all.

@HB9DTX can you explain what you are doing when it beeps?

**Comment by simonpoole** [comment]
After discussion with @HB9DTX seems as if this was simply due to a large number of notifications at the specific location.
