### ISSUE TITLE
Feature proposal: Preload data via GPX track for offline mapping

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#1217]
# Scenario
- When travelling I usually plan the route in advance. Specially, I prepare a GPX track for bicycle trips to loosely follow along. I imagine the same applies for people who hike.

# Proposal
- It would be great if the Vespucci app could use the GPX track in order to download the respective area around the track upfront. A certain buffer might be useful to download data left and right of the track to some extend.
- I consider this especially useful as I am not using a data connection on my device - which means I do use Vespucci fully offline.

**Comment by simonpoole** [comment]
While we currently don't have such a facility, you can use offline data from http://mapsplit.poole.ch/ (or generate such sources yourself) which is generated every morning from data that is roughly one hour old (all the caveats about using old data apply).

**Comment by simonpoole** [comment]
The current plan is to implement this via a GPX track replay function.

**Comment by johnjohndoe** [comment]
Which version will contain this feature? Is there documentation for how to apply it?

**Comment by simonpoole** [comment]
17.1 will have it, use
- load track
- turn on location based download
- turn on follow GPS
- playback the track

Note that you will have to up the auto prune limit massively or else the data will be deleted again.
