### ISSUE TITLE
Feature proposal: Intent action for phone, email, links

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#1218]
# Scenario
- I am using the Vespucci app not only as an editor - but often to look up certain places.

# Proposal
- It would be useful if certain field in the tag information dialog would be clickable and trigger a suitable `Intent` action.

## Examples tags & Intent actions
- [x] `email`, ... : Launch email app
- [x] `phone`, `contact:phone`, ... : Launch phone app
- [x] `website`, ... : Launch browser app

**Comment by simonpoole** [comment]
Note the website tag value is already linkified in the information dialog.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/59ef96795c020023dbde5ff23b1e1c803a0aa6c8 adds this by simply adding them as links
