### ISSUE TITLE
priority of presets not clear (if 2 presets have items with the same matches)

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1219]
## Vespucci Version
14.1.7
[perhaps no problem in 15.x.x? – Google Play Store still has only v14.1.7 ...]

## Download source
google play store

## Device (Manufacturer and Model)
Huawei – Honor 7X

## Android Version 
9.1.0

## My problem ...

Hello!

I just started to play around with a custom preset with quite personal preferences with some items (e.g. special icons, another order or selection of the attributes, combo or multiselect attributes instead of a text field and so on).

It is working fine (at least if activated as the only preset), except for one thing: for me the priority of presets (and their item matches) is not clear at all and quite confusing, if more than one preset is activated in Vespucci’s preferences.

What I simply want to do is:

1. I use simonpoole’s „beautified-JOSM-preset“ as my main preset (latest version, it’s now v1.9.5) and keep it active in the preset list (and update it from time to time).
2. I would like to have my own personal preset with some NEW items but also with some of the SAME items as in simonpoole’s preset (with the same key matches!), but another structure of the attributes (or other icons or whatever).

Then I would expect that a preset which is higher in Vespucci's preset list has a higher priority (or a lower, if the list works top-down – also not clear). This preset with the higher priority should always win, if there is a „matching tie“. So that I can be sure that items (with the same matches) in my personal custom preset always have a higher priority than those in simonpoole’s preset.

But it’s not like that. It is quite confusing. I have to play around with activating/deactivating the 2 presets or move them up/down, and then with some luck and after some tries it seems to have the priority I wanted to have – but independant of the position in the list. Or more precise: it seems to be better if my preset is over simonpoole’s preset in the list, but this alone doesn’t work always or at once. And I am not even 100% sure, if it really has to be higher in the list …

I could not find any systematics.

Can anybody help? Or does this require a code change/improvement in Vespucci and it’s (memory) management of presets (items in presets)?

**Comment by simonpoole** [comment]
Currently the ordering of the presets is only used for arranging them in the preset selection view.

The matching currently doesn't take that in to account, the tie breaking (that is when two presets have the same weight) simply prefers the first one it encountered, but that in turn depends on which order they are returned in from internal data structures which currently are unordered (so while this will be deterministic with the exactly the same preset configuration and same app version, it could easily change with both).

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/6a87e2456716d91ecafdafdb7bc2a2d568eedd02 as this was really a minor change, as an exception to the rule this will be available in the next maintenance release (likely September).
