### ISSUE TITLE
[Question] Does Vespucci allows to share PoIs map with contacts ?

### ISSUE THREAD

**Issue by KaKi87** [MarcusWolschon/osmeditor4android#1220]

**Comment by simonpoole** [comment]
Could you explain a bit more what the question is?

**Comment by KaKi87** [comment]
Does Vespucci allows to create a list of "favorite" locations, then exporting it as a file, importing it into someone else's smartphone, and retrieve the list ?

**Comment by simonpoole** [comment]
Currently this isn't possible. There is an issue here https://github.com/MarcusWolschon/osmeditor4android/issues/951 that I would potential implement, that would provide such a facility, and I suppose that could be extended to allow export/import.

**Comment by KaKi87** [comment]
Alright, thanks for answering.
