### ISSUE TITLE
Version 15.0.2 (maybe 15.*) not recording any elevation by default to gpx

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1223]
Description:
---

I just noticed that the gpx tracks recorded with version 15.0.2 beta don't store elevation at all. I then find out the (aledgedly) new option to use the pressure sensor for altitude, which seems to be disabled by default, I didn't enable it yet but i fear it might interfere with the default behavihour.

Device info:
---
<table>
<tr><td>App version</td><td>15.0.2.0</td></tr>
<tr><td>App version code</td><td>1502</td></tr>
<tr><td>Android build version</td><td>G965FXXUAETG3</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.G965FXXUAETG3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>star2lte</td></tr>
<tr><td>Device model</td><td>SM-G965F</td></tr>
<tr><td>Device product name</td><td>star2ltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos9810</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>pixelk</td></tr>
</table>

**Comment by simonpoole** [comment]
Tip added in https://github.com/MarcusWolschon/osmeditor4android/commit/1193c7edd5bb9ba36fe087fb98da842f144aea61
