### ISSUE TITLE
Vespucci always crashing after edit in Strasbourg 

### ISSUE THREAD

**Issue by erik55** [MarcusWolschon/osmeditor4android#1224]
## Vespucci Version

?? Always crashes. 
## Download source

Play store
## Device (Manufacturer and Model)

Samsung Galaxy S9

## Android Version 

Android 10
## Behaviour/Symptoms

Always crashes on start. How can I reset? 
## Expected Behaviour

Start normally or ask if I want to reset. 
## How to recreate

Edit Kaiserplatz in Strasbourg. 
## Crash dump submitted (no or yes + date)

Yes, today. Some minutes ago. 
## Any other potentially relevant information

I have already uninstalled and reinstalled the program, but still always crashing on start.

**Comment by simonpoole** [comment]
That would seem to be the issue mention here http://vespucci.io/help/en/15.0.0%20Release%20notes/#upgrading-from-previous-versions however if you deinstalled, the data should have been deleted. I would however still suggest explicitly deleting the data in app management.

**Comment by erik55** [comment]
Yes, deleting app data worked. 

Thank you. 

Maybe the app should give a hint to this or delete the app data itself after several crashes.

**Comment by simonpoole** [comment]
You should probably follow https://twitter.com/vespucci_editor/status/1291722743629647880 (or at least regularly check) if you install beta versions, by definition they will now and then have issues. Direct upgrades from 14.1 should work without issues.
