### ISSUE TITLE
Standort

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1225]
Description:
---

Eine Standortfreigabe ist nur während der Nutzung der App möglich. Option "immer" fehlt. Den Tracker beim Wandern mitlaufen lassen ist nicht möglich, da beim Abschalten des Displays das tracken unterbricht. 

Device info:
---
<table>
<tr><td>App version</td><td>15.0.3.0</td></tr>
<tr><td>App version code</td><td>1504</td></tr>
<tr><td>Android build version</td><td>42d236</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QPES30.79-124-2</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>sofiar</td></tr>
<tr><td>Device model</td><td>moto g(8) power</td></tr>
<tr><td>Device product name</td><td>sofiar_reteu</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
Das ist einerseits ein Missverständnis: der Aufzeichungsdienst läuft als ein sogenannter "Foreground-Service" dies zählt durchaus als "während der Nutzung der App", anderseits gab es in 15.0.1 bis .3 ein spezifisches Problem auf Android 10 (aufgrund einer schlecht von google dokumentierten Änderung im Verhalten), mit dem Resultat, dass die Aufzeichnung tatsächlich unterbrochen wurde. Dies ist in 15.0.4 aber behoben, die bereits auf dem Playstore verfügbar ist.

Siehe https://github.com/MarcusWolschon/osmeditor4android/issues/1222
