### ISSUE TITLE
Standort

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1226]
Description:
---

Option fehlt, den Standort immer freizugeben. Das tracken unterbricht, sobald das Display ausgeschaltet wird.

Device info:
---
<table>
<tr><td>App version</td><td>15.0.3.0</td></tr>
<tr><td>App version code</td><td>1504</td></tr>
<tr><td>Android build version</td><td>42d236</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QPES30.79-124-2</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>sofiar</td></tr>
<tr><td>Device model</td><td>moto g(8) power</td></tr>
<tr><td>Device product name</td><td>sofiar_reteu</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Clemens H</td></tr>
</table>

**Comment by HolgerJeromin** [comment]
Ref #1222
Should be fixed with 15.0.2 :-(

**Comment by simonpoole** [comment]
@HolgerJeromin 15.0.4
