### ISSUE TITLE
"Add custom imagery" option seems to have gone missing?

### ISSUE THREAD

**Issue by SomeoneElseOSM** [MarcusWolschon/osmeditor4android#1227]
## Vespucci Version
15.0.3

## Download source
Google Play Store

## Device (Manufacturer and Model)
Sony L3

## Android Version 
Android 8.1

## Behaviour/Symptoms
The "custom imagery" option described in https://vespucci.io/tutorials/custom_imagery/ seems to have disappeared.

## Expected Behaviour
I'd follow https://vespucci.io/tutorials/custom_imagery/ and be able to add new custom imagery layers.

## How to recreate
Follow https://vespucci.io/tutorials/custom_imagery/ and note that there is no "Custom imagery" option as documented on the "Advanced preferences" screen.

## Crash dump submitted (no or yes + date)
no, no crash occurs.

## Any other potentially relevant information
If previous custom imagery has been added, it can still be selected as a layer

**Comment by simonpoole** [comment]
Doc bug, the entry is now actually on the Preferences page (at least it should be).

**Comment by SomeoneElseOSM** [comment]
Thanks - doing it from there works.

**Comment by simonpoole** [comment]
Documentation has been updated
