### ISSUE TITLE
Autodownload nach Standort...

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1229]
Description:
---

Dieses neue feature ist vermutlich Ursache für meine Crashs, denn das Häkchen war gesetzt und begann den download der ganzen Weltkarte...

Device info:
---
<table>
<tr><td>App version</td><td>15.0.3.0</td></tr>
<tr><td>App version code</td><td>1504</td></tr>
<tr><td>Android build version</td><td>G930FXXS8ETC6</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>R16NW.G930FXXS8ETC6</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>herolte</td></tr>
<tr><td>Device model</td><td>SM-G930F</td></tr>
<tr><td>Device product name</td><td>heroltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8890</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>cepesko</td></tr>
</table>

**Comment by simonpoole** [comment]
Hast du ein Crash Sump geschickt? Das wird wohl an was anderem liegen, da auch wenn Vespucci verstellt wäre, die maximale Grösse der Downloads durch die API beschränkt wird.

**Comment by simonpoole** [comment]
Original report https://github.com/MarcusWolschon/osmeditor4android/issues/1228

**Comment by simonpoole** [comment]
The "location based download" doesn't automatically prune the data, nor does it (because the download is not triggered manually) show a warning when too much data has been loaded, so it is conceivable that over time any reasonable limit is exceeded.

**Comment by simonpoole** [comment]
Auto pruning added in https://github.com/MarcusWolschon/osmeditor4android/commit/75a8d1e8e28d219526d4606317af7bd830220562
