### ISSUE TITLE
Vespucci Data Styling – FILL_AND_STROKE doesn't work always

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1230]
I have a suspicion, that the style "FILL_AND_STROKE" does not work if it's applied in a nested `<feature>` element. 

E.g. "landuse=construction" here:

```
    <feature type="way" tags="landuse" area="true" updateWidth="true" widthFactor="2.0" color="8871BE80" style="STROKE" cap="BUTT" join="MITER" pathPattern="border_right">
        <feature type="way" tags="landuse=construction" color="88996633" style="FILL_AND_STROKE" pathPattern="" />
        <feature type="way" tags="landuse=residential" minVisibleZoom="10" color="88888888" />
        <feature type="way" tags="landuse=quarry" color="88d8a2a2" />
        <feature type="way" tags="landuse=military" color="88af2626" />
        <feature type="way" tags="landuse=forest" minVisibleZoom="10" color="8800BE00" />
        <feature type="way" tags="landuse=industrial" minVisibleZoom="10" color="88A3709A" />
        <feature type="way" tags="landuse=commercial" minVisibleZoom="10" color="88A3709A" />
        <feature type="way" tags="landuse=railway" minVisibleZoom="10" color="88A3709A" />
    </feature>
```

In Vespucci there is only a STROKE ... (I use v15.0.3). If I write a line like 

`<feature type="way" tags="landuse=construction" updateWidth="true" minVisibleZoom="10" color="88996633" style="FILL_AND_STROKE" cap="BUTT" join="MITER"/>`

BEFORE the block above, it works ...

**Comment by jajajaneeneenee** [comment]
I have to correct myself: it's not because if the NESTED element, it's seems to be caused by `pathPattern="border_right"` in the parent element ... if I remove this, the FILL_AND_STROKE also works in the nested element of "landuse=construction" ...

`pathPattern=""` in the line of "landuse=construction" doesn't seem to be enough …

**Comment by simonpoole** [comment]
Yes, it was an issue with cascaded path patterns not working correctly, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/41373de09cf9ffc00dcf0e72bc353bfdeb1f91fa
