### ISSUE TITLE
U.S. Forest Service Roads imagery

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1234]
Description:
---

When I select the U.S. Forest Service Roads map I get nothing displayed.

Device info:
---
<table>
<tr><td>App version</td><td>15.0.3.0</td></tr>
<tr><td>App version code</td><td>1504</td></tr>
<tr><td>Android build version</td><td>J727T1UVS7BTC1</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>M1AJQ.J727T1UVS7BTC1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>j7popeltemtr</td></tr>
<tr><td>Device model</td><td>SM-J727T1</td></tr>
<tr><td>Device product name</td><td>j7popeltemtr</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7870</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>AdamTheWebMan</td></tr>
</table>

**Comment by simonpoole** [comment]
The source that is configured for JOSM for this layer is erroring https://josm.openstreetmap.de/wiki/Maps/USA%20Country#U.S.ForestRoadsOverlay

The corresponding ELI source works, simplest short term solution is to add that as a custom layer: 

https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/sources/north-america/us/USForestService-overlay.geojson
