### ISSUE TITLE
löscht nicht

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1236]
Description:
---

lädt immer wieder gelöschten punkt
z.b. hädike Marktstraße 12 köthen umgezogen

Device info:
---
<table>
<tr><td>App version</td><td>15.0.3.0</td></tr>
<tr><td>App version code</td><td>1504</td></tr>
<tr><td>Android build version</td><td>1572951078</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>CUBOT_POWER_8071C_V25_20191214</td></tr>
<tr><td>Device brand</td><td>CUBOT</td></tr>
<tr><td>Device manufacturer</td><td>CUBOT</td></tr>
<tr><td>Device name</td><td>CUBOT_POWER</td></tr>
<tr><td>Device model</td><td>CUBOT_POWER</td></tr>
<tr><td>Device product name</td><td>CUBOT_POWER</td></tr>
<tr><td>Device hardware name</td><td>mt6763T</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Win32netsky</td></tr>
</table>

**Comment by simonpoole** [comment]
Könntest du bitte genauer erklären was genau nicht funktioniert?

**Comment by simonpoole** [comment]
No feedback, closing.
