### ISSUE TITLE
Redesign roundabout template

### ISSUE THREAD

**Issue by Mannivu** [MarcusWolschon/osmeditor4android#1240]
Roundabout template doesn't have some standard tag that can be useful and has some useless tags (see image below). I think it should be redesigned to add the `lit` and `surface` tags and remove the `oneway` tag (since is already implemented by the `junction=roundabout` tag and follows the roundabout direction) and the `overtaking` one.

<img src="https://user-images.githubusercontent.com/42747216/93336959-c07cb500-f828-11ea-9e3d-df797afa536d.jpg" width="250px"/>

**Comment by simonpoole** [comment]
Preset issues belong in the preset repo https://github.com/simonpoole/beautified-JOSM-preset/issues as I can't move issues from here to there, could you open an issue there and copy the contents?

**Comment by Mannivu** [comment]
Sure, I've opened https://github.com/simonpoole/beautified-JOSM-preset/issues/208
