### ISSUE TITLE
Fehlermeldungen "Problem mit den Hintergrundkacheln"

### ISSUE THREAD

**Issue by dx125-osm** [MarcusWolschon/osmeditor4android#1242]
## Vespucci Version
15.0.3.0; 15.0.4.0 

## Download source
Google Play

## Device (Manufacturer and Model)
LG G8sThinQ

## Android Version 
10

## Behaviour/Symptoms
Fehlermeldung bei App Start, und bei Datendownload 

## Expected Behaviour
Fehlermeldungen abstellen bitte

## How to recreate
?

## Crash dump submitted (no or yes + date)
ja, heute

## Any other potentially relevant information
keine SD Karte verwendet, nur interner Speicher 128 GB im Gerät
https://forum.openstreetmap.org/viewtopic.php?id=70622

**Comment by simonpoole** [comment]
One device custom configuration was still uses 512x512px tiles
