### ISSUE TITLE
Weighting of items in a preset XML file not clear (= matching priority in detail)

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1244]
## Vespucci Version
15.0.4

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Description

I have another problem quite similar to #1219, but now with the matching of items inside of ONE preset XML file ...

The [Vespucci Tutorial page](http://vespucci.io/tutorials/presets/) explains the matching in this way (but not in detail): _„This is done in an iterative fashion: the best matching preset is found (weighting presets with fixed key-value tuples higher than such with variable values), then all tags that can be found in linked presets are added (no separate header displayed) and this process is repeated until their are either no tags left or no preset match can be found.“_

But I ran into an insolvable problem when trying to create a preset for **entrances** where I wanted to have separate icons (and matches when editing) for entrances with house numbers and entrances without house numbers. And to make it easier, here is my code only for the case „entrance=yes“ (in my preset I also differentiated between entrance=yes and entrance=home or exit, service, main, and so on … with different icons):

```
<?xml version="1.0"?>
<presets version="1.0.0" xmlns="http://josm.openstreetmap.de/tagging-preset-1.0" shortdescription="Entrance Test" description="Entrance Test">
    <item name="Entrance YES 01" icon="entrance_small_size.png" type="node" preset_name_label="true">
      <key key="entrance" value="yes" />
      <text key="addr:housenumber" text="Housenumber" match="none" />
    </item> <!-- Entrance without housenumber -->

    <item name="Entrance YES 02 – with HN" icon="entrance_WITH_HN_small_size.png" type="node" preset_name_label="true">
      <key key="entrance" value="yes" />
      <text key="addr:housenumber" text="Housenumber" match="key!" />
    </item> <!-- Entrance with housenumber -->
</presets>
```

Preset ZIP file: [entrance_minimal.zip](https://github.com/MarcusWolschon/osmeditor4android/files/5286826/entrance_minimal.zip)

#### The desired result (display of icons in Vespucci and matching) should be like that:

![state2=OK](https://user-images.githubusercontent.com/48966999/94342876-870c2c80-0014-11eb-8f35-29e572e4706c.png)

- left node: entrance=yes (no addr:housenumber)
- right node: entrance=yes + addr:housenumber=123 [the icon should not display the real house number value, only a blue symbol … of course it would be nicer to be able to display the value as text to the node as with JOSM's MapCSS, but that’s not the topic here; a symbol would be enough for me]

#### But what I got was:

... a change between these 2 states of icon display if doing an „update preset“ command multiple times (mostly it changes after 3 to 5 tries):

![state1=WRONG](https://user-images.githubusercontent.com/48966999/94342879-94291b80-0014-11eb-936e-53d4365a7bf1.png) and  ![state2=OK](https://user-images.githubusercontent.com/48966999/94342881-9a1efc80-0014-11eb-9ab8-19d1086af1fa.png)

#### And to make it even more confusing: 

- In case of the second (= correct display) of icons: Vespucci shows the name/icon of the item "Entrance YES 02 – with HN“ for both nodes! So matching seems to be correct for the icon display, but not for editing.
- And in case of the first display of icons: if editing the nodes, Vespucci shows the name/icon of the item "Entrance YES 01“ for both nodes!

#### Other variants of code:

If I changed code line 11 to `<text key="addr:housenumber" text="Housenumber" match="key" />`, the icons changed with multiple „update preset“ commands between:

![state2=OK](https://user-images.githubusercontent.com/48966999/94342892-a905af00-0014-11eb-9f94-1536a524fb76.png) and ![state3=WRONG](https://user-images.githubusercontent.com/48966999/94342894-ad31cc80-0014-11eb-99a7-0b20fec7a971.png)

- I also tried to add „object_keys“ values like „entrance“ and „addr:housenumber“ to the preset – no change.
- And leaving out `<text key="addr:housenumber" text="Housenumber" match="none" />` in the first item also did not change anything.

## Expected Behaviour

- An item with a fixed key-value match plus a match with a key with variable values should outweight an item with only a fixed key-value match.
- An item with a fixed key-value match plus 2 matches with keys with variable values should outweight an item with a fixed key-value match plus 1 match with a key with variable values.
- An item with a fixed key-value match only should outweight another item with the same fixed key-value match and a negative match with a key with variable values (by match=„key!“).
- And so on …

## Some other questions / nebulosities

1. What is the exact effect/reason of an „object_keys“ attribute? The tutorial page only says „comma separated list of top-level keys“. Could it help here or would it be neccessary?
2. Is the order of the attributes in an „object_keys“ list of any importance? Or their alphabetical order?
3. Is the alphabetical order of items (according to their names) of any importance for the matching/weighting? (Or only for the order in the Vespucci presets window?) Or is the order of items in the XML file of any importance?
4. What happens if 2 different items weight the same with 2 different nodes (perhaps because of matchings with differents keys) – which one wins? Does any order of items counts in such a case? (There should be a logic of any kind.)

## Conclusion

It would be nice to have a clear description of the weighting algorithm which covers all these questions (best on the tutorial page!) to be able to create a preset XML with fine granulated items in a logical and clear way …

**Comment by simonpoole** [comment]
The behaviour you are seeing is likely because addr: tags are (hardwired) special cased during matching, mainly because otherwise lots of objects would match as addresses because of the typical number of addr tags an object would have. 

This however predates the current iteration of matching and the hardwiring might be avoidable with the fine grained control we have now.

To your specific questions:

1. Vespucci needs some way of determining which keys indicate real world objects vs. attributes (for example color) for matching to work without surprising results. 
2. No. However as said, adding addr tags to the list will simply add in confusion, because of the special casing of addr tags.
3./4. The candidate preset list for matching is generated by looping over the the preset "files" and then retrieving the possible matches by looping over the relevant keys of the object in question. Scoring then iterates over the candidates and returns the preset item with the highest score as match, in the case of the same score, the first item encountered with that score is returned. This is however only "deterministic" at the level of preset files, that is that items in earlier files are guaranteed to be earlier in the candidate list and therefore have "higher priority" than items from later files. The order of items from the same preset file however is dependent on the order of tags on the object and the specific implementation details of the used data structures (which in this case don't guarantee any specific ordering).

**Comment by simonpoole** [comment]
So I played around with this a bit, the simple, straightforward 

```
<?xml version="1.0"?>
<presets version="1.0.0" xmlns="http://josm.openstreetmap.de/tagging-preset-1.0" shortdescription="Entrance Test" description="Entrance Test">
    <item name="Entrance YES 01" icon="entrance_small_size.png" type="node" preset_name_label="true">
      <key key="entrance" value="yes" />
      <text key="addr:housenumber" text="Housenumber" match="none" />
    </item> <!-- Entrance without housenumber -->

    <item name="Entrance YES 02 – with HN" icon="entrance_WITH_HN_small_size.png" type="node" preset_name_label="true">
      <key key="entrance" value="yes" />
      <text key="addr:housenumber" text="Housenumber" match="key" />
    </item> <!-- Entrance with housenumber -->
</presets>
```

seems to work reliably for me. 

Setting object_keys isn't necessary as entrance is already considered as an object and you specifically don't want addr:housenumber to be treated as a separate object. Scoring will give both presets the same value for the entrance key, but the 2nd will be chosen for entrances with a house number as the the addr:housnumber key will match. Note using "key!" decreases the scoring if the key matches, the opposite of what you want to do.  

What could be a bit confusing is that in the PropertyEditor you will always see the variant "with house number" as the when the preset is applied it will add the "addr:housenumber" key and that will only get removed when the tags are saved. You could partially get around that by putting the house number tag in an optional section.

**Comment by jajajaneeneenee** [comment]
Hello!

Thank you a lot for playing around with this and the explanations. I do understand what you wrote ... except for the explanation of "key!".  Are you rally sure? I read the definition in the JOSM docs (because the Vespucci tutorial page does not say anything to these matching values) – see [https://josm.openstreetmap.de/doc/org/openstreetmap/josm/gui/tagging/presets/items/KeyedItem.html](https://josm.openstreetmap.de/doc/org/openstreetmap/josm/gui/tagging/presets/items/KeyedItem.html) and it says:

- none: neutral, i.e., do not consider this item for matching
- key: positive if key matches, neutral otherwise
- key!: positive if key matches, negative otherwise
- keyvalue: positive if key and value matches, neutral otherwise
- keyvalue!: positive if key and value matches, negative otherwise
Note that for a match, at least one positive and no negative is required. Default is "keyvalue!" for Key and "none" for Text, Combo, MultiSelect and Check.

So my understanding of "key!" is: it gives a negative score if a key does NOT match and the effect is, that the item will definitively NOT match if this key does not match – and this supersedes any positive matching score of this item **("no negative is required")**. So, there is **not** a subtraction from the positive scoring...  I this a wrong conclusion? Or is the mechanism in Vespucci different as in JOSM? (Then you urgently should explain it on the tutorial page!)

But now to your code:
this is the same code as I already tried to use and described in the section "Other variants of code" of my first posting. I tried it again now, and also RESTARTED Vespucci now (after adding and activating the test preset). And first it looked OK, but after the 3rd „update preset“ command in the prefs (did you also try this???), it look again like this:

![state3=WRONG](https://user-images.githubusercontent.com/48966999/97804580-21354500-1c51-11eb-9ec6-73ba43f39887.png)

- left node: entrance=yes (no addr:housenumber)
- right node: entrance=yes + addr:housenumber=123 

And I only activated this test preset (and used Vespucci v15.0.5). So it does not seems to work reliably for me.

Should a restart of Vespucci by pressing the BACK button of Android and confirming the message "Do you really want to close the application?" be enough to clear the cache for icons and preset matching? 

By the way: Would it not be a good idea if the cache would be emptied, if you change something in the list of "managing presets" in the prefs (activate/deactivate a preset file, or changing the order)? I was expecting that ...

=> What do we do now?

**Comment by jajajaneeneenee** [comment]
Another small question: can I see somewhere which keys are already considered as objects (and do not have to be added to object_keys)?

**Comment by simonpoole** [comment]
The issue should be fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/b6149b9fffc9c562039e6dd3bbce1bb28ba918dc

Yes, I did misspoke when I described how key! worked, however the implementation was in principle correct, except there was a actually a bug in that while a non-existing key was counted negative, an existing key wasn't. keyvalue! did this correctly so this was just an oversight (mainly due to that we currently can't do unit tests on the preset code, so have to rely on integration tests which don't go so deep). tl;dr with key! everything works as expected.

The inconsistent behaviour on updating the preset was simply due to unpredictable ordering when processing the preset items, and without the key! an object with just an entrance tag could match both presets with the same scoring.

**Comment by simonpoole** [comment]
> 
> 
> Another small question: can I see somewhere which keys are already considered as objects (and do not have to be added to object_keys)?

https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/java/de/blau/android/osm/Tags.java#L393

The reason there is a hardwired version is that at least for the common tags this always needs to work even if there are no appropriate presets.

**Comment by jajajaneeneenee** [comment]
OK – thank you! Then I look forward to v15.1! If "key!" works fine, I think I can finish my entrance presets ...

**Comment by simonpoole** [comment]
The fix will be in the November maintenance update of 15.0 as it doesn't depend on anything 15.1 specific.

**Comment by jajajaneeneenee** [comment]
That's fine, too! I thought the next release would be 15.1 ...

**Comment by simonpoole** [comment]
There are, nearly always, monthly maintenance releases (of the current release). Both that and the first beta of 15.1 are likely a week or so away.
