### ISSUE TITLE
opening_hours with SH/PH get corrupted

### ISSUE THREAD

**Issue by schuetzm** [MarcusWolschon/osmeditor4android#1245]
When an object has opening_hours like `SH Mo 10:00-12:00` (i.e. school holidays that fall on a Monday), they automatically get rewritten to `SH SH,Mo 10:00-12:00` (school holidays that fall on a school holiday or a Monday = all school holidays), which it then complains about as being invalid.

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/OpeningHoursParser/commit/eb9ce14c885e0a9f57f555db370fde554765c5d0 this will be included in the October maintenance release.
