### ISSUE TITLE
"The imagery source is erroring" is hard to understand

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#1246]
## Vespucci Version
git master 20201003

## Download source
github, built it myself

## Device (Manufacturer and Model)
Google Pixel XL

## Android Version 
lineage, aosp 8.1

## Behaviour/Symptoms
toasts appear about "imagery error", but I don't find anything in logcat

## Expected Behaviour
I expect:
  * the toast to name the imagery, and if the error is just "tried to fetch zoom 21 and that didn't work" but the source is not in general broken, not to be so loud
  * the error to also show up in logcat

## How to recreate

With bing, I think, in the US, zoom in way too far for the imagery.  But really see ./main/java/de/blau/android/views/layers/MapTilesLayer.java and note that there is a toast for too many errors, and nothing specific is sent to logcat.  So I am having a hard time telling what if anything is really wrong.

(I'm not really clear on the zoom-in-geojson plan.   I added MassGIS 2019 Orthos to ELI, and it showed up in josm, with maxzoom 7 vs 6, and probably that's right, but apparently ELI doesn't check as much.   I would expect most sources to have correct maxzoom by now.  But maybe it's not about this.)

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/67ceab802c80b3d12ec8085f22545ada4e3f4e08 addresses this partially by indicating the layer causing the issue.

There are numerous reasons why it is difficult to handle this in a reasonable fashion. In any case you should only get the message once, and that only after 50 tiles have errored. This illustrates one of the issues, if you log everything that causes tile errors you are just going to swamp the log and potentially overwrite other important information, in most cases they are harmless in any case, that is mainly configuration issues for the tile source. Bing is special in multiple ways, including in not having a consistent max zoom, and other annoyances.
