### ISSUE TITLE
Timestamps are missing in GPX when using TCP client provider

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#1248]
When using internal, the GPX file has timestamps like you'd expect.  When using the TCP client provider against an F9P, but also against rtklib on an Emlid Reach, all the times are 0 (unix timeval).

Observed for a while, but also with yesterday's master.

**Comment by simonpoole** [comment]
SHould be fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/125731726756ae003c6a71fdd6f1efabb3abf1c2 (can you test with master?)

**Comment by gdt** [comment]
I built master (plus updateImageryFromJOSM because I just put my local state 2019 leaf-off orthos in the databases), and can confirm that I get timestamps in the gpx files.  Thanks very much for the quick fix.
