### ISSUE TITLE
Geotag pictures taken by Vespucci that are not geotagged by photo app

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#1249]
I took some pictures with Vespucci (from slightly old code), and they show up in the Pictures directory of the Vespucci directory.  I expect exif tags with GPS information, but don't find that.  Perhaps the intent is to sync up with gpx, but given the ability to show geotagged photos, I expected to produce them.   (I don't want to use some other camera app because  that isn't getting the high-accuracy location from NMEA TCP client.)

I'm happy to retest if this is believed fixed recently.

**Comment by simonpoole** [comment]
Vespucci simply uses whatever app is available/you've selected on the device, so this is not going to use a high precision input.  I recommend opencamera as that will add cardinal direction to the EXIF.

Using the camera API itself would add a lot of complexity, that is: nearly doubling the code base for the app if we use the numbers from opencamera. But we could potentially overwrite existing lat/lon fields in the images, or extend opencamera to accept lat/log as parameters.

**Comment by gdt** [comment]
That explains it.  I have the system camera as default, configured not to geotag (because not geotagging when one shouldn't is important), and opencamera, configured to geotag.

FWIW, OsmAnd seems to put the coordinates in a uuencoded kind of way in the name, perhaps for this reason.  I know this is theoretically useful as it can be decoded but have not found this a useful workflow addition.

Writing the position into the exif tags afterwards sounds good to me.

**Comment by simonpoole** [comment]
Resolved by adding a preference for the camera app to use. As Android 11 doesn't allow third party apps to select the target app for image capture intents we've had to add a preference that allows to select the app you want to use with Vespucci (this works for all Android versions).

See https://github.com/MarcusWolschon/osmeditor4android/pull/1461
