### ISSUE TITLE
Splitting a way corrupts step_count and duration

### ISSUE THREAD

**Issue by DerDings** [MarcusWolschon/osmeditor4android#1251]
## Vespucci Version
15.0.4 (probably among others) 

## Download source

Google Play Store 

## Device (Manufacturer and Model)

Galaxy Tab A (2016)

## Android Version 

9

## Behaviour/Symptoms

When a way with a value for `step_count` or `duration` (e.g. `step_count=5`) is splitted, two ways are created with the same value for this key, which leads to the total value of both ways being doubled (two ways with `step_count=5` in a row => 10 steps in total) 

## Expected Behaviour

There should be a warning at least, like there is when turning around a one-way street. 

## How to recreate

1. Find steps that have step_count: https://overpass-turbo.eu/s/YQR. 
2. Split the way with Vespucci. (maybe you need to add a new node in the middle first to make it splittable) 

## Crash dump submitted (no or yes + date)

no

## Any other potentially relevant information

[same issue in StreetComplete](https://github.com/westnordost/StreetComplete/issues/2145)
May be also present in other editors.

**Comment by simonpoole** [comment]
This equally applies when merging. 

To really handle this properly, it really needs an indication that this is a metric that could change on merging and splitting in the preset configuration.

**Comment by DerDings** [comment]
Then should it rather be reported to [presets](https://github.com/simonpoole/beautified-JOSM-preset)?

**Comment by simonpoole** [comment]
> 
> 
> Then should it rather be reported to [presets](https://github.com/simonpoole/beautified-JOSM-preset)?

Nope, first we need to figure out a reasonable way of handling this, and that needs to be coded first.

**Comment by DerDings** [comment]
There are vivid discussions on this topic in https://github.com/westnordost/StreetComplete/issues/2145 and https://github.com/openstreetmap/iD/issues/8069. We should wait for their outcome to avoid people writing the same stuff three times.

**Comment by simonpoole** [comment]
parking:lane:both:capacity, parking:lane:left:capacity and parking:lane:right:capacity and the *:disabled variants are candidates for the same treatment.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/66729ba63eb1ed85d1305d35deadba6e6160639f for merging and https://github.com/MarcusWolschon/osmeditor4android/commit/c9978a21bdebd0c2f8d2dcb1b4d32501d1b4d8f3 for splitting. As in particular the later commit is rather far reaching I currently don't intend to back port this.

Demo https://twitter.com/vespucci_editor/status/1318221680351862789
