### ISSUE TITLE
Android Gesture Buttons

### ISSUE THREAD

**Issue by eightys3v3n** [MarcusWolschon/osmeditor4android#1256]
Description:
---

When using the gesture based navigations on Android 10, the app doesn't allow me to exit by swiping where the home button is. It just opens the menus. See video for example.
https://youtu.be/n9DMtwMcDtE

Device info:
---
<table>
<tr><td>App version</td><td>15.0.5.0</td></tr>
<tr><td>App version code</td><td>1506</td></tr>
<tr><td>Android build version</td><td>G975WVLU4ETH7</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.G975WVLU4ETH7</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>beyond2q</td></tr>
<tr><td>Device model</td><td>SM-G975W</td></tr>
<tr><td>Device product name</td><td>beyond2qltecs</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
General note: the home button doesn't actually exit (any) app, Android will typically pause the current activity but that's it. 

There shouldn't be any issues since version 10 has been released as we detect the mode that has been selected and configure the app appropriately (and this works on all Samsung devices with Android 10 I've tested this on satisfactory). See http://vespucci.io/tutorials/faq/#navigation-gestures-on-android-9-and-later 

Could you check your full screen settings in Vespucci, and a further question is do you actually have the Android 10 navigation gestures turned on, or the prior version?

**Comment by eightys3v3n** [comment]
Yes, not actually exit the app, but allow me to leave the app. It should be
noted that the multi-task gesture also didn't work.

Full screen mode was sent to Auto. Setting it to Never solves the problem,
navigation gestures work as expected. It is possible that Samsung has
changed the navigation offered. Here's a screen shot of my navigation
settings.

In sounds like on my phone Auto is enabling full screen mode, which
interferes with gesture navigations. While this may be intended it makes it
much harder to exit the app.

Regards, Terrence

**Comment by simonpoole** [comment]
The screenshot doesn't seem to have made it.

**Comment by eightys3v3n** [comment]
![Screenshot_20201015-090325_Settings.png](https://user-images.githubusercontent.com/15176881/96174490-9cbf9400-0ee6-11eb-8652-9b91fbb63fea.png)

**Comment by simonpoole** [comment]
That seems to indicate that you have the pre-android 10 gestures configured and I suspect that we are not detecting that properly (if it is even possible).

**Comment by eightys3v3n** [comment]
Ah, alright. So this sounds like a Samsung problem more than an app problem. I'll just switch to Never and wait for Samsung to update.

**Comment by simonpoole** [comment]
I tested with a couple of Samsung devices here in both gesture modes and they all seemed to work (fullscreen mode set to Auto in Vespucci, which is the default). Just to be sure: do you have the three gesture fields of one gesture field plus swipe from left or right configured?

**Comment by eightys3v3n** [comment]
I have the three bottom gestures and the right side Edge gesture
configured. I have also put the back gesture on the left.

Regards, Terrence

**Comment by simonpoole** [comment]
Closing as not actionable (as yet to find a device that shows the described behaviour).
