### ISSUE TITLE
Vespucci crashes if a value in a preset contains the ampersand character &

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1259]
## Vespucci Version
15.0.5

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
If a preset contains the ampersand character "&" in a value, e.g. in a combo attribute like `values="Company Name 1,Company Name 2,Company Miller & Sons"` or `<key key="xyz" value="xyz & xyz"/>`, and it is **NOT** encoded as` &#x26; `then Vespucci crashes at once if editing any node or way.

But the preset xml is UTF-8, and I suppose it should not be necessary to encode any special character in this way. Or is the ampersand an exception and it is not possible to change this? (If yes, are there other exceptions?)

## Expected Behaviour
Vespucci should not crash and it should not be necessary to encode the ampersand with `&#x26;` (IMO).

## How to recreate
obvious

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
no

**Comment by simonpoole** [comment]
Upps, seems as if I didn't save my comment on this, sorry.

& is a special character in XML and always needs to be escaped, typically with `&amp;`

Naturally the app shouldn't crash in any case, can you "re-crash" and submit the dump with a corresponding comment?

**Comment by simonpoole** [comment]
Did you by chance just have the preset with the error configured?

**Comment by jajajaneeneenee** [comment]
I just sent a error report. And here is a test preset.

Vespucci crashed after I positioned it over my other presets in the list (or if it's the only active preset file), then left the preferences and tried to edit a node.

Strange: if I position it e.g. UNDER your "beautified JOSM-Preset", it does not crash (but also don't shows the test item in the list of preset items). Is there anything wrong with my test xml? (When I reported the problem, I had the ampersand character in another quite large personal preset file, which is also on top of other preset files.)

Here is the test preset:
[ampersand_test.zip](https://github.com/MarcusWolschon/osmeditor4android/files/5425064/ampersand_test.zip)

**Comment by simonpoole** [comment]
For various reasons the app assumes that there is at least one valid preset, if the only one configured doesn't get created because of an error, then there is currently an unresolvable issue. However the case where it just depends on the ordering shouldn't happen and likely there is simply a overlooked NPE somewhere (haven't checked the crash dump yet).

**Comment by simonpoole** [comment]
The actual crash was due to small regression, but I've taken the opportunity to fix that and improve the handling of parsing failures more generally in https://github.com/MarcusWolschon/osmeditor4android/commit/88269f676b943c37a7c77cc1da51ad64c8eb5900
