### ISSUE TITLE
Can't turn off auto-download

### ISSUE THREAD

**Issue by blackboxlogic** [MarcusWolschon/osmeditor4android#1265]
## Vespucci Version
Vespucci 15.0.5
Flavor: current
Maximum avaliable memory 536870912
Total memory used 76423536
Tile Cache MAPNIK usage Size 0 of maximum 67108864 #entries 0
Tile Cache ESRIWORLDIMAGERYCLARITY usage Size 66846720 of maximum 67108864 #entries 255
Tile Cache BING usage Size 0 of maximum 67108864 #entries 0
Tile Cache MAPBOX_LOCATOR_OVERLAY usage Size 0 of maximum 67108864 #entries 0
State file size 88679 last changed 2020-10-24 16:50:19
Bug state file size 123147 last changed 2020-10-24 16:50:19
Relations (current/API): 6/0
Ways (current/API): 11/3
Nodes (current/Waynodes/API): 1075/1334/6
Available location providers
passive enabled true
network enabled true
gps enabled true

## Download source
Fdroid

## Device (Manufacturer and Model)
Google pixel 3

## Android Version 
Latest (11)

## Behaviour/Symptoms
Can't turn off auto-download. When I pan the map, osm features download automatically and I can't turn it off.

## Expected Behaviour
I expect a setting which works allow user to turn auto-download on or off

## How to recreate
Pan the map. See features download. Go to settings menu, see that there is no seeing to turn it off.

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
This sense like a recent (new) issue.

**Comment by simonpoole** [comment]
You found the setting at least once (because  default is that pan and zoom download is off). 

In the download/upload menu is where the setting is located., see also http://vespucci.io/help/en/Main map display/#available-actions

**Comment by blackboxlogic** [comment]
Thank you! Found it!
I was expecting it in
Preferences /advanced preferences / data and edit settings.
The description for the section includes "auto download" but doesn't seem to have any settings related to it.

**Comment by simonpoole** [comment]
That is for some rarely used parameters (for example up to which speed it is active), not for turning it on / off which you want to be able to reach in a hurry.
