### ISSUE TITLE
Vespucci beeping and crashes when tapped the status bar

### ISSUE THREAD

**Issue by Yarjk32** [MarcusWolschon/osmeditor4android#1269]
## Vespucci Version
15.0.5

## Download source
Google Play Store

## Device (Manufacturer and Model)
Meizu M3s

## Android Version 
Android 5.1 (Flyme 6.3.2.0G)

## Behaviour/Symptoms
Device loudly beeps when tapped on the status bar while viewing or editing a map. If tapped multiply times in a row, then the app crashes. ([Screenrecord](https://github.com/MarcusWolschon/osmeditor4android/files/5445328/Screenrecord.zip)) Also, beeps can't be muted.

## Expected Behaviour
Usually, it should view the top of a list in some apps. But, when editing a map, it should do nothing.

## How to reproduce
Tap on the status bar once or many times in a row while viewing or editing a map.

## Crash dump submitted
Yes. Around 13:40 UTC+2:00, October 27, 2020

## Any other potentially relevant information
Another OSM contributor can't reproduce it at the previous version of Vespucci (15.0.4). Actually, this bug is not very important because there is no reason to tap the status bar while using the app. But, the user can accidentally tap on it and be scared.

**Comment by simonpoole** [comment]
Normally there is no problem accessing the status bar at all, however something on your device is generating key press events when you are tapping on the notification bar and sending them to Vespucci (which then in turn beeps because you've sent it an unknown key event). The crash seems to happen in the somewhere in the android libraries because it is getting keypress events when it doesn't expect them.

"That isn't normal"

Do you have any apps or similar that could cause the issue? In any case something worth trying is forcing fullscreen mode off see http://vespucci.io/help/en/Advanced%20preferences/ and checking if anything changes.

**Comment by Yarjk32** [comment]
I don't find any apps that can cause the issue. Forcing fullscreen mode doesn't help. If I hide the status bar, then I can't reproduce the issue by touching the top of the screen. But, if I manually show the status bar, then I can tap on it and get a beep.
Also, I had installed Vespucci on Lenovo and Xiaomi, and I can't reproduce this issue on them.
In my opinion, this issue can be reproduced only on Meizu, because of their Flyme firmware.

**Comment by simonpoole** [comment]
Misunderstanding ... I wanted you to try and force fullscreen mode -off-.

**Comment by Yarjk32** [comment]
Sorry. Forcing the fullscreen mode *off* doesn't help.

**Comment by simonpoole** [comment]
OK, what happens looks awfully like if https://forum.xda-developers.com/xposed/modules/mod-statusbar-scroll-to-refactored-t4036751 is installed or that Meizu provides the functionality in their firmware. Not a bad thing per se. 

What causes the crash seems to be the calls to ToneGenerator that can cause a crash, and that seems to be a known, not Meizu specifc issue.

Keycode received:

`Unknown short cut key code 122 key event KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_MOVE_HOME, scanCode=0, metaState=META_CTRL_ON, flags=0x0, repeatCount=0, eventTime=183930936, downTime=183930936, deviceId=-1, source=0x0 }`

**Comment by simonpoole** [comment]
Crash fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/113b02cb1b234680238c774a524dd43076b66592

**Comment by simonpoole** [comment]
@Yarjk32 any further feedback on the "scroll to top" functionality?

**Comment by Yarjk32** [comment]
This feature sometimes can be useful. For example, I can scroll either a web page or an Instagram feed to the top. I am satisfied with that feature.
But it seems that developers should manually add support for this feature to their apps.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/55786246eea9005b787333ba94929fac47faa004 ignores the generated key code and stops the beeping.

**Comment by Yarjk32** [comment]
#### Tested in 15.0.6, the issue is fixed.
---
Your app is awesome! I can easily do map edits on the ground with my smartphone.
