### ISSUE TITLE
Unable to submit map Notes in fullscreen mode.

### ISSUE THREAD

**Issue by treestryder** [MarcusWolschon/osmeditor4android#1272]
Description:
---

The keyboard hides the submit button on my Pixel 3, when submitting a Note update, in fullscreen mode. Ironically, when I took a screenshot the keyboard went away.

Device info:
---
<table>
<tr><td>App version</td><td>15.0.5.0</td></tr>
<tr><td>App version code</td><td>1506</td></tr>
<tr><td>Android build version</td><td>6782484</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RP1A.201005.004</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>blueline</td></tr>
<tr><td>Device model</td><td>Pixel 3</td></tr>
<tr><td>Device product name</td><td>blueline</td></tr>
<tr><td>Device hardware name</td><td>blueline</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by treestryder** [comment]
![Screenshot_20201030-150348](https://user-images.githubusercontent.com/3682967/97747568-8eff3680-1ac2-11eb-8bf9-5c7c276efc9c.png)

**Comment by treestryder** [comment]
Also, it felt like the State kept changing back to Open.

**Comment by simonpoole** [comment]
The back button or the corresponding gestures should remove the keyboard. If that isn't possible see http://vespucci.io/tutorials/faq/#fullscreen-mode-doesnt-work-properly

**Comment by treestryder** [comment]
Thanks. I probably should have looked to see if that was a known issue.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/65e7b9d59daa8f5f074e3b4559e3aac97c7f50c7 seems to fix the issue in a reasonable fashion.
