### ISSUE TITLE
Do not offer un-selectable objects in 'expand selection' mode

### ISSUE THREAD

**Issue by woodpeck** [MarcusWolschon/osmeditor4android#1275]
(Feature request)

When you tap on a location with multiple objects, Vespucci shows a pop-up that lets you choose which one you want. 

Some objects are selectable (like an OSM node), others are not selectable (like a bug marker or a GeoJSON feature).

When you are in "expand selection" mode, and you click on a location that contains only one selectable object (but also one or more non-selectable objects), then displaying a pop-up that lets you choose does not make sense; Vespucci could, in this mode, immediately add the single selectable object to the selection.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/8a072663f04480167e8fde402de30d5146be456f
