### ISSUE TITLE
Provide per tag deprecation support in presets

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1276]
This should work similar to deprecated in preset items, if the tag is present it should be displayed as belonging to the object, however it shouldn't be offered as a new tag when the preset item is applied.

**Comment by ltog** [comment]
@simonpoole : Good to know this is planned... I'm looking forward to it.

**Comment by simonpoole** [comment]
Done in https://github.com/MarcusWolschon/osmeditor4android/pull/1468
