### ISSUE TITLE
Storage access changes for Android 11

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1278]
https://developer.android.com/about/versions/11/privacy/storage

Possible way around it 

https://developer.android.com/training/data-storage/manage-all-files

however requires review by google which is likely to be impractical.

More info https://medium.com/androiddevelopers/android-11-storage-faq-78cefea52b7c

and https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage

Specific user configurable/generated files that need to be handled

- [x] photos
- [x] (data) styles
- [x] custom presets
- [x] MBTiles (large files)
- [x] Auto-preset

**Comment by simonpoole** [comment]
See also https://github.com/MarcusWolschon/osmeditor4android/issues/1281

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/b19a80535b7a64e8164605ca4e09f8b455fa9036 should solve the issue for preset files.

**Comment by simonpoole** [comment]
Oddities from issues on Note 8:

- mbtiles file on sdcard
`05-17 19:15:22.574: I/de.blau.android.util.SelectFile(18310): isExternalStorageDocument
05-17 19:15:22.575: E/de.blau.android.util.SelectFile(18310): unknown doc type 0000-0000
05-17 19:15:22.575: E/de.blau.android.util.SelectFile(18310): Unable to determine how to handle Uri content://com.android.externalstorage.documents/document/0000-0000%3AAndroid%2Fdata%2Fde.blau.android%2Ffiles%2Fswitzerland.mbtiles
`
- the same on internal external storage
`05-17 19:37:23.539: I/de.blau.android.util.SelectFile(23722): isExternalStorageDocument
05-17 19:37:23.542: I/MBTilePro...DataBase(23722): Creating database instance for file:/storage/emulated/0/Android/data/de.blau.android/files/switzerland.mbtiles
05-17 19:37:23.542: D/de.blau.android.util.SelectFile(23722): getPath uri: file:/storage/emulated/0/Android/data/de.blau.android/files/switzerland.mbtiles
`

**Comment by simonpoole** [comment]
Originally I had assumed that the best course of action would be to move the contents of the "Vespucci" directory to the app specific directory in Android/data (that would have been Android/data/de,blau,android), as that directory continues to be accessible by the app and retains UNIXy File semantics and APIs.

However in their deep wisdom, unfathomable for mere mortals, google has made anything in the "Android" directory inaccessible to the system file picker in Android 11. Yes, that means that the app cannot use the system file picker to select files for reading / writing in it's "own" directory. But not only that, even an app with the new file management permissions cannot access such a directory (including dedicated file manager apps). This rules out storing anything there that might need to be selected via an user interaction. And this gotcha already applies regardless of if the app is targeting Android 11 or not.

Google doesn't offer a clear alternative storage location for non-media files (after all you are supposed to be a drone non-stop consuming youtube and not doing anything else), but storing these in the "Download" directory may work short term, that is till google closes this loophole.

**Comment by ChiefMikeK** [comment]
I'd suggest a sub directory  /Download/0-de.blau

**Comment by simonpoole** [comment]
Done in https://github.com/MarcusWolschon/osmeditor4android/commit/46494d914782dfbb71fd84b50c429dc424922de0 (the new dir is Download/Vespucci
