### ISSUE TITLE
"Remove node from way" not counted as change made to the way

### ISSUE THREAD

**Issue by DerDings** [MarcusWolschon/osmeditor4android#1282]
## Vespucci Version

15.0.6

## Download source

google play store

## Device (Manufacturer and Model)

Sony G8441

## Android Version 

9

## Behaviour/Symptoms

If a node is removed from a way, this change is shown on the screen and listed as an undo checkpoint. However, the change isn't shown in the uploadable changes. So, it also doesn't get uploaded. 

## Expected Behaviour

When a node is removed from a way locally, this change can be uploaded to osm

## How to recreate

1. download OSM data
2. select a way (let's call it way «A») 
3. use "remove node from way"
4. select a node (with tags) to remove from the way
5. -> no badge counter is shown on the "Transfer…" menu
6. open the "Transfer…" menu
7. -> the "upload data to osm server" option is disabled
8. make a change to an object not associated with way «A» (we'll call it way «B»)
9. upload data to osm server
10. -> the osm server will receive the change made to way «B», but not the change made to way «A».

## Crash dump submitted (no or yes + date)

no

## Any other potentially relevant information

If additional properties of the way are changed (added node or changed tags) after removing a node, ALL changes are uploaded, i. e. the node is removed as expected.

If a node is removed that is not part of any other way and does not have any tags, the node gets deleted. Thus, the deletion is shown as an uploadable change, but the change made to the way is not listed as uploadable change. I didn't try what happens when uploading this, since I don't know if it corrupts data.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/750576af2d8be0d7b6289b7d2bda572b35c02bf5 note there is was no danger of corrupting data as the upload would simply fail because of a reference conflict (the error went unnoticed because typically there will be other edits to the way that would cause it to be uploaded anyway).
