### ISSUE TITLE
"remove node from way" deletes nodes which are part of relations without warning

### ISSUE THREAD

**Issue by DerDings** [MarcusWolschon/osmeditor4android#1283]
## Vespucci Version

15.0.6

## Download source

google play store

## Device (Manufacturer and Model)

Sony G8441

## Android Version 

9

## Behaviour/Symptoms

When removing an untagged node from a way it gets deleted, even if it is part of a relation. The relation gets corrupted.

## Expected Behaviour

When removing a node, that is member of a relation, from a way only the way changes, the node and the relation remain unchanged.

## How to recreate

1. download osm data
2. Create a way with at least three (untagged) nodes
3. Select two of the nodes and create a relation consisting of those two nodes. The relation may be tagged with `type=site` and `name=TestRelation` to be easily distinguishable
4. select the way
5. use "remove node from way"
6. select one of the nodes which are part of the relation to be removed from the way
7. -> the node will be deleted without the usual "you are about to delete a node that is member of one or more relations" warning
8. tap on the other node that was part of the relation
9. select the relation
10. -> a warning "Empty relation" is shown

## Crash dump submitted (no or yes + date)

no

## Any other potentially relevant information

probably related to  #1282

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/e8008c843429b918ba17fa1df3acddeda7ef6229 adds a warning, the issue isn't related to #1282
