### ISSUE TITLE
[GitHub] Deprecation Notice

### ISSUE THREAD

**Issue by rouelibre1** [MarcusWolschon/osmeditor4android#1285]
I received this notification via email when creating #1284 from the app

> Hi @rouelibre1,
> 
> On November 13th, 2020 at 02:02 (UTC) you used a password to access an endpoint through the GitHub API using GitHubJava/2.1.5:
> 
> https://api.github.com/repositories/32623844/issues
> 
> Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

**Comment by simonpoole** [comment]
See the 15.1 Beta release notes https://github.com/MarcusWolschon/osmeditor4android/blob/master/documentation/docs/help/en/15.1.0%20Release%20notes.md "Feedback form behaviour changes".
