### ISSUE TITLE
Upload freezes while low reception

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1286]
Description:
---

The upload to OSM function freezes the app as I had low cell phone reception (OS displays: 4G, 1 bar). Restart the app don't help. I get black screen. Restart smartphone helps. Problem is reproductive. Sad to loose actual GPS record.

Device info:
---
<table>
<tr><td>App version</td><td>15.0.6.0</td></tr>
<tr><td>App version code</td><td>1507</td></tr>
<tr><td>Android build version</td><td>A105FNXXU4BTI2</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.A105FNXXU4BTI2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a10</td></tr>
<tr><td>Device model</td><td>SM-A105FN</td></tr>
<tr><td>Device product name</td><td>a10eea</td></tr>
<tr><td>Device hardware name</td><td>exynos7884B</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by simonpoole** [comment]
Are you referring to the GPX upload function? All uploads are async by nature and shouldn't block the app at all, can you describe how far you got with the upload and when exactly it started hanging?

Note that you can always simply save a recorded track and upload later.

**Comment by simonpoole** [comment]
It seems as if you were not authenticated with the OSM API (because your OSM user name is missing from the report), if you are not authenticated, the app will try to do that first, and if the connection is very slow that could be problematic. Best do that immediately after you installed the app.

**Comment by simonpoole** [comment]
No response, closing.
