### ISSUE TITLE
Vespucci 15.0.5 crashes on startup

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1287]
## Vespucci Version
15.0.5

## Download source
Fdroid

## Device (Manufacturer and Model)
HUAWEI P30

## Android Version 
10

## Behaviour/Symptoms
Crash on startup 

## Expected Behaviour
Don't crash 😊

## How to recreate
Open the app

## Crash dump submitted (no or yes + date)
Yes, 2020-11-14 9:35 CET

## Any other potentially relevant information
After update from 14.1

**Comment by simonpoole** [comment]
This seems to happen in some not clearly defined circumstances, outside of what is mentioned in the release notes. In any clearing the data for the app, should resolve the issue.

**Comment by Discostu36** [comment]
Clearing app data solved the issue.
