### ISSUE TITLE
Vespucci crash when "Tags changed" resumed

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1288]
Description:
---

1. Select way
2. Select next segment of way using multiselect 
3. Merge objects with conflicting tags
4. _Tags changed_ dialog appears
5. Switch to another app and then switch back to Vespucci
6. Click to show _Merged tags_ details
7. The app will crash

I was merging ways and I had to answer to incoming call and after call, the app crashed. So it can occur in real life.

Reported mutliple times ~11:45 20.11.2020 (UTC+01:00), email vladankudlac@gmail.com included.

Device info:
---
<table>
<tr><td>App version</td><td>15.1.0.1</td></tr>
<tr><td>App version code</td><td>1600</td></tr>
<tr><td>Android build version</td><td>A405FNXXS3BTI3</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.A405FNXXS3BTI3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a40</td></tr>
<tr><td>Device model</td><td>SM-A405FN</td></tr>
<tr><td>Device product name</td><td>a40eea</td></tr>
<tr><td>Device hardware name</td><td>exynos7904</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/kudlav"/>kudlav</A></td></tr>
</table>

**Comment by kudlav** [comment]
reported by @kudlav

this screen:
![Screenshot_20201120-114006_Vespucci](https://user-images.githubusercontent.com/11516259/99791909-9dbb9500-2b26-11eb-8e1e-46b09bb4aca4.png)

**Comment by simonpoole** [comment]
Thanks for the excellent report.

I can recreate locally, it is likely an issue with restoring saved state for the dialog.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/8ca0e17a0ddc1c80ec3ccd40d64c99363207c31f
