### ISSUE TITLE
Trunk road preset bug

### ISSUE THREAD

**Issue by davidpnewton** [MarcusWolschon/osmeditor4android#1294]
## Vespucci Version
15.1.0 BETA 1

## Download source
Google Play Store

## Device (Manufacturer and Model)
Samsung Galaxy A70

## Android Version 
10

## Behaviour/Symptoms
When using the trunk road preset and pressing the Apply preset with optional button on an existing location using the preset instead of empty values of the optional tags appearing ready to fill in, one of the tag pairs is filled in. Motorroad=yes is always populated. There are very few non-motorway roads in the UK which are so-called special roads, ie with restrictions on pedestrian access etc. So this key pair always being set to =yes is inappropriate.

## Expected Behaviour
As currently except motorroad=yes is not set.

## How to recreate
See behaviour/symptoms section

## Crash dump submitted (no or yes + date)
N/A

**Comment by simonpoole** [comment]
Thanks for the report. 
This is a preset issue and really belongs in https://github.com/simonpoole/beautified-JOSM-preset  In any case this goes back to the original JOSM preset so is not new behaviour, but I agree this probably needs country specific tagging variants, and for the general case should not be set.

**Comment by simonpoole** [comment]
Issue opened in preset repo https://github.com/simonpoole/beautified-JOSM-preset/issues/225
