### ISSUE TITLE
Geoimage.at MaxRes is erroring

### ISSUE THREAD

**Issue by MakiWolf** [MarcusWolschon/osmeditor4android#1298]
Geoimage.at MaxRes is erroring in the App, but in JOSM it works.
**Steps to reproduce:**
Add background imagery layer and select Geoimage.at MaxRes
![error](https://user-images.githubusercontent.com/73300633/101047744-5f8c8f80-3582-11eb-98c3-0fdf3506d426.gif)

App Version 15.0.8.0

**Comment by simonpoole** [comment]
Seems as if the hostname has changed 

`12-03 16:18:14.486: E/MapTileDownloader(4294): Error Downloading MapTile. Exception: UnknownHostException https://gis.bmlfuw.gv.at/wmsgw/?key=4d80de696cd562a63ce463a58a61488d&service=WMS&LAYERS=Luftbild&STYLES=default&FORMAT=image/jpeg&CRS=EPSG:3857&WIDTH=256&HEIGHT=256&BBOX=1452609.285531491,6073380.519426964,1452915.0336446315,6073686.267540105&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap Unable to resolve host "gis.bmlfuw.gv.at": No address associated with hostname
`

You can update the imagery from JOSM and then it will work (as there is no guarantee that the internal ids stay the same when switching source, you will need to switch to something else and back again). You should also report the error at https://github.com/osmlab/editor-layer-index/ as it wiill effect iD etc too. @grischard  FYI
