### ISSUE TITLE
I always get ERR_CONNECTION_REFUSED error when try to upload data

### ISSUE THREAD

**Issue by thuryn** [MarcusWolschon/osmeditor4android#1300]
## Vespucci Version
Latest production and beta

## Download source
Google play

## Device (Manufacturer and Model)
Xiaomi Mi9

## Android Version 
Android 10

**Comment by simonpoole** [comment]
Do downloads work?

**Comment by thuryn** [comment]
Yes, downloads works fine. There is no need to authenticate for downloads I suppose

**Comment by simonpoole** [comment]
Yes downloads don't need authenticated,  but I asked just to be sure that the API url is correct. 

The error would not seem to be authentication related, so might be an issue with the rails frontend you are connecting to, does the problem still persist currently?

**Comment by thuryn** [comment]
Yes, it still does not work. I can send you a short screencst to see the problem. Or I can send you some log of your app to check it.

**Comment by simonpoole** [comment]
The log would be helpful, best try to upload and immediately after the failure go to the main menu "Debug" entry and immediately send the crash dump. Please include a reference to this ticket with the dump.

**Comment by thuryn** [comment]
It just started to work ... the app probably fears of debugging and started to work 😀 But still, I'm really interested what was wrong for the next time it occurs

**Comment by simonpoole** [comment]
> 
> 
> It just started to work ... the app probably fears of debugging and started to work 😀 But still, I'm really interested what was wrong for the next time it occurs

As said it is nearly guaranteed to be something that wasn't working with one of the rails frontends, or a network related issue, getting the log might have simply given OSM ops some pointers as to what was broken.
