### ISSUE TITLE
Undo while creating way broken

### ISSUE THREAD

**Issue by johantiden** [MarcusWolschon/osmeditor4android#1305]
## Vespucci Version
15.1.1 (github) 

## Download source
Github 

## Device (Manufacturer and Model)
Oneplus 8 Pro

## Android Version 
11

## Behaviour/Symptoms
Wrong state is undone. The last node is deleted instead of movement. 

## Expected Behaviour
Movement undone

## How to recreate
1. Start creating a new way
2. Add three nodes
3. Move the whole way by dragging it
4. Press undo

**Comment by simonpoole** [comment]
While it might be a bit confusing that is not expected to work.

It's essentially the price of having all the changes in one undo checkpoint, and as a result there is no actual checkpoint that we could restore at this point. One could argue that moving nodes or the way should be blocked while in this mode I'll have a look at thst.

**Comment by johantiden** [comment]
That would solve the behavior of undo. Sure. In this instance I was trying to pan and ended up moving the way. Clicking undo didn't help. I had to start over.

I guess there are situations where you would want to move the way a little though. I don't know.

A second argument for blocking movement is that bug reports like this would stop popping up :)

**Comment by simonpoole** [comment]
I've decided on blocking for now.  Pre-refactoring of way creation this used to work (that's why it wasn't already blocked) however previously each node added created its own undo checkpoint which made undoing a change after a larger number of nodes very painful.

**Comment by simonpoole** [comment]
Behaviour changed in https://github.com/MarcusWolschon/osmeditor4android/commit/447d4d5e068dd3d93310a0250117138bf02666a2
