### ISSUE TITLE
Translation rendering error

### ISSUE THREAD

**Issue by debyos** [MarcusWolschon/osmeditor4android#1308]
## Vespucci Version
15.1.2

## Download source
google play store

## Device (Manufacturer and Model)
Samsung Galaxy S50

## Android Version 
10

## Behaviour/Symptoms
Preset translation rendering error:
when mapping `railway=level_crossing` or `railway=level_crossing` the appearing "barrier" is

master_preset.xml:4913(combo:text|group:Leisure|**preset:Dog_Park|key:barrier**):
rather than
master_preset.xml:3200(combo:text|group:Railway|**preset:Level_Crossing|key:crossing:barrier**):

## Expected Behaviour
Translations should be aligned well.

## How to recreate
Just try to map it with a translated version. (I tried it in Hungarian but I suppose it should be the same in each language version.)

Thank you!

**Comment by simonpoole** [comment]
Please open this in the preset repo (I unluckily can't move it there). Thanks,

**Comment by debyos** [comment]
Sorry, I thought this was a coding issue. I will put it there.
