### ISSUE TITLE
Issues and crashes with Bing imagery without Internet connectivity

### ISSUE THREAD

**Issue by voussoir** [MarcusWolschon/osmeditor4android#1310]
Hi, thanks for your software. Being able to edit on mobile is much better than taking pictures and doing it at home. I'm having some issues with background imagery crashes.

## Vespucci Version

15.1.0 Beta

## Download source

F-Droid

## Device (Manufacturer and Model)

LG G8X Thinq

## Android Version 

Android 10 kernel 4.14.117

## Behaviour/Symptoms

Map comes up blank when imagery should be cached:

1. Settings > Advanced > Layer download and storage > Tile cache size (Mine is 300 MB)
2. Quit app
3. Disable wifi
4. Start app
5. Map appears blank instead of showing cached tiles

Crash on open when wifi is off:

1. Enable background imagery (I'm using Bing)
2. Quit app
3. Disable wifi
4. Start app
5. Crash

Crash on enable imagery when wifi is off:

1. Disable background imagery
2. Quit app
3. Disable wifi
4. Start app
5. Enable imagery with wifi still off
6. Crash

I recorded these issues in a screen capture here: https://youtu.be/pXF0YuE6qMs

## Crash dump submitted (no or yes + date)

Yes, 2020-12-19 (this morning)

Let me know what else I can add to help debug. Thanks!

**Comment by simonpoole** [comment]
Hi. Does this happen with a different background selected, that is, not Bing?

**Comment by simonpoole** [comment]
I had a look at the dump, this is Bing specific, Bing is bit special as we get meta data from bing before we can retrieve the tiles and this isn't persisted over restarts of the app, but naturally it shouldn't crash.

**Comment by voussoir** [comment]
Sorry for not checking other imagery sources. You're right, I tried MapBox and OSM Standard and they don't have these issues. Thanks for your fast followup.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/211b39ab66cc9f9902c2f433489b6f1e99ae7a2b Thanks again for the excellent report.
