### ISSUE TITLE
Zoom level problem with very short way after clicking on a Osmose link to the way

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1312]
## Vespucci Version
15.1.2

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
I got a very strange behaviour of Vespucci with the way #716941799 ([https://www.openstreetmap.org/way/716941799#map=19/49.23494/6.97158](https://www.openstreetmap.org/way/716941799#map=19/49.23494/6.97158)) which has a Osmose bug due to a missing segregated tag (I hope nobody fixed it in the meantime ...). And it doesn't matter that the bicycle tag does not make much sense here, it's only an example ...

This way only has a length of 0.02 m (I checked it in JOSM and it is shown in the information window), and when you tap on the link in the Osmose window, Vespucci jumps to a very high zoom level .... and the horizontal and vertical rulers only show "0.0 – 0.0 – 0.0 – ...".

And you are quite stuck ... the – and + zoom buttons don't work anymore. And everything seems be be slowed down a lot ... I managed to come out of this situation only by using the layer control menu with the [ ] button on the OpenStreepMap data layer (to zoom to the downloaded area). I think also quitting and restarting Vespucci did not help – it jumps again to this bad zoom level.

Here are some screenshots:

The Osmose window:
![Zoom_level_problem_01](https://user-images.githubusercontent.com/48966999/102702601-f20c7e80-4264-11eb-8b0f-ca831a6f2640.jpg)

After using the blue link:
![Zoom_level_problem_02a](https://user-images.githubusercontent.com/48966999/102702895-3d745c00-4268-11eb-84fa-a75bf3b3c225.jpg)

Element information is reachable by the menu:
![Zoom_level_problem_03](https://user-images.githubusercontent.com/48966999/102702604-f33dab80-4264-11eb-81e5-76a01d645760.jpg)

After unselecting the way:
![Zoom_level_problem_02b](https://user-images.githubusercontent.com/48966999/102702910-482ef100-4268-11eb-9cd8-26aa9782e6d0.jpg)

This is the max. zoom level (after using my solution mentioned above to come out of the stuck situation):
![Zoom_level_problem_04 – max Zoomlevel](https://user-images.githubusercontent.com/48966999/102702933-ad82e200-4268-11eb-9a97-208e59722407.jpg)

## Expected Behaviour
Vespucci could go to his highest zoom level and perhaps could show a warning if this is not high enough to identify the way, perhaps with ways < 0.01 m (in this case it was still OK to see the way). Or it could get a higher zoom level ... e.g. like in JOSM.

## How to recreate
Use the blue Osmose link.

**Comment by simonpoole** [comment]
1 cm is more or less the max resolution of OSM. The zooming to the bounding box of that way circumvents the normal limits on zoom which stop at roughly 3 m for the smaller dimension of the screen.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/e6f3ada030f936e9a0bc472a4faee4f4db11b70b (the way won't be reasonably editable though, that will need some more work).
