### ISSUE TITLE
Crash after + button (on some connecting nodes) and undo

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1314]
## Vespucci Version
15.1.2

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
If a node  is selected which connects 2 ways, sometimes there is a "+" button in the toolbar, and sometimes the disconnect button. I could not find out the rule behind that, but I get this "+" button quite often which such nodes.

**And if there is a "+" button, Vespucci will crash after these steps:**

1. An existing node is selected which connects 2 (or more) ways
2. Press the "+" button => one of the ways will be selected!
3. Press the UNDO button in the toolbar
4. CRASH

(And if you press the new green "OK" button nothing happens – only the way is no longer selected.)

**Some screenshots:**

Node with a disconnect button in the toolbar = OK:
![Crash after + button on connecting nodes and undo – 02](https://user-images.githubusercontent.com/48966999/102951939-4d8d7500-44ce-11eb-9183-9b5f6969724c.jpg)

Node with a "+" button in the toolbar = PROBLEM:
![Crash after + button on connecting nodes and undo – 03](https://user-images.githubusercontent.com/48966999/102951976-5bdb9100-44ce-11eb-88eb-cc11e898cd29.jpg)

After pressing the "+" button:
![Crash after + button on connecting nodes and undo – 04b](https://user-images.githubusercontent.com/48966999/102952417-66e2f100-44cf-11eb-8df4-d74d896a85e5.jpg)

**If you now press the UNDO button Vespucci will crash!**

## Expected Behaviour
Please do not crash ... or do not show this "+" button, I'm not sure if it should be there ...

## Crash dump submitted (no or yes + date)
yes – just now (2020-12-23).

**Comment by simonpoole** [comment]
The "Append" action is available if you select a node that is an end node of a way, if there are multiple ways that end at the node there is currently no way to determine which one gets selected (aka you should select that way first). Old todo, if it even makes sense.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/issues/1317

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/d88f5d55a4c598ffe8859ece2f2082c621fc1676
