### ISSUE TITLE
Undo after creating a new node on an existing node (longpress) deletes the existing node!

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1315]
## Vespucci Version
15.1.2

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
If you do a longpress on any existing node for creating a new node, then press the "+" button in the toolbar, and then the undo button in the toobar, the existing node will be deleted!

It can be undone by pressing the undo button again, but this is not a very nice behaviour ... And not always the effect is directly visible like here, so potentially you delete a node without noticing it!

Step 1 (nothing is selected):
![Undo after 1 new node on an existing node deletes existing node – 01](https://user-images.githubusercontent.com/48966999/102953150-efae5c80-44d0-11eb-8d62-df062c0a618c.jpg)

Step 2: longpress on the crossing node of the 2 streets:
![Undo after 1 new node on an existing node deletes existing node – 02](https://user-images.githubusercontent.com/48966999/102953153-f046f300-44d0-11eb-97b8-f9864eb99e1f.jpg)

Step 3: After pressing the "+" button in the toolbar:
![Undo after 1 new node on an existing node deletes existing node – 03](https://user-images.githubusercontent.com/48966999/102953154-f046f300-44d0-11eb-8f49-400500853f71.jpg)

Step 4: After pressing the undo button:
![Undo after 1 new node on an existing node deletes existing node – 04](https://user-images.githubusercontent.com/48966999/102953157-f0df8980-44d0-11eb-8067-c2bba7107b5d.jpg)

=> The node and in this case the parts of the streets are deleted (there have been 3 way segments of the connected streets). This happens on ANY node, so if it's a single node (POI), this one will be deleted ...

Perhaps this is associated with issue #1314? I don't know ...

## Expected Behaviour
Node should not be deleted, only unselected.

## How to recreate
obvious

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/d88f5d55a4c598ffe8859ece2f2082c621fc1676

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/d88f5d55a4c598ffe8859ece2f2082c621fc1676
