### ISSUE TITLE
Strange undo behaviour with new nodes on an existing way

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1316]
## Vespucci Version
15.1.2

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
I know, you changed something with the undo checkpoints, but I don't know if this was the intended behaviour:

If you creating a new way with several nodes ON an existing way, the undo steps are different from the steps with a new way without connection to other ways – you need one steps more.

E.g. if you create a new way with 3 nodes on an empty space, you have to press the undo button 3 times and node after node will be deleted, which is fine.

But if you do the same ON an existing way, you have to press the undo button 4 times, and if you forget the 4th undo, 2 nodes will remain on the way ... See screenshots:

Step 1: After creating a new way with 3 nodes:
![Strange undo behaviour with new nodes on an existing way – 01](https://user-images.githubusercontent.com/48966999/102955225-b4faf300-44d5-11eb-8ad2-273125842107.jpg)

After undo 1:
![Strange undo behaviour with new nodes on an existing way – 02](https://user-images.githubusercontent.com/48966999/102955228-b5938980-44d5-11eb-9722-b0ef887b49d2.jpg)

After undo 2:
![Strange undo behaviour with new nodes on an existing way – 03](https://user-images.githubusercontent.com/48966999/102955230-b5938980-44d5-11eb-9bf4-2aa459fc34d8.jpg)

After undo 3 – **two nodes are still there (and 3 changes to upload!):**
![Strange undo behaviour with new nodes on an existing way – 04](https://user-images.githubusercontent.com/48966999/102955231-b62c2000-44d5-11eb-90b1-69bf3dbab3b0.jpg)

After undo 4:
![Strange undo behaviour with new nodes on an existing way – 05](https://user-images.githubusercontent.com/48966999/102955233-b6c4b680-44d5-11eb-8e5c-3003fdcc9a25.jpg)

## Expected Behaviour
I would prefer if the nodes would be deleted one after the other as with new ways on an previous empty space. And that you need exactly the same amount of undos like longpresses for creating the nodes, because that's intuitive – 3 new nodes - 3 undos to revert to the previous state.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/d88f5d55a4c598ffe8859ece2f2082c621fc1676
