### ISSUE TITLE
"Follow position button layout" has no effect

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1323]
Initial assumption: The "crosshair" style button, which you can click to go to your current position is indeed called "Follow position button".

I try to get the button on the right hand side, but choosing "Right" (or "None") in the menu "Follow position button layout" has no effect, i.e. the icon stays on the left hand side.

Vespucci version: 15.1.0 BETA 1
Android version: 9 on Fairphone 3.

IIRC this behaviour already occurred in previous versions.

**Comment by simonpoole** [comment]
You need to restart the app for the change to take effect.

The error is that it the corresponding message isn't dispayed.

**Comment by ltog** [comment]
@simonpoole : Oh, wow. That fixed it. Thank you!

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/4bc5b5abbdfa23eb2eb8ef5e840df2cb8666bb26
