### ISSUE TITLE
Indicate completion status

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1325]
Suggestion from @woodpeck 

Visually indicate completion status of an object.

Example at hand: tags that should be present on a tree (@woodpeck could you give your example again?).

This could be either done via validation as an extension of the current "missing" tag mechanism, or simply by using different icons and matching the tags via the style.

**Comment by woodpeck** [comment]
My use case is that I try to add `crown_diameter`, `circumference`, `height`, and `species` to all trees. 

Quite frequently you don't record all of them at the same time - some features can be recorded from the other side of the road, others require crossing the road and applying a measuring tape. While current Vespucci technology allows me to visually mark a tree that does not have ALL of a list of given tags, it does not allow me to choose different symbols or colours dependent on which tags are present or missing. 

It would be helpful for me to know that I need to cross the road *without* first clicking on the tree and bringing up the preset.

**Comment by simonpoole** [comment]
My current thinking is to allow the data style to override the icon from the preset, so like the following (for three tags). Naturally there are practical limits to this (mainly the number of icons you have to produce).

```
    ...
    <feature type="node" tags="natural=tree" iconPath="preset">
         <feature type="node" tags="circumference|height|diameter_crown" iconPath="icons/tree_all.png" />
         <feature type="node" tags="diameter_crown|circumference" iconPath="icons/tree_crown_diameter_circumference.png" />
         <feature type="node" tags="height|diameter_crown" iconPath="icons/tree_height_crown_diameter.png" />
         <feature type="node" tags="height|circumference" iconPath="icons/tree_height_circumference.png" />
         <feature type="node" tags="circumference" iconPath="icons/tree_circumference.png" />
         <feature type="node" tags="height" iconPath="icons/tree_height.png" />
         <feature type="node" tags="diameter_crown" iconPath="icons/tree_crown_diameter.png" />
     </feature>
     ...
```

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/pull/1330
