### ISSUE TITLE
Route Relation members are set to a multipolygon's roles

### ISSUE THREAD

**Issue by DerDings** [MarcusWolschon/osmeditor4android#1326]
## Vespucci Version

Vespucci 15.1.4
Flavor: current
Maximum avaliable memory 536870912
Total memory used 127918216
Tile Cache METROPOLE_RUHR_RVR-DOP10 usage Size 66846720 of maximum 67108864 #entries 255
State file size 134707 last changed 2021-01-14 17:46:54
Bug state file size 199084 last changed 2021-01-14 17:46:54
Relations (current/API): 22/0
Ways (current/API): 15/0
Nodes (current/Waynodes/API): 148/148/0
Available location providers
passive enabled true
gps enabled true
network enabled true

## Download source

Play Store

## Device (Manufacturer and Model)

Sony G8441

## Android Version 

9

## Behaviour/Symptoms

Route relation members are automatically set to "inner" and "outer" role

## Expected Behaviour

"inner" and "outer" roles are assigned to members of multipolygons and boundaries only

## How to recreate

1. Select a complex public transport route with roundabouts and detours
(e.g. https://www.openstreetmap.org/relation/1981859)
2. Add/remove members, which may also be roundabouts

## Crash dump submitted (no or yes + date)

no

**Comment by simonpoole** [comment]
Thanks for the report. Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/89f022dfdf5aac5c85315deb2371c5fe89a0222f
