### ISSUE TITLE
Broken link in Preset Tutorial

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1333]
In the Preset Tutorial, there are two broken links: https://github.com/MarcusWolschon/osmeditor4android/blame/c8aaa77f8fb926ac1c20dbd9899e442c4e5ce481/documentation/docs/tutorials/presets.md#L165-L166, search for `x-mas`.

`[https://github.com/simonpoole/xmas-preset](xmas preset)` should be `[xmas preset](https://github.com/simonpoole/xmas-preset)`

**Comment by simonpoole** [comment]
Thanks for the report, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/a7bb57b53eb4ac598f8e03ff2b766e95f98cd29d

**Comment by ltog** [comment]
The fix is not yet published on http://vespucci.io/tutorials/presets/ ;-)

**Comment by simonpoole** [comment]
Yes, because that would imply publishing the 15.2 docs.
