### ISSUE TITLE
Crash when undoing in non-downloaded area (?)

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1334]
## Vespucci Version
Not sure, probably 15.1.0 BETA 1

## Download source
Not sure, probably Playstore.

## Device (Manufacturer and Model)
Fairphone 3

## Android Version 
Android 9 /e/ OS

## How to recreate

Note: I had "Pan and zoom auto download" enabled.

Not sure: I think, I made some changes in one area, some days ago, then downloaded another area today and then undid most of the changes, including the older ones. Vespucci repeatedly crashed due to this and asked me to submit bug reports. IIRC first there were HTTP 400 errors and later on 509 errors. I assume Vespucci got into an infinite loop trying to download OSM data.

## Crash dump submitted (no or yes + date)
Yes, many, 2021-02-06, about 15:20 UTC

## Any other potentially relevant information

I had "Pan and zoom auto download" enabled.

**Comment by simonpoole** [comment]
That is a quarter of a year old beta version, which has long long long been superseded.

**Comment by simonpoole** [comment]
Stale, closing.
