### ISSUE TITLE
Fehler beim Starten der Kamera-App: Unable to create directory: /storage/emulated/0/Vespucci


### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1335]
Description:
---

Kein Photo mit Vespucci aufnehmbar:

Fehler beim Starten der Kamera-App: Unable to create directory: /storage/emulated/0/Vespucci

Device info:
---
<table>
<tr><td>App version</td><td>15.1.6.0</td></tr>
<tr><td>App version code</td><td>1609</td></tr>
<tr><td>Android build version</td><td>7005429</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RQ1A.210105.003</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>coral</td></tr>
<tr><td>Device model</td><td>Pixel 4 XL</td></tr>
<tr><td>Device product name</td><td>coral</td></tr>
<tr><td>Device hardware name</td><td>coral</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/OpenGreenStreet"/>OpenGreenStreet</A></td></tr>
</table>

**Comment by simonpoole** [comment]
If you have given the app permission to write to external storage this is likely due to Androids11s restrictions on storage access. 

Though this shouldn't be an issue as we don't target 11 yet.

**Comment by simonpoole** [comment]
Note that we currently don't have a Android 11 device to test with and emulators tend to be difficult to use for this kind of topic.

**Comment by OpenGreenStreet** [comment]
Thanks for the feedback. No problem, I just happened to notice it today. 
(For StreeComplete it was more important for me, as I often take photos to notes there. For StreetComplete the problem is solved).

**Comment by simonpoole** [comment]
Ich hab jetzt nochmals auf einem emulierten pixel 4 mit 11 getestet, funktioniert so wie vorgesehen. Kannst du ein screenshot der "App permissions" machen un hier anfügen (langer Click auf das App-Icon, (i) auswählen, und die Permissions sich anzeigen lassen).

**Comment by OpenGreenStreet** [comment]
@simonpoole, meinst Du das:

![Screenshot_20210207-151931](https://user-images.githubusercontent.com/76477269/107150572-ade15480-695e-11eb-9504-053a4e24ec60.png)
![Screenshot_20210207-152008](https://user-images.githubusercontent.com/76477269/107150573-ae79eb00-695e-11eb-8d53-23a58a6b6cb2.png)

Viele Gruesse  OpenGreenStreet

**Comment by OpenGreenStreet** [comment]
Hallo Simon Poole, ich habe es versucht . . . Viele Grüße OpenGreenStreet
 

Gesendet: Sonntag, 07. Februar 2021 um 14:41 Uhr
Von: "Simon Poole" <notifications@github.com>
An: "MarcusWolschon/osmeditor4android" <osmeditor4android@noreply.github.com>
Cc: "OpenGreenStreet" <opengreenstreet@planet.ms>, "Comment" <comment@noreply.github.com>
Betreff: Re: [MarcusWolschon/osmeditor4android] Fehler beim Starten der Kamera-App: Unable to create directory: /storage/emulated/0/Vespucci (#1335)


 

Ich hab jetzt nochmals auf einem emulierten pixel 4 mit 11 getestet, funktioniert so wie vorgesehen. Kannst du ein screenshot der "App permissions" machen un hier anfügen (langer Click auf das App-Icon, (i) auswählen, und die Permissions sich anzeigen lassen).

**Comment by simonpoole** [comment]
Also man kann da auch noch auf "Berechtigungen" klicken und bekommt Details.Berech

Aber man sieht schon von dem Screenshot, dass du der App die Berechtigung nicht gegeben hast, dass sollte so aussehen:

![Screenshot_1612711370](https://user-images.githubusercontent.com/1011860/107151024-cb172280-6960-11eb-9248-23552002b658.png)

respektive wenn du auf "Berechtigungen" klickst:

![Screenshot_1612711291](https://user-images.githubusercontent.com/1011860/107150968-960ad000-6960-11eb-9e39-fd1337243f13.png)

Bei die sieht letzteres vermutlich so aus weil du die Berechtigung verweigert hast:

![Screenshot_1612711573](https://user-images.githubusercontent.com/1011860/107151189-8dff6000-6961-11eb-9823-0e6e24b2974b.png)

Um das Problem zu beheben, einfach auf den Eintrag klicken und die Berechtigung erteilen.

**Comment by OpenGreenStreet** [comment]
@simonpoole Danke für den Hinweis, nach dem Hinzufügen der Berechtigung funktioniert die Kamera jetzt. (Ich hatte erwartet, dass bei fehlender Berechtigung ein Dialog erscheint, um die Berechtigung anzupassen. Entschuldigung, dass ich deswegen so einen Anwand generiert habe.) Viele Grüße OpenGreenStreet

**Comment by OpenGreenStreet** [comment]
Danke, jetzt funktioiert es: https://github.com/MarcusWolschon/osmeditor4android/issues/1335
 

Gesendet: Sonntag, 07. Februar 2021 um 16:31 Uhr
Von: "Simon Poole" <notifications@github.com>
An: "MarcusWolschon/osmeditor4android" <osmeditor4android@noreply.github.com>
Cc: "OpenGreenStreet" <opengreenstreet@planet.ms>, "Comment" <comment@noreply.github.com>
Betreff: Re: [MarcusWolschon/osmeditor4android] Fehler beim Starten der Kamera-App: Unable to create directory: /storage/emulated/0/Vespucci (#1335)


 

Also man kann da auch noch auf "Berechtigungen" klicken und bekommt Details.Berech

Aber man sieht schon von dem Screenshot, dass du der App die Berechtigung nicht gegeben hast, dass sollte so aussehen:



respektive wenn du auf "Berechtigungen" klickst:



Bei die sieht letzteres vermutlich so aus weil du die Berechtigung verweigert hast:



Um das Problem zu beheben, einfach auf den Eintrag klicken und die Berechtigung erteilen.
