### ISSUE TITLE
Save Note dialog state over pause/resume

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1336]
Description:
---

1. download notes
2. open now and start writing comment
3. switch to different app
4. go back to Vespucci
6. note dialog is recreated and comment draft is lost

That's a pity in case when you want to add to note some info from another app.

lang: cs_CZ

Device info:
---
<table>
<tr><td>App version</td><td>15.1.6.0</td></tr>
<tr><td>App version code</td><td>1609</td></tr>
<tr><td>Android build version</td><td>A405FNXXU3BTK4</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.A405FNXXU3BTK4</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a40</td></tr>
<tr><td>Device model</td><td>SM-A405FN</td></tr>
<tr><td>Device product name</td><td>a40eea</td></tr>
<tr><td>Device hardware name</td><td>exynos7904</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/kudlav"/>kudlav</A></td></tr>
</table>

**Comment by kudlav** [comment]
@kudlav
I mean following dialog:
![Screenshot_20210210-084857_Vespucci](https://user-images.githubusercontent.com/11516259/107492124-57595d80-6b8c-11eb-8495-bd848896de28.png)

**Comment by simonpoole** [comment]
Yes, we currently don't save the dialog state over pause/resume cycles for this dialog, this is really a defect.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/pull/1343 might (might because I wasn't really able to recreate the issue over simply pause/resume cycles), fix the issue.
