### ISSUE TITLE
Crash after editing deleted way

### ISSUE THREAD

**Issue by DerDings** [MarcusWolschon/osmeditor4android#1339]
## Vespucci Version

15.1.6

## Download source

google play store

## Device (Manufacturer and Model)

Sony G8441

## Android Version 

9

## Behaviour/Symptoms

Application crashes immediately after trying to edit a deleted way, and on subsequent starts

## Expected Behaviour

- Vespucci doesn't crash.
- tags of deleted ways are either not editable, or the the deletion is reverted before changing tags.

## How to recreate

1. delete a way
2. select "upload changes"
3. in the "changes" tab, select the deleted way
4. select "edit tags"
5. edit tags and exit using the check icon
6. the app crashes
7. re-open the app
8. it crashes again on each startup

## Crash dump submitted (no or yes + date)

yes, around UTC 2021-02-13T19:48

**Comment by simonpoole** [comment]
Thanks for the report. We naturally should not be offering to edit the tags of a deleted element, it will be removed in the next maintenance release. 

Do you have edits that were not uploaded due to the crash?

**Comment by DerDings** [comment]
> 
> Do you have edits that were not uploaded due to the crash?


Yes, but they're probably gone forever since I deleted the apps data via the Android app menu in order to make it start correctly again.

**Comment by simonpoole** [comment]
Issue fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/471b403bc9fd0fe398575d73b9fcc0a989eaf035

@DerDings  I could have potentially fixed the issue that was causing subsequent crashes, but if you zapped the data it is naturally gone.
