### ISSUE TITLE
Offset database usage

### ISSUE THREAD

**Issue by tommycrock** [MarcusWolschon/osmeditor4android#1351]
## Vespucci Version 
15.1.7

## Download source 
play store

## Device (Manufacturer and Model) 
Samsung S10e

## Android Version 
11

## Behaviour/Symptoms
When I click download it says there are no offsets stored within 10km. When I try to store an offset it fails with 'java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.'
![Screenshot_20210305-084419_Vespucci](https://user-images.githubusercontent.com/5749884/110090325-0efa1d80-7d8f-11eb-9dc6-bc72a259c4af.jpg)

## Expected Behaviour
Able to store an offset in the database. (I don't know whether the database is shared with JOSM, but if it is there should already be offsets stored).

## How to recreate
Tools > Align background > Save to database, add description, click "Save to Database".
(This has been a persistent problem for me over months)

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
Imagery being used: various
originally posted here: https://forum.openstreetmap.org/viewtopic.php?pid=820909#p820909 (no answers yet)
Near 53.88,-1.71

**Comment by simonpoole** [comment]
Both JOSM and Vespucci use the same third party service https://offsets.textual.ru/

Seems as if they have a problem with their SSL certificate (@Zverik ?), as a workaround you could try setting the URL in the Advanced Preferences / Server settings / Offset server to the none-SSL Version (http instead of https)
> (This has been a persistent problem for me over months)
You should report an issue as soon as it occurs in a repeatable fashion.

**Comment by tommycrock** [comment]
Thanks. That works well. Perhaps if the connection fails when trying to download that should be reported to the user. It was just reporting that no offsets in a 10km radius were found. With the http adjustment it now finds offsets that were already in the database.

> You should report an issue as soon as it occurs in a repeatable fashion.
Yes. It wasn't meant as a dig, just a comment on repeatability. I'm pretty new to this whole universe so assumed I was doing something wrong or hadn't found an appropriate setting for a while.
