### ISSUE TITLE
Explain when imagery offset resets, possibly change behaviour

### ISSUE THREAD

**Issue by tommycrock** [MarcusWolschon/osmeditor4android#1352]
In the user guidance, it says "Exiting the screen with "Done" will semi-permanently store the offset" http://vespucci.io/help/en/Aligning%20background%20imagery/
It's not clear to me what is meant by 'semi-permanently'. I have had problems where I have thought I've been editing to aligned imagery and later realised that the offset had gone back to zero. Selecting Apply stored offset to imagery fixes this, but I don't know for how long or how to know it has/hasn't happened again. Please explain when the stored offset will stop being applied and consider changing behaviour so that the offset remains permanent until actively changed by the user.
Thanks!

**Comment by simonpoole** [comment]
The behaviour changed with 10.1, see http://vespucci.io/help/en/10.1.0%20Release%20notes/#imagery-offsets and is more deterministic now.

**Comment by tommycrock** [comment]
Thanks. That explains it for me. Personally I would prefer a bigger radius or the ability to switch it to permanent. I think part of the problem is I don't always realise when Vespucci has restarted or when it's just idle in the background.

**Comment by simonpoole** [comment]
Looking at the code this morning I kind of came to the conclusion that the radius should probably be a user settable preference, which would solve this (there's not really a good solution to the problem overall which is a bit annoying).

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/b9dd5bcf2fc9cf00950577107914ce23f7c8f639 adds some extra explanation how local offsets are used.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/610c8fa5d33fa617d61fc3d08ec83441435de092 adds the preference
