### ISSUE TITLE
Extend background imagery source filtering to show only terrain layers

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1357]
Currently the background imagery selection dialog (accessible from the (+) in the layer dialog) allows selection of either all background layers, or aerial imagery. With more and more terrain layers becoming available (for example hill shading) it would be nice to allow filtering just for these.

**Comment by zedlabs** [comment]
Are terrain maps the maps with `Category.elevation`?

**Comment by simonpoole** [comment]
> Are terrain maps the maps with `Category.elevation`?

Yes, the Category values correspond to the category values here https://github.com/osmlab/editor-layer-index/blob/gh-pages/schema.json
