### ISSUE TITLE
Make imagery layer information dialog accesible from selection dialog

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1358]
While the user can access the layer specific information once it is selected, it would be a good idea (data privacy etc) if this was possible without actually configuring the layer.

For example this might be possible via an (i) button on the side of the entries in the layer selection dialog.

**Comment by zedlabs** [comment]
Hi, I would like to work on this.
Would something like this be fine?
<img src="https://user-images.githubusercontent.com/32540498/111180002-9be47880-85d2-11eb-95f4-50ad89ac1942.png" width="300" height="600">

**Comment by simonpoole** [comment]
Hi, yes that is roughly what I expected.

**Comment by simonpoole** [comment]
PS: the upload dialog uses a similar idea. A potential problem is the lack of horizontal space so that enough of the layer name can be displayed.

**Comment by zedlabs** [comment]
Hi, I have a few questions regarding this:
1. As we use a `RecyclerView `to display the imagery layer lists, the only way to set the `onClickListener `on the info icon would be to create an interface in the `ImageryListAdapter `and implement it in `Layers.java`, as a reference to `FragmentActivity `is required for the ShowInfo function, would this be fine?
2. There is no function to get a  `List<MapViewLayer>` from `TileLayerSource`, but a MapViewLayer object is required to call the showInfo function, should this method be created?

**Comment by simonpoole** [comment]
> 
> 
> Hi, I have a few questions regarding this:
> 
>     1. As we use a `RecyclerView `to display the imagery layer lists, the only way to set the `onClickListener `on the info icon would be to create an interface in the `ImageryListAdapter `and implement it in `Layers.java`, as a reference to `FragmentActivity `is required for the ShowInfo function, would this be fine?

Yes, essentially you should have the actual logic in Layers.java  and set that in the adapter. It will need to be passed a layer Id from the adapter and then display the dialog after retrieving the appropriate TileLayerSource. 

> 
>     2. There is no function to get a  `List<MapViewLayer>` from `TileLayerSource`, but a MapViewLayer object is required to call the showInfo function, should this method be created?

You can get the TileLayerSource for a specific id with the static method TileLayerSource.get and then directly show the dialog as we do in the de.blau.android.views.layers.MapTileLayer.showInfo code. 

This is naturally all off the top of my head, so I might be missing something.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/4c455adffd4c45be4badd79764034075cee18e8b thanks @zedlabs
