### ISSUE TITLE
Enable adding gpx layer from the layer hamburger menu also

### ISSUE THREAD

**Issue by dpriskorn** [MarcusWolschon/osmeditor4android#1364]
It's good IMO to give the user multiple ways to do the same thing.

**Comment by simonpoole** [comment]
There are still a couple of layer related things that currently are not reachable via the layer menu, this naturally mainly for historic reasons. In the case of the GPX layer it also needs some refactoring to cater for multiple instances of a GPX layer, which simply hasn't happened yet.

**Comment by dpriskorn** [comment]
see #1365 which is related
