### ISSUE TITLE
Missing documentation on gpx layers

### ISSUE THREAD

**Issue by dpriskorn** [MarcusWolschon/osmeditor4android#1365]
## Vespucci Version
newest from f-droid

## Device (Manufacturer and Model)
Samsung S5 ancient original Android OS from 2017

## Android Version 

not relevant

## Behaviour/Symptoms

Could not find documentation on gpx layers anywhere in the separate vespucci help app.

## Expected Behaviour

at least a pointer to it being possible by clicking the crosscircle in the bottom menu row.

## How to recreate

install app, try searching for gpx in the documentation -> a little about nmea, gpx follow, and a hint about layers but no information about how to add a gpx layer.

## Crash dump submitted (no or yes + date)

no

**Comment by simonpoole** [comment]
See http://vespucci.io/help/en/Main%20map%20display/#available-actions

**Comment by dpriskorn** [comment]
Can I send a pull request to improve the documentation?

**Comment by dpriskorn** [comment]
I tried searching using a search engine and found absolutely nothing when looking at the results (I did not click any of the links because none of them seem relevant )
https://duckduckgo.com/?q=add+gpx+track+to+vespucci&t=midoribrowser&ia=web

**Comment by dpriskorn** [comment]
I suggest adding a new file with a clear title that can easily be found like "Manage GPX tracks"
And include words like I searched for above GPx layer, add, manage, track, etc.

**Comment by simonpoole** [comment]
> Can I send a pull request to improve the documentation?

I never answered this, but the answer was naturally yes. The only issue is that either for 17.1 or the release after that, I'll be refactoring the code and potentially allowing for multiple GPX layers etc, so things are likely to change.
