### ISSUE TITLE
Freshly reinstalled Vespucci crashes Android

### ISSUE THREAD

**Issue by DerDings** [MarcusWolschon/osmeditor4android#1368]
## Vespucci Version

15.1.8.0

## Download source

Google Play Store

## Device (Manufacturer and Model)

Sony G8441

## Android Version 

9

## Behaviour/Symptoms

I uninstalled Vespucci a few weeks ago because I needed to free some storage.
Now I reinstalled Vespucci. When I try to open it, I see the splash screen with the Vespucci logo. Then the device freezes and restarts.

## Expected Behaviour

Device does run properly 

## How to recreate

1. Install Vespucci
2. Start Vespucci

## Crash dump submitted (no or yes + date)

No, the crash dump dialog isn't shown. If it is possible to access an old crash dump without starting the app, I could submit it via email. If so, please describe me how to do this. 

## Any other potentially relevant information

* In the times between uninstalling the app and reinstalling it, I replaced my SD card, enabled SD card encryption and disabled SD card encryption again. 
Internal storage encryption has been enabled all the time, and it never caused problems. 
* there's 1.3 GB free storage remaining on the internal storage

**Comment by simonpoole** [comment]
This is clearly an issue with your device or a corrupted install from the play store (is known to happen now and then). 

I would suggest deinstalling and then reinstalling the app to rule out the later.

**Comment by DerDings** [comment]
> This is clearly an issue with your device or a corrupted install from the play store (is known to happen now and then). 
> 
> I would suggest deinstalling and then reinstalling the app to rule out the later. 


I did so now. 
The only difference now is that not only the splash screen is shown, but also the „creating background database“ window is shown before the device is shut off. 

> 
> If the above doesn't fix the issue, you will need to try to directly determine what is going on by debugging your device via an USB connection. You will need to install adb and then view the log output while you start the app. https://www.xda-developers.com/install-adb-windows-macos-linux/ covers installing adb on common operating systems.

I will try this. But that is completely new to me, so it will take a while until I have enough time to address this.

**Comment by simonpoole** [comment]
Just as something you might want to try additionally: start Vespucci without the SD card inserted. And just to be sure: you are not installing the app on the sdcard (this shouldn't be a problem but just to narrow things down).

**Comment by DerDings** [comment]
> And just to be sure: you are not installing the app on the sdcard (this shouldn't be a problem but just to narrow things down).

No. I still cannot tell how (and if) this problem is related to the SD card. I just mentioned it because it was the only thing I knew to have changed since the last time it worked. 

> Just as something you might want to try additionally: start Vespucci without the SD card inserted. 

That worked. After that, I inserted the card again and it still works. Thanks for your support. 


Close?

**Comment by simonpoole** [comment]
> 
> > Just as something you might want to try additionally: start Vespucci without the SD card inserted. 
> 
> That worked. After that, I inserted the card again and it still works. Thanks for your support. 
> 
> 
That would indicate that something is fishy with the SD card. If one is present Vespucci will try to create its tile cache on it, if not available it will create it on internal storage and continue to do that even if a sd card is inserted. 

See also  http://vespucci.io/tutorials/faq/#on-startup-vespucci-complains-that-it-cant-write-to-a-directory
