### ISSUE TITLE
Preference option “Max. numbers of inline values” seems to count wrong

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1369]
## Vespucci Version
15.2.0

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
E.g.: If I set the preference option “Max. numbers of inline values” (Advanced preferences, User Interface Settings) to 5, only max. **4** values of combo or multiselect fields are shows (I guess this is the purpose of this preference option). If I put it to 6, only max. **5** values are shown ... And so on.

## Expected Behaviour
The maximum number of values which are shown should correspond to the choosen number in the prefs, not 1 less.

## How to recreate
Try it out.

**Comment by simonpoole** [comment]
This actually not an off by one issue. 

The problem is that the list of possible values often contains an empty value so that the tag can be cleared when the field is shown as autocomplete text, so what is actually being counted is correct, just that the empty value isn't and doesn't need to be displayed in most cases.

**Comment by jajajaneeneenee** [comment]
Hmmm ... are you really sure that an empty (autocomplete) value is the reason for the effect? (I know this "technic" from database drop-down-lists to empty a field, so I can basically imagine what you mean). Or do you mean by "not an off by one issue" that only in such cases it "seems" to count wrong, and in other cases (where no empty autocomplete value is involved) it counts correct?

For me, it seems that it ALWAYS counts wrong.

E.g.: I have some self defined preset XML files, and also with fresh defined combo or multiselect field with 5 values, they are only displayed DIRECTLY in 5 lines, if the value for “Max. numbers of inline values” is set to 6. If it is set to 5, there is only one line which has to be selected to see the 5 values. I don't know where an empty autocomplete value should come from, if such a field was never used before. (Or is it only used in the "background" to clear a field, e.g. by a long press on an radio button of a combo list?).

But I understand that this is a "Low Priority" issue. For me, too ... I simply set it to 6, if I want always to see lists with 5 values ... but perhaps it confuses also other users and specially new users.

**Comment by simonpoole** [comment]
I didn't say I wasn't going to change the behaviour, just explaining why it is behaving slightly counter-intuitive.

**Comment by jajajaneeneenee** [comment]
Then your explanations are often hard to understand (for me) ... or my knowledge of the english language is not good enough ...

And I wasn't thinking or saying that don't want to change something ... only wanted to know the background of your sentence "so what is actually being counted is correct" and if there is a empty value involved in any case ... I was thinking if t simply could be e.g. a case of a less symbol instead of "less or equal" in the coding ... or something like that ...  And I interpret your answer in a way that it's a little more, but it's also not important to know it exactly.
