### ISSUE TITLE
Show Map Roulette "challenge number"

### ISSUE THREAD

**Issue by blackboxlogic** [MarcusWolschon/osmeditor4android#1372]
When viewing a map roulette issue in Vespucci, it's not easy to find which challenge the issue is from and the information provided is sometimes unhelpful.
Consider displaying the "Challenge Number" (or some other unique identifier) which could be a way to find which challenge created the issue.

Related to: https://osmus.slack.com/archives/C029HV951/p1617673219006500

**Comment by atiannicelli** [comment]
The OSM Challenge Number or Challenge ID is what is used to uniquely identify the challenge and can be used like this 
https://maproulette.org/browse/challenges/<ChallengeID> to bring up that challenge in a browser.

**Comment by simonpoole** [comment]
As long as the maproulette creators are not supporting third party apps, I don't see a reason to waste any more effort on maproulette support than I've already have.

See 

https://github.com/MarcusWolschon/osmeditor4android/issues/1003

https://github.com/osmlab/maproulette3/issues/955

https://github.com/maproulette/maproulette2/issues/476

**Comment by mvexel** [comment]
Following up on the Slack discussion. This task seems to belong to a challenge that is not enabled, and the challenge belongs to a project that is also not enabled. So by default this [should not appear](https://maproulette.org/docs/swagger-ui/index.html?url=/assets/swagger.json&docExpansion=none#/Task/find) in a `/tasks/find` GET request. Does Vespucci only fetch tasks that belong to enabled challenges / projects in MapRoulette?
