### ISSUE TITLE
”Show POI icons on buildings” does not work anymore

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1373]
## Vespucci Version
15.2.0

## Behaviour/Symptoms
I think since v15.2.0, POI icons on buildings are not shown anymore, e.g. a building which is tagged with a valid shop key – you don't see any shop icon at all (respectively: only if you edit the building).

If the building has a housenumber, the number is shown, but an icon seems never to be shown (no matter if the building has a housenumber or not).

Perhaps this has to do with the new labelling enhancements?

## Expected Behaviour

- POI icons should be shown as before (if the corresponding preference checkbox is ON).
- It would be great if  the labels which are definded for an item in a data styling file would be displayed, too (standard=name).
- A small disadvantage (which also existed before) is that you don't see the housenumber anymore if there's a POI icon (if it's applied to the building directly) – if it could be display e.g. OVER the POI icon (in a circle), it would be great .... perhaps a little smaller than normally (?).

**Comment by simonpoole** [comment]
Since 15.2 the POI styling has changed to be customizable (the preference still makes sense as it stops computation of centroids which is rather expensive), but there are currently not pre-defined rules for this in the style files currently.

But for example changing the building styling as follows will get you the preset icons on them

```
       <feature type="way" tags="building" updateWidth="true" widthFactor="1.0" color="ffcc9999" style="STROKE" cap="BUTT" join="MITER" >
        <feature type="way" tags="building|addr:housenumber" closed="true" labelKey="addr:housenumber"/>
        <feature type="way" tags="building|shop" closed="true" iconPath="preset" labelKey="name" />
        <feature type="way" tags="building|amenity" closed="true" iconPath="preset" labelKey="name"/>
        <feature type="way" tags="building|tourism" closed="true" iconPath="preset" labelKey="name"/>
    </feature>
```

**Comment by simonpoole** [comment]
Styling added in https://github.com/MarcusWolschon/osmeditor4android/commit/153dd730aa9f48a9a5f4b4f291e3ad3db76b032b

**Comment by jajajaneeneenee** [comment]
That's great! Thank you! I didn't try out the new enhancements with icons in the style files so far ...

Your code did work, but I had to put the line with the housenumber **at the end** to prioritize icons over housenumbers (a lot of the buildings with a shop tag or one of the others also have a "addr:housenumber" tag, I think, and sometimes additionally a single separate adress node on the building – and then you would see the housenumber 2 times, and no shop icon for example) … 

Some spontaneous proposals:

- Perhaps such lines could also be added to "building:part" ... e.g. if someone tagged a shop in a building:part.
- A line with tags="building=service|power" could be added (and others?) e.g. for power substations. I think there was also an icon on it before (?).

**Comment by jajajaneeneenee** [comment]
And perhaps not to forget: buildings as multipolygons? Would this be possible at all? To have an icon in the center of such a multipolygon (surely more complex computation of centroids ...)?

I tried to add code lines for that in a style file, but it didn't worked (with and without `closed="true"` and with `type="relation"`).
