### ISSUE TITLE
Behavior of the opening hours editor with time intervalls beyond midnight could be nicer

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1374]
## Vespucci Version
15.2.0

## Behaviour/Symptoms
In any case where you have to change a time range of type "time–time" to "time–extended time" (over midnight) or the opposite case it's not very easy to manage in the opening hours editor and could easily confuse less experienced users, I think. (And I know, the complete opening hours topic is perhaps not a "beginners delight"). And other strange things can happen in my opinion. I try to describe it ...

E.g. if you want to change the opening hours of a bar from "18:00-23:00" to "18:00–04:00", you cannot simply drag the slider from 23:00 to 04:00 (and a second slider is created "on the fly"). You can or have to:
- Use the time chooser from the submenu (perhaps the best choice), which shows the numbers "24, 25, 26 …" for hours after 24:00 – a little strange, but it works (you have to choose "28:00" and get "04:00" as the end time). This is not very intuitive but a litte confusing. But at least you directly have 2 sliders!
- Add a new time intervall of type "time–extended time" and delete to old "time–time" intervall, but then you also have to enter the start time again.

And if you have a "time–extended time" entry with a second slider for the end time these strange things (strange in my opinion) can happen:
-  If you drag this second slider AFTER a time of the start time, then suddenly 24 hours are added to the end time, and you can get a result of e.g. "18:00-42:15" or "18:00-48:00" (if the second slider is set to "18:15" or "24:00"). So the second sliders goes from "17:45" to "18:00" and further, but in the top line which shows the result, the value for the end time jumps from "17:45" to "42:00". This really looks like an error for the first sight ...

And in the opposite case that you have to change an opening hour e.g. from "18:00-02:00" to "18:00-23:00", it is not possible to do it in a simple way with the two sliders. Here you can:
- Use the contextual menu (time chooser) – best method of course. Result is ONE slider = perfect!
- Or set the second slider to "00:00", save (it changes to "24:00"), the enter the opening hours editor again and change "24:00" to "23:00" with the slider (or the time chooser).

Perhaps this can confuse users who are not very experienced with the opening hous editor.

And I think, it's not too good if times like "48:00" can be created at all. I think the syntax for opening hours says "time in 24 hour format" (or only for offset times like "sunset+01:00", values of 0 to 48 may be used for hours – although I think, it also should be values from 0 to 24 …). Maybe times like "Mo 18:00-35:00" even do validate and are converted to "Mo 18:00-24:00, Tu 00:00-11:00", but the values should also be human readable in an easy way, I think ... for example if someone uses the object query function on openstreetmap.org (or somewhere else where the raw values are shown).

Example:
![Opening_Hours_Editor_Problem_02](https://user-images.githubusercontent.com/48966999/114254780-c3501a80-99b1-11eb-9f35-40b6710f97f1.png)

Result:
![Opening_Hours_Editor_Problem_01](https://user-images.githubusercontent.com/48966999/114254779-c1865700-99b1-11eb-9cf9-4610545b444e.png)

## Expected Behaviour
I would be nice IMHO ...

- ... if you could drag the time point of the second slider back to the first slider (e.g. from 02:00 on the second to 23:00 on the first slider) if there are already 2 sliders. (This is perhaps not easily possible.)
- Or if there would be a "–" button to remove a second slider (and change it to a simple time–time entry with an end time of 24:00). And perhaps a "+" button to show a second slider (and set it to "00:00") if I want to change a end time e.g. of "23:00" to "02:00". Or at least entries in the contextual menu of a time–time entry like "expand to extended time" and "reduce to simple time–time" (which KEEPs the entered start time).
- Or a button/symbol for the time chooser could be shown ALWAYS on the right side of the (last) slider.
- ... if the time chooser would show "normal" times for the end time hours (01:00 instead of 25:00 and so on).
- ... if you could drag the second slider ony maximum to the position of the first slider (no time intervalls with more than 24 hours which results in end times from 25:xx to 48:00. (And the same restriction in the time chooser …).

If this is too difficult to change, perhaps at least a warning could pop up in a case where a 25:xx to 48:00 time would be created (if pressing the SAVE button)?

**Comment by simonpoole** [comment]
Could you move this to  https://github.com/simonpoole/OpeningHoursFragment ? Thanks.

**Comment by jajajaneeneenee** [comment]
I plan to do it as soon as possible ....I forgot that there is a special repository for the Opening Hours editor.
