### ISSUE TITLE
Small glitch in the undo list after directly undoing a creation of a new way

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1375]
This issue is connected with #1316 I think ... and a small leftover or "misbehaviour" of this fix (?).

## Behaviour/Symptoms
If you are creating a new way with several nodes and directly UNDO this completely, e.g. you create a new way with 3 nodes by long-press/tap/tap, and you are still in the creation mode, and now press the "undo" button 3 times, all nodes are removed correctly and the creation mode is finished. 

**But in the undo list (section "undo", not "repeat") is one entry left at the top, which should not be there.**

It doesn't has bad negative effects, even if you choose it in the undo list, as far as I can see it, but it could be confusing and it would be better if it's not there ....

(And: I think "repeat creation" in the list does not work, if you hit "undo" again or did choose this leftover entry before … perhaps this should also not be shown in such a case? Or should it work?)

**Comment by simonpoole** [comment]
The underlying reason for this is that the checkpoint isn't empty, it doesn't do anything (because it adds stuff and then deletes it).

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/pull/1469
