### ISSUE TITLE
Non-downloaded Relation members are removed without warning

### ISSUE THREAD

**Issue by DerDings** [MarcusWolschon/osmeditor4android#1376]
## Vespucci Version

15.2.0

## Download source

Google Play Store

## Device (Manufacturer and Model)

Sony G8441

## Android Version 

9

## Behaviour/Symptoms

When removing one relation member, all non-downloaded members are removed as well

## Expected Behaviour

Nothing is removed from a relation without user consent.
Undownloaded relation members are not changed. 

## How to recreate

1. Download a small bbox which contains some parts of a relation (I tried with a type=route relation)
2. Select the relation
3. Choose add/remove members from the menu
4. Tap a way which is already part of the relation 
5. Choose to remove that element from the relation in the pop-up window

View the details of the relation. All members which have not been downloaded before have been removed now. 

## Crash dump submitted (no or yes + date)

no

## Any other potentially relevant information

current workaround: first select all members in the details view, and download them all before making any changes to the relation.

**Comment by simonpoole** [comment]
Thanks for the report. 

Note: a better workaround is to simply delete members vs the members tab in the property editor.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/cc623f2f3c02651708e50cd4f072a2168d54d050

**Comment by simonpoole** [comment]
15.2.1 with the fix has been released to googles play store and should be available on F-Droid soon too.
