### ISSUE TITLE
Preset file loading failure

### ISSUE THREAD

**Issue by davidpnewton** [MarcusWolschon/osmeditor4android#1385]
## Vespucci Version

15.2.1

## Download source

Google Play Store

## Device (Manufacturer and Model)

Samsung Galaxy A70

## Android Version

10

## Behaviour/Symptoms

Upon trying to load a preset from locally on the device the loading of the file fails with the message Element not found. This occurs whether trying to load a ZIP file or the XML file extracted from that ZIP file with the requisite file tree in place for the XML file.

## Expected Behaviour

Upon loading a preset either from a ZIP file or XML file with associated file tree on the device the preset should be created in the same way as inputting the URL of the preset would do.

## How to recreate

Try and load a preset from the local file storage of a device.

## Crash dump submitted (no or yes + date)

Not required as no crash occurs

## Any other potentially relevant information

In this particular instance the XML and ZIP files are loaded from the Onedrive storage area on the phone.

**Comment by simonpoole** [comment]
Please move the file to the vespucci folder and check if it works then, this sounds like a SAF issue.

**Comment by davidpnewton** [comment]
I think you're correct about it being an SAF issue. Putting the ZIP file directly into the same directory as autopreset mrutags.xml did create the preset when the file was loaded. Putting the XML file in there with the images in a directory tree below it produced a preset with lots of blank icons!

After I'd edited the .xml file again to try fiddling with the settings I did get another issue with a different error message, but I think that might be a different bug.

The message said failed to create uk signs test preset
Error Attempt to invoke virtual method 'void.java.io.InputStream.close()' on a null object reference

Do you think that's to do with the same thing or is it another problem that I've come across after editing the XML file?

**Comment by simonpoole** [comment]
Note: the access issue is with Android 10 and higher and I can recreate the issue of such a device, but not on earlier Android versions.

Could your create a 2nd issue for the 2nd problem and include the file that is causing the issue? Thanks.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/b19a80535b7a64e8164605ca4e09f8b455fa9036 (tested with google drive).
