### ISSUE TITLE
Error Attempt to invoke virtual method 'void.java.io.InputStream.close()' on a null object reference

### ISSUE THREAD

**Issue by davidpnewton** [MarcusWolschon/osmeditor4android#1386]
See issue #1385 for the genesis of this issue:

https://github.com/MarcusWolschon/osmeditor4android/issues/1385

Since first raising this error I believe I may have found out what is causing it. The problem appears to be with the directory structure inside the ZIP file being loaded in Vespucci. I have been trying to edit yopaseopor's UK traffic signs preset so that it is more useful to me, so that's the basis of the xml files.

[GB1.zip](https://github.com/MarcusWolschon/osmeditor4android/files/6393288/GB1.zip)
[GB2.zip](https://github.com/MarcusWolschon/osmeditor4android/files/6393290/GB2.zip)

GB1.zip is the file that loads into Vespucci OK and creates a preset (subject to already being in the Vespucci directory on the phone as per #1385 ). GB2.zip is an almost-identical file which produces the error message Error Attempt to invoke virtual method 'void.java.io.InputStream.close()' on a null object reference upon the import. The only difference is that with GB1.zip the XML file is in the base directory inside the ZIP file and with GB2.zip the XML file is in a second-level directory. So I think the error may be to do with the program expecting to find the XML file within the base directory, not finding it and throwing the exception.

**Comment by simonpoole** [comment]
Both of the examples have the preset file in the root directory, and both work for me.
