### ISSUE TITLE
Improved point movement

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#1387]
Please return, as it was in previous versions: when selecting a point, a large circle appeared, clicking on which with your finger, you could move the point, and, at the same time, the point did not jump under the middle of the finger.  This is much more convenient, since you can see where you need to set the point.

**Comment by simonpoole** [comment]
As you've probably noticed the large touch area can be enabled/disabled in the preferences: http://vespucci.io/help/en/Preferences/#large-node-drag-area

**Comment by mic140** [comment]
Thank you, I have already discovered this possibility29 апр. 2021 г. 3:32 ПП пользователь Simon Poole ***@***.***> написал:
As you've probably noticed the large touch area can be enabled/disabled in the preferences: http://vespucci.io/help/en/Preferences/#large-node-drag-area
