### ISSUE TITLE
Complaints about missing ref (guideposts) should be supressesed by noref=yes tag

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#1392]
To reproduce: created guidepost node, tag with name, tag with `noref=yes`

Vespucci complains about missing ref.

https://wiki.openstreetmap.org/wiki/Key:noref

https://www.openstreetmap.org/node/2606373914
![IMG_20210505_075938](https://user-images.githubusercontent.com/899988/117129677-468d4200-ad9f-11eb-857a-eaf913777422.jpg)

moved from https://github.com/simonpoole/beautified-JOSM-preset/issues/264 - hopefully this is the correct repo

**Comment by simonpoole** [comment]
Support noref https://github.com/MarcusWolschon/osmeditor4android/commit/e523acb7efe6d0ef14f34a1e726fbae948fce669
