### ISSUE TITLE
Opening hours editor: "off" instead of "closed"

### ISSUE THREAD

**Issue by PhilippFS** [MarcusWolschon/osmeditor4android#1393]
Hi,

thanks for all your work, Vespucci is really a tremendous help for my start with OSM.

One minor aspect: When using the opening hours editor, adding "closed on public holidays" currently generates the value "PH closed". The [OSM wiki](https://wiki.openstreetmap.org/wiki/Key:opening_hours#Closed_on_holidays) however states that "PH off" should be preferred.

It would be great if you could change this behaviour!

**Comment by simonpoole** [comment]
The free text wiki isn't really relevant in this case (and if anything good arguments could be made that "closed" is preferable). The specification https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification treats both values as equivalent.

**Comment by PhilippFS** [comment]
Ok, thanks. I was informed by other contributors that I should change the information that I submitted, but then I'll simply refer them to the specification!

**Comment by simonpoole** [comment]
Can you link to the relevant changeset?
