### ISSUE TITLE
BLANK MAP

### ISSUE THREAD

**Issue by elielsaarineen** [MarcusWolschon/osmeditor4android#1394]
## Vespucci Version

15.2.1
## Download source

google play
## Device (Manufacturer and Model)

Redmi Note 8T
## Android Version 

10
## Behaviour/Symptoms

i don't see the OpenStreetMap but only a blank screen instead.
## Expected Behaviour

OpenStreetMap imagery background
## How to recreate

i don't know
## Crash dump submitted (no or yes + date)

no
## Any other potentially relevant information

![Screenshot_2021-05-17-19-16-48-911_de blau android](https://user-images.githubusercontent.com/84340081/118529862-42b8d280-b744-11eb-9afd-958f4047de0e.jpg)
![Screenshot_2021-05-17-19-15-27-280_de blau android](https://user-images.githubusercontent.com/84340081/118529864-43516900-b744-11eb-8706-0000012ec3a7.jpg)

**Comment by elielsaarineen** [comment]
Please can someone help me? til few weeks ago the app works. But know it doesn't. thanks

**Comment by simonpoole** [comment]
> 
> 
> Please can someone help me? til few weeks ago the app works. But know it doesn't. thanks

- please touch the layer "hamburger" menu, make a screenshot and attach it to this issue,
- and the same for the main overflow menu (the "three dot" menu).

**Comment by elielsaarineen** [comment]
done

**Comment by elielsaarineen** [comment]
> ## Vespucci Version
> 15.2.1
> 
> ## Download source
> google play
> 
> ## Device (Manufacturer and Model)
> Redmi Note 8T
> 
> ## Android Version
> 10
> 
> ## Behaviour/Symptoms
> i don't see the OpenStreetMap but only a blank screen instead.
> 
> ## Expected Behaviour
> OpenStreetMap imagery background
> 
> ## How to recreate
> i don't know
> 
> ## Crash dump submitted (no or yes + date)
> no
> 
> ## Any other potentially relevant information
> ![Screenshot_2021-05-17-19-16-48-911_de blau android](https://user-images.githubusercontent.com/84340081/118529862-42b8d280-b744-11eb-9afd-958f4047de0e.jpg)
> ![Screenshot_2021-05-17-19-15-27-280_de blau android](https://user-images.githubusercontent.com/84340081/118529864-43516900-b744-11eb-8706-0000012ec3a7.jpg)

**Comment by simonpoole** [comment]
You have no background layers active (you must have accidentally removed them). just the data and task layers. press the "+" button in the layer dialog and add a background layer.

Note: it is extremely unfriendly to add a one star review in the play store for something that is

- not a review
- an issue that is not related to the apps functionality or similar attributes.

**Comment by elielsaarineen** [comment]
if i resolve the problem (i did not remove any layer, i'm a pro engineer and i know what i do generally) i'll be happy to give 5 stars.
Thank you for now. I try your suggest.

**Comment by elielsaarineen** [comment]
> You have no background layers active (you must have accidentally removed them/it). You've just got the data and task layers. Press the "+" button in the layer dialog and add a background layer.
> 
> Note: it is extremely unfriendly to add a one star review in the play store for something that is
> 
> * not a review
> * an issue that is not related to the apps functionality or similar attributes.

resolved.
1 star removed
5 stars given in play store, sorry for the misunderstanding.
the app is very useful.

**Comment by simonpoole** [comment]
Thanks.
