### ISSUE TITLE
Data styling – proposal (and a question) for icons on buildings

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1398]
## Vespucci Version
15.2.1

## Download source
Google Play Store

## Behaviour/Symptoms
The section for icons on buildings in the data styling xml file (version of April 10, 2021) looks like this:

```
    <feature type="way" tags="building" updateWidth="true" widthFactor="1.0" color="ffcc9999" style="STROKE" cap="BUTT" join="MITER" >
        <feature type="way" tags="building|addr:housenumber" closed="true" labelKey="addr:housenumber"/>
        <feature type="way" tags="building|shop" closed="true" iconPath="preset" labelKey="name" />
        <feature type="way" tags="building|amenity" closed="true" iconPath="preset" labelKey="name"/>
        <feature type="way" tags="building|tourism" closed="true" iconPath="preset" labelKey="name"/>
    </feature>
    <feature type="way" tags="building:part" updateWidth="true" widthFactor="0.8" color="ffcc9999" style="STROKE" cap="BUTT" join="MITER" >
    	<dash phase="1.0">
    		<interval length="2.0" />
    		<interval length="2.0" />
    	</dash>
    </feature>
```

**Proposal:**
I think it would be fine if you could add **craft** and **office**, too: 
```
        <feature type="way" tags="building|craft" closed="true" iconPath="preset" labelKey="name" />
	<feature type="way" tags="building|office" closed="true" iconPath="preset" labelKey="name" />
```
And all the tag combinations also for (closed) `building:part` ways, because sometimes a shop or another tag is also applied to a building:part only. (And perhaps also for multipolygons!)

I would even add:

`<feature type="relation" tags="building=service|power" iconPath="preset" labelKey="name"/>`

Because at least in my area power substations are often drawed as closed ways with building=service and power=substation, and then you have its icon on the building ... It's nice to distinguish it from other buildings ... It looks like this:

![building_service_power_substation](https://user-images.githubusercontent.com/48966999/118910357-9a159900-b924-11eb-81b0-211e09f30f0e.jpg)

**And one question:**

I had the idea for a personal data styling file to see an icon on building=garage objects (to quickly see if a building is tagged as a garage), and I thought that the following code would work:

`<feature type="way" tags="building=garage" closed="true" iconPath="preset" />`

Because there is an item for building=garage with a nice icon in the Beautified Simonpoole preset which also matches for building=garage objects. **But the icon will not be displayed.**

But it **is** shown if I change the code to: 

`<feature type="way" tags="building=garage" closed="true" iconPath="man_made_garage.png" />`

And I put the png in the same directory like the xml of course. Then it looks like this:

![building_garage_with_icon](https://user-images.githubusercontent.com/48966999/118908427-b82dca00-b921-11eb-9f01-aa93e9b304ac.jpg)

But why is `iconPath="preset"` not working? Or is it a bug or a special thing with buildings? (Because it works fine with other closed ways and other keys, I tried it out.)

[And by the way: an item for building=**garages** – additionally to building=garage – would make sense, because this is also quite common. Taginfo=662.027. I added it to my personal preset file ... but I know, this is not the right repository for this little issue ...]

**Comment by simonpoole** [comment]
The problem with the building preset is that we explicitly remove the building tag before matching with the preset to force matching with whatever else is tagged on the object. 

In principle this could be avoided by using the full matching process as we do for the property editor that will iteratively determine all matching presets for the object, which is slower, but given that we cache the results anyway probably not a big concern. But we would still need some magic criteria to then decide which of the matching presets we would then use for choosing the icon to display. This is naturally always an issue but outside of buildings an infrequent issue that we simply ignore.

**Comment by simonpoole** [comment]
Addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/01a2b6862e521ccc33fc6b7338ba2ede9ee781e9
