### ISSUE TITLE
Crashing consistently when submitting feedback via activity

### ISSUE THREAD

**Issue by Lee-Carre** [MarcusWolschon/osmeditor4android#1400]
## Vespucci Version
v15.2.1

## Download source
F-Droid repository, via stock F-Droid app.

## Device (Manufacturer and Model)
Samsung Galaxy A40 [2019] SM-A405FN

## Android Version 
v10 (API 29), stock Samsung distribution (patch level 2020-09-01).

## Behaviour/Symptoms
Whenever attempting to submit any (even brief, natural language) info via the in-app feedback activity, Vespucci consistently crashes.

## Expected Behaviour
To not crash, even if there's a problem (e.g. network failure) with submitting feedback.

To handle errors gracefully. If unable to submit successfully, explain why & offer link to this repository's issues section (in order that the user may submit manually), with easy way to copy to clipboard the already input text.

To not lose user (input) data, even in the event of a crash. A simple way would be copying each field (title & description) to clipboard when the user presses the submit button, but before Vespucci actually begins attempting to submit the data.

To inform the user that they can (via configuration toggle) disable the interactive mode of the feedback activity and simply be directed via URL to this issues section.

To (preserve, and eventually) successfully submit feedback (since the data is important enough for the user to bother making the effort).

## How to recreate
Attempt to submit any feedback via the in-app activity.

## Crash dump submitted
Yes; 2021-05-21 (late evening) and/or 2021-05-22 (very early hours).

## Any other potentially relevant information
As a work-around, I changed the configuration for the behaviour of the feedback feature to simply direct me to this issues section, for manual submission. This will remain so (to avoid the risks to not-yet-uploaded data of crashing) until it's either overridden by a newer version or mention is made of this bug being fixed in the release notes.

While out surveying, I don't have a browser running (for memory & performance reasons), so this will mean that I'll not be able to report issues at the time, which will affect the quality of the description when (or if) they are reported. Minor problems are likely to go unreported.

**Comment by simonpoole** [comment]
This seems to be related to http://vespucci.io/help/en/15.1.0%20Release%20notes/#feedback-form-behaviour-changes Github no longer supports login/password for authentication and this should be disabled in the feedback form. Wasn't this the case for you?

The feedback submission activity is a third party component, it naturally shouldn't crash if it gets a error response back from github, but it seems that is what is happening here:

`java.lang.IllegalStateException: You must provide a GitHub API Token.
at i.j.a.d.a(IssueReporterActivity.java:11)
at i.j.a.c.onClick(IssueReporterActivity.java:1)
at android.view.View.performClick(View.java:7870)
at android.view.View.performClickInternal(View.java:7839)
at android.view.View.access$3600(View.java:886)`

**Comment by simonpoole** [comment]
It just went "click".
 
The apk built and distributed by F-Droid doesn't have the key necessary to submit an issue (this is a matter of F-Droid policy and completely out of our hands), and as due to the github changes, login/password doesn't work either, using the form should never be enabled for apks generated by F-Droid.

https://github.com/MarcusWolschon/osmeditor4android/commit/9cd5ffad11a2c1d363cee3ea1232139e5b49de1d disables use of the form for builds for which the key isn't present.
