### ISSUE TITLE
ConditionalRestrictionFragment — OSM API error; long tag values yield XML lines which exceed 255 characters

### ISSUE THREAD

**Issue by Lee-Carre** [MarcusWolschon/osmeditor4android#1401]
## Vespucci Version
v15.2.1

## Download source
F-Droid repository, via stock F-Droid app.

## Device (Manufacturer and Model)
Samsung Galaxy A40 [2019] SM-A405FN

## Android Version 
v10 (API 29), stock Samsung distribution (patch level 2020-09-01).

## Behaviour/Symptoms
When attempting to upload changes to [OSM way #168413554](http://www.openstreetmap.org/way/168413554), involving a long charge:conditional value (the per-hour price rises the longer one stays), Vespucci returned an error indicating that OSM's API had rejected the upload because the (XML) line-length exceeded 255 Unicode characters.

The original value of the charge:conditional key was:

    0.88 GBP/hour @ (maxstay<=3 hours); 0 @ (Mo-Sa 17:00-08:00; Su 00:00-24:00; PH); 0 @ disabled parking AND maxstay<=3 hours; 4.40 GBP @ maxstay>3 hours AND maxstay<=4 hours; 7.04 GBP @ maxstay>4 hours AND maxstay<=5 hours; 10.56 GBP @ maxstay>5 hours AND maxstay<=6 hours; 14.96 GBP @ maxstay>6 hours AND maxstay<=7 hours; 20.24 GBP @ maxstay>7 hours AND maxstay<=8 hours; 26.40 @ maxstay>8 hours AND maxstay<=9 hours

When I removed most of the conditions, to shorten the length, the upload was accepted.

Since it may also be relevant; I had changed several tags, and added many others, some of which had a (non-short) URL as their value. These factors may have contributed to exceeding 255 characters in the (would-be) XML upload, when it wouldn't commonly be encountered.

## Expected Behaviour
To not encounter OSM API errors.
Though, it's unclear to me if the (root-)problem is with OSM's API or with Vespucci's XML.

Vespucci can adapt by, it would seem, ensuring that the XML it uploads doesn't have long lines. Perhaps apply some pretty-print reformatting so that each XML element has its attributes on a separate line (thus, this problem would only be encountered when a single key:value pair approaches the 255 character limit).

## How to recreate
Attempt to upload changes which include long values for tag keys.

## Crash dump submitted
No (didn't crash).

## Any other potentially relevant information
This was displeasing because it took considerable time to input that data during a survey. To then have to remove (most of) it in order for the upload to succeed so as to not lose all the other changes I'd made in the same set.

I intend to return to the site, so can perform some more testing of the conditions of failure, such as the charge:conditional value being the only change, and incrementally adding conditions until the same error is encountered. I'll report my findings as supplementary comments to this issue.

**Comment by simonpoole** [comment]
The OSM API only allows  tag values up to a maximum of 255 characters. This is enforced in most places including notifying the user, it seems as that doesn't happen in the CR editor.

Note that there is currently no way around the API length restriction, so you are basically stuck. See also https://github.com/openstreetmap/openstreetmap-website/issues/2025

**Comment by simonpoole** [comment]
Check and trncation added in https://github.com/MarcusWolschon/osmeditor4android/commit/52996724b54caaf65df0d50bfc8ef3f12e8fadcc

**Comment by xorgy** [comment]
> Check and truncation added in [5299672](https://github.com/MarcusWolschon/osmeditor4android/commit/52996724b54caaf65df0d50bfc8ef3f12e8fadcc)

Just a heads-up: from the looks of it, you are checking the UTF-16 length of the String, which is not the byte length of the string, and is not the number of unicode codepoints. I'm trying to figure out which of these is the actual limit in OSM right now, but probably UTF-16 length is the wrong thing to check.

**Comment by xorgy** [comment]
Nevermind, seems it is the UTF-16 length that is checked.

**Comment by simonpoole** [comment]
Note that a legal conditional restriction value doesn't actually contain any non 8-bit characters to start with, so the how many bytes discussion is a bit tangential to the actual issue. 

However the conditional restriction fragment should check (as the other parts of the property editor) for the maximum length and not allow exceeding it.

**Comment by xorgy** [comment]
Upon further discussion, it seems that in the environment where openstreetmap-cgimap is run, it's actually counting the unicode codepoints. You're right about these emitted values being single-byte characters so it won't matter as it stands.
