### ISSUE TITLE
Unexpected root element in *.jos file

### ISSUE THREAD

**Issue by hike39** [MarcusWolschon/osmeditor4android#1407]
## Vespucci Version
Vespucci V15.2.2.0

## Download source
Google Play Store

## Device (Manufacturer and Model)
Samsung Galaxy S%

## Android Version 
Lineage 17.1

## Behaviour/Symptoms
I've exported the region I've surveyed into a *.jos file. But if I try to import that file into JOSM (17919) I get an error message that an unexpected root element is found.

## Expected Behaviour
The *.jos content should be displayed as a layer in JOSM

## How to recreate
Open the *.jos file in JOSM

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
See attached file 
[wemding-2021-06-04-jos.txt](https://github.com/MarcusWolschon/osmeditor4android/files/6607861/wemding-2021-06-04-jos.txt)

**Comment by simonpoole** [comment]
This is simply caused by JOSM not recognizing the file format correctly as the error message hints at. If you change the extension to ".osm" it will work as intended.

![image](https://user-images.githubusercontent.com/1011860/120998632-8d000300-c788-11eb-834b-249983d8bbb3.png)
