### ISSUE TITLE
Problem with maxspeed:type as a combo field in a preset xml

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1408]
## Vespucci Version
15.2.2

## Android Version 
9.1.0

## Behaviour/Symptoms
I tried to add a combo field in a preset xml for "maxspeed:type" with the values (for Germany) with this code:

`
<combo key="maxspeed:type" text="Maxspeed:type" values="sign,DE:zone20,DE:zone30,DEːurban,DEːrural,DE:motorway" values_sort="false" />`

But in Vespucci, it always only shows the values "30,50,100,130", even if the value is set e.g. to "DE:urban"! It looks like this:

![Maxspeed DP type-Problem with combo – 01](https://user-images.githubusercontent.com/48966999/121034656-75874100-c7ad-11eb-9d53-a604cfe39d6b.png)

Details view:

![Maxspeed DP type-Problem with combo – 02](https://user-images.githubusercontent.com/48966999/121033594-9f8c3380-c7ac-11eb-866f-ce0378af2170.jpg)

And I also tried it with `delimiter=","`  (or `delimiter="|"`) and `editable=true`, but it never works as expected.

With other fields like `source:maxspeed` or `zone:maxspeed` it's no problem ....

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/7526eda4fef022ee352af7bcc1cce84584616cd8 

We were mistakenly displaying speed values from https://github.com/simonpoole/geocontext
