### ISSUE TITLE
Upload dialogue: Option to clear the comment

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1410]
Description:
---

I always have to manually remove the comment. I'd like an option to not have to do that every time. Your can keep it default off of course, there's usecases where that is helpful, but not for what I am doing.

Thanks though, I just started using your app and really like it

Device info:
---
<table>
<tr><td>App version</td><td>15.2.2.0</td></tr>
<tr><td>App version code</td><td>1704</td></tr>
<tr><td>Android build version</td><td>2105112216</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>ONEPLUS A6013_41_210511</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus6T</td></tr>
<tr><td>Device model</td><td>ONEPLUS A6013</td></tr>
<tr><td>Device product name</td><td>OnePlus6T</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/wonderb0lt"/>wonderb0lt</A></td></tr>
</table>

**Comment by wonderb0lt** [comment]
wonderb0lt is also my Github user name, if there's anything unclear, you can contact me here as well :)

**Comment by simonpoole** [comment]
I'm not quite sure what the actual issue is here, the contents of the two fields can be deleted by touch the 'x' in the right hand top corner, which would seem to be quite fast and delays the choice till actual upload. But clearly adding a preference is an option.
