### ISSUE TITLE
Switch to iD presets

### ISSUE THREAD

**Issue by lectrician1** [MarcusWolschon/osmeditor4android#1412]
This issue is regarding [this issue](https://github.com/openstreetmap/iD/issues/8537) posted on the iD repo.

The author of that issue questioned why all of the OSM editors don't use the same presets. I explained that JOSM and Vespucci have made the choice to use their own. 

This issue is a formal request that this project switches to the [iD Tagging Schema](https://github.com/openstreetmap/id-tagging-schema) to unify presets across editors.

**Comment by simonpoole** [comment]
ID prests are extremely tied to their UI and have various other issues (which is slightly hilarious as the ID bubble used to make fun of JOSM for exactly that).

**Comment by simonpoole** [comment]
PS: for histoical correctness I need to point out that it was the ID developers that decided to do their own thing and not use a format that had already been in use for years, not the other way around as you are implying.

**Comment by HolgerJeromin** [comment]
Simon suggested even this task as a Google summer of code project:
https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2017/Project_Ideas#Unified_Preset_Management_System

**Comment by simonpoole** [comment]
> Simon suggested even this task as a Google summer of code project:
> https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2017/Project_Ideas#Unified_Preset_Management_System
That  however was at a time when iDs presets where still reasonably generic, now I don't believe it to be a reasonable thing to do.

**Comment by matkoniecz** [comment]
> This issue is a formal request that this project switches to the iD Tagging Schema to unify presets across editors.

To even consider that iD Tagging Schema should have features important to Vespucci. 

Many of them would be directly beneficial to iD itself (like not-yet-supported features present in Vespucci presets).

**Comment by matkoniecz** [comment]
@simonpoole Given that Vespucci forked presets from JOSM - is it at least theoretically viable to merge this two?

Or is JOSM or Vespucci preset also tightly coupled with the specific editor, making it more or less hopeless?

**Comment by simonpoole** [comment]
> 
> 
> @simonpoole Given that Vespucci forked presets from JOSM - is it at least theoretically viable to merge this two?
> 
> Or is JOSM or Vespucci preset also tightly coupled with the specific editor, making it more or less hopeless?

There is literally nothing to do.

I've always produced a JOSM compatible version of the presets (by automatically removing extensions) and since https://github.com/simonpoole/beautified-JOSM-preset/commit/e1b692d2dc065781986b5f700d06716ac8921b16 (November last year) there's a version with the original JOSM icons.

So anybody using JOSM can simply use these, without the advantages some of the extensions would have for them, but with the advantages of the more complete coverage.

**Comment by matkoniecz** [comment]
> There is literally nothing to do.

But they still differ in content, right? With some entries missing in JOSM and maybe some missing in Vespucci.

**Comment by simonpoole** [comment]
> 
> 
> > There is literally nothing to do.
> 
> But they still differ in content, right? With some entries missing in JOSM 
Yes.

> and maybe some missing in Vespucci.
No

**Comment by matkoniecz** [comment]
I think that this issue can be closed? For start iD presets miss many, many features supported in Vespucci presets and until this is fixed it would cause clear damage to Vespucci.

Or is it open just in case that

> That however was at a time when iDs presets where still reasonably generic, now I don't believe it to be a practical thing to do.

will turn to not be true?
