### ISSUE TITLE
Why are presets not unified across editors? 

### ISSUE THREAD

**Issue by Tomagori** [MarcusWolschon/osmeditor4android#1413]
So, this is less of an issue with Vespucci specifically, but something that Vespucci IMO should consider.

OSM Wiki notes ["Presets have not been standardized across editors"](https://wiki.openstreetmap.org/wiki/Preset). It seems [a first attempt at doing this](https://github.com/osmlab/editor-presets) was considered some years ago, but nothing ever came of it.

My question is: Why not?

There are a ton of obvious benefits to having unified presets. Data quality of OSM, ease of use for editors, communicability of editing practices, accuracy of rendering by editors would all increase massively if presets (and therefore tagging schemes) were standardized more. The wiki, in integrating that standard preset scheme, could offer even better documentation of those tagging schemes. Changes in tagging could easily propagate across geography and time, past tagging could be understood better as a result of previous unified standards, editing and adding data would be simplified considerably and the barrier of entry for new editors (and editor solutions) would be lowered as well.

Why haven't there been more attempts at integrating the presets JOSM, Potlach, iD and other editing solutions use? We see some convergence; StreetComplete uses iD's presets, Vespucci uses JOSM's. But still, a (IMO highly unnecessary) rift remains, only getting worse with time as more editors, editing solutions and tagging discrepancies emerge.

iD issue: https://github.com/openstreetmap/iD/issues/8537
JOSM ticket: https://josm.openstreetmap.de/ticket/20995

**Comment by simonpoole** [comment]
Because the ID developers at the time (2012) wanted to do their own thing. In the mean time there is even less common ground (both technically and content wise) and any kind of merger us extremely unlikely to happen.

I did a talk at SotM Milano in 2018 iirc on the topic of presets that might interest you BTW.

**Comment by Tomagori** [comment]
Thanks for the reply, I'll gladly check your talk out. Nevertheless, wouldn't a merger be something to aim for in the mid- to long-term? Or do you see no issue with these two "groups" of editors doing their own thing?

**Comment by simonpoole** [comment]
I suspect this is not going to happen outside of actually paying for it (given that the people that created the issue in the first place were paid handsomely for doing so) and given the work that has gone in to the systems (code, icons, the presets themselves) and, in the case of JOSM format large number of specialized presets, we are talking about hefty sums.
