### ISSUE TITLE
Rename your app. 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1414]
Description:
---

App is great but if we cannot find it then we can't contribute it. OpenMap Editor is a nice name. Contribute OpenMap is good as well. 

Device info:
---
<table>
<tr><td>App version</td><td>15.2.2.0</td></tr>
<tr><td>App version code</td><td>1704</td></tr>
<tr><td>Android build version</td><td>eng.ramisk.20210515.005152</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>fluid_apollo-userdebug 11 RQ2A.210505.003 eng.ramisk.20210515.005152 test-keys</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>apollo</td></tr>
<tr><td>Device model</td><td>M2007J3SG</td></tr>
<tr><td>Device product name</td><td>fluid_apollo</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Varun Batra"/>Varun Batra</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Where  can't you find it? And it what form do you want to contribute?

**Comment by VarunBatraIT** [comment]
Hi,

Contribute to maps by adding stuff. I kept searching OpenMap editor on playstore and It got me various maps app. This was way down. I even ignored this app as it didn't click this is relevant to my search at all.

**Comment by simonpoole** [comment]
It's actually the top entry if you search for "openstreetmap editor" there is no "openmap" project so you will get a lot of generic, not relevant to OSM stuff.

**Comment by HolgerJeromin** [comment]
I had a hard time to reproduce your issue. 
"OpenMap editor"
"Open Map editor"
in browser, in incognito mode, in app on device. All showing this app on place 1.

**Comment by VarunBatraIT** [comment]
This is what I get

https://ibb.co/PYs5LR3
https://ibb.co/wMYw1tf

My concern was only that name itself doesn't indicate what the app is about. Mere a feedback.

**Comment by simonpoole** [comment]
> My concern was only that name itself doesn't indicate what the app is about. Mere a feedback.

But that is on purpose, products should not have descriptive names.

**Comment by HolgerJeromin** [comment]
We could switch the description from 

> Vespucci - an OSM Editor

to 

> Vespucci - an OpenStreetMap Editor

This would be a bit longer (sometimes cutted?) and has perhaps problems with the OpenStreetMap trademark (Simon will know details here).

**Comment by VarunBatraIT** [comment]
> But that is on purpose, products should not have descriptive names.

This is the reason why companies win. We devs often have a fixation on coding and not marketing. Next thing you know, a great product dies because people don't find it. Please note that this comment is not based on this app - it is a generic revert based on my limited experience.
