### ISSUE TITLE
Fields for custom/private OSM instance consumer keys and secret to enable OAuth

### ISSUE THREAD

**Issue by aaj013** [MarcusWolschon/osmeditor4android#1416]
Currently the app provides option to add custom OSM server API endpoint. But without option to add consumer keys and secret it is not beneficial for creation/editing purposes rather than just downloading the data. Found that keys and secret are currently considered only from hard coded values in `src/main/res/values/apis.xml`. It would be great if extra fields for key and secret can be added along with new server details dialog form. I can try for arranging contributor (I'm no android expert :)) in case needed.

**Comment by simonpoole** [comment]
There are some thoughts on improving key management in general. The question what is your use case? Private instance of the rails-port (aka the software that is openstreetmap.org), or something else? I ask because the current logic is closely tied to OAuth 1.0a, which is slowly dying out.
