### ISSUE TITLE
RFE: when saving an opening hours template, allow a value for the Key field to match *:conditional tags

### ISSUE THREAD

**Issue by Lee-Carre** [MarcusWolschon/osmeditor4android#1417]
## Vespucci Version
v15.2.1.0

## Download source
F-Droid repository, via stock F-Droid app.

## Device (Manufacturer and Model)
Samsung Galaxy A40 (SM-A405FN)

## Android Version 
v10 (API v29), stock Samsung distribution (patch level 2020-09-01).

## Behaviour/Symptoms
See [Parade parking](http://www.openstreetmap.org/way/905408294) for an example.

The problem I encountered was that the relevant opening hours for which I wanted to save a template were for access:conditional (daytime is public parking, at night it's permit-only residents parking), and therefore none of the existing values (for Key) were applicable.

I was reluctant to set “Key: All” since it would then be listed every time in much more common cases (rather than this rare one). I greatly value the filtering which Vespucci enables for OH templates, which enhances usability significantly.

Another example would be [La Colomberie](http://www.openstreetmap.org/way/110004215) for which motor_vehicle:conditional was needed to specify when deliveries where permitted (ordinarily its it's a pedestrians-only zone).

Unless, of course, this is what the “Object” field is for, but the documentation made no mention of this field.

## Expected Behaviour
Being able to save a scoped template for each OH syntax use-scenario, in order that the ‘only show relevant templates’ filtering can be effective in minimising noise.

## How to recreate
Attempt to save as an OH template any *:conditional involving opening hours syntax.

## Crash dump submitted
No (didn't crash).

## Any other potentially relevant information
Not that I can think of 🙂.

**Comment by simonpoole** [comment]
Note any work on this will be in https://github.com/simonpoole/OpeningHoursFragment/issues/51

**Comment by simonpoole** [comment]
Support added in https://github.com/MarcusWolschon/osmeditor4android/commit/d731dd0f80c1a29871ddec700fdb6a1d967c1766

Note as a workaround till this is actually available you can load templates from a file and have whatever key values you want in it. This will cause a warning in the UI that can be ignored, and doesn't have wild card support which would make it a bit cumbersome.
