### ISSUE TITLE
Help Topics : Bugs/Notes

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1421]
Description:
---

The advanced preferences menu does not have the options relating to showing/hiding Bugs/Notes.

I eventually found them in Tasks.

Please update the Help topics.

Regards,

Mike

Device info:
---
<table>
<tr><td>App version</td><td>15.2.3.0</td></tr>
<tr><td>App version code</td><td>1705</td></tr>
<tr><td>Android build version</td><td>T295XXU4CUF7</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RP1A.200720.012.T295XXU4CUF7</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>gto</td></tr>
<tr><td>Device model</td><td>SM-T295</td></tr>
<tr><td>Device product name</td><td>gtoxx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Mike Parfitt"/>Mike Parfitt</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/08d11230bf5aa3c2a9d5e939cedb4283ebf6ec49
