### ISSUE TITLE
Do not beep on osmosis issues

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1423]
Description:
---

sometimes there are like tens of osmosis issues in a download. Please don't play a sound for all of them 🙄.

Or provide an option to turn all sounds off.

Thanks

Device info:
---
<table>
<tr><td>App version</td><td>15.2.3.0</td></tr>
<tr><td>App version code</td><td>1705</td></tr>
<tr><td>Android build version</td><td>133121e2d7</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>UOS363F - OPM5.171019.017</td></tr>
<tr><td>Device brand</td><td>Wileyfox</td></tr>
<tr><td>Device manufacturer</td><td>Wileyfox</td></tr>
<tr><td>Device name</td><td>marmite</td></tr>
<tr><td>Device model</td><td>Swift 2 X</td></tr>
<tr><td>Device product name</td><td>Swift2</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Berend Veldkamp"/>Berend Veldkamp</A></td></tr>
</table>

**Comment by simonpoole** [comment]
See http://vespucci.io/help/en/Advanced%20preferences/#data-and-editing-settings the setting already exists.

**Comment by simonpoole** [comment]
The alert once per group doesn't mute completely. As the audio signal is not generated by the app (it is generated by Android) there's not much else we can do.

**Comment by bveldkamp** [comment]
That makes sense. It also triggered me to change the Android settings for notifications coming from Vespucci to Importance: _Average_ rather than _High_, and Sound: _None_.

Not muting completely would be fine with me, as long as there's only a single sound. Alert once per group sounds like a perfect solution to me. 

In the end, I really don't want to silence _all_ notifications, it's just that there are too many now.
