### ISSUE TITLE
Arabic translation 

### ISSUE THREAD

**Issue by abdullahO2** [MarcusWolschon/osmeditor4android#1432]
Thank you for this great application and I have updated all Arabic translation for Vespucci app and presets.
Thank you and my regards
Abdullah

**Comment by simonpoole** [comment]
Thanks @abdullahO2 the translations will be included in the next maintenance release likely in 2-3 weeks. Roughly at the same time I expect the 1st Beta of the next release and there will be a small number of additional/changed strings to translate then. I'll announce this on transifex when it happens.

**Comment by abdullahO2** [comment]
I tried the latest version and noticed some problems with the translation and I will review it, also I noticed that the translation of the presets was not applied.

**Comment by simonpoole** [comment]
The releases were built ~12 days ago, and the translations were updated at the same time, so I suspect the presets were simply pretty incomplete at the time (I did a quick spot check). I'll update the translations in the preset repo in a day or two and make a new preset release that you can then install, see http://vespucci.io/help/en/Presets/#managing-presets

**Comment by abdullahO2** [comment]
Thank you so much for all the great work you do on this outstanding app

**Comment by abdullahO2** [comment]
thank you very much
