### ISSUE TITLE
Kartenansicht ist in full-screen, kann soft navigation Keys nicht sehen

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1441]
Description:
---

Hi, vielen Dank für die App :). Hatte sie auf meinem vorherigen Handy (OnePlus 5) gut nutzen können, aber auf meinem neuen hab ich ein Problem.

Ich muss, um aus der App zu kommen, immer vom unteren Bildschirmrand nach unten wischen. Erst dann werden mir die Zurück, Home und Übersichts-Icons angezeigt. Glaub die Activity ist full-screen oder so. Kann man das irgendwo einstellen? Hab's leider nicht finden können.

Vielen Dank im Voraus,
Carsten

Device info:
---
<table>
<tr><td>App version</td><td>15.2.5.0</td></tr>
<tr><td>App version code</td><td>1707</td></tr>
<tr><td>Android build version</td><td>2106011630</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>IN2013_15_210601</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus8</td></tr>
<tr><td>Device model</td><td>IN2013</td></tr>
<tr><td>Device product name</td><td>OnePlus8_EEA</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/carstenhag"/>carstenhag</A></td></tr>
</table>

**Comment by carstenhag** [comment]
Ich hab den Bericht gesendet. Screenshot: 
![Screenshot_20210817-202523](https://user-images.githubusercontent.com/3776997/129781172-db723a1f-c9ff-4339-bbe9-c8f73b9f2b9b.jpg)

**Comment by simonpoole** [comment]
Der Swipe von unten ist wie es funktionieren sollte, aber man kann, natürlich, das ganze auch abschalten, siehe http://vespucci.io/tutorials/faq/#fullscreen-mode-doesnt-work-properly

**Comment by carstenhag** [comment]
Ahh vielen Dank, wusste dass es die Option geben muss, hatte es aber nicht gefunden. Jetzt klappt's, danke
