### ISSUE TITLE
Too persistent uploading pop-up

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1443]
Description:
---

Uploading pop-up sometimes stays for several minutes and cannot be dismissed, functionally locking the app

AFAIK it is supposed to disappear and start uploading in the background if I click somewhere

Though I am unsure what is the benefit of such big pop-up. Why not have something smaller in corner or to side? In the beginning I was unaware that this box can be dismissed to background.

I have recording (sadly, with Polish translation enabled) that I can upload of the situation.

It happened on a terribly poor mobile data connection (other editing apps also had bugs in such environment)

Curiously, I was able to select elements in the downloaded area - though editing was functionally impossible

Pinging myself @matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>15.2.3.0</td></tr>
<tr><td>App version code</td><td>1705</td></tr>
<tr><td>Android build version</td><td>V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.191002.002.V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Mateusz Konieczny"/>Mateusz Konieczny</A></td></tr>
</table>

**Comment by matkoniecz** [comment]
This white dot is register of tapping on the screen

https://user-images.githubusercontent.com/899988/131412933-6a98b0f1-dfc5-4ca9-bb69-44260d7ad7b9.mp4

**Comment by simonpoole** [comment]
Hmm that actually looks like an issue with Android on the device though it really seems unlikely .... I'll investigate a bit further.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/32b04d82fe482fddb552649cbb3802567018627b just to be on the safe side sets canceable true (that is the default) for the enclosing DialogFragment but it should make a difference.

Other angle: did you rotate the screen or use a different app and then returned to Vespucci when this occurred?

**Comment by matkoniecz** [comment]
> did you rotate the screen or use a different app and then returned to Vespucci when this occurred

No to the first one, probably no to the second one. Maybe I checked something or interacted with notifications but I do not remember it.

**Comment by chau-intl** [comment]
I think I had the same issue a couple of days ago. I think it worked pressing the back button, but seen from my point of view (as a user) I was worried that my upload was then cancelled when the dialog closed (I also had an extremely bad internet connection and wouldn't dare stop the upload). 

Instead of a modal dialog maybe a toast or something would be better to notify the user, that an upload process has been started and is continuing in the background? And maybe a button somewhere so I can check the status and progress of the upload?

**Comment by simonpoole** [comment]
That is a different issue though, the weird issue is that @matkoniecz couldn't cancel the modal.
'
Outside of that, all network activities run asynchronously until they eventually succeed or fail (which may take a long time) regardless of if you cancel the modal or not. Unluckily there is currently no way to really improve the user experience as there is no facility to cancel and repeat an upload in a consistent fashion with the OSM API 0.6.

**Comment by simonpoole** [comment]
Stale, closing.
