### ISSUE TITLE
Long press on "Undo" button does not do anything

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#1445]
## Vespucci Version
15.2.6 (but earlier versions were affected too)

## Download source
Sorry, not sure...

## Device (Manufacturer and Model)
Fairphone 3

## Android Version 
Android 10 with non-stock OS (/e/ OS)

## Behaviour/Symptoms
Long press on Undo button does not do anything

## Expected Behaviour
Long press on Undo button should show edit history

## How to recreate
Long press on Undo button

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
- Undoing by short press works
- Long press on lock symbol also works

**Comment by simonpoole** [comment]
This works on Android 11 and pre-10 real hardware and on Android 10 emulators (currently don't have an Android 10 device).

However emulators don't run in full screen mode do that could be an angle to explore.

Can you try switching nav bar settings (in the OS) and full screen settings in the app?

Further setting to check: in the accessibility settings of the OS there should be a setting for long click duration (possibly named touch and hold). Try making the time for detection longer and shorter.

**Comment by HolgerJeromin** [comment]
This works with Vespucci 16.0.0 BETA 2 here on android 10 with my Motorola g7 power.
Fullscreen setting: never

**Comment by ltog** [comment]
@simonpoole : I had success using the in-app fullscreen setting (setting it to `never`). I am not sure that I found the OS setting you mentioned. I only saw and tested `Show arrow keys while typing`, but that didn't work.

So I guess that can't be fixed?

> Can you try switching nav bar settings (in the OS) and full screen settings in the app?

Shall I add this info to https://vespucci.io/tutorials/faq/ ? If I am at it, I could restructure the FAQ a bit. I propose to add some sections, something like "About, Getting started, Troubleshooting" Shall I do this?

**Comment by simonpoole** [comment]
> 
> 
> @simonpoole : I had success using the in-app fullscreen setting (setting it to `never`). I am not sure that I found the OS setting you mentioned. 
> 
![Screenshot_1630438835](https://user-images.githubusercontent.com/1011860/131565695-66dcc499-127f-41c0-a107-948220424c6a.png)

"Touch and hold delay"

But from your description I suspect it may have to do with swiping up from the bottom.

**Comment by simonpoole** [comment]
> 
> 
> @simonpoole : I had success using the in-app fullscreen setting (setting it to `never`). I am not sure that I found the OS setting you mentioned. I only saw and tested `Show arrow keys while typing`, but that didn't work.
> 
> So I guess that can't be fixed?

There are settings for the navigation bar, typically in "System" somewhere that allow you to for example display classical navigation buttons or use gestures for navigation (the options tend to depend on the Android version and manufacturer).

A short video of it not working would be helpful too.

> 
> > Can you try switching nav bar settings (in the OS) and full screen settings in the app?
> 
> Shall I add this info to https://vespucci.io/tutorials/faq/ ? If I am at it, I could restructure the FAQ a bit. I propose to add some sections, something like "About, Getting started, Troubleshooting" Shall I do this?

Not before we've understood what the actual issue is. If it isn't related to gesture navigation I have  a spare Samsung S7 that I can install /e/ on, I don't have any devices without buttons so it won't be a 1-1 comparision.

**Comment by ltog** [comment]
I found the setting `Touch and hold delay`, I can set it to `Short`, `Medium` or `Long`. It doesn't seem to have an effect. (When it was set to `Medium`, it only once opened the undo menu, but I can't reproduce it.)

> But from your description I suspect it may have to do with swiping up from the bottom.

I usually swipe down from the top since otherwise menus tend to get activated.

**Comment by simonpoole** [comment]
Which options do you have for navigation bar display? aka do you have multiple gesture options or just one? A couple of screen shots or a video of the settings would be interesting.

We try to detect what is configured and turn fullscreen mode automatically off on such devices, however this relies on undocumented Android resources and that may not be working with /e/.  I can build a debug build for you to determine this, but it implies uninstalling the current version you have installed. Haven't been able to get /e/ running on the spare S7, so can't test locally.

**Comment by ltog** [comment]
> Which options do you have for navigation bar display? aka do you have multiple gesture options or just one?

I don't understand your question, so I assume, I have only one option. See first screenshot below.

When I search for "Gesture" I find also another menu (see second screenshot) but I don't think, it is what your are looking for...

> I can build a debug build for you to determine this, but it implies uninstalling the current version you have installed.

Yes please, I can certainly run such a debug build...

First screenshot:

![Screenshot_20210906-201329_LineageOS_Settings-fs8](https://user-images.githubusercontent.com/4726277/132252042-4b1f97d5-3cc1-4e9f-ae68-71c71ddb887e.png)

Second screenshot:

![Screenshot_20210906-202203_Settings-fs8](https://user-images.githubusercontent.com/4726277/132252307-ff7e7b79-c270-4dc6-9718-dbef1683e50e.png)

**Comment by simonpoole** [comment]
Can you add a screenshot of vespucci with full screen mode switched to automatic?

**Comment by simonpoole** [comment]
Build that simply adds a bit more logging to the code that determines if fullscreen mode should be used or not 
https://drive.google.com/file/d/1PQovx6zyU8ptSggYql9jpO-eecFi4hHN/view?usp=sharing

Install, switch Vespucci fullscreen mode to "auto", then restart, immediately after startup go to the debug screen (at the bottom of the main menu), and click on "SEND DEBUG INFO".

Outside the extra logging this is the same as 15.2.6 so you can use it completely normally.

**Comment by ltog** [comment]
> Can you add a screenshot of vespucci with full screen mode switched to automatic?

There you go!

![Screenshot_20210907-073120_Vespucci-fs8](https://user-images.githubusercontent.com/4726277/132366421-ceb42ae5-cb02-45e6-bc23-41b7c9c188f5.png)

**Comment by simonpoole** [comment]
> 
> 
> > Install, switch Vespucci fullscreen mode to "auto", then restart, immediately after startup go to the debug screen (at the bottom of the main menu), and click on "SEND DEBUG INFO".
> 
> Ok, I just did that. Did it work?

Yes, see:

```
179	09-07 17:04:59.715 E/FullScreenAppCompatActivity(10165): config_showNavigationBar 17891521
180	09-07 17:04:59.715 E/FullScreenAppCompatActivity(10165): config_navBarInteractionMode 17694850
181	09-07 17:04:59.715 E/FullScreenAppCompatActivity(10165): config_navBarInteractionMode mode is 0
182	09-07 17:04:59.718 D/FullScreenAppCompatActivity(10165): full screen auto true KEYCODE_BACK false KEYCODE_HOME false
```

The key bit is ````config_navBarInteractionMode mode is 0```` if instead of on-screen buttons, navigation gestures are enabled that should be 2 (though as said it isn't actually documented by google) and we would not turn on full screen mode, 0 is the code for a three button navigation bar. 

So it seems as if you are stuck with turning full screen mode of manually for now. I'll add your device and OS to https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/assets/devices.json, but I first have to determine how best to document OS specific issues. 

Medium term

**Comment by ltog** [comment]
@simonpoole : Ok, thanks for taking care. Just ask me, if you need more information.

**Comment by simonpoole** [comment]
Text added to FAQs here https://github.com/MarcusWolschon/osmeditor4android/commit/334da98306160e348b5e85ee3fbe8dd61b6f2510
