### ISSUE TITLE
Dependencies problems

### ISSUE THREAD

**Issue by Apochens** [MarcusWolschon/osmeditor4android#1448]
When gradle building,  it can't get markdown-gradle-plugin and preset-utils. I built it with AS and gradle using the original code.
The wrong info is as follows:
  > Could not resolve all artifacts for configuration ':classpath'.
     > Could not resolve ch.poole.gradle:markdown-gradle-plugin:2.2.0.
       Required by:
           project :
        > Could not resolve ch.poole.gradle:markdown-gradle-plugin:2.2.0.
           > Could not get resource 'https://dl.bintray.com/content/simonpoole/gradle/ch/poole/gradle/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom'.
              > Could not GET 'https://dl.bintray.com/content/simonpoole/gradle/ch/poole/gradle/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom'. Received status code 403 from server: Forbidden
        > Could not resolve ch.poole.gradle:markdown-gradle-plugin:2.2.0.
           > Could not get resource 'https://dl.bintray.com/content/simonpoole/osm/ch/poole/gradle/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom'.
              > Could not GET 'https://dl.bintray.com/content/simonpoole/osm/ch/poole/gradle/markdown-gradle-plugin/2.2.0/markdown-gradle-plugin-2.2.0.pom'. Received status code 403 from server: Forbidden
     > Could not resolve ch.poole:preset-utils:0.19.0.
       Required by:
           project :
        > Could not resolve ch.poole:preset-utils:0.19.0.
           > Could not get resource 'https://dl.bintray.com/content/simonpoole/gradle/ch/poole/preset-utils/0.19.0/preset-utils-0.19.0.pom'.
              > Could not GET 'https://dl.bintray.com/content/simonpoole/gradle/ch/poole/preset-utils/0.19.0/preset-utils-0.19.0.pom'. Received status code 403 from server: Forbidden
        > Could not resolve ch.poole:preset-utils:0.19.0.
           > Could not get resource 'https://dl.bintray.com/content/simonpoole/osm/ch/poole/preset-utils/0.19.0/preset-utils-0.19.0.pom'.
              > Could not GET 'https://dl.bintray.com/content/simonpoole/osm/ch/poole/preset-utils/0.19.0/preset-utils-0.19.0.pom'. Received status code 403 from server: Forbidden

**Comment by simonpoole** [comment]
Which release/version are you trying to build?

Those artifacts were hosted on bintray which as you may know was closed down early this year. New versions of the artifacts are distributed on mavencentral and the build files have been modified to reflect that, however those changes have not been backported to versions before 15.2 (.4) so you may simply be trying to build something too old.

**Comment by Apochens** [comment]
I am trying to build version 11.0.0-8 and 0.9.10b1324. They are truly too old. If there are no this artifacts anymore, these version/release then can't be built and uesd？Or there may be some methods to tackle this problem?

**Comment by simonpoole** [comment]
I'm not quite sure why you would want to build those versions, but both of the dependencies in question could be replaced by the current versions (they are not "really" required for building anyway), see https://github.com/MarcusWolschon/osmeditor4android/blob/master/build.gradle#L13 and https://github.com/MarcusWolschon/osmeditor4android/blob/master/build.gradle#L13

**Comment by Apochens** [comment]
I'm using them for some tests. I'll try what you mentioned. THANKS.

**Comment by simonpoole** [comment]
> By the way, you give the same line about the artifacts we discussed. I want to know which line can replace the artifact "preset-utils".

Fixed.
