### ISSUE TITLE
Selecting open note, opening state menu and leaving on open marks it add changed

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1449]
Description:
---

Reproduce: click on open note, in state drop-down select open

Current: note symbol on map becomes modified (blue)

Expected: note symbols status unmodified (yellow)

Ping myself: @matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>15.2.3.0</td></tr>
<tr><td>App version code</td><td>1705</td></tr>
<tr><td>Android build version</td><td>V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.191002.002.V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Mateusz Konieczny"/>Mateusz Konieczny</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Thanks for report, btw you are running an old version and should update.

**Comment by simonpoole** [comment]
The only way I can reproduce this is by first switching the state to "Closed" and then switching back to "Open" (re-selecting "Open" without changing the state in between, does, as expected, nothing).
