### ISSUE TITLE
Not all ways can be edited.

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1451]
Description:
---

Some ways are black, others are white and cannot be edited.
Why is that?
Can people lock ways against editing?

Device info:
---
<table>
<tr><td>App version</td><td>15.2.6.0</td></tr>
<tr><td>App version code</td><td>1708</td></tr>
<tr><td>Android build version</td><td>A202FXXU3CUG2</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RP1A.200720.012.A202FXXU3CUG2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a20e</td></tr>
<tr><td>Device model</td><td>SM-A202F</td></tr>
<tr><td>Device product name</td><td>a20eeea</td></tr>
<tr><td>Device hardware name</td><td>exynos7884B</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/gpermant"/>gpermant</A></td></tr>
</table>

**Comment by simonpoole** [comment]
This sounds as if you have a filter turned on, check the main map display if you have a filter button in the middle of  the right hand side.

**Comment by simonpoole** [comment]
No response to message via osm.org
