### ISSUE TITLE
"Tags changed" is misleading

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1455]
Description:
---

To reproduce:

Tag `highway=service` `oneway=yes`

Reverse way direction

Check tags after getting window that tags were changed. Tags were not changed

Ping @matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>16.0.0.3</td></tr>
<tr><td>App version code</td><td>1801</td></tr>
<tr><td>Android build version</td><td>V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.191002.002.V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Mateusz Konieczny"/>Mateusz Konieczny</A></td></tr>
</table>

**Comment by simonpoole** [comment]
> Check tags after getting window that tags were changed. Tags were not changed

Oh yes they were: reversing a way "should" change the oneway tag to oneway=-1 to maintain the same semantics, however most of the time people actually want to change the oneway direction so we leave the value the same, and that is why it needs to be reviewed.
