### ISSUE TITLE
f-droid build of 16.0 fails

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1459]
@Bubu & @roptat the build of 16.0 currently fails, see

https://monitor.f-droid.org/builds/log/de.blau.android/1802#site-footer

this seems to be because I added a further zip file as a fixture for the instrumentation tests. As f-droid doesn't run the tests anyway, this could simply be removed as the build does for the already existing preset fixture.

**Comment by simonpoole** [comment]
The cause of the original failure seems to be fixed now thanks to linsui, however there is currently a mysterious compile error https://monitor.f-droid.org/builds/log/de.blau.android/1802 that doesn't make sense, maybe something was corrupted?

**Comment by linsui** [comment]
Looks like the issue is still there. See https://monitor.f-droid.org/builds/log/de.blau.android/1803#site-footer

**Comment by simonpoole** [comment]
@linsui very unclear what is causing it. https://github.com/MarcusWolschon/osmeditor4android/blob/16.0-MAINT/src/main/java/de/blau/android/presets/Preset.java#L465 hasn't been touched for ages. 

And between 15.2 and 16.0 there were not many changes, the only thing that could be remotely relevant imho is that I cleaned up some code and replaced a class with a lambda on line 301. But if that is causing an issue it is clearly a compiler bug. Naturally the app has been built literally 100s of times without issue, so the question would be what is different about what F-Droid is doing.

Just to check my sanity, I just built the 16.0-MAINT branch on a box where it had never been built before. absolutely no issue. And just to be absolutely absolutely sure I just downloaded the source from https://github.com/MarcusWolschon/osmeditor4android/releases/tag/16.0.1.0 and rebuilt again somewhere completely different ... and again no issue at all.

**Comment by simonpoole** [comment]
Note that F-Droids failure to distribute a 16.0 variant will cause users with devices with Android 11 or later issues when they install 16.1 or later (assuming that at some point in the future the issues are fixed) as they will not be able to access the app specific directory for migration to the new location.

**Comment by TheLastProject** [comment]
> Note that F-Droids failure to distribute a 16.0 variant will cause users with devices with Android 11 or later issues when they install 16.1 or later (assuming that at some point in the future the issues are fixed) as they will not be able to access the app specific directory for migration to the new location.

I'm not sure I understand this, is the migration code only in 16.0 and removed in 16.1 again?

If wanted, we could temporarily disable pulling new versions of Vespucci in altogether. Even then, assuming the build can be fixed, there is no way to guarantee users won't skip a version once we would re-enable the update checker.

**Comment by simonpoole** [comment]
> 
> I'm not sure I understand this, is the migration code only in 16.0 and removed in 16.1 again?

The problem, because 16.1 targets Android 11, is that it looses access to the old directory location.

It's not a gigantic problem because a user can use a file manager to copy things after the fact, it just isn't very user friendly.


> 
> If wanted, we could temporarily disable pulling new versions of Vespucci in altogether. Even then, assuming the build can be fixed, there is no way to guarantee users won't skip a version once we would re-enable the update checker.

Well the big question is still why the build fails in the 1st place,  yes, users can naturally skip a version, not much we can do against that in any case.

**Comment by simonpoole** [comment]
Still failing https://monitor.f-droid.org/builds/log/de.blau.android/1902#site-footer since September the app has literally been built 100s of times without issues.

**Comment by linsui** [comment]
Finally I found that it failed just because Java 1.8.
