### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by dschrempf** [MarcusWolschon/osmeditor4android#1460]
## Vespucci Version
F-Droid, Version 15.2.8

## Device (Manufacturer and Model)
LG, H870

## Behaviour/Symptoms
I can not log in with OAuth, nor when I provide the login credentials in the advanced settings.

## Expected Behaviour
Login works.

## How to recreate
Click wrench on the bottom. Click Authorize OAuth. A Browser window opens, the OAuth login page is shown for a few milliseconds and the browser window closes and the following error is toasted:
```
net::ERR_CONNECTION_REFUSED
```

I just logged in with OAuth minutes before using `StreetComplete`, so it is not a general issue with my phone. However, I do use Bromite WebView, which might be relevant for fixing this issue. I did not find any errors in the logcat related to `de.blau.android`, but please see yourself.

Probably related to
https://github.com/MarcusWolschon/osmeditor4android/issues/1405
https://github.com/MarcusWolschon/osmeditor4android/issues/1300

[logcat_09-26-2021_14-26-43.txt](https://github.com/MarcusWolschon/osmeditor4android/files/7231371/logcat_09-26-2021_14-26-43.txt)

**Comment by simonpoole** [comment]
Note that #1300 was because the user was blocking access with a pihole. In the same vein you should check that you don't have a firewall configured or similar that blocks access.

**Comment by dschrempf** [comment]
I expected this much. But why did it work perfectly well for StreeComplete? What do they do different? How can I use Vespucci without changing my WebView? I also tried with Firefox and it did not work. Also, I do see the homepage but then it closes again, so it is not blocked, at least not completely.

**Comment by simonpoole** [comment]
StreetComplete likely does it differently (probably without employing a WebView maybe by scraping osm.org) I assume that Bromite allows you to configure a white list in one way or another. Anyway to verify you should switch to the stock WebView and test (you essentially can switch back to Bromite after authentication, so that is a possible workaround if you can't fix Bromite).

The issue is likely caused because during the OAuth handshake the OSM website calls back to the device and probably Bromite assumes that is a popup.

**Comment by dschrempf** [comment]
Thank you! After removing Bromite WebView, and also after disabling the ad blocker, login worked. If you are interested in fixing this issue, you could have a look at how they handle logins at StreetComplete. I am sorry, I can not really help you in that because I am not an Android developer. I leave the issue open, but feel free to close!

**Comment by simonpoole** [comment]
> 
> 
> Thank you! After removing Bromite WebView, and also after disabling the ad blocker, login worked. If you are interested in fixing this issue, you could have a look at how they handle logins at StreetComplete. I am sorry, I can not really help you in that because I am not an Android developer. I leave the issue open, but feel free to close!

We do this the way we do, because we want to display the original OSM webpage without intermediary that might fake or otherwise manipulate the contents of the page and obfuscate the details of what you are actually authorizing.

**Comment by dschrempf** [comment]
Hm, I don't understand the details, but to me it is trustworthy if I do not have to deactivate my privacy-honoring web view and ad blocker. Thank you anyways for your fast and helpful support!

**Comment by iandees** [comment]
For what it's worth, I ran into this today while using NextDNS's DNS-based blocking with default Chrome browser on a Pixel 4a with Android 12. NextDNS resolved piwik.openstreetmap.org to 0.0.0.0 while trying to login on Vespucci and I got the error as mentioned in the title of this bug. I added piwik.openstreetmap.org to the allowlist in NextDNS and Vespucci started working.

**Comment by simonpoole** [comment]
I've added a fix that simply ignores the piwik URLs. Will be in the March maintenance release.
