### ISSUE TITLE
Error loading offsets

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1464]
Description:
---

The offset server address should be changed to http://offsets.textual.ru.  This address does not work: https://offsets.textual.ru

Device info:
---
<table>
<tr><td>App version</td><td>16.0.0.0</td></tr>
<tr><td>App version code</td><td>1802</td></tr>
<tr><td>Android build version</td><td>V11.0.2.0.OEGMIXM</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>ZQL1711-vince-build-20191108142512</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>vince</td></tr>
<tr><td>Device model</td><td>Redmi 5 Plus</td></tr>
<tr><td>Device product name</td><td>vince</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/mike140"/>mike140</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Yes this seems to be an issue with the certificate of the site, note that you can change the URL in the advanced settings. Best would be to fix this at the source though.
