### ISSUE TITLE
Crossing=Zebra

### ISSUE THREAD

**Issue by hungerburg** [MarcusWolschon/osmeditor4android#1466]
Recently, in my neighbourhood, on a  street a node got added, with just a single "crossing=zebra" attribute. Found out, the mapper did that with Vespucci. Not sure though quite certain, this is missing a "highway=crossing" attribute, isnt it?

**Comment by hungerburg** [comment]
Thank You, I thought I might have missed a new development in tagging of such, and Vespucci being a fore-runner of.

**Comment by Lee-Carre** [comment]
@hungerburg

Definitely sounds like a careless mistake, to me. I'm curious; would you cite the node / changeset.

Besides missing highway=crossing, if it is indeed a zebra crossing, then (to my understanding) it should be crossing=uncontrolled and crossing_ref=zebra.

Like Simon said; this is exactly what presets are for.
