### ISSUE TITLE
Questions for setting/changing/removing values by applying presets (to code “shortcut items” or “quick change items”)

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1477]
Because these questions have something in common – setting values by presets, overwriting existing values, removing existing keys – I put them in one issue ...

###  Background
I created some presets for my personal use containing variants of items of the same kind with different typical sub key/value pairs (objects that occur frequently in my surroundings – I call them “shortcut items”) like turquoise benches with 3 seats and backrest, brown benches with 4 seats and no backrest and so on ... And I also wanted to have some “quick change items” which overwrite existing key/values or remove some keys of an existing object.

###  Vespucci Version
16.0.1

### Question 1 – behaviour of the default parameter in presets

Is it correct that there is a different behaviour with the default parameter in Vespucci compared to JOSM? In JOSM there is the rule : "The default value is only applied through a preset when the object the preset is applied to has _zero_ keys." In Vespucci it is (normally) also applied if an object has some keys, but not the key with the default value (no overwriting of existing values).

I prefer this behaviour of Vespucci! I only ask for a conformation, although it seems to be clear. It seems to be one of the case where the information "supported" on the tutorial page for presets ([http://vespucci.io/tutorials/presets/](http://vespucci.io/tutorials/presets/)) does NOT imply the same behaviour as JOSM. It perhaps would be a nice-to-have (not a must-have) if such a difference (which could be important and are quite fundamental) would be mentioned on the tutorial page – perhaps in a footnote. But I understand that it's hard to describe every difference in detail (and perhaps this can also change after some time with changes in Vespucci and/or JOSM ...)

### Question 2: changing existing values or remove keys (= overwrite existing values of keys or remove key/value pairs)

Another fundamental difference between Vespucci/JOSM and presets I experienced when coding such “shortcut” or “quick change items” items – as mentioned above – for the usage in Vespucci **and** JOSM: If you want to have an item with **overwriting any existing values of keys** (and you don't want that it matches itself at all!), you can code it for JOSM quite simple with lines like:
```
<key key="x1" value="y1" match="none"/>
<key key="x2" value="y2" match="none"/>
<key key="x3" value="y3" match="none"/>
...
```
And you can even remove key/values with: 
`<key key="xyz value="" match="none"/>`

[I found items of this kind useful in cases where you want to change something in existing objects. E.g. if you have to split a footway or path because there are some steps missing and you quickly want to change the new segment to steps and overwrite values or remove key/value pairs which make no sense with steps (or vice versa). And you don't want to do that by hand in the editor's detail tab ... where you perhaps forget or overlook something ...]

In Vespucci, such an item does not work at all, because it doesn't match anything at all (I suppose) and `<key key="xyz value=""' does not work, too (never works). And even if you add matching keys and the item matches (what's not desired ...), it seems that you cannot overwrite values or remove key/value pairs in this way. Indeed it's a little harder to code such an item for Vespucci ...

Question 2.1: is the only way (apart from using Javascript; see below) **for overwriting values** by applying a preset to use key fields like:

`<key key="x" value="y" />`?

And you always have to accept the side effect of matching (what's not desired for such “quick change items”)?

Question 2.2: is the only way **to remove keys** (key/value pairs) by applying a preset to use Javascript?

The best (or only) solution I found for any kind of manipulation comes with Javascript (of course a very nice possibility and a powerful tool to manipulate/check/transform values in any way you want – it's great that Vespucci supports Javascript in items!!!). But you have to code it quite different for Vespucci and JOSM (if you want to use these presets in Vespucci AND JOSM) ... And perhaps it's not easy for people without any knowledge of Javascript (the Javascript sample codes for items also could be extended perhaps). But In the meantime, I have a lot of good working items of this kind (for personal usage).

My Javascript sample code to overwrite or remove existing key/values I use (= shortest possible code – apart from the key name?):

```
<text key="manipulate_key_values_with_javascript" javascript="
    tags.put('keyToSet',['valueForTheKey']);
    tags.remove('keyToRemove');
    tags.remove('manipulate_key_values_with_javascript');" />
```

My Javascript sample code with sample conditions:

```
<text key="manipulate_key_values_with_javascript" javascript="
    /* Only set new value if key doesn't exist (or has no value): */
    if (tags.get(keyToSet) == null || tags.get(keyToSet)[0] == '') {
        tags.put('keyToSet',['valueForTheKey']);
    }

    /* Only set or remove a key if the key has the value "valueToCheck": */
    if (tags.get(keyToSetOrToRemove)[0] == 'valueToCheck') {
        tags.put('keyToSet',['valueForTheKey']);
        tags.remove('keyToRemove');
    }
    tags.remove('manipulate_key_values_with_javascript');" />
```

Last question (2.3): anything OK or to improve with this code (I am not a Javascript expert ...)?

**Comment by simonpoole** [comment]
Question 2 first: the match parameter doesn't have any effect on individual fields at all, it just indicates how a tag should be taken in to account for overall preset item matching (I'm not aware of any other documented behaviour in JOSM either). 

The reason overwriting doesn't work is that we only overwrite "fixed value" tags (with the corresponding fixed values from the preset) and don't touch any tags with "variable values". This makes sense IMHO (consider changing a mistagged restaurant to a fast food place with the same name and opening hours).

Your issue is that a tag without a value/with a empty string as a value is not treated as a "fixed value" tag, which in turn makes sense too.   

Maybe a simple fix would be a button to delete any unknown keys en bloc.

**Comment by simonpoole** [comment]
Question 1: that was not the documented behaviour of JOSM before https://josm.openstreetmap.de/wiki/TaggingPresets?version=144 (roughly 3 years ago), it is unclear if the just the documentation changed, or both the behaviour and the documentation. 

But in any case it shows the difficulty with your request: it just isn't possible to know with a reasonable amount of effort what behaviour JOSM is supposed to have at any specific moment in time. Throw in the lack of versioning of their presets and willy-nilly changes and it just doesn't make sense to say anything else than that things might work differently.

**Comment by simonpoole** [comment]
> Maybe a simple fix would be a button to delete any unknown keys en bloc.
@jajajaneeneenee  any feedback on this?

**Comment by jajajaneeneenee** [comment]
Hello!

Your reply to question 1 first: OK, I understood (and also expected something like that)

Your reply to question 2 (what have been 3 questions 2.1 and 2.2 and 2.3 indeed):

I missed a direct answer to the questions at the beginning of your answer … would have been helpful. And I didn't understand your first paragraph, to be honest (what are " individual fields"?). Also the second paragraph is quite confusing (not the content itself, but because it doesn't seems to answer any of my questions ... at least not clearly). I am already aware that we only overwrite "fixed value" tags ... and don't touch any tags with "variable values" (I also understand why this is reasonable). But it wasn't my question (or even something I would like to be changed). I only clearly understand your answer regarding a tag without a value/with a empty string (this concerns my question 2.2) – and it was what I expected ...

I mainly wanted to be sure of these things with my questions:

1. That JOSMs acts quite different here (because I want to use my self coded presets both in Vespucci AND in JOSM and I wanted to be sure to know what I have to change for these 2 editors – I aready know it quite well, but perhaps there would be an easier way – you never know ... And I'm sure you know it better).
2. I wanted to be sure that the only (or best) way for coding individual presets which overwrite or remove **specific** tags for Vespucci (**and** avoid matching by fixed key-value items) is to use Javascript (that's what I am doing and it works very well for me). And I wanted to know if my Javascript is generally OK ...

I didn't expected or asked for a change of the matching systematics in Vespucci (only if it really would have been a no brainer and very very few effort with no side effects – what is certainly very unlikely). This issue should really one contain questions ... not more.

Your question _“Maybe a simple fix would be a button to delete any unknown keys en bloc.“_:
I think it would not be the solution I need, because I want to control excatly WHICH keys I want to remove/overwrite with different special presets for these purposes. And I don't know exaxtly what you mean with "unknown keys" – keys which are not part of the matching item(s) and are listed under the divider "Additional properties" in the Vespucci form based editor?

Maybe I couldn't describe the situations for which I want to use such presets well enough ... The best example is perhaps the one I already described: when splitting ways (path/footway) to insert steps which were missing (or vice versa). Other examples:

- A way was tagged as `highway=track` with `tracktype=grade1`, but it is indeed a narrow path (`highway=track` has to be changed to `highway=path`, `tracktype` has to be removed, perhaps `surface=*` has to be added instead).
- There is a `barrier=swing_gate` with` swing_gate:type=single`, but it is wrongly tagged as `barrier=lift_gate` with `lift:gate:type=single` (change/overwrite, remove and set new value is neccessary)
- In the city, ALL vending machines for parking tickets were equipped with `payment:ep_geldkarte=yes` (and some credit cards) as payment methods in the past, but now this possibility is removed and only  `payment:coins=yes` and `payment:note=yes` is possible (=> remove exactly the omitted payment methods and set the possible ones with one click with a special preset).

The list could be extended indefinitely ... and often there are very specific cases were quite specific presets are necessary (or several presets to to cover a few cases with small differences ...).

I simply like to have a nice set of such presets for my personal usage (which I often have to change or complement) ... it's more fun when mapping and a lot goes faster (and more reliably with fewer human errors) ...

But perhaps we can close this issue already, because I guess (or suppose) that I'm on the right track altready and there is no other (easy) way at the moment ... and I already get better with javascript for more complex manipulations of keys and values (thanks again that this is possible in Vespucci!).
