### ISSUE TITLE
Lange Listen unübersichtlich - Option 'immer alphabetisch sortieren'

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1478]
Description:
---

Auswahl-Listen wie bspw für den Gebäudetyp finde ich immer wieder unübersichtlich i.S. ich gehe nach unten zu den möglichen Anfangsbuchstaben der mir einfallenden Synonymen aber finde den gesuchten Typ nicht. Dann gehe ich alle Typen von untern nach oben durch und merke erst dann, dass ich den gesuchten Typ wohl irgendwann die letzten Tage mal verwendet habe und er daher oberhalb der initialen Position steht anstelle bei dem entsprechenden Anfangsbuchstaben.
	Mögliche Lösungen
	1) speziell für Gebäudetypen mehrere Ebenen, zuerst die grobe Kategorie (zB zuletzt benutzte, Wohnen, Geschäftlich, Landwirtschaft), darin dann den konkreten Typ auswählen. Also ähnlich wie bei Street Conplete. Dadurch wird auf jeder Ebene die Liste so kurz, dass man alle Optionen sieht. Was in 'zuletzt benutzte' steht, taucht zusätzlich auch in seiner Kategorie auf. Grömter Nachteil dieses Ansatzes ist, dass das bestehende UI-Konzept erweitert werden muss und die beiden Ebenen für jede Auswahlliste neu konzipiert werden müssen.
	2) Option 'immer alphabetisch sortieren' anbieten, egal ob innerhalb der einzelnen, konkreten Auswahlliste oder den Einstellungen oder beides. Vorteil wäre, dass es auf einmal für alle Listen umgesetzt wäre und immer dieselbe Reihenfolge bestehen würde, dass also bspw. bei Campingplätzen die Sterne-Auswahl immer in aufsteigender Reihenfolge statt wild durcheinander stehen würde.
3) Die zuletzt benutzten Einträge oben in der Liste anzeigen, dann  einen trenner, dann alle Optionen inkl der zuletzt benutzten.

Device info:
---
<table>
<tr><td>App version</td><td>16.0.1.0</td></tr>
<tr><td>App version code</td><td>1803</td></tr>
<tr><td>Android build version</td><td>08051356</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>8901.3.A.0129.20210805</td></tr>
<tr><td>Device brand</td><td>Fairphone</td></tr>
<tr><td>Device manufacturer</td><td>Fairphone</td></tr>
<tr><td>Device name</td><td>FP3</td></tr>
<tr><td>Device model</td><td>FP3</td></tr>
<tr><td>Device product name</td><td>FP3</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/schoschi"/>schoschi</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Bitte den Issue in den Preset Repo verschieben, da zum grössten Teil die Punkte dorthin gehören https://github.com/simonpoole/beautified-JOSM-preset Du kannst dir übrigens problemlos ein aufgeteiltes Gebäude Preset selber machen.

Es wäre tatsächlich schön wenn man optisch die zuletzt verwendeten Werte abtrennen könnte, da aber die Android dropdown/popup listen das nicht unterstützen bedeutet das einiges an Entwicklungsaufwand.

**Comment by jajajaneeneenee** [comment]
Kann man auch auf deutsch schreiben ... ach, das ist ja schön ...

Das mit den Listen und dem Durcheinander, was sich schnell einstellt ist mein NUMMER-1-LEIDEN in Vespucci seit ganz langer Zeit ... siehe auch #1071 ... Und vor allem täglich bei JEDEM Mapping ... Es ist einfach anstrengend, dass sich die Listen ständig ändern, und man irgendwann immer von oben nach unten nach dem gewünschten Eintrag durchsuchen muss. Z.B. auch bei surface oder numerischen Listen, die dann durcheinander sind. Z.B. "building:levels" oder "min_level" / "max_level" – da macht es absolut keinen Sinn, dass sich die Reihenfolge ändert. Da dürften auch so gut wie nie neue Werte hinzukommen, die nicht in den Listen vorgesehen sind. Das ist bei ganz vielen Listen so ...

Irgendeine Lösung muss es doch geben dafür?! BITTE! Es wäre ein schönes Weihnachtsgeschenk ...

Wirklich schade, dass man wegen Android-Beschränkungen die zuletzt benutzen Werte nicht optisch abtrennen kann und den Rest so lassen, wie es im Preset definiert ist (v.a. bei `values_sort="false"`, wo man sich in eigenen Presets eine spezielle sinnvolle Reihenfolge erstellt hat) oder eben alphabetisch sortiert (mit Option) ... kann man nicht tricksen? Zum Beispiel einen Texteintrag mit Dashes als Trenner-Linie einfügen, der dann ignoriert wird, wenn man ihn antippt? Ist es denn nicht nur etwas Listengenerierungs-Zauberei? Also zum Beispiel sowas (reine Zeichenfolge):

——————————

Oder es gibt ja noch andere schöne UTF-8-Zeichen ... Oder auch nur eine Leerzeile ...

Oder von mir aus eine Option, IMMER alphabetisch (und numerisch) zu sortieren, oder die zuletzt benutzten Werte GAR nicht anzuzeigen (oder nur im Detail Tab) – ist alles besser als völlig unsortierte Listen, die man irgendwann hat. Und ich weiß nicht, ob es in das Preset Repo gehört – es ist ja ein generelles Vespucci Problem. Ich habe das auch mit vielen selbst erstellten Presets, wo ich Listen oft noch erweitert habe und viele lange Listen entstanden sind ...

Viele Grüße und hoffentlich eine gute Idee ...

**Comment by simonpoole** [comment]
Ich habe übrigens gestern einen horizontalen Ruler eingebaut in den dropdowns für Textfelder, und de-duplizere die Einträge nicht (sprich man hat die volle sortierte Liste der Werte auch noch) eher unwahrscheinlich aber, dass die bis Weihnachten veröffentlicht ist. 

Für die Dialoge mit radio button oder checkboxen ist das aber keine Lösung (da beruht die ganze Logik darauf das jeder Wert nur einmal vorkommt), bei den langen Listen ist es aber ja so, dass das Problem nur die ersten paar Elemente betrifft, der Rest ist ja wie erwartet sortiert.
