### ISSUE TITLE
Dropdow menu is too small

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1482]
Description:
---

It is not showing translated value.

Rotating phone to horizontal completely hides drop-down selection menu

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>16.1.0.2</td></tr>
<tr><td>App version code</td><td>1901</td></tr>
<tr><td>Android build version</td><td>V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.191002.002.V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Mateusz Konieczny"/>Mateusz Konieczny</A></td></tr>
</table>

**Comment by matkoniecz** [comment]
![Screenshot_20211104-211813](https://user-images.githubusercontent.com/899988/140490677-36b79fd8-7935-42b4-a609-f4de0c65f0f7.png)

**Comment by simonpoole** [comment]
This is on purpose as full width dropdowns (at least used to be) near impossible to use. A possible solution would be to switch Translation and actual value around.

**Comment by matkoniecz** [comment]
> full width dropdowns (at least used to be) near impossible to use

What about 75% wide dropdowns? (or is it annoying to test/implement?)

**Comment by simonpoole** [comment]
Partial fix in https://github.com/MarcusWolschon/osmeditor4android/commit/85c856bf2b7e4178d47afbc49991f4a95b3cd362
