### ISSUE TITLE
Undo of movement doesn't undo connected elements

### ISSUE THREAD

**Issue by chau-intl** [MarcusWolschon/osmeditor4android#1483]
## Vespucci Version
16.1.0

## Download source
Google Play (BETA program)

## Device (Manufacturer and Model)
Xiaomi Mi 9T Pro

## Android Version 
Android v. 11 (MIUI 12.5.1)

## Behaviour/Symptoms
When I create new paths I often end up dragging the path by accident. If the newly created path is connected to an existing path the existing path is moved along with the newly created path - as expected. When I then try to undo the movement, the undoing process is undoing the creation of the new path instead of the movement.

## Expected Behaviour
When dragging a newly created path connected an existing path and thus moving both of them I expect the undo button to undo the movement I just made and not part of the creation process.

## How to recreate
0. Unlock>
![1_step](https://user-images.githubusercontent.com/6311686/140657926-7bc97e50-5752-435b-82a3-70f9456c99a0.jpg)
1. Long click on an empty area to create a new object:
![2_step](https://user-images.githubusercontent.com/6311686/140657929-555114e4-82c4-4033-89e9-0fd9400f3d49.jpg)
2. Click on a vertex of an existing path element:
![3_step](https://user-images.githubusercontent.com/6311686/140657936-d8471de1-513a-4ddf-ab7c-37ef289eab14.jpg)
3. Move the new path by dragging it:
![4_step](https://user-images.githubusercontent.com/6311686/140657941-108cacd9-52db-4f40-93d8-78f0d599673c.jpg)
4. Press undo to undo the movement:
![5_step](https://user-images.githubusercontent.com/6311686/140657949-854ae130-8815-40aa-b73b-3ee88251311a.jpg)
5. Observe that the movement is ignored but the placement of the second vertex is undoed.

## Crash dump submitted (no or yes + date)
No

**Comment by simonpoole** [comment]
That looks like regression as from 15.1 on you shouldn't be able to drag the way in the 1st place. All additions when creating or appending to a way are now in the same undo checklpoint and there is not really a way to undo the move on its own. 

See http://vespucci.io/help/en/15.1.0%20Release%20notes/#user-interface-changes-and-additions

**Comment by simonpoole** [comment]
There are two ways we could potentially handle this:

- drop out of  path creation mode when the way gets dragged (and create a separate checkpoint for the drag), disadvantage the user needs to then continue appending manually and maybe it is a bit confusing for the mode change to happen automatically
- disallow way dragging in path creation mode, disadvantage the drag functionality is removed

**Comment by chau-intl** [comment]
>     * disallow way dragging in path creation mode, disadvantage the drag functionality is removed

Until undo-operations gets more advanced, I think this method is the most simple way to go. I haven't needed dragging to be enabled while creating new objects.
