### ISSUE TITLE
Feature Request: Title Case in the name field

### ISSUE THREAD

**Issue by pkoby** [MarcusWolschon/osmeditor4android#1484]
I've requested this feature in OSMAnd and it never went anywhere. Maybe it will here?

When adding POIs, usually the minimum I add is type and name. The name field (and all others) by default inputs as lowercase. Names almost always should be Title Case, so it would be awesome if this was the default input method.

I _think_ that the Android code for this would be changing `android:inputType="text"` to `android:inputType="textCapWords"` for that input field.

**Comment by simonpoole** [comment]
Thanks for the suggestion, it may need some locale/location dependence though.

**Comment by alesarrett** [comment]
I would prefer to use `android:inputType="textCapSentences"` instead of `android:inputType="textCapWords"` because, generally speaking, not all the words should be capitalised.

**Comment by Zverik** [comment]
Most commonly in English-speaking countries. Most countries do not capitalize all the words. To me, `textCapSentences` would be the best option.

**Comment by simonpoole** [comment]
https://en.wikipedia.org/wiki/Capitalization
