### ISSUE TITLE
Validator settings UI problem in german (and perhaps other languages)

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1486]
## Vespucci Version
16.1.0

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Language
German

## Behaviour/Symptoms
Perhaps this problems depends on the resolution of the screen of your device, I don't know ... And it's also only problematic if you hold your phone in an upright position (not turning it to landscape format). I describe my situation and experience ...

The validator settings for configuring the validation rules has 2 tabs. In english their column titles are "Re-survey" and "Check" and you can see the two tabs if you enter the setting sceen – or you see at least that there is something more than only the "Re-survey" column/tab ... if you take a close look (you see the word "Check") – it could also be clearer in english.

But in german, the first title has much more characters: "Noch einmal überprüfen" and you see nothing of the second title. The result: you can only see the first tab if you enter the settings ... and if you don't know that there is a second tab and you need to swipe left, you will perhaps never detect the "Check" tab ... It just looks as if there is only this screen with the "Noch einmal überprüfen" settings. I remember that it took some time until I detected the second tab! It's a longer time ago, but I wanted to post it now, because it didn't change since that time ... Perhaps it can help other (new) users in Germany or other countries.

Here are some screenshots to show the problem:

English (very good that it's possible to disable translations in the UI now!!!):
![Validator settings screenshots EN](https://user-images.githubusercontent.com/48966999/140867237-817bce41-19c7-49e2-892d-b94b10be323b.png)

German:
![Validator settings screenshots DE](https://user-images.githubusercontent.com/48966999/140867368-256a0db4-3fb5-4cc6-bc68-a9c7a518b835.png)

## Expected Behaviour

Perhaps you can improve the UI here by simple changes, e.g. simply split it in 2 separate setting screens without swiping left/right like:
- Validator Settings – Re-survey key/values
- Validator Settings – Check for missing keys [could perhaps also be more self-explanatory than only "Check"]

Or perhaps you have a better idea ...

**Comment by simonpoole** [comment]
The simplest solutions are to shorten the German translation, or line break it (not sure if the later is possible with the tab widget).

**Comment by simonpoole** [comment]
I've improved the translations a bit that should fix the issue in the next maintenance release.

**Comment by jajajaneeneenee** [comment]
> The simplest solutions are to shorten the German translation, or line break it (not sure if the later is possible with the tab widget).

That's really a very simple solution ...but a good one?  I'm not sure ... I didn't thought that you propose **THAT**. And other languages could also be affected ... I don't think this swiping screen design is really a good solution for these settings. Not even in english ...
