### ISSUE TITLE
Whiny about _link refs

### ISSUE THREAD

**Issue by zyphlar** [MarcusWolschon/osmeditor4android#1490]
As a follow-up to #211 only [6% of motorway_links have a ref](https://taginfo.openstreetmap.org/tags/?key=highway&value=motorway_link#combinations) and the wiki is very unclear about what exactly that ref value should be. (There are at least three possible "IDs" involved in a US interstate onramp/offramp: the ref of the motorway so the link is part of the "network", the name ref of the other road (may overlap with destination:ref or destination:street) and the identifier of the ramp itself (in USA, usually the exit number.)

In issue #211 the author seems to be of the opinion that all or most links should have a ref, but it's been awhile and the OSM database and wiki doesn't appear to agree with that. I've been filling in link refs like a madman with my own interpretation of the best thing to do, but then I realized I'm not in good company there: Vespucci is making me think something is critical when nobody else in the world seems to agree.

The Vespucci author's opinions aside, are there any authoritative ideas about what's best here, and can we make Vespucci in alignment with that?

## Vespucci Version
16.1.0

## Download source
Google play store

## Device (Manufacturer and Model)
Samsung Galaxy S21

## Android Version 
11 stock

## Behaviour/Symptoms
Vespucci validation errors don't seem to reflect a consensus in the wiki or other validators like iD and JOSM

## Expected Behaviour
Even if there isn't "one right way" to tag in OSM, validation errors in the GUI should probably only appear for items where a consensus has been reached that the current tagging or geometry is quite wrong, and where clear guidelines are documented in the wiki for proper usage. 

For example, it appears that a motorway_junction that is not attached to a way with a destination tag is far more problematic than a motorway_link without a ref tag, but one gets a magenta highlight and the other is treated by Vespucci as fine.

## How to recreate

- Go to any of the 94% of motorway_link highways in the world, and note the magenta coloring in Vespucci advising that a ref is required
- Go to [highway:motorway_link](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dmotorway_link) and [ref](https://wiki.openstreetmap.org/wiki/Key:ref) and [Highway link](https://wiki.openstreetmap.org/wiki/Highway_link) and try to figure out what the right value for `ref` should be

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/issues/211 is 7 years old and the current mechanism to highlight elements literally has nothing to do with that. Highlightling missing tags has been based on presets for a long time see http://vespucci.io/help/en/Preferences/#validator-settings a possible way to address this would be to make the ref/name optional for motorway_link, but in any case the issue belongs in the preset repo https://github.com/simonpoole/beautified-JOSM-preset

Note that I can't move issues, there so pls C&P this in to a new issue there so that the discussion can continue.

**Comment by zyphlar** [comment]
Ah ok. I tried browsing that repo but I couldn't tell if that was the case.
