### ISSUE TITLE
Spelling error in Golf club preset value 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1492]
Description:
---

The "Golf club" preset value is spelled wrong.

It say: golf=clubhuse 
...instead of: golf=clubhouse 

Device info:
---
<table>
<tr><td>App version</td><td>16.1.0.0</td></tr>
<tr><td>App version code</td><td>1902</td></tr>
<tr><td>Android build version</td><td>G986BXXU9DUH2</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RP1A.200720.012.G986BXXU9DUH2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>y2s</td></tr>
<tr><td>Device model</td><td>SM-G986B</td></tr>
<tr><td>Device product name</td><td>y2sxeea</td></tr>
<tr><td>Device hardware name</td><td>exynos990</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Christoffre"/>Christoffre</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Thanks for the report, fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/847f5599301ab2de0eccee6185ad5bd760dd5e24

Note that preset issues should go to the preset repo https://github.com/simonpoole/beautified-JOSM-preset

**Comment by HolgerJeromin** [comment]
You can add links to the other repos to the issue templates:

https://github.com/openstreetmap/iD/pull/8746
