### ISSUE TITLE
Android 11, download fails, permissions allegedly denied?

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1500]
Description:
---

Vespucci 16.1.1
Flavor: current
Target SDK: 30
Permissions: 
Permissions not available
Maximum avaliable memory 536870912
Total memory used 47491101
Tile Cache MAPNIK usage Size 38273024 of maximum 67108864 #entries 146
Tile Cache AJT usage Size 44302336 of maximum 67108864 #entries 36
State file size 19463 last changed 2021-12-04 21:15:48
Bug state file size 3678 last changed 2021-12-04 21:15:48
Relations (current/API): 0/0
Ways (current/API): 27/0
Nodes (current/Waynodes/API): 262/262/0
Available location providers
passive enabled true
network enabled true
gps enabled true
Display name SomeoneElse

Note in "app permissions" it says "no permissions denied"

Device info:
---
<table>
<tr><td>App version</td><td>16.1.1.0</td></tr>
<tr><td>App version code</td><td>1903</td></tr>
<tr><td>Android build version</td><td>00WW_1_200</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>00WW_1_200</td></tr>
<tr><td>Device brand</td><td>Nokia</td></tr>
<tr><td>Device manufacturer</td><td>HMD Global</td></tr>
<tr><td>Device name</td><td>SCW_sprout</td></tr>
<tr><td>Device model</td><td>Nokia X10</td></tr>
<tr><td>Device product name</td><td>ScarletWitch_00EEA</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/SomeoneElse"/>SomeoneElse</A></td></tr>
</table>

**Comment by SomeoneElseOSM** [comment]
For completeness, in "app permissions" I see
Allowed:
Files and Media: Media
Location: Only while app is in use
Denied:
No permissions denied

Remove permissions if app is unused (no - I explicitly turned that off)

**Comment by simonpoole** [comment]
To clarify:

- the download failing is downloading data from OSM?
- is this a new install or is this an existing install that stopped working? (or OS upgrade or similar?)

**Comment by SomeoneElseOSM** [comment]
> the download failing is downloading data from OSM?

it appears to be, yes

> is this a new install or is this an existing install that stopped working? (or OS upgrade or similar?)

It's a brand new install on a new phone.

**Comment by simonpoole** [comment]
That's weird, downloading data doesn't write directly to device storage and doesn't need any permissions in any case. So it is very unclear what is happening.

In any case could you try to download and then immediately send a crashdump from the debug screen. That will include the last lines from the log which may help in pinning down the issue.

**Comment by SomeoneElseOSM** [comment]
OK, sent.  The screen I pressed "Send debug info" on had similar info to "Description:" above - have you now received something sensible?

**Comment by simonpoole** [comment]
> OK, sent. The screen I pressed "Send debug info" on had similar info to "Description:" above - have you now received something sensible?

Sorry it was bed time. Yes I received the dump but it looks completely normal and suspect that the error message may not have anything directly to do with the download. 

Just to tick off the "is it plugged in" type of errors:

- you shouldn't have a filter button in the middle of the right hand side
- if you open the layer control check that the data layer is above any imagery layer that might obscure it (that should be automatic, but has been known to go wrong)

**Comment by SomeoneElseOSM** [comment]
> if you open the layer control check that the data layer is above any imagery layer that might obscure it (that should be automatic, but has been known to go wrong)

Thanks - that was exactly it.  The custom layer was added as "OSM Based map" this time and had somehow been added to the top of the list.  Also "save and set" in the custom layer settings adds a new copy of an imagery layer to the top of the list, even if there's only one layer in custom list and it's already being displayed.

**Comment by SomeoneElseOSM** [comment]
This issue can be closed now.  See linked enhancement issues above for more detail.  I'm not https://github.com/vespucci-reporter so I can't close this myself.
