### ISSUE TITLE
It'd be great if full screen mode wasn't set to "auto" by default on new installs

### ISSUE THREAD

**Issue by SomeoneElseOSM** [MarcusWolschon/osmeditor4android#1502]
As noted at http://vespucci.io/tutorials/faq/#fullscreen-mode-doesnt-work-properly and http://vespucci.io/tutorials/faq/#navigation-gestures-on-android-9-and-later , there are some odd interactions both between fullscreen mode and gesture-based navigation and fullscreen mode and the non-gesture buttons at the bottom of the screen.

The only way I've found to get everything to work together is (with 3 button navigation set) to change Vespucci fullscreen mode from "auto" to "never".

Also, in the absense of on-devcie searchable help (see https://github.com/MarcusWolschon/osmeditor4android/issues/1501 ) this is a bit of a challenge to find:

Preferences
There's "user interface settings" displayed here, but "fullscreen mode" is not there.

Advanced Settings
User interface settings (another entry with that name)
fullscreen mode
Never (default is auto, other options are "force" and "no statusbar")

**Comment by simonpoole** [comment]
The reason that it is set to automatic as default because "in general" this is the user friendly option. Unluckily Android 11 is causing more issues with detecting exactly what UI mode the device is in (there is no API for this so it is a series of hacks), however for example for Samsung devices it continues to work well. 

The current solution is to blacklist devices with known issues, I might expand that facility or simply disable automatic mode for Android 11 devices.

**Comment by simonpoole** [comment]
@SomeoneElseOSM can you jog my memory what device/OS version this was on?

**Comment by SomeoneElseOSM** [comment]
> @SomeoneElseOSM can you jog my memory what device/OS version this was on?

A Nokia X10, which at the time was running Android 11.

**Comment by simonpoole** [comment]
When you were experiencing the issues did you have gesture nav turned on, or was it a case of having navbar turned on and swiping up to show it while Vespucci is in fullscreen mode not working (or something else).

**Comment by SomeoneElseOSM** [comment]
> When you were experiencing the issues did you have gesture nav turned on,

I've no idea unfortunately - it was a new phone, with Android 11 on it.  From memory I think that gesture nav is turned on by default, and I did turn that off, but whether I did that before or after installing Vespucci I can't remember.
