### ISSUE TITLE
If data is downloaded behind a layer that is likely to be opaque, display a warning

### ISSUE THREAD

**Issue by SomeoneElseOSM** [MarcusWolschon/osmeditor4android#1503]
This was the biggest contributor to https://github.com/MarcusWolschon/osmeditor4android/issues/1500 earlier.

For whatever reason, a new custom "OSM based map" layer was added at the top of the imagery list above "tasks" rather than at the bottom below aerial imagery.  Users can also manual move layers to be in a "non-sensible" order, with opaque-background layers above transparent-background ones.

Although Vespucci can't know whether a particular layer _actually_ has an opaque background or not, it can assume that one added as "OSM Based Map", "Aerial Imagery" etc.  might have, and then when data is downloaded into a layer behind that, display a warning.

**Comment by simonpoole** [comment]
"Save and set" in the custom imagery modal wasn't using the mechanism to correctly arrange imagery that is otherwise used when adding new imagery layers (via the "+" button).

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/pull/1515
