### ISSUE TITLE
Custom imagery setup is confusing

### ISSUE THREAD

**Issue by SomeoneElseOSM** [MarcusWolschon/osmeditor4android#1504]
Logically, I'd expect to:

Click "layers" menu at top right
Click "add".  Lots of options appear, not all obvious ("Add imagery from OAM")
One that I'd expect to work is "Add background imagery layer", but there seems to be no way there to add custom imagery here.

Instead, I have to go into
Settings
Custom imagery
Add
"Save and Set"
Which I think both adds to the "Custom imagery list" and the "list of layers visible from the layer menu"?

**Comment by simonpoole** [comment]
This is simply the remaining (well not quite the last one, but the last one that really matters) from the introduction of the layer control, simply hasn't been done yet.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/pull/1515
