### ISSUE TITLE
Editing a custom imagery layer can add it multiple times as a selected layer

### ISSUE THREAD

**Issue by SomeoneElseOSM** [MarcusWolschon/osmeditor4android#1505]
(somewhat related to https://github.com/MarcusWolschon/osmeditor4android/issues/1504 )

Preferences
Custom Layers
Tap an existing custom layer
Make some changes
Save and set
Done

Via the layers menu I now have this layer listed twice.  The new entry goes in at the top of the list (which is presumably part of what casued https://github.com/MarcusWolschon/osmeditor4android/issues/1500 , see also https://github.com/MarcusWolschon/osmeditor4android/issues/1503 ).

Is there actually a reason why someone would want to add the same layer twice?  I can't think of one.

**Comment by simonpoole** [comment]
> Is there actually a reason why someone would want to add the same layer twice? I can't think of one.

Yes, for example a mosaic with different max zooms depending on location.

But it should at least warn if the entries are actually identical.

**Comment by simonpoole** [comment]
I misunderstood this, naturally editing an existing layer should not duplicate the entry.
