### ISSUE TITLE
"Permissions" info on three dots menu / debug can confuse users

### ISSUE THREAD

**Issue by SomeoneElseOSM** [MarcusWolschon/osmeditor4android#1507]
(well it confused me!)

See the title of https://github.com/MarcusWolschon/osmeditor4android/issues/1500 for an example:

    Permissions:
    Permissions not available

What I think that bit of debug is trying to say is:

"Permissions on Android used to be handled in a certain way that made it relevant to check that first-run app permissions had been granted.  Now, Android has moved more to runtime permissions that are requested as needed, making the need to check for currently granted permissions less relevEnt"

What I read was:

"This app is trying to find details of permissions and thinks that it has not been granted any, and is confused"

If permissions are expected to be "not available" (or whatever this check is doing) in a particular build or on a particular version of Android, perhaps expand the text slightly to reflect this?

**Comment by simonpoole** [comment]
Actually it is just that the the OS no longer reports the available permissions via the API that is in use there, so the line should simply be removed.
