### ISSUE TITLE
Device (screen) rotation in form based editor – preset matching gets lost

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1510]
## Vespucci Version
16.1.1

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
If I turn my device for a screen rotation. e.g. from portrait to landscape and I am in the form based editor view, the preset matching gets lost. Then ”Unknown element (no preset found)” is displayed in the title. This happens since some time – I think it was OK in the past (but not 100% sure, because I normally work in portrait view only).

Here is an example with screenshots:

(1) Before rotating the device:
![Screenshot_1](https://user-images.githubusercontent.com/48966999/145661630-c8d59cd1-48cf-44a5-8967-b4bbd2aaf82d.png)

(2) After rotation to landscape:
![Screenshot_2](https://user-images.githubusercontent.com/48966999/145661636-0e4ee074-73e6-4a50-86a0-8bd4c1601575.png)

(3) After rotation back to portrait:
![Screenshot_3](https://user-images.githubusercontent.com/48966999/145661648-81b2d545-3a8b-497f-9dbe-52bfd21578ce.png)

I have to leave the editor and enter it again to get the matching back ...

**Comment by simonpoole** [comment]
This is a regression.

**Comment by simonpoole** [comment]
Something that used to work, but broke.

**Comment by jajajaneeneenee** [comment]
Ah, OK ... quite obvious. Thank you for clarification!
