### ISSUE TITLE
Touching a map link in the the lower left corner and using „back“ initiates the NEW mode

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1512]
## Vespucci Version
16.1.1

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
If you (mostly accidentially) touch the link of a background map (e.g. of the OpenStreetMap layer or Bing layer) in the the lower left corner and then use the "BACK" function of your device, you find yourself in the NEW Mode in Vespucci. And if you don't notice it at once and tap on the screen, you already have created a line of 2 nodes ...

See screenshots (step 1 = touching the link, step 2 = after going back, step 3 = after tapping somewhere on the screen):

![Screenshot-1–3](https://user-images.githubusercontent.com/48966999/145665048-dbfe8997-5654-40e0-9760-2761a7807b7c.png)

## Expected Behaviour

This should not happen ... And there should be a way to prevent a website from being called up immediately when you touch the link (at least a message whether you want that, or – better – a preference option to switch it off completely - because  it can also be called via the layer menu under "Info"). Or simply removing it there?

I really very often touch this link accidentially ...

**Comment by simonpoole** [comment]
For whatever reason the system seems to detect a long press instead of completely consuming the touch event (there's a beep if you are in "Simple mode") this is clearly a regression vs previous behaviour.
