### ISSUE TITLE
Placeholder id not found, can't upload

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1513]
Description:
---

"The API responded with an error, please save your data and report the issue:

Placeholder id not found for node reference -258"

What should I do?

Device info:
---
<table>
<tr><td>App version</td><td>16.1.1.0</td></tr>
<tr><td>App version code</td><td>1903</td></tr>
<tr><td>Android build version</td><td>eng.yacha.20210809.024407</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RQ3A.210805.001.A1</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>lavender</td></tr>
<tr><td>Device model</td><td>Redmi Note 7</td></tr>
<tr><td>Device product name</td><td>lineage_lavender</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Martino Scaglione"/>Martino Scaglione</A></td></tr>
</table>

**Comment by simonpoole** [comment]
You should save your edits as a "JOSM File", and for good measure export to an OSC file too.

Then it would be good if you could add the OSC file to a comment here so that I can have a look at it.

Did any thing go wrong during editing or any other weirdness?

**Comment by martino2002** [comment]
Thank you for your so quick help!
Yeah, actually, when I tried to create buildings and square them the squaring didn't work.
Apart from that I don't recall anything.
It should be noted also that my changesets count increased of 1 everytime I clicked on the "close open changeset" button. This is not really a problem, but out of curiosity, is it reversible?
[2021-12-11T171047.txt](https://github.com/MarcusWolschon/osmeditor4android/files/7697484/2021-12-11T171047.txt)

**Comment by simonpoole** [comment]
There is nothing technically wrong with the. OSC file however the node with ID -258 is not referenced by anything which would seem to be weird. You might want to search for it and check if something is missing there.

Why are you manually closing the chsngesets? Except if you are deliberately not closing them on upload that is never necessary.

**Comment by martino2002** [comment]
For no reason at all, I've seen that button and since I haven't had anything better to do I clicked it more than once.

**Comment by simonpoole** [comment]
> For no reason at all, I've seen that button and since I haven't had anything better to do I clicked it more than once.

But you normally wouldn't be able to access the button except if you have auto-closing unchecked.

In any case have you retried the upload?

**Comment by martino2002** [comment]
It is probably an exception, when an upload fails the system opens nonetheless an empty changeset. I've seen this button only on this occasion.
However yes I succeeded :) Thank you for your help.
