### ISSUE TITLE
Kann nicht mehr bearbeiten 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1520]
Description:
---

Moin,

Seit dem letzten Update kann ich nichts mehr bearbeiten. Die 'klickbaren' Kreise um die Knoten sind nicht mehr da. Nach dem Download der Daten und dem entsperren erscheint nichts. Früher ging das wunderbar. Mit meinem Tablet geht's. Christophe 

Device info:
---
<table>
<tr><td>App version</td><td>16.1.1.0</td></tr>
<tr><td>App version code</td><td>1903</td></tr>
<tr><td>Android build version</td><td>A320FLXXS9CTK2</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>R16NW.A320FLXXS9CTK2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a3y17lte</td></tr>
<tr><td>Device model</td><td>SM-A320FL</td></tr>
<tr><td>Device product name</td><td>a3y17ltexc</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7870</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Hunte"/>Hunte</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Du sollest zuerst mal überprufen ob

- kein Filter eingeschaltet ist
- der Datenlayer nicht von einer nicht transparenten Layer verdeckt wird 

Die Anzeige der Layer sollte ungefähr wie folgt aussehen, sprich Datenlayer über den Hintergrund:

![Screenshot_1639759909](https://user-images.githubusercontent.com/1011860/146579810-8413a8cb-aab8-4e2a-933f-854eb48a6836.png)

**Comment by simonpoole** [comment]
Resolved (filter was enabled).
