### ISSUE TITLE
Map icon display of nodes by matching with a preset item which is only defined for ways

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1523]
## Vespucci Version
16.1.2

## Download source
Google Play Store

## Behaviour/Symptoms
Today I made a surprising experience when testing something with railway platforms ... Something that I have never consciously noticed before.

I tagged a single **node** with <code>railway=platform</code> by entering the key/value manually in the editor (yes, I know, the old legacy scheme – it's only for a test) – this is normally not an "allowed" tag on nodes, but only for ways, closedways, multipolygons – and I got an icon on the map in Vespucci of the preset item "Railway Platform" – without any highlighting that something is wrong ... (This item is correctly defined with <code>type="way,closedway,multipolygon"</code>.)

The same happens for example if you tag a single node with <code>highway=residential</code>. And you can also select and edit it without any warning or something else ...

Is this the intended behaviour?

Because you don't have a big chance of noticing such a wrongly tagged single node for example, specially in cases like the railway platform, where the icon looks very nice and correct ...

The same applies in the opposite case, of course, if you tag a **way** with a key which should **only be used for nodes**, e.g. <code>highway=traffic_mirror</code> on a way. Of course there's no icon, only a gray line (but it had the validation error colour if it had no tags at all before). So it also looks quite OK now and it is also not marked with the validation error colour and you get no warning if you select or edit it (then the preset matches in the editor and also there it looks as if everything is OK).

These cases may perhaps not happen very often, because you have to enter the tags manually (the "wrong" presets itself are of course not shown if you select an **untagged** node or way and go to the list of  presets in the editor to tag it by selecting a preset item). But it can also happen if you weren't careful with copying / pasting of tags in the editor. And perhaps you had multiple objects selected with a mixture of ways and nodes and didn't notice that. So I don't think that's a complete unrealistic scenario ... And that's why I wrote this issue – to help reduce human errors, which can happen ...

## Expected Behaviour
It would be nicer if it would at least get a **validation error** (with the thick coloured outline) or/and a **warning** if you select it or edit it. Or no icon at all on the map in case of a node (and a validation error)? Or even a special "error" icon? Or a special validation error colour?

Perhaps that's more a feature request ... I'm not sure ... but for me it feels more like a bug and not intended (?).

**Comment by simonpoole** [comment]
There is currently no immediate validation for "wrong object type" as defined by a preset, I suspect osmose will eventually create an issue in such cases.
