### ISSUE TITLE
Message "Error loading EGM" shown on startup

### ISSUE THREAD

**Issue by chris-ca** [MarcusWolschon/osmeditor4android#1524]
## Vespucci Version
Vespucci 16.1.2

## Download source
google play store

## Device (Manufacturer and Model)
Motorola g10

## Android Version 
11

## Behaviour/Symptoms
The error message in the screenshot is shown  briefly whenever Vespucci is opened.

![Screenshot_20211223-110938.png](https://user-images.githubusercontent.com/13023534/147211095-5589cf66-c554-4402-b343-692d3edc7e4b.png)

## How to recreate
Open Vespucci

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
I never had a "blau.de" app installed

**Comment by simonpoole** [comment]
Seems as if you installed the EGM (earth gravitational model) file at one point in time and it is no longer available, or maybe moved. Did this start happening after you upgraded to 16.1 or maybe your phone to Android 11? 

Try de-installing (and potentially re-installing) via the "Tools" menu.

PS: de.blau.android is the package name of the Vespucci app which is used by Android to name the private directories.

**Comment by chris-ca** [comment]
Thanks, that did the trick!

Yes, the message started showing some months ago, probably after updating to v16. I wasn't even aware I had previously installed EGM myself
