### ISSUE TITLE
documentation is out of date but how to document is not written down

### ISSUE THREAD

**Issue by niccokunzmann** [MarcusWolschon/osmeditor4android#1526]
When I read the [release notes](http://vespucci.io/help/en/16.1.0%20Release%20notes/), I read that the documentation is out of date.

I would expect a Wiki page on how to document things.
E.g. How do I edit the front page to include F-Droid as source?
Where is documentation located? GitHub? Wiki? Separate Website?
Is documentation translated?

**Comment by simonpoole** [comment]
You didn't look very far, see https://github.com/MarcusWolschon/osmeditor4android/blob/master/DOCUMENTATION.md

Note that f-droid is not mentioned on purpose.
