### ISSUE TITLE
The timestamp in file names of OSC files could use the correct local time

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1529]
## Vespucci Version
16.1.2

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
When I exported changes to an OSC file yesterday, the filename was set to "2022-01-05T175748.osc". But the correct time was 18:57. See screenshot (from a file manager). 

Not a big issue, but I wanted to report it anyway. It could be confusing when you have different OSC files saved and time is of the essence in choosing the right one afterwards – and in Vespucci I only see the date (and the file name and file size) when using the command "Apply changes from OSC file".

Screenshot from an external file manager:
![Screenshot_20220105_185832_timestamp_OSC_file_50%](https://user-images.githubusercontent.com/48966999/148315818-c6f01ff2-045d-4cfc-a25e-7c956e80c72d.jpg)

My time zone is CET (UTC +1) ... I'm in Germany (winter time) ...

## Expected Behaviour
The file name should use the correct local date and time.

## How to recreate
obvious

**Comment by simonpoole** [comment]
It currently simply uses UTC (as all of OSM), not doing so would create issues with ordering when you cross timezone boundaries. The "proper" fix is to allow specifying the name, the solution with date and time is really only appropriate for emergency state saves which is were this comes from.
