### ISSUE TITLE
Javascript in a preset item can crash Vespucci

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1531]
## Vespucci Version
16.1.2

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
This is not meant to be maliciously composed code ... I came across it when I was creating some complex presets with Javascript and once accidentally built it that way (forgot to remove some lines) ... And I was able to break it down to the following code (a Javascript that does nothing, but it also happens if you add some other Javascript lines).

Vespucci will crash with this code in a preset xml:

	<item name="Crash by Javascript and Fixed Tag" icon="Crash_TEST_Icon.png" type="node" preset_name_label="true">
		<key key="crashtest" value="xxx"/>
		<text key="javascript_crash_test" javascript="
		tags.remove('javascript_crash_test');" />
	</item>

Under these conditions and with these steps:

- The key "crashtest" has to be add to "object_keys" (the item should match with <code>crashtest=xxx</code>). Or simply use another object key for the test.
- Create a node with <code>crashtest=xxx</code> or use the preset one time (once is not once - once it works )
- Leave the editor
- Select the node (or keep it selected after creating) and press the edit button

If you want you can use this icon for the "Crash_TEST_Icon.png" ... ![Crash_TEST_Icon](https://user-images.githubusercontent.com/48966999/148666838-89ad4653-2329-4769-8154-a197e5b79e0a.png)

 ☺

First I thought it would only happen if you apply the fixed key value tag in the Javascript code (e.g. with a line

    tags.put('crashtest',['xxx']);

Or it you assign a value to any other key. But that's not necessary. Now I suspect that it is simply due to the **combination "fixed key value" + Javascript text field**. (Or more generally a Javascript text field + other fields/keys which are object_keys which take part in the matching process?). And I am not 100% sure, but perhaps it worked in earlier versions of Vespucci (no crash), because I had this problematic combination in one preset since a longer time ...but not sure if I ever used it in the way it causes a crash. And because you can use it ONCE without a problem (if it's not a node with THIS key-value combination).

Just to mention: other combinations of a Javascript text field with other fields, e.g. with a simple text field are working fine, e.g. something like that:

	<item name="Javascript add note + text field (name)" icon="Crash_TEST_Icon.png" type="node" preset_name_label="true">
		<text key="javascript_crash_test" javascript="
		tags.put('Note',['Example note']);
		tags.remove('javascript_crash_test');" />
		<text key="name" text="Name" default="Example name"/>
	</item>

But perhaps it only works fine if no matching takes place by the other fields, (which can also be caused by a variable value field ... which means, that the other key in the item is an object key – coded as a combo/multiselect/check or text field). I did not test THIS to the end ...

I don't know if you want to intercept this problematic case, I only wanted to report it, because it was a bad surprise as it happened. Of course it's not a good idea to mix a fixed key value field with a Javascript text field – but I even use it sometimes with other fields (mostly with TEXT fields and non-object keys), and never together with fixed key value fields or other matching keys to avoid bad side effects like this one ... Hope you won't eliminate the ability to mix Javascript text fields with other (unproblematic) fields ... And changing the values of object keys in Javascript is of course not a problem (just to mention that).

## Expected Behaviour
I don't know exactly – I perhaps cannot see every dimension here. But at the end nothing bad should happen ... no crash would be nice. Now I don't know if a Javascript text field (or more than just ONE!) can peacefully coexist with all other types of keys and fields and the matching process ... you will know better ...

**Comment by simonpoole** [comment]
Did you submit a crash dump? If not could you do so?

Thanks.

**Comment by simonpoole** [comment]
Fixed, this doesn't mean that adding the key of such field to object_keys actually makes sense.
