### ISSUE TITLE
Tag:service=parking

### ISSUE THREAD

**Issue by Davileci** [MarcusWolschon/osmeditor4android#1534]
Description:
---
Invalid preset: Service way type=Estacionamiento (spanish)
https://wiki.openstreetmap.org/wiki/Tag:service%3Dparking_aisle#Possible_Tagging_Mistakes

Device info:
---
<table>
<tr><td>App version</td><td>16.1.2.0</td></tr>
<tr><td>App version code</td><td>1904</td></tr>
<tr><td>Android build version</td><td>00WW_2_16A</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>00WW_2_160_SP01</td></tr>
<tr><td>Device brand</td><td>Nokia</td></tr>
<tr><td>Device manufacturer</td><td>HMD Global</td></tr>
<tr><td>Device name</td><td>CBL</td></tr>
<tr><td>Device model</td><td>Nokia 1.4</td></tr>
<tr><td>Device product name</td><td>Cable_00EEA</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by simonpoole** [comment]
Please report preset related issues in the preset repo: https://github.com/simonpoole/beautified-JOSM-preset 

That said the value used to be quite popular https://taginfo.openstreetmap.org/tags/service=parking#chronology the "deprecation" of it seems to be undocumented.
