### ISSUE TITLE
Chronik

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1535]
Description:
---

Der 1. Aufruf der Chronik ist ok.
Danach wird bei der Chronik anderer (gleichartiger) Objekte immer das 1. Objekt dargestellt.
Erst nach einem Neustart von Vespucci kann ein anderes Objekt angezeigt werden.

Device info:
---
<table>
<tr><td>App version</td><td>16.1.2.0</td></tr>
<tr><td>App version code</td><td>1904</td></tr>
<tr><td>Android build version</td><td>V12.5.5.0.RFDEUXM</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RKQ1.200826.002 test-keys</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>tucana</td></tr>
<tr><td>Device model</td><td>Mi Note 10</td></tr>
<tr><td>Device product name</td><td>tucana_eea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/biketeur"/>biketeur</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Kannst du ein Beispiel geben? Der Code würde, dass eigentlich nicht hergeben: 
https://github.com/MarcusWolschon/osmeditor4android/blame/2ea55c2709e63f9d86fbac4af6a1a100dabe9b6e/src/main/java/de/blau/android/easyedit/ElementSelectionActionModeCallback.java#L387

**Comment by biketeur** [comment]
https://www.openstreetmap.org/?mlat=51.5860717&mlon=7.4491752#map=17/51.58633/7.44928
anzeigen lassen.
Den Rand des Schrebergartens auswählen und zur tag-Bearbeitung öffnen.
Nichts verändern und sofort wieder schließen. Umrandung des Gebietes wird mit Pfeilen als markiert dargestellt.
Chronik aufrufen. Auf der Karte wird das Gebiet hervorgehoben und Texte dargestellt:
https://photos.app.goo.gl/BqwSTbYcbSh38JZY7
Soweit ok.
Jetzt ein beliebiges Gebäude des Schrebergartens selektieren, die tag-Bearbeitung öffnen und sofort wieder schließen. Das Gebäude ist markiert.
Chronik öffnen.
Es erscheint wieder die Chronik des gesamten Schrebergartens und nicht die des selektierten Gebäudes.

**Comment by simonpoole** [comment]
Interessant, hier auch am konkreten Beispiel nicht nachvollziehbar. Hast du überprüft ob das korrekte Objekt in einem anderen Reiter des Browsers angezeigt wird? Und, wie gehst du jeweils vom Browser in die App zurück?

**Comment by simonpoole** [comment]
Stale and not reproducible.
