### ISSUE TITLE
Add go to end/start of way in way selection actionmode

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1538]

**Comment by aarewhyan** [comment]
I am facing a problem here, when the button is clicked the associated lambda expression is executed but the zoomTo method is not called automatically. Instead, it is called when the user interacts with the MapView again, suggesting it being swallowed by lambda in the process

Here are its two iterations:

 
<img width="601" alt="g1" src="https://user-images.githubusercontent.com/122718496/227941881-ca1cd418-d918-4d75-9d2b-0a19b38bd1f7.png">

<img width="437" alt="G2" src="https://user-images.githubusercontent.com/122718496/227941886-9c8c96ee-eafb-4954-8b0b-e6277bde48bb.png">

**Comment by simonpoole** [comment]
You will typically need to explicitly invalidate the map after zooming or setting the bounding box to a new value.

**Comment by aarewhyan** [comment]
I have updated it.
Should add, there are two methods in Main doing the same work of invalidating map
                   - main.invalidateMap()
                   - main.update()
The second one is only used once in - TaskFragment as - mListner.update(); 
(Redundent or not?)

Now should I rebase my work using force push?

**Comment by simonpoole** [comment]
For starters you need to create a pull request for review and that, if all goes well, will later be merged. 

For complicated re-factorings it will make sense to keep the PR continuously rebased on the main development branch, for something simple most of the time that can be delayed to immediately pre-merge.

**Comment by aarewhyan** [comment]
So sorry, In one of the last PR's you said to rebase not to create PR, maybe that was in different context.

**Comment by simonpoole** [comment]
Completed in https://github.com/MarcusWolschon/osmeditor4android/pull/2200
