### ISSUE TITLE
Keine Hintergrundbilder 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1541]
Description:
---

Das Laden der Hintergrundbilderdatenbank scheint fehlzuschlagen, ich kann keine Hintergrundbilder auswählen.

Device info:
---
<table>
<tr><td>App version</td><td>17.0.0.2</td></tr>
<tr><td>App version code</td><td>2001</td></tr>
<tr><td>Android build version</td><td>FP3Q</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>FP4.FP3Q.A.094.20211213</td></tr>
<tr><td>Device brand</td><td>Fairphone</td></tr>
<tr><td>Device manufacturer</td><td>Fairphone</td></tr>
<tr><td>Device name</td><td>FP4</td></tr>
<tr><td>Device model</td><td>FP4</td></tr>
<tr><td>Device product name</td><td>FP4eea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by Discostu36** [comment]
![Screenshot_20220121-092807_1.png](https://user-images.githubusercontent.com/30999326/150492888-e227bad9-c30d-49ca-a2f7-20c6697a130c.png)

**Comment by Discostu36** [comment]
Seems to fixed in 17.0.3. Ticket can be closed.

**Comment by simonpoole** [comment]
Danke für die Meldung, ist aber bereits behoben siehe https://github.com/MarcusWolschon/osmeditor4android/commit/bdc464910f6f42d51a5967e34b0dbb5e924e2ebe und https://github.com/MarcusWolschon/osmeditor4android/blob/master/CHANGELOG.txt
