### ISSUE TITLE
how to seperate the gradle for android studio 

### ISSUE THREAD

**Issue by piyushshende76** [MarcusWolschon/osmeditor4android#1550]
sir i was not able to separate the Gradle in android studio for some research  can you please suggest how to separate the Gradle and run app on mobile

**Comment by simonpoole** [comment]
Sorry, but it isn't clear what your issue is. You should simply be able to import the project in to Android Studio and build, or alternatively build from the command line with gradle.

If there is a problem with a specific Android Studio version you need to state which version it is.

**Comment by piyushshende76** [comment]
h
