### ISSUE TITLE
Android-Navigationsleiste schlecht bedienbar / Fehleingaben

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1551]
Description:
---

Die Navigationsleiste von Android wird automatisch ausgeblendet, liegt beim einblenden aber genau über der unteren Menüleiste. Wenn man z.B. die App verlassen will, muss man vom unteren Rand hoch wischen, um die Android-Navigationsbuttons zu sehen. Diese werden aber so schnell wieder ausgeblendet, dass man sehr oft versehentlich eine Aktion in der App auslöst, obwohl man eigentlich nur den Zurück-Button antippen wollte. Die Android-Navigation sollte nicht ausgeblendet werden.

Device info:
---
<table>
<tr><td>App version</td><td>17.0.1.0</td></tr>
<tr><td>App version code</td><td>2004</td></tr>
<tr><td>Android build version</td><td>3311891731</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>47.2.A.11.228</td></tr>
<tr><td>Device brand</td><td>Sony</td></tr>
<tr><td>Device manufacturer</td><td>Sony</td></tr>
<tr><td>Device name</td><td>G8341</td></tr>
<tr><td>Device model</td><td>G8341</td></tr>
<tr><td>Device product name</td><td>G8341</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/omicron"/>omicron</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Siehe http://vespucci.io/tutorials/faq/#fullscreen-mode-doesnt-work-properly und http://vespucci.io/tutorials/faq/#navigation-gestures-on-android-9-and-later
