### ISSUE TITLE
how to just seperate map in whole projects 

### ISSUE THREAD

**Issue by piyushshende76** [MarcusWolschon/osmeditor4android#1553]
i was trying to seperate the map only with main activity but unable to seperate that please share a suggestion just to load a single map in mainactivity without any other code

**Comment by simonpoole** [comment]
Vespucci isn't primarily a map viewer, and that part of the app was never developed with reusability in mind. If you simply want to integrate raster maps with an application you would be far better served with osmdroid https://github.com/osmdroid/osmdroid or any number of other libraries with similar functionality.

**Comment by simonpoole** [comment]
No response, closing.
