### ISSUE TITLE
[Bug] Voice input options stay in Simple Mode even if voice commands is turned off

### ISSUE THREAD

**Issue by pkoby** [MarcusWolschon/osmeditor4android#1554]
## Vespucci Version

17.0.7

## Download source

F-Droid

## Device (Manufacturer and Model)

Motorola Moto X4

## Android Version 

Android 9

## Behaviour/Symptoms

In Simple Mode, the light green (+) button shows many options:

- Add tagged node
- Add way
- Add map note
- Add node
- _Add tagged node_
- _Add map note_
- Paste object
- Paste multiple times

The italic items are the voice command inputs. I don't know how to remove these from the menu. In Preferences->Advanced Preferences->Experimental, I have "Enable voice commands off". Toggling it makes no difference.

## Expected Behaviour

I don't want the extra input options in the simple menu, and even if I turn them on, I would think they should have some differentiation to show they're voice inputs.

## How to recreate

? It's in simple mode, that's all I know.

## Crash dump submitted (no or yes + date)

No.

**Comment by simonpoole** [comment]
Thanks for the report. It's simply an issue that nobody noticed during testing.

Will be fixed in the next maintenance release.

**Comment by simonpoole** [comment]
Reopen till maintenance release has happened.

**Comment by simonpoole** [comment]
17.0.2 has been tagged.
