### ISSUE TITLE
Preset matching in property editor does not work if presets are not auto-applied

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#1557]
## Vespucci Version

Vespucci 17.0.1
Flavor: current
Target SDK: 30
## Download source

Play store
## Device (Manufacturer and Model)

Motorola g7 power
## Android Version 

10
## Behaviour/Symptoms

+ABC does not work anymore in Properties Tab
It does still work in Details tab

Related: 
Presets are often not recognized anymore

https://www.openstreetmap.org/way/286019978
shows:
"Unbekanntes Element (keine Vorlage gefunden)"
+ACB does nothing
Swipe to the right
+ABC works
Playground is now detected in Properties Tab

**Comment by HolgerJeromin** [comment]
Ah. If I add a tag via paste or undo the presets are detected. Only on first load the view is not correct

**Comment by simonpoole** [comment]
Worksforme. 

Do you have the default presets loaded? Further it is probably worth checking Advanced preferences/Data and edit settings/Enable auto-apply of preset is checked (the default).

**Comment by HolgerJeromin** [comment]
> Further it is probably worth checking Advanced preferences/Data and edit settings/Enable auto-apply of preset is checked (the default).

Thanks!

**Comment by simonpoole** [comment]
I wasn't expecting that to fix anything though 😃

**Comment by HolgerJeromin** [comment]
It was not checked. But after activating it in my user view the problem is solved.

**Comment by simonpoole** [comment]
Thanks for the report.
