### ISSUE TITLE
Translation too brought for outdoor

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#1558]
I see in translate site for outdoor:

Occurrences
master_preset.xml:2450(combo:display_values|preset:Elevator|key:surveillance):, master_preset.xml:8609(combo:display_values|group:Man_Made|preset:Surveillance|key:surveillance):, master_preset.xml:9823(item:name|group:Clothes|preset:Outdoor):

Only "power" is seperated

**Comment by simonpoole** [comment]
This is a preset issue and needs to be reported in the preset repo https://github.com/simonpoole/beautified-JOSM-preset
