### ISSUE TITLE
WebView content gets lost after device orientation change

### ISSUE THREAD

**Issue by mmc20520** [MarcusWolschon/osmeditor4android#1568]
## Vespucci Version
16.1.3.0

## Download source
f-droid

## Device (Manufacturer and Model)
Android emulator

## Android Version 
10

## Behaviour/Symptoms
WebView content refreshes after device orientation change

For example, click "Authorise OAuth" and randomly browse in the login page. Before rotation:

![pic13](https://user-images.githubusercontent.com/100833575/156699192-983b11ee-23f7-474c-a5dc-de6acc29e3de.png)

After rotation:
![pic14](https://user-images.githubusercontent.com/100833575/156699227-ebc01c9f-a1f0-4688-9e1a-16767de49831.png)

## Expected Behaviour
Web content should remain unchanged

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
Note that the webview in this case is not intended to be used for random browsing and there is no guarantee at all that it will work outside of openstreetmap.org.
