### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by Mahabarata** [MarcusWolschon/osmeditor4android#1571]
Hi,

some typos in the documention : http://vespucci.io/help/en/Introduction/

* in the part "Adding an Area", second section, it is writen : "multi-ploygons"
* in the part "Efficiently Adding Addresses", first section "(_non-simple mode only:)" (chars _ and : looks strange)
* in the part "Check entries", second section, "of the matching preset ." (space before the dot)

Best regards

**Comment by simonpoole** [comment]
Thanks!
