### ISSUE TITLE
"Dirty" state not respected when closing/opening Edit Note dialog

### ISSUE THREAD

**Issue by johantiden** [MarcusWolschon/osmeditor4android#1574]
## Vespucci Version
17.0.3

## Download source
google play store

## Device (Manufacturer and Model)
OnePlus 8 Pro

## Android Version 
Oxygen OS 11 (stock) 

## Behaviour/Symptoms
Edit Note. When trying to close a note, the user can either Upload or Save the changes to be uploaded later. 
If you close the dialog using Save and then reopen the dialog, the Upload button is disabled, forcing the user to instead upload via the action menu. 

## Expected Behaviour
The Upload button is still enabled. 

## How to recreate
1. Open a new note. 
   * Write some text
   * Press upload
2. Press the note to open the dialog
3. Change the state to "Closed"
  (notice that the `Upload` and `Save` buttons get enabled)
4 Press Save
5. Press the note to open the dialog
6. Try to Upload the note
  (notice that the `Upload` and `Save` buttons are _not_ enabled)

## Crash dump submitted (no or yes + date)
no crash

**Comment by simonpoole** [comment]
Not being to upload would seem to be correct as the state hasn't changed relative to the server version so uploading doesn't make sense.

**Comment by simonpoole** [comment]
I can't seem to replicate this issue, mainly because in step 2 it isn't possible to close the note (the drop down is disabled).

**Comment by johantiden** [comment]
[Screen recording on Google Drive](https://drive.google.com/file/d/1biRJEjaFgJEoZe2s9YDetcPq-ZK7qgYe/view?usp=drivesdk)

**Comment by johantiden** [comment]
Still present in 17.0.4

**Comment by simonpoole** [comment]
Does Oxygen OS 11 correspond to Android 11? Still can't recreate here so I need to narrow things down.

**Comment by johantiden** [comment]
Yes, exactly. They keep more up to date than other manufacturers e. g Samsung.
![Screenshot_20220313-153241.jpg](https://user-images.githubusercontent.com/22770524/158064471-4085ccba-e669-4fc9-b2ed-d96a59e09dea.jpg)

**Comment by simonpoole** [comment]
This is the behaviour I'm seeing, which is as expected
![note_issue](https://user-images.githubusercontent.com/1011860/158852534-a0fc94f1-f14a-4fea-9943-69e7b9929004.gif)

**Comment by simonpoole** [comment]
Are you still having issues with 17.0.6?

**Comment by simonpoole** [comment]
Closing as stale and likely fixed.

**Comment by johantiden** [comment]
I can still reproduce this on b90826bdf (17.0.6.0) building with gradle.
I now have Oxygen OS 12.

**Comment by johantiden** [comment]
Running `git bisect` I get this:
```
....

~/git/osmeditor4android 16.0.0.3~72 bisect
❯ git bisect good
Bisecting: 21 revisions left to test after this (roughly 5 steps)
[3e819c376a6898fd24fa9c946ff3c5604ae2b55b] Organize imports

~/git/osmeditor4android 16.0.0.3~54^2~1 bisect
❯ git bisect bad
Bisecting: 10 revisions left to test after this (roughly 4 steps)
[2614ac1f91cd7deafddd1d6889c62c7cba2fba01] Make clearer what a valid WMS entry is

~/git/osmeditor4android 16.0.0.3~61 bisect
❯ git bisect good
Bisecting: 5 revisions left to test after this (roughly 3 steps)
[32b04d82fe482fddb552649cbb3802567018627b] Explicitly set setCancelable to true, even though it is the default

~/git/osmeditor4android 16.0.0.3~57 bisect
❯ git bisect good
Bisecting: 2 revisions left to test after this (roughly 2 steps)
[0882df497d9df494519b2b19f3c8f1b8b5213f17] Rename package containing NSI support

~/git/osmeditor4android 16.0.0.3~54^2~4 bisect
❯ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 1 step)
[59a5ff44c676b5b877e1358e15dc71b463cc854d] Minor code clean up

~/git/osmeditor4android 16.0.0.3~55 bisect
❯ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[610f161a7030b1147997694bc48c099b3c9d322f] Improve business logic when switching state back and forth

~/git/osmeditor4android 16.0.0.3~56 bisect
❯ git bisect bad
610f161a7030b1147997694bc48c099b3c9d322f is the first bad commit
commit 610f161a7030b1147997694bc48c099b3c9d322f
Author: simonpoole <simon@poole.ch>
Date:   Wed Sep 1 20:17:48 2021 +0200

    Improve business logic when switching state back and forth

    Fixes https://github.com/MarcusWolschon/osmeditor4android/issues/1449

 .../java/de/blau/android/tasks/NoteFragment.java   | 20 ++++++++++++++-----
 .../java/de/blau/android/tasks/TaskFragment.java   | 23 +++++++++++++++++-----
 2 files changed, 33 insertions(+), 10 deletions(-)
 ```
