### ISSUE TITLE
Comment stuck in gui after trying to comment on closed note

### ISSUE THREAD

**Issue by johantiden** [MarcusWolschon/osmeditor4android#1575]
## Vespucci Version
17.0.3

## Download source
google play store

## Device (Manufacturer and Model)
OnePlus 8 Pro

## Android Version 
Oxygen OS 11 (stock) 

## Behaviour/Symptoms
This is just a weird glitch. 
On openstreetmap.org, there is no way to comment on a closed note. It seems you have to open it first. 
But in Vespucci, you can (try to) upload text on a closed note. This comment is then tacked onto the last state of the note, totally unrelated. 

## Expected Behaviour
The Upload button is still disabled. 
The Combobox for Open/Close should be disabled with the state Open (because you have to open the note if younwant to comment) 

## How to recreate
1. Open a new note. 
2. Close it (Upload) 
3. Press the note again
5. Write some text in the comment text field. 
- Note the state changes to Open. 
6. Change the state to Closed again. 
7. Press Upload. 

- Now, nothing happens server side, if you view the note again, the text you just wrote is there, but appended to the "closed" state from step 2. 

8. Clear all notes from the Tasks action menu. 
9. Download tasks again from the Tasks action menu. 

- Comment gone. 

## Crash dump submitted (no or yes + date)
no crash

**Comment by johantiden** [comment]
I can still reproduce it in 17.0.4
[Google Drive](https://drive.google.com/file/d/1blfYRjSJE759XU0lNfwh-i4mGKJvtsr3/view?usp=drivesdk)

**Comment by simonpoole** [comment]
Can't reproduce as such. Note there are two different issues

- for mating of new comments when they have just been saved. This is due to some weirdness in the OSM bugs API that I haven't worked around. So I'm still seeing that as expected.
- comment not being saved when the state was set to closed, can't reproduce that.

**Comment by simonpoole** [comment]
>     * formating of new comments when they have just been saved. This is due to some weirdness in the OSM bugs API that I haven't worked around. So I'm still seeing that as expected.
I've addresssed that in https://github.com/MarcusWolschon/osmeditor4android/commit/2eb515f62a80026d09abd921968ccc82a1f52830

**Comment by simonpoole** [comment]
Are you still having issues with 17.0.6?

**Comment by simonpoole** [comment]
Closing as stale and likely fixed.

**Comment by johantiden** [comment]
I can still reproduce it in b90826bdf (17.0.6.0)
