### ISSUE TITLE
preset for emergency_ward_entrance should have entrance=yes

### ISSUE THREAD

**Issue by pippopip** [MarcusWolschon/osmeditor4android#1577]
The preset for `emergency=emergency_ward_entrance` should add `entrance=yes` according to [the wiki](https://wiki.openstreetmap.org/wiki/Tag:emergency=emergency_ward_entrance).

**Comment by simonpoole** [comment]
Please do not open preset issues here (there are multiple larger notices pointing to the correct repo).

**Comment by HolgerJeromin** [comment]
Issue templates could be added like:

https://github.com/openstreetmap/openstreetmap-website/issues/3379

**Comment by simonpoole** [comment]
@HolgerJeromin the issue template already contains text that you can't really miss to that effect, just as the README does.

**Comment by HolgerJeromin** [comment]
People do not read text.
A separate issue entry would make a different

**Comment by simonpoole** [comment]
> People [do not read](https://code.visualstudio.com/blogs/2022/03/08/the-tutorial-problem#_nobody-reads) text.
That was my point, it is just more text that people still don't read.

**Comment by pippopip** [comment]
Kindly stop. I already let it go that you did "not read" the above link, which made you upstream a bugged preset, because all adults without exception have a life and countless legitimate reasons. I dislike going off-topic, unprofessional, disrespectful and stubborn, but if an answer can help you calm down your obsession, also seen in the threads with other people, I am sorry, I got it and will do better next time. Many thanks
