### ISSUE TITLE
compatibility issue when calling method

### ISSUE THREAD

**Issue by Valentin-ys** [MarcusWolschon/osmeditor4android#1579]
Hi, nice day! This time we confirm a callback compatibility issue which might threaten the robustness of your app and give a detailed suggestion for you.

In ''de.blau.android.PhotoUriHandler", you call the framework API "<android.content.ContentResolver: void takePersistableUriPermission(android.net.Uri,int)>" in "onSuccess" method as shown in following. But actually, this method is added in API level 19 (https://developer.android.google.cn/reference/kotlin/android/content/ContentResolver?hl=en#takepersistableuripermission).

```java
if ((intentFlags & Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION) != 0) {
                        Log.d(DEBUG_TAG, "Persisting permissions for " + uri);
                        main.getContentResolver().takePersistableUriPermission(uri,
                                intentFlags & (Intent.FLAG_GRANT_READ_URI_PERMISSION | Intent.FLAG_GRANT_WRITE_URI_PERMISSION));
                        pi.addPhoto(photo);
                    } else { // can't persist, add just to the in memory index
                        PhotoIndex.addToIndex(photo);
                    }
``` 
So when the app try to call this API on devices level 14~19, your app will run with an unpredictable results. So we suggest you add an "if(SDK_INT>19)", " @TargetApi(Build.VERSION_CODES.KiKaT)" or change your app miniSDK from 14 to 19 to fix this potential issue. 
By the way, "@TargetApi(Build.VERSION_CODES.KiKaT)" will be deleted by Android compiler when extracting APKs, so it seems like a not good way to solve those issues.

**Comment by simonpoole** [comment]
This is a false positive. The Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION flag will not be set on versions that don't support the feature.

**Comment by Valentin-ys** [comment]
Thanks, we have not taken this flag into consideration, but actually Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION flag is also introduced in API level 18 (https://developer.android.google.cn/reference/android/content/Intent?hl=en#FLAG_GRANT_PERSISTABLE_URI_PERMISSION), which will return error on API level 14~17.
We suggest you using Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_WRITE_URI_PERMISSION which is added in API level 1.
