### ISSUE TITLE
Add "ruler"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#158]
```
It would be great to have a ruler like in Google Maps that shows how far is a 
distance in the map (3km/2mi).
```

Original issue reported on code.google.com by `koem...@gmail.com` on 11 Jun 2013 at 12:56

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/9df04a6e60bbad6df39d8635ca3a8f443f8618db
