### ISSUE TITLE
Empty relation

### ISSUE THREAD

**Issue by Mahabarata** [MarcusWolschon/osmeditor4android#1580]
Hi,

a few days ago, someone sent an empty relation (no member) to osm database :
[13441833](https://www.openstreetmap.org/relation/13441833/history)

It looks like he deleted a node, the relation had only this node as a member, so the relation became empty and was sent empty. In such a case, ID (the editor) automatically delete the relation : maybe the good solution ?

Could you have a look and try to solve this to prevent another case ?

Best regards

**Comment by simonpoole** [comment]
iDs behaviour in such cases is at least questionable if not outright broken. Vespucci with ask the user if they want to delete the relation or not, obviously the user decided to keep the relation in this case. 

That said empty relations are totally harmless and not a reason for concern.
