### ISSUE TITLE
Data issues link to a broken browser page

### ISSUE THREAD

**Issue by zyphlar** [MarcusWolschon/osmeditor4android#1581]
## Vespucci Version
17.0.4

## Download source
Google Play

## Device (Manufacturer and Model)
Samsung Galaxy S21

## Android Version 
Stock Android 12

## Behaviour/Symptoms
The OSM Data Issues notification, when pressed, does not open Vespucci anymore but instead opens a browser window with a "connection refused" message.

## Expected Behaviour
It should open the issue inside Vespucci as it did previously.

## How to recreate
Download an area in Vespucci with issues. Open the Android notification drawer. Select a Vespucci notification about OSM Data Issues. Notice browser error.

## Crash dump submitted (no or yes + date)
No crash

## Any other potentially relevant information
It used to work, just no longer.

## Screenshot
![](https://i.imgur.com/lmBe6Fw_d.webp?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by simonpoole** [comment]
Are you sure the behaviour changed with version 17? Asking because there were no relevant changes in 17, but it might be a consequence from version 16.1 targeting Android 11.

**Comment by zyphlar** [comment]
It worked about 4-12 months ago, I haven't been paying attention to versions but it's sure possible that any OS or Vespucci or library releases in that timespan are the culprit.

**Comment by simonpoole** [comment]
This is likely just the browser on your device being configured to capture the JOSM RC links. Try resetting the standard apps setting for the browser app in question.

**Comment by zyphlar** [comment]
Thanks this is the correct fix, I recall many other apps requiring explicit permission for being associated with urls once I upgraded to Android 12. It may be possible to detect whether this association is enabled and pop up a warning to instruct the user to enable it.

**Comment by simonpoole** [comment]
Link authorization mechanics has changed for Android 12 it seems and using generic http/https Urls there doesn't seem to be a way around the issues, however using a custom scheme seems to work fine without any real loss of functionality.
