### ISSUE TITLE
Entrance automatically retagged as emergency_ward_entrance

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1582]
## Vespucci Version

17.0.4

## Download source

Google Play

## Device (Manufacturer and Model)
Fairphone 4

## Android Version 

Android 11

## Behaviour/Symptoms
Entrance node [8942309516](https://www.openstreetmap.org/node/8942309516) is shown as emergency  ward entrance on screen, but it is only tagged as
`entrance=yes`.
![Screenshot_20220316-083732_1.png](https://user-images.githubusercontent.com/30999326/158539856-d6b60edf-9695-40a6-97ee-2f1b1e2d413b.png)
When opening the tag editor for the node, `emergency=emergency_ward_entrance` is shown in the editor and saved to the node when closing the editor.

## Expected Behaviour
Render entrance correctly, don't automatically add wrong tag.

## How to recreate
1. Download area around 53.37078° N, 9.59634° E
2. Look at rendering of node 8942309516
3. Open tag editor for the node and look at the detailed tags view
4. Close tag editor and see that an edit has happened

## Crash dump submitted (no or yes + date)
No

**Comment by simonpoole** [comment]
The issue is an unintended consequence of a preset update (see https://github.com/MarcusWolschon/osmeditor4android/issues/1577). Manually updating the preset as per http://vespucci.io/help/en/Presets/#managing-presets "Update of default preset" (remember to disable the pre-installed version).

**Comment by Discostu36** [comment]
Yes, updating the preset has solved the issue. But the update didn't work without problems. I'll see if I can recreate and open a separate ticket. I have also sent a crash report from the app.

**Comment by simonpoole** [comment]
> ..But the update didn't work without problems. 
Note that the matching preset is cache in the object data so you may have had to force a refresh (by existing the app etc) to actually change the matching.

**Comment by Discostu36** [comment]
App crashed when downloading and activating the preset. But I couldn't reproduce it when I did the exact same steps again, so... 🤷‍♂️

Thanks for the quick fix!

**Comment by simonpoole** [comment]
17.0.5 has been pushed to the play store with an updated preset.
