### ISSUE TITLE
Display <desc> of gpx waypoints

### ISSUE THREAD

**Issue by opk12** [MarcusWolschon/osmeditor4android#1591]
I survey with [this app](https://f-droid.org/en/packages/de.hauke_stieler.geonotes/), to collect notes into a GPX that is imported into Vespucci when I am back at home. `<desc>` has the description and `<name>` has an auto-generated identifier. Vespucci displays `<name>` but not `<desc>`. For example, JOSM shows both. An example GPX (trimmed down by hand) and screenshots are below.

**Comment by opk12** [comment]
`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1"><wpt lat="48.84732235851925" lon="2.3633668527374425"><name>341</name><desc>Text of a note</desc></wpt></gpx>`

**Comment by opk12** [comment]
![Vespucci](https://user-images.githubusercontent.com/40740650/159925569-26e25cc5-1780-4c1f-b4dd-4ceb9614ac5d.png)
![josm](https://user-images.githubusercontent.com/40740650/159925590-78fc6667-b358-4e05-91cb-3207c45f1df2.png)

**Comment by simonpoole** [comment]
Would you prefer being able to select what is displayed as label, or would you rather have a combined value?

**Comment by opk12** [comment]
I would like to save some characters on my small screen, so I would rather select what is displayed or input the format string.
