### ISSUE TITLE
DataStyling issue – labels on closed ways are missing if the way has a validation error marking

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1600]
## Vespucci Version
17.0.5

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
It seems that labels on closed ways are not show, if the way has a validation error. E.g.  a building drawed as a closed line which is also tagged with shop=supermarket (and a name of course) with missing opening_hours. It gets the thick coloured validation error outline, and the name **not shown**. If you add the opening hours, the name is displayed.

(I used the data style "Color Round Nodes" for testing.)

Example:

2 buildings with 2 different validation errors: 
![Screenshot_01_with_validation_errors](https://user-images.githubusercontent.com/48966999/160505509-e63686cf-cc01-4300-8039-b420383d4a06.jpg)

Without validation errors:
![Screenshot_02_without_validation_errors](https://user-images.githubusercontent.com/48966999/160505566-87c081ca-221b-4e5f-9408-358d5f7fe4ef.jpg)

## My solution

I modified the styling and added `labelKey="name"` to these lines:

`<feature type="problem_way" updateWidth="true" widthFactor="1.5" color="ffff00ff" style="STROKE" cap="BUTT" join="MITER" labelKey="name" />`

And:

`<feature type="validation" code="2" updateWidth="true" widthFactor="1.5" color="ffffe000" style="STROKE" cap="BUTT" join="MITER" labelKey="name" />`

Then the name was also shown with the coloured validation error outlines (I made no screenshot of this state).

## Expected Behaviour
The label should also be shown if there is a validation error.

**Comment by simonpoole** [comment]
Yes adding labelKey="name" is the correct fix. Note that in general there should be no expectation that the validation styling for ways mirrors the normal styling, in this case the fix just happens to work.
