### ISSUE TITLE
“Zoom to location then undo” doesn't work correctly

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1601]
## Vespucci Version
17.0.5

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
If I press the undo button and the message “Undo location is not in view“ is displayed and I press “ZOOM TO LOCATION THEN UNDO”, then the map will jump to a location about 1.5 km west of the correct location (in a very high zoom level) – it's often outside of the downloaded area and you don't know where you are. This is quite irritating and it is not helpful at all … So I cannot really use this function and have to search the location manually if I want to see what is changing by the undo in such a case.

![Message](https://user-images.githubusercontent.com/48966999/160508620-194d57f6-c102-433b-a98c-4f6051d337a6.jpg)

## Expected Behaviour
Obvious – the map should jump to the correct "undo location”.

## How to recreate
Obvious

**Comment by simonpoole** [comment]
This effects undos of single node changes as then only a degenerate bounding box for the undo operation exists.
