### ISSUE TITLE
Website check displays a red message “Invalid argument”

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1602]
## Vespucci Version
17.0.5

## Download source
Google Play Store

## Device (Manufacturer and Model)
Huawei Honor 7x

## Android Version 
9.1.0

## Behaviour/Symptoms
Perhaps this is a rare or special case, I don't know … Because normally it works fine! But when I recently mapped a new shop and wanted to add a website (in the form based editor) and pressed the **CHECK** button, I got a red message “Invalid argument” and the check did not work:

![Message](https://user-images.githubusercontent.com/48966999/160511125-3f217f67-c6a0-47d8-9dcb-f0355af18f41.jpg)

But the website url is correct – but it has an age verification (which is not really a verification …) which is perhaps loaded/implemented in a special way (not very cleanly?). It seems to reload the page or something like that. The url is: [https://thesmoker-shop.de](https://thesmoker-shop.de)

## Expected Behaviour
The check should work correctly (or display a message that this url couldn't be checked properly, or something like that).

## How to recreate
Obvious

**Comment by jajajaneeneenee** [comment]
What is PR? The unix command? A part of the framework? Or does Vespucci still uses Perpendicular Recording (a joke ...)? For me it is mainly the abbreviation for "Public Relations" ...

OK ... it's not a big problem and certainly a rare case ... But a better (generally understandable) message would perhaps be nice in such a case (403 means that something is forbidden as far as I know) ... e.g.:  "URL validation failed - reason unknown. Please check it in a bowser."

"Invalid argument" sounds as if there is a bug in the code for me ...

**Comment by simonpoole** [comment]
PR == Pull Request ... the center piece of github interactions.
