### ISSUE TITLE
Review edits

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1612]
Description:
---

Sometimes I don't save immediatly and when I reopen Vespucci I would be able to list my modifications.

Thanks,
Alain RUET.

Device info:
---
<table>
<tr><td>App version</td><td>17.0.5.0</td></tr>
<tr><td>App version code</td><td>2008</td></tr>
<tr><td>Android build version</td><td>10.1.0.150C431</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>VOG-L29 10.1.0.150(C431E19R2P5)</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWVOG</td></tr>
<tr><td>Device model</td><td>VOG-L29</td></tr>
<tr><td>Device product name</td><td>VOG-L29EEA</td></tr>
<tr><td>Device hardware name</td><td>kirin980</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Al-Hun"/>Al-Hun</A></td></tr>
</table>

**Comment by simonpoole** [comment]
The simple solution is to start an upload and not actually upload.
