### ISSUE TITLE
OSM problems notification 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1613]
Description:
---

Clicking on the notification for OSM problems leads to a browser pointing to http://127.0.0.1:8111/load_and_zoom?left=8.577383&right=8.5787887&top=50.1987171&bottom=50.1978172&select=way24050445 for example. 
It opens in a browser and not the app. 

Device info:
---
<table>
<tr><td>App version</td><td>17.0.5.0</td></tr>
<tr><td>App version code</td><td>2008</td></tr>
<tr><td>Android build version</td><td>8229987</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>32</td></tr>
<tr><td>Android build ID</td><td>SP2A.220305.013.A3</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>raven</td></tr>
<tr><td>Device model</td><td>Pixel 6 Pro</td></tr>
<tr><td>Device product name</td><td>raven</td></tr>
<tr><td>Device hardware name</td><td>raven</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/juschu"/>juschu</A></td></tr>
</table>

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/issues/1581 it is an Android 12 specific issue which you can avoid by changing your Android settings. We've implemented a workaround that will be available in the next maintenance release.
