### ISSUE TITLE
Menu bar bug

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1619]
Description:
---

When opening the app, the window size is so big it hides the three Android buttons at the bottom (back button ++) 

When tapping a menu icon to open the menu, the three Android buttons overlay the app menu bar so that I cannot close a menu or open a new one without accidentally hit one of the Android buttons.

This behavior is quite confusing! 

Device info:
---
<table>
<tr><td>App version</td><td>17.0.6.0</td></tr>
<tr><td>App version code</td><td>2009</td></tr>
<tr><td>Android build version</td><td>N986BXXS3FVC8</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.N986BXXS3FVC8</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>c2s</td></tr>
<tr><td>Device model</td><td>SM-N986B</td></tr>
<tr><td>Device product name</td><td>c2sxeea</td></tr>
<tr><td>Device hardware name</td><td>exynos990</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/haabe"/>haabe</A></td></tr>
</table>

**Comment by HolgerJeromin** [comment]
See
https://vespucci.io/tutorials/faq/#navigation-gestures-on-android-9-and-later

**Comment by simonpoole** [comment]
http://vespucci.io/tutorials/faq/#fullscreen-mode-doesnt-work-properly is probably more applicable in this case as gestures don't seem to be turned on. It should be noted that on the 1st startup on such a device, the app does show a note about full screen mode. 

Historically fullscreen mode has worked well on Samsung devices, however I don't have one with Android 12 available so things may have changed. There are some related issues with detecting if gestures are turned on Android 12 phones that we will need to look at too.

**Comment by simonpoole** [comment]
No response, closing.
