### ISSUE TITLE
Small data styling issue with boundaries – a thick black line instead of a thinner dashed line is displayed

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1620]
## Vespucci Version
17.0.6

## Download source
Google Play Store

## Behaviour/Symptoms
I am not sure if this is a new problem (perhaps a regression?) or if it was always like that ... I was just astonishing since some time, that boundary ways which are tagged with ...

```
admin_level=10
boundary=administrative
```
... and which are also part of one (or more) boundary relations with the same tags are displayed **as thick black lines**.

Tags of the relation – e.g.:

```
admin_level=10
boundary=administrative
type=boundary
name=xyz
ref=xyz
```

Generally speaking: Boundary ways (way segments) **which are parts of boundary relations** (a normal case I think) are shown as a thick black (or nearly black) line instead of a thinner dashed line (except with the style "Color Round Nodes No Multipolygons" – which has no styling for relations). 

Perhaps the special case here is that **both** the way segment AND the relation should have the boundary tag (according to the OSM Wiki which describes the case "boundary=administrative" in Germany – [see the German page here](https://wiki.openstreetmap.org/wiki/DE:Grenze_zeichnen#Schl.C3.BCssel)). A little strange – because normally, only the relation gets the main tags ... But it should be a help for the renderers, I think – but for Vespucci it's a negative "help" at the moment ... What is the opposite of "help"? An obstacle?

## Presumably intended behavior and what happens instead

I think they should be displayed as a dashed line as defined for **ways**:

```
    <feature type="way" tags="boundary" updateWidth="true" widthFactor="0.6" color="ff000000" style="STROKE" cap="BUTT" join="MITER">
    	<dash phase="1.0">
    		<interval length="6.0" />
    		<interval length="2.0" />
    	</dash>
    </feature>
```

But the general style for relations is **also** applied in such a case (like a casing style):

```
 <feature type="relation" updateWidth="true" widthFactor="1.0" color="ff222222" style="STROKE" cap="BUTT" join="MITER" />
```

And this results in a dashed line in color ff000000 (widthFactor="0.6") **underlaid** with a line in color ff222222 and  width 1 – which looks like a thick black line. I could confirm this by defining another colour in the styling for the way ... then it looks like that (here with color ffaf4798 for the dashed way style above):

![boundary-example-300px](https://user-images.githubusercontent.com/48966999/163742364-a848c9eb-8829-4917-854d-e9954ba2ca3f.png)
 
## Expected Behaviour

It should be displayed **as a (thinner) dashed line** – no matter if it's a way only with a boundary tag or a way which is part of a boundary relation, too ("double tagged" with the key "boundary").

## How to recreate
See above.

## Proposal for a solution
Add the same dashed styling for a relation as the styling for a way (under the general style for relations):

```
	<feature type="relation" tags="boundary" updateWidth="true" widthFactor="0.6" color="ff000000" style="STROKE" cap="BUTT" join="MITER">
		<dash phase="1.0">
			<interval length="6.0" />
			<interval length="2.0" />
		</dash>
	</feature>
```

Small glitch of this method:
In some zoom levels of Vespucci it looks like a normal, non-dashed line again – maybe the dashings of the 2 stylings (way + relation style) are not always 100% congruent in every zoom level? (I tried it out with a longer, real boundary line with many nodes.) Perhaps you have a better solution ...

**Comment by simonpoole** [comment]
The better solution would seem to be to suppress the rendering of the boundary relations completely as there will be at least the way and two relations to be rendered and none of them will be in phase in the general case. This will lead to the default rendering for a way if the tags are "only" on the relation, but there is no really good solution.
