### ISSUE TITLE
Strada senza uscita

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1625]
Description:
---

Questa strada da anni é senza uscita solo ad uso dello stabile e chiusa da un cancello.

Device info:
---
<table>
<tr><td>App version</td><td>17.0.6.0</td></tr>
<tr><td>App version code</td><td>2009</td></tr>
<tr><td>Android build version</td><td>f0f57</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QPIS30.28-Q3-28-26-4-1-7</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>doha_n</td></tr>
<tr><td>Device model</td><td>moto g(8) plus</td></tr>
<tr><td>Device product name</td><td>doha_reteu_n</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/ViandanteC"/>ViandanteC</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Should likely have been a map note.
