### ISSUE TITLE
Límites de velocidad

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1632]
Description:
---

Todo el puente de la carretera A-497 entre Huelva y Corrales está limitado a 80km/h en ambos sentidos. El límite que tiene puesto a 100 km/h está obsoleto

Device info:
---
<table>
<tr><td>App version</td><td>17.0.6.0</td></tr>
<tr><td>App version code</td><td>2009</td></tr>
<tr><td>Android build version</td><td>G950FXXUCDUD1</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.G950FXXUCDUD1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dreamlte</td></tr>
<tr><td>Device model</td><td>SM-G950F</td></tr>
<tr><td>Device product name</td><td>dreamlteeea</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/AntonioGRosado"/>AntonioGRosado</A></td></tr>
</table>

**Comment by simonpoole** [comment]
This should have been a note I expect
