### ISSUE TITLE
Unable to comment on notes

### ISSUE THREAD

**Issue by AndrewHain** [MarcusWolschon/osmeditor4android#1649]
## Vespucci Version
17.0.7

## Download source
F-droid

## Device (Manufacturer and Model)
Samsung Galaxy A03

## Android Version 
11

## Behaviour/Symptoms
I cannot add comments to notes because the keyboard obscures the Upload and Save buttons.

## Expected Behaviour
I can add a comment to a note with or without closing it.

## How to recreate
Open a note and add a comment, the keyboard obscures he Upload and Save buttons and cannot be removed without aborting the edit.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
The phone has OneUI Core, version 3.1

**Comment by simonpoole** [comment]
Can you make a screen shot of the situation and attach it here? 

And: are you running in fullscreen mode or not?  If you are, can you check if the issue persists if you force fullscreen mode of?

**Comment by simonpoole** [comment]
Closing as stale (no response to query).
