### ISSUE TITLE
"unknown error" when trying to upload changes

### ISSUE THREAD

**Issue by johndh** [MarcusWolschon/osmeditor4android#1652]
Description:
---
It seems that some nodes were merged, and the app doesn't seem to know what to do (or provide a way to reconcile).
![Screenshot_20220606-150759](https://user-images.githubusercontent.com/692397/172240189-5f830858-7af9-44ff-8be5-cae8ca84e733.png)
![Screenshot_20220606-150744](https://user-images.githubusercontent.com/692397/172240204-e637ece0-8622-46b4-ad4e-deb539dc449e.png)

Device info:
---
<table>
<tr><td>App version</td><td>17.0.7.0</td></tr>
<tr><td>App version code</td><td>2010</td></tr>
<tr><td>Android build version</td><td>89dec</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QZKS30.Q4-40-95-9</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>kiev</td></tr>
<tr><td>Device model</td><td>motorola one 5G ace</td></tr>
<tr><td>Device product name</td><td>kiev_retailu</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
Can ypu save your edits as a .osc file and attach it to the issue (export as osc file). You will need to use .txt as file extension to make github happy.

This looks like a classical edit conflict, that should end with you being asked how you want to reconcile the issue. But that obviously doesn't happen

**Comment by simonpoole** [comment]
Seems as if the nodes were deleted 5 days in https://www.openstreetmap.org/changeset/121807705#map=18/35.72833/-86.93053

With other words the data you were editing seems to have been stale.

Once you have saved you edits as described above, you could try the 'Update data" function, no guarantees but that might directly resolve the issue.

**Comment by simonpoole** [comment]
We did not handle this specific upload conflict it seems, fixing this. 

`Precondition failed: Way 1061790062 requires the nodes with id in 9754977034,9754977041,9754977064, which either do not exist, or are not visible.`

**Comment by johndh** [comment]
> Can ypu save your edits as a .osc file and attach it to the issue (export as osc file). You will need to use .txt as file extension to make github happy.
[changes_060622.txt](https://github.com/MarcusWolschon/osmeditor4android/files/8849147/changes_060622.txt)

**Comment by simonpoole** [comment]
I've removed the reference to the way in question from the attached OSC file. You should now be able to download the area in question, apply the file and upload. Naturally because the data the edits were based on are rather old this might still have problems that we don't know of yet (the OSM API aborts after the first conflict). If you don't want to do this on your mobile you can load OSC files in JOSM which has the advantage of more sophisticated conflict handling.

[changes_060622_modified.txt](https://github.com/MarcusWolschon/osmeditor4android/files/8850878/changes_060622_modified.txt)
