### ISSUE TITLE
Missing submit button of Accepted material dialog

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#1657]
Description:
---
1. Create a new node
2. Select recycling container preset
3. Open recycled materials
4. Unable to save selected values - there's no button

![Screenshot_20220610-153254_Vespucci](https://user-images.githubusercontent.com/11516259/173077689-97d4f1ac-9394-45e9-9676-34b2737d5d68.png)

Device info:
---
<table>
<tr><td>App version</td><td>17.0.7.0</td></tr>
<tr><td>App version code</td><td>2010</td></tr>
<tr><td>Android build version</td><td>A405FNXXU4CVD1</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RP1A.200720.012.A405FNXXU4CVD1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a40</td></tr>
<tr><td>Device model</td><td>SM-A405FN</td></tr>
<tr><td>Device product name</td><td>a40eea</td></tr>
<tr><td>Device hardware name</td><td>exynos7904</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

osm user: kudlav

**Comment by simonpoole** [comment]
Interesting, do you have full screen mode turned on? If yes, try forcing it off.

**Comment by kudlav** [comment]
Hi, I'm not using full screen mode.

The occurs only when opened keyboard before opening the dialog, see the screenshot. There's still keyboard opened. This is because I search for presets.

**Comment by simonpoole** [comment]
When I so this the dialog opens over the keyboard. Are you using the standard samsung keyboard?

**Comment by kudlav** [comment]
Hi, yes, the dialog is opened over the keyboard, just the buttons are missing.
I'm using Gboard 11.7 by Google.

**Comment by kudlav** [comment]
Same problem with Samsung keyboard 5.3

**Comment by simonpoole** [comment]
My daughter has an A40, I'll see if I can determine what is causing the issue on it.

**Comment by simonpoole** [comment]
I wasn't able to recreate the issue on my daughters A40. One possible difference  is the theme, or maybe accessibility settings. Have you tested with the default light theme?

**Comment by kudlav** [comment]
Same with the default light theme.

**Comment by simonpoole** [comment]
I missed asking one thing: what navigation bar setting (for your whole device not for Vespucci) have you set? Gestures or the virtual buttons? As said maybe it is an accessibility setting, in particular font size or other magnification setting, though in testing I didn't notice any effect.

**Comment by kudlav** [comment]
Hi,
I have switched navigation bar from swipe gestures (+ show button to hide
keyboard) to buttons. And it's ok, so it's triggered by the following
settings:

**Comment by kudlav** [comment]
![Screenshot_20220611-110513_Settings](https://user-images.githubusercontent.com/11516259/173199516-5be76b6e-e20b-4c7b-845d-1c491ff074eb.png)

**Comment by simonpoole** [comment]
Could you try with "Show button to hide keyboard" disabled?

**Comment by kudlav** [comment]
When disabled "Show button to hide keyboard" buttons are correctly there.
Turning it on again broke it. So this is the trick. 🤔

**Comment by simonpoole** [comment]
Interesting enough switching this on and off does not change the behaviour on my daughters phone. I suppose the extra dimension we've not explored is if this is locale/language dependent as that is different on her phone.

**Comment by kudlav** [comment]
I'm using my phone and the app in Czech, but for purpose of taking screenshots I switch my phone into English (UK).

Without hide button:
![Screenshot_20220613-100328_Vespucci](https://user-images.githubusercontent.com/11516259/173308977-8e44ce37-4f2a-472b-9ebd-edfb99a6cee8.png)

With hide button:
![Screenshot_20220613-100113_Vespucci](https://user-images.githubusercontent.com/11516259/173309011-3ffb39b3-c006-4e4a-a781-735ce245a65f.png)

**Comment by simonpoole** [comment]
OK, so the effect is likely locale independent.

**Comment by simonpoole** [comment]
Closing as there is nothing we can reasonably do about this.
