### ISSUE TITLE
Wie kann man die Knoten-ID ermitteln

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1658]
Description:
---

In Openstreetmap kann ich mir die Konten-ID (zum Beispiel: 268594090) anzeigen lassen. Wie kann ich diese ID in Vespucci ermitteln?

Device info:
---
<table>
<tr><td>App version</td><td>17.1.1.0</td></tr>
<tr><td>App version code</td><td>2102</td></tr>
<tr><td>Android build version</td><td>8643238</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>32</td></tr>
<tr><td>Android build ID</td><td>SQ3A.220605.009.A1</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>coral</td></tr>
<tr><td>Device model</td><td>Pixel 4 XL</td></tr>
<tr><td>Device product name</td><td>coral</td></tr>
<tr><td>Device hardware name</td><td>coral</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/OpenGreenStreet"/>OpenGreenStreet</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Für alle Elemente gilt sieht man das wenn man nach dem Auswählen des Elementes auf "Info" im Menu auswählt, siehe auch http://vespucci.io/help/en/Node%20selected/#actions (auch in der Hilfe auf dem Gerät).

**Comment by OpenGreenStreet** [comment]
@simonpoole: vielen Dank für die prompte Rückmeldung!
