### ISSUE TITLE
Schlüssel: "wikimedia_commons" wird nicht mehr angeboten?

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1659]
Description:
---

Kann es sein, dass der Schlüssel "wikimedia_commons" nicht mehr unter "Details" angeboten wird?
Ich bilde mir ein, dass die Schlüssel bei jedem Objekt angeboten wurde und jetzt nicht mehr oder gehört er nur zu bestimmten Objekttypen?

Device info:
---
<table>
<tr><td>App version</td><td>17.1.1.0</td></tr>
<tr><td>App version code</td><td>2102</td></tr>
<tr><td>Android build version</td><td>8643238</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>32</td></tr>
<tr><td>Android build ID</td><td>SQ3A.220605.009.A1</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>coral</td></tr>
<tr><td>Device model</td><td>Pixel 4 XL</td></tr>
<tr><td>Device product name</td><td>coral</td></tr>
<tr><td>Device hardware name</td><td>coral</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/OpenGreenStreet"/>OpenGreenStreet</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Nein, wir haben noch nie wikimedia_commons angeboten,

Ich würde vorschlagen in https://github.com/simonpoole/beautified-JOSM-preset (dort gehört der issue so oder so hin), ein Issue aufzumachen mit den Presets bei denen es Sinn machen würde (oder gerade ein entsprechenden Pull Request).
