### ISSUE TITLE
Edit Ski Pistes

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1667]
Description:
---

Hello,
how could I edit/correct Ski Pistes with Vespucci?

Best Regards,
.kai  

Device info:
---
<table>
<tr><td>App version</td><td>17.1.1.0</td></tr>
<tr><td>App version code</td><td>2102</td></tr>
<tr><td>Android build version</td><td>A528BXXS1CVF1</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.A528BXXS1CVF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a52sxq</td></tr>
<tr><td>Device model</td><td>SM-A528B</td></tr>
<tr><td>Device product name</td><td>a52sxqeea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/kaijen"/>kaijen</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Hi, do you have an example of what you want to edit? You can add/remove members from "piste" route relations (though currently that is missing for the "Create route" function), and tag individual ways. 

See https://wiki.openstreetmap.org/wiki/Tag:route%3Dpiste

**Comment by kaijen** [comment]
I seem to be blind. I can see pists as an opensnowmap overlay map. But I don't get the actual piste data from OSM. I'll create some screenshots.

**Comment by simonpoole** [comment]
OK :-) The user issue would still interest though.
