### ISSUE TITLE
Relation Data

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1670]
Description:
---

After a while, the relation data cache is overfull, that means that trying to add a relation to a hiking route is quite impossible, because there are too many relations in the cache.
Possible solutions:

- [ ] 1.(preferred): add a method to clean the relation cache without loosing total presets
- [ ] 2.(additional): sort relations by alphabet (and/or category)

Best regards, Vespucci is my favourite tool for adding open street map details

Klaus Grüger 

Device info:
---
<table>
<tr><td>App version</td><td>17.1.1.0</td></tr>
<tr><td>App version code</td><td>2102</td></tr>
<tr><td>Android build version</td><td>V12.5.7.0.RGGEUXM</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RP1A.200720.011</td></tr>
<tr><td>Device brand</td><td>Redmi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>begonia</td></tr>
<tr><td>Device model</td><td>Redmi Note 8 Pro</td></tr>
<tr><td>Device product name</td><td>begonia_eea</td></tr>
<tr><td>Device hardware name</td><td>mt6785</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/KlausG"/>KlausG</A></td></tr>
</table>

**Comment by simonpoole** [comment]
There is no relation cache as such, a screen shot might help. 

Pruning the data (layer control -> data layer -> menu) will remove unmodified relations (and other data) from memory, this happens automatically when auto download is enabled.

**Comment by simonpoole** [comment]
Stale (no response after OSM message)
