### ISSUE TITLE
Data styling confusion with indoor=room plus shop or amenity or other tags

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1673]
## Vespucci Version
17.1.1

## Download source
google play store

## Used data style and preset
- Data style: "Color Round Nodes"
- Presets: Default or Simonpooles Beautified Presets v4.3.0

## Behaviour/Symptoms

With the Style "Color Round Nodes" closed ways with `indoor=room` are displayed as a filled area (color="99f2c791" which is a light orange or beige). This is fine (although I defined my own style with a transparency of 66 instead of the opaque 99, but that just by the way).

What confuses me is the inconsistent rendering of indoor closed ways and the different icon display:

1. The combination of the tags `indoor=room + amenity=cafe` results in a **dashed black line**  (= standard styling of amenity ways) **with the cafe icon** – presupposed a name and opening_hours is also given and the validator does not show a thick pink outline. In the property editor, there is a double item match of the items "Cafe" and "Room" – and "Cafe" seems to be the first priority (it is displayed first in the "Properties" tab).
2. The combination of the tags `indoor=room + shop=clothes` results in a **black line** (= standard styling of shop ways = default stroke style) **with the indoor=room icon** (no matter if name/opening_hours are missing or not). In the property editor, there is a double item match of the items "Room" and "Clothes" – and here "Room" seems to be the first priority (it is displayed first in the "Properties" tab).

(Note: both amenity and shop closed ways are styled with `iconPath="preset"` in "Color Round Nodes".)

And as a side effect of case 2:

If the clothes shop has a missing name or opening_hours are missing, the Vespucci validator for missing tags fails – I mean it does not work, there is no thick pink outline!

I basically understand what is happening and why you see a cafe icon in case 1 and a room icon (indoor_room.png) in case 2 (which is not displayed normally because the indoor styles don't have a `iconPath="preset"`): in the data styling, the amenity and shop styles for closed ways come first, the indoor styles at the very end – so the amenity and shop styles are applied; both have `iconPath="preset"` – and the icon of the item with a higher priority is displayed.)

But I have several questions here:

1. What is the reason for this different prioritization of the amenity and shop key in combination with `indoor=room` (which leads to a different icon display at the end)?
2. Is there an easy way to influence this prioritization? (I tried several things, including using the new "object" attribute for the indoor=room item instead of listing it under "object_keys" or changing the order of the items, but nothing helped.)
3. Is the alphabetical order of the keys of any importance here (amenity – indoor – shop)? Because I also tried tags with craft, emergency, tourism instead of amenity and shop and there seemed to be a correlation, but I wasn't sure.
4. Could the validator also work with "second level" matching items in general (because this can also happen with other "double item matches")? An example: I had this case with a building which was tagged by someone with`building=industrial + shop=paint` and missing opening_hours – because`building=industrial` has a higher matching priority as `shop=paint`. The result: **No pink validator rendering!** If you change it to` building=yes` (= not a fixed key matching, therefore lower priority as `shop=paint`), the validator works ...

And I have these suggestions:

- I would move the styling for the indoor tags **before** the styles for amenity and shop. And I would add `iconPath="preset"` and `labelKey="name"` for all indoor styles. The result would be, that also closed ways with` indoor=room `+ amenity or shop tags (or other main tags) would be rendered as filled areas with the indoor color and not with a black or black dashed outline. => Consistent indoor room rendering with useful icons.
- If the matching priority problem could be solved in any way, the icons for shops or amenity would be displayed, or the indoor icon, if there is no amenity/shop tag (or other tags like craft, office ...) – which is also helpful IMO.
- And I would reduce the transparency for the indoor fill colors from 99 to e.g. 66 (useful if you have a layer like Bing activated below.)

## Expected Behaviour
- Consistent rendering of all indoor closed ways
- Display of shop/amenity/craft/office ... icons as with closed ways of buildings

## How to recreate
Draw 5 closed ways:
1.  with `indoor=room`
2. with `indoor=room + amenity=cafe`
3. with `indoor=room + amenity=cafe + name=xyz + opening_hours=24/7`
4. with`indoor=room + shop=clothes`
5. with `indoor=room + shop=clothes + name=xyz + opening_hours=24/7`

And see the rendering results (and the function/failing of the validator).

## My workaround

Just for the sake of completeness: I wanted to get rid of this problem (specially the different icons) and the only way I found – beside changing the data styling as described above – was to add a `level` key with `match=key` to every shop item (normally it has match="none"), then it gets a higher matching priotrity than the indoor=room item, because every indoor=room closed way normally has a level tag … but it's really only a bad workaround for this single case and this combination of tags ... A general solution would be fine.

**Comment by simonpoole** [comment]
This is currently expected behaviour. The matching algorithm determines the best preset by scoring based on the matching tags, and if the score is the same for both presets (in the two simple cases one matching fixed tag each) then the outcome (that is which preset will be used for rendering) is essentially up to chance. 

This is always an issue, for example for building outlines with additional objects tagged on them, there special behaviour is hardwired, we could do something for indoor=room, but it needs some thought.
