### ISSUE TITLE
Aufgezeichnete GPS Tracks exportieren / speichern?

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1696]
Description:
---

Bei der Vespucci v17.1.4.0 fehlt der Menüpunkt GPX-Track speichern oder exportieren. Bei früheren Versionen konnte man Track noch exportieren.

Schade die Funktion zum Track aufzuzeichnen ist so nicht mehr verwendbar, wenn man den Track als Fatei bräuchte.

Gruß
Jakob48

Device info:
---
<table>
<tr><td>App version</td><td>17.1.4.0</td></tr>
<tr><td>App version code</td><td>2105</td></tr>
<tr><td>Android build version</td><td>G390FXXS6CTI2</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.G390FXXS6CTI2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>xcover4lte</td></tr>
<tr><td>Device model</td><td>SM-G390F</td></tr>
<tr><td>Device product name</td><td>xcover4ltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7570</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Jakob48"/>Jakob48</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Siehe http://vespucci.io/help/en/17.1.0%20Release%20notes/#improved-gpx-layer-support und http://vespucci.io/help/en/Main%20map%20display/#layer-control beides auch auf dem Gerät und beim ersten Starten nach dem Update angezeigt.
