### ISSUE TITLE
App becoming unresponsive while downloading from osm

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1699]
## Vespucci Version
17.1.4

## Download source
Play Store, I guess

## Device (Manufacturer and Model)
Fairphone 4

## Android Version 
11

## Behaviour/Symptoms
When I try to download data from the OSM server, the app freezes after about one minute 

## Expected Behaviour
If the download fails, the app should give an error message.

## How to recreate
Navigate to an area and download current view

## Crash dump submitted (no or yes + date)
2022-07-15 7:35 CEST

**Comment by Discostu36** [comment]
The problem disappeared after I deleted and re-downloaded map data. But still, in such cases the app should not crash.

**Comment by Discostu36** [comment]
I tried to download a rather small area around https://www.openstreetmap.org/way/984489869,  maybe about this size:

![Screenshot_20220715-113533.png](https://user-images.githubusercontent.com/30999326/179197423-5d335281-2424-42ee-add6-3ae6252b137a.png)

**Comment by simonpoole** [comment]
Further question "unresponsive" was an ANR or how else did it manifest itself?

**Comment by Discostu36** [comment]
If this is an ANR then it was an ANR ![Screenshot_20220715-072953_1.png](https://user-images.githubusercontent.com/30999326/179225886-c6fb53b5-992e-42f8-8df3-902458019b64.png)

**Comment by simonpoole** [comment]
Yes that's an ANR, did you wait or did you abort?

**Comment by simonpoole** [comment]
The problem is that google has no record of the ANR which would have given at least a hint of what was causing the issue. So right now there's not really anything further I can do.

**Comment by Discostu36** [comment]
Ok, next time I'll hit the report button when an ANR happens

**Comment by Discostu36** [comment]
A few minutes ago I had the problem again and sent the report this time.

**Comment by simonpoole** [comment]
Sorry the response has taken so long, google didn't show an ANR that I could associate with your device at the time, if it happens again could you report it again (and give a heads up here). 

My only suspicion right now is that there may be an issue with one of the relations in the vicinity there and that is causing an issue with merging (which would be consistent with the problem going away when you remove the existing data), obviously is you are seeing the issue elsewhere then that can't really be the cause.

**Comment by Discostu36** [comment]
The problem hasn't happened since, but I will do if it does.

**Comment by simonpoole** [comment]
Closing as stale.
