### ISSUE TITLE
When splitting a way, ask which part should keep history

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1700]
At the moment, when I am splitting a way, the app decides automatically which way will inherit the id and history of the original way and which one will be created as new. This might lead to undesired results. 

For example, I just wanted to split a way and delete one of the two parts. Vespucci decided to give the original data to the part of the way that I wanted to delete. If I had continued, the history of the way would now be gone. 

Vespucci should instead ask which part of the way should inherit the data. I think JOSM does that already. If it is considered to be too complicated for novice users, it could also be made an optional feature.

**Comment by simonpoole** [comment]
We don't really "decide" anything, the first part of the way (aka the nodes up to the node that is the split location) has nodes removed, and the 2nd part is used for the new way. Offering a choice is fairly complex for a number of reasons. Currently reversing the way will serve as a workaround.

**Comment by Discostu36** [comment]
**Alternative suggestion:**

Maybe the app should start "deciding" and give the history to the longer part of the way because this will be the desired choice in the majority of cases. This would improve the situation without the user even noticing. Of course, it is still more complex than the current system, but perhaps the "number of reasons" would be lower 😉
