### ISSUE TITLE
Crash when editing and closing POI

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1701]
## Vespucci Version
17.1.4

## Download source
Google Play Store

## Device (Manufacturer and Model)
Fairphone 4

## Android Version 
11

## Behaviour/Symptoms
I edited an POI and then closed it. The app crashed and gave me the oppertunity to send a report and I did. Before the crash I edited contact information, operator and opening hours. Just before closing I wondered about an empty contact:facebook field but don't know if this is part of the problem. 

## Expected Behaviour
App should not crash

## How to recreate
Not sure

## Crash dump submitted (no or yes + date)
Yes, 2022-07-25 13:03 CEST

**Comment by simonpoole** [comment]
The issue was fixed this morning, see https://github.com/MarcusWolschon/osmeditor4android/releases/tag/17.1.5.0
