### ISSUE TITLE
State file names can be too long (was Loading GPX causes errors when using the app)

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#1703]
Description:
---
1. load gpx
2. open tag editor
3. crash report occurs every time the tag editor is opened or on any other action that brings map into background

Reported today, multiple time.

Device info:
---
<table>
<tr><td>App version</td><td>17.1.4.0</td></tr>
<tr><td>App version code</td><td>2105</td></tr>
<tr><td>Android build version</td><td>A405FNXXU4CVF1</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RP1A.200720.012.A405FNXXU4CVF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a40</td></tr>
<tr><td>Device model</td><td>SM-A405FN</td></tr>
<tr><td>Device product name</td><td>a40eea</td></tr>
<tr><td>Device hardware name</td><td>exynos7904</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
The issue is due to the file name for the state file, which is derived from the original, being too long:

    java.io.FileNotFoundException: /data/user/0/de.blau.android/files/-document-content%3A%2F%2Fcom.microsoft.skydrive.content.metadata%2FDrive%2FRID%2Fvladankudlac%2540gmail.com%2FItem%2FRID%2F41499EFB497F3A8D%252175784%2FProperty%2F%3FRefreshOption%3DAutoRefresh%26RefreshTimeOut%3D15000%26CostAttributionKey%3D11-21-1.res.1658008459324: open failed: ENAMETOOLONG (File name too long)

**Comment by simonpoole** [comment]
What is actually too long is the name for the copy of the existing file that we make when saving so we can rollback if anything goes wrong.

**Comment by simonpoole** [comment]
As the fix is not backwards compatible, this will get deployed with version 18, which is a month or 2 away. The current workaround would be to move the files to the device itself before loading.
