### ISSUE TITLE
Handle <error> elements in OSM XML input

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#1705]
In some circumstances the OSM API 0.6 will return, even though the return code indicates a sucessful request, `<error></error>` elements  inline in the response. While this is totally undocumented, it is expected behaviour when there are server side issues, see https://github.com/zerebubuth/openstreetmap-cgimap/issues/276

https://master.apis.dev.openstreetmap.org/api/0.6/changeset/240891/download

```
<osmChange version="0.6" generator="CGImap 0.8.7 (2465271 errol.openstreetmap.org)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
<error>Mismatch in tags key and value size</error>
</osmChange>
```

https://master.apis.dev.openstreetmap.org/api/0.6/ways?ways=4305913777,4305913753

```
<osm version="0.6" generator="CGImap 0.8.7 (2465342 errol.openstreetmap.org)" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
<error>Mismatch in tags key and value size</error>
</osm>
```

While parsing such input will cause, as expected, a parse error and should be harmless, it would be nice to provide an error message that makes it clear what is going on.

**Comment by mmd-osm** [comment]
By the way, `<error>` has been around since at least 2010: https://github.com/zerebubuth/openstreetmap-cgimap/blame/master/src/xml_writer.cpp#L184

No idea why it hasn't been documented back then.

**Comment by simonpoole** [comment]
In any case I did add a sentence on it to the wiki yesterday.

**Comment by mmd-osm** [comment]
Ok, I guess I need to add some more explanation why this approach is needed, and of course an example for JSON output.
