### ISSUE TITLE
Unconnected ways check is too greedy, many false positives

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1712]
Description:
---

@matkoniecz - will attach screenshot

Device info:
---
<table>
<tr><td>App version</td><td>17.1.5.0</td></tr>
<tr><td>App version code</td><td>2106</td></tr>
<tr><td>Android build version</td><td>V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.191002.002.V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Mateusz Konieczny"/>Mateusz Konieczny</A></td></tr>
</table>

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/?mlat=50.07934&mlon=19.92098#map=19/50.07934/19.92098

![ttttt](https://user-images.githubusercontent.com/899988/182612796-4611d316-cc46-435b-bae3-e536b041b02b.png)

**Comment by simonpoole** [comment]
What do you have the tolerance setting http://vespucci.io/help/en/Preferences/#validator-settings ? The default is 2 meters, your screenshot would indicate that you have it set to 10 or more.

**Comment by matkoniecz** [comment]
2 meters, but things fixed itself when I set it to 3 meters, when I set it back to 2 meters everything was fine

close as "matkoniecz phone is doing weird things" again?

**Comment by simonpoole** [comment]
Probably just a different default setting from an old beta or so.
