### ISSUE TITLE
Can't download data (Netguard issue)

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1718]
## Vespucci Version
17.1.5

## Download source
Google Play

## Device (Manufacturer and Model)
Fairphone 4

## Android Version 
11

## Behaviour/Symptoms
Sometimes the app doesn't let me download data. 
![Screenshot_20220809-171632.png](https://user-images.githubusercontent.com/30999326/183690037-e09a098f-d04b-4806-bc33-68eab43f0b6b.png)

Debug screen says "network enabled false" but I have a working 5G connection (I write this issue with it)

## Expected Behaviour
Download should work

## How to recreate
Not sure

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
- I am near but not connected to my WiFi
- I use NetGuard but it doesn't block anything Vespucci related

**Comment by Discostu36** [comment]
Deactivating and reactivating NetGuard fixed it. Not sure if this is a Vespucci issue or a NetGuard issue.

**Comment by simonpoole** [comment]
We are using an Android service to determine if network connectivity is there or not .... so I would suspect that may be Netguard is changing something in how it behaves.

**Comment by Discostu36** [comment]
- When does this check happen?
- What URL does the check use?

**Comment by simonpoole** [comment]
It doesn't use an URL, the mechanism uses a BroadcastReceiver that receives a broadcast Intent from the system when connectivity changes, this in turn invalidates the menus and during that Vespucci checks the current network status.

**Comment by Discostu36** [comment]
Ok, so Android tells Vespucci that network has changed, Vespucci deactivates download menu and asks Android if there is connectivity, Android says no and... what happens then? Vespucci waits until Android tells it that there is connectivity again?  That there was another network change? Could the problem be that with VPN (NetGuard uses VPN) connectivity can change without a network change?

**Comment by simonpoole** [comment]
> Ok, so Android tells Vespucci that network has changed, Vespucci deactivates download menu and asks Android if there is connectivity, Android says no and... what happens then? 
> Vespucci waits until Android tells it that there is connectivity again? That there was another network change? 

Vespucci doesn't "wait" in that sense, the menu items are activated / deactivated depending on the network status when the menus are rebuilt, this can be triggered by various events, not just by a connectivity change. The connectivity change simply invalidates the menu, which in turn causes it to be rebuilt. 

> Could the problem be that with VPN (NetGuard uses VPN) connectivity can change without a network change?

You'll need to ask the Netguard authors.

**Comment by simonpoole** [comment]
As a test I've had Netguard installed for 9 days and had no issues, however crossing the border to Italy today (and consequently roaming in a different network) led to Netguard inverting my settings and blocking all permitted apps.

With other words everything points to your problem simply being caused by Netguard instability.
