### ISSUE TITLE
Upload track to OSM

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1720]
Description:
---

Where the hell is the option to upload a gpx track to OSM ???

Device info:
---
<table>
<tr><td>App version</td><td>17.1.5.0</td></tr>
<tr><td>App version code</td><td>2106</td></tr>
<tr><td>Android build version</td><td>00WW_4_15O</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>00WW_4_15O</td></tr>
<tr><td>Device brand</td><td>Nokia</td></tr>
<tr><td>Device manufacturer</td><td>HMD Global</td></tr>
<tr><td>Device name</td><td>PL2_sprout</td></tr>
<tr><td>Device model</td><td>Nokia 6.1</td></tr>
<tr><td>Device product name</td><td>Plate2_00WW</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Jvitegem"/>Jvitegem</A></td></tr>
</table>

**Comment by simonpoole** [comment]
See https://vespucci.io/help/en/17.1.0%20Release%20notes/#improved-gpx-layer-support and https://vespucci.io/help/en/Main%20map%20display/#layer-control

As you can have multiple GPX tracjs now, the upload option is now per track in the layer control.
