### ISSUE TITLE
Vespucci:  Nodes/Ways tagged with "location=underground" are not Displayed/Editable

### ISSUE THREAD

**Issue by sainokawara** [MarcusWolschon/osmeditor4android#1725]
I add/edit Infrastructure tagged "location=overground" and "location=underground".  The "location=overground" Displays and is Editable.  Unfortunately, anything tagged "location=underground" doesn't Display so you can't Edit it.  This prevents Vespucci from being an Android tool for adding/editing Pipelines and even some Electrical.

**Comment by simonpoole** [comment]
Vespucci always displays everything except if you have a filter active. There is currently no pipeline specific styling so it visually won't be very nice. But there is no reason you shouldn't be able to edit such elements.

**Comment by sainokawara** [comment]
My problem could very definitely be a "user error".  Why do I only see
the rendered OSM image and nothing that even looks like Nodes/Ways that
I see using any other editor?  And, if I click to "unlock" the display
"darkens" but I still don't see the Nodes/Ways that I am familiar with
using other editors.

Thank you,  Harrison

**Comment by simonpoole** [comment]
As long as you don't have pan and zoom download turned on you need to explicitly download data.

**Comment by sainokawara** [comment]
My "misunderstands":  Got everything working the way I would want.  Now, I just need to CLOSE this "issue" out as "user error".

**Comment by sainokawara** [comment]
Simon,

So simple, thank you!  Do you close the issue or do I have to?  Now, I
have to get rid of all confusing "names" cluttering the screen unless I
want to look at the tags.  I am sorry I missed this step but it didn't
register when I was reading the instructions.

Thank you again, Harrison

**Comment by simonpoole** [comment]
You closed the issue back in August.
