### ISSUE TITLE
Recent backgrounds disappear

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1727]
Description:
---

After updating the program, a problem appeared: now every time you start the program, to select the background layer, you need to select it from the full list of layers.  Previously, it was possible to select it in the context menu of the layer from the last three backgrounds used.  These backgrounds remain in the menu only while you use the program.  If you close it and open it again - the last backgrounds disappear.

Device info:
---
<table>
<tr><td>App version</td><td>18.0.0.1</td></tr>
<tr><td>App version code</td><td>2200</td></tr>
<tr><td>Android build version</td><td>V13.0.12.0.SKFMIXM</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SKQ1.210908.001 test-keys</td></tr>
<tr><td>Device brand</td><td>Redmi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>sweet</td></tr>
<tr><td>Device model</td><td>M2101K6G</td></tr>
<tr><td>Device product name</td><td>sweet_global</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/mike140"/>mike140</A></td></tr>
</table>

**Comment by mic140** [comment]
![IMG_20220823_093249](https://user-images.githubusercontent.com/69987154/186087227-eecb9250-06b5-45b9-aaa6-04237aafc2b8.jpg)

**Comment by simonpoole** [comment]
Seems as if the the MRU image list is not being saved, restore however is called.
