### ISSUE TITLE
Updates to Osmose issues cannot be uploaded

### ISSUE THREAD

**Issue by MMK21Hub** [MarcusWolschon/osmeditor4android#1730]
## Vespucci Version
Vespucci 17.1.6

## Download source
Google Play Store

## Device (Manufacturer and Model)
Motorola Moto G7 Power 

## Android Version 
Android 10 (QPOS30.52-29-7-6)

## Behaviour/Symptoms
The upload appears to fail, with the http response 400 Bad Request.

## Expected Behaviour
The changes would be successfully uploaded to Osmose.

## How to recreate
1. Enable the Tasks layer
2. Select an Osmose issue
3. Change its status
4. Click "Upload"

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
![Screenshot_20220825-131754.png](https://user-images.githubusercontent.com/50421330/186651205-3e46e35a-8f92-481b-9353-fd7e4fe6d3ef.png)

**Comment by simonpoole** [comment]
The OSMOSE V0.2 code in 17.1 hasn't really changed since 15.1 (18.0 has switched to the 0.3 API). So as a 1st guess I would suspect that OSM-FR is having a technical issue. Have you already checked that, else I'll contact them.

**Comment by frodrigo** [comment]
It was an issue while makking a better https support.
It is now fixed.

**Comment by simonpoole** [comment]
Thanks @frodrigo !
