### ISSUE TITLE
Tunnel instead of steps

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#1733]
When extracting a segment, the program offers 3 presets to choose from: bridge, tunnel and steps
![IMG_20220826_144136](https://user-images.githubusercontent.com/69987154/186899931-bbb95f56-59d9-4ac4-888f-5d320a176147.jpg)
App version: 18.0.0.1
App version code: 2200
Android build version: V13.0.12.0.SKFMIXM
Android release version: 12
Android SDK version: 31
Android build ID: SKQ1.210908.001 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sweet
Device model: M2101K6G
Device product name: sweet_global
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

**Comment by simonpoole** [comment]
Thanks for spotting this!
