### ISSUE TITLE
Vespucci seems to occasionally create self-referencing relations

### ISSUE THREAD

**Issue by lonvia** [MarcusWolschon/osmeditor4android#1735]
I've stumbled upon some route relations containing itself, sometimes multiple times. These were created with Vespucci, so this might be a software bug. I can't give details about the edits because I'm not the author but maybe you see a common pattern in the changesets.

Examples:

*  https://www.openstreetmap.org/relation/3998231 (relation members added in version 8)
   Changeset: https://www.openstreetmap.org/changeset/118173424
   Reported Vespucci version: 17.0.3.0
* https://www.openstreetmap.org/relation/362111 (relation members added in version 38)
  Changeset: https://www.openstreetmap.org/changeset/119973066
  Reported Vespucci version: 17.0.5.0
* https://www.openstreetmap.org/relation/13627971
  This one started in version 1 with including relation 12634680 which is likely unintended.
  Then went on to add 12634680 and itself again in version 3.
  Changeset: https://www.openstreetmap.org/changeset/115712672
  Reported Vespucci version: 16.1.2.0

Note that I have fixed the current versions of the relations in the meantime.

**Comment by simonpoole** [comment]
Changeset https://www.openstreetmap.org/changeset/115712672 seems to be the most interesting one as there are no changes to other elements associated with it, in particular no way splitting/merging etc.

So either all relevant geometry changes were undone (and potentially something went wrong during that) and/or the relation was directly edited. However the addition of 12634680 twice was not self-referential in the changeset (ignoring the issue in version 1), so compared to the other two occurrences of the issue it is possible that something else was going on here.

**Comment by simonpoole** [comment]
As a precautionary measure we should filter out the current relation in the property editor for "Add to relation" function in the "Relations" tab. It is very easy to add the current relation, and while that in current versions causes a validation error, those can naturally be ignored.

**Comment by mmd-osm** [comment]
FWIW, the changeset upload would return an HTTP 400 when trying to create a new self-referential relations (Error: "Placeholder Relation not found for reference -1 in relation -1."). That's why you wouldn't find those cases as v1 on the database. 

This restriction obviously doesn't apply to v2 and later versions. The Rails port always handled this case in that way, and CGImap uses the same approach for compatibility reasons.

**Comment by simonpoole** [comment]
After communicating with the mapper in question, it would seem to very likely really have been a manual edit. Closing for now.
