### ISSUE TITLE
Add an ABORT button on the "Loading data into memory" dialogue

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1740]
![Screenshot_20220829-194222_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/187318074-38add0fe-531b-41c6-8696-304318e91c44.jpg)
If this dialogue had an "abort" button, then one wouldn't need to wait for Android's process stopper, if there is any problem such as like the one shown.

**Comment by simonpoole** [comment]
There is typically not an actual problem. Reading in the data is completely asynchronous, and you can simply click the dialog away by clicking outside of the form if for whatever reason you believe that it is mistakenly still being shown. 

If the app is really hanging an abort button or similar won't work in any case. 

Note this in version 18: http://vespucci.io/help/en/18.0.0%20Release%20notes/#improvements-to-app-startup

**Comment by HolgerJeromin** [comment]
Adding "hide" would explain the asynchronous-ity to the user.

**Comment by jidanni** [comment]
All I know is I was using version 18.0.0.1, the only way to get back into the app was to clear all its data.
I suppose that's what happens when somebody has too much data in the app last time upon closing. Anyway it doesn't matter what the reason was... but like you said I guess it  an abort button wouldn't work anyway, even before the Android message appears.
