### ISSUE TITLE
Menu item cut off, even in landscape mode

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1744]
Here the menu item is cut off just to the letter T. Even in landscape mode:
![Screenshot_20220831-132952_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/187742811-4f5c2615-d4d6-4998-8bd7-61179d384466.jpg)
 Version 18.0.0.1

**Comment by simonpoole** [comment]
Two notes:

- the width is currently determined by the behaviour of the stock Android AlertDialog
- Androids RadioGroup doesn't support automatic line wrap, the layout is either entirely horizontal or vertical, switching to vertical would arguably make things worse.
