### ISSUE TITLE
Mitdrehen der Karte

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1751]
Description:
---

Die App ist super, ich hätte aber einen sehr großen Wunsch: Die Karte sollte "mitdrehen".

Ich nutze maps.me, Alpenvereinaktiv und StreetComplete. Diese Apps unterstützen das Mitdrehen (Himmelsrichtung wie Handyausrichtung)

Device info:
---
<table>
<tr><td>App version</td><td>17.1.6.0</td></tr>
<tr><td>App version code</td><td>2107</td></tr>
<tr><td>Android build version</td><td>8819323</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>TP1A.220624.014</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>coral</td></tr>
<tr><td>Device model</td><td>Pixel 4 XL</td></tr>
<tr><td>Device product name</td><td>coral</td></tr>
<tr><td>Device hardware name</td><td>coral</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/OpenGreenStreet"/>OpenGreenStreet</A></td></tr>
</table>

**Comment by simonpoole** [comment]
> Die App ist super, ich hätte aber einen sehr großen Wunsch: Die Karte sollte "mitdrehen".
> 
> Ich nutze maps.me, Alpenvereinaktiv und StreetComplete. Diese Apps unterstützen das Mitdrehen (Himmelsrichtung wie Handyausrichtung)

Dazu gibe es bereits 2 Issues, https://github.com/MarcusWolschon/osmeditor4android/issues/1415 und https://github.com/MarcusWolschon/osmeditor4android/issues/1382 deshalb mach ich dieses zu.

Sowohl Alpenvereinaktiv wie StreetComplete verwenden spezielle Frameworks für die Kartendarstellung die aber für unsere Zwecke (aka voller Editor bei dem man auch Geometrien ändern kann) ungeeignet sind. Es ist natürlich nicht unmöglich solche Funktionalität nachzurüsten, ist aber einerseits mit Aufwand verbunden, grob geschätzt ein Mannmonat, und wird natürlich das ganze auch langsamer machen.

**Comment by OpenGreenStreet** [comment]
Vielen Dank für Deine Rückmeldung. Ich komme auch so klar. Aber schön wäre es . . . :-) Vielleicht irgend wann einmal . . .
