### ISSUE TITLE
Mention etymology of C-mode

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1753]
> C-Mode

> In C-Mode only objects are displayed that have a warning flag set, this makes it easy to spot objects that have specific problems or match configurable checks. If an object is selected and the Property Editor started in C-Mode the best matching preset will automatically be applied.

Perhaps in the above documentation snippet, mention if C-mode stands for check mode. That way  users would have an easier time remembering what it means.

**Comment by simonpoole** [comment]
It is really up to the user to find which interpretation fits best.
