### ISSUE TITLE
Making vast amounts of the map gray..

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1758]
![Screenshot_20220905-223436_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/188535145-b67eebd8-62f9-4c3d-bba8-29194a79c614.jpg)
Allow showing an e.g., orange rectangle around already downloaded areas, instead of making vast amounts of the map gray.

(Perhaps add teeth, or crenulations, on the inside of the rectangle, so one can be sure which side of it they're looking at when zoomed in.)

**Comment by jidanni** [comment]
(Yes there is the preference,
"...Always dim non-downloaded areas
If on the non-downloaded areas will be dimmed when the screen is locked. Default: off." But it seems not to be of much help in this case.)

**Comment by simonpoole** [comment]
The problem with all of these schemes is that if the border is not on the screen there is no visual feedback that the area isn't downloaded, which is the whole point of dimming the non-downloaded areas (not to mention that adding a border obscures things unnecessarily). And yes you shouldn't be editing without downloading.
