### ISSUE TITLE
Give some perspective of where we are in the Preferences menus

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1769]
![Screenshot_20220911-174349_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/189550151-402c900d-18c7-4a2d-8a8d-aeeba23cb936.jpg)
Here we are at a third level deep menu in the preferences. But from the top of the screen it's rather hard to know that we're that far deep. So I think the top of the screen should have some kind of breadcrumb list or directory slashes or something so we can not just be somewhere underwater deep down in the menus and not really have much feel of where we are. It'll only waste one little extra line of space up there on the top of the screen.

So the top of the screen should say Preferences / Advanced (preferences) / User interface..." for this example.

**Comment by jidanni** [comment]
By the way there is this weird TH there on one of those preference screens:
"Adding way nodes
THis mode can be entered via the simple mode Add way action, via a long click otherwise, and via the Append action in way and node selection modes."

**Comment by simonpoole** [comment]
We use googles standard preferences library for all preferences so none-of this would be automatic. Further it would require forcing line-breaks in one form or the other because you wouldn't be able to read any longer text in the first place.
