### ISSUE TITLE
Locked window shortcut

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1773]
Here where I scribbled in red,
![Screenshot_20220913-220049_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/190042908-aa566b75-717b-40ff-b840-91331da0a46b.jpg)![Screenshot_20220913-220129_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/190042929-75812d23-0e57-4f96-921e-87a479b545d6.jpg)might be a good place to add a shortcut button, that takes one straight to the lock screen, without requiring the additional two or three taps to finally arrive there.

**Comment by simonpoole** [comment]
The action mode bar is not particularly customizable which would make this difficult to start with, and it would seem to be confusing from an UI pov.

**Comment by jidanni** [comment]
(I was also thinking of a "Download current region" button  also always being available too so one wouldn't have to leave an edit to climb back to the needed window. But yes maybe that would inject data at the wrong time.)
