### ISSUE TITLE
Progress bar instead of spinner when loading into memory

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1776]
Here a progress bar showing the percentage completed would be much more useful than the spinner.

That way the user could get some idea of any of what's going on instead of assuming that the app is  stuck forever etc.
![Screenshot_20220914-223227_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/190300072-7e67320c-eb11-409b-9db4-91a22fe3e1a2.jpg)

**Comment by jidanni** [comment]
Also show some raw numbers, like: 532/22432.

That way the user could see the problem right away. For instance: "oh no wonder; it was a large number of points that I had to load still." Or, "something's wrong because so few points and it's still not loading."

**Comment by simonpoole** [comment]
This literally isn't possible without counting how many elements are in the state file/download/local file first, which is essentially the same thing as loading the data in to memory.
