### ISSUE TITLE
Also share Openstreetmap links

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1777]
Instead of just sharing Geo links it would be great if the app could also have a way to directly share openstreetmap links, like this other app pictured here:
![Screenshot_20220915-000547_All-In-One Offline Maps.jpg](https://user-images.githubusercontent.com/1230959/190409507-d03d4625-25cf-4dd1-a8f9-8e5a828e07a5.jpg)

**Comment by simonpoole** [comment]
Isn't this already covered via the "Share position" function and then selecting  the "Share on OpenStreetMap" target?

**Comment by jidanni** [comment]
![Screenshot_20220916-023431_Android System.jpg](https://user-images.githubusercontent.com/1230959/190572495-2d923793-dacc-4308-b6e1-3213bb4ef260.jpg)
Wow, indeed it is.

Obscure!!!!
