### ISSUE TITLE
Warn earlier to download data

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1779]
We have hit the big green button with the plus mark on it, and we have chosen "add a way". Here's what the screen now looks like:
![Screenshot_20220917-215623_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/190882392-676efdf4-c563-4d4c-8d0b-07dbc8e15193.jpg)
Now we tap the screen just like it says and it warns...
![Screenshot_20220917-215634_GitHub.jpg](https://user-images.githubusercontent.com/1230959/190882412-a36b4068-6bd9-46d3-9c73-3f17c6c149ca.jpg)

Notice the entire screen has darkened background.

That means anywhere on the entire screen would need a download.. so my point is just have the warning appear earlier,  when we choose "add a way." That way we wouldn't have to  back out after going deeper further in the menus...

**Comment by simonpoole** [comment]
You can pan and zoom after selecting "Add way" so this would seem to be not necessary, further you can download data after you have finished drawing the way, you will simply need to create any connections to other data after the fact.

**Comment by jidanni** [comment]
Okay, I see that sometimes people wouldn't want this,  so I'll close the issue.
