### ISSUE TITLE
Differentiate closed and open ways with different colors

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1780]
Instead of using the same magenta color for closed and open ways, it seems to be a great idea to have a different color when  a way is closed. That way one can instantly see if they haven't closed their way yet.
![Screenshot_20220917-232055_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/190884288-e870b690-7b83-4b1f-8bd5-ba0cb9d47220.jpg)

**Comment by jidanni** [comment]
![Screenshot_20220917-232834_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/190884413-9c0cfda9-17c9-4e1e-9737-9f2d0f552b36.jpg)
Else one has to look really really close, or one has to notice the presets being offered are somewhat slightly different so something must be  wrong... (we haven't closed our way.)

**Comment by simonpoole** [comment]
The magenta color is an validation error indicator (untagged way in this case) and the validation styling currently is only based on the validation code and not on any other attributes, see http://vespucci.io/tutorials/data_styling/#validation-styling

**Comment by jidanni** [comment]
Okay I see that Vespucci has many uses for many different colors. But still I think it would be great if open ways could be distinguished from closed ways.
So the only way left to do this, is by some kind of different texture of the lines.
Well I suppose one could also shade the inside of the line.. well anyway it still would be nice somehow visually distinguish them.

**Comment by simonpoole** [comment]
Because the way is untagged (and also not a member of a relation in a specific role) there is no way the app can determine if the way should be closed or not. There -could- be a validation with its own styling for ways that are expected to be closed and are not but that would require them to be tagged.

**Comment by jidanni** [comment]
(I was thinking to have them look different even if they didn't have any tags at all yet: Just to differentiate closed and open ways.)

**Comment by simonpoole** [comment]
> (I was thinking to have them look different even if they didn't have any tags at all yet: Just to differentiate closed and open ways.

See https://github.com/MarcusWolschon/osmeditor4android/issues/1780#issuecomment-1250709430
