### ISSUE TITLE
Can't scroll website menus

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1781]
I can't find where to report this bug  regarding the Vespucci.IO  website so I'll just report it here:

At the top of the screen there is a blue bar that says Introduction, Editing, Tutorials and Posts, Videos and Screenshot, FAQ, and Privacy.

Okay, click Introduction and the menu drops down  and now and we can see all the way down to the 11.1.0 release notes.

Okay now make the browser full screen. Now we can see all the way down to 10.0.0 release notes.

Now hit control minus several times to make the font smaller and smaller. Now we can finally  see to the bottom where it says previous release notes.

There's no other way to see to the bottom of this menu, there in Chrome on Windows.
Okay now let's restore our window back to regular size and click on Editing. We can see all the way down to Preferences but that's it...

**Comment by simonpoole** [comment]
This is an mkdocs issue likely, but you should detail your browser and screen settings as on a normal size screen the menu is currently visible in full.

**Comment by jidanni** [comment]
(Hmm, well at some point someone is going to use a laptop that just isn't tall enough  for those fixed menus!)
