### ISSUE TITLE
Red keys should be red everywhere

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1782]
Here we see a red item in Element Info: "Reference key is missing."
![Screenshot_20220918-103901_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/190926523-206591da-d3a9-4f96-9e0f-40ccad66453f.jpg)

Okay, but here's an idea: make make the word "Reference" red here too!:

![Screenshot_20220918-103915_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/190926617-d4c3799a-6bfa-4b5e-941b-12482c2a89a3.jpg)

**Comment by simonpoole** [comment]
Closing because https://github.com/MarcusWolschon/osmeditor4android/issues/1782 is essentially the same problem.

**Comment by jidanni** [comment]
[#1996]
