### ISSUE TITLE
OSM elements created with geojson

### ISSUE THREAD

**Issue by GPSOruxMaps** [MarcusWolschon/osmeditor4android#1783]
Creating OSM elements from a .geojson is duplicating the nodes and uploading 2 changesets.

I import a geojson created in OruxMaps (polygon, road,...), I use the "Create OSM Object", I put the TAGS and go up to OSM, as the first answer=
1. Notice that the API rejected the edit
2. Checking my OSM profile I noticed 2 changesets created at the same time.
- The way in a Changeset = Object created successfully.
-  The same way nodes but duplicated in a second Changeset.
Examples=

https://www.openstreetmap.org/changeset/126349483

https://www.openstreetmap.org/changeset/126349485
Two changesets for a highway=track, one with the way and one with the nodes.
I'll leave it open for a couple of days before reverting the Changeset with the nodes.

![Screenshot_20220918-201301](https://user-images.githubusercontent.com/83801073/190936848-3b90c8df-d912-4fe4-bfdb-f3a5a70d24d0.png)
![Screenshot_20220918-201410](https://user-images.githubusercontent.com/83801073/190936850-6add5bb9-82c0-478e-b372-231245c58e33.png)

**Comment by GPSOruxMaps** [comment]
.geojson used in Vespucci for creating highway=path

{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"utctimestamp":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"name":"","description":""},"geometry":{"type":"LineString","coordinates":[[-75.49675673246384,4.980014028269062,2327.38427734375],[-75.49691498279572,4.980091518694157,2326.80126953125],[-75.49701690673828,4.980080830360203,2326.027099609375],[-75.49713760614395,4.980043421190005,2324.552490234375],[-75.4974702000618,4.979973947011139,2317.0810546875],[-75.49750506877899,4.979976619095073,2316.38671875],[-75.49753189086914,4.979989979514602,2316.098876953125],[-75.49754798412323,4.9800113561852815,2316.187744140625],[-75.49756944179535,4.980193057858025,2319.148681640625],[-75.4975962638855,4.980217106605083,2318.797607421875],[-75.49762845039368,4.980230467019712,2318.052734375],[-75.49766600131989,4.980238483268371,2317.0263671875],[-75.49780279397964,4.9802491715997546,2312.871337890625],[-75.4978859424591,4.980283908675575,2310.54833984375],[-75.49793154001236,4.980318645749549,2309.393798828125],[-75.49797713756561,4.980417512796216,2308.90771484375],[-75.49800664186478,4.980444233617093,2308.27685546875],[-75.49804955720901,4.980452249863143,2307.06494140625],[-75.49809247255325,4.980436217370941,2305.40185546875],[-75.4981192946434,4.980401480303174,2304.21875],[-75.49813002347946,4.980353382821706,2303.5751953125],[-75.49811393022537,4.98029459700622,2303.64697265625],[-75.49801468849182,4.980160992860605,2304.7041015625],[-75.49796372652054,4.980043421190005,2304.87939453125],[-75.49796909093857,4.979997995766186,2304.0966796875],[-75.49798518419266,4.979960586591267,2303.247802734375],[-75.49806296825409,4.979843014884842,2300.15771484375],[-75.49808442592621,4.979792245277838,2299.05810546875],[-75.49809247255325,4.979730787327263,2298.32763671875],[-75.49804955720901,4.9795196925837475,2293.59912109375],[-75.49805223941803,4.979479611295672,2292.23193359375],[-75.4980656504631,4.979447546263457,2290.771728515625],[-75.4981005191803,4.979423497488284,2289.114990234375],[-75.49838215112686,4.979356695330365,2280.0888671875]]}}]}

**Comment by simonpoole** [comment]
This doesn't look like a problem specific to GEOJson, but more likely an issue uploading the data (possibly due to a network issue). Did you get the  error message just the first time you tried to upload? Any network connection issues around the time you tried.

Note that there is no way for the app to know if the upload was successful if the response from the API is not received, which is likely what happend, see https://github.com/openstreetmap/openstreetmap-website/issues/2201

**Comment by simonpoole** [comment]
Ping
