### ISSUE TITLE
theater:type=amphi

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1785]
https://wiki.openstreetmap.org/wiki/Tag:theatre:type%3Damphi was very hard to tag. Select a closed way, and  push the theater preset and where it says "Theater Type" we are actually inserting theater genre! And there was only about six genres to choose from. Anyway we have to 100% manually insert theater:type=amphi.

**Comment by simonpoole** [comment]
theatre:type doesn't seem to be a useful tag (and is used on less than 10% of all theatres), the type of facility that a theatre uses for its performances should probably be either recorded in the building or landuse tag.

In any case wrong repo for a preset question, pls open an issue in https://github.com/simonpoole/beautified-JOSM-preset
