### ISSUE TITLE
Add search box to Map Background 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1787]
Map background choices may be overwhelming. Therefore a way to search through them might be helpful:
![Screenshot_20220918-084649_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191090124-ea9cc1ca-c839-42a9-8689-26b94c8e326d.jpg)

**Comment by simonpoole** [comment]
Zooming in to a level that is suitable for editing will reduce the available layers to local and global ones. A search function would only help if you new what the layer was actually called (and if it is a place name you could just as well search for it, and then select the imagery).
