### ISSUE TITLE
Add Open Infrastructure map to map background choices

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1788]
https://openinframap.org/ maps would be useful on the list of Background map choices.

**Comment by simonpoole** [comment]
OpenInfraMap is mapbox vector tile overlay, it is currently not included in ELI because there is no standard way to add MVT layers there. You can naturally add it as a custom layer, see http://vespucci.io/help/en/16.0.0%20Release%20notes/#mapbox-vector-tile-and-styling-support
