### ISSUE TITLE
Enter single mailbox time

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1791]
Here the user had difficulty figuring out how to enter a single mailbox time, 08:00 in the morning. There was no way to stop using ranges and just go to a single time. Sure you might say this is not supposed to be used that way, but that's what happened. In the end the user had to give up and just enter it manually in the details panel.![Screenshot_20220920-083710_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191263360-56bef1d6-a3e0-455f-9159-9f39283105d0.jpg)![Screenshot_20220920-083755_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191263415-eb90a003-8a9b-409b-bbc5-d2915bc7685b.jpg)

**Comment by jidanni** [comment]
https://wiki.openstreetmap.org/wiki/Key:collection_times allows single times, like collection_times=Mo-Fr 08:00 that I ended up entering manually in the details panel.

So perhaps it is a mistake to always expect the range, like https://wiki.openstreetmap.org/wiki/Key:opening_hours .

**Comment by HolgerJeromin** [comment]
"Add time span" / "Time" (I only have the German one here) is what you want.

**Comment by simonpoole** [comment]
The collection_times default  template already is a single time only (single times are a special case of time spans if you want to add one manually, don't blame me that is how the OH specification works).
