### ISSUE TITLE
Bottom row  too claustrophobic

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1794]
Hear the bottom row (below "search online"), although can be scrolled, is still too short to be fully read comfortably.
![Screenshot_20220920-101047_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191280791-8ce160c0-f918-4763-a636-42336d5c3826.jpg)
![Screenshot_20220920-101024_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191280852-c47b4f77-be7a-4966-a1a0-d85bc5cfd6e0.jpg)
Yes different device settings might affect this, but this should be tested so it works on all devices. Otherwise one has to remember the image and then scroll down to see what the words are.

**Comment by jidanni** [comment]
In fact the items below the words "search online" apparently don't have anything to do with searching online. Very confusing!

**Comment by simonpoole** [comment]
> In fact the items below the words "search online" apparently don't have anything to do with searching online. Very confusing!

That is why there is a divider there

**Comment by simonpoole** [comment]
You can simply dismiss (green X) the search results to get the full preset view back. Using maximum accessibility settings will always have some negative layout consequences that can either only be remedied with a lot of work (feel free to organize a grant or two) or not at all.

**Comment by jidanni** [comment]
Indeed the X even has effect when there is no text to the left of it!
