### ISSUE TITLE
Say if we are searching for a preset for a node, versus a way

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1795]
Here there is plenty of white space in the upper left corner, to indicate if we are searching for a preset for a **node**, or a **way**, etc.
![Screenshot_20220920-101047_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191282137-a61368c4-db26-4c7f-a96e-4c3d146a0e4a.jpg)
It's just an extra idea for a little bonus information, feedback to the user. Yes even if he is supposed to remember what he is doing from the previous screen.

**Comment by jidanni** [comment]
So it should say "searching for node preset", or" "searching for way preset, or just "node", or just "way", etc. etc.

**Comment by simonpoole** [comment]
A case could could potentially be made for display of some additional information about the currently edited element, however the action bar is not a suitable place for such information (and there is no easily usable space there) and obviously it should be visible/accessible in all tabs.
