### ISSUE TITLE
Add delete element choice

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1796]
Having an additional choice to delete element here, would save a few steps, even though it could be accomplished in other ways.![Screenshot_20220920-102620_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191284925-48943bba-1046-45fa-a16d-70ae7fa444d1.jpg)

**Comment by simonpoole** [comment]
Adding a further option would reduce the space available for the actual information (and require a custom modal), which considered that you simply need to "GO TO ELEMENT" and select delete to do the same, imho doesn't justify adding this.
