### ISSUE TITLE
Debug info screen improvements

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1797]
![Screenshot_20220920-105415_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191293005-0c1830b5-9ac6-421e-805e-100a1704fd20.jpg)

- This should be tested so the very bottom doesn't get pushed off the screen a little, depending on the user's device settings, like fonts and magnification.
- The first sentence assumes that the user had a crash. But actually in this case all the user did was just curiously push the debug menu item. So maybe put an "if" in front.
- Maybe add separate fields for the user's username, and perhaps optionally email, and GitHub bug hyperlink.

**Comment by simonpoole** [comment]
The modal is what is used for crash dumps and is normally shown automatically, the mechanism can simply be triggered manually by the button in the debug display.
