### ISSUE TITLE
'Add node' lacks snap control

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1803]
After selecting "add node" from the Big Green Plus Button, we see:
![Screenshot_20220920-135509_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191329946-cb3cf63f-e0e3-4e88-a843-e485d04e57d4.jpg)
Here if we push the question mark, we read:
>Add node
>Create a new untagged OSM Node at the tapped position, merging with nearby objects. This is for example useful if you simply want to add a Node to an existing Way.

Okay, but wouldn't it be more flexible for in addition to that "?" there at the bottom, next to it add  the 'snap control' icon, so we can control if we really want it to snap or not!

**Comment by simonpoole** [comment]
Merging a node to another is one click, so there is absolutely no gain relative to the current behaviour.

**Comment by simonpoole** [comment]
The "Add tagged node" function doesn't merge noes, so use that and simply don't add any tags.

**Comment by jidanni** [comment]
(Sure hope all these special differences are documented somewhere.)

**Comment by simonpoole** [comment]
> (Sure hope all these special differences are documented somewhere.)

http://vespucci.io/help/en/Simple%20actions/#in-normal-tag-only-indoor-and-c-mode

**Comment by jidanni** [comment]
That page very much needs a table,
one axis operations: add way, add node, add tagged node etc.
The other axis: forced snap or disabled snap or snap choice.
That would also eliminate the doubt about non-mentioned parts.
