### ISSUE TITLE
"Way selected" help improvement

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1805]
"Way selected" help says:

>Split Split
>Split the selected way. The nodes at the available locations for splitting will have a visible touch area. The "Split" action is only available if the way has more than two nodes. **If the way is closed you will need to select two nodes.**

In which case, please mention that it is the same as:

>Split in to polygons

>Available for closed ways with at least four nodes. Will split the way in to two polygons, sharing the common nodes.

**Comment by simonpoole** [comment]
I'm summary closing all documentation change requests from you as you are creating triple work (that you are not paying me for) by not producing pull requests for them.

**Comment by jidanni** [comment]
I wasn't sure which answer was correct, and I didn't have a laptop.

OK, you must be happy with what I wrote.

So when I get more time on the shared laptop I will do a PR.
