### ISSUE TITLE
Split Way Selected help page into two groups

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1807]
Here looking at the Way Selected help,![Screenshot_20220920-153309_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191348423-2cc84667-a8c3-4fd1-a22e-870700f57091.jpg)

Here the item called Append marks a borderline.

Above it are discussed the choices from the bottom of the screen where we came from.

Below and including it are discussed items from the three dot menu.

So maybe at least add a horizontal line separating the two groups.

**Comment by simonpoole** [comment]
This is based on a misunderstanding items move between being visible as buttons on the bottom bar and the overflow menu dynamically based on available space (there are a small number of items that are forced to the overflow menu, but that is the exception to the rule).

**Comment by jidanni** [comment]
OK but I would hope you could determine this before adding PR mandatory.

**Comment by simonpoole** [comment]
You have created something around 70 issues over the last 14 days in this repo, even spending just 10 minutes per issue triaging them, checking if they are actually an issue, are reasonably implementable etc etc. adds up to to nearly an hour per day. That is without the time required to implement fixes / additions and so on.
