### ISSUE TITLE
Can't see node we are supposed to append to always

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1808]
Here one needs to blow up the screen to finally see the node that we're supposed to append to!!:
![Screenshot_20220920-154112_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191349784-cc65cc39-2153-4c03-b711-d4019b485207.jpg)![Screenshot_20220920-154121_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191349809-6bb978e6-5700-47b0-aa7b-a807a8c40a52.jpg)
Also it should say "pick a node to append to" to avoid the user needing to look in Help.

**Comment by simonpoole** [comment]
There is no guaranteed to work solution to this as there are always two nodes that can be chosen from and they can be arbitrarily far apart.
