### ISSUE TITLE
Add incremental back button to presets page

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1809]
Choose a preset from the presets panel. Then choose another one from the choices offered.

Yes I am talking about touching those big square icons with the pictures on them.

Okay but let's say we aren't happy and we want to go back to the previous page, the first set of presets that we saw. The only way to do this is to hit the cellphone's back button. But that throws us out of the presets completely and back into the map.

Thus we see the presets pages need their very own personal arrow button to just go back one step instead of going back completely.

**Comment by jidanni** [comment]
(No I don't have any time frame for all my wonderful suggestions. I just think that maybe in a few years one day somebody might Implement them.)

**Comment by simonpoole** [comment]
There are already up and top buttons for navigating the preset hierarchy.
