### ISSUE TITLE
Items truncated not folded

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1812]
Here we try to figure out what those two lines differ by. We end up trying landscape mode. But the moment we tap the entry field it's too big to see anything anyway because the keyboard popped up. So next time perhaps the lines could not be chopped off and instead be folded so we can see what they're trying to say.
![Screenshot_20220920-171518_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191366695-ead09934-c232-411b-b945-c1791ec655ad.jpg)![Screenshot_20220920-171557_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191366739-2e06a43f-1456-4683-a641-061bdc88f809.jpg)

![Screenshot_20220920-171632_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191366758-3f680075-694e-44ed-9330-d367e216d6db.jpg)

**Comment by simonpoole** [comment]
The OSM value is the first bit that is displayed, the part after it is just a display value of description, so the values don't actually differ.
