### ISSUE TITLE
Mast preset shown twice

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1813]
![Screenshot_20220920-172335_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191367527-46ac1307-0a19-474a-aa24-bc4abc155327.jpg)

**Comment by simonpoole** [comment]
The top section (different background) displays alternative tagging suggestions and is independent of the MRU display.

**Comment by jidanni** [comment]
Indeed there is a slightly thicker border for the top section.

Wish there were pictures in the docs.
