### ISSUE TITLE
Always have redo

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1822]
>Adding way nodes
>Further actions

>Undo

>Tapping the icon once will undo the last addition of a node

Here indeed there is no redo. So coming from other parts of the app, one would expect a long press on the undo button would bring up the menu, but it doesn't. It just says what the button does: one word: undo. So in fact users will tap on it several times,  longer and shorter, trying to bring up the menu but each time they're actually eating up their edits with no way to redo them. 

So maybe the best thing in all parts of the app would be separate undo / redo buttons. So even if there is no redo available it'll be easily noticeable so one wouldn't press on the undo button hoping to bring up a menu but in fact just chewing up their work each press.

Or, make sure the undo button acts the same no matter what window we're looking at. In another words make sure there's always redo possible with it.

**Comment by simonpoole** [comment]
This used to be possible, but because we now treat adding a way as one operation for the purpose of undo / redo (which is much preferable to the old behaviour) the undo facility when adding way nodes no longer uses the normal undo facility. While theoretically possible to add a redo facility, it would seem to have little to no actual utility. Adding a tip the first time the undo button is used is probably the best compromise.

See also https://github.com/MarcusWolschon/osmeditor4android/issues/1493

**Comment by jidanni** [comment]
Ah, perhaps a long press on this certain button should say, instead of just "Undo", "You have touched a special one way Undo Button, with no Redo capabilities."

**Comment by jidanni** [comment]
![Screenshot_20220923-191443_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/192093627-df9b6369-7015-46f6-8c70-096089cc8644.jpg)
I must tell you about this extremely hazardous undo button here circled in red. If we long press it it says it is a revert key. And indeed a user might have filled in all these fields by hand and then accidentally erased some characters and thinking that it's just like browser control Z key, touches it which will then erase every field that he just filled in. 

There's a simple solution. Replace the icon with the correct icon. The correct icon is the same as commonly seen in browsers for page refresh: 
“⟳” U+27F3 Clockwise Gapped Circle Arrow Unicode Character. Thank you.

**Comment by jidanni** [comment]
Although this should be a separate bug report but, 
![Screenshot_20220924-105906_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/192105452-a4e833b1-9e7f-4ad7-9c89-89af25d41500.jpg)
Here the user has mistakenly entered the 12th member, and he wants to undo back to only have 11 members, and then add different item for the 12th. So he presses the undo button seen here on the bottom left. And it undid something else. And he presses it again. And then it says nothing left to undo.
So in fact this undo button is operating on the previous screen's  level. And not the screen that we are currently operating on! The 12 stays a 12 and we have instead undid something that we had earlier in the day still in the upload queue.
So this particular undo button on the multi-select screen should be simply removed for now. Thank you.

**Comment by jidanni** [comment]
Although this should be a separate bug report but, 
![Screenshot_20220924-105906_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/192105452-a4e833b1-9e7f-4ad7-9c89-89af25d41500.jpg)
Here the user has mistakenly entered the 12th member, and he wants to undo back to only have 11 members, and then add different item for the 12th. So he presses the undo button seen here on the bottom left. And it undid something else. And he presses it again. And then it says nothing left to undo.
So in fact this undo button is operating on the previous screen's  level. And not the screen that we are currently operating on! The 12 stays a 12 and we have instead undid something that we had earlier in the day still in the upload queue.
So this particular undo button on the multi-select screen should be simply removed for now. Thank you.

**Comment by simonpoole** [comment]
Undo undos operations, selecting something isn't an operation (doesn't change the selected objects).
