### ISSUE TITLE
Send debug info screen upon app launch 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1829]
Upon launching the app, the "send debug info" screen appears momentarily, and then the app launches as usual.
It is almost too hard to even see what screen it was, but it just flashes for a moment and then the app launches.
Seems to happen every time I launch the app.

**Comment by simonpoole** [comment]
That would seem to be -very- unlikely behaviour. Maybe you are referring to the crash dump modal?

**Comment by jidanni** [comment]
A screen recording shows:
1. Please wait   ... Loading presets
2. "Vespucci crashed or encontered a serious... Please help by clicking... Any further... Thank you..." CANCEL OK
1. Black screen for one second.
2. And then some more quick loading message and the the app starts normally.

**Comment by simonpoole** [comment]
Stale.

**Comment by jidanni** [comment]
(Well all I know is this message appears every time I start the app.)
