### ISSUE TITLE
Current Position Information screen formatting

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1834]
This may not look good on certain devices:
![Screenshot_20220923-055755_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191937252-df8ac762-7241-4bdd-b4c3-fcddd76d8410.jpg)

**Comment by simonpoole** [comment]
The formatting is due to "Hieght over the ellipsoid" being too wide due to your accessibility settings.
