### ISSUE TITLE
Upload queue inspection not available offline

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1835]
![Screenshot_20220923-063000_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/191942415-dfac1904-d2c6-4bd3-b93f-f4ff4cdfb5f2.jpg)
I just want to mention that the "upload data to osm server" menu item is locked out of, if we are offline. That of course makes sense, except for the unfortunate fact that there's some sub menus inside there allowing us to inspect each item in our upload queue, which we now cannot access offline. However I understand this is not a priority, so I'll just close this report now.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/issues/1612

Note that besides opening issues without doing even a superficial check that the topic already exists (including issues that you opened yourself), you are doing the github equivalent of calling somebody on the phone at 4am and then hanging up after a couple of rings.
