### ISSUE TITLE
GPX-layer wird nicht mehr geladen 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1841]
Description:
---

Vielleicht hat's schon jemand gemeldet:
In der neuen Version für Android kann keine Gpx Datei mehr als Ebene geladen werden.
Herzlichen Dank für die Arbeit an Vespucci, 
Cepesko 

Device info:
---
<table>
<tr><td>App version</td><td>18.0.2.0</td></tr>
<tr><td>App version code</td><td>2203</td></tr>
<tr><td>Android build version</td><td>10.1.0.150C431</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>VOG-L29 10.1.0.150(C431E19R2P5)</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWVOG</td></tr>
<tr><td>Device model</td><td>VOG-L29</td></tr>
<tr><td>Device product name</td><td>VOG-L29EEA</td></tr>
<tr><td>Device hardware name</td><td>kirin980</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/cepesko"/>cepesko</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Tut für mich (und auch die Tests laufen durch), hast ein Beispiel File das nicht tut?

**Comment by simonpoole** [comment]
Auch auf Nachfrage keine Antwort.
