### ISSUE TITLE
Wrong node deleted

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1850]
With the screen locked long press a node, then press Edit Tags, and then just hit the check mark.

Okay, now do the same thing for a different node. 

Okay now in the three dot menu push Delete.

The wrong node is deleted!

![Screenshot_20220926-232305_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/192425201-3b6b7d26-205a-422a-a1e9-3423103b36b6.jpg)
![Screenshot_20220926-232325_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/192425220-a05dbbeb-86d2-4a6f-a3c2-f4ea98d39912.jpg)
![Screenshot_20220926-232356_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/192425227-47a2cd0e-579b-406e-b730-01161f8843e0.jpg)
![Screenshot_20220926-232410_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/192425244-5e946545-a324-4d34-b3fb-58eb8e46c156.jpg)

**Comment by simonpoole** [comment]
The error is the node being selected and deletable in the 1st place.

**Comment by simonpoole** [comment]
The question is which behaviour is preferable

- Editing the tags unlocks the app, and element is selected after the property editor is closed

or

- App remains locked and element isn't selected after the property editor is closed

**Comment by simonpoole** [comment]
Implementing the 1st option.
