### ISSUE TITLE
Wrong exit message

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1853]
Here touching a blank area causes the wrong message to appear at the bottom. Because there's no way to unlock because that button isn't available, the message actually should say to use the arrow at the upper left to exit.
![Screenshot_20220927-061533_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/192500638-b973acfb-d628-482f-b34d-dbd0977f30ea.jpg)

**Comment by simonpoole** [comment]
As pointed out in https://github.com/MarcusWolschon/osmeditor4android/issues/1850 the problem (was) that you can trick the app in to selected status while it was locked.
