### ISSUE TITLE
Pre-opened choice menus on Details panel

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1858]
First let's talk about the color of the little pop-up screen of things to fill in. It shouldn't be the same exact white color as the list that it's partially covering.
![Screenshot_20221001-151733_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193424998-050c1eec-81ea-4950-80d2-bac27df7fac7.jpg)
Maybe instead use a yellow tint.

Next, it shouldn't be pre-opened anyway. Or perhaps there should be a preference if one wants it to be pre-opened or not. 

I mean even after we fill it out the first one, the next choice isn't then automatically pre-opened etc. So the F
first choice should not be automatically pre-opened because we don't necessarily want to fill that out instead we are often choosing  between the many choices that it is covering up. So when the list starts out they should be all closed like this:
![Screenshot_20221001-151738_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193425060-27577f5c-89b6-41e1-8890-f1d096dadb27.jpg)

**Comment by jidanni** [comment]
I'm saying you don't know that we want to fill in Theme  right away, we might want to fill in Maximum Age first. So you really don't know so you shouldn't  "helpfully" open the list for us even before we touch it. Yes we can just touch some other area on the page in the close it. But it's just more work.

No big deal. I'm just banging around with some ideas for this page. Works pretty good as it is. But it could work 5% better.

**Comment by simonpoole** [comment]
This was likely fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/0d12f769a8435d6c4dfdf13ca16360cc7c53e9c1
