### ISSUE TITLE
'Arrange into a circle' not uniform

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1860]
Perhaps just use the iD editor algorithm. Maybe it just takes the centroid of all the notdes, and then makes a circle in a uniform distribution around it.

I have never seen an uneven distribution of points in ID.

Maybe leaving a little lopsidedness is somehow what the user wanted. But in the majority of cases I don't think so. So it should be a uniform distribution around a circle.
![Screenshot_20221002-165651_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193476103-35ed0f2e-20a5-455e-9288-ab62ac220705.jpg)

**Comment by simonpoole** [comment]
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/828
