### ISSUE TITLE
Share Position versus exact point

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1861]
With Share Position we can share a precise marker at a given point.  Except we can't tell where that point is, until we share it!

It is the screen center coordinates, what we can't see where that is, exactly.

So it seems the correct thing would be just to share the map view, not adding a marker.

I. e., remove mlat, mlon from OSM URL.

(Yes, if we want to share exact coordinates, we could do it for a node.)

**Comment by jidanni** [comment]
![Screenshot_20221003-062454_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193555731-8a0b55db-ae03-4f01-93f2-a06e763a977f.jpg)

**Comment by simonpoole** [comment]
Other people wanted something else.
