### ISSUE TITLE
Use different colors to indicate state of x

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1864]
The little X on the middle of the upper right: sometimes hitting it will go back one menu. Sometimes hitting it will not go back any further. All the time it retains its green collar. Well, if somehow the two states could be distinguished by different colors, then we would know that it wouldn't be worth hitting it again because there's no further levels to go back!
Or just use gray, just like browsers do, when there's no more use to hitting the Back key because there's no more places to go back.![Screenshot_20221003-092945_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193591156-8bd1ba14-a5f3-45f8-9b8b-22f43110e6b4.jpg)![Screenshot_20221003-092951_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193591172-820fc4b7-9702-40c0-9aaf-da2a926f763e.jpg)
(This is a little complicated though, because this x also has the function of a erasing characters too.)

**Comment by simonpoole** [comment]
The x removes the search text and any associated search results. It doesn't do anything else.

**Comment by jidanni** [comment]
A second press of the X will go back one menu sometimes.
