### ISSUE TITLE
All of the sudden we are looking at the entire Earth

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1869]
No I cannot reproduce this.

Here is what happened. It happens every few days. Here if I touch Mapbox Satellite,

![Screenshot_20221004-141936_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193896010-0c4cfb8b-ce3e-4826-92ab-bb0f1a5bc914.jpg)

normally I should get this menu:

![Screenshot_20221004-141944_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193896170-d10a4108-007e-4c90-9149-cc4c99da46a6.jpg)

But if I am very unlucky, the next screen I will see is this:
![Screenshot_20221004-141754_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193896275-2da3348d-8d16-42b1-9016-58a31e3dc6a8.jpg)

So I then have to zoom all the way back in again due to some weird bug?

I repeat I cannot reproduce this. It happens every few days.

**Comment by simonpoole** [comment]
You are likely simply hitting the "Zoom to extent" button.

**Comment by simonpoole** [comment]
No response, closing.

**Comment by jidanni** [comment]
Holy smokes,
https://vespucci.io/help/en/Main%20map%20display/#layer-control
so indeed (no icons on help page)
- eyeball is Hide/Show button
- box is Zoom to extent button

So you are indeed right! Any non-carefull finger placing will hit that rectangle, that will zoom out 17 levels!!
