### ISSUE TITLE
Open only for special occasions 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1870]
![Screenshot_20221004-143206_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193897926-3211b20f-b794-4115-a43a-940c887b1715.jpg)
Wish there was a way to say it is only open for special occasions, in the opening hours choice menu.

**Comment by HolgerJeromin** [comment]
You can edit this template yourself
https://vespucci.io/help/en/Opening%20hours/#manage-templates

**Comment by HolgerJeromin** [comment]
Most probably you want to use

> Add modifier/comment
