### ISSUE TITLE
Set sentence capitalization for changeset comment. (was Allow beginning comments with uppercase)

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1872]
![Screenshot_20221004-151208_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/193906208-3e6d4d2c-1e39-4a07-bd96-2a8c90adcd5b.jpg) Here we see my keyboard has been switched to lowercase at the beginning of a comment.

So I have to switch it back to uppercase. Shouldn't proper comments begin with uppercase (and then with the period like as in complete sentences?) Therefore I wish my keyboard wouldn't be automatically switched to lower case. Thank you.

**Comment by simonpoole** [comment]
What does your complaint to do with "allowing" starting a comment with upper case? Nothing? If anything you are actually asking for us to switch to sentence capitalization, instead of doing nothing as we do now.

**Comment by jidanni** [comment]
Something's wrong.
Even though release notes now say
> If latin script is being used, use sentence caps for comment and source field in the upload dialog.

But as you see:
![Screenshot_20221214-061303_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/207620642-d70f21b4-cc40-440e-ad72-464ca5066a19.jpg)

I should see:
![Screenshot_20221214-061312_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/207620764-cc6d47d5-74d7-4575-a75e-a8785a474779.jpg)
