### ISSUE TITLE
A custom style files does not appear in Vespucci on a new device (Android 12 issue?)

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1874]
## Vespucci Version
18.0.2

## Download source
Google Play Store

## Device (Manufacturer and Model)
Samsung A33 G5

## Android Version 
12

## Behaviour/Symptoms
I use a custom style file since quite a long time (and many Vespucci versions), and it always worked fine with Android 9 on my old phone (a Honor 7x). I was using it even before the Vespucci folder was moved to "Download".

Now I got a new phone (Samsung A33 G5 with Android 12; newest system updates are installed) and I can't get it to work anymore. Anything else (custom presets and so on) works fine, but not a custom styling xml. And I did exactly the same as on the old device: I put my style file in the Vespucci folder (in Downloads/Vespucci), it has the correct name syntax (_name_-profile.xml) and a unique _name_ attribute of course. (I haven't changed anything on the xml which works on my old device.)

But it does not appear in Vespucci. I also tried another (very short) file name like "test_2022-10-06-profile.xml" and a new (short) attribute name and tried it out on my old and my new phone – on my old device (the Honor 7x with Android 9) it appears at once (after a Vespucci restart), on the new device: nothing ... Only the 4 internal styles are shown. Very bad – as long as THIS does not work, I cannot really use my new phone ... I use it mainly and daily for Vespucci and I'm very used to my own style file, which includes a lot of personal preferences, special icons and so on ...

I also tried to put it in Android/data/de.blau.android/files/styles/ as it's written on the tutorial page (http://vespucci.io/tutorials/data_styling/). Without success.

Is there anything I could do or try out, or is it perhaps really a problem with Android 12 or a bug?

PLEASE HELP ... I would appreciate any help ... it would be too sad if it wouldn't work.

_By the way: a simple interface for managing styling files (specially to add/remove a styling file and getting information about the file name/storage location and so on) like it exists for preset files would be very welcome. And a support for zip files (for the xml file plus icon PNGs) would be fantastic – like it works with preset zip files. This might also make it possible (I mean easier) to share or publish custom styling files, i.e. make them available to other Vespucci users._

**Comment by simonpoole** [comment]
This seems to be an Android 12 and higher issue, which doesn't allow us to list the contents of directories using File.listFiles in the Download(s) directory (and sub-directories). I'm trying to determine if there is any short term workaround.

**Comment by jajajaneeneenee** [comment]
Thanks a lot for the quick fix! I hope, a new release will come soon. It seems, you are still working on a “Import data style” function (#1876). That's very good ...
