### ISSUE TITLE
Keyboard hide validation note or upload

### ISSUE THREAD

**Issue by Marjolain** [MarcusWolschon/osmeditor4android#1875]
![Screenshot_20221006-085256_Vespucci](https://user-images.githubusercontent.com/30159077/194319940-a3e7302d-cac2-4180-b3b9-8a4cc311e006.png)

## Vespucci Version
18.0.2

## Download source
F-droid

## Device (Manufacturer and Model)
Samsung galaxy S9

## Android Version 
/e/ OS 1.2

## Behaviour/Symptoms
When you upload your modifications, the button for send or validate is hide by the keyboard.
You can go back and upload again, your comment is still there and you can send.
But for a note, if you go back, the note disappear. So you can't send notes.

## Expected Behaviour
A Burton for hide the keyboard or a adaptative windows.

**Comment by simonpoole** [comment]
You Android version should be showing a button to hide the keyboard, this is not untypical of  Android version that don't support fullscreen / immersive mode properly. Disabling full screen mode should provide at the expense of screen real estate, a workaround.

See http://vespucci.io/tutorials/faq/#fullscreen-mode-doesnt-work-properly

**Comment by Marjolain** [comment]
Ok, I force the full screen off, the return button hide the keyboard.
Thanks.

**Comment by Marjolain** [comment]
Maybe I my OS fault but I think not.
I close the issue.

**Comment by simonpoole** [comment]
> Maybe I my OS fault but I think not. I close the issue.

On an S9 with stock Samsung supplied OS the hide button is visible.
