### ISSUE TITLE
Exit Background Alignment Mode after Apply button press

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1879]
Perhaps pressing "Apply (all zoom levels)" here should also get us out of  Align Background Mode immediately, instead of us needing to also press the upper left arrow afterwards.
![Screenshot_20221008-130820_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/194719324-71805ab9-4a5a-433c-b8a7-26214834ca3a.jpg)

**Comment by simonpoole** [comment]
Bad idea and breaks UI behaviour.
