### ISSUE TITLE
Display empty GPX entries or discard them automatically (was Cannot discard mapillary)

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1883]
Description:
---

Hi, once I enabled mapillary, it seems that now I cannot discard it. Also, when I open the app the view is on, even if I have hid it in the previous use.

Device info:
---
<table>
<tr><td>App version</td><td>18.0.2.0</td></tr>
<tr><td>App version code</td><td>2203</td></tr>
<tr><td>Android build version</td><td>V13.0.1.0.SJWEUXM</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SKQ1.211019.001 test-keys</td></tr>
<tr><td>Device brand</td><td>Redmi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>curtana</td></tr>
<tr><td>Device model</td><td>Redmi Note 9S</td></tr>
<tr><td>Device product name</td><td>curtana_eea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/SucreRouge"/>SucreRouge</A></td></tr>
</table>

**Comment by Discostu36** [comment]
Cannot reproduce with same version on Fairphone 4, Android 11.

**Comment by simonpoole** [comment]
Yes I can't recreate this either, I've contacted the user, lets see if they turn up here.

**Comment by sucrerouge123** [comment]
Hey there! 

This issue also happens for me after updating in 18.0.3.

I have enabled Mapillary layer from the menu. Now it is first in the row. I try to discard it and nothing happens, try to move it down then 2nd layer in the row alternates with the 3rd, Mapillary still first. Try to move down, the 3rd now comes up to 2nd place, cause it again alternates with the 2nd (previously 3rd). Trying to move down other layers, strange behavior too.

**Comment by simonpoole** [comment]
@sucrerouge123 That sounds as if the internal database and/or the internal data structure that contains the information on which layers are available and in which position has become corrupted/out of sync (I suspect a duplicate entry).

Can you add the layer information from the Debug screen (overflow menu -> Debug, at the end there is a list of layers) to the issue?

**Comment by sucrerouge123** [comment]
Vespucci 18.0.3
Flavor: current
Target SDK: 31
Maximum avaliable memory 536870912
Total memory used 52825712
Tile Cache MAPNIK usage Size 66846720 of maximum 67108864 #entries 255
Tile Cache MAPILLARYV4 usage Size 8 of maximum 128 #entries 6
State file size 49222 last changed 2022-10-16 14:29:10
Bug state file size 550 last changed 2022-10-16 14:29:10
Relations (current/API): 2/0
Ways (current/API): 127/0
Nodes (current/Waynodes/API): 570/538/0
Available location providers
passive enabled true
network enabled true
fused enabled true
gps enabled true
Display name SucreRouge
Configured layers
GPX 0 GPX true null
IMAGERY 1 IMAGERY true MAPNIK
TASKS 2 TASKS true null
OSMDATA 3 OSMDATA true null
SCALE 4 SCALE true null
MAPILLARY 5 MAPILLARY true null

**Comment by simonpoole** [comment]
Does the list correspond to the layers displayed in the layer control? Best a screen shot. I do note that the GPX layer is in a weird place, but that shouldn't really cause an issue.

**Comment by sucrerouge123** [comment]
![IMG_20221016_180010.jpg](https://user-images.githubusercontent.com/43409115/196042656-7cdf1099-e8a8-4fd2-8404-13295a405e53.jpg)

**Comment by simonpoole** [comment]
Ah that's good, so it is actually an issue with a rogue GPX layer, maybe an incomplete or wrong migration in 17.1.

Could you try starting a GPX track and then check if it gets displayed in the layer selector. If it does, test if discarding the Mapillary layer works now.

**Comment by sucrerouge123** [comment]
Vespucci 18.0.3
Flavor: current
Target SDK: 31
Maximum avaliable memory 536870912
Total memory used 51255632
Tile Cache MAPNIK usage Size 26476544 of maximum 67108864 #entries 101
State file size 49222 last changed 2022-10-16 15:13:17
Bug state file size 550 last changed 2022-10-16 15:13:17
Relations (current/API): 2/0
Ways (current/API): 127/0
Nodes (current/Waynodes/API): 570/538/0
Available location providers
passive enabled true
network enabled true
fused enabled true
gps enabled true
Display name SucreRouge
Configured layers
GPX 0 GPX true null
IMAGERY 1 IMAGERY true MAPNIK
TASKS 2 TASKS true null
OSMDATA 3 OSMDATA true null
SCALE 4 SCALE true null
GPX 5 GPX true GPX recording

https://user-images.githubusercontent.com/43409115/196043417-ffff59ba-1267-43c5-b6c6-773b4bc4eb96.jpg

**Comment by simonpoole** [comment]
> It got discarded

Unluckily the bogus GPX layer at position 0 is still there, so I suspect the issue hasn't been fixed and this will need a workaround/fix in the next maintenance release.

**Comment by sucrerouge123** [comment]
Vespucci 18.0.3
Flavor: current
Target SDK: 31
Maximum avaliable memory 536870912
Total memory used 51653280
Tile Cache MAPNIK usage Size 66846720 of maximum 67108864 #entries 255
Tile Cache MAPILLARYV4 usage Size 1 of maximum 128 #entries 1
State file size 49222 last changed 2022-10-16 15:26:28
Bug state file size 550 last changed 2022-10-16 15:26:28
Relations (current/API): 2/0
Ways (current/API): 127/0
Nodes (current/Waynodes/API): 570/538/0
Available location providers
passive enabled true
network enabled true
fused enabled true
gps enabled true
Configured layers
TASKS 0 TASKS true null
IMAGERY 1 IMAGERY true MAPNIK
SCALE 2 SCALE true null
MAPILLARY 3 MAPILLARY true null
OSMDATA 4 OSMDATA true null

**Comment by simonpoole** [comment]
OK good. I still want to add some protection against this happening so I'll leave the issue open for now.
