### ISSUE TITLE
Loading todos (with multiple lists) does not work like it should (and there is also a crash scenario)

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#1889]
## Vespucci Version
18.0.3

## Download source
Google Play Store

## Device (Manufacturer and Model)
Samsung A33 G5

## Android Version 
12

## Behaviour/Symptoms
I just changed my phone and had to migrate all my Vespucci settings and stuff (custom presets, data styling – AND: todos!).

I like the new todo functionality with separate lists! I was using the default list and 2 custom lists since some time (since it was possible with v18) on my old phone and have already learned to appreciate them. And because I still have much open todos, I need them on the new phone ... So I saved these 3 lists with “Save todos ...“ separately (this is the only way), and everything worked fine.

Then I transferred them to the new phone and loaded them one after the other with ”Load todos ...“ and every time I got a positive response (“File read successful”). So at first glance it looked good ...

But then I had to realize (and didn't immediately understand what had happened, at first I thought everything was fine):
* Only 2 lists were shown instead of 3 (if using “Add to todo list …“ or “Go to nearest to do…“).
* And only the to dos of the last loaded  list were shown on the map and seem to be there …
* Indeed, loading a list seems to empty other list(s) and even delete the last loaded custom list. The result is that at most the default list and one custom list are displayed (if using “Add to todo list …“ or “Go to nearest to do…“), and only the custom list would contain todos in this case. To precise:
  * If I first load the default to do list, then my 2 custom lists, then only the last loaded custom list and the default list are shown (if using “Add to todo list …“ or “Go to nearest to do…“), but only the custom list has entries (to dos are shown on the map and “Go to nearest to do…“ is working). But comments in these todos are lost (see below)!
  * And if I load the default list again after that, the custom list has disappeared and the default list contains its entries.
 
The result:
* I could only transfer 1 of my 3 lists (without comments). Not a very good result ...

And furthermore:
* The todos of the last loaded list, which are shown on the map, and seem to be OK, are not OK. They have lost their comment text, which of course is very important. The todos are pretty much useless in this state ... A todo only shows for example:
   * State Open
   * List default
   * node XY
* I also checked the export files in an editor – there are no comments included (only coordinates, the open/close state and the ID of the object).

### And there is also a crash scenario – not sure if it's related to the loading functionality and its problems (as a side effect?) or a general problem:
* When I first loaded the saved default to do list, then one of my 2 custom lists (as described above – the default list was empty after that), and then selected the command “Go to nearest to do…“ (Default list), then Vespucci was crashing at once! (I also sent 2 crash reports.)

## Expected Behaviour (and functionality)
* It should (must) be possibly to save and reload multiple to do lists, e.g. to be able to transfer them to a new phone.
* The comment text should not be lost when saving/loading (and be included in a saved file).
* An additional command to save/load (or replace) ALL to do lists in one steps (similar to the "Save All Notes..." command) would be very helpful (I am thinking about the situation when having 10 or 20 different to do lists and want to tranfer them to the next phone ...). See also #1890.
* And of course, Vespucci should never crash when using the "Go to nearest todo..." command, whether caused by an empty list (e.g. after a fresh install of Vespuccior if a todo has never been created) - or just in that specific situation with saving/loading todos (?).

## Crash dump submitted (no or yes + date)
yes, 2022-10-20 (and 2022-10-19?)

**Comment by simonpoole** [comment]
Pls do not refer to multiple different issues in one, in this case a feature request and a crash.

**Comment by jajajaneeneenee** [comment]
Pls do no comment things like this. I wrote that I don't know if it's connected and for me, it's connected. It's already work enough to write it (more than 2 hours).

**Comment by simonpoole** [comment]
Crash fixed in https://github.com/MarcusWolschon/osmeditor4android/pull/1893/commits/5fea5cb65c3f6469a97187c05d34f922614d6e7c

Currently the only way to load todos from multiple lists is to manually merge the files.

**Comment by simonpoole** [comment]
Enhancements are listed in https://github.com/MarcusWolschon/osmeditor4android/issues/1890

**Comment by jajajaneeneenee** [comment]
You closed this issue, I don't understand why, because it is not completed.

You only fixed the crash, which wasn't a very important point, only a side effect (that's why I described it at the end!). The most essential point was, that comments are not exported at all. I described that, see above (I hope clear enough). I didn't highlighted that in bold text, because you don't like bold text.

So it is impossible to transfer todos from one phone to another with all the information (that's what I still would like to do!). And the comment is a very important information, it contains the main information (what should be done). I think, the save command is nearly useless in the current state.

And I didn't listed that in #1890, because it's not a feature request in my eyes, it's a basic malfunction of the current saving command “Save todos ...“.

And  manually merging the files is not a solution for this problem ... (I could merge them if it would be the only thing to do for the transferring of the to dos ...).

So please re-open this issue and find some time to fix this malfunction. Thank you in advance ...
