### ISSUE TITLE
MBtiles maps won't open

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#1891]
The program does not open mbtiles maps

https://user-images.githubusercontent.com/69987154/196953277-a6ceeb11-5a7e-4aa0-ac1f-d93af921ca70.mp4

[Sumy.mbtiles](https://drive.google.com/file/d/1JH030U95liljxgmTNhPcC-kZpLoTdEb4/view?usp=sharing) 

App version: 18.0.3.0
App version code: 2204
Android build version: V13.0.12.0.SKFMIXM
Android release version: 12
Android SDK version: 31
Android build ID: SKQ1.210908.001 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sweet
Device model: M2101K6G
Device product name: sweet_global
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

**Comment by mic140** [comment]
I can copy the file to the application folder, but from the application itself I cannot access this file.

**Comment by simonpoole** [comment]
> I can copy the file to the application folder, but from the application itself I cannot access this folder

Yes, that is because the system file picker can't access those directories.

**Comment by mic140** [comment]
In version 18.0.5. Play store still won't open. Unlike F Droid
![Screenshot_2022-11-04-01-34-53-080_de blau android](https://user-images.githubusercontent.com/69987154/199856757-a8ade829-5f42-4262-a0b6-ded530d7f68f.jpg)

**Comment by simonpoole** [comment]
As the information says the fiel is already present in the destination directory, I assume from the F_Droid version. You will need to delete it manually first (the file should be in Vespucci/Imports).

**Comment by mic140** [comment]
Thanks for the tip.  Found the file in the Download/Vespucci/imports folder.  Apparently he was there because of the parallel installed version of Fdroid.  I deleted it and downloaded it in a new way for the version from the Playmarket.  It appeared in the list of custom layers, but it is not in the list of available background maps

**Comment by simonpoole** [comment]
The APKs distributed by google and F-Droid are literally different apps for Android and on Android 12 an later there is no way to access a file owned by other variant.

**Comment by simonpoole** [comment]
> I didn't quite understand your message. Is it possible to open these files on Android 12 in the Play Store version?

Sure, just if there is a copy of the file that was copied by an APK from a different distribution it isn't possible to open it and you need to remove it and "re-import".
