### ISSUE TITLE
"Go to last edit" button doesn't work after uploads

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1892]
The "Go to last edit" button is great. Alas,

1. It is totally undocumented. I can't find it anywhere in the documents.
2. It suffers an  artificial restriction, that after any uploads, the position is thrown away. It's a shame that there's such an artificial restriction, because often we still want to go to that spot even if we have uploaded everything already.

**Comment by simonpoole** [comment]
> 2\. t suffers an  artificial restriction, that after any uploads, the position is thrown away. It's a shame that there's such an artificial restriction, because often we still want to go to that spot even if we have uploaded everything already.

Please don't pontificate on things you don't know anything about, The function literally uses the last edit (from the undo stack) and that is gone once you upload.

**Comment by simonpoole** [comment]
> 1. It is totally undocumented. I can't find it anywhere in the documents.

http://vespucci.io/help/en/14.0.0%20Release%20notes/#miscellaneous
