### ISSUE TITLE
Empty square on Properties page ambiguous

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1899]
Here we see three empty squares:
![Screenshot_20221021-111743_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/197251488-f4e2f5e9-1bbb-4247-b989-267935cd2cf5.jpg)

But here on the Details page we find that they don't all exactly mean the same!!:
![Screenshot_20221021-111756_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/197251638-1113c6fa-2537-47bb-a186-5a0db0886009.jpg)
https://www.openstreetmap.org/way/320634001

**Comment by simonpoole** [comment]
That is because the default (unchecked) state of the checkboxes is different, the whole point is that you don't actually need to know what that is. In any case if anything it is a preset issue and doesn't belong here.
