### ISSUE TITLE
Jump to item from Members list

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1900]
Let's say we are looking at this members list,
![Screenshot_20221021-220645_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/197316619-fdb56aad-60f1-4bee-b026-e88974f2a894.jpg)
And we become very curious about the "railway=platform" item.

Sure, we can get lots of information about its tags detail.

But no matter where we look in the menus, there's still is no way to select and then jump to where the item is on the map!

![Screenshot_20221021-220708_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/197316749-edf38d11-4fe4-4446-9766-6394231f9fb0.jpg)
![Screenshot_20221021-220748_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/197316759-c7bd1b48-f5dd-4dc8-a666-62b2c2a814c7.jpg)

The best we can do is select all 175 items in a multi-select...
![Screenshot_20221021-221901_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/197316851-7e637af4-91ce-4473-9fea-75ef2191d009.jpg)

**Comment by jidanni** [comment]
We try another approach. The Info menu item, operating on the relation. We see a few members yes, but it turns out the only way to get where we want is to go back up to the top and hit that green link to the ID number which takes us to the OSM website.

![Screenshot_20221021-222101_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/197317007-a4898fe9-b4f2-410b-a37c-764493ae0ffc.jpg)
![Screenshot_20221021-222127_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/197317009-3b0a136f-8282-4e2e-9d08-4a184ded4440.jpg)

I'm saying that an  enhancement would be if we didn't have to leave  Vespucci in the first place.

**Comment by simonpoole** [comment]
The 3rd approach would have been to read the release notes http://vespucci.io/help/en/18.0.0%20Release%20notes/#property-editor-changes Terminating or hiding the property editor and displaying the map in single window mode becomes very confusing as there can be a stack of property editors potentially with pending changes so that is currently only available in split window mode.

**Comment by jidanni** [comment]
Currently long pressing items in the members list does nothing. Perhaps it could offer to open the URL of the item on the OSM website.
