### ISSUE TITLE
`Label: GPX Description` is not honored in the GPX layer settings

### ISSUE THREAD

**Issue by opk12** [MarcusWolschon/osmeditor4android#1901]
The `<desc>` of the GPX waypoint should appear if `GPX Description` is chosen in the layer style settings.

Example steps:
- In the top-right hamburger menu, click `Add layer from GPX file`.
- Choose the example file below.
- Set `Label`: `GPX Description` and press Ok.
- The desc does not appear (even at a very high zoom).

Example GPX:

`<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1"><wpt lat="48.84732235851925" lon="2.3633668527374425"><name>341</name><desc>Text of a note</desc></wpt></gpx>`

This is Vespucci 18.0.2 from F-droid.

![vespucci2](https://user-images.githubusercontent.com/40740650/197350742-f166f67d-a279-485e-8fa3-4bda60e0ddd3.png)

**Comment by simonpoole** [comment]
This would seem to be simply a typo in the waypoint parser.

**Comment by opk12** [comment]
I confirm that it is fixed, thank you.
