### ISSUE TITLE
Show GPX `<desc>` in the waypoint details dialog

### ISSUE THREAD

**Issue by opk12** [MarcusWolschon/osmeditor4android#1902]
Add a layer from GPX file. Click a waypoint to open the details form. The details include the name, but not the `<desc>`. The GPX spec says that `<desc>` has the human-readable description and my GPX editor works this way.

![vespucci4](https://user-images.githubusercontent.com/40740650/197350949-4c4c88d0-625f-44b3-a8ad-505c8e172ef8.png)

**Comment by simonpoole** [comment]
Same issue as https://github.com/MarcusWolschon/osmeditor4android/issues/1901

**Comment by opk12** [comment]
I confirm that it is fixed, thank you.
