### ISSUE TITLE
Add "Copy tags" to Way Selected menu

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1903]
![Screenshot_20221022-151529_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/197360806-8138a6f2-d543-4261-a601-2ee9efd7d591.jpg)
Here there is only Paste tags. There is no Copy tags. It is missing. Yes there are other ways to copy the tags but there should be a pair of these functions in the menu or none at all.

**Comment by jidanni** [comment]
The problem does not occur when  Node is  selected, only when Way is selected. When Node is selected we can find the Copy tags button on the bottom of the screen.

**Comment by simonpoole** [comment]
> The problem does not occur when Node is selected, only when Way is selected. When Node is selected we can find the Copy tags button on the bottom of the screen.

There is no "copy tags" function outside of the one in the property editor.
