### ISSUE TITLE
Vespucci doesn't show photos from media storage

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1904]
This may be partly related to #1584

Photos don't work at all with Vespucci on my Fairphone 4:
- Photos in `/storage/emulated/0/Download/Vespucci/Pictures` are not shown on photo layer
- Photos from media storage (I guess that means Gallery?) are not shown on photo layer when the option is checked in preferences
- It doesn't matter if the photos were taken with stock photo app or with a Google Photos port
- When I take a picture from within Vespucci,  I get an error that it has no GPS coordinates attached to it and that I should check if geotagging is enabled. ![Screenshot_20221022-130158.png](https://user-images.githubusercontent.com/30999326/197361010-ae681843-cfc9-4c3c-80f4-fa4f861a5596.png)

Here are two example images for download:
https://cloud.familie-brandtner.de/s/4gxFDzw7dbKimnZ

Bug report sent from app 2022-10-22 22:21 CEST

Vespucci 18.0.3 from Playstore
Fairphone 4
Android 11

**Comment by simonpoole** [comment]
On Android 10 (and later) there is no expectation that you can access any photos outside those taken via the photo app configured for vespucci (which will need to support geo tagging, I would recommend OpenCamera for that) and, if enabled, those indexed via Androids MediaStore.

See http://vespucci.io/help/en/17.1.0%20Release%20notes/#include-androids-mediastore-in-scan-for-images and http://vespucci.io/help/en/16.1.0%20Release%20notes/#preference-to-select-camera-app

**Comment by Discostu36** [comment]
OK, so I've looked at the problem again and this is the current status:
- Scanning media storage adds no images to the Photos layer, while there are hundreds of photos with geotags in my DCIM directory (two examples are linked above)
- Taking photos from within Vespucci opens Fairphone's integrated camera app. While the app does support geotagging, Vespucci opens a somewhat simplified version of the app that lacks access to the options and doesn't write geo data to the file

**Comment by Discostu36** [comment]
Ok, i now found the option to use OpenCamera and it does work. So the only issue left is failing showing of photos from media storage.

**Comment by simonpoole** [comment]
The 'MediaStore' is Androids media index; not directly the directly the storage, if the images are visible in your gallery app then you can assume they are indexed.

There are a number of reasons why accessing the photos via the mediastore might go wrong, in particular you need to get a special permission granted to actually get the original files. Unluckily debughing this is going to be difficult without access to the device. 

Note that the indexing works on the android 11 devices I have access to.

**Comment by simonpoole** [comment]
> I have no possibility to use another camera app from within Vespucci

Can't you use OpenCamera?

**Comment by Discostu36** [comment]
> Can't you use OpenCamera? 

Yes, as written above, I've now found the option in Vespucci and it works.

**Comment by Discostu36** [comment]
> There are a number of reasons why accessing the photos via the mediastore might go wrong, in particular you need to get a special permission granted to actually get the original files. 

I can only tell you that Vespucci has the permission

![Screenshot_20221023-081255.png](https://user-images.githubusercontent.com/30999326/197377040-5417bc21-ed16-472d-8c94-41cc6ca66422.png)

**Comment by simonpoole** [comment]
This is Android you don't really think things would be so simple? :-) There's a special runtime permission ACCESS_MEDIA_LOCATION that we need to get for things to work (there is no direct way for you to check that we got it).

Have you exited the app and started it again after changing the  "Use the MediaStore" preference? That may be necessary.

We do log some things during indexing, so if you can use adb to connect to the phone (via USB) you should be able to see the indexing happening. There should be something like

```
10-23 08:28:21.296: D/PhotoIndex(9138): scanning MediaStore
10-23 08:28:21.411: D/Photo(9138): lat: 475516662 lon: 75891666
10-23 08:28:21.413: D/Photo(9138): dir 288.79 direction 288 ref M
.....
10-23 08:28:21.483: D/Photo(9138): lat: 475519447 lon: 75886111
10-23 08:28:21.486: D/Photo(9138): dir 146.6 direction 146 ref M
10-23 08:28:21.622: D/PhotoIndex(9138): updating MediaStore to scan 1666513701621 tag 1209:2f8e77a4-bb20-4b46-a38e-03821b8df104
```
You will need to take a photo to force re-indexing or delete the Vespucci internal index by switching the preference off and on again (but you will need to do: pref off - exit app - start app - pref on - exit app - start app).

**Comment by Discostu36** [comment]
Ok, I'll try that tonight.

**Comment by Discostu36** [comment]
About the problem with the native photo app: Can you tell me how you open it, so I can exlplain this better to Fairphone support? I guess it is some Android intent?

**Comment by simonpoole** [comment]
> About the problem with the native photo app: Can you tell me how you open it, so I can exlplain this better to Fairphone support? I guess it is some Android intent?

See https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/java/de/blau/android/Main.java#L1995 literally the only way you can do it. They are probably concerned about privacy issues (rogue app using the camera to determine the location) and that's why they don't write the location when started via intent.

**Comment by Discostu36** [comment]
This is the indexing log:
```
10-23 21:47:24.464  2097  2189 D PhotoIndex: starting scan
10-23 21:47:24.464  2097  2189 D PhotoIndex: scanning directories
10-23 21:47:24.474  2097  2189 D PhotoIndex: DCIM 1666553912458
10-23 21:47:24.474  2097  2189 D PhotoIndex: Scanning directory /storage/emulated/0/DCIM
10-23 21:47:24.626  2097  2134 D OpenGLRenderer: endAllActiveAnimators on 0xb400007616f84dc0 (i0$a) with handle 0xb400007537301540
10-23 21:47:25.140  2097  2189 D PhotoIndex: updating DCIM to scan 1666554445140 tag null
10-23 21:47:25.144  2097  2189 D PhotoIndex: Scanning directory /storage/emulated/0/external_sd/DCIM
10-23 21:47:25.145  2097  2189 D PhotoIndex: Directory /storage/emulated/0/external_sd/DCIM doesn't exist
10-23 21:47:25.146  2097  2189 D PhotoIndex: Scanning directory /storage/emulated/0/Download/DCIM
10-23 21:47:25.148  2097  2189 D PhotoIndex: Directory /storage/emulated/0/Download/DCIM doesn't exist
10-23 21:47:25.149  2097  2189 D PhotoIndex: Vespucci 1666553912754
10-23 21:47:25.149  2097  2189 D PhotoIndex: Scanning directory /storage/emulated/0/Vespucci
10-23 21:47:25.150  2097  2189 D PhotoIndex: Directory /storage/emulated/0/Vespucci doesn't exist
10-23 21:47:25.150  2097  2189 D PhotoIndex: Scanning directory /storage/emulated/0/external_sd/Vespucci
10-23 21:47:25.151  2097  2189 D PhotoIndex: Directory /storage/emulated/0/external_sd/Vespucci doesn't exist
10-23 21:47:25.151  2097  2189 D PhotoIndex: Scanning directory /storage/emulated/0/Download/Vespucci
10-23 21:47:25.348  2097  2189 D PhotoIndex: updating Vespucci to scan 1666554445348 tag null
10-23 21:47:25.350  2097  2189 D PhotoIndex: osmtracker 0
10-23 21:47:25.350  2097  2189 D PhotoIndex: Scanning directory /storage/emulated/0/osmtracker
10-23 21:47:25.351  2097  2189 D PhotoIndex: Directory /storage/emulated/0/osmtracker doesn't exist
10-23 21:47:25.351  2097  2189 D PhotoIndex: Scanning directory /storage/emulated/0/external_sd/osmtracker
10-23 21:47:25.353  2097  2189 D PhotoIndex: Directory /storage/emulated/0/external_sd/osmtracker doesn't exist
10-23 21:47:25.354  2097  2189 D PhotoIndex: Scanning directory /storage/emulated/0/Download/osmtracker
10-23 21:47:25.355  2097  2189 D PhotoIndex: Directory /storage/emulated/0/Download/osmtracker doesn't exist
10-23 21:47:25.359  2097  2189 D PhotoIndex: updating MediaStore to scan 0 tag
10-23 21:47:25.364  2097  2189 I PhotoIndex: Query returned 0 photos
```
The photos in question are in sub folders of /storage/emulated/0/DCIM, I don't know if it has something to do with that? Otherwise, it is weird that the scan takes less than a second for 1900 files.

**Comment by simonpoole** [comment]
So it isn't actually scanning the media store the  
```
scanning MediaStore
```
line would be present otherwise.

You can ignore the rest, that is just the conventional directory scan, Android 11 will not return any directory contents, for the DCIM directories so it is very fast.

**Comment by simonpoole** [comment]
I may have been able to recreate the issue on an Android Emulator running Android 11 (as said it works on a number of real world devices with 11), will give it a closer look tomorrow.

**Comment by simonpoole** [comment]
I just realized what the problem could be. Requesting and getting the ACCESS_MEDIA_LOCATION is tied to getting the permission for storage access, could you turn off the storage permission, (re-)start the app and grant the permission again and see if that changes the behaviour?

**Comment by Discostu36** [comment]
It worked!

But only when I removed the photo layer first, then revoked permisson, then restarted the app, then added the photo layer again. When I didn't remove the layer, Vespucci started scanning for photos immediataley after I opened the app, without waiting for granted access permission first.
