### ISSUE TITLE
Accept preset icons in SVG format

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1905]
At the moment presets don't show icons in Vespucci when they are in SVG format. That makes some of them quite useless, like `traffic signs_DE`

![Screenshot_20221022-131120.png](https://user-images.githubusercontent.com/30999326/197361154-fe5e3c73-8320-4880-bfe1-ec14d293238b.png)

Please add SVG support if you can find the time.

**Comment by simonpoole** [comment]
Android doesn't support SVG natively, so any such icon would have to be converted before the preset could be used (theoretically it should be possible to convert to Androids VectorDrawable format, but that still means doing that before use). 

While it is in principle possible to add code to do this in the app and convert on device, all in all it doesn't make sense from many aspects and you are better off simply generating two (or more) versions of the preset for different uses. Have a look at my preset repos for how to do this with minimal duplication.

**Comment by simonpoole** [comment]
https://github.com/BigBadaboom/androidsvg might be a viable way of supporting this now, last time I checked it was years out of date and didn't work on modern Android versions, but seems that has been fixed with version 1.4. 

Unluckily it will still require quite some work to actually implement.
