### ISSUE TITLE
Add more fields for `highway=rest_area`

### ISSUE THREAD

**Issue by Dimitar5555** [MarcusWolschon/osmeditor4android#1911]
https://wiki.openstreetmap.org/wiki/Tag:highway%3Drest_area

operator=*

caravan=yes/no - Indication whether a feature provides caravan access.

Where the location of these features is known it is best to map them as separate features: 

toilets=yes/no - Indication of whether a feature has public toilets.

drinking_water=yes/no - Indication whether a feature provides drinking water.

bin=yes/no - Indication whether a feature provides garbage bins.

picnic_table=yes/no - Indication whether a feature provides picnic tables

**Comment by simonpoole** [comment]
This is a preset issue, please open an issue there https://github.com/simonpoole/beautified-JOSM-preset
