### ISSUE TITLE
Internal photo viewer doesn't rotate image correctly

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#1912]
## Vespucci Version

18.0.3

## Download source

Google

## Device (Manufacturer and Model)

Fairphone 4

## Android Version 

11

## Behaviour/Symptoms

Internal photo viewer doesn't show photos with correct orientation 

## Expected Behaviour

Internal photo viewer should show photos with correct orientation. As far as I know it needs to read orientation from image metadata for that.

## How to recreate

Open a photo on photo layer. It doesn't seem to make a difference if the photo was taken in portrait or horizontal orientation.

![Screenshot_20221028-085406.png](https://user-images.githubusercontent.com/30999326/198822925-9f631682-d17b-4f7f-8ccf-12f0a0634917.png)

![Screenshot_20221029-105746.png](https://user-images.githubusercontent.com/30999326/198822983-0fbdb817-b16c-4f55-92c3-3eb43da667b6.png)

**Comment by simonpoole** [comment]
I'm fairly sure that there was a reason I used a fixed orientation value instead of  reading it from the EXIF (as in not showing predictable behaviour on some devices) , in any case I'm creating a PR to change that.
