### ISSUE TITLE
Very easy to send an incomplete changeset comment 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1919]
Here, attempt to remove the z's by repeatedly tapping the delete button on the keyboard.

![Screenshot_20221031-211607_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/199144113-62346234-d979-435f-b6e7-37bba5f413e9.jpg)

If your finger slips downward, you will end up hitting **Next**, which becomes **Done**, which becomes **Upload**, and then it's too late ... you've closed this changeset and sent a mangled changeset comment! 

It would be best if the dangerous keys were not all exactly lined up on the same position, one underneath the other, underneath the other, underneath the other.. That way if your finger gets stuck somewhere you won't end up sending non-ready edits right through to the server (with no way to undo.)

It's the same principle why emergency telephone numbers are 911, or 119, not 999, or 111.

**Comment by simonpoole** [comment]
Use a different keyboard?
