### ISSUE TITLE
What GPX should I be able to download from OpenStreetMap?

### ISSUE THREAD

**Issue by rrodrigueznt** [MarcusWolschon/osmeditor4android#1920]
Hi! Not sure if this is the right place to ask about this. I'm new to Vespucci, installed it on a Samsung A52 running Android 12. Should I be able to download any of my OSM traces stored as identifiable? I'm able to upload traces, but I'm not able to access my traces stored in OSM.

Please, could you point me in the right direction Thanks!

**Comment by simonpoole** [comment]
You should be able to download all of your GPX tracks regardless of their visibility status (but no 3rd party ones),. you do need to be authenticated though. When retrieving the list of available tracks we test that the first trackpoint is in the current view (unluckily the 1st point is the only location we get, any other implementation would require downloading all tracks for a user, which obviously would be very expensive), 

See also http://vespucci.io/help/en/Main%20map%20display/#layer-control and

**Comment by simonpoole** [comment]
Success?

**Comment by rrodrigueznt** [comment]
Absolutely! Sorry, I didn't want to make noise. But once here: I'm impressed by this software and enjoying a lot of studying its features and capabilities and also trying to understand how it fits in the _toolscape_ of mapper rookie! Thanks for your answer, and thanks to @MarcusWolschon and the team of collaborators for this great piece of code!
