### ISSUE TITLE
Print message upon GPX file collision

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1922]
![Screenshot_20221103-161359_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/199835566-91bf8ede-c7c3-44b2-a654-fb99daa45d82.jpg)

If we add layer from the same GPX file twice, the app should say:
- that layer already exists. File ignored. Or,
- that layer already exists. Overwriting. Or,
- that layer already exists. Please choose a different file.

**Comment by simonpoole** [comment]
Your screen shot is showing two differently named at least layers.

**Comment by jidanni** [comment]
Yes, let's say we have GPX files a, b, and c. And we upload a, and b, and b again by accident.
