### ISSUE TITLE
Pressing "Node not downloaded" doesn't download

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1923]
Pressing "Node (not downloaded)" doesn't download. 

We see "downloading data from server." But that doesn't fix the "Node not downloaded" message. 

geo:42.1660857,-87.7825081

![Screenshot_20221104-015959_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/199912517-b7fe04cd-8044-4387-8b25-ec574995e61f.jpg)

**Comment by simonpoole** [comment]
> Pressing "Node (not downloaded)" doesn't download.
> 
> We see "downloading data from server." But that doesn't fix the "Node not downloaded" message.

Because you deleted the node in question 8 days ago https://www.openstreetmap.org/node/10112539246

**Comment by jidanni** [comment]
It should print a message: node longer available.

Currently we could push the not downloaded button several times and each time it says downloading and then nothing happens. It should print an error message please.

**Comment by simonpoole** [comment]
> It should print a message: node longer available.

How would it know that? it simply downloads the area around the element (as it needs to include parent elements) and merges it with the existing data. After merging the element still isn't present because it is deleted. Naturally we can detect that, however it requires yet another round trip to the API, but the message in the dialog will still not change as it is correct.

**Comment by jidanni** [comment]
I have a few ideas:
1. First, none of the text on this page is copyable. It would be nice if we could copy it with our fingers.
2. And each time a node number is mentioned, it could actually be a hyperlink to the node on the OSM website.
3. Then down at the bottom of the page, there could be a button that does just what you said and is marked clearly "Download this area's Tasks again."
And in fact it should probably be "clear and download this area's  tasks again" or simply "refresh this area's tasks."
