### ISSUE TITLE
Rendering nodes: place=locality

### ISSUE THREAD

**Issue by rrodrigueznt** [MarcusWolschon/osmeditor4android#1927]
Hi! I'm afraid I've not yet enough understanding about the OSM ecosystem as for posting good questions, but I'm stuck with a question I would like to answer.

While using Vespucci, I found almost everywhere map features with key place=locality. Without entering the discussion about the use of that key, I would like to know if it is possible to avoid Vespucci rendering them as a black-solid icon and get their labels in a readable size instead. See below: on the top, a map area as rendered by Vespucci in edit mode; on the bottom, the same area as rendered at OpenStreetMap site with Standard style.

<table>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/1550835/200071013-eaa78051-f99b-4c2b-8e0e-7d73f89f88de.jpg" width="400" ></th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/1550835/200071045-9eeaba12-ab6e-407d-a5ab-0b62869f3f3e.png" width="400"></th>
  </tr>
</table>

Does it make any sense for you to avoid those non-informative black-solid icons?

Thanks for your help!

**Comment by simonpoole** [comment]
There is simply no place=locality specific icon, the primary source for these are the presets https://github.com/simonpoole/beautified-JOSM-preset (you can override these in the data styling, but that rarely makes sense http://vespucci.io/tutorials/data_styling/)

See also http://simonpoole.github.io/beautified-JOSM-preset/#Geography

Note that this discussion belongs in the preset repo.

**Comment by rrodrigueznt** [comment]
Thanks!

> There is simply no place=locality specific icon, the primary source for these are the presets https://github.com/simonpoole/beautified-JOSM-preset (you can override these in the data styling, but that rarely makes sense http://vespucci.io/tutorials/data_styling/)
> 
I see that some features are defaulting to "solid icons" (no content, just squared polygons of different colors; it is the case of Reef, Payment center, or Locality), while for others no icon, neither with the content of being "solid icons" as explained above (it is the case of Protected Areas or Garages, for instance). Please, could you help me to understand the difference between them? Could you point me in the right direction? Thanks!

In the case of place=Locality, I think it would be more convenient to avoid any icon or figure rendered for them: default OpenStreetMap rendering shows the name of the feature. It could even be advisable to avoid showing the name at any zoom level to prevent superposing both the default name coming to OpenStreetMap (Standard) and the value shown by Vespucci.

> See also http://simonpoole.github.io/beautified-JOSM-preset/#Geography
> 

> Note that this discussion belongs in the preset repo.
> 
Sorry, I don't understand this last sentence. Please, what do you mean? **Thanks for your help!**

**Comment by simonpoole** [comment]
> > Note that this discussion belongs in the preset repo.
> 
> Sorry, I don't understand this last sentence. Please, what do you mean? **Thanks for your help!**

As said icons are part of the presets, which are a separate project (you could use a completely different one if you wanted too), and any icon changes etc need to be made there:  https://github.com/simonpoole/beautified-JOSM-preset

**Comment by rrodrigueznt** [comment]
Got it! Thanks!
