### ISSUE TITLE
Allow downloading more data during an edit

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1929]
Here, oops, we've gone a little bit beyond the edge of the known data, so we've triggered the message to download more data,
![Screenshot_20221104-170257_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/200081762-4074c0fe-cb33-48e7-9509-f39002c2d541.jpg)

Now certainly there would be no harm in allowing the user to somehow download more data at this point without requiring the formalities of leaving the edit mode just for access to the 'up and down arrows' button to download more data.

I mean users, very often, become like a hungry dog chasing some prey, and then before you know it they've gone beyond the boundaries of what they've already downloaded. (Yes, they didn't plan ahead.)

So maybe the message could say "would you like to download some more data now? "And then it could download this screen's worth of data...

Yes, it's still possible to edit into the unknown areas, but still the user would feel better if he could just download the data, but also not need to leave the edit mode.

**Comment by simonpoole** [comment]
Use pan and zoom auto-download mode.

**Comment by jidanni** [comment]
Hmm. Maybe the error message could suggest that.
