### ISSUE TITLE
Allow selecting all text on imagery info dialog

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1930]
Here, to copy all the text on this dialogue each line has to be tediously selected and copied individually!
![Screenshot_20221104-173722_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/200084898-3ec7dc62-67f2-4af8-864a-71a3d8ac628e.jpg)
Perhaps that restriction could be relaxed to enable the user to copy all the lines he wishes, all in  one operation.

**Comment by jidanni** [comment]
Indeed, each **field** of each line requires a separate copy operation:
![Screenshot_20221104-173952_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/200085110-2ed892ff-09f4-41dc-8cc3-850fc88704ff.jpg)

**Comment by simonpoole** [comment]
What is the use case for this supposed to be?

**Comment by jidanni** [comment]
It's mainly too avoid the need to make screenshots for anything longer than copying a line. Screenshots are not web searchable either. 

Maybe add a button at the bottom to copy the whole thing, and then people could later remove the lines they don't want on their own.

For instance, I could just place the first few lines here, using a hundred bytes, instead of using a screenshot for a thousand times more bytes.

**Comment by simonpoole** [comment]
> It's mainly too avoid the need to make screenshots for anything longer than copying a line. Screenshots are not web searchable either.

What is the use case for the specific dialog? Why would you want the text at all?

**Comment by jidanni** [comment]
I could make personal notes of the data, or share it with friends, all without needing environmentally unfriendly screenshots.

**Comment by simonpoole** [comment]
So know actual use case.

**Comment by jidanni** [comment]
(And pasting in bug reports.)
