### ISSUE TITLE
Ignore style files with parse errors (was Crashes on Samsung A52 device, Android 12)

### ISSUE THREAD

**Issue by rrodrigueznt** [MarcusWolschon/osmeditor4android#1931]
The application **ALWAYS** crashes when I click the Preferences button.

## Vespucci Version
18.0.5

## Download source
Google Play Store

## Device (Manufacturer and Model)
Samsung, model SM-**A52**8B

## Android Version 
12

## Behaviour/Symptoms
When I click the Preferences button, Vespucci crashes and sends a report.

## Expected Behaviour
To open the Preferences menu.

## How to recreate
No idea. It consistently happens every time I click the Preferences icon.

## Crash dump submitted (no or yes + date)
Yes. Several dumps were submitted today, November 5th, 2022. I'm also attaching the dump report _removed the dump report_
generated by some general crashed analysis and reporting software installed on the phone.

## Any other potentially relevant information
Before the crashes started, I was trying to understand how OSMOSIS and other errors/inconsistencies reported problems on the map, close to the area I was in, on my Android device, and found some issues: clicking on the warning doesn't open Vespucci, but another application and the map was not centered on the in troubles items.

I'm at your disposal to send all the information you require. Thanks!

**Comment by simonpoole** [comment]
Did this start happening immediately after you installed 18.0.5?

**Comment by simonpoole** [comment]
It seems to be crashing while trying to generate the list of available styles. Can you check if you can access Android/data/de.blau.android/files/styles on your device with a file manger or similar and if something is present there, move it somewhere else for now?

**Comment by rrodrigueznt** [comment]
Nice point! It was not immediately after installing 18.0.5 that started crashing, but after creating a test.xml empty file in Android/data/de.blau.android/files/styles. Once I deleted it, no more crashes happened so far!

Must I try with a non-empty file? Thanks!

**Comment by simonpoole** [comment]
> Must I try with a non-empty file? Thanks!

No not necessary, the cause for the issue is obvious.
