### ISSUE TITLE
Way to input opening_hours:drive_through

### ISSUE THREAD

**Issue by yaomtc** [MarcusWolschon/osmeditor4android#1932]
Have to type `opening_hours:drive_through` in Details manually. Is it possible to have that field show up for restaurants when `drive_through=yes`? Otherwise an option in the three-dot menu of the opening hours dialog might be useful, such as "add rule for..." > "Drive through". Could add `opening_hours:kitchen` there too, since it's suggested in Details.

**Comment by simonpoole** [comment]
Could you open this in the preset repo, best with a PR: https://github.com/simonpoole/beautified-JOSM-preset
