### ISSUE TITLE
Too easy to move entire ways

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1935]
One enormous pitfall of Vespucci, is there is no way to tell it, that _no matter what we don't want any of our actions to end up moving the entire way._ There's just no preference to stop it happening.

Okay. Starting from this state:

![Screenshot_20221107-162138_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/200428214-4f581864-83a4-44d3-b1f1-62828e95d049.jpg)

And finally ending up in this state:

![Screenshot_20221107-162743_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/200430140-a20ce153-1044-4d1e-a700-2bafe4291bcb.jpg)

We are happy, however it was not easy. We always had to keep our hands ready to hit the undo button. The problem is that you have to be careful to hit the pluses etc. Those are the only ones guaranteed not to accidentally move the entire way by accident.

Sure, you might say "it's your own fault for touching parts of the way you're not supposed to touch with your large size fingers."

For some reason Vespucci seems to be designed for people that like to move giant ways by grabbing on them. We are just trying to adjust the shape of a way. We don't want to actually move the whole  thing.

So here's what I want: no matter what I touch or accidentally touch I don't want to end up moving the entire ring anywhere!

It's just like I'm fixing the front door of  my grandma's house. I don't to have it be like the whole house is on some greasy jelly and I end up shoving her entire house, front door, back door, everything, seven feet back.

You might say: "toggle the enable way node dragging preference." However this has nothing to do with it.
  
You might say that disabling any actions when you touch a line segment would reduce functionality. Well that's the price I'm willing to pay for my large size fingers.

**Comment by simonpoole** [comment]
What about zooming in further?

**Comment by davidpnewton** [comment]
How about using the add node functionality and not selecting the way at all?

There is already a way to achieve what you want which accounts for clumsiness. Besides how do you suggest ways be moved without being moved when selected and dragged?

**Comment by simonpoole** [comment]
It should be pointed out that the "touch" areas around objects can be configured in the data styles, in the case of ways with way_tolerance and way_tolerance_2 see http://vespucci.io/tutorials/data_styling/

**Comment by simonpoole** [comment]
> Well in iD they never would have dreamed someone would want to move an entire way... without specifically picking the **move** command out of the menu! (That is what I'm aiming for with this feature request.)

You could have fooled me, I though the point was to make random inflammatory comments so that we perma-ban you at last.
> 
> > It should be pointed out that the "touch" areas around objects can be configured in the data styles, in the case of ways with way_tolerance and way_tolerance_2 see http://vespucci.io/tutorials/data_styling/
> 
> Yes one can make enormous touch areas, so much that the screen is dominated by them, but then you have too large touch areas. Yes in theory the user can no longer reach the way to accidentally move it, but then the touch areas are so large they begin to overlap, and on long straight ways with few nodes the touch areas wouldn't be enough protect the way from getting accidentally moved.

The idea would be to reduce the touch areas for ways.

**Comment by jidanni** [comment]
> The idea would be to reduce the touch areas for ways.

Interesting. I thought you meant _increase_ touch areas for nodes.
But still the danger of moving an entire way persists.

**Comment by jidanni** [comment]
I discovered one real hazard, is... well, keep your eyes on the node in the middle of this screen:
First we'll take a screenshot of it:

![Screenshot_20221121-173608.jpg](https://user-images.githubusercontent.com/1230959/203180317-aa7986a1-5ad0-4747-9d65-e64ec3df2374.jpg)

Now we'll move it a little and take another screenshot:

![Screenshot_20221121-174044.jpg](https://user-images.githubusercontent.com/1230959/203180442-593d6d3a-1f37-4798-85b5-a701c239b7c6.jpg)

Now we'll move it some more and take even another screenshot:

![Screenshot_20221121-174112.jpg](https://user-images.githubusercontent.com/1230959/203180539-1f9179f1-fed1-4ca1-9c7d-07e342a1f5b8.jpg)

But, what a surprise, it's behavior has changed, and now it drags the entire way along with it. 

Yes, of course it's just following the rules, but it's not very user friendly: the same actions have different results.

I mean, just like when we walk down the street. If we stop to look at our wrist watch, we would expect when our legs start moving again we will still be walking.

**Comment by HolgerJeromin** [comment]
> I discovered one real hazard, is... well, keep your eyes on the node in the middle of this screen:

This is no node. It is a "drag me to add new nodes" feature
![image](https://user-images.githubusercontent.com/2410353/203246092-ba1d5ebb-c1a1-4f97-b78d-42a036340f41.png)

Which makes manipulating a way very fast!

**Comment by jidanni** [comment]
(Yes, but when one's finger releases it suddenly becomes a node.)
