### ISSUE TITLE
Maps Humanity style Not Update

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1937]
Description:
---

Is the humanity style map not updating, I have edited it but it doesn't update it still looks like the old maps, even though all the other style maps have been updated.  please fix.

Device info:
---
<table>
<tr><td>App version</td><td>18.0.5.0</td></tr>
<tr><td>App version code</td><td>2206</td></tr>
<tr><td>Android build version</td><td>V12.0.14.0.QCDIDXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020</td></tr>
<tr><td>Device brand</td><td>Redmi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>dandelion</td></tr>
<tr><td>Device model</td><td>M2006C3LG</td></tr>
<tr><td>Device product name</td><td>dandelion_id</td></tr>
<tr><td>Device hardware name</td><td>mt6762</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Endarko"/>Endarko</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Vespucci caches all tiles from an imagery layer on device, if there are updates that you want to use, you need to flush the cache, see vespucci.io/help/en/Main map display/#layer-control

**Comment by simonpoole** [comment]
Seems to be a general issue with the layer.
