### ISSUE TITLE
Show more hint info in disambiguation menu

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1938]
Description:
---

Continuing ways is really nicely handled in Vespucci

But would it be possible to show also way length (may be just node count)? At least for cases where multiple ways for selection have exactly the same name?

I split residential road near its end (as it was splitting in two) and wanted to continue longer section. But both were just shown just as "Zarzecze" (street name) and the first random selection was wrong.

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>18.0.5.0</td></tr>
<tr><td>App version code</td><td>2206</td></tr>
<tr><td>Android build version</td><td>V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.191002.002.V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Mateusz Konieczny"/>Mateusz Konieczny</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Anyway of addressing this is dependent on https://github.com/MarcusWolschon/osmeditor4android/issues/1235 

That said node count sounds good as an additional displayed attribute, but it will only work when the ways are short, or very unbalanced in length (aka a Node count of 123 and 132 to two ways doesn't make the entries any easier to differentiate).

**Comment by simonpoole** [comment]
Maybe numbering the segments would be a way of doing this.
