### ISSUE TITLE
Custom layer

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1942]
Description:
---

Custom layer don't display anymore, layer is erroring. Same problem on Pixel 6.

Device info:
---
<table>
<tr><td>App version</td><td>18.0.5.0</td></tr>
<tr><td>App version code</td><td>2206</td></tr>
<tr><td>Android build version</td><td>9196637</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>R107-15117.112.0 release-keys</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>hatch_cheets</td></tr>
<tr><td>Device model</td><td>hatch</td></tr>
<tr><td>Device product name</td><td>hatch</td></tr>
<tr><td>Device hardware name</td><td>bertha</td></tr>
<tr><td>ABIs</td><td>[x86_64, x86, arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[x86, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[x86_64, arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/osmviborg"/>osmviborg</A></td></tr>
</table>

**Comment by simonpoole** [comment]
> Custom layer don't display anymore, layer is erroring. Same problem on Pixel 6.

If it doesn't work on two devices that would be a good indicator that the layer provider is having issues.  Can you provide an URL for the layer, otherwise it is going to be "a bit difficult" to debug.
