### ISSUE TITLE
Rename default Data Style to Black Data Style

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1943]
![Screenshot_20221117-150357_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/202560347-1f9410d5-463c-404c-bf8c-a06ca8a8c610.jpg)
The  "Default" data style now is simply a name. Because it is not the actual default anymore shiped with the app. Therefore perhaps it should be renamed to Black (line) Data Style.

Also calling it by a specific name is much clearer than calling it just  Default.

And even if it was the default it should still have a name of its own in addition.

**Comment by simonpoole** [comment]
'Minimal' would probably be more appropriate.
