### ISSUE TITLE
Just zoom to location, don't undo

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1951]
Here also useful, would be the additional choice: just zoom to the location, but don't undo anything.
![Screenshot_20221121-191811_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/203191001-bd25c418-56f2-46b5-b645-bfce81b11aba.jpg)
(Yes, currently that could also be achieved by doing the undo, and then doing a redo.)

**Comment by simonpoole** [comment]
Going/zooming to the last edit will have the same effect.
