### ISSUE TITLE
Offer copy URL of Osmose issue

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1952]
In https://github.com/osm-fr/osmose-backend/issues/1657 I was asked to include the link to an Osmose issue.

However, it turns off that there is no way to copy it off of this page:
![Screenshot_20221122-200342_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/203456909-2f23b909-39e8-48d0-a7ed-298bda548e31.jpg)

There could perhaps be a link at the bottom added, to just to copy the Osmose link when pressed.

**Comment by simonpoole** [comment]
The uuid in the id field should be unique and enough that they can locate the issue.
