### ISSUE TITLE
Accidental upload

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1956]
Description:
---

I just went to submit my changes to OSM, verified my changes in the first screen and then went to click "Upload" to proceed to the next screen. Doing so, I accidentally tapped it twice, which instantly confirmed the upload with the comment set to the one I used most recently.

This is not exactly ideal. I don't think you need to upload changesets with the exact same comment very often, so I believe leaving the comment field blank initially would be better to prevent accidental uploads like that.

Device info:
---
<table>
<tr><td>App version</td><td>18.0.5.0</td></tr>
<tr><td>App version code</td><td>2206</td></tr>
<tr><td>Android build version</td><td>A135FXXU2AVJ3</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.A135FXXU2AVJ3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a13</td></tr>
<tr><td>Device model</td><td>SM-A135F</td></tr>
<tr><td>Device product name</td><td>a13nseea</td></tr>
<tr><td>Device hardware name</td><td>exynos850</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Xandaros"/>Xandaros</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Lots of users use similar tags on changesets as they just used, particularly for the source tag, so not setting the last one used would cause endless complaints. TH^he fix is simply de-bounce the button (aka require a minimum delay between clicks).
