### ISSUE TITLE
add gpx layer doesn’t do anything

### ISSUE THREAD

**Issue by erik55** [MarcusWolschon/osmeditor4android#1959]
## Vespucci Version
18.0.5 on Android 10 and also on Android 8

## Download source
google playstore

## Device (Manufacturer and Model)
* Samsung Galaxy S7
* Samsung Galaxy S9

## Android Version 
* Android 8
* Android 10

## Behaviour/Symptoms
I want to import or load a gpx track file to use it for tracing and painting new ways.

I tried add gpx layer in the 3 bar layer menu, but nothing shows up. No change at all visible. As if I hadn’t done anything.

## Expected Behaviour
The gpx track should be shown on the map and something should be shown in the layers menu to know, that this track has been loaded.

## How to recreate
Happens all the times. Start Vespucci, try to add gpx track in the layer menu by hitting the + button and then 
add gpx layer.

## Crash dump submitted
There is no crash. Just no reaction.

## Any other potentially relevant information
I have been asking this here <https://help.openstreetmap.org/questions/86243/how-to-addloadimport-gpx-track-in-vespucci?>

**Comment by simonpoole** [comment]
Can you try to submit a crash dump via the "Debug" page as described in https://help.openstreetmap.org/questions/86243/how-to-addloadimport-gpx-track-in-vespucci? 

As a further clarification (to narrow this down) do you get the layer styling dialog after you selected the file or not? 

As creating a GPX layer works without issue on a S7 with stock Android 8.0 here (this is one of the test devices we do a manual check on before release), there is likely something that is common to both your devices and how you are trying to load the GPX file that is causing the issue. 

Random things to think about: 
- are you trying to load from a removable SD card?
- anti-virus apps?
- ...

**Comment by scaidermern** [comment]
I got the same problem with Android 10 (LineageOS, so no weird vendor modifications) on a Samsung S9.

> As a further clarification (to narrow this down) do you get the layer styling dialog after you selected the file or not?

No. After selecting the GPX file the regular layer dialog is visible again (the one that is directly accessible via the hamburger menu from the top right).

> are you trying to load from a removable SD card?

Tried both, neither one works.

> anti-virus apps?

No such thing.

"Debug" page:
![photo_2022-11-30_08-51-16](https://user-images.githubusercontent.com/1040784/204738074-e2d42da9-69bc-49aa-b26f-1394dbadac53.jpg)
Nothing relevant as far as I can see :(

**Comment by simonpoole** [comment]
@scaidermern can you try to add a layer and then immediately go to the debug page and send a crash dump "Information zur Problembehebung senden"? Pls add something to the description so that I can clearly identify it.

**Comment by simonpoole** [comment]
OK, interesting, I've been able to narrow down where things go wrong from the dump provided by @scaidermern (assuming that this is the same error). Unluckily it seems that it is the system file selector having an issue, that is, it is not returning the URI for the files. 

This naturally makes things very difficult to debug, can you provide a sample file that doesn't work (original file name pls) and the exact location it was stored on your device?

**Comment by scaidermern** [comment]
> can you provide a sample file that doesn't work (original file name pls) and the exact location it was stored in on your device? A screen recording might be helpful too.

File: [foo.gpx.txt](https://github.com/MarcusWolschon/osmeditor4android/files/10121643/foo.gpx.txt) (I had to append .txt at the end because GitHub doesn't allow uploading .gpx files)

This file is located at `/storage/emulated/0/Download/foo.gpx` on my device. I also tried other locations.

Screen recording: https://user-images.githubusercontent.com/1040784/204759038-d57f4973-bf3c-4cae-8db6-fc1921a817c5.mp4

**Comment by simonpoole** [comment]
> As you can see, I tried to select the file via two different file manager apps.

And that is the problem, MiXplorer causes the issue (@erik55 can you confirm that you have it installed or another similar 3rd party app?), interestingly enough it stops the system file picker from working too.

**Comment by erik55** [comment]
I have tried with a small gpx file that is located on internal memory in folder Music (as you can see in the screen recording). I have sent you a debug log (you can see it in the screen recording). And I tried two file managers (the blue one is the internal one, the other one is 3rd party. You can find the gpx file here: <https://wormhole.app/y5ejK#2Xoq22Lq8mP5kF0nzNn6iw> and the screen recording here: <https://wormhole.app/L91D9#E948qg6D3Ruo35webnOIQQ>

**Comment by erik55** [comment]
I can later try the same with the Samsung Galaxy S7 (which has Android 8).

**Comment by erik55** [comment]
Ok, thank you very much. Great work! Donation started, so that my friends and me who are using Vespucci have lesser bugs in the future.

**Comment by erik55** [comment]
Bug was found and fixed. I expect it to work with the next release.

**Comment by simonpoole** [comment]
> Bug was found and fixed. I expect it to work with the next release. 

To be clear there was no bug in Vespucci.

Having multiple file selection apps is simply not properly supported in Android (and goes completely away in Android 11).

The fix is a workaround Androids broken behaviour, not a fix for anything Vespucci does.
