### ISSUE TITLE
Say close, not cancel at bottom of map background dialog

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1968]
Here at the bottom in green, the word "cancel" should actually be the word "close", else it seems like it'll revert any choices we make to the three radio buttons at the very top row.

![Screenshot_20221123-215124_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/203690256-bfe8118d-4833-4fc2-9163-dc1344063395.jpg)

**Comment by simonpoole** [comment]
Given that the category radio buttons don't really change anything of relevance for further use of the app, "Cancel" is actually correct as it cancels the selection of a layer.
