### ISSUE TITLE
Allow choosing what key to show in relation member list

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1972]
Here all these guideposts only differ by their reference numbers. It would be great if we could select "ref" to be the key that is shown in this case.

Then we could tell in it at a glance if they were 1, 2, 3, or 3, 2, 1, or 1, 1, 2, etc. without needing to tap each one to find out.

![Screenshot_20221204-092702_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/205499708-413a1719-2347-4886-b64f-443f91a4d6ac.jpg)

**Comment by simonpoole** [comment]
Will be provided (via presets) with https://github.com/MarcusWolschon/osmeditor4android/issues/1232

**Comment by jidanni** [comment]
Also let's say we have trail markers, like in https://github.com/MarcusWolschon/osmeditor4android/issues/1971#issuecomment-1337133949 ,
but... their tags are not identical. But they in fact differ via
> ref=01
> ref=02
> ref=03

Well, now that we will soon be able to list them by their e.g., ref, please make sure the Sort button will also be able to sort them by their ref.

**Comment by simonpoole** [comment]
> Well, now that we will soon be able to list them by their e.g., ref, please make sure the Sort button will also be able to sort them by their ref.

PLs open a separate issue for this, it literally doesn't have anything to do with the current isse. But: relation member sorting mainly depends on the semantics of the relation, it is highly unlikely that sorting on arbitrary keys actually makes any sense.
