### ISSUE TITLE
Upgrading warning seen after upgrading

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1980]
After upgrading we click to see what's new in the dialogue that pops up and see
> Upgrading from previous versions

>As the saved state file has changed you should upload any pending changes before updating.

That is good advice, but users will see this usually **after** upgrading.

So I sure hope there are other safety checks to prevent disasters.

By the way in that message says up_grading_ at the top and up_dating_ at the bottom.

**Comment by simonpoole** [comment]
The release notes are always available in advance see for example http://vespucci.io/help/en/18.1.0%20Release%20notes/ and in any case the warning always applies even if there has been no specific change for the version in question as the user might be multiple versions behind.
