### ISSUE TITLE
Better "+" menu ordering

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1982]
![Screenshot_20221211-215328.jpg](https://user-images.githubusercontent.com/1230959/206959423-93672da7-6fa2-4448-9250-bd7f20d0b33a.jpg)

A better ordering perhaps would be:
1. Add node
1. Add untagged/raw node
1. Add way
1. Paste once
1. Paste twice.../multiple tiimes
1. Add map note

**Comment by simonpoole** [comment]
No, it wouldn't be better.
