### ISSUE TITLE
URL green but not clickable 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1987]
The first green hyperlink works fine,

![Screenshot_20221214-070628_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/207632289-235b4481-9212-46fc-84cc-920b95e6c213.jpg)

But not the second,
![Screenshot_20221214-070615_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/207632706-a288501f-b8a3-410c-813e-f0b938d09fc8.jpg)

**Comment by jidanni** [comment]
So the method to open such hyperlinks is: 

If tapping the link doesn't do anything, then long press.
![Screenshot_20221214-100533_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/207673199-e7f44229-b3a7-4062-9756-8622ccb1161c.jpg)
Next, be sure the entire link is highlighted, and then press "Open."

It would be nice if there was more choices, like:
![Screenshot_20221214-100356_Brave - Beta.jpg](https://user-images.githubusercontent.com/1230959/207673419-3207ac46-3162-4a32-9524-6f10d6e1ce28.jpg)

**Comment by jidanni** [comment]
It seems that the appropriate colour for such items should not be green, but instead black. In fact there could also be a little box next to it with an arrow inside it meaning hyperlink so there still could be a hyperlink. Even though the URL would be repeated twice in the source code of the page.

**Comment by simonpoole** [comment]
The colour for links is whatever Android chooses from the theme.
