### ISSUE TITLE
When house numbers increment in different regular intervals other than two

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#1998]
Here house numbers are 5, 15, 25, 35, 45, 55:

![Screenshot_20221216-101514_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/208163347-3c561239-b0e6-480f-bdef-409db7602b05.jpg)

This apparently baffled the "42" shortcut, which apparently assumes only intervals of two.

Its artificial  intelligence didn't catch on even after I entered each one and corrected the answer that it gave. For instance at the very last one, 55, it still had guessed 46.

The regular gap of 10 even threw off its odd/even footing etc.

Yes, it usually does a pretty good job, and knows if we're going up or down etc., but in this case it really got befuddled.

**Comment by simonpoole** [comment]
There is neither a hardwired increment nor any odd even logic. Increments are determined per street side separately. I suspect there might be something weird with the street geometry that is throwing things off. 

I'll need a link to the actual location to debug.

**Comment by jidanni** [comment]
The location is [GPS 37.955027 N 122.533496 W] 

You can practice on the southeast side of the street. The numbers are 10, 20, 30.

**Comment by simonpoole** [comment]
> The location is [GPS 37.955027 N 122.533496 W]

Those are not decimal degree coordinates.

**Comment by simonpoole** [comment]
> There is neither a hardwired increment nor any odd even logic. Increments are determined per street side separately.

That was not quite correct in its entirety, currently after increments are calculated they are capped to a max of 2. The reason for this is that typically if there is an address 10 and then 20 following it, in nearly all cases that implies that there are addresses missing and -not- that the house number increment is 10.

**Comment by jidanni** [comment]
Ah, but those are just some cultural assumptions.
Newer house numbering makes sure to leave room for growth. Thus as you see in newer areas, instead of 2, 4, 6, there will be 10, 20, 30, or even 20, 40, 60.

The meters per house number is often stated in the Municipal Code.

**Comment by simonpoole** [comment]
Given the lack of space between buildings in both cases I would conider it simply silly; but I've already made an aspect if it tune/ble which should largely eliminate the need to cap the interval.
