### ISSUE TITLE
Conditional restriction

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#1999]
Description:
---

Bei Erstellen einer conditional restriction, zum Beispiel bicycle:conditional = no @ ( 09:00-19:00 ) oder sonst einer conditional restriction, die eines dieser Sonderzeichen enthält  , - > < fehlen jeweils die erforderlichen Klammern. Ist es möglich, dass diese automatisch zugefügt werden?

Device info:
---
<table>
<tr><td>App version</td><td>18.0.5.0</td></tr>
<tr><td>App version code</td><td>2206</td></tr>
<tr><td>Android build version</td><td>T555XXU1CRG1</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NMF26X.T555XXU1CRG1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>gt510lte</td></tr>
<tr><td>Device model</td><td>SM-T555</td></tr>
<tr><td>Device product name</td><td>gt510ltexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/nurdafur"/>nurdafur</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Nsch der Grammatik sind Klammern nur bei einem **;** in der Bedingung notwendig.

**Comment by simonpoole** [comment]
Seems as this has been fixed in osmose.
