### ISSUE TITLE
Broken link to current Vespucci preset

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#2005]
## Vespucci Version
18.1-BETA 2

## Download source
Google Play

## Device (Manufacturer and Model)
Fairphone 4

## Android Version 
11

## Behaviour/Symptoms
When installing the current Vespucci preset by the provided link in the help, it doesn't work as the link leads to a 404

![Screenshot_20221224-101413~2.png](https://user-images.githubusercontent.com/30999326/209429430-53c54952-b199-42b4-90f1-b997c5fc8f40.png)
![Screenshot_20221224-102510~2.png](https://user-images.githubusercontent.com/30999326/209429588-24a21425-1e75-4ffc-95ce-695853e56a79.png)
Broken link: https://github.com/simonpoole/beautified-JOSM-preset/raw/master/gen/vespucci_zip.zip

## Expected Behaviour
A working preset should be installed 😃

## How to recreate
1. Preferences
2. Presets
3. Help
4. Current Vespucci preset
5. Add preset
6. Ok

## Crash dump submitted (no or yes + date)
No

**Comment by Discostu36** [comment]
Maybe this link should be used instead?

https://github.com/simonpoole/beautified-JOSM-preset/releases/latest/download/vespucci_zip.zip

**Comment by simonpoole** [comment]
That link should simply be removed (it likely never did anything reasonable), you should use the one in the list at the end of the page.
