### ISSUE TITLE
Show relation member on map

### ISSUE THREAD

**Issue by frprieto** [MarcusWolschon/osmeditor4android#2006]
When clicking on a relation member, the object preferences can be edited, but I can not find an option to display that object on the map. It would be useful for checking and correcting routes continuity.

![IMG_20221226_094906](https://user-images.githubusercontent.com/48330461/209527646-59a7ce6a-1a91-4f1a-a6e2-8fb5df73db5d.jpg)

**Comment by simonpoole** [comment]
See https://vespucci.io/help/en/18.0.0%20Release%20notes/#property-editor-changes

**Comment by frprieto** [comment]
With the Advanced preference enabled, the map view is on screen with the object selected, so I can zoom and locate it. Thanks!
