### ISSUE TITLE
Object not showing duplicated relation membership

### ISSUE THREAD

**Issue by frprieto** [MarcusWolschon/osmeditor4android#2007]
When an object is member of the same relation twice, only one membership is shown in the Preferences editor

In ID editor we see the 2 entries of the same relation:
![IMG_20221226_135618](https://user-images.githubusercontent.com/48330461/209553207-46c13bb4-d1ef-4931-af7a-d634d601293a.jpg)

In relation members the object is shown twice:
![IMG_20221226_131626](https://user-images.githubusercontent.com/48330461/209548961-202ce0f3-2d70-4f71-bd21-483e8a18698d.jpg)

But in object relations we only see the relation once:
![IMG_20221226_125003](https://user-images.githubusercontent.com/48330461/209549000-871ccd18-577d-4aa7-9a55-c93b0f207d5a.jpg)

**Comment by simonpoole** [comment]
Iirc this an old limitation.
