### ISSUE TITLE
Don't go to nowhere 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2008]
If "Current Position Info" says "No usable location",
then "Go to current location" should refuse to go to it.

(E.g., new phone turned on in basement.)

Yes, it makes an error to the phone's notifications, but the map still flies to nowhere, with no sight of land no matter how much one zooms out. Wait, it seems we are dumped at longitude 180 and the equator.

Anyway, the map shouldn't budge, and the error should just print on the screen, just like it does with "Current Position Info ".

Also please check if the "Go to coordinates..." command still works after we end up in the unknown location. I attempted to go to a coordinate pair but I couldn't. Yes, normally it does work.

**Comment by simonpoole** [comment]
The two functions are different in which sources they (can) use "Current Position Info" only uses and supports GNSS derived location information, the "Go to current location" is more lenient and will use what the best available location source returns (arguably Android should not be returning a location in the scenario you describe).
