### ISSUE TITLE
Measure with ARCore

### ISSUE THREAD

**Issue by westnordost** [MarcusWolschon/osmeditor4android#2010]
<img src="https://user-images.githubusercontent.com/4661658/210075240-818b36e3-0a7c-43d5-8bae-2630a7926ea0.jpg" align="right"/>

 [I implemented this for StreetComplete a while back](https://github.com/streetcomplete/StreetComplete/releases/tag/v41.0) and now outsourced this functionality into an own app which will be released in a week or so on Google Play (I am waiting for some localization to be done first). In the future, StreetComplete will just call this app (like calling the camera to have a photo taken) to achieve the same functionality.

This means that other (OpenStreetMap editor) apps can also implement this functionality with very little effort. The readme in https://github.com/streetcomplete/StreetMeasure explains how to do this. Feel free to close it if you are not interested in adding this functionality or ask for help if you are but confused how to exactly do it.

**Comment by simonpoole** [comment]
Thanks for the heads up. I'll give it a look asap.

I suggested something along such lines way back in 2018 https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2018/Project_Ideas but there were no GSOC takers, and, at least at the time, even on certified phones ARcore was far to unreliable for production use so I never wanted to spend the time, I trust that is better now?

**Comment by westnordost** [comment]
I implemented it 4 years later. According to my tests with a Samsung S10e the precision when compared to a laser measure was up to ~3% off (e.g. 6m street would show as ~5.9m) if measured right*, which is fine. But in any case, StreetComplete sets [`source:width=ARCore`](https://taginfo.openstreetmap.org/tags/source%3Awidth=ARCore) whenever a width was determined by the AR measuring to mark that it may not be precise down to the centimeter and I'd recommend that other editor apps do the same.

\* It is possible to achieve grossly wrong widths too (see https://github.com/streetcomplete/StreetComplete/issues/4655), however: In situations where ARCore presumes the ground to be a bit higher or lower than it actually is. 

This can happen initially when ARCore still scans the surroundings and is not sure yet what's where, but it can also happen as entirely not the fault of ARCore: For example it sets the ground at sidewalk level but the user measures the road till the lower end of the curb - either not being aware of this or thinking it won't make a big difference if the arrow is on top of the curb or below (it's just a few pixels on the screen after all):

![image](https://user-images.githubusercontent.com/4661658/210136573-827212d7-f79b-4a1b-81bc-47123fe3a877.png)

To really make sure that the ground is detected at the correct height, one would need to observe the "measuring tape" from different directions. If it is parallax to the ground, it's a bit above or below. But there is an easy way to not have to worry about this at all.

Since one cannot expect users to be aware of this, I added the following text when one taps the ℹ️ button on the upper right corner:

> ARCore sometimes (initially) presumes the ground to be a bit lower or higher than it actually is. This introduces a measurement error that gets larger the more you tilt your phone towards the horizon>
> **Set each the start- and endpoint while pointing the phone straight down (so that you see the white arrow from above) to completely avoid this issue for horizontal measurements.**
> For vertical measurements, you need to instead check that the startpoint is not parallax to the ground by looking at it from different directions.

**Comment by simonpoole** [comment]
My major concern back then were outright crashes, hangs and 'simply not working'.

BTW Wheelmap had a version of their app that ran on the tango platform to measure entrance widths and slopes. Maybe they would be interested too.

**Comment by westnordost** [comment]
> BTW Wheelmap had a version of their app

Didn't find their repo right now. I only find https://github.com/sozialhelden/wheelmap-android but this has been archived.

**Comment by danieldegroot2** [comment]
> BTW Wheelmap had a version of their app that ran on the tango platform to measure entrance widths and slopes.

See https://github.com/sozialhelden/wheelmap-classic/issues/413

While current wheelmap can be found here:
- https://github.com/sozialhelden/wheelmap-frontend (frontend)
- https://github.com/sozialhelden/accessibility-cloud (backend)

**Comment by westnordost** [comment]
It is now live: https://play.google.com/store/apps/details?id=de.westnordost.streetmeasure

**Comment by westnordost** [comment]
The `MeasureContract.kt` is for copying into your project if you use `ActivityResultContract` (and have kotlin support enabled). If you use this class, you don't need the keys as constants because it is encapsulated in this class anyway, i.e. just use the type-safe `createIntent` method in your code.

If on the other hand you use the "old" method of calling an activity for result via `startActivityForResult` or what this function is called, you need to put in the extras as parameter "by hand" (`intent.putExtra`). Whether you copy over the documented constants from `MeasureActivity` or just use their string values is really up to you.
