### ISSUE TITLE
Prefix language

### ISSUE THREAD

**Issue by Davileci** [MarcusWolschon/osmeditor4android#2011]
[Key:language](https://wiki.openstreetmap.org/Key:language) is a key prefix rather than a simple key. Preset values should be "main" and "yes" rather than iso ones.

**Comment by simonpoole** [comment]
Which preset item are you referring to?

**Comment by Davileci** [comment]
language=af;sq;de;am;ar;hy;as;az;be;bn;bs;bg;my;ca;cs;zh;ko;hr;da;dv;nl;sk;sl;es;et;fo;fi;gd;gl;ka;el;gn;gu;he;hi;hu;is;id;it;ja;kn;ks;kk;km;lo;la;lv;lt;mk;ms;ml;mt;mi;mr;mn;ne;nb;nn;or;fa;pl;pt;pa;rm;ro;ru;sa;sr;tn;sd;si;so;sb;sv;sw;th;tg;ta;tt;te;bo;ts;tr;tk;uk;ur;uz;vi;cy;xh;yi;zu+amenity=language_school

**Comment by simonpoole** [comment]
The tagging (language:xx) documented in the wiki is broken and should not be propagated. 

Note that this would have been a preset issue in any case and should have been opened there.
