### ISSUE TITLE
create todo list from Overpass query

### ISSUE THREAD

**Issue by brunnerpaul** [MarcusWolschon/osmeditor4android#2016]
Would be great if the following was possible:

1. create Overpass query, e.g. [this](https://overpass-turbo.eu/s/1pZU), could be done directly on phone in web browser
2. download the GeoJSON from Overpass
3. load the GeoJSON file in Vespucci (arrows at the bottom-> tasks -> load todos)
4. upon loading, the JSON needs to be adjusted to match the syntax needed for the todo list, as in the example below ([source](https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/androidTest/resources/todos.json))
```
{
   "name":"Name change",
   "todos":[
      {
         "lat":47.5521575,
         "lon":7.5878035,
         "id":"9932d420-2828-4e97-af51-820167597cef",
         "state":"OPEN",
         "osm_ids":{
            "nodes":[
               5341711822
            ]
         }
      },
      {
         "lat":47.5521318,
         "lon":7.5881302,
         "id":"abbcd315-f79a-4165-bb8a-30f58b4a9e72",
         "state":"OPEN",
         "comment":"test comment",
         "osm_ids":{
            "nodes":[
               6372498630
            ]
         }
      }
   ]
}
```
5. start mapping

No need to implement Overpass directly in Vespucci and still have full functionality. What do you think?

**Comment by WNMW** [comment]
That'll be very useful, I'm waiting for this option for years
