### ISSUE TITLE
Split way

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2017]
Description:
---

Bei mir funktioniert die neue Funktion "Zuordnen der history zu einem Segment" nicht. Wenn ich nach dem Auswählen der Schere lange auf den Knoten drücke, an dem ich den Weg trennen will, dann komme ich in den Modus "neu".

Device info:
---
<table>
<tr><td>App version</td><td>18.1.0.0</td></tr>
<tr><td>App version code</td><td>2302</td></tr>
<tr><td>Android build version</td><td>T555XXU1CRG1</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NMF26X.T555XXU1CRG1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>gt510lte</td></tr>
<tr><td>Device model</td><td>SM-T555</td></tr>
<tr><td>Device product name</td><td>gt510ltexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/nurdafur"/>nurdafur</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Ja die neue Funktion beisst sich mit dem "non-simple" Mode, der Konflikt ist vermutlich behebbar aber die Frage ist natürlich wieso du den Mode immer noch verwendest.

**Comment by nurdafur** [comment]
Hallo Simon
Habe den non-simple Mode nun ausgestellt. Ich hab das gar nicht gemerkt, dass es da eine andere Option gibt. Macht der Gewohnheit wahrscheinlich. Nun funktioniert das tatsächlich mit dem Aufspalten. Danke für den Tipp.
