### ISSUE TITLE
Note creation and editing on Android 7.1 doesn't show keyboard

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2018]
Description:
---

Wenn ich eine neue Notitz anlege oder eine bestehende bearbeiten will, dann öffnet sich die Tastatur nicht mehr, wenn ich einen Kommentar eingeben will.

Device info:
---
<table>
<tr><td>App version</td><td>18.1.0.0</td></tr>
<tr><td>App version code</td><td>2302</td></tr>
<tr><td>Android build version</td><td>T555XXU1CRG1</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NMF26X.T555XXU1CRG1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>gt510lte</td></tr>
<tr><td>Device model</td><td>SM-T555</td></tr>
<tr><td>Device product name</td><td>gt510ltexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/nurdafur"/>nurdafur</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Und in das Kommentarfeld klicken hilft nicht?

**Comment by nurdafur** [comment]
Genau, ich klicke ins Kommentarfeld und nichts passiert.
Nur der Abbrechen-knopf funktioniert, wenn ich eine neue Notiz erstellen will.

**Comment by simonpoole** [comment]
Wie ist der Fullscreen Modus eingestellt?

**Comment by nurdafur** [comment]
Der ist auf Automatisch gesetzt. 
Habe kurz alle anderen Optionen durchgetestet. Bei keiner bekomme ich die Tastatur.

**Comment by simonpoole** [comment]
Hast du eine Ahnjng wsnn genau das angefzngrn hat? Noch was zum ausprobieren: andere Tastatur.

**Comment by nurdafur** [comment]
Angefangen hat es direkt nach der Installation der neuen Version.
Eine Andere Tastatur zu verwenden bringt auch nichts.
Ich kann so oft in das Feld klicken wie ich will.

**Comment by simonpoole** [comment]
Also, es scheint ein Android 7.1 spezifisches Problem zu sein. Abklärungen so weit:

S5 Android 6.0 works (needs 2nd click)
Emulator 7.1 doesn't work
S7 Android 8.0 works
Note 8 Android 9.0 works
(and no problems on any higher version)

Die älteste Version auf den wir die automatisierten Tests laufen lassen können is 8, sonst wäre das beim Testen aufgefallen.

**Comment by simonpoole** [comment]
This is a regression caused by https://github.com/MarcusWolschon/osmeditor4android/commit/7e8f90e24c664dce9f07ab1c3b325ee453db37aa
