### ISSUE TITLE
Weird direction preset

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2020]
I don't know what "180 - 180"  etc. ranges are all about. I pushed it and I got 180. So why not just call it "180"?

And some have spaces in them and some don't.

![Screenshot_20230113-150734_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/212258999-7a0beb4d-ecdd-46ee-95e7-7504cf825f36.jpg)

**Comment by simonpoole** [comment]
It is just a mix of predefined values from the preset in the form _actual value_ __-__ _textual description_ (as always) and previously entered/existing values.
The predefined values are

0 - 0°
180 - 180°
270 - 270°

so these are not ranges, and yes 180° is called 180°. One could argue that the values don't actually need a description, but that would be an issue to raise in the preset repo and not here.

**Comment by jidanni** [comment]
(Maybe different fonts should  be used for actual value vs. textual description.)
