### ISSUE TITLE
Re-Tagging site_type zu archaeologicical-site

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2030]
Description:
---

Hallo,
zur Info für die Anpassung:
https://wiki.openstreetmap.org/wiki/Automated_edits/ChillyDL#site_type_to_archaeological_site_implementation

Viele Grüße!

Device info:
---
<table>
<tr><td>App version</td><td>18.1.0.0</td></tr>
<tr><td>App version code</td><td>2302</td></tr>
<tr><td>Android build version</td><td>A320FLXXS9CTK2</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>R16NW.A320FLXXS9CTK2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a3y17lte</td></tr>
<tr><td>Device model</td><td>SM-A320FL</td></tr>
<tr><td>Device product name</td><td>a3y17ltexc</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7870</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/ChillyDL"/>ChillyDL</A></td></tr>
</table>

**Comment by simonpoole** [comment]
See https://github.com/simonpoole/beautified-JOSM-preset/issues/350
