### ISSUE TITLE
Go back one menu level

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2033]
Here we are deep in the tools menu for example:

![Screenshot_20230121-093114_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213832897-fb5b7f58-aee3-46ed-9049-1415df1ef09b.jpg)

Let's say we want to go one step back to this view:

![Screenshot_20230121-093209_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213832288-9279d9fc-b067-46d5-97c8-3205f221f43e.jpg)

Well the only thing we could do is hit the cellphone's back button, which will throw us  out of the entire tools menu  completely!

So maybe at the bottom of each of these menus there should be an additional Back button.

**Comment by simonpoole** [comment]
Android doesn't provide a way to do this.

**Comment by jidanni** [comment]
All I know is I could climb back one level in Preferences by using this Arrow we see at the upper left:
![Screenshot_20230122-135358_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213902723-3df2f119-1c80-4554-a0cb-a20144ff676c.jpg)
