### ISSUE TITLE
Regression: align background mode doesn't lockout "+" button

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2034]
Here we see the words "tap the next node position."
![Screenshot_20230121-095951_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213836824-e0346da8-acce-460d-8fe1-db43067124d9.jpg)

But in Help we see instructions:

> In the "Align background" screen you can simply drag the background to the desired position, overlays and the OpenStreetMap data will remain stationary. 

So it seems the wording at the top of the screen needs to be changed.

**Comment by simonpoole** [comment]
It seems as if there is currently a regression in changing to the align background mode that leaves the "+" button active and doesn't completely clean out action mode titles. Workaround for now: don't use the "+" button while in the align background mode.
