### ISSUE TITLE
Exiting Align Background dialog 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2035]
We have adjusted the background to where we want it and now it's time to leave the screen:

![Screenshot_20230121-095951_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213839672-2acfc06d-6013-4af5-bc21-21a904b93d93.jpg)

There is an arrow at the upper left, but we are not sure if that will throw away our carefully aligned changes or not.

We check the three dot menu and there is "Apply (all zoom layers)", but it applies to all layers, but we just want to apply it to this one layer.

We check Help,

>Exiting the screen with "Done" will store the offset for this zoom level.

Okay, after experimenting I conclude the arrow at the upper left must be the Done button. 
Further experiments show that hitting a cell phone's back button is equivalent to hitting the arrow button.

How about instead a big green check mark somewhere we can tap.

Then the back function should throw away the changes properly.

**Comment by simonpoole** [comment]
This currently uses the standard Android "Exit Action Mode" semantics.

**Comment by simonpoole** [comment]
Replaced by https://github.com/MarcusWolschon/osmeditor4android/issues/2049
