### ISSUE TITLE
Align background Reset menu item

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2036]
Help says
>RESET - reset the offset to what is was before the "Align background" mode was started

But as I drag the background around the screen the numbers in the upper left change. But when I hit the Reset menu item  nothing happens. The numbers stay the same. The imagery doesn't jerk back to place.

**Comment by simonpoole** [comment]
Works for me.

**Comment by simonpoole** [comment]
Seems as if the issue might be triggered by starting the align mode multiple times.
