### ISSUE TITLE
Mention Undo later

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2040]
The first thing mentioned on this Help page is Undo:
- Way selected
- - Actions
- - - Undo

Perhaps the page could be reordered, putting the more common items up at the top, and Undo near the bottom.

It's just like when we start discussing marriage we don't start off with divorce. We leave that for the end.

**Comment by simonpoole** [comment]
The documentation consistently lists the actions from left to right, top to bottom as they appear on the screen (in RTL locales), ordering them any other way is going to be rather confusing (not to mention is that the Undo button is the one action that is essentially always shown).
