### ISSUE TITLE
Can differentiate ambiguous selector

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2041]
Fot exact ties like
![Screenshot_20230121-130500_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213844522-2e5b9fd1-100d-4c59-8470-caf68b21c4b5.jpg)
perhaps add the words north, south, east, west, or top, bottom, left, right, in parentheses.

**Comment by simonpoole** [comment]
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1938
