### ISSUE TITLE
Shortcut when there is only one multi-select item

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2042]
Here we are in multi-select mode. We now have gone down to having only one item, a way,  selected:
![Screenshot_20230121-131921_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213845108-6bc0b221-bb4f-4a81-87bf-e212c74bb00b.jpg)

At this point several additional menu choices could be available,
![Screenshot_20230121-131938_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213844986-9c6dcc81-2eee-43f0-9493-6c449661a678.jpg)

But we must first get out of multi-select mode, and then  reselect that way again if we want to see those additional choices.

So maybe remove that formality. Recognize that we just have one way selected and then offer the operations that can be done on that way, in addition to the other menu items.

It's like we're in the candy store, and we see the candy bar on the shelf. Well the owner doesn't require us to go out the door and come back in again before we can buy it.

(Note, these are all just long-term feature requests that I have submitted. It doesn't matter if they take several years to get to. I just don't want let them slip away by putting them in some private list that I would forget about.)

**Comment by simonpoole** [comment]
The shortcut here is to simply deselect the remaining selected item and then select it again. This is fast (two clicks, or two clicks and a menu selection) and doesn't involve overloading an interaction.
