### ISSUE TITLE
Add Cancel to feature chooser 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2044]
This has a convenient Cancel choice:
![Screenshot_20230122-090538_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213896013-e49fa2a6-dbb5-4408-b57b-258240ac1d66.jpg)

But this "leaves us in the lurch":
![Screenshot_20230122-090556_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213896035-33e5423d-25d4-4257-b954-c02d24b0e152.jpg)

It would be nicer if it also had a Cancel button.

We are forced to try the cellphone's Back button.

(Seen here:)
![Screenshot_20230122-090547_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/213896058-8013fa6d-30c6-4f8b-a0f5-422357ef58f0.jpg)

**Comment by simonpoole** [comment]
Just tap outside of the modal.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/issues/1235
