### ISSUE TITLE
Recorded GPX-track disappears after closing app

### ISSUE THREAD

**Issue by soshial** [MarcusWolschon/osmeditor4android#2051]
## Vespucci Version
Vespucci 18.1.0
Flavor: current
Target SDK: 31
Maximum avaliable memory 536870912
Total memory used 54843960
Tile Cache MAPNIK usage Size 15990784 of maximum 67108864 #entries 61
State file size 332059 last changed 2023-01-23 16:56:26
Bug state file size 1766 last changed 2023-01-23 16:56:26
Relations (current/API): 20/0
Ways (current/API): 120/0
Nodes (current/Waynodes/API): 5538/5510/0
Available location providers
passive enabled true
network enabled true
fused enabled true
gps enabled true
Configured layers
IMAGERY 0 IMAGERY true MAPNIK
SCALE 1 SCALE true null
OSMDATA 2 OSMDATA true null
TASKS 3 TASKS true null

## Device (Manufacturer and Model)
Samsung Galaxy S22

## Android Version 
13

## Behaviour/Symptoms
GPX-tracks disappear after closing app

## Expected Behaviour
The layer should be visible after reopening the app.

## How to recreate
1. Record track for several minutes (The recording is seen on a map as blue track, the track is present in layers' menu)
2. Pause recording
3. Close/kill app.
4. No GPX track layer in the layers' menu; no track see on the map.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/commit/acc30a8d161dad2de81e525e42a8656fd84b56a8 if you believe that this is actually a fixable issue and not standard Android behaviour please supply the required information that you left away.

**Comment by soshial** [comment]
@simonpoole I am sorry for that. I updated the description.

**Comment by simonpoole** [comment]
Close/kill app is unclear are you exiting the app with the back button, or doing something else?

**Comment by soshial** [comment]
Either exiting with a back button, ir miniming and then killing by swiping
upward.

**Comment by simonpoole** [comment]
> Either exiting with a back button, or minimizing and then killing by swiping upward.

As pointed out in the commit I linked, killing the process does exactly that and there is no guarantee that the app and in particular the service doing the recording will be notified in any way.

**Comment by soshial** [comment]
As described in the instruction, first pause the recording, then close the app.
Why wouldn't recording be saved then?

**Comment by simonpoole** [comment]
Just to check one more thing, you did press "Resume GPX track" after restarting? That will recreate the recording GPX layer and should show the track just as you left of (it could be argued that the layer should be automatically loaded, but currently that isn't the case).

**Comment by soshial** [comment]
So that's how to retrieve it??? I thought I lost my recorded track forever!

**Comment by simonpoole** [comment]
The reason for the the admittedly slightly surprising behaviour is that the track data is managed by the recording service. When the app starts up without the service already running there is a race condition between layer configuration and the service starting, this wouldn't be an issue except that if the service isn't running layer configuration removes the layer.

**Comment by soshial** [comment]
Wow, thanks! This would definitely improve GPX recording experience.
