### ISSUE TITLE
Recognize .HEIC

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2056]
The photo layer ignores .heic files, even if they contain exif location data just like .jpgs.

**Comment by simonpoole** [comment]
What are HEIC files?

**Comment by jidanni** [comment]
https://www.adobe.com/creativecloud/file-types/image/comparison/heic-vs-jpeg.html .
Saves space here on Samsung stock camera.

Currently sharing one with Vespucci gives error: photo content not found... Must convert to jpg first.

**Comment by simonpoole** [comment]
You'll need to provide a sample for testing. Prior to Android 9 there was no native support for such images, and it needs to be seen if all the necessary libraries support the format.

**Comment by simonpoole** [comment]
Currently doesn't seem to be fully supported in https://github.com/davemorrissey/subsampling-scale-image-view See https://github.com/davemorrissey/subsampling-scale-image-view/issues/559

**Comment by jidanni** [comment]
```
wget https://upload.wikimedia.org/wikipedia/commons/2/2d/Chunu_Bay%2C_Kanaga_Island%2C_Alaska.jpg
convert Chunu_Bay,_Kanaga_Island,_Alaska.jpg C.heic #imagemagick
exiftool C.heic #shows exif coordinates
```

**Comment by simonpoole** [comment]
You can append it to the issue.

**Comment by jidanni** [comment]
I am on a little modem line and can't upload big images.

**Comment by simonpoole** [comment]
There's no hurry.

**Comment by jidanni** [comment]
[h.heic.gz](https://github.com/MarcusWolschon/osmeditor4android/files/10507831/h.heic.gz)
You'll need to unzip it.

**Comment by simonpoole** [comment]
![h heic](https://user-images.githubusercontent.com/1011860/214814572-82f839da-b296-4bdc-bc02-afec7f7adbeb.jpg)
