### ISSUE TITLE
Can't delete scanned in pictures

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2057]
Put some jpgs in Vespucci/pictures. Okay now back in the app enable the photo layer, which scans in pictures. 

Press delete on one of those pictures that we just scanned in. Nothing happens. We're still looking at the picture.
Android 12.

Delete seems to only work with pictures we added using the camera app.

**Comment by simonpoole** [comment]
This is expected behaviour, the app does not own the images and will not be able to delete them since something like Android 8.

**Comment by jidanni** [comment]
Okay. The prompt shouldn't say delete permanently. Just to say remove from Vespucci.

And then it should take it off the screen, instead of just having it sit there like we didn't ask it to delete anything.

I suppose it thinks it owns the file, but that was many Android versions ago.

**Comment by simonpoole** [comment]
> Okay. The prompt shouldn't say delete permanently. Just say remove from Vespucci.

We don't know that it wont be deleted permanently.

> And then it should take it off the screen, instead of just having it sit there like we didn't ask it to delete anything.

That is what it tries to do, but the next indexing will re-find the image.

 You can try indexing the photos from the MediaStore that may or may not work better, see http://vespucci.io/help/en/17.1.0%20Release%20notes/#include-androids-mediastore-in-scan-for-images

**Comment by jidanni** [comment]
Media store? That's 2000 images in my phone! Thanks but no thanks.

Anyway, this issue will need more Android 12+ users to test it to see if they also see weird things.
