### ISSUE TITLE
Show individual tile cache size

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2062]
Help says:
> Flush tile cache Flush the on device cache for this layer.

> Info Display information on the currently selected imagery.

Perhaps Info could show the size of  the cache mentioned in  Flush  above.

Perhaps even show its disk location too.

**Comment by jidanni** [comment]
For some layers one couldn't find some information in Debug
>Tile Cache REDWOODS usage Size 66846720 of maximum 67108864 #entries 255

But that's not the same as disk usage...

**Comment by simonpoole** [comment]
We use one common sqlite database as a cache for all tile based layers, there is no way to associate a specific amount of disk usage nor are there individual files per layer.
