### ISSUE TITLE
Document Save, vs. Save and set

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2063]
Help says:
> Custom layers

> Manage custom imagery layers not included in the standard configuration. This supports configuring both remote tile..

Okay, but the actual dialogue has two choices
- save, and 
- save and set. 

Their difference should be documented. We have no idea which one to push.

Oh I see. The latter means save and select.

Maybe I should make a PR to the documents.

I see, it adds an additional layer to the bottom of the layer stack. I thought it might select the imagery instead of the current imagery. Well I'm not qualified to write any documentation about this. Somebody else will have to do it. Also I had selected that it was a overlay layer. So maybe that's why it ended up where it did. Anyway there's so a whole lot that needs to be explained about that "set" word.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/144019b5e8087c9cc69b217021ea8be044a88fd5
