### ISSUE TITLE
Support GetCapabilities

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2064]
The bounding box is already listed in, for example, https://mapwarper.net/maps/wms/68850?request=GetCapabilities&service=WMS&version=1.1.1

That way the user wouldn't have to fill out the bounding box manually, or be faced with a worldwide bounding box.

Currently one can enter the above URL for Custom Imagery, but it will only get errors.

**Comment by simonpoole** [comment]
See http://vespucci.io/help/en/Main%20map%20display/#layer-control "Add imagery from WMS"

**Comment by jidanni** [comment]
Yes, on https://github.com/MarcusWolschon/osmeditor4android/blob/master/documentation/docs/help/en/Preferences.md#custom-layers there is
```
WMS server specific place holders

{proj} EPSG projection number, one of 3857, 900913 and 4326.
{width} image width.
{height} image height.
{bbox} WMS bounding box.
```
but no support for the much easier URLs like
https://mapwarper.net/maps/wms/68850?request=GetCapabilities&service=WMS&version=1.1.1
which have all the detail in the XML file.

**Comment by simonpoole** [comment]
Because that document was written before the support for WMS endpoints was added.

**Comment by jidanni** [comment]
Well all I know is on
https://mapwarper.net/maps/68850#Export_tab there is
> WMS: WMS Capabilities URL (for JOSM OpenStreetMap Editor )

**Comment by simonpoole** [comment]
> Well all I know is on https://mapwarper.net/maps/68850#Export_tab there is
> 
> > WMS: WMS Capabilities URL (for JOSM OpenStreetMap Editor )

And what do we have to do with that? Nothing.

**Comment by jidanni** [comment]
Pretend it said
> WMS: WMS Capabilities URL (for  OpenStreetMap Editors)
