### ISSUE TITLE
OSM Notes, Mapdust, Keepright support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#207]
```
Implement quality assurance / bag reporting services support please. That are:
https://wiki.openstreetmap.org/wiki/OSM_Notes_API
https://wiki.openstreetmap.org/wiki/MapDust
https://wiki.openstreetmap.org/wiki/Keep_Right
https://wiki.openstreetmap.org/wiki/Osmose
```

Original issue reported on code.google.com by `ddifran...@gmail.com` on 17 Feb 2014 at 4:22
* Blocked on: #228

**Comment by simonpoole** [comment]
Will be done in the new notes code.

**Comment by simonpoole** [comment]
0.9.7 has greatly improved Notes support with support for Osmose thrown in

https://github.com/MarcusWolschon/osmeditor4android/commit/cd3564b57d6af8f1a03afe35427deea2ca0aef64
