### ISSUE TITLE
Just call the preference: menu icons location

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2071]
~~When looking at a photo, the screen is split into two parts. If we pull up on the boundary, this causes the strip of icons to now be lodged into the top of the screen.~~

~~And indeed, that is where they will stay forever. Even if one discards the photo layer.~~

![Screenshot_20230127-111930_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215003627-3514beba-27f6-4a86-ac15-f8f706fedcce.jpg)

~~Sure, we can view a photo again. The screen gets split but no amount of pulling it up or down, will change the new place where the icon strip lives.~~

**Comment by jidanni** [comment]
Oh. I had changed this preference:

>Show the menu buttons at the bottom of the screen. Default: on. You need to restart the app for changes to this setting to take effect.

Disable translations

**Comment by jidanni** [comment]
The problem is, looking in Preferences, one would hardly think that this had anything to do with menu bar location:
![Screenshot_20230127-113512_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215004634-df1018e0-0212-4056-9a03-fee384c735de.jpg)

**Comment by jidanni** [comment]
So in preferences, there should be some words about menu icon location.

**Comment by simonpoole** [comment]
Action bar is Android for the menu bar in action modes, and ```When looking at a photo, the screen is split into two parts.``` is Androids multi-window mode.
