### ISSUE TITLE
app freeze

### ISSUE THREAD

**Issue by johndh** [MarcusWolschon/osmeditor4android#2074]
## Vespucci Version

18.1.1
## Download source

F-Droid 
## Device (Manufacturer and Model)

Motorola One 5G Ace
## Android Version 

11

## Behaviour/Symptoms

App freezes, when reopening it will fail to render the background and most of the objects and remain frozen
## Expected Behaviour

Some error message and indication of the solution
## How to recreate

No idea
## Crash dump submitted (no or yes + date)

No
## Any other potentially relevant information

The most recent time it did it was when I uploaded about 50 changes, mostly new houses and addresses
![Screenshot_20230127-122343](https://user-images.githubusercontent.com/692397/215174659-3278d8f5-51a3-4569-8d26-4bbd601234ab.png)
![Screenshot_20230127-122421](https://user-images.githubusercontent.com/692397/215174667-326eaeeb-c908-4d95-9d97-d5fbe9ddc910.png)

The only way I've found to resolve it is to clear all the app data. Clearing the cache doesn't fix it. I checked to make sure my device isn't running out of space, and it's nowhere close.

**Comment by simonpoole** [comment]
Unluckily this going to be difficult to disect. If it is happening in roughly the same location repeatedly then there might be a specific data issue in the OSM data there that we don't catch.

In any case before doing anything else I would suggest re-instoring from f-droid, it isn't totally unheard of Android to mangle an install now and then.

If that doesn't help, then hooking the phone per usb up to a desktop/laptop for debugging is going to be the only resort.

It should be noted that we don't control or test the builds produced by f-droid.

**Comment by simonpoole** [comment]
> App freezes, when reopening it will fail to render the background and most of the objects and remain frozen

Just a follow up: you could try, immediately after restarting try to send in a crash dump via the "Debug" menu item, it contains a fair bit of log, which just might give a hint what is going on.

**Comment by johndh** [comment]
It only happens rarely, but in various locations. I'm not able to access any of the menus when restarting. I can't select anything at all, until I delete the app data. It has happened with multiple versions, so I doubt it's the specific installation.

**Comment by simonpoole** [comment]
Anything else special about your installation? SD-card for the app?

**Comment by johndh** [comment]
Nothing special that I'm aware of, no SD card, and over 70GB available. I had just uploaded some changes immediately before it happened. Thinking back, that might have been the case the last time it happened too, but I couldn't swear to it.

**Comment by simonpoole** [comment]
When you have time could you manually send a crash dump (Debug screen, button at the bottom)? Pls reference this issue. It is unlikely, but maybe there's something special that we haven't thought about wrt your setup. 

One further thing to check is how large the tile cache is (unlikely that it is an issue, but better check), see http://vespucci.io/tutorials/faq/#other-tile-database-related-issues

In case it isn't clear "freezing" isn't normal behaviour, normally we should at least get an ANR (app not responding) crash report from google in such circumstances, but as I mentioned I haven't found any for your device type (however we only get then 60 days back).

**Comment by johndh** [comment]
I've sent the debug info.

**Comment by simonpoole** [comment]
> I've sent the debug info.

Thanks. Nothing noteworthy though. IMHO the best way forward would be to have a look at an ANR dump, not sure why I couldn't find one from you, but if you can alert us when you've just hand the issue it would be easier to check.

See also https://developer.android.com/topic/performance/vitals/anr

**Comment by simonpoole** [comment]
@johndh are you still having this issue?

**Comment by johndh** [comment]
Haven't noticed it in a long time, so I'm assuming it's resolved.

**Comment by simonpoole** [comment]
OK, closing, you can always reopen if necessary.
