### ISSUE TITLE
Go to first/last node of closed way

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2084]
It is very easy to find the beginning and ends of open ways. But to do the same for closed ways, looking in the menu, we are out of luck:

![Screenshot_20230131_055227_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215610462-96fcb5f0-fa73-4adc-8212-d12861f63822.jpg)

The best we can do is tap each node and see which ones are the highest and lowest numbered:

![Screenshot_20230131_055149_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215611038-81a3f4b8-031b-40a9-8bdf-56aa685a0cfa.jpg)

Normally we have a full grasp of the topology. Alas not  in this case.

So perhaps have an  additional menu item: go to first/last node. Or call it go to loop joining node.

**Comment by simonpoole** [comment]
> But to do the same for closed ways

Why would you want to do that for closed ways? There isn't really a semantic difference between the individual nodes once you've closed the way.

**Comment by jidanni** [comment]
- e.g., benches need open ways to not cause an warning, so one might want to pick the "most efficient spot" to open the way.
- Or one oops... closed a way recently. And now wants to open it at the same place, which is not in the undo list by that time.
-  In general, to have more precise grasp of the topology than more mundane editors.

**Comment by simonpoole** [comment]
It would seem that you simply want a function to "open" a closed way at one of its nodes, and not what you are asking for in this issue.

**Comment by jidanni** [comment]
I was just wanting more data exploring functionality. But okay, it's not that important.
