### ISSUE TITLE
Long line waypoint name difficulties

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2085]
Often one makes long comments into the 'voice to text' of their GPX tracker.

There are several problems ensuing.

Here when the node moves off the screen the entire line will also disappear even though we haven't read it to the very end yet. 
![Screenshot_20230131_053957_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215613236-d9130a98-6724-4e28-9070-ec25bcedeb99.jpg)

In other words we pan to read the line to the end but because the node  that it is based on now is off the screen the entire line disappears before we are able to finish reading it.

So instead we need to tap the node and read its info box as a work around.

Another problem is when two nodes are at the same horizontal level their letters will overwrite:

![Screenshot_20230131_052711_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215614133-24209480-6944-48a6-9fc2-d7a09e74b6f7.jpg)

**Comment by simonpoole** [comment]
The value used as a label should naturally be suitable for use as a label. There is nothing that we can do that would fix using unsuitable values, line wrapping would simply create the same issue vertically.
