### ISSUE TITLE
Label font size doesn't work

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2087]
I tested changing this font size:

![Screenshot_20230131_022115_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215617467-d48344e0-697e-4664-b3c0-4146320ed93d.jpg)

My results are: there is only one font size: no matter what number you choose, the size of the font of the label on the screen doesn't change. 

Except if you make the font size  number as large as it can go. Then the font disappears entirely.

**Comment by simonpoole** [comment]
That isn't the label font size it is the minimum zoom from on the label will be displayed, aka default setting 18: labels will be shown from level 18 on.
