### ISSUE TITLE
No playback when adding layer from GPX file

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2092]
Today I tested using

- Add layer from GPX file, then
-  Start playback. 

I found no playback ensued.

![Screenshot_20230131_030646_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215624709-6ea73730-6e20-44b1-b52f-92bfafad0566.jpg)

All I know is I had to remember to push Stop Playback later otherwise I feared that something was going on that I could not see, using up CPU cycles.

I was using tracks made by
https://play.google.com/store/apps/details?id=net.osmtracker , with plenty of waypoints in them.

**Comment by simonpoole** [comment]
Currently you have to manually turn on following the GPS/GNSS position.
