### ISSUE TITLE
Thick lines ambiguous

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2094]
Which nodes are on the line? It is super hard to tell:

![Screenshot_20230131_033400_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215626371-8875343f-b3fb-4ec8-9b83-39ffdb13dcc0.jpg)
One has to change the style to tell:![Screenshot_20230131_033430_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215626497-de8f56ea-2bb3-43db-a7fc-03709acb0b15.jpg)

So it turns out the top edge of that thick line in the first image is where the line really is!

The bottom node there, although it appears equally probable to be the line,  turns out not to be on the line at all.

So, if thick lines are to be used, they still need a bonus stripe, to show where they really are. No matter if it's some favorite edge, or right down the middle.

More worrisome images:
![Screenshot_20230131_032757_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215627523-62481e74-2410-4bc0-990d-e859551e9766.jpg)

![Screenshot_20230131_032719_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215627538-611e0155-e779-42fe-9b67-cc9f538217d6.jpg)

In such cases the only way to see if a point is on the line is to look in the menus to see if join vs. unjoin is offered.

**Comment by simonpoole** [comment]
> Which nodes are on the line? It is super hard to tell:

A) you are selecting the line in the 1st image, before you selected it the situation was completely clear.
B) nodes that are near together are, surprise, near together, and yes there is nothing in OSM stopping them from being in ambiguous positions
C) you are free to create your own data style if you are unhappy with the default ones

**Comment by jidanni** [comment]
I see. In image 3 the selected node is exactly on the halfway point of the top line,
vs. slightly off the side of the bottom line for the selected node in image 4.
So one needs to look closely...
