### ISSUE TITLE
Direction not considered on way merge

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2099]
Hear no warning is given that we are about to destroy the direction of one of the ways.
![Screenshot_20230201_133513_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215960958-cde117f5-01ce-4048-9537-2e1c7104b8c6.jpg)

![Screenshot_20230201_133522_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215961003-dccfd08d-d798-42a1-bda9-e78fb7f9f099.jpg)
Nor are any rules documented about what would happen in such cases:
>Merge
> Join the selected way with one that it shares a node with resulting in a single way. This option will only be available if the ways have compatible tags and relation memberships.

For instance, you might document: if the ways have incompatible directions, one will be arbitrarily chosen.

P.S., this item is called Join in the menus, but Merge in The Help file.

**Comment by simonpoole** [comment]
We only "warn" if there are tags on one of the ways that need to be reversed, if there aren't any, there is nothing "destroyed" and the direction of the ways in inconsequential.
