### ISSUE TITLE
Toggle empty tags back off after Apply best preset with optional tags

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2100]
This is great:
> Apply best preset with optional tags

> Will locate the best matching preset to the existing tags and apply the preset adding further suggested / optional fields.

Except that after we are finished filling in a few of the optional tags we might want to get rid of the ones we didn't fill in so they don't clutter the view. In this case perhaps a second tap of this button should clean up the empty ones we have not filled in.

**Comment by HolgerJeromin** [comment]
> Except that after we are finished filling in a few of the optional tags we might want to get rid of the ones we didn't fill in so they don't clutter the view.

Reopen the dialog...
