### ISSUE TITLE
Be sure to mention the object node

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2101]
Here we see helpful messages, but they only mention one node number, the node we have selected.

It would be very helpful if they mentioned both node numbers. The one that we have selected, and then the one that it says that we should connect to.

I mean, we already know the node we have selected. We want to know the other node it is talking about.

That way we could be sure if it's talking about the other pink node, or in fact each node has a different node right underneath it.

![Screenshot_20230201_162839_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215991466-5269933a-ed83-412f-b130-caa4f76dff8f.jpg)

![Screenshot_20230201_162555_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215991524-4a7ea55e-da9c-4f98-a742-95f6ca1398d6.jpg)

Yes, we check the menu and there's only  unjoin, no join.

![Screenshot_20230201_162626_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215991876-1d0e98d1-aa68-4592-8171-66d6b0395699.jpg)

**Comment by jidanni** [comment]
Okay reading the message again it says 'element'. So it seems that both of these notes in pink coincidentally both have the same disease.

So the message is not at all telling us to connect these two pink notes together. It's instead telling us to that there's something else we need to connect to. However there's no number of what that item is so we can't be sure. Therefore it would be great if that message just simply said the number of the item that it wants us to connect to also. Thank you.

**Comment by jidanni** [comment]
Okay, there is an experiment we can do: simply delete one of the nodes and then undo it.

Okay the moment I deleted it both pink dots disappeared. And upon undoing the deletion everything looks good: no more pink dots. So it's it was a temporary condition.

So what did we learn today? We learned that it would be great if both numbers appeared in the message. Thanks.

**Comment by simonpoole** [comment]
Besides the fact that you don't know the ids of any other objects at this point so the information wouldn't be helpful to start with, and that it could be multiple objects. Calculating this is already very expensive and to make any sense at all the message would have to be re-toasted every time the candidate other node changed, you wouldn't actually want that.

**Comment by jidanni** [comment]
Wait I found another lone pink dot.
![Screenshot_20230201_164812_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/215995052-ea60392c-84a0-41c4-a52f-198ab373f481.jpg)

It isn't clear which node it wants me to connect to. Does it want me to connect to the bench? Or the farther away path.

Simply revealing what number it is talking about would go a long way too clearing up such mysteries.

**Comment by simonpoole** [comment]
http://vespucci.io/help/en/Main%20map%20display/#highlighting-of-data-issues
http://vespucci.io/help/en/Preferences/#enabled-validations

**Comment by jidanni** [comment]
> unconnected highway end nodes, if the end nodes a near to a highway object that they could be connected to, the node is highlighted
Yes, but if it's near two of them it would be good to show the number of which one of the two of them it means. And in fact it could show the number all the time, even better.
