### ISSUE TITLE
Create OSM objects out of tracks

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2105]
I was just thinking, Vespucci can create OSM objects out of waypoints. Well why not also out of tracks?

![Screenshot_20230203_062642_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/216472177-4c358c76-58bb-4898-8274-d9f81dfff78b.jpg)

I mean we don't have to make them by hand anymore if we already happy with them.

Thus creating this could be automated:
![Screenshot_20230203_063356_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/216472412-72726d86-360c-40ee-ba2e-fb16ab342a7a.jpg)

I am just saying have the following also work on entire tracks themselves:
![20230203_071832.jpg](https://user-images.githubusercontent.com/1230959/216472965-6a1a4812-2914-405c-8c33-80b61b1a4845.jpg)

I mean we had about 15 track points. And we ended up adding about 15 dots (nodes) on the map. Well if  we just had the original trackpoints become the dots, that would even be more accurate than our approximations with our fat fingers. Sure it's not going to be perfect every time but it would save some work. We can always go along and stretch (adjust node positions) the non-perfect spots later.

**Comment by HolgerJeromin** [comment]
This would be horrible data to add in osm. 
Creating ways should be done with far less well placed points.

**Comment by jidanni** [comment]
I was just thinking if we tune our tracker just right so that we are making trackpoints at about the same spacing we would with our mouse, and if we had a good GPS, then for e.g., tracks through jungle where no air imagery was possible (not even in winter) then we would have tracks just as good as we could make with our wrist.
