### ISSUE TITLE
Cannot Cut, and then Paste  Multiple Times

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2108]
Usually I use Copy, and then I can choose Paste Multiple Times. 

But today I tried Cut, and all I could do is Paste Object. No Multiple Times!

![Screenshot_20230203_171205_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/216560961-68e68333-fee3-4a94-8e25-60710b1bf1d2.jpg)

The item in question was a tree.

**Comment by simonpoole** [comment]
Copy makes a copy, cut uses and pastes the original object, so obviously you are expecting something wrong.
