### ISSUE TITLE
Tag name only shows up in redo list

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2109]
It's not fair. We have to move something from the undo list into the redo list to finally reveal what the tag name was.

Why can't the tag name be visible in both lists?

![Screenshot_20230203_183639_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/216580360-5d6529a7-ccbc-4454-81c8-350dcaed95f3.jpg)

![Screenshot_20230203_183714_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/216581584-5c8dadb3-33d4-4fd0-9cf6-c89354c017d5.jpg)

**Comment by simonpoole** [comment]
Because the undo state of the node doesn't have tags.
