### ISSUE TITLE
create osm object from preset search same as create osm object

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2113]
These two undocumented functions appear to do exactly the same thing.
![Screenshot_20230205_183825_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/216814441-5391df5f-8893-46ae-b2e1-59a64053cc10.jpg)
I stepped through them and I couldn't find any difference at all in what they do. If there's a difference it's probably only in the source code.

**Comment by simonpoole** [comment]
Create from preset search will search in the presets if it can find a matching preset. If there is none, yes then it doesn't differ from the other option.

**Comment by jidanni** [comment]
I am trying to find a place to document this difference.
I think that place might be somewhere on
https://github.com/MarcusWolschon/osmeditor4android/blob/master/documentation/docs/help/en/Main%20map%20display.md
