### ISSUE TITLE
Multipolygon members not sorted

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#2116]
Here is a multipolygon where Vespucci can't order the members: https://www.openstreetmap.org/relation/11541886
This can only be done manually.

## Vespucci Version
18.1.1.0

## Download source
google play store

## Device (Manufacturer and Model)
Redmi Note 10 Pro

## Android Version 
12

**Comment by simonpoole** [comment]
This is currently expected behaviour as we only use a trivial sorting algorithm here and not the full multi-polygon ring building code (as for example we do for data rendering).
