### ISSUE TITLE
Maxar imagery doesn't work

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#2117]
Maxar imagery does not work. Maybe related JOSM issues:

https://josm.openstreetmap.de/ticket/22711
https://josm.openstreetmap.de/ticket/22719

I don't know if this is something that has to be fixed at Vespucci's side (do you have a separate API key from JOSM's?) so I am also mentioning it here.

## Vespucci Version
18.1.1

## Download source
GPlay

## Device (Manufacturer and Model)
Fairphone 4

## Android Version 
Android 12

## Behaviour/Symptoms
No imagery in Maxar Standard or Maxar Premium layer 

## Expected Behaviour
Imagery 😃

## How to recreate
Choose Maxar background imagery 

## Crash dump submitted (no or yes + date)
Yes, today, 21:14 CET

**Comment by simonpoole** [comment]
The API key is not the same as the JOSM one but unluckily it seems it has been cycled too  

With other words you can expect the layer not to work till we can get hold of somebody from Maxar (if the last time this happened is anything to go by this will take months).

**Comment by stoecker** [comment]
Contact me by mail and I'll point you to the right place.

**Comment by simonpoole** [comment]
@stoecker thanks for the offer, sorry to respond so late, I was on vacation. Seems as if Maxar has provided us with a key in the mean time, just need to check if it works irl.

**Comment by simonpoole** [comment]
New key checked and it works. This will be available in the next maintenance release which will likely be out next week.
