### ISSUE TITLE
place=square German translation incorrect

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2118]
Description:
---

The preset for place=square is named "rechtwinklig machen", which is incorrect.

The translation for "to square" (the verb) is indeed "rechtwinklig machen". So the action of squaring an area has the correct label.

The translation for "square" (noun) however is "Platz", so the preset is named after the verb, but should be named after the noun.

Device info:
---
<table>
<tr><td>App version</td><td>18.1.1.0</td></tr>
<tr><td>App version code</td><td>2303</td></tr>
<tr><td>Android build version</td><td>2010292059</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>ONEPLUS A5010_43_201029</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus5T</td></tr>
<tr><td>Device model</td><td>ONEPLUS A5010</td></tr>
<tr><td>Device product name</td><td>OnePlus5T</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/phoque"/>phoque</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Note this is a preset issue (missing translation context).
