### ISSUE TITLE
No Data Style radio button pre-selected

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2119]
Today I looked in preferences and I saw that I had 'color round nodes' selected. But then when I tapped on that preference this menu popped up with no radio button selected. It should have the 'color round nodes' radio button pre-selected. Maybe for this cell phone this is the first time I visited it.
![Screenshot_20230209-212733.jpg](https://user-images.githubusercontent.com/1230959/217826615-9b611233-1c63-4ada-84d3-f1e4aa3e9afa.jpg)

Yes, if I finally select the radio button then at least that choice is then remembered. I'm just saying the first time you see this menu none of the radio buttons are selected. One of them should because in the parent menu there is a choice already made.

**Comment by simonpoole** [comment]
This seems to occur when the previously selected style doesn't exist any more.
