### ISSUE TITLE
Holding on the map produces do-nothing box

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2120]
With node or way selected, hold down on some other part of the screen.

After a while, the names of the items underneath your finger will appear:

![Screenshot_20230209-213831.jpg](https://user-images.githubusercontent.com/1230959/217830792-34503915-fb0c-4ebb-b23a-0c5388b65601.jpg)

Select one of them, playground for instance.

The Box just disappears.

If this is intentional, I don't see it documented anywhere.

All I see in Help is:
> Simple action mode replaces the long click action on the screen with a menu driven way of creating new objects. **Long clicks are disabled as long as the mode is active**

Indeed, what is going on here is: if one long clicks on a **single item** the phone beeps correctly. But, if there are **two or more items** underneath your finger there is a bug: the chooser menu still pops up!

**Comment by simonpoole** [comment]
http://vespucci.io/help/en/Introduction/#vespucci-in-locked-mode

**Comment by jidanni** [comment]
You misunderstand. Lock mode behaves perfectly as documented. I am not talking about a lock mode. I'm talking about when a node is already selected, or a way is already selected and the user long presses on more than one item on the map (his finger covers more than one element.)

You won't see this bug if your finger only covers one element. Needs to cover more than one element. If your finger only covers one element you'll cause a beep when you long press it. But if your finger covers more than one element then the bug occurs, a do-nothing selection menu pops up.

If this were locked mode picking one of the items from the menu would produce an  info screen.

But in this case it doesn't. Picking one the items just makes the menu disappear.

That is not the bug. The bug is we should get a beep, instead of getting the menu.

We are not in lock mode. We are in node selected or way selected mode when this bug occurs.

**Comment by simonpoole** [comment]
Yes that is a, minor, issue.

**Comment by jidanni** [comment]
In fact the bug also occurs when **nothing** is selected. Just long press a place near two items.

If you just long press where there is one item you'll get the proper beep. But if there's more than one item then you'll get the bogus selection menu instead of getting the proper beep.

**Comment by jidanni** [comment]
In fact the bug also occurs when **nothing** is selected. Just long press a place near two items.

If you just long press where there is one item you'll get the proper beep. But if there's more than one item then you'll get the bogus selection menu instead of getting the proper beep.
