### ISSUE TITLE
Add title to chooser menu

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2121]
Is this menu asking us to choose an item, or just showing us a list of the items underneath our finger?

![Screenshot_20230209-213831.jpg](https://user-images.githubusercontent.com/1230959/217830792-34503915-fb0c-4ebb-b23a-0c5388b65601.jpg)

Well such mysteries could be solved if this menu simply had a title on the top. It could say "choose one item", or "select one item", etc.

In fact many of the functions bring up this menu. And in all cases it's actually asking us to select one item, not just showing us a list. So at the top that's what it should say, "Select (one)".

**Comment by simonpoole** [comment]
This was addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/023a26f6ac4309d09e0cfc8d66e7be30f3e7d261
