### ISSUE TITLE
Help screen is not kept after re-enter app

### ISSUE THREAD

**Issue by mmc20520** [MarcusWolschon/osmeditor4android#2124]
## Vespucci Version
18.1.1

## Download source
GitHub

## Device (Manufacturer and Model)
emulator

## Android Version 
10

## Behaviour/Symptoms
Press home button at the Help page, then re-enter app, the Home Screen is displayed rather than the Help page

Before press home button

<img width="316" alt="Screen Shot 2023-02-10 at 2 30 10 PM" src="https://user-images.githubusercontent.com/100833575/218019600-3a832b96-8f5f-4d6b-b9b1-50681da53df0.png">

After re-enter app

<img width="316" alt="Screen Shot 2023-02-10 at 2 30 28 PM" src="https://user-images.githubusercontent.com/100833575/218019670-b668b6ef-bdce-425e-8010-252662bf2311.png">

**Comment by simonpoole** [comment]
This is intentional. For nearly all practical purposes the help system is a separate app, you can even start it directly from the launcher.

If you check in the recent apps display you will find a separate entry, and it will retain whichever page you were on.
