### ISSUE TITLE
Address tool fills addr:state instead of addr:province in Canada

### ISSUE THREAD

**Issue by neilguertin** [MarcusWolschon/osmeditor4android#2133]
## Vespucci Version
18.1.1

## Behaviour/Symptoms
addr:state is auto filled

## Expected Behaviour
addr:province is auto filled

## How to recreate
Navigate to anywhere in Canada (I tried in big cities and in the middle of nowhere).
Add tagged node, for example "Buildings>Apartments"
Click address tool (42 in box on top row)

**Comment by simonpoole** [comment]
I'm a bit confused by the "instead" bit as the default configuration is to add both addr:state and addr:province if they exist in other nearby addresses, see also http://vespucci.io/help/en/Advanced%20preferences/#address-tags 

In any case could you add the "proper" address keys to https://github.com/simonpoole/geocontext

**Comment by simonpoole** [comment]
ping @neilguertin

**Comment by neilguertin** [comment]
I didn't realize it was pulling data from nearby addresses. That explains why I could sometimes get addr:province to autofill and sometimes I couldn't.

Nevertheless, addr:state should not be autofilled. The tag is not used in Canada, so I have to delete it for each node.

I'm not an expert on addresses so don't want to say whether addr:province or other addr tags should be used or included in the autofill or not. However it looks like addr:province is used on only 8% of addresses in Canada, compared to addr:state used on 62% in US. ([CA Taginfo](https://taginfo.geofabrik.de/north-america/canada/search?q=addr)) ([US Taginfo](https://taginfo.geofabrik.de/north-america/us/search?q=addr))

And I'm sorry but I don't have a good way to test changes, fix formatting, etc for that json file. I think it's easier if you make the necessary changes there.
