### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2143]
Description:
---

I need to change the language of the app to English, I am very familiar with the OpenStreetMap related terms in English and having the app in Dutch makes me translate imprecise in my head.

Device info:
---
<table>
<tr><td>App version</td><td>18.1.1.0</td></tr>
<tr><td>App version code</td><td>2303</td></tr>
<tr><td>Android build version</td><td>c6fde</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>POBS29.288-60-6-1-29</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>fiji</td></tr>
<tr><td>Device model</td><td>moto e6s</td></tr>
<tr><td>Device product name</td><td>fiji_reteu</td></tr>
<tr><td>Device hardware name</td><td>mt6765</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by simonpoole** [comment]
See https://vespucci.io/help/en/Advanced%20preferences/#disable-translations
