### ISSUE TITLE
Cannot fetch objects or imagery from openstreetmap.org

### ISSUE THREAD

**Issue by Valenoern** [MarcusWolschon/osmeditor4android#2151]
OSM objects do not seem to render at all on my device if they came from `openstreetmap.org`.  
It should be noted this is a bit of an old, low-power device, but I don't _think_ that's the problem here, as imagery is not loading from openstreetmap.org and loading fine from other sources.

## Vespucci Version
18.1.2

## Download source
F-Droid

## Device (Manufacturer and Model)
* Model: LG15G / "LG Sunrise"
* Device: y25
* Build ID: KOT49I.LGL15G11a

## Android Version 
4.4.2 (Kit Kat)

## Debug screen
* Target SDK: 31
* Memory used: 48,443,392/134,217,728
* Bug state file size: 60

## Behaviour/Symptoms
* No OpenStreetMap objects appear at all
* With a fresh configuration, this notification appears: "The imagery source 'OpenStreetMap (standard) is erroring'" (this would be on openstreetmap.org)
* Imagery and geojson layers still display just fine, as long as they are not on openstreetmap.org

## Expected Behaviour
OpenStreetMap objects should load and display, even if the map is slow to load or respond.  
At (46.8451322, -71.1321903), you should see a viewpoint and a bookcase.

## How to recreate
* Install Vespucci fresh or delete app data
* Open Vespucci with wifi and location on
* Discard grid and tasks layers
* Move map and try to get imagery layer to load tiles
* Have two layers, default OSM layer and imagery layer set to ESRI or "OpenStreetMap (German Style)" (I don't think which imagery matters for map objects)
* Go to example coordinates: (46.8451322, -71.1321903)
* Disable and enable default OSM layer
* Add a new URL to default OSM layer making it http: "http://api.openstreetmap.org/api/0.6/". Choose it. Disable and enable layer
* On each URL move the map around and zoom in/out to see if it loaded

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
F-Droid apps and F-Droid itself have sometimes had problems on this device. F-Droid has trouble applying updates properly and neither the old nor new [Newpipe](https://github.com/TeamNewPipe/NewPipe) apps were working

F-Droid version: 1.12.1

**Comment by simonpoole** [comment]
This is nearly guaranteed to be due to https requirements on openstreetmap.org (the tiles erroring is the give away). See https://vespucci.io/tutorials/faq/#cant-download-data-from-openstreetmap-servers Unluckily the workaround with the non-http url doesn't work anymore iirc.

I need to update the FAQ in any case.

@firefishy OSM side of things correct?

**Comment by simonpoole** [comment]
PS: you did try with the standard (https) API entry?

**Comment by Valenoern** [comment]
Yes, the steps were supposed to show that I used the https entry, then the http entry, and the https entry again, but neither of them worked.

I tried booting up my other Android device that's a bit more powerful and recent and exporting and installing the exact same apk, and it still could not load OSM data from the default URL. Though oddly it had no problem with the openstreetmap.org tiles.

---

## Device
* Vespucci version: 18.1.2
* Android version: 5.1.1 (Lollipop)
* Model: KFSUWI "Kindle Fire 7th generation" / suez
* Build ID: LVY48F

## How to recreate
* Install the Vespucci apk that shows up in F-Droid `1.12.1` - I believe this is the same one that shows up in F-Droid `1.15.6`, because it still showed the apk as current.
* Discard grid and tasks layers
* Move map and try to get imagery layer to load tiles
* Change imagery to "openstreetmap (German style)" or anything else, and then back to "openstreetmap (standard)" to verify openstreetmap.org tiles load
* Disable and enable default OSM layer, toggle to sandbox URL and test, toggle back to default URL and test

## Behaviour/Symptoms
openstreetmap.org tiles appear but objects do not

**Comment by simonpoole** [comment]
Ad blocker? Firewall? Have you tried using mobile network vs. WLAN?

Note that there are no known issues outside of potential https issues with devices with Android 4.X with downloading from OSM (and mater of fact one of the devices we use for testing pre release is a Kindle running Android 5).  Naturally it is possible that F-Droid broke something, but that seems unlikely for this functionality.

**Comment by Valenoern** [comment]
Okay... it turns out I just had not figured out how to actually download data.  
If I use "download current view", Vespucci can fetch objects just fine.

The OSM layer is a little slow on the "sunrise" device, but the important thing is it's definitely functional, it can read the objects and look at their tags. I even managed to upload new points.

But I would like to verify one last thing: is the "download current view" option the main way to fetch OSM objects, or is there some more obvious interface element or something I missed?

**Comment by simonpoole** [comment]
> But I would like to verify one last thing: is the "download current view" option the main way to fetch OSM objects, or is there some more obvious interface element or something I missed?

Its the "JOSM-like" way, but depending on how you are using the app one of the auto-download options might be more appropriate, see http://vespucci.io/help/en/Introduction/#downloading-osm-data and http://vespucci.io/help/en/Main%20map%20display/#transfer

Note that the introduction and the context sensitive help is available on device too.
