### ISSUE TITLE
Name the wrench menu

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2153]
Here if we tap the cog wheel the menu comes up that says Preferences.
If we tap the wrench a menu comes up but it is missing any name.
It should have a name.
And then there's the three dot button. . But at least there should only be one thing that doesn't have a name, not two.
![Screenshot_20230308_211626_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/223723396-f6887e93-291a-481f-b26f-8c4741116f10.jpg)

If in the Android settings we make our screen zoom higher, the wrench disappears. So now it must be inside the three dot menu. However which one is it there? Without knowing its name we can't figure out which of those three dot menu items it now is. We end up needing to look in the manual!

**Comment by simonpoole** [comment]
All the standard buttons including the overflow menu have names/titles that a long press will display (standard Android behaviour), this is the same as what the overflow menu shows as the menu entry. If there is no space on the menu bar, again standard Android behaviour is that the entries are moved to the overflow menu.

Not only that, both icon and title of the "Tools..." menu are documented.
