### ISSUE TITLE
Say how much to zoom into edit

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2157]
![Screenshot_20230309_190000_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/224004536-427160b6-441c-485f-8fc5-6be0251e7ee1.jpg)

Here it tells us to zoom into edit, so we do it and then we try to edit and then it tells us again to zoom in to edit.

Over and over.

Recommendation: have it say how many steps are still remaining until we finally get to edit!

For instance it could say tacked on the back: 16/18, then 17/18...
Something like that so we can get an idea of how many times we should push the little white Plus button.

And indeed, the Big Green Plus button could become even greener when we get the "green light" to edit!

By the way, the words you see on the screen forget to mention the white Plus button! They only mention other ways to zoom.

By the way, the message sometimes even partially covers up the button we need to push to zoom:

![Screenshot_20230309_192328_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/224010611-9f21a591-26ac-4068-8fd5-c908154832fb.jpg)

**Comment by simonpoole** [comment]
You already get visual feed back because the "touch areas" will appear when you've zoomed in far enough.

**Comment by jidanni** [comment]
(Yes, we know we have arrived when we see the house. We just want to know how many blocks we still need to walk.)
