### ISSUE TITLE
List relations in italics in selection lists 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2158]
![Screenshot_20230309_191334_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/224007809-fd5d138d-91d3-44c7-b8e3-c7e3ca38c8d3.jpg)

Here, if nodes had blue backgrounds, ways had yellow backgrounds, and relations had pink backgrounds, or whatever your favorite colors are, then we would immediately be able to tell at a glance which ones were which!

Currently the only ones we can be certain of are raw nodes with no tags at all.

(And yes we can guess what stream and service are: ways.)

**Comment by simonpoole** [comment]
This would be super distracting and would conflict with other use of colours in the menu.

**Comment by jidanni** [comment]
Wait!: I've got it simply write the relations in _italics_!
