### ISSUE TITLE
Spurious change left after tapping Undo

### ISSUE THREAD

**Issue by opk12** [MarcusWolschon/osmeditor4android#2159]
- Start without local changes. For example, upload changes, or use the menu to download and discard local changes.
- Select the last node of a way, for example [this one](https://www.openstreetmap.org/node/1445880890).
- Tap `+` to continue the way.
- Tap somewhere to create a new last node.
- Press Undo.
- Now you have a local change. Tapping Undo will not undo it. The upload panel does not explain what is the difference.

This is 18.1.3.0 from F-droid on Samsung Android 7.1.

**Comment by simonpoole** [comment]
Thanks for the report.

The reason for the glitch is that the way that is appended to is added to the changed elements at the beginning of the operation, but because the undo works differently in the path creation mode, it doesn't get removed "automatically" when all way additions are removed.
