### ISSUE TITLE
Allow copying pKey (ID) of a certain Mapillary image

### ISSUE THREAD

**Issue by LuisAPI** [MarcusWolschon/osmeditor4android#2163]
I can't find a way to get the pKey= or the URL of a Mapillary image, so I could add it to a feature as `mapillary=`.

— On iD (OpenStreetMap.org), what I usually do is right-click the small Mapillary logo icon before the date on the lower-right corner of the Mapillary pop-up widget, which links to the source image with the key number. I could then use "Copy Link" on that and paste it while removing the other parts of the URL.

— On Vespucci, the only equivalent seems to be the Share button, which turns the image into a .jpg on my Gallery with the filename as a string of random numbers. idk if that's the pKey I'm looking for but either way, I can't copy and paste that.

**Comment by simonpoole** [comment]
I suppose one possible option would be to provide an option to copy it as a tag to Vespuccis internal tag clipboard.
