### ISSUE TITLE
Allow selecting all items

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2171]
Today we want to select all these items. 

![Screenshot_20230314_184056_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/225449423-effaeea9-8f34-45dd-9f1f-323b77815488.jpg)

It is going to be hard work. We've already selected one and now we have to add each one one by one via multi-select to get the rest.

If way down at the bottom there was an additional item: "(Select all)" then all it would take is one touch!

**Comment by simonpoole** [comment]
Simply use a search expression: https://github.com/simonpoole/JosmFilterDoc/blob/master/filter.md

**Comment by jidanni** [comment]
All I know is there are all items that we want to select sitting there right in front of us on that list.

So first we must must figure out exactly which menu item you are talking about.

Then we must figure out what kind of search expression we want to use that will get exactly those eight items and not any others.

Then we must type that long search expression by hand into some box.
