### ISSUE TITLE
Nice to have: Auto-select next node

### ISSUE THREAD

**Issue by ceever** [MarcusWolschon/osmeditor4android#2176]
When deleting a node from a way or area, it would be nice if the app would select the next or nearest node, so one could continue deleting without first selecting the next node again. I know this is a little arbitrary to define the next node, but on openstreetmap.org the (simple) editor functions in a similar way and it is therefore quite efficient to clean up parts of a way or area.

Cheers

**Comment by simonpoole** [comment]
The idiomatic (and fastest) way  to do this is to select all the relevant nodes and delete them with one operation (1 double tap plus (n-1) single ones plus one button press).
