### ISSUE TITLE
Making notes should increment the upload counter

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2179]
We read 
> After creating a new Note you can move it or delete it until you've uploaded it to the OSM servers

That's great, except let's say we make five notes when we're off in the field.

Now we're back to somewhere with Internet. Well let's upload our notes. First we must remember how many notes we made. Then we must find them on the map one by one wherever we placed them and then press them and then we get an upload button for them.

If we forgot about one, or we forgot about where we put one, well that's too bad.

Therefore it would be much better if these notes were treated just like nodes. In other words  incrementing the 'up and down arrow' icon's items to be uploaded counter, and uploading in the same fashion with any other nodes. Thanks.

**Comment by simonpoole** [comment]
While you can immediately upload a note from the modal, they (and other changes to tasks) will get uploaded the next time you upload data, or when you explicitly "Upload all", see https://vespucci.io/help/en/Main%20map%20display/#transfer

**Comment by jidanni** [comment]
Well,  we must find something to edit first in order to enable the ⇅ button... Which also was the only place to tell the glance if there is something we still haven't uploaded yet.

**Comment by HolgerJeromin** [comment]
>Well, we must find something to edit first in order to enable the ⇅ button...

No, simon is correct. He means the menu, not the menu item. 

But a bug in this context:
Add text to a note.
Save, not upload
Reopen note
Delete saved content
Saving not possible 
So you can not get rid of your text

"Upload/Task/reset all" kills it, but there could be more which should survive.

**Comment by simonpoole** [comment]
> But a bug in this context:

Could you open a separate issue for this (it isn't really in this context, it is just that we in general don't allow saving of empty comments, for obvious reasons).
