### ISSUE TITLE
'Add layer from GPX file' should allow multi-file select

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2184]
In the Android file chooser we are only allowed to pick one GPX file at a time. This is rather frustrating when  one wants to add seven etc. GPX files and they are sitting right in front of us but we can only add them one by one.

**Comment by simonpoole** [comment]
The question is naturally: one layer or a layer per file?

**Comment by jidanni** [comment]
For starters, one layer per file. I didn't even know anything else was possible.

**Comment by simonpoole** [comment]
It is completely possible to merge multiple GPX tracks in to one (from a resource usage pov this would even be preferable compared to potentially creating a lot of layers).

**Comment by jidanni** [comment]
Well okay, but the user can't unglue them afterwards. With  separate layers the user gets the flexibility to pick how many layers he wants at any time. 


Maybe there should be two menu buttons instead of one,  just like there are two:
>Paste object
>Paste multiple times
