### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by Mahabarata** [MarcusWolschon/osmeditor4android#2185]
In Vespucci software we have in the "preferences/advanced preferences/user interface settings" the english text "Fullscreen mode" with the options "Auto", "Never", "Force", "No statusbar".
In Transifex, we have 8 texts, 1 for Fullscreen mode, 7 for the options, 4 with the context "full_screen_preference_entries", 3 with the context "full_screen_preference_no_auto_entries". These texts have been translated in french since 2018 for "Fullscreen mode" and since Nov. 2020 for the 7 texts for the options.
But in the sofware, we have only the french translation of "Fullscreen mode", the 4 options are still in English.

debug infos : Vespucci 18.1.3
Flavor: current
Target SDK: 31

**Comment by simonpoole** [comment]
The minimum required translation coverage for the string-arrays resource is 100% see https://github.com/MarcusWolschon/osmeditor4android/blob/master/.tx/config#L72 As there are three translations missing in French the whole file is currently not downloaded and included in the build.

**Comment by Mahabarata** [comment]
Ok, thanks : now string-arrays is complete ;)

**Comment by simonpoole** [comment]
Yes, that translation and some other French ones got pulled now: https://github.com/MarcusWolschon/osmeditor4android/commit/624bd7444a2800c7eb92ed2c4e2f529ef4f07e6d
