### ISSUE TITLE
Zufügen von Wegweisern zu einer bestehenden Route 

### ISSUE THREAD

**Issue by nurdafur** [MarcusWolschon/osmeditor4android#2186]
Hallo

Wenn ich eine (Wander-)Route neu anlege und dabei die Wegweiser direkt zufüge, dann werden diese automatisch mit dem Zusatz Guidepost markiert.
Will ich jedoch nachträglich einer bestehenden Route einen Wegweiser zufügen, indem ich auf Relationsmitglieder zufügen klicke, dann kann ich den Wegweiser nicht auswählen.
Klicke ich doppelt auf den Wegweiser, damit ich die Mehrfachauswahl starte, dann kann ich zu Relation zufügen auswählen, muss dann aber manuell noch definieren, dass es ein Guidepost ist. Dies ist zwar eine mögliche Option, um zum erwünschten Ergebnis zu kommen, jedoch ist es nicht immer leicht, die gewünschte Route zu finden. Speziell, wenn sehr viele Routen im heruntergeladenen Bereich vorhanden sind, wird es sehr unübersichtlich. 
Gleiches gilt zum Beispiel auch, wenn ich einem Fitnesstrail die einzelnen Stationen zufügen möchte. Es gibt bestimmt noch weitere Fälle, bei denen zu einer bestehenden Route ein Knoten-Objekt zugefügt werden könnte.
Wenn zumindest das Zufügen von (bestimmten) Knoten zu bestehenden Routen möglich ist, wäre das schon eine grosse Hilfe. Sortieren muss ich die Objekte ja dann sowieso noch. Da kann ich dann auch noch den entsprechenden Zusatz einfügen.

Liebe Grüsse 
Urs

**Comment by simonpoole** [comment]
Bei mir kann ich durchaus bei `..  indem ich auf Relationsmitglieder zufügen klicke, dann kann ich den Wegweiser nicht auswählen.` einen Wegweiser hinzufügen, kannst du das nochmals überprüfen?

**Comment by nurdafur** [comment]
Ich habe das einen Tag zu früh geschrieben. Nach der Installation des neuesten Updates funktioniert das Zufügen nun.

Am 31. März 2023 12:40:32 MESZ schrieb Simon Poole ***@***.***>:
