### ISSUE TITLE
History compare leads to crash

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#2187]
## Vespucci Version

18.1.4

## Download source

Google Play

## Device (Manufacturer and Model)

Fairphone 4

## Android Version 

12

## Behaviour/Symptoms

When comparing version 5 with version 6 of https://www.openstreetmap.org/way/1098448370, the app crashes

## Expected Behaviour

Show comparison

## How to recreate

Select way, select history, versions 5 and 6 and select compare

## Crash dump submitted (no or yes + date)
Yes, ca. 2023-03-27 08:58

**Comment by simonpoole** [comment]
Seems as if comparing the two specific versions causes a loop (other versions work fine), unluckily there is no debug output at this point. In any case this needs to be reported to https://github.com/zedlabs/ElementHistoryDialog @zedlabs
