### ISSUE TITLE
GPX ends up at the international dateline

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2189]
On https://www.gpsvisualizer.com/ this GPX looks great. But loading into Vespucci end up at 180° or something.

In fact I can load it about 2 and 1/2 times.
![Screenshot_20230328-131010.jpg](https://user-images.githubusercontent.com/1230959/228135973-fee0544a-a069-4424-8c5e-7d14d425ddde.jpg)

[3248.gpx.gz](https://github.com/MarcusWolschon/osmeditor4android/files/11085722/3248.gpx.gz)
I had to compress it to attach it here.

**Comment by simonpoole** [comment]
Looks perfectly OK.

![Screenshot_1679988639](https://user-images.githubusercontent.com/1011860/228161930-a0b27f0a-044f-426b-a944-efdab56c5f97.png)

**Comment by jidanni** [comment]
Okay, here's how I finally managed to reproduce it:

First in bookmarks I switched to a bookmark that I had saved from in the United States, North Dakota to be precise. Then, I switched to unlocked mode.

Okay, now I imported the GPX.

Then I selected go to first node, and ended up in the ocean.

Share location gave: geo:24.1817382,-179.9998190?z=21

So the latitude was okay, but they longitude banged into the antimeridian.

**Comment by simonpoole** [comment]
This would seem to have nothing to do with bookmarks or GPX files, it is simply an issue with correctly calculating the longitude offset in an (180°) overflow situation which is triggered by the specific original and target coordinates.
