### ISSUE TITLE
Layer + menu uses only half screen 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2194]
Here I wish this menu  would use a little more of the screen.
![Screenshot_20230329-231307.jpg](https://user-images.githubusercontent.com/1230959/228590981-9ac4240e-366f-42ba-a7fc-3b82adcd7ef2.jpg)
Then we wouldn't need to scroll so much often..

**Comment by simonpoole** [comment]
While it is possible to overlap the menu anchor it is in general not desirable, particularly in this case where you would start running out of space to dismiss the menu.
