### ISSUE TITLE
.gpx suffix should be in saving dialogue

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2195]
When we Export to GPX, we aren't sure if the .gpx suffix is being added or not automatically for us. The only way to tell is later on the file system.. And the answer is no.

Therefore when the user fills in the file name, I suggest that the .gpx should be at the end already filled in for him.
If he wants to change it before saving, then he can also do that while filling in the form.

At least he will no longer worry if he will end up with two,  or zero, .gpx suffixes!

**Comment by simonpoole** [comment]
The android SAF file picker doesn't support this or similar setting of default extensions or filenames.
