### ISSUE TITLE
Don't add bogus timestamps upon GPX export

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2196]
If we import a GPX file with no timestamps,
and then export it,
`<time>1970-01-01T00:00:00Z</time>`
gets added to each line.
- Adding inaccurate information. No we were not there then. Even if then=0.
- Doubling the size of the file

**Comment by simonpoole** [comment]
Given you already have the original file, this is a complete non-problem.

**Comment by jidanni** [comment]
That's not the point. I was only able to detect the bug because I could compare before and after.

**Comment by simonpoole** [comment]
It isn't a bug, it is on purpose as the OSM API requires timestamps. So the only "use case" where this an "issue" is taking an existing  track importing it in the app and then exporting it, which doesn't make sense.
