### ISSUE TITLE
missing texts to translate for validations

### ISSUE THREAD

**Issue by Mahabarata** [MarcusWolschon/osmeditor4android#2199]
Hi,

In Preferences/Validator settings/Enabled validations, there are several texts in English in Vespucci software, for example Object age, FIXME tags, missing tags...

In transifex, these texts are missing.

Could you add them in a future version of Vespucci to be able to translate them ?

**Comment by simonpoole** [comment]
This was just an oversight, should have been added ages ago. Thanks for the report.
