### ISSUE TITLE
Avoiding crash loop

### ISSUE THREAD

**Issue by opk12** [MarcusWolschon/osmeditor4android#2204]
I loaded too much data and now Vespucci freezes at `Loading data into memory` until it runs out of memory and crashes. Tapping outside the dialog does not help. Is it possible to bypass the loading phase, if the app crashed last time, sort of a "safe mode"?

**Comment by simonpoole** [comment]
Not really, if it can't read the data it will try to read the previous saved state, however if it is in principle valid data that wont help. Loading the data is completely asynchronous and the dialog has no function outside of indicating that loading is still running, aka dismissing it does nothing.

If the device isn't rooted there isn't really anything you can do at this point except clear the apps data. But I would try rebooting the device first just to rule out a glitch in the OS.

There are numerous safeguards against loading too much data, however there are other ways by which you can in the end exceed available memory. Do you have any GPX or GeoJSON layers configured? Did you get a warning before this happened?

**Comment by simonpoole** [comment]
PS: did you submit a crash dump? If you have, I can give it a quick look.

**Comment by opk12** [comment]
Rebooting did it! I did not have the chance to send a bug report, but it seems the amount of data is not the cause as I had assumed. I meant to write that the app enters a safe mode automatically, but anyway this is solved for me. Thank you for the prompt, detailed reply!

**Comment by simonpoole** [comment]
I wouldn't rule out that memory management was under pressure so much that it couldn't allocate enough one way or the other.
