### ISSUE TITLE
Presets Tailings and Branch tower type

### ISSUE THREAD

**Issue by Mahabarata** [MarcusWolschon/osmeditor4android#2206]
In the presets for Vespucci, on Transifex, we have the word "Tailings".

In the context on Transifex, we find this =
build/temp/v4.xml:3634(combo:display_values|group:Water|preset:Reservoir|key:reservoir_type):

But on the wiki, this preset has been deprecated :  https://wiki.openstreetmap.org/wiki/Key:reservoir_type

The new preset should now be : https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dtailings_pond

**Comment by Mahabarata** [comment]
Same thing for 'Branch tower type'

context = build/temp/v4.xml:9631(combo:text|preset:Power_Tower|key:branch:type):

but branch:type is deprecated = https://wiki.openstreetmap.org/wiki/Key:branch:type

The new preset should be = https://wiki.openstreetmap.org/wiki/Key:line_management

**Comment by simonpoole** [comment]
These issues need to be opened in the preset repo as indicated in the issue template.

**Comment by Mahabarata** [comment]
Done (I opened this issue with "Empty bug report" so I didn"t know for the preset repo, sorry and thanks for your help)

**Comment by simonpoole** [comment]
Seems as if you didn't open an issue for the branch:type possible issue (as everything wrt power changes at least once per year, I'll probably wait a bit for this :-)).

**Comment by Mahabarata** [comment]
For branch:type, there is already an issue : https://github.com/simonpoole/beautified-JOSM-preset/issues/319
