### ISSUE TITLE
None in french

### ISSUE THREAD

**Issue by Mahabarata** [MarcusWolschon/osmeditor4android#2207]
Hi,

it is not really a bug but I need more informations.

In Transifex, we have 2 times the word "None".

One is very clear because there is a context = followGPSbutton_entries

The second has no context (or context is useless) = "Clé none"

In french, we can translate it by "Aucun" if the object is male ("aucun chemin")  or by "Aucune" if the object is female ("aucune relation") or by "Aucun(e)" if the object is sometimes a male object and sometimes a female object.

I need to know when/where this word is used : you can answer me here (so I will immediately translate it) but to have a more clear context would be better.

**Comment by simonpoole** [comment]
Android resource strings don't have a direct way to indicate context outside of the resource name. In the case of generic strings, like "None" there's isn't really an alternative to checking where it is used in the source code. In this case we're lucky and there is only one use in the layer style modal for the key that should used for a GPX or GeoJson object label.

**Comment by Mahabarata** [comment]
Ok, thanks, I found it : so I changed the translation (Aucune instead of Aucun because used with "label" translated by "Etiquette")
