### ISSUE TITLE
Pending upload

### ISSUE THREAD

**Issue by Mahabarata** [MarcusWolschon/osmeditor4android#2211]
Sorry to disturb you again ;)

In the Preferences/Advanced preferences/User Interface Setting, I don't understand the Pending upload OK and the Pending upload warning.

First, in the Help, it is written for Pending upload warning "Limit below..." : I suspect the text should be "Limit above..." (no warning if number of changes is small, a warning if we have too much changes)

Second, if the Pending upload OK is set to N1 objects and the Pending upload warning is set to N2, what happens if :
* I have changed less than N1 objects (nothing I suppose)
* I have changed between N1 and N2 objects
* I have changed more than N2 objects (a warning I suppose if the typo below/above is really a typo and not a misunderstanding)

In the second case, if nothing happens, why to have N1 ? If a warning is shown, why to have N2 ? So I suppose something else happens but the Help says nothing.

**Comment by simonpoole** [comment]
Below the OK value the pending upload count is green, above that and below the warning level orange, and above it red.

**Comment by Mahabarata** [comment]
Ok, thanks a lot
