### ISSUE TITLE
"Download GPX track"  doesn't

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2212]
Today I tried
> Download GPX track 
Download a GPX file from the OSM API for the user and create a layer from it. Note that only GPX tracks with their starting point in the area currently displayed will be available for selection, this is a limitation of the current OSM API.

But no matter how far I zoomed out, it just said Nothing Found, in orange.

As you can see the same zoomed out area has tons of tracks in it https://www.openstreetmap.org/#map=13/24.6899/121.1928&layers=G

Maybe we are talking about different things. On the Osm website they are called "Public GPS Traces" . Maybe your document should mention that. 

Also maybe the name of the command should end in tracks not track.

> for the user 

Ah ha, maybe this means only the tracks the user has as uploaded himself, previously.

Not tracks uploaded by anybody else.

**Comment by simonpoole** [comment]
It already says what it does: ```for the user ```

There is no public API to retrieve the ids of GPX tracks owned by a third party, see https://wiki.openstreetmap.org/wiki/API_v0.6#GPS_traces
