### ISSUE TITLE
Millisecond difference causes selection to fail

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2219]
I discovered an enormous bug.

![Screenshot_20230407_143804_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/230555840-dc57fbaa-2de1-46f5-ab83-e1480e4f1666.jpg)

~~Let's say we touch the trail at points A.~~

~~Well, we get the chooser  dialogue as you see in the screenshot.~~

~~But, our choice will get ignored! No selection will occur. We are left staring at the exact same thing that we started with.~~

~~Okay now do it over again, but tap area B. We make our choice from the chooser dialogue and... it works! Our selection is indicated. The trail becomes yellow.~~

~~So there is some bug. If one puts a finger on a label, that causes the entire chooser menu to fail.~~

~~No we are not particularly wanting to look to see  if there's some label where we put our finger. It should all act the same, label or not.~~

Wait it's not the labels. It's something else. Give me a couple minutes.

Okay I figured it out it's all a matter of milliseconds. To the user it might be very hard to figure out what equals a long press, and  what equals a short press. But to the app it is very picky:  one millisecond difference and it becomes a long press. And with a long press you'll get the failure I mentioned above.

**Comment by simonpoole** [comment]
The labels are just black pixels there is no conceivable way they would have anything to do with selection in any form.

**Comment by jidanni** [comment]
See #2128.

**Comment by jidanni** [comment]
#2128.

**Comment by jidanni** [comment]
Anyway if this is intentional. Then at least the selection menu at its should say that it's not a selection menu, it's just a listing menu.

**Comment by simonpoole** [comment]
Long vs. short click is determined by the operating system and is adjustable in the OS setting to a certain degree.

**Comment by jidanni** [comment]
Yes but long click is currently bound to undocumented, and erroneous, behavior!
