### ISSUE TITLE
Warn that you're not copying as many items as you think

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2220]
Here the user thinks he is copying five items. But he's actually only copying one.

![Screenshot_20230407_151342_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/230561180-67b312b2-fa59-4ca9-8708-2354e0720e66.jpg)

Even harder for the user to notice would be e.g., when he thinks he's copying five items but he's only copying four.

Anyway in both cases of warning should show up on the screen or something! 

Or, allow copying empty items:
handrail:left=

**Comment by simonpoole** [comment]
I'm not totally convinced about copying these as "key only" tags are really only of use as transient placeholders in the property editor, but it makes more sense than a warning.
