### ISSUE TITLE
Save intermediate state in "Extract segment" action mode (was "Extract segment Set tags"  page lost if one dares to look at Help)

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2223]
Here we are on the "Extract segment Set tags" page.

It is our first encounter with those two icons, bridge and tunnel, there at the bottom, and we're all excited to try them out.

![Screenshot_20230407_044254_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/230565362-1745584b-fe2e-41e0-8731-80ddd11691cf.jpg)

But wait, in the lower right corner there is a question mark. A help page link.

Well we were always taught to follow instructions. So let's have a look at the instructions.

Okay now we're finished reading the help page and we go back to where we were and..

We're now looking at a usual Way Selected page.

The interesting two icons are gone.

It makes people scared to go reading instructions.

Yes, you might say, "Well, you are just selecting a Way. So don't feel bad."

Anyway, please be sure when returning from help that we return to the same thing we were looking at. Thanks.

**Comment by simonpoole** [comment]
> Anyway, please be sure when returning from help that we return to the same thing we were looking at. Thanks.

How much is it worth to you?

**Comment by jidanni** [comment]
We're talking about heartbroken little children at the UNICEF mapping camp.

But it's okay. I'm in no hurry. Fixing it by 2028 will be fine.

**Comment by simonpoole** [comment]
UNICEF employees tend to be paid.
