### ISSUE TITLE
Add a missing text to be translated

### ISSUE THREAD

**Issue by Mahabarata** [MarcusWolschon/osmeditor4android#2226]
In Preferences/Advanced preferences/Data and edit settings, we find a text on Vespucci = "Distance between neighbour adresses" with a subtitle "N meter(s)".
On transifex, the first text is missing.
The second text can be found (4 times) but contexts seem not to be appropriate.

Could you add these texts ?

**Comment by simonpoole** [comment]
This was a late addition to 18.0 and seems as if the strings weren't updated after that.
