### ISSUE TITLE
Anzeige von Routennamen

### ISSUE THREAD

**Issue by nurdafur** [MarcusWolschon/osmeditor4android#2229]
Wenn ich auf einen Weg klicke oder wenn ich ausgewählte Elemente einer Route zufügen möchte, dann werden die vorhandenen Routen mit ihren Namen aufgelistet. 
Es gibt jedoch diverse eher kurze Routen, die keinen Name-Tag besitzen. In diesem Fall steht dann nur Wanderroute, Veloroute... 
Wäre es möglich, in solchen Fällen, falls vorhanden, die from- und to-Tags zu dem angezeigten Namen zu machen?

**Comment by simonpoole** [comment]
Das hängt von https://github.com/MarcusWolschon/osmeditor4android/issues/1232 was leider schon oft verschoben wurde.

**Comment by simonpoole** [comment]
Dies braucht jetzt noch entsprechende Einträge in den Vorlagen: https://github.com/simonpoole/beautified-JOSM-preset/issues/394
