### ISSUE TITLE
Translation of JOSM presets

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#223]
```
The usage of the JOSM tag presets is awesome: user can use its
knowledge of the desktop software to improve his efficiency on the
ground, and developers ensure to always use up to date and centralized
presets. The only drawback of the current implementation is that the
presets labels are not translated. I know this is not a simple task
since JOSM presets translatrions are not in their own file, but I have
to mention it 

```

Original issue reported on code.google.com by `sp8...@gmail.com` on 6 May 2014 at 7:43

**Comment by simonpoole** [comment]
See https://github.com/simonpoole/PoParser Given that this is feature is a bit of a blocker for other stuff priority has gone up.

**Comment by simonpoole** [comment]
Potentially a slightly better display of additional information to the fields in the tag editor would make sense.

**Comment by simonpoole** [comment]
Link to transifex project: https://www.transifex.com/projects/p/presets/

**Comment by simonpoole** [comment]
This is now WIP that can be followed on transifex
