### ISSUE TITLE
Invalid access token on attempt to submit feedback

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#2235]
Vespucci 18.1.4 (from Google store)
Flavor: current
Target SDK: 31
Maximum avaliable memory 536870912
Total memory used 71215768
In memory Tile Cache MAPNIK usage Size 0 of maximum 67108864 #entries 0
In memory Tile Cache GEOPORTAL2-PL-AERIAL_IMAGE_WMTS usage Size 4980736 of
maximum 67108864 #entries 19
In memory Tile Cache FREEMAP.SK-OUTDOOR usage Size 0 of maximum 67108864
#entries 0
Current used file system net tile cache size: 17339972B
State file size 3624220 last changed 2023-04-11 06:02:09
Bug state file size 26390 last changed 2023-04-11 06:02:09
Relations (current/API): 263/0
Ways (current/API): 1407/0
Nodes (current/Waynodes/API): 12880/12670/0
Available location providers
passive enabled true
gps enabled true
network enabled true
Configured layers
IMAGERY 0 IMAGERY false MAPNIK
IMAGERY 1 IMAGERY true GEOPORTAL2-PL-AERIAL_IMAGE_WMTS
IMAGERY 2 IMAGERY false FREEMAP.SK-OUTDOOR
SCALE 3 SCALE true null
OSMDATA 4 OSMDATA true null
TASKS 5 TASKS true null

![Screenshot_20230409-124010](https://user-images.githubusercontent.com/899988/231136147-95ebc5ed-8626-45eb-b113-9bb7c7e70a8d.png)

**Comment by simonpoole** [comment]
Seems as if the last build used an old token. Fixed now.
