### ISSUE TITLE
Vespucci sometimes create duplicate ways (half-failed splitting of way?)

### ISSUE THREAD

**Issue by mnalis** [MarcusWolschon/osmeditor4android#2238]
## Vespucci Version
18.1.4

## Download source
f-droid

## Device (Manufacturer and Model)
Huawei P30 Pro

## Android Version 
Stock EMUI 12.0.0

## Behaviour/Symptoms
In [Changeset 134692847](https://osmcha.org/changesets/134692847/) Vespucci created two new ways (way [1160874269](https://www.openstreetmap.org/way/1160874269) and way [1160874270](https://www.openstreetmap.org/way/1160874270)). The ways were **not** created _manually_ by the user, but were most probably a result of splitting the [way 136881849](https://www.openstreetmap.org/way/136881849) in Vespucci (note: what way was later manually removed in JOSM changeset 134792855 after the issue was detected)

## Expected Behaviour
Splitting the way should not have have created duplicate ways. It should have atomically either: 
- removed old way and created two new ways (or even better: modified old way to be shorter - in order to preserve history, and created only one new way), _or_
- refused to create new ways if it was not possible to update/remove original way (e.g. if version conflict or some other problem was encountered)

In other words, split operation should've been atomic: either _whole_ of it should succeed, or _none_ of it should succeed. In this case it seems Vespucci created two new ways (splits) but failed to remove original way (that they were split from), resulting in duplicate (overlapping) ways. 

## How to recreate
I'm not sure (only just happened to me), but my guess is maybe it might be recreated by downloading data in Vespucci, modifying the way in some other editor without Vespucci knowing, and then trying to split the way in Vespucci and uploading?

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
`smoothness` tag was also being removed from that way which was split (I do not remember if before or after it was split), if that might have influenced the behaviour.

**Comment by simonpoole** [comment]
> In [Changeset 134692847](https://osmcha.org/changesets/134692847/) Vespucci created two new ways (way [1160874269](https://www.openstreetmap.org/way/1160874269) and way [1160874270](https://www.openstreetmap.org/way/1160874270)). The ways were **not** created _manually_ by the user, but were most probably a result of splitting the [way 136881849](https://www.openstreetmap.org/way/136881849) in Vespucci (note: what way was later manually removed in JOSM changeset 134792855 after the issue was detected)

The ways were clearly created by splitting way 136881849 twice, no magic involved. It seems as if you were concurrently using streetcomplete at the same time on way 136881849, this created a version conflict on upload for that way, and you chose to keep the version on the server on upload. This led to the remaining stub of 136881849 not being uploaded, leaving the version of 136881849 that you created in https://www.openstreetmap.org/changeset/134692188 in place (uploaded Sunday April 9th 15:07 vs 15:20 for changeset 134692847).

> ## Expected Behaviour
> 
> Splitting the way should not have have created duplicate ways. It should have atomically either:
It didn't.
> 
>     * removed old way and created two new ways (or even better: modified old way to be shorter - in order to preserve history, and created only one new way), _or_
Splitting always creates just one new way (there is literally no code to do anything else) and it does the right thing wrt preserving history. 
> 
>     * refused to create new ways if it was not possible to update/remove original way (e.g. if version conflict or some other problem was encountered)

There is no way to do this without fixing things up after a conflict has occurred and there is no OSM editor that does this any different.

> 
> In other words, split operation should've been atomic: either _whole_ of it should succeed, or _none_ of it should succeed. In this case it seems Vespucci created two new ways (splits) but failed to remove original way (that they were split from), resulting in duplicate (overlapping) ways.

You are asking for behaviour that is difficult to implement in the OSM data model and API, and which is not supported by any other editor either. 

> ## How to recreate
> 
> I'm not sure (only just happened to me), but my guess is maybe it might be recreated by downloading data in Vespucci, modifying the way in some other editor without Vespucci knowing, and then trying to split the way in Vespucci and uploading?

See above, it is very clear what happened. To prevent this re-occuring you should update any existing data in an editor (or discard and re-download in editors that don't provide that) after you have changed the same data somewhere else.
