### ISSUE TITLE
Bauplatz teilweise nur als Linie statt als Fläche

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2240]
Description:
---

Hallo

Auf diesem Gerät mit Android 7 werden mir Bauplätze nicht als Flächen angezeigt, sondern als gelber Weg, wenn noch das zusätzliche Tag check_date=* vorhanden ist. 
Das ist nichts schwerwiegendes, denn nur wenige Mapper hängen an einen Bauplatz noch mehr Informationen als constrution=*. construction=* beeinflusst die Darstellung nicht. Auch tritt das Problem bei meinem Gerät mit Android 11 nicht auf.
Das Problem existiert schon seit mehreren Versionen.

Device info:
---
<table>
<tr><td>App version</td><td>18.1.5.0</td></tr>
<tr><td>App version code</td><td>2307</td></tr>
<tr><td>Android build version</td><td>T555XXU1CRG1</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NMF26X.T555XXU1CRG1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>gt510lte</td></tr>
<tr><td>Device model</td><td>SM-T555</td></tr>
<tr><td>Device product name</td><td>gt510ltexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/nurdafur"/>nurdafur</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Ein Beispiel wäre nicht schlecht. "gelb" ist jedenfalls die Standardfarbe für veraltete Elemente, siehe  https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/assets/styles/Color-round.xml#L51

Seit Version 18.1 werden Bauplätze etc. auch in der Defaulteinstellung für Neuinstallationen für die Altersüberprüfung eingeschlossen, ich nehme also an das das Verhalten schlicht mit dem Alter des Bauplatzes, resp, dem Alter des check_dates zu tun hat.
