### ISSUE TITLE
Non-downloaded areas always dimmed

### ISSUE THREAD

**Issue by afgb1977** [MarcusWolschon/osmeditor4android#2244]
Has this option been activated by default?
I have unchecked the "Always dim non-downloaded areas" option to be able to follow and trace what I am mapping with clear satellite images.
Now with new version (19.0.0.1) screen is always dim.
It's a bug?
From now on it will always be greyed out?
Can we choose not to see the Dimmed screen always?
If I want to see non-dimmed images, I now have to download the zone from OSM. It is somewhat complicated to edit in this way since I do different types of tracking with satellite images and other layers personalized before working on an area.

This new version is a complete wonder with the ability to filter OverPass API data. Thanks guys.

**Comment by simonpoole** [comment]
This is a regression caused by the imagery layer aligning refactoring, unluckily because it really only effects the visuals we can't easily test for this automatically (not the 1st time that we've managed to break it). But that is what beta releases are for.

**Comment by simonpoole** [comment]
Re-opening till next beta release so that beta testers can find this easier.

**Comment by jidanni** [comment]
What is the workaround while we are waiting for a new release? Thanks.

**Comment by simonpoole** [comment]
There is no workaround. It's a Beta release and hiccups are expected. In any case the 2nd beta has already been tagged an built so it just depends on when Marcus has time and how long google takes to verify the app.

**Comment by simonpoole** [comment]
Beta 3 is now available.
