### ISSUE TITLE
Make conditional orthogonal to value_type in presets

### ISSUE THREAD

**Issue by tordanik** [MarcusWolschon/osmeditor4android#2250]
If Vespucci's preset extensions are to be part of a standard used across multiple editors (as per the [GSoC project idea](https://wiki.openstreetmap.org/wiki/Google_Summer_of_Code/2023/Project_ideas#JOSM_editor)), this seems like a good opportunity to make the `value_type` a bit more future-proof while there is still just a single editor where changes need to be made.

One such change could be to make "conditional" a modifier that can be applied to any value type, e.g. by moving this to a separate XML attribute. That is, keys such as `access:conditional=*` or `vehicle:conditional=*` apply conditional restriction syntax to access values, `maxspeed:conditional=*` applies the same syntax to speed values, `maxheight:conditional=*` to height values, `turn:conditional=*` to turn restriction types, and so on.

Even if this is not something Vespucci's CR editor can do today, it would seem sensible to anticipate the possibility in the preset format.

**Comment by Sarabjeet108** [comment]
Are there any additional points to consider when introducing the "conditional" modifier as an attribute, such as determining in which keys it should/should not be applied?

 Despite being applicable to any type of value, certain keys may not support the "conditional" modifier.

**Comment by simonpoole** [comment]
> Despite being applicable to any type of value, certain keys may not support the "conditional" modifier.

That was the reason that I added the value initially. However there are no current issues detecting conditional tags via the ":conditional" suffix, so IMHO for now this can wait. Preset schema version 1.16 removes the value, see https://github.com/simonpoole/preset-utils/blob/master/src/main/resources/vespucci-preset-1.16.xlmns
