### ISSUE TITLE
Unable to upload note (Android 10 and higher)

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2255]
Description:
---

@matkoniecz

Button is grayed out

Device info:
---
<table>
<tr><td>App version</td><td>19.0.0.1</td></tr>
<tr><td>App version code</td><td>2400</td></tr>
<tr><td>Android build version</td><td>V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QKQ1.191002.002.V11.0.5.0.QDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Mateusz Konieczny"/>Mateusz Konieczny</A></td></tr>
</table>

**Comment by simonpoole** [comment]
New or modified note?

If modified, state change or new comment or both?

Which button?

**Comment by matkoniecz** [comment]
> New or modified note?

both new and modified note

> If modified, state change or new comment or both?

new comment, state change works fine

> Which button?

save, upload, "open" dropdown

I can upload screen recording, I just reproduced it at home.

**Comment by simonpoole** [comment]
> I can upload screen recording, I just reproduced it at home.

That would be good as it is not reproducible here, nor did the tests fail when building the release.

**Comment by simonpoole** [comment]
Ping @matkoniecz

**Comment by matkoniecz** [comment]
https://user-images.githubusercontent.com/899988/235658682-7befc7a4-56cb-4fcc-8640-f44d58f379e9.mp4

you can also see a different issue: you cannot end text input in normal mode, you need to rotate phone (it was already present earlier)

**Comment by simonpoole** [comment]
This seems to be an actual regression, however only effects devices on Android 10 and higher (which is why it fell through the cracks pre-production release).
