### ISSUE TITLE
Remove suggestions for layers that are no longer at new location

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2260]
We tapped a bookmark that took us from North America, to Asia. When we arrived in Asia we were warned that there is no imagery for the Canvec layer here. However it is still in the list of suggestions as you see. Therefore, when making the warning, you might as well automatically kick it off the list of suggestions too.

![Screenshot_20230429-110526.jpg](https://user-images.githubusercontent.com/1230959/235280739-e08c9abd-415f-4a66-967a-7049173abeb8.jpg)

(Yes, we only got the warning because that was our current layer at the time.)

Another idea, would be, when displaying the above list, first do a check to see if each one is valid for the area we are in.

**Comment by jidanni** [comment]
And, can you believe it, even though I was later switching back and forth among some local layers, the foreign layer has eased its way up right into first place!
![Screenshot_20230429-112106.jpg](https://user-images.githubusercontent.com/1230959/235281229-6c25b32b-d66f-4795-9993-6f32ab3bfd75.jpg)

**Comment by simonpoole** [comment]
The layers are the ones you last used. 

Removing (and therefore loosing) them when they are no longer are applicable to the current area would work against one of the major use cases: making it easy to switch between layers that you just used. And yes that could be just over a boundary of one layer.
