### ISSUE TITLE
How will OverPass Query work?

### ISSUE THREAD

**Issue by afgb1977** [MarcusWolschon/osmeditor4android#2261]
What should we expect from the new search function in OverPass API?
I have done different tests and the search in OverPass API works correctly.

**Comment by simonpoole** [comment]
The data is loaded automatically. Depending on the checkbox it either replaces the existing data *default or is merged with it.

**Comment by afgb1977** [comment]
The search screen in OverPass API shows a dropdown menu at the bottom right (3 dots) with 3 options=
1. Save
2. Load
3. Share
Option 1 create a 0 byte file.
What information should go there?
- The search results (.osm file) ?
-  Query text ?
![Screenshot_20230429-011201~2](https://user-images.githubusercontent.com/128996366/235287426-e723f704-9f64-42f1-bec9-676a6e2031b7.png)

**Comment by simonpoole** [comment]
>     1. Save
> 
>     2. Load
> 
>     3. Share

These are for saving, loading and sharing queries, not for the data.

**Comment by simonpoole** [comment]
Any more questions?

**Comment by afgb1977** [comment]
> Any more questions?

Yes, please don't close the thread, I'm doing more tests and I have some questions and comments.

**Comment by afgb1977** [comment]
> Any more questions?
Is it possible that the downloaded OverPass file has "Line Wrap"?
The file text is on a single line, it's easier to scroll down in the code editor.

P.S. Nearby Nodes does not detect the "Bus Stops"
I had other small comments but I think they are the result of a mistaken request on my part to the OverPass API.
I can only say that this new version is fantastic and except for the screen dimming, it is working very well. Thanks guys for your work.

**Comment by simonpoole** [comment]
> > Any more questions?
> 
> Is it possible that the downloaded OverPass file has "Line Wrap"? The file text is on a single line, it's easier to scroll down in the code editor.
> 
You can simply insert new lines. Try generating a query from "Object search" to see that, they should be maintained of save/load.

> P.S. Nearby Nodes does not detect the "Bus Stops"
Example?

**Comment by afgb1977** [comment]
![Screenshot_20230430-173752~2](https://user-images.githubusercontent.com/128996366/235379242-cd88ac3f-b4b4-4ce4-ada3-506adbf0cc92.png)

**Comment by simonpoole** [comment]
See http://vespucci.io/help/en/Main%20map%20display/#nearby-point-of-interest-display the default behaviour doesn't show highway of public_transport objects (and currently the default configuration is hardwired, making it configurable is something I though of doing and which might be added). 

However any filter will override this, so if you add a  tag filter with .* .* you will get literally all objects with tags.

**Comment by simonpoole** [comment]
Question from my side, can you give me your device / Android details? The text in the buttons shouldn't be wrapping and be restricted to one line, and it is interesting that your device is showing different behaviour.

**Comment by afgb1977** [comment]
> Question from my side: can you give me your device / Android details? The text in the buttons shouldn't be wrapping and be restricted to one line, and it is interesting that your device is showing different behaviour.

NOKIA G50 TA-1367, Android 13
