### ISSUE TITLE
Esri World Imagery zoom broken

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2264]
The Esri World Imagery zoom is broken in Vespucci, but works fine in iD.

No I cannot find the issue I reported about it earlier.

![Screenshot_20230430-231325.jpg](https://user-images.githubusercontent.com/1230959/235361074-7df5fe94-1be9-4188-b5b7-5446d7a65d39.jpg)

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/issues/2126

Im the mean time it has been fixed on ELI so you can simply update the configuration.

**Comment by jidanni** [comment]
Will removing and reinstalling Vespucci fix it?

**Comment by simonpoole** [comment]
No. Update the update imagery layer configuration see https://vespucci.io/help/en/Main%20map%20display/#tools

Use the update from ELI entry.

**Comment by jidanni** [comment]
Okay, that worked!

However average users never going to imagine to go looking in that far away menu. 

So it would be best if the thing updated automatically every week or something.

Else average users will just go around for the rest of their lives thinking that, well, somethings are just broken and they have to accept that.

**Comment by simonpoole** [comment]
Everybody already gets an update once per month.
