### ISSUE TITLE
Allow long press to be multi-select

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2266]
Here I have one node  selected. If I long press another node, the phone just beeps. Might as well make it add the other node to the selection.

Yes in the menu there is 'extend selection" but this could be a new shortcut.

![Screenshot_20230502-165409_1 - Copy.jpg](https://user-images.githubusercontent.com/1230959/235625407-3e65f6b4-7b03-4a85-9e12-ed77594f21ff.jpg)

**Comment by simonpoole** [comment]
Nope.
