### ISSUE TITLE
Old and new are the same

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2273]
Here we are looking at what changed but the coordinates are the same so why is it reminding us that they are different or something with the old and new? It shouldn't.
![Screenshot_20230504-082504.jpg](https://user-images.githubusercontent.com/1230959/236079561-4d50c722-5246-49ba-9f7b-b42faf0c427d.jpg)

How did we get here? Well it is on a node that got merged into.

In other words the things that were attached to it changed. But not the node itself. Because the coordinates are exactly the same. So the program shouldn't list them as the things that have changed.

![Screenshot_20230504-082520.jpg](https://user-images.githubusercontent.com/1230959/236079711-656b913c-a571-44ee-9517-96eae1602f0d.jpg)

I mean it is great that it's in the list, but when we look at the details we are told to compare the old and new coordinates but they're exactly the same so that shouldn't be on the list of things of that we're supposed to compare.

**Comment by simonpoole** [comment]
There is no harm in uploading an object that hasn't actually changed it will get a new version and that's it.

**Comment by jidanni** [comment]
I'm just saying it's wrong to have tables where both sides are the same thing.

Keep the item, but just don't attach the table to the item.
