### ISSUE TITLE
Now just grey screen of death 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2274]
Vespucci now refuses to start anymore. It says loading. Then we switch to a gray screen. And then after a few seconds we're back into our cell phones launcher. Yes I tried clearing the cache in Android app settings.  logcat.txt:

"05-04 14:51:23.629 I/TileLayerSource(4648): Trying to read custom imagery from /storage/emulated/0/Download/Vespucci/imagery.geojson
05-04 14:51:26.915 I/l7.h    (4648): Loading downloaded preset, directory=/storage/emulated/0/Download/Vespucci/autopreset
05-04 14:51:26.930 I/        (4648): No usable old MRU list, creating new one (java.io.FileNotFoundException: /storage/emulated/0/Download/Vespucci/autopreset/mru.dat (No such file or directory))
05-04 14:51:26.936 D/MRUTags (4648): Loading from /storage/emulated/0/Download/Vespucci/mrutags.xml
05-04 15:00:26.919 I/TileLayerSource(10065): Trying to read custom imagery from /storage/emulated/0/Download/Vespucci/imagery.geojson
05-04 15:00:29.555 I/l7.h    (10065): Loading downloaded preset, directory=/storage/emulated/0/Download/Vespucci/autopreset
05-04 15:00:29.565 I/        (10065): No usable old MRU list, creating new one (java.io.FileNotFoundException: /storage/emulated/0/Download/Vespucci/autopreset/mru.dat (No such file or directory))
05-04 15:00:29.569 D/MRUTags (10065): Loading from /storage/emulated/0/Download/Vespucci/mrutags.xml
05-04 15:01:21.194 D/LauncherLog(10286): AppsCustomizePagedView - syncAppsPageItems page: 3 index: 60 Item: Vespucci"
 content://ru.zdevs.zarchiver.external/storage/emulated/0/Android/data/ru.zdevs.zarchiver/files/logcat.txt#:~:text=05%2D04%2014,60%20Item%3A%20Vespucci

**Comment by jidanni** [comment]
I would go into the menus but I can't get to them.

**Comment by jidanni** [comment]
https://vespucci.io/tutorials/reporting_issues/ seems to say I should have seen some prompt about reporting crashes. But when this happens. There is nothing. We're just back on the launcher screen. Plus there is no opportunity to send any crash information in. Android 8 ASUS.

**Comment by simonpoole** [comment]
I would suggest restarting your phone.

**Comment by simonpoole** [comment]
> https://vespucci.io/tutorials/reporting_issues/ seems to say I should have seen some prompt about reporting crashes. But when this happens. There is nothing. We're just back on the launcher screen. Thus there is no opportunity to send any crash information in. Android 8 ASUS.

You are not getting a crash dump prompt because it isn't vespucci crashing.

**Comment by jidanni** [comment]
In https://vespucci.io/tutorials/faq/ we see several tips about just clearing out the app's data.

But there is no mention there that this will also wipe out your passwords and all your preferences and everything.

**Comment by jidanni** [comment]
I tried restarting the cell phone but that didn't fix the problem.

I'm not going to take the step of clearing the app's data because this is a valuable opportunity  where we can fix this problem.

The FAQ says

> To recover from the directory containing the tile database not being writable you do not need to re-install Vespucci, simply clearing the apps data in your application manager is enough. If the problem is related to access to a removable storages, disabling the "Prefer removable storage" in the Advanced preferences "Layer download and storage" section may help.

Anyway you need to warn people that they're going to see this message

![Screenshot_20230504-153543.jpg](https://user-images.githubusercontent.com/1230959/236142329-6240c24b-c3d8-463e-8289-29951dd0d7dc.jpg)

> To resolve you can clear all the data for the app (upload any pending changes before that), or you can try to simply remove the database file,. The location is typically (on removable storage or on the internal "sdcard") in Android/data/de.blau.android/files/databases/ remove osmaptilefscache_db.db and the accompanying journal file too

And I need above only at the very end do we see that it is only talking about the tiles.

**Comment by simonpoole** [comment]
If restarting didn't help you can try re-installing the version you already had installed to rule out that the problem is caused by corruption of the binary on device.

**Comment by jidanni** [comment]
https://support.google.com/googleplay/answer/113410 
mentions  reinstalling but it doesn't seem possible.. will probably need adb. Thus will probably have to wait half month.

**Comment by simonpoole** [comment]
You can try downloading the apk from the repo and installing that, as it is signed with the same key as the google play store build it should just work.

**Comment by jidanni** [comment]
Okay it going to take a while to find the actual dot APK link on https://github.com/MarcusWolschon/osmeditor4android/releases/tag/19.0.0.3

**Comment by jidanni** [comment]
It looks like I'll just have to downgrade in order to get the APK:
https://github.com/MarcusWolschon/osmeditor4android/releases/tag/18.1.5.0

**Comment by jidanni** [comment]
Wait I found
https://github.com/MarcusWolschon/osmeditor4android/releases/download/19.0.0.1/vespucci-19.0-BETA-1-signed.apk
That's not too old. I'll try that!

**Comment by jidanni** [comment]
Check your mailbox or whatever to see if the app is actually sending a lot of crisis messages to you. There should be about 20 of them all coming from an Asus cell phone.

**Comment by simonpoole** [comment]
There are no crash reports, I'll check the play store for ANRs but you would have got the corresponding Android model in that case. The log excerpt doesn't indicate anything out of the ordinary except the last entry which I suspect is from the launcher you are using. Does the log contain everything till the loading stops? (Is the phone rooted btw?)

**Comment by simonpoole** [comment]
> I'll check the play store for ANRs but you would have got the corresponding Android modal in that case.

As expected no ANRs.

**Comment by jidanni** [comment]
Indeed it creates a new Downloads/Vespucci before it gets stuck.

**Comment by jidanni** [comment]
Okay in Matlog logcat I instead used the keyword "blau" and found much more details.

![logcat.txt](https://github.com/MarcusWolschon/osmeditor4android/files/11395850/logcat.txt)

**Comment by simonpoole** [comment]
Essentially that indicates that the app was killed by the system potentially because of an OOM event. Do you have the full log up to 17:12:13.618 ? Likely the interesting bits are not tagged with the apps package name.

Did you have a lot of GPX layers loaded?

**Comment by jidanni** [comment]
I think I had one GPS layer that's been there for weeks and isn't very large.

**Comment by simonpoole** [comment]
So the full log clearly shows that the app starts up correctly and the relevant main state files are all loaded successfully. The next thing that happens is that the app is killed (no crash dump or similar). Have you installed any app killers or does your version of android has something like that installed, potentially this could be in the developer preferences. Any other new installed apps.

I would rename the GPX file, but I don't see any reason in the log that that would cause the issue.

**Comment by jidanni** [comment]
turning off battery optimization for this app, https://www.howtogeek.com/762936/how-to-stop-android-from-killing-background-apps/amp/ didn't help.

I'm thinking perhaps that have gets into some infinite loop,

`while(1){}`

So something else, maybe the kernel, killed it.

**Comment by jidanni** [comment]
Maybe it was getting some file from the network on the network had a problem so only got half the file. And then every time it tries to read that file there's some loop that gets caused.

I guess I'll have to take a look at the end of the month when I can use ADB, and then can proceed and give you a report on what all the internal files look like.

**Comment by simonpoole** [comment]
External files should all have been read by the time the app gets terminated, essentially the only candidate would be the GPX file in any case (which why I suggested to rename it, just to rule that out). If you didn't configure a layer that references something online then there is nothing that would cause any network accesses (outside of the downloading OSM data etc).

**Comment by jidanni** [comment]
Here we see the screen that we stare at for 20 seconds.

![Screenshot_20230505-032017_1 - Copy.jpg](https://user-images.githubusercontent.com/1230959/236309763-3abb3d03-2b0d-4df3-ae0d-25d18ad402db.jpg)

The first problem is, couldn't this screen have some words on it, like "please wait"  or something?

Okay, I suppose that we are only supposed to see the screen for about a half a second. And the reason why it takes 20 seconds, is there must be that infinite loop going on.

We also notice in the upper left corner two icons. One is for a screenshot that I recently took. The other is for https://play.google.com/store/apps/details?id=simple.batttery.alarm .

Now, the amazing thing is, after Vespucci disappears and we are back staring at the launcher, that second icon is gone from the top of the screen!

![Screenshot_20230505-032046_1 - Copy.jpg](https://user-images.githubusercontent.com/1230959/236310633-b5c5d5cb-325c-4d30-88e8-b2b850a2efd8.jpg)

I checked the running processes listing and it's definitely not running at all anymore.

So whatever is killing Vespucci is also killing it.

(It is an alarm that will tell me when my battery is charged to 99%. I have it start every time upon power up.)

Yes maybe it is some Google Play Services thing that is doing this. But I stopped all those processes, but then they started up again anyway.

**Comment by simonpoole** [comment]
> Android 8 ASUS.

Is this a zenfone 3? If it is, seems as if an ANR report has arrived on googles play store from roughly 28 hours ago which could fit. However you never mentioned getting the ANR modal.

**Comment by jidanni** [comment]
Yes. Zenfone 3!
I was going to mention it. But you know what happened? I was going to copy the GitHub bug number into the little place where it asks me for comments but by the time I switched back to the screen, it was gone, so I assume you never got it.

In fact of the many times I ran the program there was only one time it  caused the anr. All the others were just simply the app disappearing after 20 seconds.

**Comment by simonpoole** [comment]
> In fact of the many times I ran the program there was only one time it caused the anr.

And did you wait? (from the sump there is no indication that anything specific is going on it is simply drawing a way, deep in Androids library code).

**Comment by jidanni** [comment]
He asked me if I wanted to add any comments. So I switched to the other window to copy the GitHub bug number, and when I switched back it was gone.


Anyway, please see if you can reproduce it by simply making an infinite loop.
https://stackoverflow.com/questions/3332656/is-it-possible-to-detect-an-endless-loop
First start with a simple infinite loop. Then if after 20 seconds that doesn't get killed, then add some battery hungry behavior to it also.

The more bad behavior you can add into it the sooner or whatever police force is doing a killing will wake up and then kill all the wasteful jobs. In fact as you saw it killed more than one, it  killed my other app too.

And if this all actually is successful and reproduces the behavior, then we'll think about ways to fix it.

**Comment by simonpoole** [comment]
> It asked me if I wanted to add any comments.

I was referring to the ANR modal.

> Anyway, please see if you can reproduce it by simply making an infinite loop.

An infinite loop will lock up your phone and do all kind of bad things, there is no need to test that. You seem to be forgetting that it is -your- phone doing this, not that of anybody else, so unless you want to send your phone here, you need to stop wild speculation and provide more facts so that we can narrow down what could potentially be causing the issue, For example where you were editing before this occurred. This doesn't imply that there is anything happening that is under our control, actually everything up to now would indicate it isn't.

**Comment by simonpoole** [comment]
Note that beta 3 is available now, not likely  to help, but I would still suggest installing it.

**Comment by jidanni** [comment]
You are right, updating didn't help.

I do notice one new thing: if I switch away from Vespucci during the 20 seconds, the other app doesn't get killed.

Okay, at the end of the month, using adb, I'll compare the file system, with the APK's file system.

I think on the dreadful day that started happening, I was switching on and off my Wi-Fi at the time.

**Comment by jidanni** [comment]
Looking at logcat, we see even the launcher itself gets killed,
```
05-07 01:39:57.650 I/ActivityManager(1542): Process com.asus.launcher (pid 11401) has died: vis  BFGS
```

https://developer.android.com/reference/android/app/AppOpsManager apparently involved.

**Comment by jidanni** [comment]
Just a guess... 
https://stackoverflow.com/questions/7316680/process-has-died

**Comment by simonpoole** [comment]
That thread is 11 years old and has no bearing on the issue.

**Comment by jidanni** [comment]
( Skype was also crashing.
Removing updates to market://details?id=com.google.android.webview fixed that, but not Vespucci. )

**Comment by simonpoole** [comment]
> There is a bug with restoring map data. If there are ways with triangles on the side, indicating which side is down, Vespucci for some reason may fail to load the data.

That has previously never been reported. 

It would seem to be unlikely that the issue has to do with restoring the data, as the saved state doesn't actually include the stying information, but could be something going on with rendering after a restore.

**Comment by simonpoole** [comment]
> v19.0.0.0 fdroid: load a place with retaining walls, manually restart Vespucci - crash at 'loading data' or gray screen
> 
> downgrade to v18.1.5.0: load the same place (which now renders differently), restart - everything works ok

This is not reproducible here, neither with 18.1 with embankments nor with 19.0 with retaining walls. Not saying that it isn't happening for you, but there must be further circumstances that cause this to happen.

Can you provide some further details, for example a link to an area / object with which you've had the issue, and what to you exactly understand under "manually restarting"?

**Comment by simonpoole** [comment]
ping @AntonKhorev

**Comment by AntonKhorev** [comment]
- tablet with Android 6.0 (Lenovo TAB 2 A10-70L) - crashes on data with embankments
- phone with Android 7.0 (Samsung Galaxy A3) - same
- maybe it works on newer devices?
- crashes also happen on Vespucci 17.0.1.0, although it doesn't seem to render triangles for embankments
- "manually restarting" = Android settings > Apps > Vespucci > Force stop

**Comment by AntonKhorev** [comment]
Vespucci 16.1.3.0 crashes. So it's some change between 16.1.2.0 and 16.1.3.0. I installed older versions from F-Droid Archive repository.

**Comment by AntonKhorev** [comment]
> @AntonKhorev it is fairly clear that your issue doesn't have anything to do with this one. As a temporary workaround I would suggest using a datastyle without path patterns.

Not so clear to me. When my crash happens it also kills other apps. I'm not sure if @jidanni tried clearing the data. If he tried and it didn't help, then maybe it's a different issue.

**Comment by simonpoole** [comment]
I just tested on an Samsung S5 with Android 6.0.1 no problems. A concrete example of real OSM data where the issue happens would be really useful.

> * "manually restarting" = Android settings > Apps > Vespucci > Force stop

You should never do this except if the app is really hanging, it will end with potential corruption of state files and so on. To exit the app completely simply press the back button.

**Comment by AntonKhorev** [comment]
Pressing back button twice and restarting Vespucci doesn't cause the crash.

**Comment by AntonKhorev** [comment]
> This sounds very much like an Android issue, do you have any developer options turned on?

I have USB debugging on.

**Comment by AntonKhorev** [comment]
Turned off developer options on the tablet where I haven't modified styles - still crashes.

**Comment by AntonKhorev** [comment]
I first encountered this crash when I edited this park last year:
https://www.openstreetmap.org/relation/2653740#map=16/59.9444/30.3368

I suspected that there's something in the data that Vespucci doesn't like. I started to download smaller areas to find where the crash happens. Eventually I narrowed it down to this embankment way: https://www.openstreetmap.org/way/1002092895 Then I was able to replicate it on any empty place where I add only an embankment way and restart Vespucci. I kept editing the park making sure Vespucci is not restarted until the edit is done. I was going to report this issue but then crashes stopped even when I had the entire park loaded. Maybe adding something to the data can negate whatever causes the crash? So I forgot about it for a while.

Later I was editing this place with retaining walls https://www.openstreetmap.org/#map=19/59.93138/30.29245 I updated to Vespucci 19.0.0.0 and it crashed.

**Comment by simonpoole** [comment]
I've been able to recreate this (after a forced stop) in the area you pointed to, see https://github.com/MarcusWolschon/osmeditor4android/issues/2298 Right now it simply seems to be an issue with Skia.

Please continue the discussion there are it clearly doesn't have anything to do with @jidanni issue.

**Comment by simonpoole** [comment]
> but in bookmarks.ser.backup.gz the last one seems to be missing...
backup.der is the old save format for bookmarks and no longer used, see https://github.com/MarcusWolschon/osmeditor4android/blob/master/CHANGELOG.txt#L26
> 
> [bookmarks.ser.backup.gz](https://github.com/MarcusWolschon/osmeditor4android/files/11630905/bookmarks.ser.backup.gz)
> 
> So maybe something about bookmarks is garbled.
Nope.
> 
> Maybe the program should first scan the bookmarks to see they are OK, before attempting to use them... and crash. (Wild guess.)
> 
> In fact if you could release a new version that upon starting simply first checks the validity of the various files it reads in and prints error messages instead of 'getting stuck', then maybe such corruption wouldn't be 'ruin things forever'. (Again, just a wild guess. The program perhaps already checks...)
> 
Yes naturally "the program checks" and as we already established here https://github.com/MarcusWolschon/osmeditor4android/issues/2274#issuecomment-1534679733 that the program does read the state files correctly and that the hang is later on.

> Anyway I can post the whole backup.ab here. Just tell me which file(s) have my password in it so I can edit it out. Thanks.

If you haven't entered a password in the preferences, which you shouldn't have for the standard OSM API, then we don't store any passwords in the app.

**Comment by simonpoole** [comment]
Revisiting the ANR report, it seems as if this could actually be related to @AntonKhorev report, just that you never mentioned anything about force stopping the app.

```  
      #00  pc 0x00000000002df394  /system/lib64/libskia.so (SkPathRef::Editor::Editor(sk_sp<SkPathRef>*, int, int)+196)
      #01  pc 0x00000000002d6c7c  /system/lib64/libskia.so (SkPath::lineTo(float, float)+176)
      #02  pc 0x00000000002d9420  /system/lib64/libskia.so (SkPath::addPath(SkPath const&, SkMatrix const&, SkPath::AddPathMode)+172)
      #03  pc 0x0000000000340724  /system/lib64/libskia.so (SkPath1DPathEffect::next(SkPath*, float, SkPathMeasure&) const+452)
      #04  pc 0x0000000000340160  /system/lib64/libskia.so (Sk1DPathEffect::filterPath(SkPath*, SkPath const&, SkStrokeRec*, SkRect const*) const+128)
      #05  pc 0x00000000003402ac  /system/lib64/libskia.so (SkPath1DPathEffect::filterPath(SkPath*, SkPath const&, SkStrokeRec*, SkRect const*) const+60)
      #06  pc 0x00000000002d3c00  /system/lib64/libskia.so (SkPaint::getFillPath(SkPath const&, SkPath*, SkRect const*, float) const+104)
      #07  pc 0x0000000000272c3c  /system/lib64/libskia.so (SkDraw::drawPath(SkPath const&, SkPaint const&, SkMatrix const*, bool, bool, SkBlitter*) const+620)
      #08  pc 0x00000000001f26dc  /system/lib64/libskia.so (SkBitmapDevice::drawPath(SkPath const&, SkPaint const&, SkMatrix const*, bool)+92)
      #09  pc 0x00000000002113b0  /system/lib64/libskia.so (SkCanvas::onDrawPath(SkPath const&, SkPaint const&)+712)
      #10  pc 0x000000000025f86c  /system/lib64/libskia.so
      #11  pc 0x000000000051e608  /system/framework/arm64/boot-framework.oat (Java_android_graphics_BaseCanvas_nDrawPath__JJJ+168)
      at android.graphics.BaseCanvas.nDrawPath (Native method)
      at android.graphics.BaseCanvas.drawPath (BaseCanvas.java:298)
      at android.graphics.Canvas.drawPath (Canvas.java:1652)
      at de.blau.android.layer.data.MapOverlay.paintWay (MapOverlay.java:1401)
      at de.blau.android.layer.data.MapOverlay.paintOsmData (MapOverlay.java:562)
      at de.blau.android.layer.data.MapOverlay.onDraw (MapOverlay.java:463)
      at de.blau.android.layer.MapViewLayer.onManagedDraw (MapViewLayer.java:70)
      at de.blau.android.Map.onDraw (Map.java:606)
      at android.view.View.draw (View.java:19123)
      at android.view.View.buildDrawingCacheImpl (View.java:18371)
      at android.view.View.buildDrawingCache (View.java:18231)
      at android.view.View.draw (View.java:18843)
      at android.view.ViewGroup.drawChild (ViewGroup.java:4214)
      at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4000)
      at android.view.View.updateDisplayListIfDirty (View.java:18064)
      at android.view.View.draw (View.java:18851)
      at android.view.ViewGroup.drawChild (ViewGroup.java:4214)
      at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4000)
      at de.blau.android.views.SplitPaneLayout.dispatchDraw (SplitPaneLayout.java:373)
      at android.view.View.updateDisplayListIfDirty (View.java:18064)
      at android.view.View.draw (View.java:18851)
      at android.view.ViewGroup.drawChild (ViewGroup.java:4214)
      at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4000)
      at android.view.View.updateDisplayListIfDirty (View.java:18064)
      at android.view.View.draw (View.java:18851)
      at android.view.ViewGroup.drawChild (ViewGroup.java:4214)
      at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4000)
      at android.view.View.updateDisplayListIfDirty (View.java:18064)
      at android.view.View.draw (View.java:18851)
      at android.view.ViewGroup.drawChild (ViewGroup.java:4214)
      at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4000)
      at android.view.View.updateDisplayListIfDirty (View.java:18064)
      at android.view.View.draw (View.java:18851)
      at android.view.ViewGroup.drawChild (ViewGroup.java:4214)
      at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4000)
      at android.view.View.updateDisplayListIfDirty (View.java:18064)
      at android.view.View.draw (View.java:18851) 
      at android.view.ViewGroup.drawChild (ViewGroup.java:4214)
      at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4000)
      at android.view.View.updateDisplayListIfDirty (View.java:18064)
      at android.view.View.draw (View.java:18851)
      at android.view.ViewGroup.drawChild (ViewGroup.java:4214)
      at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4000)  
      at android.view.View.draw (View.java:19126)
      at com.android.internal.policy.DecorView.draw (DecorView.java:785) 
      at android.view.View.updateDisplayListIfDirty (View.java:18073)
      at android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:643)
      at android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:649)  
      at android.view.ThreadedRenderer.draw (ThreadedRenderer.java:757)
      at android.view.ViewRootImpl.draw (ViewRootImpl.java:3010)
      at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:2814)
      at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2359) 
      at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1394)
      at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6770) 
      at android.view.Choreographer$CallbackRecord.run (Choreographer.java:966) 
      at android.view.Choreographer.doCallbacks (Choreographer.java:778)
      at android.view.Choreographer.doFrame (Choreographer.java:713)  
      at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:952)
      at android.os.Handler.handleCallback (Handler.java:789) 
      at android.os.Handler.dispatchMessage (Handler.java:98)
      at android.os.Looper.loop (Looper.java:169)
      at android.app.ActivityThread.main (ActivityThread.java:6578)
      at java.lang.reflect.Method.invoke (Native method)
      at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
      at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)
```

**Comment by simonpoole** [comment]
19.0.2 adds a "Safe" shortcut that will set the data rendering style to the built-in minimal style (aka "black lines") and start the app. In my tests changing back to the regular style then works.

Note: shortcuts are only available on from Android 7.1 and later.

**Comment by AntonKhorev** [comment]
> Revisiting the ANR report, it seems as if this could actually be related to the report from @AntonKhorev, just that you never mentioned anything about force stopping the app.

"Force stopping" is only a way to reproduce the crash in controllable manner. The crash also happens when Vespucci fully restarts under normal circumstances: running other apps, updating Vespucci etc.

**Comment by jidanni** [comment]
Okay, the safe start mode allow me to start it. And then I could start it some more, and then...
![Screenshot_20230603-133750.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/0b75d932-3c82-45d3-8c72-e54661657e09)

**Comment by simonpoole** [comment]
You would waste a lot less of everybodies time if you would simply state what occured. 

Did the app crash? If it did, when did that happen, what did you change?

**Comment by jidanni** [comment]
Just tell me, for Android 8, should we users always stay in minimal mode to be safe from now on? Thanks.

**Comment by simonpoole** [comment]
As I just pointed out here https://github.com/MarcusWolschon/osmeditor4android/issues/2274#issuecomment-1575124837 the crash was independent of rendering and likely only google knows what triggers it. If you are concerned about the rendering issue, you can use the style without path patterns. See https://github.com/MarcusWolschon/osmeditor4android/blob/19.0-MAINT/CHANGELOG.txt#L16

**Comment by jidanni** [comment]
Guaranteed way to reproduce the bug:

The following will leave the user just staring at a gray screen that does nothing:

- Use Android 8.0.
- Navigate to https://www.openstreetmap.org/?mlat=43.0900596&mlon=-79.0676052#map=19/43.09006/-79.06761 and zoom out a little. 
- Download current view (OSM data)
- In preferences choose Color Round nodes
- Stop and restart Vespucci.

**Comment by simonpoole** [comment]
> Guaranteed way to reproduce the bug:

We have already established what triggers the bug. As forced closing should only be used when there is no other way to proceed, it is easily avoided. google, as far as we have been able to determine, fixed the bug not quite 5 years back, so recent devices should not be affected. There is really not really anything that we can do about it other than offer a way to recover, which we have done

**Comment by jidanni** [comment]
Actually, the program could always open the app in minimal mode. And then after the app is fully open, turn on the Data Style that the user has in his preferences.

Because the problem seems to be only occurring when the app is launched, so all that needs to be done is get past the launch phase safely, and then you can restore the data style the user has in his preferences.

**Comment by AntonKhorev** [comment]
> We have already established what triggers the bug. As forced closing should only be used when there is no other way to proceed, it is easily avoided.

Can you please forget about "forced closing"? The problem happens any time the app is fully restarted.

**Comment by simonpoole** [comment]
> The problem happens any time the app is fully restarted. 

Not on any device that I have access to, you yourself confirmed that it didn't happen if you left Vespucci via the "back" button. If this is not correct please indicate if this happens on both your devices.

>It can be avoided by clearing the data before using other apps 

Running other apps doesn't really do anything different than exiting the app. Note that "clearing the data" simply works because if there is no data there is nothing to render so Skia wont crash, it doesn't have anything to do with restoring the data itself as the style information is not saved over invocations of the app.

>  updating Vespucci / rebooting the device.
Is Vespucci running when you are doing this? Because that is potentially equivalent to a forced close.

**Comment by AntonKhorev** [comment]
> > The problem happens any time the app is fully restarted.
> 
> Not on any device that I have access to, you yourself confirmed that it didn't happen if you left Vespucci via the "back" button. If this is not correct please indicate if this happens on both your devices.

It doesn't happen when you quit with back button. And it doesn't happen when you quit with back button AND force stop / run other apps etc after quitting this way.

> > It can be avoided by clearing the data before using other apps
> 
> Running other apps doesn't really do anything different than exiting the app. 

Apparently it does. (*)

> Note that "clearing the data" simply works because if there is no data there is nothing to render so Skia wont crash, it doesn't have anything to do with restoring the data itself as the style information is not saved over invocations of the app.

"style information is not saved" is another thing you are repeating for some reason. What difference would it make if it was saved?

> > updating Vespucci / rebooting the device.
> 
> Is Vespucci running when you are doing this? Because that is potentially equivalent to a forced close.

(*) Apparently it is, just like running other apps. Basically you have to either exit with back button or clear the data before doing anything else on your device. You can't for example take photos from Vespucci.

**Comment by simonpoole** [comment]
> (*) Apparently it is, just like running other apps. Basically you have to either exit with back button or clear the data before doing anything else on your device. You can't for example take photos from Vespucci.

I would suggest checking for "memory management" apps and other things that could cause apps to be killed, because nothing of what you are suggesting is reproducible on the devices I have here that run pre-9 Android. Exiting the app regularly just invokes the normal Android activity lifecycle, just like Android will do if an app is paused and potentially later removed from memory.

**Comment by jidanni** [comment]
On ASUS, not only Vespucci dies, but it makes the entire ZenUI launcher restart, killing other apps too.

**Comment by AntonKhorev** [comment]
> I would suggest checking for "memory management" apps and other things that could cause apps to be killed, because nothing of what you are suggesting is reproducible on the devices I have here that run pre-9 Android.

Run Vespucci, load an area with line patterns, reboot the device, run Vespucci again and you'll probably get a crash after "Loading data into memory" message. Did you try rebooting? Do memory management apps mess with rebooting? Or is rebooting one of those things that shouldn't be done?
