### ISSUE TITLE
Could not find relations

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2277]
We wanted to search for:
- https://www.openstreetmap.org/relation/4230162

We followed the instructions we found in:

- https://vespucci.io/tutorials/object_search/
- https://github.com/simonpoole/JosmFilterDoc/blob/master/filter.md

Alas, we failed:
![Screenshot_20230507_183048_Vespucci.jpg](https://user-images.githubusercontent.com/1230959/236672507-f403960b-288d-48d7-ad08-8701a533efc8.jpg)

**Comment by simonpoole** [comment]
> We followed the instructions we found in:

No you didn't.

The correct expression would be

`type:relation id:4230`

**Comment by jidanni** [comment]
I see. I didn't think about the example,
> type:node & child type:way & child child id:14297825

even more thoroughly.

But all this frustration and tedious typing, could be avoided if only #844 was implemented.
