### ISSUE TITLE
Refactor Notes code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#228]
```
Notes adding and commenting should be a action mode to make the UI more 
consistent. We should further consider storing new and edited notes on device 
and saving at the same time as normal edits.

Potentially we should cache all downloaded notes and on pan etc only redownload 
new ones.
```

Original issue reported on code.google.com by `sp8...@gmail.com` on 27 Jul 2014 at 10:52
* Blocking: #207

**Comment by simonpoole** [comment]
Remaining open items:
* download and editing of references elements (Osmose)
* potentially separate download areas for autodownload
* filter for Osmose bugs
* import/export (low prio)

**Comment by simonpoole** [comment]
In some way removing notifications when the issue has been resolved would be nice.

**Comment by simonpoole** [comment]
Complete https://github.com/MarcusWolschon/osmeditor4android/commit/804ca1b458e6659e8a14684bd548779ed0b3f82c
