### ISSUE TITLE
geo: links are opened with a different zoom

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#2283]
## Vespucci Version
19.0.0

## Download source
F-Droid

## Device (Manufacturer and Model)
OnePlus 9 Pro (LE2121)

## Android Version 
LineageOS 20 (Android 13)

## Behaviour/Symptoms
Opening geo: links from OsmAnd opens them in a lower zoom than in OsmAnd (i.e. Vespucci opens them more zoomed out)

The zoom at which I shared from OsmAnd -
![Screenshot_20230517-114448_Trebuchet (1)](https://github.com/MarcusWolschon/osmeditor4android/assets/8513118/36102605-5d1c-4a50-88b7-7fbd52f08883)
The zoom at which Vespucci opened it -
![Screenshot_20230517-114503_Trebuchet (1)](https://github.com/MarcusWolschon/osmeditor4android/assets/8513118/86390aaa-af51-48fa-9bf7-a36ecffe95d8)

## Expected Behaviour
Open geo: links at the same zoom level

## How to recreate
Tap on a POI in OsmAnd - Share - geo: - Open with Vespucci.

## Crash dump submitted (no or yes + date)
no

**Comment by contrapunctus-1** [comment]
This also occurs when opening a geotagged image's location from Simple Gallery in Vespucci.

**Comment by simonpoole** [comment]
The question is if osmand specifies a zoom level or not. If it doesn't there is no way for Vespucci to use the same zoom.

**Comment by contrapunctus-1** [comment]
Both OsmAnd and Simple Gallery seem to share the zoom level. According to Intent Intercept, OsmAnd shares the current zoom level, and the latter shares z=16.

After reading your comment, though, I wonder if Vespucci should perhaps always open geo: links at a high zoom, assuming the user wants to edit the map after opening the location.
