### ISSUE TITLE
Easier way to enter longer values 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2286]
Some tags like 'description', 'fixme', 'inscription', might require 100+ character descriptions... Hard (though yes, still possible) to edit currently in Vespucci.

**Comment by jidanni** [comment]
Long pressing the one-line tall value field of an item could bring up a large textbox where the user could enter a longer entry.

It could even have a countdown "250/256" so the user could see how far away from the maximum string length he had already typed in.

No matter if in the Details panel, or the panel to the left of it, long pressing could give such large edit windows.

**Comment by simonpoole** [comment]
Long press is used by Android in EditTexts for providing copy & paste functionality.

**Comment by simonpoole** [comment]
As a general note, I might add a modal with a large edit text for tags that are expected to be more than a small number of characters.

**Comment by jidanni** [comment]
> Long press is used by Android in EditTexts for providing copy & paste functionality.
> 
> I would recommend trying Androids support for voice entry if your device and keyboard supports it (not this is independent of Vespuccis voice support).

Yes, but then one
```
Gets a very long line that goes off the page and invariably has one or two voice typos that need to be corrected but may lie beyond the edge of the screen. Although indeed possible to access and edit, but still very difficult and error prone. Just like trying on a cellphone to proofread / correct this very long line I have typed here.
```
