### ISSUE TITLE
Changing the role of a relation member is not recognized by the program as an edit

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#2287]
If you select an object that is a member of a relationship and go to the "Relations" tab in the editor panel and change the role of this member there, then when you exit the editor, the number of edits ready to be sent to the server does not change.  If you change the role of this member of the relation by editing the relation itself in the "Members" tab, then in this case the number of edits changes.

## Vespucci Version
19.0.0.0

## Download source
google play store

## Device (Manufacturer and Model)
Redmi Note 10 Pro

## Android Version 
13

**Comment by simonpoole** [comment]
Thanks for the report!
