### ISSUE TITLE
Snap mode: junction points should be even more magnetic than lines

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2301]
The program is working correctly. Snap mode is on, and the program has joined our new node to the nearest line.

![Screenshot_20230602_073527_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/7e0831c9-20b3-4930-93f6-4c18e1f4e4ed)

![Screenshot_20230602_073539_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/01eaa5fc-9934-4e28-9cc5-4e5e7f2f7bcc)

The problem is, it should have also noticed that there was  a nearby junction point with even more lines.

So although it might be a tiny bit farther away, it should still have more magnetic attraction forces.

I found I could get it to attach to the junction point, but I needed to zoom in even more, to the extreme maximum.

Any less zooming and it was too hard  get my position perfectly on top of the point to make it have priority over simply joining to ~~an arbitrary place~~ the nearest place on the line.

**Comment by simonpoole** [comment]
You need to zoom out more, not zoom in. The size of "touch" area around nodes and ways is zoom independent and a (customizable) fixed number of pixels. With other words if you want to make it larger relative to the geometries you are editing you need to zoom out which makes editing "coarser".

**Comment by jidanni** [comment]
That is great advice. I wish https://vespucci.io/help/en/Simple%20actions/#snap would mention it.

And the only thing I found related that is customizable is
https://vespucci.io/help/en/Advanced%20preferences/#show-tolerance
