### ISSUE TITLE
Add preference: disable way dragging 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2302]
There is a preference
- Enable way node dragging

There should also be a preference
- Disable way dragging

Many people, in their entire lives, never intend to casually move entire shorelines, power lines, highways or whatever around. I guarantee you never in their lives. So it would be great for them to be able for them to turn it off.

Yes, sometimes one wants to move an entire building northwest 2 m, but not larger objects usually.

**Comment by jidanni** [comment]
We **do** want to edit geometries.
We want to
- add tagged nodes
- add ways
- move way nodes
- in fact everything, except:

moving an entire way.

For that we like iD's method of clicking the way, then in a menu, choosing "move".

It's much safer.

**Comment by simonpoole** [comment]
Thats why you have to select the way first.

**Comment by jidanni** [comment]
Yes, we select the way to be able to individually drag its nodes.
E.g., refining a coarsely drawn shoreline to a more exact version.
But if we accidentally grab anywhere along it not at a "O" or "X" point
(nodes and halfway points), we end up moving the entire line!

**Comment by simonpoole** [comment]
You are using an option that is intended for mouse/pen usage (that you were made aware of) and then moaning that it doesn't work that well when you don't use it with mouse/pen.

**Comment by jidanni** [comment]
The only thing I recall about "mouse/pen" is there is a style called "pen round nodes".
Must be because they are smaller, like a tip of a pen.

Anyway, it never occurred to me that parts of Vespucci were only for use on cellphones with stuff attached to them, that one couldn't use with just one's fingers.

Anyway it works great with one's fingers....

Except one thing:

Too easy to move a way instead of the intended X or O point.

I'm saying you've got a $50,000 invention here: being able to move the points in a selected way one by one very conveniently.

It's only that there is one danger: moving the entire way, which many users would never want to do ever usually.

**Comment by simonpoole** [comment]
See http://vespucci.io/help/en/18.0.0%20Release%20notes/#way-geometry-editing-changes

**Comment by jidanni** [comment]
OK, but new users won't be looking in old release notes, so won't know that, and

> As this may be problematic on small screen devices and when editing with fingers, this is by default turned off,

it isn't in fact problematic at all with fingers. What's problematic is accidentally moving entire ways.

Much more damaging that accidentally moving a single node. (So the default is: disabled.)

But for moving entire ways, the default is: Enabled, with no way to turn it off.

Yes, it is not that bad: the user can always undo one step.

But if he moved an entire way a little, and didn't notice, and kept on editing (the same way), and maybe even saved his changes. Then fixing the mess is a lot of work.

**Comment by simonpoole** [comment]
Closing because of constant trolling.
