### ISSUE TITLE
Don't say Type value

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2303]
![Screenshot_20230602_103845_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/fbb8f643-3484-445e-b255-f58b7a3eae59)

Don't say Type value. Just say value. That way it will be the same as the Details page (key:value, not key:type value). Or just leave it white.

Otherwise, the addition of a verb here is confusing.

**Comment by simonpoole** [comment]
It is totally in line with the other hints on the property tab.
