### ISSUE TITLE
Diff view in 'Review changes' doesn't show difference for deleted website tag

### ISSUE THREAD

**Issue by riQQ** [MarcusWolschon/osmeditor4android#2304]
## Vespucci Version
19.0.0

## Download source
F-Droid

## Device (Manufacturer and Model)
Google Pixel 6a

## Android Version 
Android 13 

## Behaviour/Symptoms
Diff view doesn't show `website` tag as changed and doesn't show the old value.

![Screenshot_20230603-122148](https://github.com/MarcusWolschon/osmeditor4android/assets/3404787/4668f7cd-d4ac-4d66-8f47-065fa3e7a6f2)

## Expected Behaviour
Diff view shows `website` tag as changed and shows the old value.

## How to recreate
Is reproducible on multiple nodes. Example https://www.openstreetmap.org/node/5915334152. Edit the tags, mark the checkbox of the website line and delete it. Open the diff view (review changes).

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
\-

**Comment by simonpoole** [comment]
Thanks for the report!

**Comment by riQQ** [comment]
Thanks for the quick fix 👍
