### ISSUE TITLE
Add tooltip to 'Snap to node' option when appending to a way

### ISSUE THREAD

**Issue by riQQ** [MarcusWolschon/osmeditor4android#2307]
Add a tooltip on long press to the 'Snap to node' option when appending to a way to further explain the function of this button. The other buttons in the button bar already have a tooltip.

I'm talking about the button / switch circled in red in this screenshot.
![Screenshot of the app when appending to a way with the button bar at the bottom](https://github.com/MarcusWolschon/osmeditor4android/assets/3404787/fedaade0-a935-43b2-8d06-4d6f5841e918)

**Comment by simonpoole** [comment]
It isn't clear if this is possible with a reasonable amount of effort. Standard menu items will automatically display the menu title on long press, however when you set an ActionView (as we do here) it doesn't work automatically.
