### ISSUE TITLE
opening_hours editor

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#232]
```
Special editor for opening_hours and related tags. Has been in the works for a 
while now, issue for documentation purposes.
```

Original issue reported on code.google.com by `sp8...@gmail.com` on 29 Aug 2014 at 3:54

**Comment by ypid** [comment]
You might find [ComplexAlarm](https://github.com/ypid/ComplexAlarm) useful. Please do not try to implement the [oh specification](https://wiki.openstreetmap.org/w/index.php?title=Key:opening_hours/specification) yourself.

**Comment by simonpoole** [comment]
Pushed back to 0.9.7

**Comment by simonpoole** [comment]
See WIP  https://github.com/simonpoole/OpeningHoursFragment and https://github.com/simonpoole/OpeningHoursParser

**Comment by simonpoole** [comment]
Pushed back to 0.9.8 since the UI part or this task hasn't made a lot of progress yet.

**Comment by simonpoole** [comment]
I've at last got around to working a bit on this, simple (typical) OH string:
![oh_simple](https://cloud.githubusercontent.com/assets/1011860/16396440/feac2c54-3cbe-11e6-98cc-044bd5f6678d.png)

Highlight location of a parse error:
![oh_parse_error](https://cloud.githubusercontent.com/assets/1011860/16396447/03bd42dc-3cbf-11e6-99b2-f5290858acd9.png)

**Comment by HolgerJeromin** [comment]
Looks awesome. 
Please add public holiday PH and school holiday SH as pseudo days

**Comment by HolgerJeromin** [comment]
Between 12 and 13 the first example needs a comma, 
Not ;

**Comment by simonpoole** [comment]
@HolgerJeromin the current way I group rules for display purposes is that everythig with the same "large" selector (years, months etc) gets in the same group, likely the title in the bar should be "Group 1" to make this clearer. So both a "," and a ";" would result in the same layout (this is mainly to sayve space and to avoid multiple redundant restatements of the same).

WRT to SH & PH the intent is that you will be able to add and edit everything with the GUI.

**Comment by simonpoole** [comment]
Integrated in to the beta https://github.com/MarcusWolschon/osmeditor4android/commit/e7f9e38428f8c04c0026041d0eaf95c18f6d6789

**Comment by simonpoole** [comment]
While there are still a few things remaining on the OpeningHoursFragment side, the integration in vespucci (without ConditionalRestrictions) is complete.
