### ISSUE TITLE
Mapbox imagery requires private apikey now

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2323]
![Screenshot_20230618_062330_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/8e40a38d-3c44-4577-a431-eee82ef8c1bc)

Mapbox, available in iD here in Illinois, is oddly absent from the Vespucci imagery choices.

**Comment by simonpoole** [comment]
Mapbox now requires an apikey, see https://github.com/osmlab/editor-layer-index/commit/cc3f64158fac656c9c09fc9e894f1362e29c2ea1 , but we don't have one.

**Comment by jidanni** [comment]
Maybe the failed items should still be listed on the bottom of the list in grey.
That way the user would know that some layer was, yes, intended to be available,
but some problem happened.

Else like today, detection relies on "I swear before winter vacation our class had a student called Ralph. But when I look over there is no empty seat. So I guess his family moved away."

**Comment by simonpoole** [comment]
As a rule we don't list any URLs that require an API key when we don't have one, for pretty obvious reasons.
