### ISSUE TITLE
Query OverPass

### ISSUE THREAD

**Issue by afgb1977** [MarcusWolschon/osmeditor4android#2324]
I just tried to do a simple search for natural=peak and Vespucci doesn't return any results.
I installed the 2 versions prior to the current one and could not get any results.
What has changed?
Search Objects
natural=peak + QUERY OVERPASS returns the following query:

`[out:xml][timeout:90];
(
node[natural=peak];
way[natural=peak];
relation[natural=peak];
);
(._;>;);
out meta;`

This query doesn't work, so I went directly to OverPass-Turbo for a working query and got:

`[out:xml][timeout:25];
(
  nwr["natural"="peak"]({{bbox}});
);
out meta;`

This query does work on Vespucci.

Has something changed in the way OverPass queries are built?

P.S. The option to export the OverPass (Save Code) query still doesn't work, it generates an empty file (0 bytes).
What should be done to save the OverPass query in a .txt file?
I use the "Share Code" option and choose my code editor (MixPlorer) and "Copy To", MiXporer automatically creates the .txt file with the OverPass query.

**Comment by simonpoole** [comment]
See http://vespucci.io/tutorials/object_search/#overpass-api-queries You are missing an "inview" or other scope limiting statement and because of that are trying to query the whole world. This hasn't changed from previous versions (changes would be noted in the change log).
