### ISSUE TITLE
Follows Location Button Layout does not work on Vespucci PlayStore version

### ISSUE THREAD

**Issue by afgb1977** [MarcusWolschon/osmeditor4android#2325]
## Vespucci Version

I uninstalled and reinstalled different versions of Vespucci (Github Beta, PlayStore), doing so lost my settings.
I tried setting "Follow Location Button Layout" to "None" and it had no effect. The follow button is still visible on the left of the screen.
Again I uninstalled and installed the latest version available on GitHub and the settings took effect.

**Comment by simonpoole** [comment]
The relevant code is nearly a decade old and hasn't changed in that time. You need to exit the app completely (as the message says) and then start the app again, you might have to give Android a second or two in between. 

The versions on the play store, github and Amazon are identical (they are literally the same build).
