### ISSUE TITLE
100% duplicate choices appear 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2332]
![Screenshot_20230621_082731_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/4d21c167-e8da-430d-b458-60c0564956ae)

I  can't find the previous bug I submitted about this.

Picking either choice gives the same results in the Details tab.

Yes, the tag is Bench, but this bug also affects other tags probably.

**Comment by simonpoole** [comment]
This is just a side effect of the AutoCompleteText not showing the divider between MRU values and the actual list.

**Comment by jidanni** [comment]
![Screenshot_20230715_144151_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/4cfd00f6-80fa-4b07-9cfa-4447a5f5dbfa)

All I know is the average user has no idea what is trying to be communicated here.

**Comment by HolgerJeromin** [comment]
We h

**Comment by jidanni** [comment]
In fact as a bonus that '<empty>' could then allow the user to click it to make all three empty, yes even if there was the trash can method!
