### ISSUE TITLE
Differentiate choices intelligently

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2333]
![Screenshot_20230621_084155_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/decdc6db-038e-4ab3-bc8b-568fe9fd92ce)

https://www.openstreetmap.org/#map=18/42.1655804/-87.7823129

Here the two choices are actually node versus way, and also building, versus entrance.

But, various factors unfortunately cause this to become a very big dilemma in which one to choose.

The first is the extremely limited field length, as reported earlier.

Next is, unfortunately each item also has an address.

And instead of picking the things that differentiate the two items, it ends up picking the same thing, causing the choices to look exactly the same.

So what could be done here is using a little artificial intelligence. If the two items have different parts then use the different parts when showing the choices.

I mean we can expect a lot of properly tagged items to also have an address.

So they'll all end up looking the same in the choice list, unless something different is grabbed on when constructing the list.

**Comment by simonpoole** [comment]
Please stop opening issues to the same topic time and time again.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/issues/2158
