### ISSUE TITLE
Get colour hex value from photos

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#2338]
I'm often adding the colour=* field from the photo layer. It would be nice if I could get the colour hex value from the photo itself, e.g. when the cursor is in the colour=* field, I could tap a spot in the photo viewer, and the hex value would be inserted (replacing any existing value).

**Comment by simonpoole** [comment]
Duplicate of https://github.com/MarcusWolschon/osmeditor4android/issues/1750
