### ISSUE TITLE
Multi-select

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#234]
```
Add action mode for multi select
```

Original issue reported on code.google.com by `sp8...@gmail.com` on 31 Aug 2014 at 2:15

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/124fd84c4a7b3d522adfa42d4a8d16db31afd545

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/44f8a2492afa7751968d5315045e685287bf3a60 addresses the issue with respect to deleting multiple objects.
