### ISSUE TITLE
Cook County Illinois imagry black

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2343]
![Screenshot_20230706_194344_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/41e6538a-5e99-4060-9f97-6ad39b7263c2)
These three Cook County Illinois imagry layers, are black in Vespucci,  however they are fine in iD.

**Comment by simonpoole** [comment]
These are servers using a proprietary system and should have never been classified as WMS servers in the editor layer index.
