### ISSUE TITLE
Pending changes count background uncoloured on Android 5 and 6

### ISSUE THREAD

**Issue by goldfndr** [MarcusWolschon/osmeditor4android#2348]
On an old (2017) tablet, the Transfer icon's pending changes count lacks a coloured background, making the number difficult to read when the Theme is Light due to the low contrast. It's legible enough in Dark Theme but text isn't coloured.

## Vespucci Version
19.1 BETA 1

## Download source
Google Play Store

## Device (Manufacturer and Model)
Amazon Kindle Fire HD 10 Gen 7 [2017]

## Android Version 
Fire OS 5.7.0.0

## Behaviour/Symptoms
The pending changes count's text is white, but without a coloured background, its visibility on Light Theme has contrast low enough to be barely visible.

## Expected Behaviour
A coloured background or at least bold/thick digits with text coloured appropriately for themed contrast.

## How to recreate
1. Launch Vespucci on an old Kindle Fire tablet.
2. Set theme within Advanced Preferences to Light (if not already set).
2. Download data.
3. Move a node or way.
4. Observe the pending changes count on the transfer (￪￬) icon.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
Not an issue on an Android 10 phone (LG V50) or Android 13 phone (Samsung Galaxy Z Fold3).

**Comment by simonpoole** [comment]
There's no directly obvious erason why this shouldn't work, the method we are using should exist for Android 5 and later: 

https://developer.android.com/reference/android/graphics/Canvas#drawRoundRect(float,%20float,%20float,%20float,%20float,%20float,%20android.graphics.Paint)

https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/java/de/blau/android/util/BadgeDrawable.java#L104

**Comment by simonpoole** [comment]
For completeness sake could you add a screenshot to the issue? Thanks.

**Comment by goldfndr** [comment]
![Screenshot_2023-07-18-15-36-11](https://github.com/MarcusWolschon/osmeditor4android/assets/173956/af30a410-b21b-4eb0-9466-d06902542269) 
![Screenshot_2023-07-18-15-37-01](https://github.com/MarcusWolschon/osmeditor4android/assets/173956/50abe037-fbc8-4083-8f5c-dfd4fc4a337c)

Here are a couple in both themes.

**Comment by simonpoole** [comment]
I can recreate this on an Amazon device running 5.6.8.
