### ISSUE TITLE
Magenta lines should not completely block the original line

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2351]
Magenta lines are very good for indicating lines with problems.

However I have  a better idea.

I think a dashed magenta line would be better. That way the user could still see if the line the magenta line represented, was a river, or a power line, or something else.

Anyway it doesn't have to be dashed it could be some other method, to allow the user to visually see what the original line was at the same time.

That way we could be sure if we're about to connect something to a river or a power line, without leaving and the editing mode to check first.

It's a big surprise to see later that one connected to a river to a power line, or a highway to a river.

Okay, that was discussing Ways. Now let's talk about Points.

Apparently there is no problem with the magenta color and points. For instance create a simple manhole cover. This will create a magenta border around the manhole cover but we can still see the manhole cover. 

Then there is the Bug insect icon.
I am not sure how that interacts with pure points. Because I've only seen it on ways so far.

**Comment by simonpoole** [comment]
You could for example make the styling less opaque: http://vespucci.io/tutorials/data_styling/#validation-styling
