### ISSUE TITLE
"Customers" value

### ISSUE THREAD

**Issue by Mannivu** [MarcusWolschon/osmeditor4android#2352]
## Vespucci Version
19.0.3.0

## Download source
Google Play Store 

## Device (Manufacturer and Model)
Xiaomi Redmi Note 11 Pro

## Android Version 
MIUI V14.0.1.0.TGDEUXM (Android 13)

## Behaviour/Symptoms
When selecting the "Customers" value from the "Access" presets the app incorrectly insert the "`customer`" (without the "s" at the end) value, wich is incorrect 

## Expected Behaviour
The app should insert "`customers`"

## How to recreate
On a random POI or highway try to insert "Customers" from the "Access" presets

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
none

**Comment by simonpoole** [comment]
This issue need to be opened on the preset repo , the issue goes back to this value being in the preset before customers with s being established. Naturally the plural variant is at odds with the normal OSM convention of using the singular.

**Comment by Mannivu** [comment]
Opened in https://github.com/simonpoole/beautified-JOSM-preset/issues/401
