### ISSUE TITLE
Unsure where we are typing into

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2353]
After making an edit we push the big green check mark. The next screen we see is this,
![Screenshot_20230717-120532.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/bf43e21a-c582-45d1-a4e0-6580eedf47dd)

The keyboard is thrown up, we start typing strings into it, but apparently where we are typing goes somewhere we don't see. We thought we were typing search screen strings. But we need to tap a field to activate it before that really works. So we don't know why the keyboard is throwing up for us to start typing but no field we see  is activated to type into.

**Comment by simonpoole** [comment]
The issue is void of any useful information. The described behaviour doesn't happen in general, and you need to supply the information as suggested in the issue template.

**Comment by jidanni** [comment]
It turns out, at least on Android 8 Zenfone 3, that for creating new **tagged nodes**, everything works perfectly.
![Screenshot_20230718-044312.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/ef8c7380-1f46-4d10-a0c1-ad75dadf4686)

and we see the flashing cursor.

But when entering **ways**, we end up looking at the wrong panel,
![Screenshot_20230718-044343.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/30bb614b-d2d9-4d4f-bd10-50d70e168cfd)

We need to manually pull the panel that is on the left into view. Then we will find the flashing cursor.

**Comment by jidanni** [comment]
In Android 13, Samsung A13 5G,
the situation is the same, except the keyboard is not up.

![Screenshot_20230718_065656_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/f5f3b7fd-94a6-4121-873b-a148772cbf9f)

We still see different initial panels, node vs. way.

**Comment by simonpoole** [comment]
What is different here is that the _Add node_ and _Add way_ operations show the properties panel in the property editor when completed, the _Add tagged node_ op shows the preset panel. Regardless of which panel is shown it is always going to be wrong in some cases.

**Comment by jidanni** [comment]
Thanks but please turn my notifications back on for this issue so I know when you respond. Thanks.
