### ISSUE TITLE
Sanitäre Entsorgungsstation beim camping mit falscher Anzeige

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2354]
Description:
---

Der Eintrag (Beispiel https://www.openstreetmap.org/way/116721410)
name=Camping municipal de Tinténiac
sanitary_dump_station=no
Wird angezeigt als "Privat"
Das ist falsch, es sollte heissen "nicht vorhanden", oder etwas sinngemässes.

Device info:
---
<table>
<tr><td>App version</td><td>19.0.2.0</td></tr>
<tr><td>App version code</td><td>2405</td></tr>
<tr><td>Android build version</td><td>T725XXS2CUA2</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.T725XXS2CUA2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>gts4lv</td></tr>
<tr><td>Device model</td><td>SM-T725</td></tr>
<tr><td>Device product name</td><td>gts4lveea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/pebogufi"/>pebogufi</A></td></tr>
</table>

**Comment by simonpoole** [comment]
This belongs in the preset repo and is likely an issue of a missing translation contest.
