### ISSUE TITLE
Multipolygon member exclusion

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#2361]
When creating a multipolygon, if the number of its pre-selected members is odd, the member that was selected last is excluded.  And it has to be added separately.  It doesn't matter if the contour of this multipolygon is closed.

## Vespucci Version
19.1.0.1

## Download source
Github

## Device (Manufacturer and Model)
Redmi Note 10 Pro

## Android Version 
13

**Comment by simonpoole** [comment]
To clarify you are selecting members with multi-select and then 'create relstion'?

**Comment by mic140** [comment]
Yes

**Comment by simonpoole** [comment]
Thanks for the report. There were two independent issues that ganged up to cause this, and naturally the tests just happened to have rings with an even number of segments.
