### ISSUE TITLE
Improve notification queue flushing (was: Toast notifications are excessive, obscure buttons and fields)

### ISSUE THREAD

**Issue by zyphlar** [MarcusWolschon/osmeditor4android#2367]
## Vespucci Version
19.1.1

## Download source
Google Play

## Device (Manufacturer and Model)
Samsung Galaxy S21

## Android Version 
13

## Behaviour/Symptoms
When rapidly moving around the interface, such as copy/pasting common address tags between many POIs in one building, and especially when standing in an urban area with poor GNSS reception, the blue-green notification popups at the top of the screen will tend to obscure clickable or important elements. Since notifications are queued, this can obscure things for many seconds: you can force this behavior by rapidly clicking back and forth between two POIs a few dozen times and then trying to edit something. 

Additionally, popups at the bottom of the screen also obscure the main buttons at the bottom.

This penalizes power users and creates frustration by delaying their activities when they are standing in public trying to survey things efficiently.

Generally, all notifications could benefit greatly from some heavy prioritization: very few of the notifications are actionable or intuitive (do I need a notification that I selected a building, or do I just need a status icon that unobtrusively shows what kind of thing I have selected? Do I need just a notification about an error with tasks or uploads or opening files, or could I really use some clickable followup actions like a red Upload Errored menu or a red layer in the layers screen or a report of tasks/changes that have failed/conflicted with reasons and remediations?) -- when too many things are popping up and there's not a whole lot a newbie can do about them, they start becoming visual noise that gets ignored. There's many reasons that `alert()` and `prompt()` and browser popups have been lambasted as an anti-feature and dynamic data-bound self-validating UI elements have become standard: it's too easy to overrely on them as a primary way of communicating with a user when we'd much prefer that our form be highlighted and scrolled to the appropriate section, or that a button turns red and changes its label, than have a bunch of alerts pop up divorced from any context.

## Expected Behaviour
- Notifications never obscure any other UI elements, especially clickable ones.
- Notifications that require user action, like an error, naturally lead to that action (perhaps they persist a little longer and are clickable to go to a dialog or FAQ or help menu, or at least describe appropriate steps in plain language. Maybe actionable errors persist in a red Alerts menu. Twelve year olds in my country don't know what `GNSS` or `Download/EGM96.dat` are, but they might know what `Your Location` and `Imported Layer #3` are. Programs like Vespucci and JOSM are complex tools, users often need a little hand-holding inside the app to know what exists where. Smartphone users are accustomed to expecting all relevant information to exist inside an app, and rarely visit the app developer's website except out of extreme frustration.)
- Messages that don't require user action but are informative, like communicating status or state, are reconsidered to be built into the UI itself instead of popup notifications over the UI whenever possible.
  - There are ways of indicating location accuracy besides textual popups. I see the location arrow already has a radius and blue or black color and filled or unfilled, so if I care about accuracy or staleness I already have those indicators even though I'm not sure exactly what the differences are. At least there if I care about it I can research or try clicking on it; excessive popups just queue up, delay, and obscure.
  - Knowing whether I'm selecting `Building #12345` or `Building #23456` doesn't tell me much -- I can't even select the ID to look it up, and the numbers are often too long to remember -- whereas an icon in the corner that looks like a Building versus a Street versus a Relation could indicate a lot to me unobtrusively and even subconsciously.
  - Missing wheelchair or opening hours tags are already communicated by a magenta color, and would more appropriately be encouraged inside the tag editor itself than present in a popup: due to the Americans with Disabilities act it can be assumed that 99.9% of all new construction is wheelchair-friendly in my country, so of all the missing tags to highlight and alert on that is one of the least effectual (much more critical in my area would be highlighting curbs and crossings with missing ramp information, or POIs/buildings without addresses, for example. I really don't need a popup about it, but I could really use a customizable missing tags highlighter feature in the style of StreetComplete overlays instead.) Exhaustively alerting about all missing tags would take up the entire screen, so popups just seem like one of the worst ways to indicate such issues.

## How to recreate
Click around a lot generating a long queue of alerts and then try to do various things

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information

Screenshots:

Inactionable and large error; I don't remember downloading this and it's not in a list of downloads, it doesn't affect usability, doesn't hang around and isn't clickable, so I ignore it
<img src="https://github.com/MarcusWolschon/osmeditor4android/assets/48434/ec0b3438-6a85-4868-a337-c12516ff0cd1" width="400">

Obscuring key menu items
<img src="https://github.com/MarcusWolschon/osmeditor4android/assets/48434/850c8767-a8b7-40d2-82a1-ebbd26cb8d0f" width="400">

Obscuring the topmost layers
<img src="https://github.com/MarcusWolschon/osmeditor4android/assets/48434/c12bc237-5c64-4aa2-8d3d-e0a6840a7289" width="400">

Obscuring the most important tag-editing buttons
<img src="https://github.com/MarcusWolschon/osmeditor4android/assets/48434/5978f8a1-2602-4da6-87b0-b1a9fa2c1bbc" width="400">

Obscuring the app's primary buttons at the bottom of the screen
<img src="https://github.com/MarcusWolschon/osmeditor4android/assets/48434/1de634e3-b5e4-4026-a40d-309ea2aad9c2" width="400">

Obscuring settings menu items
<img src="https://github.com/MarcusWolschon/osmeditor4android/assets/48434/aa44aa42-5c7e-48aa-af1c-03bf2d9f5520" width="400">

Obscuring the most important preset buttons in the tag editor
<img src="https://github.com/MarcusWolschon/osmeditor4android/assets/48434/7f3f6bc8-2d2d-4661-bdfc-e3940f44ea3e" width="400">

Obscuring the topmost (thus most frequently used) options in the tag dropdown
<img src="https://github.com/MarcusWolschon/osmeditor4android/assets/48434/002e1793-9829-4520-9ebe-a8f288ffe30b" width="400">

**Comment by simonpoole** [comment]
As I pointed out, the specific issue with your setup seems to be that your device is switching back and forth between GNSS and / "Network" location services a lot which causes notifications to queue and be displayed significantly later than in normal circumstances. The short term fix for this is to turn off the "Fallback to network location" setting http://vespucci.io/help/en/Advanced%20preferences/#location-settings or to not enable network location use on the device, the medium term fix is to improve flushing of the notification queue.

The 2nd issue that compounds the situation is that you are ignoring the messages when they indicate a problem, as in all other venues of life that doesn't make the underlying problem go away. For example the first screenshot is a message that the EGM file for GPX height information you installed has been deleted. If this isn't available GPX tracks will not contain elevation information, so you need to take action: either delete the configuration if you are happy with not having the elevation information or reinstall the EGM file. Either action will stop the notification being generated.

**Comment by simonpoole** [comment]
Note: only Snackbars have a accessible queuing mechanism, Toasts are handled by an Android internal service.

**Comment by zyphlar** [comment]
There are many issues bundled up in with this issue; even if I didn't have GNSS alerts or the EGM alert (which I don't recall installing, and I don't know where the configuration is or where the EGM would've been installed from in the first place) the ultimate issue is that the raw excessive use of these notifications by all parts of the system causes the most important parts of the page to be obscured. Just the other day I was clicking around many nodes to work quickly and got "Node #____" and "Building #_____" popups overlapping key menu items as in the 2nd and 4th screenshots. It's an intrinsic problem to using the app quickly and I'm surprised you haven't run into it yourself. The simplest resolution for this issue is as stated: "notifications should never obscure any other UI elements, especially clickable ones."
