### ISSUE TITLE
Fairphone 4 - GPX tracks have wrong timestamps

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#2368]
## Vespucci Version
19.1 Beta 1

## Download source
Google Play

## Device (Manufacturer and Model)
Fairphone 4

## Android Version 
12

## Behaviour/Symptoms
When recording and then exporting a GPX-Track, the track has a wrong date associated to it, for example:

`<time>2003-12-16T14:38:51Z</time>`

The track was actually recorded on 2023-08-01. When I create a track today, it is timestamped with 2003-12-18.

I can reproduce the problem for tracks that I directly upload to OSM from Vespucci, and also for tracks that I export to the file system.

## Expected Behaviour
Add a correct timestamp to the track.

## How to recreate
(German locale)
1. Select location button
2. Select "GPX track starten"
3. Walk a few meters
4. Select "GPX track pausieren"
5. Go to layers menu
6. Select three dots of current track
7. Select "GPX track exportieren…" or "GPX track hochladen..."
8. Export or upload the track
9. Open the gpx file in an editor and see the wrong timestamps

## Crash dump submitted (no or yes + date)
No.

## Any other potentially relevant information
Location settings:
![Screenshot_20230803-235043](https://github.com/MarcusWolschon/osmeditor4android/assets/30999326/f8263fcc-b0ed-4784-b7f0-a1c590a366c3)

**Comment by simonpoole** [comment]
Can't reproduce the behaviour here so something more must be going on. 

Could you screenshot the relevant settings  https://vespucci.io/help/en/Advanced%20preferences/#location-settings and add it to the issue?

**Comment by Discostu36** [comment]
Added above

**Comment by simonpoole** [comment]
This seems weird, with the settings that you have, we simply use the system provided Location objects that contain the time since the UNIX epoch in milliseconds and don't do anything except formatting for output, see:

https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/java/de/blau/android/gpx/TrackPoint.java#L71

and

https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/java/de/blau/android/gpx/TrackPoint.java#L252

The time formatter is created here https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/java/de/blau/android/gpx/Track.java#L123

**Comment by Discostu36** [comment]
I don't  have /e/OS/ but stock Android.

Just checked with other apps. Osmand tracks have the correct timestamp. OSMTracker also had the incorrect timestamp (the same as Vespucci). So this might really be somehow related to my phone.

I'm not sure it would be a good idea to look at what Osmand does differently. I'll contact Fairphone support about this.

**Comment by simonpoole** [comment]
Does your phone have google play services? Because osmand might be using googles fused  location provider.

**Comment by Discostu36** [comment]
Yes, I have. The Fairphone thread suggests the SIM card might be faulty. I'll order a new one.

**Comment by Discostu36** [comment]
I now managed to solve the problem (at least temporarily):

1. I removed the SIM
2. Got a GPS fix without the SIM, GPSTest app showed me that I have now a correct GNSS date
3. I put the SIM into the phone again
4. I got another GPS fix and the date was still correct. 
5. I recorded a track with Vespucci and the timestamp is now correct

The question remaining is if you want to do anything about this issue. You could

1. Ignore this because it is device and/or SIM problem, not a Vespucci problem
2. Give users a warning if GNSS time and system time are too different
3. Write system time instead of GNSS time into the timestamp

Option 3 might lead to other problems we don't know about, but in my opinion, option 2 is something you might want to consider.

**Comment by HolgerJeromin** [comment]
> option 2 is something you might want to consider.

What should the user do in that case?

**Comment by Discostu36** [comment]
I don't think Vespucci should give detailed instructions because it depends on the situation. Something like 

> The GPS time and the system time of your phone are off by more than x hours. Generated GPX tracks may have a wrong timestamp as a result. Please contact your phone manufacturer or network provider for support.

**Comment by simonpoole** [comment]
Has there been any response from Fairphone?

**Comment by Discostu36** [comment]
As someone in the forum thread wrote that support told him that the SIM card was to blame, and I could fix the problem for my case, Ididn't contact support.

**Comment by simonpoole** [comment]
The consensus seems to be that this is something that Fairphone should fix.
