### ISSUE TITLE
Ärzte: Termin nach Vereinbarung 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2369]
Description:
---

Ich sehe keine Möglichkeit bei Ärzten  "Termin nach Vereinbarung" einzugeben 

Device info:
---
<table>
<tr><td>App version</td><td>19.0.3.0</td></tr>
<tr><td>App version code</td><td>2406</td></tr>
<tr><td>Android build version</td><td>10216780</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>TQ3A.230705.001</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>cheetah</td></tr>
<tr><td>Device model</td><td>Pixel 7 Pro</td></tr>
<tr><td>Device product name</td><td>cheetah</td></tr>
<tr><td>Device hardware name</td><td>cheetah</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a]</td></tr>
<tr><td>ABIs (32bit)</td><td>[]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/OpenGreenStreet"/>OpenGreenStreet</A></td></tr>
</table>

**Comment by HolgerJeromin** [comment]
Editor öffnen.
Im Wizard leer lassen
Im Menüpunkt der Regel 1: "Zustandsänderung/Kommetar"
Evtl "Offen" abwählen.
Freitext eintragen

**Comment by simonpoole** [comment]
> Editor öffnen. Im Wizard leer lassen Im Menüpunkt der Regel 1: "Zustandsänderung/Kommetar" Evtl "Offen" abwählen. Freitext eintragen

Und das ganze noch als Vorlage speichern für das nächste Mal.

**Comment by OpenGreenStreet** [comment]
Hallo @HolgerJeromin, @simonpoole , vielen Dank für die Hinweise. Da wäre ich nie drauf gekommen… :-) 
Habe es gleich mal versucht: https://www.openstreetmap.org/changeset/139445366
Viele Grüße
