### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2370]
Description:
---

Necesito ayuda, mis capas de OSM fueron borradas por accidente. ¿Como puedo recuperarlas?

Device info:
---
<table>
<tr><td>App version</td><td>19.0.3.0</td></tr>
<tr><td>App version code</td><td>2406</td></tr>
<tr><td>Android build version</td><td>J111MUBU0AQF2</td></tr>
<tr><td>Android release version</td><td>5.1.1</td></tr>
<tr><td>Android SDK version</td><td>22</td></tr>
<tr><td>Android build ID</td><td>LMY47V.J111MUBU0AQF2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>j1acevelte</td></tr>
<tr><td>Device model</td><td>SM-J111M</td></tr>
<tr><td>Device product name</td><td>j1acevelteub</td></tr>
<tr><td>Device hardware name</td><td>sc8830</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Leonard250"/>Leonard250</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Hi, sorry but the translation of your question doesn't make a whole lot of sense, could you explain what you mean with "capas de OSM".

**Comment by HolgerJeromin** [comment]
Google translate is quite confusing, but deepl looks reasonable:

> I need help, my OSM layers were accidentally deleted, how can I get them back?

**Comment by leonard505-6** [comment]
sorry, it was my mistake. I mean the surface layers, satellite images... I already solved this error but I don't want it to happen again :-(

**Comment by simonpoole** [comment]
https://vespucci.io/help/en/Main%20map%20display/#layer-control is the relevant documentation.
