### ISSUE TITLE
Keine routenbezeichnung

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2371]
Description:
---

Hallo bei den Routen wird nur eine Klammer angezeigt hier fehlt die roten Bezeichnung bei Radrouten ist dieses wiederum okay vielleicht mal nachschauen vielen Dank

Device info:
---
<table>
<tr><td>App version</td><td>19.1.1.0</td></tr>
<tr><td>App version code</td><td>2502</td></tr>
<tr><td>Android build version</td><td>V14.0.1.0.TKCEUXM</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>TKQ1.221114.001 test-keys</td></tr>
<tr><td>Device brand</td><td>POCO</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>veux</td></tr>
<tr><td>Device model</td><td>2201116PG</td></tr>
<tr><td>Device product name</td><td>veux_p_eea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/BER319"/>BER319</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Das ist ein "Problem" in den Vorlagen, da ab 19.1 wenn kein name-Tag gesetzt wird, dieser Ausdruck ausgewertet wird

https://github.com/simonpoole/beautified-JOSM-preset/blob/master/master_preset.xml#L13238

als letzte Variante sollte es wohl die OSM id verwenden, trotzdem würde mich ein Beispiel interessieren, da natürlich die OSM id eigentlich nicht wirklich hilfreich ist.

**Comment by simonpoole** [comment]
Vorlagen Version 5.13.0 sollte das Problem beheben, die kann man sich als Ersatz für die mit dem APK gelieferten installieren. 

Siehe http://vespucci.io/help/en/Presets/ speziell http://vespucci.io/help/en/Presets/#useful-presets-for-download

**Comment by BER319** [comment]
Vielen Dank für die schnelle Erledigung. Mit der neuen Vorlage sieht es nun viel besser aus.
