### ISSUE TITLE
Keine routenbezeichnung

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2372]
Description:
---

Nachtrag bei Auswahl eines Weges wird dann bei der rote nur hikingroute angezeigt und danach die Klammern

Device info:
---
<table>
<tr><td>App version</td><td>19.1.1.0</td></tr>
<tr><td>App version code</td><td>2502</td></tr>
<tr><td>Android build version</td><td>V14.0.1.0.TKCEUXM</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>TKQ1.221114.001 test-keys</td></tr>
<tr><td>Device brand</td><td>POCO</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>veux</td></tr>
<tr><td>Device model</td><td>2201116PG</td></tr>
<tr><td>Device product name</td><td>veux_p_eea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/BER319"/>BER319</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Duplicate
