### ISSUE TITLE
Modal for entering longer text in tags doesn't seem to work for "Additional properties"

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#2373]
## Vespucci Version
19.1.1

## Download source
Google Play Store

## Device (Manufacturer and Model)
Samsung A33

## Android Version 
13

## Behaviour/Symptoms
If there is a tag with a long text which isn't part of the current matching item (and therefore is displayed under "Additional properties" in the form based editor, tab "Properties") and it has a text (value) with string length equal or larger than "Long string limit", no modal dialog is shown for an easy text entry (and there is also no multi-line display in the editor). And it is difficult to enter (and to read) in the standard one line text field.

## Expected Behaviour
It would be nice and comfortable, if the modal would also been shown in such a case. (And a multi-line display in the "Additional properties" section would be great, too – if possible).

**Comment by simonpoole** [comment]
This adds support for items in the "Additional properties" layout. Currently there is no support for any of the modal input methods in the "Details"  tab, see https://github.com/MarcusWolschon/osmeditor4android/issues/706 as this would directly contradict the purpose of that tab.
