### ISSUE TITLE
No way to upload gpx track

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2375]
Description:
---

Button to upload gpx talk nowhere to be found

Device info:
---
<table>
<tr><td>App version</td><td>19.1.1.0</td></tr>
<tr><td>App version code</td><td>2502</td></tr>
<tr><td>Android build version</td><td>58b4278261</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>lineage_lemonadep-userdebug 13 TQ2A.230505.002 58b4278261</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus9Pro</td></tr>
<tr><td>Device model</td><td>LE2123</td></tr>
<tr><td>Device product name</td><td>OnePlus9Pro</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/martin-kokos"/>martin-kokos</A></td></tr>
</table>

**Comment by simonpoole** [comment]
As you can have multiple GPX layers since 17.1 the upload option has been moved to the menu of the respective layer.

See http://vespucci.io/help/en/17.1.0%20Release%20notes/#improved-gpx-layer-support and http://vespucci.io/help/en/Main%20map%20display/#layer-control (GPX layers).

**Comment by simonpoole** [comment]
No feedback.
