### ISSUE TITLE
Knoten Nummer suchen

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2376]
Description:
---

Wie kann man direkt eine Knoten-Nummer suchen?

Über den Knoten-Namen geht das, das wird aber unkomfortabel, wenn eine lange Liste angezeigt wird.

Zum Beispiel wenn ich nach dem nachfolgenden 
Knoten suche: Middlewood (29947059)

Device info:
---
<table>
<tr><td>App version</td><td>19.1.1.0</td></tr>
<tr><td>App version code</td><td>2502</td></tr>
<tr><td>Android build version</td><td>10216780</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>TQ3A.230705.001</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>cheetah</td></tr>
<tr><td>Device model</td><td>Pixel 7 Pro</td></tr>
<tr><td>Device product name</td><td>cheetah</td></tr>
<tr><td>Device hardware name</td><td>cheetah</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a]</td></tr>
<tr><td>ABIs (32bit)</td><td>[]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/OpenGreenStreet"/>OpenGreenStreet</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Das genaue Vorgehen hängt davon ab der Node im Speicher ist oder nicht, aber grundsätzlich kann man dazu die Objektsuche verwenden siehe http://vespucci.io/tutorials/object_search/

Für dein Beispiel wäre der Suchausdruck

```
type:node id:29947059
```

Wird der Node im Speicher gefunden wird er selektiert und darauf gezoomt, ist er nicht im Speicher, kannst du eine Overpass query aus dem Suchausdruck erstellen und den laufen lassen, dass lädt dann das Objekt vom Overpass-Server.

**Comment by OpenGreenStreet** [comment]
Hallo @simonpoole , danke für Deine sehr schnelle Rückmeldung. Das mit dem Suchausdruck "type:node id:29947059" habe ich bei "Finden" und "Overpass abfragen..."´leider nicht hinbekommen.

Über die Funktion "Zu Koordinaten gehen" und der Eingabe von "53.3600557 -2.0835284" statt "53,3600557 -2,0835284" (Punkt satt Komma) bin ich aber doch relativ einfach dort hingekommen, wo ich hin wollte.


PS: Macht es Sinn, eine extra "Rückmeldung senden" einzureichen und sich zu wünschen, dass hinter dem Vespucci-Ortungssymbol ( https://commons.wikimedia.org/wiki/File:Gps-thin-symbol-in-circle-outline-button.svg ) eine Suchfunktion "Gehe zu Note . . ." angeboten wird?

Viele Grüße

**Comment by simonpoole** [comment]
Ich hab das natürlich bevor ich geantwortet habe verifiziert, müsste also gehen. Du musst aber 'Objekt suchen' verwenden und nicht 'Finden'.

Generell bitte ein neues Issue aufmachen für Feature Requests.

**Comment by simonpoole** [comment]
Hmm müsste jetzt nachschauen ob Daten geladen sein müssen, definitive muss aktuell entsperrt sein.

**Comment by OpenGreenStreet** [comment]
Ja, war nicht entsperrt. Ich probiere es morgen

**Comment by OpenGreenStreet** [comment]
Guten Morgen @simonpoole, vielen Dank für Deine Geduld mit mir. Es hat jetzt super geklappt:

https://www.openstreetmap.org/node/34050752
https://www.openstreetmap.org/node/69487423

Invalid category corrected, see also: https://gist.github.com/Ordoviz/0f1896c3ccd0fba65c0983356322b3c5

Aus meiner Sicht kann diese Diskussion hier abgeschlossen werden 

Viele Grüße
