### ISSUE TITLE
Laden dauert neuerdings langer

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2388]
Description:
---

Ich habe den Eindruck, dass das Land von Kartenausschnitten neuerdings (seit dem letzten Release?) länger dauert (bis zu einer Minute, trotz guter Verbindung)
Tippt man irgendwo hin - bevor der Ladevorgang von alleine abgeschlossen ist - scheinen alle Daten vorhanden zu sein.

Device info:
---
<table>
<tr><td>App version</td><td>19.1.2.0</td></tr>
<tr><td>App version code</td><td>2503</td></tr>
<tr><td>Android build version</td><td>10316531</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>TQ3A.230805.001</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>cheetah</td></tr>
<tr><td>Device model</td><td>Pixel 7 Pro</td></tr>
<tr><td>Device product name</td><td>cheetah</td></tr>
<tr><td>Device hardware name</td><td>cheetah</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a]</td></tr>
<tr><td>ABIs (32bit)</td><td>[]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/OpenGreenStreet"/>OpenGreenStreet</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Der Ladevorgang ist so oder so völlig asynchron zum UI, sprich auch wenn man "abbricht" wird fertig geladen. Es kann sein, dass dies einfach ein Problem mit dem entfernen der Dialoge ist, ich schau's mal an.

**Comment by simonpoole** [comment]
Das Problem scheint zu sein, dass das Downloaded von OSMOSE Tasks manchmal relativ lange dauert, und dass gleichzeitig der falsche Text angezeigt wurde.

**Comment by OpenGreenStreet** [comment]
@simonpoole danke, dass Du danach geschaut hast. Ist ja keine Funktionseinschränkung, nur irritierend. Viele Grüße
