### ISSUE TITLE
Relationen Ansicht löschen (Wiederaufnahme)

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2389]
Description:
---

Entschuldigung, 
ich hatte das Problem schon vor längerer Zeit einmal gemeldet, hatte dann aber versäumt, einen Screenshot zur Erklärung nachzuliefern (den könnte ich jetzt nachliefern:

Falls man einen Wanderweg o.ä. was die Zuordnung von neuen Relationen erfordert, eintragen möchte, muss man sich durch quasi unendliche Listen zwischengespeicherter Relationen durchsuchen.

a) es gibt offenbar keine Möglichkeit, diese Liste zurückzusetzen, außer man löscht sämtliche Daten der App (Cache löschen reicht leider nicht)
-> das ist das Hauptproblem (und u.a.weil es so umständlich ist, hatte ich damals keine aktuellen Screenshot liefern können)

b) eventuell wäre es auch geschickt, eine Option zu ergänzen, nach Art der Relationen zu filtern. Da das aber vermutlich schwierig zu implementieren ist und kein großes Problem, wenn a) gelöst ist, wäre das nur ein kleiner Vorschlag.

Danke für die Geduld und ein ansonsten erstklassiges Programm! Ich nutze es fast täglich, zumindest wenn ich irgendwo unterwegs bin!

Schöne Grüße

KlausG

Device info:
---
<table>
<tr><td>App version</td><td>19.1.2.0</td></tr>
<tr><td>App version code</td><td>2503</td></tr>
<tr><td>Android build version</td><td>V12.5.7.0.RGGEUXM</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RP1A.200720.011</td></tr>
<tr><td>Device brand</td><td>Redmi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>begonia</td></tr>
<tr><td>Device model</td><td>Redmi Note 8 Pro</td></tr>
<tr><td>Device product name</td><td>begonia_eea</td></tr>
<tr><td>Device hardware name</td><td>mt6785</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/KlausG"/>KlausG</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Hallo Klaus, kannst du mir dein Workflow kurz skizzieren?

Weg auswählen und dann "Zu Route hinzufügen"? Oder anders?

**Comment by klausgr** [comment]
![Screenshot_2023-08-27-08-45-13-052_de blau android](https://github.com/MarcusWolschon/osmeditor4android/assets/29913972/d7e73631-f009-4575-aedf-c25cb771becd)

Ja, im Prinzip schon. Ich erzeuge einen Weg, oder meistens einen Punkt für einen fehlenden Wegweiser, und versuche ihn dann im Tab "Eigenschaften" mit Daten zu füttern. Meist als letztes, wobei die Reihenfolge keine Rolle spielt, wähle ich den rechten Tab "Relationen" aus, gehe dann auf die drei senkrechten Punkte (Menü), dabei dann auf "Relationen hinzufügen", und dann bekomme ich eine quasi unendliche, ungeordnete Liste, die offenbar mit allen Relationen gefüllt ist, die zu den Objekten (Wege, Punkte) gehören, die ich seit ersten Start von Vespucci heruntergeladen hatte. Die Relationsanzeige ist dabei auch kaum lesbar, weil es meist längere Einträge sind.

Vom Betriebssystem aus den Programm-Cache zu löschen, reicht nicht aus, um die Liste zu resetten, ich muss dazu wirklich alle Programm-Daten löschen. Einen Menü-Eintrag im Programm selbst dafür kenne ich nicht.

Danke für die Nachfrage!

Klaus

PS: Manchmal (=selten) bleibt bei mir das gesamte Vespucci bei anderen Editierarbeiten hängen, dann hilft auch nur, alle Daten zu löschen (oder das ganze Programm und dann neu installieren), dann ist die Relationen-Liste wieder leer. Das war u.a. neben der übersehenen Kontaktaufnahme der Grund, weshalb ich bei meiner ersten Problembeschreibung zeitnah keinen Screenshot geliefert hatte

**Comment by simonpoole** [comment]
> Ja, im Prinzip schon. Ich erzeuge einen Weg, oder meistens einen Punkt für einen fehlenden Wegweiser, und versuche ihn dann im Tab "Eigenschaften" mit Daten zu füttern.

Ich hätte, mindestens für Routen, vorgeschlagen eher die Funktion "Zu  Route hinzufügen" http://vespucci.io/help/en/Way%20selected/#add-to-route  zu verwenden, es beschränkt die Auswahl wenigstens auf bestehende Routen Relationen (wenn auch nicht nur auf solche bei dem die aktuelle Auswahl passt).

Zu

> PS: Manchmal (=selten) bleibt bei mir das gesamte Vespucci bei anderen Editierarbeiten hängen,

das sollte natürlich nicht passieren. Hast du irgendeine Meinung wenn das passiert? 

So oder so kannst du den ganzen Datenbestand mit "Clear and download current view" oder mit "Clear data" den vorgehaltenen Datenbestand löschen siehe http://vespucci.io/help/en/Main%20map%20display/#transfer . Oder mit "Zurückschneiden" im Layer-Dialog den Datenbestand auf das nötigste reduzieren (sprich auf gemachte Änderungen und Elemente in der aktuellen Ansicht). Wenn einer der "Automatischen" Datendownloadmodi aktiv sind, passiert letzteres automatisch.

**Comment by klausgr** [comment]
![Screenshot_2023-09-18-11-25-05-071_de blau android](https://github.com/MarcusWolschon/osmeditor4android/assets/29913972/9771a5c4-a018-4b6c-9d34-54a22c896c8d)

Vielen herzlichen Dank für die Tipps!
Jetzt verstehe ich, warum man der Sache nicht nachgegangen ist.
Die Optionen mit dem Datenlöschen hatte ich entweder bislang übersehen (wahrscheinlich) oder sie hatte bislang nicht funktioniert (eher unwahrscheinlich). Jetzt zumindest hat das auf Anhieb geklappt!

Was allerdings zuvor nur mäßig geklappt hatte: der Tipp "Zur Route hinzufügen". Da bekomme ich eine stark reduzierte, viel lesbarere Liste angezeigt, aber die enthält offenbar immer noch alle Gegenden, wo ich in der letzten Zeit gemappt hatte (siehe Screenshot). In Verbindung mit dem Datenlöschen in der App ist das dann aber wirklich kein Problem 

Nochmals vielen Dank für den Support und Entschuldigung für mein Übersehen dieser an sich doch sehr naheliegenden Optionen!

Die Diskussion kann deshalb nun geschlossen werden.

Happy Mapping (& Happy Programming)

KlausG

**Comment by simonpoole** [comment]
Kein Problem.
