### ISSUE TITLE
Property editor split window mode broken in 19.2 (was: Bug when exiting the tag editor)

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#2395]
After the last update of the program, it became impossible to use it - when you try to close the tag editing window, it becomes the same as the top map window.  And when one of the windows is closed, the map may no longer be active, or the map may move to one of the previous editing locations.
  It is also not possible to install an earlier version of the application.
![Screenshot_2023-09-12-11-10-49-030_com miui gallery](https://github.com/MarcusWolschon/osmeditor4android/assets/69987154/c3c700e7-2324-4edb-80e7-43e6eccb5d5e)
![Screenshot_2023-09-12-11-10-17-735_com miui gallery](https://github.com/MarcusWolschon/osmeditor4android/assets/69987154/a9ec2ea0-0312-42b6-8eab-f3e7f7bb0c4d)

## Vespucci Version
19.2.0 Release

## Download source
github

## Device (Manufacturer and Model)
Redmi Note 10 Pro

## Android Version 
13

**Comment by simonpoole** [comment]
For now I would suggest turning the split window mode off.. 

The regression is likely caused by a change that I had to make to fix things on Android 4.1 and needs some thinking on how to fix.
