### ISSUE TITLE
Saving settings

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#2396]
Please add a function for saving settings or at least saving custom layers.  This is an extremely necessary function when the application crashes, when you have to configure everything again.  This is especially true for custom layers, if there are more than two or three of them.

**Comment by mic140** [comment]
Unfortunately, I'm not a programmer and don't know how to create such a file.  Could you send me a sample of such a file so I could make my own?

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/assets/imagery_vespucci.geojson the Thunderforest entry is likely a good one to use as a template. https://github.com/osmlab/editor-layer-index/blob/gh-pages/CONTRIBUTING.md explains what the values mean.
