### ISSUE TITLE
Black nodes and paths

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2402]
Description:
---

Lamentablemente no puedo mandarle una foto en esta interfaz, pero le aseguro que todos los nodos y vías se convirtieron a color negro. ¿Por qué?

Device info:
---
<table>
<tr><td>App version</td><td>19.2.0.1</td></tr>
<tr><td>App version code</td><td>2600</td></tr>
<tr><td>Android build version</td><td>J111MUBU0AQF2</td></tr>
<tr><td>Android release version</td><td>5.1.1</td></tr>
<tr><td>Android SDK version</td><td>22</td></tr>
<tr><td>Android build ID</td><td>LMY47V.J111MUBU0AQF2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>j1acevelte</td></tr>
<tr><td>Device model</td><td>SM-J111M</td></tr>
<tr><td>Device product name</td><td>j1acevelteub</td></tr>
<tr><td>Device hardware name</td><td>sc8830</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Leonard250"/>Leonard250</A></td></tr>
</table>

**Comment by simonpoole** [comment]
This sounds as if the "minimal data style" is selected, setting it back to the default "Color round nodes" should fix the issue: http://vespucci.io/help/en/Preferences/#data-style
