### ISSUE TITLE
Follow location during locked screen

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2406]
Description:
---

It will be a great feature if it could be possible for vespucci to continue to follow the user's location even if the screen phone is off.
So when the user swich on vespucci could show the current position and it could be possible to add quickly new POI.

Thanks for your great application 

Device info:
---
<table>
<tr><td>App version</td><td>19.2.0.0</td></tr>
<tr><td>App version code</td><td>2601</td></tr>
<tr><td>Android build version</td><td>V13.0.16.0.SKFEUXM</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SKQ1.210908.001 test-keys</td></tr>
<tr><td>Device brand</td><td>Redmi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>sweet</td></tr>
<tr><td>Device model</td><td>M2101K6G</td></tr>
<tr><td>Device product name</td><td>sweet_eea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/fredoh"/>fredoh</A></td></tr>
</table>

**Comment by simonpoole** [comment]
The current workaround is to record a GPS track (you can disable display of the layer if it disturbs you).

**Comment by fredoh91** [comment]
OK, thank you very much for your answer.

**Comment by fredoh91** [comment]
![Vespucci_GPS](https://github.com/MarcusWolschon/osmeditor4android/assets/22547830/88b3e6cb-b644-447e-967a-5f169555c7bc)

I try to record my GPS track, and lock my phone after starting recording.

When I unlock my phone, Vespucci find quickly my new position (after clicking on the "current position" button).

But the application doesn't follow the current location, when the screen is off.

This is why, in my screenshot, I show area, in the GPS track, when vespucci doesn't follow the locationwhen the screen is off.

thanks

**Comment by simonpoole** [comment]
The application is not necessarily running while the screen is off (what exactly happens will depend on a lot of things), it is quite possible that on your device it is being paused and will need a second or so to start and get the current position from the tracking service.
