### ISSUE TITLE
German translation "No entry"-relation

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2407]
Description:
---

Currently, the "No entry"-relation is shown as "Kein Eintrag" in German; correct would be "Keine Einfahrt".

Device info:
---
<table>
<tr><td>App version</td><td>19.2.0.0</td></tr>
<tr><td>App version code</td><td>2601</td></tr>
<tr><td>Android build version</td><td>A715FXXU8BVA2</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RP1A.200720.012.A715FXXU8BVA2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a71</td></tr>
<tr><td>Device model</td><td>SM-A715F</td></tr>
<tr><td>Device product name</td><td>a71naeea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Morneo"/>Morneo</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Danke für die Meldung, gehört eigentlich in das Vorlagen Repo. Siehe oben.
