### ISSUE TITLE
Copy/Paste Tags Doesn't Work 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2409]
Description:
---

When I first copy an object's tags and then later paste I instead have the "system" clipboard pasted. 

Device info:
---
<table>
<tr><td>App version</td><td>19.2.0.0</td></tr>
<tr><td>App version code</td><td>2601</td></tr>
<tr><td>Android build version</td><td>G965U1UES9FVD1</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QP1A.190711.020.G965U1UES9FVD1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>star2qlteue</td></tr>
<tr><td>Device model</td><td>SM-G965U1</td></tr>
<tr><td>Device product name</td><td>star2qlteue</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/David Peters"/>David Peters</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Could you run me through your work flow as I can't recreate the issue here. You can paste from the system clip board but that is a different function than the app internal pasting.

**Comment by DavidPx** [comment]
Hey Simon!
This one is user error.  I was using the "paste from clipboard" menu choice within the object, expecting that to paste the tags I had previously copied. The "paste tags" choice from the main screen's hamburger menu works as expected.

Sorry for the bother and thanks for the follow up!

**Comment by simonpoole** [comment]
IIRC we used to use "Paste from system clipboard" as the text for that item, but it is long and not necessarily clear either. See http://vespucci.io/help/en/Property%20editor/#paste-from-clipboard
