### ISSUE TITLE
Waypoints stripped upon GPX upload 

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2415]
I shared a GPX track from OSMTracker into Vespucci.

I can see the waypoints fine in Vespucci.

But then if I "upload GPX track" the waypoints are stripped! All that is left are the trackpoints, there on the OSM website.

Yes, if I just uploaded directly from OSMTracker the problem doesn't occur. 

https://www.openstreetmap.org/user/jidanni/traces has two bad and two good at top. 

Also note the more relevant filenames chosen by OSMTracker.

**Comment by simonpoole** [comment]
"Upload GPX track" does exactly what is says on the box (it uploads the track). Is there any specific use case for which you want to have the waypoints on the OSM site?
