### ISSUE TITLE
ElementHistoryDialog doesn't handle network issues

### ISSUE THREAD

**Issue by opk12** [MarcusWolschon/osmeditor4android#2418]
## Vespucci Version
19.2.1.0, 19.1.2.0, a couple versions before 19.1.2.0.

## Download source
F-droid

## Device (Manufacturer and Model)
Samsung Android 7.1

## Android Version 
Samsung Android 7.1

## Behaviour/Symptoms
I had a weak network connection. I tapped for the history of an object and was told the element was deleted. I could not believe it and tried again, and really it was a network connection failure.

## Expected Behaviour
The error message should say there is a network connection failure.

## How to recreate
* Be online.
* Select a node.
* Press the Hamburger menu at the bottom right.
* Have an unreliable network connection, or disconnect the network.
* Press `History`.
* See `The Selected element has been deleted`.

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
Sounds like an upstream issue in https://github.com/zedlabs/ElementHistoryDialog

**Comment by simonpoole** [comment]
I just gave the code a look and it doesn't really handle network errors specifically at all. ping @zedlabs
