### ISSUE TITLE
 Check Internet connectivity before initiating downloads etc

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#242]
```
Investigate if behaviour in case of no network can be improved before opening a 
network connection etc. This is likely to be most interesting for tiles. 
```

Original issue reported on code.google.com by `sp8...@gmail.com` on 6 Nov 2014 at 1:19

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/8ec7ccf33f0a5b581e6b82de72f42197045f4fd3

Nothing done for tiles for now, created a separate issue.
