### ISSUE TITLE
Preset search results

### ISSUE THREAD

**Issue by octavo** [MarcusWolschon/osmeditor4android#2420]
The user would like better/more/accurate/category/synonym search results for presets.

The case is the user is looking for a node to add and is searching the presets quickly. The user searches 'post' but parcel lockers don't appear in the results.

Parcel lockers are an example of a recent addition that didn't appear in the search results but now do: [parcel locker].

post_office=post_partner, post_office:service_provider= are missing from the search results as a preset and sometimes autocomplete.

**Comment by simonpoole** [comment]
1st point: we rely on the same data as iD for synonyms, if there are none added that are applicable, there us literally nothing we can do, see https://github.com/MarcusWolschon/osmeditor4android#related-projects You need to add terms and we we'll pick them up the next time we update the synonyms.

2nd point this is a preset issue and should be raised in the preset repo https://github.com/simonpoole/beautified-JOSM-preset/blob/master/master_preset.xml we currently don't support the post_office subtag as it only very recently received any noticeable use, but feel free to open an issue there and I'll add it.
