### ISSUE TITLE
[DOCS] Add link to F-Droid to installing section

### ISSUE THREAD

**Issue by inson1** [MarcusWolschon/osmeditor4android#2423]
https://github.com/MarcusWolschon/osmeditor4android#installing

**Comment by simonpoole** [comment]
f-droid is not different then any other 3rd party build over which we have no control. Given that it has substantially less functionality than our original builds, we do not recommend them for "normal" users. If you want to install without accessing googles play store you can use the release builds from this repo, which are identical.

**Comment by inson1** [comment]
@simonpoole Why it has less functionality?

**Comment by simonpoole** [comment]
> @simonpoole Why it has less functionality?

Because F-Droid has no mechanism to provide API keys for the build (nor does F-Droid want them).
