### ISSUE TITLE
Reproducible build

### ISSUE THREAD

**Issue by opk12** [MarcusWolschon/osmeditor4android#2425]
reproducible-builds.org is a cross-distro effort to make builds verifiable (as in identical byte-per-byte) as a security guarantee that the binary was not infected by malware on the build server. Are the GitHub and Google Play builds reproducible and is Google Play doing an independent build? F-droid ([docs here](https://f-droid.org/en/docs/Reproducible_Builds/)) will do the rebuild and verification steps, if the upstream app is marked as reproducible and the maintainer commits to keeping it reproducible in the foreseeable future.

**Comment by simonpoole** [comment]
-We- do the build that is distributed on google play. Given that the contents are not the same (mainly numerous API keys that are different), no, there's not a remote chance that this will work.

**Comment by opk12** [comment]
Would it be feasible to auto-download on first start or something?

**Comment by simonpoole** [comment]
> Would it be feasible to auto-download on first start or something?

Just so that we in turn immediately get bad mouthed behind our backs because we are phoning home? 

Not to mention that that would simply be kicking the can down the road as we would still need a key of some sorts that would have to be different for 3rd party builds.

**Comment by opk12** [comment]
I'm not an Android dev, but I'm sure reproducible builds with API keys are definitely possible on F-droid if that's the problem.

If you're talking about the Bing AF, it was a matter of opening a bugreport at F-droid to fix the (definitely misleading) wording on the website and waiting 2 weeks. Full answer is [here](https://github.com/MarcusWolschon/osmeditor4android/issues/1642#issuecomment-1779161910).

**Comment by simonpoole** [comment]
> If you're talking about the Bing AF,

Bing, a number of other imagery sources that require api keys, Mapillary (not available in 3rd party builds because of that), pseudonymous github issue generation (not available in 3rd party builds because of that), and not to forget the raison d' être the OSM client key (different for 3rd party builds).

**Comment by opk12** [comment]
That's clear, thank you. F-droid has 5+ GitHub clients; OsmAnd with Mapillary and Bing / Microsoft Maps / Microsoft Hybrid; unrelated apps with the OAuth secret.

Why do you think that publishing the key into a .zip renamed .apk is more confidential / ToS-compliant to $company's eye than a repo? The key is being obfuscated perhaps?

**Comment by simonpoole** [comment]
It is simply an contractual issue plus avoiding being nagged at by github. That it doesn't provide any protection against anybody with a bit of motivation is clear, but on the other hand simply scanning the repo isn't enough.
