### ISSUE TITLE
Improve default experience

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#2430]
Vespucci is currently the only general-purpose OSM editor on Android, but people are frequently put off by the default experience, not discovering what it's capable of.

By merely improving some defaults, Vespucci can come closer to becoming the Android equivalent of iD - an editor which is not only general-purpose but also newbie-friendly.

Specifically, this involves -

1. Using aerial imagery by default, rather than OSM raster tiles. Esri is probably best, since it's available on both Google Play Store and F-Droid flavors.

   When I teach people to use Vespucci, adding an aerial imagery layer is one of the first things we cover. Having to dive into layers and imagery providers before even starting editing gives Vespucci the impression of being difficult, discouraging further exploration.

2. Enabling pan and zoom autodownload by default. This can be an issue for users with limited mobile data plans, so Vespucci should probably ask on the first run whether to enable it or not.

   I've met a number of people who tried Vespucci and gave up on it in favor of OsmAnd, StreetComplete, or Every Door - most of them didn't know that autodownload was even an option. Discovering it usually encourages them to give Vespucci another shot.

3. Informing the user to "Zoom in further to edit the map" when they are zoomed out beyond the autodownload threshold. Vespucci currently displays a similar message only when the user taps on the map, but showing it when zooming is more discoverable.

4. A default layer for displaying place names (ideally in the device language) on low zoom levels, overlaid on the aerial imagery. (As seen in iD.)

**Comment by simonpoole** [comment]
> 1. Using aerial imagery by default, rather than OSM raster tiles. Esri is probably best, since it's available on both Google Play Store and F-Droid flavors.

The reason we display the "standard style" map tiles is purely legal, all global imagery mosaics require a) accepting the providers ToS and b) exposing the users private information to a 3rd party typically located in a country with low to no privacy protection.

**Comment by contrapunctus-1** [comment]
I guess Vespucci could add another intro screen for that.

Screen 1
> **Enable aerial imagery?**
> Aerial imagery is the preferred background for most contributors. However, it also exposes your IP (and therefore your rough location) to a third party. These are typically located in a country with little to no privacy protection.
> By using aerial imagery you accept the `<link> $PROVIDER ToS </link>`
> You can enable or disable aerial imagery at any time from the `<layers icon>` layers menu.
> `[Use aerial imagery]`
> `[Don't use aerial imagery]`

Screen 2
> **Enable pan and zoom autodownload?**
> Autodownload removes the need for manually downloading data for editing.
> 
> However, it can also result in greater mobile data consumption, increased load on OSM servers, and performance problems on phones with limited RAM.
>
> You can enable or disable autodownload at any time from the `<menu icon>` Transfer menu.
>
> `[Enable autodownload]`
> `[Disable autodownload]`
