### ISSUE TITLE
Allow larger labels within preset boxes

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2436]
In the field, I noticed some of these labels are rather hard to read. Perhaps more use could be made of the empty area, to make the characters larger.
![Screenshot_20231120_132317_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/8a986b4b-e187-4205-891f-3fbea87d840f)

**Comment by simonpoole** [comment]
Increasing the font size in the system settings will increase the size of font used in the preset display.

**Comment by jidanni** [comment]
I searched and searched Preferences. I'm starting to slowly think that you mean  Android system settings. In other words changing that  would affect all the apps on my device.

But I don't want to change it for all the other apps on my device. They're fine.

**Comment by danieldegroot2** [comment]
See also https://support.google.com/accessibility/android/answer/6006949?hl=en#zippy=%2Cfull-screen-magnification-zoom-in-make-everything-bigger%2Cpartial-screen-magnification%2Cfull-screen-magnification-zoom-in-temporarily

**Comment by jidanni** [comment]
Yes, I could magnify in, and magnify back out. 
Or I could turn on magnification all day long for all the apps.
All that is not as good as simply just using more of the space that is being wasted..
