### ISSUE TITLE
New Crash with Javascript preset code since Vespucci v19.3

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#2438]
## Vespucci Version
19.3.1 (the problem has existed since v19.3.0)

## Download source
Google PlayStore

## Device (Manufacturer and Model)
Samsung A33

## Android Version 
13

## Behaviour/Symptoms
I already mentioned this issue in #2433, here is a complete description.

I created some custom presets for myself that use Javascript code to assign joined strings to a key as a value. Before Vespucci v19.3 this (example) Javascript code worked, but since v19.3.0 Vespucci crashes (without any error reporting):

```
<item name="Javascript Crash" icon="javascript.png" type="node,way,closedway,multipolygon,relation" preset_name_label="true">
	<text key="javascript_code" javascript="
		if(tags.get('TestKey') != null) {
			/* This line causes the crash (string join with +): */
			tags.put('Testoutput',['Value TestKey = ' + tags.get('TestKey')[0]]);
		} else {
			tags.put('Test_Note',['TestKey=123 serves as a test tag (value can also be changed). Then run this test preset again!']);
			tags.put('TestKey',['123']);
		}
		tags.remove('javascript_code');" />
</item>
```

It seems to have something to do with my perhaps unconventional method of querying and assigning values via `tags.get(Key,[0])` and `tags.put(Key,[Value_as_string])` in conjunction with string join via `+` (and perhaps with Javascript data type conversion?).

Because if you use an explicit data conversion with `String()`, or the Javascript method `.concat()` or value assignment using `function setKeyValue(key,value)` or no string join at all, then no crash will occur.

Examples without a crash:

(1) – Without any string join:

```
<item name="No Crash 1 – without string join" icon="javascript.png" type="node,way,closedway,multipolygon,relation" preset_name_label="true">
	<text key="javascript_code" javascript="
		if(tags.get('TestKey') != null) {
			/* No crash without any string join: */
			tags.put('Testoutput',[tags.get('TestKey')[0]]);
		} else {
			tags.put('Test_Note',['TestKey=123 serves as a test tag (value can also be changed). Then run this test preset again!']);
			tags.put('TestKey',['123']);
		}
		tags.remove('javascript_code');" />
</item>
```

(2) – String Join and using the String() function for explicit data conversion:

```
<item name="No Crash 2 – using String()" icon="javascript.png" type="node,way,closedway,multipolygon,relation" preset_name_label="true">
	<text key="javascript_code" javascript="
		if(tags.get('TestKey') != null) {
			/* If using the String() function for explicit data conversion, no crash occurs: */
			tags.put('Testoutput',[String('Value TestKey = ' + tags.get('TestKey')[0])]);
		} else {
			tags.put('Test_Note',['TestKey=123 serves as a test tag (value can also be changed). Then run this test preset again!']);
			tags.put('TestKey',['123']);
		}
		tags.remove('javascript_code');" />
</item>
```

(3) – String Join using the .concat() method for the string join:

```
<item name="No Crash 3 – using .concat()" icon="javascript.png" type="node,way,closedway,multipolygon,relation" preset_name_label="true">
	<text key="javascript_code" javascript="
		if(tags.get('TestKey') != null) {
			/* No crash if using the concat method for the string join: */
			tags.put('Testoutput',['Value TestKey = '.concat(tags.get('TestKey')[0])]);
		} else {
			tags.put('Test_Note',['TestKey=123 serves as a test tag (value can also be changed). Then run this test preset again!']);
			tags.put('TestKey',['123']);
		}
		tags.remove('javascript_code');" />
</item>
```

(4) – String Join using `+` and the array function `setKeyValue(key,value)`:

```
<item name="No Crash 4 – using the array function setKeyValue" icon="javascript.png" type="node,way,closedway,multipolygon,relation" preset_name_label="true">
	<text key="javascript_code" javascript="
		function setKeyValue(key,value) {
			v = new java.util.ArrayList();
			v.add(value);
			tags.put(key,v); }
		if(tags.get('TestKey') != null) {
			/* No crash if using + for string join and the array function setKeyValue: */
			setKeyValue('Testoutput','Value TestKey = ' + tags.get('TestKey')[0]);
		} else {
			tags.put('Test_Note',['TestKey=123 serves as a test tag (value can also be changed). Then run this test preset again!']);
			tags.put('TestKey',['123']);
		}
		tags.remove('javascript_code');" />
</item>
```

## To the background:
My presets are used to create traffic_sign=* tags with multiple values such as traffic_sign="DE:205;209-10" from the values (numbers) of individual signs (here DE:205 and DE:209-10), which then form the composite value. (With further checks via Javascript to see whether a value already exists, and so on – the complete code is more complex than the example code above.)

A string join is necessary here, and I wanted to use the simplest and most compact code (with the + operator, `tags.get(Key,[0])` and `tags.put(Key,[Value_as_string])`).

## Expected Behaviour
If possible, it could work like before v19.3 ... I already asked in #2433 whether something has changed in the Javascript engine, but there was no answer yet. But maybe there is another reason.

I was able to change my presets using the methods above (using `String()` was the easiest way), and they work again, but anyway: it would be nice if there wouldn't be a crash even with the old code.

## Crash dump submitted (no or yes + date)
No. There is no Vespucci crash report starting after the crash.

**Comment by simonpoole** [comment]
The crash seems to be due to https://www.servicenow.com/community/developer-forum/javascript-consstring-error-quot-org-mozilla-javascript/td-p/1935023

```
   <item name="Javascript Crash" icon="javascript.png" type="node,way,closedway,multipolygon,relation" preset_name_label="true">
        <text key="javascript_code" javascript="
            if(tags.get('TestKey') != null) {
                /* This line causes the crash (string join with +): */
                tags.put('Testoutput',[('Value TestKey = ' + tags.get('TestKey')[0]).toString()]);
            } else {
                tags.put('Test_Note',['TestKey=123 serves as a test tag (value can also be changed). Then run this test preset again!']);
                tags.put('TestKey',['123']);
            }
            tags.remove('javascript_code');" />
    </item>
```
Works as expected.


Note that we haven't upgraded our Rhino version for a long time, so there's no reason that this crash should suddenly appear, we should naturally be catching the ClassCastException as we don't want scripts to be crashing the app.

**Comment by jajajaneeneenee** [comment]
Thank you for the explanation and the link ... and another solution via `.toString()`.

All I can say is that I hadn't changed anything in the Javascript code for months (or longer) and the crash occurred exactly from Vespucci v19.3.0. But since the solution is really simple, it doesn't pose a major problem.

And if such crashes could be intercepted – all the better!
