### ISSUE TITLE
MbTiles support for offline OSM data broken?

### ISSUE THREAD

**Issue by felagund** [MarcusWolschon/osmeditor4android#2455]
Description:
--- I might be doing something wrong, the docs are not the clearest, but I do not see what.

1. I downloaded the Guernsey map from 
https://mapsplit.poole.ch/

2. I press the layer button in upper right corner
3. I click the three dots next to the OpenStreetMap data
4. I select configure and add API
5. I try to select the downloaded file for Read-only API
Result:
I get an error saying the file is not in MBTiles format. Custom maps Improduced with mapsplit also do not work:

![Screenshot_20231211-142945_Vespucci](https://github.com/MarcusWolschon/osmeditor4android/assets/1218098/376169cf-e3f5-4984-9a79-cfc9cdb949e4)

Edit: I tried with app version 13.1 and 19 and it is not a regression, it never works, just the error message changed between 13 and 19.

Device info:
---
<table>
<tr><td>App version</td><td>19.3.1.0</td></tr>
<tr><td>App version code</td><td>2702</td></tr>
<tr><td>Android build version</td><td>M515FXXS5DWG1</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.M515FXXS5DWG1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>m51</td></tr>
<tr><td>Device model</td><td>SM-M515F</td></tr>
<tr><td>Device product name</td><td>m51nseea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
Further note: this could very well be a file access issue as you are running Android 12. Downloading via the UI will guarantee that these are correct.

**Comment by felagund** [comment]
Thank you for the swift reply. I sent the debug info (from the app - it does not show any confirmation, does it?).

It is truly bizzare. Downloading the file through Vespucci makes this work. The file I downloaded externally is the same, md5sum is the same, permissions are the same. Yet one works and one does not (the one downloaded from Vespucci is in folder Vespucci, the manually downloaded on is one folser above; i tried to move it to Vespucci folder but that does not change anything):
![Screenshot_20231211-155418_Termux](https://github.com/MarcusWolschon/osmeditor4android/assets/1218098/cc3ca1dc-76f8-4c67-8021-7542b6f9ea02)

**Comment by simonpoole** [comment]
Yes, welcome to the world of Android :-). Post Android 10 we only get random access (needed for SQLite) to to files if they are both in a directory considered to be "safe" and are owned by the app. We work around this in most circumstances by actually copying the files, I just considered this too expensive (space wise) for these data files.

In any case the error message is confusing and I'll fix that.

**Comment by felagund** [comment]
Hm, when I try to copy the file downloaded from Vespucci to Downloads directory on my SD card, it starts saying "Element not found". Same result with the file I downloaded manually. The files were originally downloaded to Downloads directory on internal storage.

**Comment by felagund** [comment]
How can I make my files to be owned by Vespucci? Moving them to Vespucici directory does not help.

**Comment by simonpoole** [comment]
> So, is my understanding correct then that on Android 10+, one can only use this feature with files that are available on https://mapsplit.poole.ch/ and user-generated files with malsplit cannot be used at all? Google, that is ridiculous!

Yes, though I can implement the same workaround that we have for other similar cases as I mentioned above, aka make a copy of the file on Android 10+ devices, perhaps showing a modal first.

There is one other potential workaround, that is to ask for the MANAGE_EXTERNAL_STORAGE permission in Android 11 and later (note that this isn't a solution for Android 10), the downside is that it is that it is too broad and puts you even more at the mercy of google if your app gets released or not. See https://developer.android.com/training/data-storage/manage-all-files

**Comment by felagund** [comment]
Well, I would be happy for either, though the import sounds safer google-wise.

Another solutuon would be to generate the offline maps on your side for more locations, but I guess that would be expensive (given offline data are old anyway, maybe they could be generated once a week and not daily or something like that).

The app can then tell the user the file can be deleted after importing.

I now have two nice unusable files of Chile and Argentina on my phone, where I am currently heading for three months. I will be days and sometimes weeks withou internet, so offline support would have been crucial. I will make waypoints with notes and them work through them with JOSM once I get back but some things would have been way easier to modify right away with Vespucci.

Thanks for your swift and insightful reply though, I really appreciate it!

**Comment by simonpoole** [comment]
I can easily generate files for Chile and Argentina, when are you leaving (note they will update daily just as the other files)?

**Comment by felagund** [comment]
Well, I am taking my flight tonight but I would be able to download them from there too, that would be awesome, thanks!

Dec 11, 2023 16:47:27 Simon Poole ***@***.***>:

**Comment by simonpoole** [comment]
For whatever reason Argentina didn't work, but Chile is generated. I'll give Argentina a look when I get back home

**Comment by simonpoole** [comment]
Seems to have been a typo on my behalf, re-running as I type. Note that I haven't actually tested the files yet, but there is no reason that they shouldn't work.

**Comment by simonpoole** [comment]
So Argentina is there now too.

**Comment by felagund** [comment]
Perfect, thank you, both work!

**Comment by simonpoole** [comment]
The changes unluckily won't make it in to version 19, but will have to wait for version 20.

If you have any issues or questions while away feel free to ask.
