### ISSUE TITLE
Problem with background

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2463]
Description:
---

Hallo,
Seems there's a Problem with the map "Stuttgart Luftbild Stadtmessungsamt 2021 (wms)".
By selecting it for background, IT doen't load anything and shows the Info "map produces error".

Greets 

Device info:
---
<table>
<tr><td>App version</td><td>19.3.1.0</td></tr>
<tr><td>App version code</td><td>2702</td></tr>
<tr><td>Android build version</td><td>S911BXXS3BWK5</td></tr>
<tr><td>Android release version</td><td>14</td></tr>
<tr><td>Android SDK version</td><td>34</td></tr>
<tr><td>Android build ID</td><td>UP1A.231005.007.S911BXXS3BWK5</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dm1q</td></tr>
<tr><td>Device model</td><td>SM-S911B</td></tr>
<tr><td>Device product name</td><td>dm1qxeea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/basdie"/>basdie</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Scheint als ob der Layer generell nicht tut (so auch in iD). M.a.W: muss man beim Anbieter anklopfen, oder wenn einfach die URL falsch ist das im  https://github.com/osmlab/editor-layer-index korrigieren.

**Comment by simonpoole** [comment]
Scheint wieder zu tun.
