### ISSUE TITLE
Change upload mechanism to uploading diff files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#247]
```
Currently vespucci uploads changes one at a time. This requires creating a new 
connection for each element and can be rather slow, further API 0.7 will likely 
depreceate this and require diff uploads.

```

Original issue reported on code.google.com by `sp8...@gmail.com` on 16 Nov 2014 at 11:54

**Comment by simonpoole** [comment]
Doesn't seem if we will be getting API 0.7 in the time frame foreseen for 0.9.7 delay to 0.9.8

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/pull/465
