### ISSUE TITLE
Tag-only mode should make it clearer what I am editing

### ISSUE THREAD

**Issue by osmuser63783** [MarcusWolschon/osmeditor4android#2472]
I quite like tag-only mode (its main purpose, for me, is to prevent you from accidentally moving objects when you are just trying to move the map.)

But try tagging a path or a road with a tag e.g. smoothness or trail_visibility. When you tap a segment of road the tagging screen immediately opens, and when you close the tagging screen, the segment is immediately unselected. This means there is no visual feedback on how long the segment of road or path is that you have just edited, and you also don't know where the next one begins, which is a problem when you are trying to make sure that every segment along a path/road has been tagged.

One solution would be for tag only mode to not immediately open the tagging screen after tapping an element, so you can check what you're editing before you edit it and/or not immediately unselect the element after editing it. (See also #522)

Another improvement would be to visually highlight any elements you have edited in the current session. (But I imagine that the first suggestion is much less work!)

Apologies if I have missed something, I don't consider myself an expert user of Vespucci.

**Comment by simonpoole** [comment]
As it is the tag only mode is currently most useful for actual POIs and using it on roads (or other similar objects) is a bit of an edge case. IMHO at least "tag-only classic" mode should continue to directly start the property editor, but there is clearly room for other variants.

**Comment by simonpoole** [comment]
Related: https://github.com/MarcusWolschon/osmeditor4android/issues/522

**Comment by simonpoole** [comment]
BTW as a workaround: if you turn on split window mode for the property editor https://vespucci.io/help/en/Advanced%20preferences/#enable-split-window-property-editor, you do see the visible feedback from the map screen.

**Comment by osmuser63783** [comment]
Thanks, amazing!
