### ISSUE TITLE
Details editor can't clear values

### ISSUE THREAD

**Issue by goldfndr** [MarcusWolschon/osmeditor4android#2475]
## Vespucci Version
19.3.2.0, 19.3.3.0

## Download source
Google Play Store

## Device (Manufacturer and Model)
Samsung Z Fold3 (cover)

## Android Version 
13

## Behaviour/Symptoms
Clearing a value (e.g. yes for bridge and 1 for layer or give_way for highway) in the Details tab is not retained after tapping the check mark in the upper left corner. Values changed but not cleared *are* kept.

## Expected Behaviour
It shouldn't be necessary to use the Properties tab, or tick box(es) and tap the trash bin, for clearing values. I thought for sure that I'd successfully cleared tags in the recent past this way, especially tiger tags. If the Details values cannot be simply cleared (e.g. due to a preference), a toast would be helpful.

## How to recreate
Go to https://www.openstreetmap.org/way/1176773639 and edit it. On the Details tab, clear the values for `bridge` and `layer` (delete characters until the hint shows), then tap ✔ to keep. Edit again and observe the values weren't cleared.

(also occurs on an Amazon Fire HD 10 gen 7 with Fire OS 5.7.1.0 and an LG V50 with Android 10, both with Vespucci 19.3.2.0)

**Comment by goldfndr** [comment]
For better clarity, using the tick boxes and trash bin *does* correctly commit the changes, so this isn't a full showstopper for the Details tab.

**Comment by simonpoole** [comment]
Clearly a defect, not quite sure why the tests didn't pick it up.

**Comment by simonpoole** [comment]
The test case was slightly different to what was happening here and that actually worked.

Thanks for the report.
