### ISSUE TITLE
19.3.3 Release

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2478]
Description:
---

The latest release is entitled: "19.3.3 Release", and the files contain version 19.3.2.  Why is that?

Device info:
---
<table>
<tr><td>App version</td><td>19.3.2.0</td></tr>
<tr><td>App version code</td><td>2703</td></tr>
<tr><td>Android build version</td><td>V14.0.8.0.TKFMIXM</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>TKQ1.221013.002 test-keys</td></tr>
<tr><td>Device brand</td><td>Redmi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>sweet</td></tr>
<tr><td>Device model</td><td>M2101K6G</td></tr>
<tr><td>Device product name</td><td>sweet_global</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/mike140"/>mike140</A></td></tr>
</table>

**Comment by simonpoole** [comment]
I've notified @MarcusWolschon it is likely just an accidental upload of the previous APKs.

**Comment by simonpoole** [comment]
Seems as if Marcus fixed this.
