### ISSUE TITLE
Incorrect color display

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#2480]
Blue and partially green colors are displayed incorrectly in the vector layer style color selection window. This is what blue looks like:
![Screenshot_2024-01-20-21-31-59-509_de blau android](https://github.com/MarcusWolschon/osmeditor4android/assets/69987154/e5f02153-fd4d-4883-bb2b-282aabf854a0)

## Vespucci Version
19.3.3.0

## Download source
github

## Device (Manufacturer and Model)
Redmi Note 10 Pro

## Android Version 
13

**Comment by simonpoole** [comment]
That looks very much like as if, actually guaranteed to be, you have tritanomaly colour blindness accessibility mode turned on.

**Comment by simonpoole** [comment]
The dead giveaway is that all the other colors including those not set by Vespucci are off. Not to mention that I can trivially recreate the issue locally by turning the accessibility mode on.
