### ISSUE TITLE
Lock should  turn on after months of inactivity

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2487]
Usually the lock turns on after 60 seconds of inactivity.

However it wasn't on even after 2 months of inactivity.

Yes, it probably needs 2 months plus 60 seconds to turn on.

I'm just saying after the user hasn't been using the app for a few months, and then activates the app. It really should just assume that the 60 seconds of expired and turn on the lock, for safety sake. Thank you.

Probably after 15 minutes in an unknown state it should turn on that lock. It should assume the counter got frozen.

**Comment by simonpoole** [comment]
How is the app supposed to know that (it was inactive for two months)?

**Comment by jidanni** [comment]
Maybe something like https://stackoverflow.com/questions/13205952/how-to-get-last-opened-date-of-an-application-in-android

(P.S., I almost didn't see your question. Good thing there is https://webapps.stackexchange.com/questions/173729/on-github-how-to-get-notified-despite-block/173730 .)
