### ISSUE TITLE
Style settings errors

### ISSUE THREAD

**Issue by mic140** [MarcusWolschon/osmeditor4android#2489]
In the geojson file style settings, changing the symbol type has no effect.  Also, selecting an option in the "Label" field does not cause that option to appear next to the feature icon on the map.

![IMG_20240131_163703](https://github.com/MarcusWolschon/osmeditor4android/assets/69987154/b67545af-92d1-4b26-9459-2213f82f7c8e)

Vespucci Version
19.3.3.0

Download source
github

Device (Manufacturer and Model)
Redmi Note 10 Pro

Android Version
13

**Comment by mic140** [comment]
[fiz-geo-sumska.zip](https://github.com/MarcusWolschon/osmeditor4android/files/14114672/fiz-geo-sumska.zip)

**Comment by mic140** [comment]
> I can replicate the issue with the symbol, but not with the label (I use that all the time). Can you add the GeoJSON file to the issue, so that I can test?

Can you send me a file in which the labels are displayed on the map?

**Comment by mic140** [comment]
Thanks, I didn't notice this setting

**Comment by mic140** [comment]
Should labels be displayed on area objects?  I can not

**Comment by simonpoole** [comment]
Currently labels are only supported on POINT and MULTIPOINT geometries, there's not a fundamental issue with supporting them on other geometries outside of it being a bit slow.

**Comment by mic140** [comment]
> Currently labels are only supported on POINT and MULTIPOINT geometries, there's not a fundamental issue with supporting them on other geometries outside of it being a bit slow.

I wish this would be implemented

**Comment by simonpoole** [comment]
The symbol issue is fixed in https://github.com/MarcusWolschon/osmeditor4android/pull/2494, sorry that this took a while but I was on vacation.
