### ISSUE TITLE
vespucci tried to download a huge thin rectangle from bucharest to somewhere in africa

### ISSUE THREAD

**Issue by hehehe92** [MarcusWolschon/osmeditor4android#2496]
i clicked on a notification saying "fixme: some bus stops are missing from this relation" and this happened
![Screenshot_20240216-111142_Vespucci](https://github.com/MarcusWolschon/osmeditor4android/assets/158172547/a12a4942-0d9e-4ecf-8a53-5d1e7d67a25f)

## Vespucci Version
19.3.3

## Download source
f-droid

## Device (Manufacturer and Model)
Samsung Galaxy S9

## Android Version 
10

**Comment by simonpoole** [comment]
Do you have a link to the object that had the FIXME on it?  The way this is supposed to work is that a bounding box around the object will be downloaded, that should include the object itself. Seems as if something went wrong during calculation of the box, this can happen with relations naturally, but shouldn't lead to the behaviour you are seeing.

**Comment by hehehe92** [comment]
i think i also clicked clear data between the notification appeared and i clicked it

**Comment by hehehe92** [comment]
no, but maybe we can find it in overpass?

**Comment by simonpoole** [comment]
> i think i also clicked clear data between the notification appeared and i clicked it

I need to check if that could auch an issue.

**Comment by hehehe92** [comment]
it's relation 15067882, and the rectangle starts at a bus stop where that bus can come

**Comment by simonpoole** [comment]
Seems to be a regression introduced in https://github.com/MarcusWolschon/osmeditor4android/commit/9e810d3cdd8a4777eb77b7fb0e3b8d7a61a8ca4e due to a C&P error
