### ISSUE TITLE
Feature request: support custom tile server

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#250]
```
It will be very helpful if Vespucci can support custome tile server. Let users 
to fill tile url template.

For example, if users want to use "no name" overlay from http://qa.poole.ch/
they can input something like
http://tile3.poole.ch/noname/{z}/{x}/{y}.png
```

Original issue reported on code.google.com by `kuang...@gmail.com` on 1 Dec 2014 at 8:46

**Comment by simonpoole** [comment]
This has been resolved in principle for ages: in your Vespucci directory you can located a file named "imagery.json" in imagery index format with whatever custom tile servers you want. Note however that they will be checked against the imagery blacklist.

This issue has been left open pro-memoria on case we want to and a UI for individual servers.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/5eed17327a67ea6cfae4b8a666196f7105c7c954 note custom imagery in file format is still supported (though it has changed to the newer geojson based format).
