### ISSUE TITLE
UI errors on dark theme switch

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#2500]
## Vespucci Version

19.3.4

## Download source

Google Play

## Device (Manufacturer and Model)

Fairphone 4

## Android Version 

13

## Behaviour/Symptoms

When the system theme switches from dark to bright at sunrise while Vespucci is open, there are some interface color errors, like this one from the changeset comment suggestions:

![Screenshot_20240221-074213.png](https://github.com/MarcusWolschon/osmeditor4android/assets/30999326/e7e2e505-11cc-4121-9f25-c4133807c351)

## Expected Behaviour

Flawless switching of themes

## How to recreate

I guess this can be recreated by manually switching system theme from dark to bright. 

## Crash dump submitted (no or yes + date)

No

**Comment by simonpoole** [comment]
This is not unexpected, we currently force activities to recreate, but don't do anything special for DialogFragments (the upload modal is one), and it isn't even really clear what would work.

> I guess this can be recreated by manually switching system theme from dark to bright.

Unluckily not, manually changing the system theme in the device settings doesn't call the onConfigurationChange callback in the activities.

**Comment by simonpoole** [comment]
The interesting thing is after I've fixed the issue with detecting the theme change, things seem to work as expected:

[following_system_theme.webm](https://github.com/MarcusWolschon/osmeditor4android/assets/1011860/87699735-73a7-4e0b-aa1c-c24b02c1606c)
