### ISSUE TITLE
Path missing from data

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#2512]
## Vespucci Version

19.3.4

## Download source

Google Play

## Device (Manufacturer and Model)
Fairphone 4

## Android Version 
13

## Behaviour/Symptoms
Path is missing from data, also after delete and redownload
 ![Screenshot_20240301-145605.png](https://github.com/MarcusWolschon/osmeditor4android/assets/30999326/b6516c6b-9d36-405a-a0b1-18391aa29c7b)
https://www.openstreetmap.org/way/822836112#map=16/54.3331/10.1097

## Expected Behaviour
Data should be complete 

## How to recreate
Download area around https://www.openstreetmap.org/query?lat=54.33301&lon=10.10965#map=19/54.33331/10.11050

## Crash dump submitted (no or yes + date)
No

**Comment by simonpoole** [comment]
The OSM API map call will only return ways that have at least one node in the downloaded area, which the way in question however doesn't have. Vespucci doesn't behave differently than OSM, iD or any other OSM editor in this respect.
