### ISSUE TITLE
Pan and zoom auto download glitches and produces errors

### ISSUE THREAD

**Issue by PizzaTreeIsland** [MarcusWolschon/osmeditor4android#2523]
Description:
---
Paning and zooming around causes error 403 a lot and the flickering of the darkened out areas make it impossible to work. See video. 

https://github.com/MarcusWolschon/osmeditor4android/assets/163044645/a925daf9-c5cd-4477-8eb5-77f63623c206

Device info:
---
<table>
<tr><td>App version</td><td>19.3.5.0</td></tr>
<tr><td>App version code</td><td>2706</td></tr>
<tr><td>Android build version</td><td>2401161446</td></tr>
<tr><td>Android release version</td><td>14</td></tr>
<tr><td>Android SDK version</td><td>34</td></tr>
<tr><td>Android build ID</td><td>U2.5-240116-1446</td></tr>
<tr><td>Device brand</td><td>Nothing</td></tr>
<tr><td>Device manufacturer</td><td>Nothing</td></tr>
<tr><td>Device name</td><td>Pong</td></tr>
<tr><td>Device model</td><td>A065</td></tr>
<tr><td>Device product name</td><td>PongEEA</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
This is likely an issue with the OSM API/one of the frontends, seems to have gone away for now.

**Comment by simonpoole** [comment]
Seems if there is a DDOS attack underway, so outside of our control.
