### ISSUE TITLE
Intent does not move to correct location if internet is disconnected

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2525]
`intent:42.0303389,-87.6795967
?z=16#Intent;scheme=geo;launchFlags=0x13000000;end`

This intent will function correctly, if the internet is connected.

However if the internet is not connected the position will not be moved at all. We will remain at the previous position.

**Comment by simonpoole** [comment]
This because it tries to download data around the target location, which will fail for obvious reasons, setting the download radius to zero http://vespucci.io/help/en/Advanced%20preferences/#download-radius will stop the app from trying to do that.
