### ISSUE TITLE
Cannot find building:shed

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2526]
![Screenshot_20240314_133640_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/2b805347-9b44-4b8b-8a32-f280a0e196a9)

https://wiki.openstreetmap.org/wiki/Tag:building%3Dshed not found.

**Comment by simonpoole** [comment]
From the the presets displayed it seems fairly clear that you didn't have a closed way or a mp relation selected. So you won't get any matches for objects that only apply to them.

**Comment by jidanni** [comment]
It turns 
![Screenshot_20240316-174022.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/8ce9f435-ff39-4fea-9fb6-4835b5288e22)

It turns out there is no way for users to tell if their way is really closed or not, other than by checking the Info menu item!

I recommend having their insides look different, like in iD.

No, "snap" mode is no guarantee.

**Comment by simonpoole** [comment]
The "insides" can only look consistently different if we already know that the intention is to create an area, which we only know after a preset has been applied.
