### ISSUE TITLE
Deselect and lock all in one tap

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#2527]
![Screenshot_20240315_221659_Vespucci.jpg](https://github.com/MarcusWolschon/osmeditor4android/assets/1230959/735aa0f0-2005-4521-a895-3844c7f79755)

Here if we tap in the same spot two times we can deselect, and lock. Even easier would be allowing just one tap to do both actions. This might need an extra new icon on the page though. It should be right next to the arrow there in the upper left.

Another possibility people might want is to lock but not deselect.

**Comment by simonpoole** [comment]
We are not adding additional user interface elements at this point in time. We get enough complaints as is.
