### ISSUE TITLE
Use NotificationManagerCompat

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#2529]
Currently we use our own code for backwards compatibility, using current (requires androidx.core:core:1.11.0) NotificationManagerCompat might reduce some of that.

See https://github.com/MarcusWolschon/osmeditor4android/pull/2528

**Comment by johnjohndoe** [comment]
Be aware of this function different from the usual way to get an instance: https://github.com/EventFahrplan/EventFahrplan/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fnerd%2Ftuxmobil%2Ffahrplan%2Fcongress%2Fextensions%2FContexts.kt
