### ISSUE TITLE
The redo function is too well hidden

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#253]
```
The undo button should always show a popup menu asking if you want to undo or 
redo, if there is something to redo.

Otherwise I think a lot of people won't know it's there.
```

Original issue reported on code.google.com by `char...@derkarl.org` on 6 Dec 2014 at 6:08

**Comment by HolgerJeromin** [comment]
Wow. There is an redo function!
Perhaps the first undo should generate an popup explaining this.

**Comment by simonpoole** [comment]
It is well documented.

**Comment by HolgerJeromin** [comment]
Yeah, i just read the documentation after years of vespucci usage to find other cool stuff :-)

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/3dc4ff500c2d8eb4c6dfcd9f5ccd83c3d3386e47 adds a one time message when using the undo button.
