### ISSUE TITLE
Openstreetmap data not downloading

### ISSUE THREAD

**Issue by davidpnewton** [MarcusWolschon/osmeditor4android#2534]
## Vespucci Version
20.0.0.1

## Download source
Google Play

## Device (Manufacturer and Model)
Samsung Galaxy A55

## Android Version 
14

## Vespucci Version
20.0.0.1

## Behaviour/Symptoms
When starting Vespucci the Openstreetmap data layer simply does not load, meaning editing of the map us not possible.

## Expected Behaviour
Openstreetmap data layer loading on start up to allow Map editing

## How to recreate
Start Vespucci and wait for layers to liad

## Crash dump submitted (no or yes + date)
No crash

## Any other potentially relevant information
Software running on Galaxy A55 with problems starting after software and settings copied across using Samsung Smartswitch.

**Comment by simonpoole** [comment]
Do you get an error message? 

In any case as noted in the release notes former saved state is not compatible with 20.0. Normally you should simply get an error message, if you don't, I would suggest starting in safe mode and reseting the saved state.

**Comment by davidpnewton** [comment]
No error message. It simply sits there and doesn't download the data layer.

I'll try the suggestion of restarting in safe mode.

**Comment by davidpnewton** [comment]
*sigh*

Simple explanation as it turns out: thr auto download features for the data had been turned off somehow.
