### ISSUE TITLE
coords

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2535]
Description:
---

Get position info returns No usable location. How to fix?

Device info:
---
<table>
<tr><td>App version</td><td>19.3.5.0</td></tr>
<tr><td>App version code</td><td>2706</td></tr>
<tr><td>Android build version</td><td>G715FNXXSDFXA1</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>TP1A.220624.014.G715FNXXSDFXA1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>xcoverpro</td></tr>
<tr><td>Device model</td><td>SM-G715FN</td></tr>
<tr><td>Device product name</td><td>xcoverproeea</td></tr>
<tr><td>Device hardware name</td><td>exynos9611</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/nappr"/>nappr</A></td></tr>
</table>

**Comment by simonpoole** [comment]
The message is displayed if we cannot retrieve a valid GPS/GNSS location from the device. So either you have no GPS reception or it isn't enabled on your device.
