### ISSUE TITLE
R8 minified APK broken

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#2539]
The fake release and by extension the release APKs hang on startup. Preliminary analysis indicates that this is due to an R8 issue.

**Comment by aarewhyan** [comment]
Piggybacking this issue to ask a general query on releases and installations. Why does all the installation of the application on devices has this - missing preset file & missing auto-preset file Exception? (Some also has a failed to open database exception) While opening the app most time is usually spent on the [Please wait : Loading preset] window, that is why I wanted to ask this.

See here logs for master-branch installation of this application
[master Oneplus 2024-04-01-A.txt](https://github.com/MarcusWolschon/osmeditor4android/files/14817902/master.Oneplus.2024-04-01-A.txt)

Here are the same logs mixed with the device wide logs
[master Oneplus full 2024-04-01-A.txt](https://github.com/MarcusWolschon/osmeditor4android/files/14817903/master.Oneplus.full.2024-04-01-A.txt)

**Comment by simonpoole** [comment]
> Why does all the installation of the application on devices has this - missing preset file & missing auto-preset file Exception?

We need to test if there is already an existing tile database or not, if it already exists and is readable we don't need to create it, For whatever reason the Android Sqlite implementation always writes out a stack trace when it can't open a database instead of just throwing an exception (which we duly catch).
