### ISSUE TITLE
5h work (& fun)  lost

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2543]
Description:
---

Heyhey,

Yeah, maybe better to upload smaller changesets.... And before I never had a issue with this great app...

Now, the update with the message about oauth change deleted all my uncommitted changes :-(

No complaints, just for info. I love the app!

Best regards
Metzor

Device info:
---
<table>
<tr><td>App version</td><td>20.0.0.0</td></tr>
<tr><td>App version code</td><td>2801</td></tr>
<tr><td>Android build version</td><td>S901BXXS7DXBD</td></tr>
<tr><td>Android release version</td><td>14</td></tr>
<tr><td>Android SDK version</td><td>34</td></tr>
<tr><td>Android build ID</td><td>UP1A.231005.007.S901BXXS7DXBD</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>r0s</td></tr>
<tr><td>Device model</td><td>SM-S901B</td></tr>
<tr><td>Device product name</td><td>r0sxeea</td></tr>
<tr><td>Device hardware name</td><td>s5e9925</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Metzor"/>Metzor</A></td></tr>
</table>

**Comment by simonpoole** [comment]
It is noted all over the place that you need to always upload before updating.

That said you should have plenty of auto-save files with your edits see https://vespucci.io/help/en/18.0.0%20Release%20notes/#auto-save-support and https://vespucci.io/help/en/Advanced%20preferences/#auto-save-configuration

You will need the OSC files, as, as you noticed the state file format has changed.
