### ISSUE TITLE
Lost data after upgrade

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2544]
Description:
---

I did some Vespucci editing, and then Google Play upgraded Vespucci before I uploaded my edits. Now I can't see my edits. Is there any way to restore these edits?

Device info:
---
<table>
<tr><td>App version</td><td>20.0.0.0</td></tr>
<tr><td>App version code</td><td>2801</td></tr>
<tr><td>Android build version</td><td>11445699</td></tr>
<tr><td>Android release version</td><td>14</td></tr>
<tr><td>Android SDK version</td><td>34</td></tr>
<tr><td>Android build ID</td><td>AP1A.240305.019.A1</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>oriole</td></tr>
<tr><td>Device model</td><td>Pixel 6</td></tr>
<tr><td>Device product name</td><td>oriole</td></tr>
<tr><td>Device hardware name</td><td>oriole</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/kimo"/>kimo</A></td></tr>
</table>

**Comment by HolgerJeromin** [comment]
see #2543
