### ISSUE TITLE
Aerial imagery

### ISSUE THREAD

**Issue by octavo** [MarcusWolschon/osmeditor4android#2545]
Aerial images for cph do not seem to be available anymore as before. The user uses aimagery when mapping from memory eg.

**Comment by simonpoole** [comment]
cph is ? But in general issues wrt imagery sources belong in https://github.com/osmlab/editor-layer-index see also http://vespucci.io/tutorials/faq/#the-aerial-or-satellite-imagery-is-out-of-date

**Comment by octavo** [comment]
The user found them under 'Add background imagery layer ...'.
