### ISSUE TITLE
Wrong state after restart in property editor (was Cut/copy missing from property editor)

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#2547]
Vespucci 20.0.0
Flavor: current
Target SDK: 33

When editing the raw tags of an osm element I can select, paste tags like before.
But I do not find the copy icon.

![Screenshot_20240426-223403_copy_540x397](https://github.com/MarcusWolschon/osmeditor4android/assets/2410353/2f5195c8-c037-4fe2-b8dd-3da183aff868)

**Comment by simonpoole** [comment]
Any idea how you got to that state? And is that repeatable?

Normally selecting one or more or more of the check boxes will start an action mode that will display 'Tags selected' and the copy icon.

**Comment by simonpoole** [comment]
I've kind of been able to repeat that by selecting a tag then starting help and not terminating the property editor regularly. 

Terminating help and the app completely makes the issue go away on next start. So it's likely just some state mixup.

**Comment by HolgerJeromin** [comment]
Yes. I was opening help in this session.
Glad you found the trigger

**Comment by simonpoole** [comment]
If you simply exit help before leaving the property editor then, at least for me, things work as expected.

**Comment by simonpoole** [comment]
BTW what Android version are you running? The issue may be dependent on that.

**Comment by HolgerJeromin** [comment]
Android 14
