### ISSUE TITLE
App crashes infinitely and more

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2561]
Description:
---

App self-created invalid nodes, when trying to go to the node's place via changes review the app crashes, repeatedly every time. Now no further uploads are possible as the invalid nodes yield an error. Also, trying to send an error report tells invalid access token. Wiping app data didn't help and resultet in blank map. Only deinstallation and new setup helped.

Device info:
---
<table>
<tr><td>App version</td><td>20.0.0.0</td></tr>
<tr><td>App version code</td><td>2801</td></tr>
<tr><td>Android build version</td><td>eng.abuild.20230125.213400</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RSV1.210329.057</td></tr>
<tr><td>Device brand</td><td>Sony</td></tr>
<tr><td>Device manufacturer</td><td>Sony</td></tr>
<tr><td>Device name</td><td>pdx213</td></tr>
<tr><td>Device model</td><td>Xperia 10 III (AOSP)</td></tr>
<tr><td>Device product name</td><td>aosp_xqbt52</td></tr>
<tr><td>Device hardware name</td><td>pdx213</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Makeena"/>Makeena</A></td></tr>
</table>

**Comment by simonpoole** [comment]
What is an 'invalid node' in this context and did you submit a crash dump? 

Note that if it crashed after you wiped the data via the system that is an indication that the app image itself was corrupted,  there's nothing we can do about that. Or did you use safe mode to internally wipe data, see https://vespucci.io/help/en/19.3.0%20Release%20notes/#safe-mode-improvements ?

**Comment by simonpoole** [comment]
Crash dumps found.

The secondary issue (continuing to crash) seems to be that whatever caused the initial issue left a zero length way that restarting reselected in the action mode. We can protect against that unluckily that doesn't help with determining where this started.
