### ISSUE TITLE
OAuth1.0 and 1.0a are disabled, Login Forbidden

### ISSUE THREAD

**Issue by strk** [MarcusWolschon/osmeditor4android#2576]
I cannot upload changes made via Vespucci due to authentication mechanism changed upstream:

![photo_2024-06-10_15-21-35](https://github.com/MarcusWolschon/osmeditor4android/assets/289678/1935b635-fce3-4283-bc1d-bd49d8d4a2f6)

**Comment by strk** [comment]
Figured: it works when logging into openstreetmap via username/password.
The reason why it failed was because I logged via OpenID-2.0 instead and that somehow failed to perform the proper authorization.

**Comment by simonpoole** [comment]
This has been covered in multiple places (see https://vespucci.io/help/en/20.0.0%20Release%20notes/ and https://en.osm.town/deck/@vespucci_editor/111740472340290731 for example) and the app offered you to migrate your settings when you first installed version 20.

To manually migrate see https://en.osm.town/deck/@vespucci_editor/112528993868806218
