### ISSUE TITLE
Oauth auf Tablets mit Android 6.0.1 ?

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2580]
Description:
---

Hallo Entwickler,

es kommt eine leere Anmelde-Seite in Vespucci, wenn man bei einem alten Gerät mit Android 6 (see below) die Anmeldedaten für den Upload eingeben möchte. Oauth Autorifizierung nicht möglich per Tools Menü.

Wird ein so altes Android nicht mehr unterstützt?
Laut Google Play Store ist Android 5 als Minimum zum Installieren angegeben.

Gruß
Jakob48 (at OSM)

Btw. Auf einem anderen Gerät mit Android 14 alles i. O.

Device info:
---
<table>
<tr><td>App version</td><td>20.0.3.0</td></tr>
<tr><td>App version code</td><td>2804</td></tr>
<tr><td>Android build version</td><td>T800XXU1CVG1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29K.T800XXU1CVG1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>chagallwifi</td></tr>
<tr><td>Device model</td><td>SM-T800</td></tr>
<tr><td>Device product name</td><td>chagallwifixx</td></tr>
<tr><td>Device hardware name</td><td>universal5420</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by simonpoole** [comment]
Das ist bereits behoben in https://github.com/MarcusWolschon/osmeditor4android/issues/2578 und wird im nächsten Wartungsrelease verteilt, sprich in ca. ~2 Wochen.

Das Problem liegt daran das Android Versionen vor 7.1.1 aktuelle Letsencrypt Zertifikate nicht unterstützen. 20.0.3 hat das für die OSM API behoben, aber für die Authorisierung musste ich noch ein Workaround für Webviews finden.
