### ISSUE TITLE
Highlighting of deleted relation members

### ISSUE THREAD

**Issue by Velomeloman** [MarcusWolschon/osmeditor4android#2582]
## Vespucci Version
20.0.3

## Download source
 google play store

## Device (Manufacturer and Model)
Huawei P60 Pro

## Android Version 
12

## Behaviour/Symptoms

In the process of deleting relation members, when the map is shifted, the deleted relation members begin to be displayed again. They are eventually removed when the operation is completed, but this highlight gets in the way during the process.
https://github.com/MarcusWolschon/osmeditor4android/assets/109347561/e96093bb-35e9-4562-a84f-f0a824f8193e

## Expected Behaviour

Highlighting of deleted relation members does not appear

## How to recreate
Screencast above

## Crash dump submitted (no or yes + date)
no

**Comment by mic140** [comment]
It seems that in version 20.1.0.2 the problem is still not solved

**Comment by simonpoole** [comment]
Ah this was a misunderstanding on what was reported issue was, which was a distinct different issue as what was fixed in https://github.com/MarcusWolschon/osmeditor4android/pull/2584 . The new PR should fix the issue.
