### ISSUE TITLE
Better docs for offline downloads

### ISSUE THREAD

**Issue by felagund** [MarcusWolschon/osmeditor4android#2591]
Hello,
I wrote a howto about using the offline download functionality: https://community.openstreetmap.org/t/tutorial-how-to-use-vespucci-with-offline-data/115194

If you like it, I think it would be good, after some feedback if there is going to be any, to include it here (or instead of it and have that as a link from the howto?)  https://github.com/MarcusWolschon/osmeditor4android/blob/master/documentation/docs/tutorials/offline.md

**Comment by simonpoole** [comment]
Thanks.

I can add it to the tutorial docs if that is OK with you, at least the version on the forum seems to have a blank first image, or something else is weird.

**Comment by felagund** [comment]
Yeah, sure that would be great to add it to tutorials - I imagine the current tutorial can be replaced by it and your original post on OSM daily (I think) can be linked from it.

I see this as the first image: 
![Screenshot_20240627-093243_Vivaldi](https://github.com/MarcusWolschon/osmeditor4android/assets/1218098/07e1e029-63b4-444e-98b3-c4c8288a8122)
Which is correct. You do not see anything? I turned off the map background for the tutorial.

**Comment by simonpoole** [comment]
For me it looks like 

![grafik](https://github.com/MarcusWolschon/osmeditor4android/assets/1011860/96e55ee8-1aa7-472b-a161-a7f421c1b0ba)

In any case I would assume that that is just an artifact of the way the forum handles things. If you can provide me a markdown file including author and licence information I'll include it on the vespucci.io site.

**Comment by felagund** [comment]
Hello,
attaching a .md file with images here. I hope it renders well, it includes a code block in a list and I am not sure how standard that is.
[guide_vespucci_offilne.zip](https://github.com/user-attachments/files/16119543/guide_vespucci_offilne.zip)

As for Author, Tomáš Hnyk/tomashnyk@gmail.com will do. As for licence, anything that the current documentation is licences like, so either GPL or some CC? I am not sure what the proper format is to include it in the MD file.

I wrote is so that it can be a direct replacement of https://github.com/MarcusWolschon/osmeditor4android/blob/master/documentation/docs/tutorials/offline.md

- it even links the OSM diary pages that the original guide is based on.
