### ISSUE TITLE
Unable to upload data: OAuth 1.0 and 1.0a are disabled

### ISSUE THREAD

**Issue by afita** [MarcusWolschon/osmeditor4android#2602]
## Vespucci Version
20.0.4

## Download source
F-Droid

## Device (Manufacturer and Model)
OnePlus Nord CE 2

## Android Version 
OxygenOS 13.0 | Android 13

## Behaviour/Symptoms
When I try to upload data to OSM I get the following popup: "Login forbidden, OAuth 1.0 and 1.0a are disabled: https://wiki.openstreetmap.org/wiki/2024_authentication_update" and I can't upload.

## Expected Behaviour
Upload data to OpenStreetMap.

## How to recreate
Try to upload data to OSM.

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
See 

http://vespucci.io/help/en/20.0.0%20Release%20notes/

https://en.osm.town/@vespucci_editor/112528993868806218

https://blog.openstreetmap.org/2024/04/17/oauth-1-0a-and-http-basic-auth-shutdown-on-openstreetmap-org/

https://en.osm.town/@openstreetmap/112285994296917032

https://github.com/openstreetmap/operations/issues/867

**Comment by afita** [comment]
I made it work by following the instruction from https://en.osm.town/@vespucci_editor/112528993868806218 . Thanks!
