### ISSUE TITLE
Move dead releases as archives

### ISSUE THREAD

**Issue by Mahabarata** [MarcusWolschon/osmeditor4android#2603]
I was using the last version of 18.1 releases but impossible to upload my changes because of 
an "OAuth" error.

I was thinking it was a problem of version so I tried several versions of 19.x releases : same problem.

I didn't try versions 20.0 because of the warning about 'stored internal state format'.

I just read on github the issue #2602.

2 questions : is it true that all versions before the releases 20.x will no more work because of this big evolution ?
If yes, could you archive all these dead releases elsewhere than in the current release directory to prevent people to try these now useless releases ?

**Comment by simonpoole** [comment]
> 2 questions : is it true that all versions before the releases 20.x will no more work because of this big evolution ?

Yes, that was announced multiple times. There is no Problem with upgrading though, simply export your changes to a file (either OCS or JOSM format) and after the upgrade read them back in.

> If yes, could you archive all these dead releases elsewhere than in the current release directory to prevent people to try these now useless releases ?

They are only useless for the openstreetmap.org API, private and other API instances might still support at least Basic Auth. At some point I'm likely going to remove the oldest ones just as a clean up in any case.
