### ISSUE TITLE
Auth 1.0 issue required reinstall

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2604]
Description:
---

Hi, just wanted to let you know that I had to reinstall the app after getting an error about OSM not supporting OAuth 1 any more. I looked through all the menus and found no way to get Vespucci to work with 2.0, so eventually an uninstall and a reinstall was the only option. 

Device info:
---
<table>
<tr><td>App version</td><td>20.0.3.0</td></tr>
<tr><td>App version code</td><td>2804</td></tr>
<tr><td>Android build version</td><td>G998BXXU9FWK5</td></tr>
<tr><td>Android release version</td><td>14</td></tr>
<tr><td>Android SDK version</td><td>34</td></tr>
<tr><td>Android build ID</td><td>UP1A.231005.007.G998BXXU9FWK5</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>p3s</td></tr>
<tr><td>Device model</td><td>SM-G998B</td></tr>
<tr><td>Device product name</td><td>p3sxxx</td></tr>
<tr><td>Device hardware name</td><td>exynos2100</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Ilya Kogan"/>Ilya Kogan</A></td></tr>
</table>

**Comment by simonpoole** [comment]
See 

http://vespucci.io/help/en/20.0.0%20Release%20notes/

https://en.osm.town/@vespucci_editor/112528993868806218

Definitely no reinstall required.
