### ISSUE TITLE
"Could not carry out OAuth handshake"

### ISSUE THREAD

**Issue by chrissawyerfan4** [MarcusWolschon/osmeditor4android#2607]
## Vespucci Version
20.0.4.0

## Download source
F-Droid

## Device (Manufacturer and Model)
Irrelevant

## Android Version 
Irrelevant

## Behaviour/Symptoms
!["Could not carry out OAuth handshake: Communication with the service provider failed: ..."](https://github.com/MarcusWolschon/osmeditor4android/assets/126926647/7402e354-ab7e-47e0-bf91-4aa00598a595)

The application subsequently hangs. Need to close via app switcher and re-launch it to get back into the functionality.

## Expected Behaviour
A login form

## How to recreate
Press:

1. Menu (three dots on the bottom right)
2. Tools...
3. Authorise OAuth

## Crash dump submitted (no or yes + date)
Not a crash, but logcat says  
`D OAuth1aHelper: getRequestToken oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: Service provider responded in error: 403 ()`

## Any other potentially relevant information
Tapping the error message does nothing, the actual problem remains hidden behind the final "..." of the error message until you get logcat working and start digging through them.

**Comment by chrissawyerfan4** [comment]
I found [this other thread with instructions](https://github.com/MarcusWolschon/osmeditor4android/issues/2576#issuecomment-2158399867) but when trying to follow the instructions, it says it will discard all the changes that I was trying to upload if I proceed to "Configure" the openstreetmap data layer, so I cancelled that.

After backing the changes up to a file, intending to reapply them (or just upload via josm at this point), and after changing the oauth method to v2 on the data layer, it turns out that it does not throw away the changes at all. This "confirm to delete your edits" pop-up is bogus, at least with this type of change. The wording could be changed to reflect that changing authentication method will not discard one's edits...

That thread also claims a pop-up appeared to do an automatic migration, but no such pop-up appeared. Perhaps because I went from 19.x to 20.0.4? This may need to be fixed as well -- or perhaps Vespucci could just use oauth2 when you press on the oauth authorisation menu option, since that's afaik the only one currently in use?

**Comment by simonpoole** [comment]
> I found [this other thread with instructions](https://github.com/MarcusWolschon/osmeditor4android/issues/2576#issuecomment-2158399867) but when trying to follow the instructions, it says it will discard all the changes that I was trying to upload if I proceed to "Configure" the openstreetmap data layer, so I cancelled that.
> 
> After backing the changes up to a file, intending to reapply them (or just upload via josm at this point), and after changing the oauth method to v2 on the data layer, it turns out that it does not throw away the changes at all. This "confirm to delete your edits" pop-up is bogus, at least with this type of change. The wording could be changed to reflect that changing authentication method will not discard one's edits...

At that point, the app cannot know what you are going to change, and many things -will- cause edits to be lost, so better safe than sorry. Note that upgrading from version 19 to 20 will have lost changes anyway as the saved state file format changed.


> 
> That thread also claims a pop-up appeared to do an automatic migration, but no such pop-up appeared. Perhaps because I went from 19.x to 20.0.4? This may need to be fixed as well -- or perhaps Vespucci could just use oauth2 when you press on the oauth authorisation menu option, since that's afaik the only one currently in use?

The migration functionality is integrated in to the normal version modal that is (always) shown when there's a minor or major version change:

![Screenshot_1720255336](https://github.com/MarcusWolschon/osmeditor4android/assets/1011860/c50b9247-7b7f-4cc8-b21a-f89782a54fc7)

Really the only case in which you don't get shown the migration text is if you are using a non-standard API instance. Version 20 was released 4 months ago when all three supported authorisations methods were still available on openstreetmap.org, not to mention that we have to cater for private API instances that might be not be using OAuth 2.

**Comment by chrissawyerfan4** [comment]
I do not remember seeing that pop-up, but perhaps it was months ago as you say. I often check that apps still work after updating, so I may have briefly opened Vespucci and then homebuttoned out of it when I saw this (not having my password handy). There is no reason for me to press skip since I knew this migration had to happen, unless the "you can just do it later" text made me think it would be easy to do after pressing skip (that "you can always do it later manually" refers to such an obscure option, it is basically wrong for standard users who never have to touch the API URL configuration: they can actually not do it manually themselves, they need help with it).

Can it be that this pop-up appears only on first run after updating, rather than until the user makes a choice? Since any run may crash or be navigated out of (not skipped) for many reasons, such behavior would seem suboptimal.

I can see the reasoning behind some of the identified issues being acceptable enough, namely:

- that confirmation dialog being worded defensively to the point of being incorrect (it says it'll discard my edits immediately upon pressing confirm, rather than that many of the settings can cause discarding) for the sake of being unmistakable, and
- not wanting to automatically migrate oauth, even if it would be a simple string compare to see if the user is trying to use the standard API instance with the wrong oauth version, since it's extra code for a temporary issue.

However, I'm a bit surprised by this being closed spontaneously as though there is nothing further to consider. I would see the following as still worth resolving:

- The application breaks when the server gives an unexpected response and needs to be killed via the app switcher when using the authorise oauth option from the menu. (The original bug described in the initial filing.)
- The alluded-to manual upgrade path is so unfindable that one (who is about as tech-savvy as it gets, just not familiar with Vespucci internals) is lead to think it's simply the oauth mechanism that is broken, leading to the creation of this bug in the first place.
  - A fix could be to show a hint "To configure the oauth version..." when an http error status occurs in the oauth flow.
  - It might also help inform users they'll not get a second chance at finding this easily by changing the message from "you can always do it later" to "this will not be offered again; please bookmark <link to docs> if you cannot do this now".
- Errors in the oauth flow are not fully shown and cannot be tapped, so users will have no idea what is actually the issue unless they are familiar enough with Android app development to extract logcat messages. Not only in this specific case but any time something goes wrong in the oauth flow.

**Comment by simonpoole** [comment]
For anybody looking for instructions http://vespucci.io/tutorials/faq/#oauth-10a-to-oauth-2-migration
