### ISSUE TITLE
Http 500 fehler

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2612]
Description:
---

Unbekannter Fehler - Einträge können nicht mehr hochgeladen werden

Device info:
---
<table>
<tr><td>App version</td><td>20.0.5.0</td></tr>
<tr><td>App version code</td><td>2806</td></tr>
<tr><td>Android build version</td><td>V12.5.2.0.RCXEUXM</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RKQ1.201004.002 test-keys</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>willow</td></tr>
<tr><td>Device model</td><td>Redmi Note 8T</td></tr>
<tr><td>Device product name</td><td>willow_eea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by HolgerJeromin** [comment]
Related to  #2611 ?

**Comment by simonpoole** [comment]
Yes. But as they used anonymous issue creation and didn't add any contact details there is no way to tell them.
