### ISSUE TITLE
MTB:scale 0- missing from the path details

### ISSUE THREAD

**Issue by TommiContursi** [MarcusWolschon/osmeditor4android#2615]
Hello!

I have observed that it is currently not possible to add MTB:scale of 0-. I assume the use of negative zero is relatively new, but it is widely used here in Finland with the Trailmap app. In this context, the zero indicates easy forest mtb trails, and the negative zero distinguishes these from forest jogging paths, roads, and other very easy trails.

https://wiki.trailmap.fi/fi/kartoitus/tagit

**Comment by simonpoole** [comment]
Hi, can you open the issue in preset repo? https://github.com/simonpoole/beautified-JOSM-preset Thanks.

**Comment by TommiContursi** [comment]
> Hi, can you open the issue in preset repo? https://github.com/simonpoole/beautified-JOSM-preset Thanks.

Sure, Vespucci's play store change log linked to this repo so that's why I added it here.
