### ISSUE TITLE
Small cosmetic problem with new direction input method

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#2626]
Both the new direction input option with compass and the arrow display are great (see #2559)!

I noticed a small cosmetic problem in the property editor: If an item contains a `direction` key with a combo that contains e.g. `display_values="Forward,Backward, ..."` then the display_values ​​are no longer taken into account for the display in the property editor - e.g. "forward" and "backward" are now displayed in lowercase (which is somewhat irritating) – I mean after the value was assigned. (As long as the input option with compass is displayed, the display_values are shown correctly.)

I had this case on a node with a `traffic_sign=*` tag and a custom preset of mine (direction can be forward/backward for nodes on ways – probably the most common case – or a cardinal direction for nodes beside ways).

**Comment by jajajaneeneenee** [comment]
Should I maybe post some screenshots?

**Comment by simonpoole** [comment]
This would seem to work fine with for example https://github.com/simonpoole/beautified-JOSM-preset/blob/master/master_preset.xml#L3687 

Display values not being shown typically indicates that the preset item is not matching/not being considered an object.

**Comment by jajajaneeneenee** [comment]
Your link to the beautified presets now goes to `item name="Rest Area"`. I assume it should go to `item name="Traffic Signal"` (the line number has probably changed).

And I guess the example you mean should be:

`<combo key="traffic_signals:direction" text="For traffic direction" values="forward,backward,both" display_values="Forward,Backward,Both"/>`

But this is not an accurate example of what I mean (with this case there is no problem, but the new direction selector does not appear here either). What I meant (and also described above) concerns the item "Traffic sign" and its `direction` key, which is defined via `chunk id="traffic_signals_direction"` as follows:

```
<combo key="direction" text="For traffic direction" values="forward,backward,N,E,S,W,0,90,180,270"
       display_values="Forward,Backward,North,East,South,West,0°,90°,180°,270°" values_sort="false" />
```

I think 2 screenshots would be helpful ... pictures say more than 1000 words:

Input with the new selector – everything fine:
![Screenshot_traffic_sign_direction_input_1](https://github.com/user-attachments/assets/732cf6f5-2348-4842-82e8-cab4ac1ef1cc)

After choosing "Forward" and tapping "Save":
![Screenshot_traffic_sign_direction_input_2](https://github.com/user-attachments/assets/8b35f0c7-209d-4281-af63-d172c6c50862)

The value "forward" is displayed in lowercase. Previously (without the new selector) it was displayed here as "Forward" – with the initial letter written in capital letters (= display_value). As is always the case with other combos – and there is now a break in this consistency. That's what I'm talking about...

The case "Traffic sign" is – as I have already wrote above – probably a special case, because direction can be forward/backward for nodes on ways – probably the most common case! – OR a or a direction as a cardinal value or angle value for nodes beside ways (and the combo is correctly defined for both cases).

**Comment by simonpoole** [comment]
> The value "forward" is displayed in lowercase. Previously (without the new selector) it was displayed here as "Forward" – with the initial letter written in capital letters (= display_value). As is always the case with other combos – and there is now a break in this consistency. That's what I'm talking about...

With the new functionality the  field is now treated primarily as a text field without fixed values, contrary to previously as a combo field with fixed values with non-standard values as an exception. Changing this would likely need a refactoring of how text fields work which certainly can be done but will need to wait for a future version.

**Comment by jajajaneeneenee** [comment]
> With the new functionality the field is now treated primarily as a text field without fixed values, contrary to previously as a combo field with fixed values with non-standard values as an exception.

OK, this explains some things … Perhaps you should mention this in the documentation on http://vespucci.io/tutorials/presets/ (and other details to the new selectors, especially when they are displayed, when not, for which keys, whether you can suppress the display, etc.).

Of course, I would like it if the value was displayed with a capital letter at the beginning like with other combos ... then it would be consistent and understandable.

For your information – I had other strange effects, which may be partly explained by the treatment as a text field (but not completely):

1. If you add `match="none"` to a direction combo, the element is displayed without the selector, but like an editable combo (last tested in v20.1.0 Beta3) – even if it does not have an `editable="true"` attribute. An unexpected effect...
2. I had a special item for `traffic_sign=*` with `deprecated="true"` (for a test) and it had the direction key with some cardinal values ​​like N, E, S, W, NE, etc. The selector was then displayed there with all the display_values ​​I defined, but but additionally with all possible other direction values ​​that I had not defined in the combo (e.g. "clockwise", "left", "right" - these are defined as values in my custom presets in other items - for `highway=mini_roundabout` and `man_made=guard_stone` – correct values ​​according to Wiki). So it looked like a collection of ALL direction values ​​defined somewhere. And the sorting was also very strange (not alphabetical, etc.) When I removed `deprecated="true"` (which was not necessary and was just a test), the correct values ​​were displayed again. And the sorting was OK too.
4. The items for `highway=milestone` and `waterway=milestone` also have an (optional) direction combo with the values "forward,backward,both" – also in your Beautified JOSM Presets (I think it's for nodes ON a way). Here the direction selector is displayed, too - I think it should not be displayed. 

So there are still some side effects, which are strange if they occur (even if these are probably not "normal" cases). And it is not really clear to outsiders when the selector is displayed and when it is not - is this hard coded? A special attribute in the combo would make it very easy to understand – also to suppress it if you don't want it (for example). Or good documentation... I am also thinking of possible new cases in the future where a direction key could be used (with or without fixed values).
