### ISSUE TITLE
Vespucci hangs on application start

### ISSUE THREAD

**Issue by wschidol** [MarcusWolschon/osmeditor4android#2628]
## Vespucci Version
4th BETA of 20.1

## Download source
google play store, two days ago

## Device (Manufacturer and Model)
Google Pixel 7a

## Android Version 
14

## Behaviour/Symptoms
Starting Vespucci, it hangs on the green splash screen. Putting it into the background and bringing it up again is "sluggish". App does not show in list of active apps. Using the "back" button to back out of the hanging splash screen does not work.

## Expected Behaviour
App starts up as per usual.

## How to recreate
Start the app.

## Crash dump submitted (no or yes + date)
Not available.

## Any other potentially relevant information
Nothing that comes to mind.

**Comment by HolgerJeromin** [comment]
Same here with Motorola moto g73 5G on Android 14

**Comment by simonpoole** [comment]
What did you have installed before this version?

**Comment by wschildbach** [comment]
> What did you have installed before this version?

I can't say for sure, but since I update apps fairly religiously, chances are it would be the immediately preceding version.

**Comment by simonpoole** [comment]
Could you start in safe mode and delete the state file? See http://vespucci.io/help/en/19.3.0%20Release%20notes/#safe-mode-improvements 

This is weird because a) I use this version all the time on an Android 14 device, and b) it is naturally tested against an Android 14 emulator which should be very close to your device. If removing the state doesn't help, you might try reverting to the previous beta version (which will however require an uninstall, so should really be avoided).

**Comment by wschildbach** [comment]
Starting in safe mode initially was different in that it hung on a black screen... which I can't reproduce; it is now back to being hung on the green splash screen. Should I deinstall/reinstall?

**Comment by simonpoole** [comment]
Did you get the safe mode modal which allows to select which action should be taken? And for clarification did you get the notice that it was processing the imagery configuration and then the presets? The only change that should effect startup between Beta 3 and 4 is targeting Android 14

If you want to try the previous version it is here https://github.com/MarcusWolschon/osmeditor4android/releases/tag/20.1.0.3 after deinstall you might want to rename the /Download/Vespucci directory as the re-installed version will not be able to write to it.

Note: I'm on vacation in roughly an hour as a result I wont be able to respond as fast as normal for ~10 days.

**Comment by wschildbach** [comment]
Long press brought up the menu where I could choose between safe mode, help, Tag only an "address".
Clicking on safe brought up no further dialog, it just hung. There were no processing notices (although... the very first time I tried this I saw something flashing but it was too brief to be recognized. Starting in safe mode now gives me no notices).

**Comment by wschildbach** [comment]
Uninstalling and reinstalling the same version through the play store still did not work, so I'll now try with the previous beta.

**Comment by wschildbach** [comment]
Confirming the previous version does start.

**Comment by simonpoole** [comment]
> There were no processing notices (although... the very first time I tried this I saw something flashing but it was too brief to be recognized.

Sigh, essentially everything that runs before the progress modals is literally from google.

**Comment by HolgerJeromin** [comment]
I sent you some logs via email right now which I captured yesterday.
Hope they contain usefull stuff.
I filtered them in Matlog and exported them. But because I am on vacation, too, I could not checked the content.

**Comment by simonpoole** [comment]
Thanks @HolgerJeromin 

This is indeed an issue with targeting Android 14, just don't ask me why it doesn't happen on all devices:

```
07-23 22:43:21.333 E/AndroidRuntime(24498): Process: de.blau.android, PID: 24498
07-23 22:43:21.333 E/AndroidRuntime(24498): java.lang.RuntimeException: Unable to create application de.blau.android.App: java.lang.SecurityException: de.blau.android: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
07-23 22:43:21.333 E/AndroidRuntime(24498): Caused by: java.lang.SecurityException: de.blau.android: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
07-23 22:43:21.333 E/AndroidRuntime(24498): 	at de.blau.android.App.onCreate(SourceFile:66)
07-23 22:43:21.333 E/ACRA    (24498): ACRA caught a RuntimeException for de.blau.android
07-23 22:43:21.333 E/ACRA    (24498): java.lang.RuntimeException: Unable to create application de.blau.android.App: java.lang.SecurityException: de.blau.android: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
07-23 22:43:21.333 E/ACRA    (24498): Caused by: java.lang.SecurityException: de.blau.android: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
07-23 22:43:21.333 E/ACRA    (24498): 	at de.blau.android.App.onCreate(SourceFile:66)
07-23 22:43:21.424
```

**Comment by HolgerJeromin** [comment]
I started the app first time after (silent) upgrade via geo: link.
That is the only "unusual" thing I remember.

**Comment by rami-l** [comment]
Same. Oneplus 11 5g, android 14

**Comment by HolgerJeromin** [comment]
This was fixed my Simon, but he did not managed to publish a new version before his vacation...

**Comment by simonpoole** [comment]
> This was fixed my Simon, but he did not managed to publish a new version before his vacation...

Note that there is a follow on issue caused by the fix that will cause a crash if you try to start recording a GPX track however editing works.

**Comment by simonpoole** [comment]
I've built a further beta release thar should fix the issue. I hope Marcus has time to publish it today, as a simple install over the misbehaving version should fix things.

**Comment by simonpoole** [comment]
The beta release is currently awaiting review by google (yet another time because of GPX recording).

**Comment by simonpoole** [comment]
And rejected. 

Getting this resolved is going to take a lot of time because it needs finding out what googles bots actually don't like which is far from obvious. However the signed APK is now available from the repo https://github.com/MarcusWolschon/osmeditor4android/releases/tag/20.1.0.5 and you should be able to install that over any existing installs.

**Comment by rami-l** [comment]
Works. Thanks 

> And rejected.
> 
> Getting this resolved is going to take a lot of time because it needs finding out what googles bots actually don't like which is far from obvious. However the signed APK is now available from the repo https://github.com/MarcusWolschon/osmeditor4android/releases/tag/20.1.0.5 and you should be able to install that over any existing installs.

**Comment by HolgerJeromin** [comment]
Thanks for the workaround!

**Comment by simonpoole** [comment]
Seems as if we may have convinced google to release beta 5 now.
