### ISSUE TITLE
Reinitialize the validator engine every time something (relevant) with the presets was changed

### ISSUE THREAD

**Issue by jajajaneeneenee** [MarcusWolschon/osmeditor4android#2632]
## Vespucci Version
20.1.0 Beta4 (but this problem has existed for a long time, I know it since 2020).

## Problem
It would be necessary for the validator to be reinitialized every time something in the presets (relevant for a validator check key) was changed. 

If there are changes in the presets (e.g. if you have made validator check keys optional in preset items which weren't optional before – and the „Require optional“ checkbox is off), the validator engine will not immediately/automatically recognize this after using "Update preset". You must for example first change something in the validator check keys to trigger a re-initialization of the validator. Restarting Vespucci doesn't help either.

Of course, changes to the presets also include activating/deactivating other presets, adding/removing presets etc.

My current workaround to trigger a re-initialization of the validator looks like this:

* I created a validator check entry key "xxx" and then add (or remove) an "x", save it and exit the settings.
* Alternatively, you can also activate a checkbox "Require optional" (even if you don't want this), exit the settings (and then change it back again).

But that is very cumbersome and easy to forget.

**Comment by jajajaneeneenee** [comment]
I checked it today the first time and I got a strange effect.

* I changed the name key in a certain (custom) preset to optional and reloaded (updated) the changed preset (and left the preferences).
* A node matching the preset (which had the validator styling outline) still had validator styling outline. I expected it to go away immediately.
* When I selected the node, the green popup appeared at the top of the screen, where you normally see which key is missing – but there was only the description of the node (= item name + its ID) without a key that is missing. This looks like an "empty" or a false message.
* I was only able to get rid of the validator styling outline (and the message) by first giving the object a name (validator styling is gone) and then deleting the name again. OR by selecting the node and moving it!
* Neither my old workaround (see above) nor a restart of Vespucci nor a change of data styling (to another one and back again) worked. So now it's even more difficult to get rid of a false (outdated) validator styling then before (for example, if a large number of objects are affected).

Have you checked/tested your change (#2637) at all or can you reproduce what is described here?

Maybe something else needs to be reset with the loaded objects / the data styling? Or simply some kind of refresh of the displayed objects?

**Comment by simonpoole** [comment]
The result of validating an object is cached in the object itself and only reset when the object is changed or an actual validation is changed (for example the connected node tolerance). The later should probably be changed to reset when any validation aspect is changed.
