### ISSUE TITLE
Opening history on web doesn't work when Vespucci's allowed to open `openstreetmap.org` links

### ISSUE THREAD

**Issue by FireFragment** [MarcusWolschon/osmeditor4android#2634]
## Vespucci Version
20.0.6

## Download source
Google Play store

## Device (Manufacturer and Model)
Google Pixel 6

## Android Version 
Android 14

## Behaviour/Symptoms
When Vespucci is allowed to open `openstreetmap.org` links, it's not able to show history on the openstreetmap.org webpage through the `History (Web)` button. If clicked, it just plays a glitched animation and nothing else happens. Vespucci doesn't even show its own history dialog in this case.

## Expected Behaviour
Vespucci open history on the web, regardless of whether it's allowed to open `openstreetmap.org` links.

## How to recreate

1. Open the  `Settings` app
2. Go to `Apps` -> `See all apps` -> `Vespucci` -> `Open by default`
3. Choose `Add link`
4. Windows opens with 5 links. Check all of them, except the `127.0.0.1` one (it's not needed for this reproduction)
5. Click `Add`
![Screenshot_20240727-142746](https://github.com/user-attachments/assets/35aa5e90-acc5-4a5f-82fb-08134fa124c0)
6. Open Vespucci
7. Select a node. If there are no nodes to select, do `Download current view`.
8. Click the three dots in the bottom right
9. Click `History (Web)`
10. See that nothing happens, just a glitched animation

## Any other potentially relevant information

This is probably caused by the fact, that Vespucci tries to open all openstreetmap.org links, even if it can't handle them - in this case history of an element.

**Comment by simonpoole** [comment]
> This is probably caused by the fact, that Vespucci tries to open all openstreetmap.org links, even if it can't handle them - in this case history of an element.

It isn't, but currently the path patterns don't exclude URLs that end with an appended "/history" not quite clear if that is possible with the the wildcard expressions google supports.
