### ISSUE TITLE
Add description of error highlighting to docs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#264]
```
Document what gets highlighted in magenta.
```

Original issue reported on code.google.com by `sp8...@gmail.com` on 15 Dec 2014 at 10:06

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/afacc7f0210f6a6f3b2690fc572c88f34c65007e
