### ISSUE TITLE
Error in translation of key=value into Spanish

### ISSUE THREAD

**Issue by afgb1977** [MarcusWolschon/osmeditor4android#2642]
I wanted to report a small translation error that I find constantly.
Vespucci is translating natural=heath as "salud" (health in English) in both the popup menu and the properties panel.
The correct translation would be "brezal"

![IMG_20240802_014544_974](https://github.com/user-attachments/assets/dd78f588-60b4-4914-b6c1-cbc9d067a2f4)
![IMG_20240802_014540_185](https://github.com/user-attachments/assets/6d236d9e-9815-4fb0-ad8a-802ad1d557f6)

It's just a small suggestion, do not translate the TAG's into other languages, it can generate bias if the key=value are poorly translated, Spanish is a language very rich in words and synonyms, additionally there is the fact that there are many Spanish-speaking countries, each with their own linguistic regionalisms. A word can have different meanings depending on the country in which it is used.
To keep in mind = the technical language in OSM is English, we are used to reading the key=value in English, when we write in our groups and forums in Spanish we do not translate the key=value.
The description of the key=value in Spanish It is quite useful and is what we rely on to obtain information about the element, more accurate information if the key=value is kept in English.
This problem also happens in OSM ID with the number of erroneous translations or selection of wrong words, in some countries they are understood and in others they are not.

**Comment by simonpoole** [comment]
Hi, this is the wrong repo for the issue (and I can't move it to the correct one), but if it is a simple translation error you can correct it on transifex yourself, see https://github.com/simonpoole/beautified-JOSM-preset?tab=readme-ov-file#translations 

If it is a question of the same English term having to be translated in two or more different ways depending on context, we have to add a translation context to the term in the preset itself (the translation will still need fixing naturally after we've done that) and you open an issue in the preset repo  https://github.com/simonpoole/beautified-JOSM-preset

**Comment by afgb1977** [comment]
> Hi, this is the wrong repo for the issue (and I can't move it to the correct one), but if it is a simple translation error you can correct it on transifex yourself, see https://github.com/simonpoole/beautified-JOSM-preset?tab=readme-ov-file#translations
> 
Thanks, I'll try to do them.

> If it is a question of the same English term having to be translated in two or more different ways depending on context
>
No, please no.
