### ISSUE TITLE
Auth err

### ISSUE THREAD

**Issue by octavo** [MarcusWolschon/osmeditor4android#2646]
The user cannot log in and does not receive password reset from osm.

![img_24.jpg](https://github.com/user-attachments/assets/fb9a0a88-61b5-462b-8983-d39ef3213037)

**Comment by simonpoole** [comment]
You need to at least include the version of Vespucci in use for a proper answer, but likely this is happening in a pre-version 20 app that doesn't support OAuth2.

**Comment by octavo** [comment]
20.0.6.0

**Comment by simonpoole** [comment]
The user didn't automatically migrate to OAuth2 when it was offered and chose to migrate manually, instructions on how to do that are here: http://vespucci.io/tutorials/faq/#oauth-10a-to-oauth-2-migration

For more information see 

https://blog.openstreetmap.org/2024/04/17/oauth-1-0a-and-http-basic-auth-shutdown-on-openstreetmap-org/

https://en.osm.town/@vespucci_editor/112528993868806218
