### ISSUE TITLE
Undo accidental tag change

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2658]
Description:
---

How do I undo an accidental change to a node? I went on to make real changes to other nodes and ways, but I don't want to upload my changes with an extra accidental change. I can't seem to undo that change, or not upload every change at once.

Device info:
---
<table>
<tr><td>App version</td><td>20.1.0.0</td></tr>
<tr><td>App version code</td><td>2905</td></tr>
<tr><td>Android build version</td><td>ef5f02bb61</td></tr>
<tr><td>Android release version</td><td>13</td></tr>
<tr><td>Android SDK version</td><td>33</td></tr>
<tr><td>Android build ID</td><td>lineage_taimen-userdebug 13 TQ3A.230901.001 ef5f02bb61</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>taimen</td></tr>
<tr><td>Device model</td><td>Pixel 2 XL</td></tr>
<tr><td>Device product name</td><td>lineage_taimen</td></tr>
<tr><td>Device hardware name</td><td>taimen</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/CLundy"/>CLundy</A></td></tr>
</table>

**Comment by simonpoole** [comment]
There's a couple of ways to avoid uploading an unwanted change, the 

- undo the specific change (long press on the undo button, find the actual edit undo it)

- selective upload, select all changed, new, deleted elements and then deselect what you don't what you upload, upload the selected elements. See https://vespucci.io/help/en/Multiselect/#upload-elements

If you have too many changes to manually select you can use the 'Object search' to select them: https://vespucci.io/help/en/Main%20map%20display/#search-for-objects

**Comment by simonpoole** [comment]
No response from issue creator, closing.
