### ISSUE TITLE
Image viewer does not respect image rotation

### ISSUE THREAD

**Issue by leekleak** [MarcusWolschon/osmeditor4android#2667]
## Vespucci Version
20.1.0

## Download source
f-droid

## Device
Samsung S24 Ultra

## Android Version 
14

## Behaviour/Symptoms
When images are opened (eg from the image overlay) they are opened with the assumption that they are horizontal even if they were shot vertically.

## Expected Behaviour
Image rotation matches that of their metadata

## How to recreate
Take a vertical image and open it

**Comment by simonpoole** [comment]
I suspect this might be an issue with images retrieved from the media store that might be pre-rotated. We explicitly use the EXIF data to determine this and at least with photos loaded directly this works without issue, see https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/java/de/blau/android/photos/PhotoViewerFragment.java#L168

**Comment by leekleak** [comment]
How does this this image open for you?

 ![20240707_150216.jpg](https://github.com/user-attachments/assets/78cf34fd-f462-4d49-9464-553551a84481)

**Comment by leekleak** [comment]
Ouch, I thought I had mentioned it, but apparently I forgot...

The photo is rotated incorretly no matter if it was taken from the app itself or from the camera app.

**Comment by simonpoole** [comment]
The image you uploaded doesn't actually contain any EXIF information (likely due to Android privacy), you could try moving it to a google drive folder.

**Comment by leekleak** [comment]
That's weird... If I give the image link to some online exif info extractor it is able to extract the data, but I guess you can try [this](https://quickshare.samsungcloud.com/jQ4yr995zXpX)

**Comment by simonpoole** [comment]
> but I guess you can try [this](https://quickshare.samsungcloud.com/jQ4yr995zXpX)

Yes that is better.

**Comment by simonpoole** [comment]
After some further investigation seems as if the SubsamplingScaleImageView.ORIENTATION_USE_EXIF to the SubsamplingScaleImageView doesn't work for Android > 10 at least for images that can only be accessed via the ContentResolver.

**Comment by simonpoole** [comment]
@leekleak it currently isn't clear if I'll backport this PR to the current release, or if this will only be included in 20.2.

**Comment by leekleak** [comment]
That's fine, the issue isn't **that** critical ;)
