### ISSUE TITLE
no map display 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2675]
Description:
---

When entering Vespucci, I get an all green display background without any detail. Zooming in/out does no change this.

Device info:
---
<table>
<tr><td>App version</td><td>20.1.2.0</td></tr>
<tr><td>App version code</td><td>2907</td></tr>
<tr><td>Android build version</td><td>12043167</td></tr>
<tr><td>Android release version</td><td>14</td></tr>
<tr><td>Android SDK version</td><td>34</td></tr>
<tr><td>Android build ID</td><td>AP2A.240805.005.F1</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>bluejay</td></tr>
<tr><td>Device model</td><td>Pixel 6a</td></tr>
<tr><td>Device product name</td><td>bluejay</td></tr>
<tr><td>Device hardware name</td><td>bluejay</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/tkoeller"/>tkoeller</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Is this a new install? 

In any case opening the layer modal/dialog (hamburger button in the top right corner) will display the current layer configuration, a screenshot would be helpful.

Other things to check https://vespucci.io/tutorials/faq/#ive-downloaded-data-but-the-screen-remains-blank

**Comment by simonpoole** [comment]
No response, closing.
