### ISSUE TITLE
Add possibility to make a choice by encircling on a map, which "commits" are included when "pushing" local changes into OSM data

### ISSUE THREAD

**Issue by Peter0** [MarcusWolschon/osmeditor4android#2684]
Description:
If one uses Vespucci to do some edits en passant here and there, it occasionally happens that there are locally made edits that are otherwise unrelated, possibly spreaded over an extensive area.
I'd like to have the occasion to somehow choose or edit the set of published edits when doing an upload to OSM. For example by encircling them in a map style overview, in order to limit upload to a given surrounding.

**Comment by Peter0** [comment]
The poor man's solution was to undo last edit, push changes and then redo. But this approach is spoiled by emptying undo buffer in the moment of push.

**Comment by simonpoole** [comment]
You can selectively upload edits. See 

https://vespucci.io/help/en/15.0.0%20Release%20notes/#upload-selection-and-update-data-functions

To select the elements to upload you can, besides simply selecting them, use a search expression, which is not super convenient but works. 

See also https://github.com/MarcusWolschon/osmeditor4android/issues/2573 for an idea for a UI to make it somewhat easier.

**Comment by Peter0** [comment]
Maybe it would habe been better if I'd used to talk about choosing edits that are "staged" for a "commit". But regardless the words I used, I hope that the intention is clear.

**Comment by simonpoole** [comment]
@Peter0 Question answered?

**Comment by Peter0** [comment]
Yes, albeit haven't had the occasion to try it.

I'll leave this issue open due to the alternative approach to design an UI compared to the tick approach in #2573.
