### ISSUE TITLE
Value selector flips to opposite value with Android 5

### ISSUE THREAD

**Issue by goldfndr** [MarcusWolschon/osmeditor4android#2689]
Recently, as of Vespucci 20.1.3, tapping the layer selector for an object (e.g. gantry, bridge outline via multipolygon) causes the value to instantly "flip" to an opposite (e.g. 0 ⇒ -256, 1 ⇒ -255, -256 ⇒ 1, -255 ⇒ 2).

## Vespucci Version
20.1.3

## Download source
google play store

## Device (Manufacturer and Model)
Amazon Fire 10 HD Gen 7 (not reproducible on LG V50 ThinQ with Android 10 or Samsung Z Fold3 with Android 14)

## Android Version 
Fire OS 5.7.1.0 (CPU Info by KG Soft says version 5.1.1 SDK 22)

## Behaviour/Symptoms
Within a newly displayed Layer modal dialog, after the on-screen keyboard appears, tapping the spinner instantly "flips" the value: If the value was cleared/unset, the spinner instantly changes value from 0 to -256 if tapped in the middle/top, often 254 or -253 with animation if tapped where "1" is visible. Saving an "opposite" value and editing again "flips" again, so it's somewhat mitigated.

## Expected Behaviour
Tapping on the spinner in the middle should keep the existing value centered, like on other Android versions.

## How to recreate
1. Add a new way of 2 nodes.
2. Tag it with preset Gantry.
3. Tap the Layer's value field.
4. In the Layer dialog, tap the spinner control. Observe.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
Possibly a side effect of #2643's fix.

**Comment by simonpoole** [comment]
Thanks for the report.

This effects Android 5 to 8 and is at least undocumented behaviour, if not simply a bug, workaround currently unclear.
