### ISSUE TITLE
Zoom level not maintained returning from camera app

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#269]
```
In some situations in 0.9.6 when starting an camera app via the icon will zoom 
out when the camera app is closed
```

Original issue reported on code.google.com by `sp8...@gmail.com` on 12 Feb 2015 at 4:29

**Comment by simonpoole** [comment]
This seems to be specific to using OpenCamera, removing from milestone for now.

**Comment by simonpoole** [comment]
Tested with a recent (patched) version of OpenCamera and problem seems to have gone away.
