### ISSUE TITLE
Reversing a oneway highway shows surprising dialog

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#2691]
## Vespucci Version
20.1.3

## Download source
Play store

## Device (Manufacturer and Model)
Motorola Moto G73 5G

## Android Version 
14

## Behaviour/Symptoms
Find a highway with a `oneway=yes` tag.
Select "Reverse way".
Find nice "I changed some tags of the elements" dialog.
Revisit tags.

## Expected Behaviour
I expected the way has now `oneway=-1` tag.

Reading [doc](https://vespucci.io/help/en/Way%20selected/#reverse-way) shows me:

> oneway tags are not automatically reversed here the assumption is that the intent was to change the effect of the tag,

This was surprising.

> the tag editor will be started automatically and you can change the tag manually if necessary. 

The editor did not started. 
And perhaps the editor should not show the dialog if no other "Direction dependent tags" are found.

**Comment by simonpoole** [comment]
Reversing the way will reverse the way, keeping the oneway in way direction and then show the warning . If you want the oneway to be opposite of the way direction you need to edit it. It has literally always been this way as the most likely use of the reverse way function on a oneway is to change the direction of the oneway.

The documentation is a bit out of date on the warnings displayed (it used to directly start the property editor that is really the only behaviour change).

**Comment by HolgerJeromin** [comment]
Yes, I think keeping the oneway tag is fine and in most cased wanted. 
But the dialog explains that the app had adjusted some tag (which it did not when there are no such tags).

**Comment by HolgerJeromin** [comment]
Thanks!
