### ISSUE TITLE
Show ruler on the map

### ISSUE THREAD

**Issue by miklcct** [MarcusWolschon/osmeditor4android#2692]
I can't find a way in the app to show a ruler on the map to know the scale. I need it to properly map underground areas when outdoor GPS references are not available.

**Comment by simonpoole** [comment]
There is no freely orientable ruler, but there is naturally the configurable scale/grid https://vespucci.io/help/en/Introduction/#layer-settings

**Comment by simonpoole** [comment]
ping @miklcct

**Comment by simonpoole** [comment]
I really just wanted to if the scale/grid is what you were looking for, or if you want something else.
