### ISSUE TITLE
The template for Railway platform lacks entry for Light Rail

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2697]
Description:
---

The template for Railway platform
railway=platform
lacks entry for Light Rail
light_rail=yes
https://wiki.openstreetmap.org/wiki/Key:light_rail
in the selection list for
Transportation type

Thus this must be entered manually. 

This is rather cumbersome. 
How can I add this to the list? I suppose there is some kind of list responsible for such mappings in the source code.

Device info:
---
<table>
<tr><td>App version</td><td>20.1.3.0</td></tr>
<tr><td>App version code</td><td>2908</td></tr>
<tr><td>Android build version</td><td>N975FXXS9HWHA</td></tr>
<tr><td>Android release version</td><td>12</td></tr>
<tr><td>Android SDK version</td><td>31</td></tr>
<tr><td>Android build ID</td><td>SP1A.210812.016.N975FXXS9HWHA</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>d2s</td></tr>
<tr><td>Device model</td><td>SM-N975F</td></tr>
<tr><td>Device product name</td><td>d2seea</td></tr>
<tr><td>Device hardware name</td><td>exynos9825</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/frodeseverin"/>frodeseverin</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Thanks for the report, it is easier for us to track thing is preset issues are reported in the preset repo: https://github.com/simonpoole/beautified-JOSM-preset
