### ISSUE TITLE
cannot do oauth2 flow to private OSM instance

### ISSUE THREAD

**Issue by spongebyte** [MarcusWolschon/osmeditor4android#2699]
Hi. I am running my own OSM instance (using the docker-compose method from https://github.com/openstreetmap/openstreetmap-website). I cannot connect to my instance with oauth2 using Vespucci.

I have read https://vespucci.io/help/en/Advanced%20preferences/ and https://vespucci.io/tutorials/faq/. I have set up my instance in Advanced preferences > Server settings, and I have selected it. I can read data just fine, but when I try to upload, Vespucci tries to open the auth webpage and it just fails with a blank page. I cannot find a place to add the app's secrets (client_id, client_secret) as suggested by the FAQ.

I can connect to the instance with JOSM using oauth2 (with a small trick: JOSM tried to open https://my.instance.com/api/authorize, whereas the correct auth page is https://my.instance.com/oauth2/authorize ; also JOSM complains in the logs that there is no https://my.instance.com/.well-known/oauth-authorization-server endpoint).

Perhaps Vespucci expects to find directions at https://my.instance.com/.well-known/oauth-authorization-server, and/or expects the auth page to be https://my.instance.com/api/authorize?

Is there a way to make this work? I have tried manually editing the sql3 db `/data/data/de.blau.android/databases/AdvancedPrefs` and putting a token manually generated (mimicking the oauth2 flow manually) but that isn't working.

Please let me know if you need anymore data.

Many thanks for the great app.

## Vespucci Version
20.1.3

## Download source
f-droid

## Device (Manufacturer and Model)
Google Pixel 6a

## Android Version 
Android 14 / LOS 21

## Behaviour/Symptoms
Cannot do oauth2 flow with private OSM instance

## Expected Behaviour
Working oauth2 flow with private OSM instance

## How to recreate
OSM instance created with docker-compose from https://github.com/openstreetmap/openstreetmap-website
Configure OSM server in Vespucci to point to my instance.

## Crash dump submitted (no or yes + date)
No. This is the latest meaningful info from `logcat | grep de.blau`.
```
10-15 12:07:11.637  2614  2646 V WindowManagerShell: Transition requested (#1537): android.os.BinderProxy@95a9f29 TransitionRequestInfo { type = OPEN, triggerTask = TaskInfo{userId=0 taskId=25964 displayId=0 isRunning=true baseIntent=Intent { flg=0x10000000 cmp=de.blau.android/.Main } baseActivity=ComponentInfo{de.blau.android/de.blau.android.Main} topActivity=ComponentInfo{de.blau.android/de.blau.android.prefs.APIEditorActivity} origActivity=null realActivity=ComponentInfo{de.blau.android/de.blau.android.Main} numActivities=4 lastActiveTime=177306817 supportsMultiWindow=true resizeMode=2 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@aca72ae} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 132 - 0, 0) topActivityInfo=ActivityInfo{7b8084f de.blau.android.prefs.APIEditorActivity} launchCookies=[] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false locusId=null displayAreaFeatureId=1 isTopActivityTransparent=false appCompatTaskInfo=AppCompatTaskInfo { topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=1080 topActivityLetterboxHeight=2400 isUserFullscreenOverrideEnabled=false isSystemFullscreenOverrideEnabled=false cameraCompatControlState=hidden}}, pipTask = null, remoteTransition = null, displayChange = null, flags = 0, debugId = 1537 }
10-15 12:07:11.638  1826  2697 D CoreBackPreview: Window{7a62a82 u0 de.blau.android/de.blau.android.prefs.AdvancedPrefEditor}: Setting back callback null
```
No other log entry related to keywords API, oauth, or my instance's URL was present.

**Comment by simonpoole** [comment]
You will need to create your own set of client keys and load them with the correct base url configured.

See 

https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/assets/keys2-default.txt

and 
https://vespucci.io/help/en/Main%20map%20display/#tools "Load keys..."

**Comment by simonpoole** [comment]
@spongebyte did you get it working?

**Comment by spongebyte** [comment]
Hey, many thanks for following up.
So far I haven't managed to make it work.

Say my instance is `https://my.instance.com/`
In `Preferences > Advanced preferences > Server settings > Manage APIs`, I have created an entry:
    - API name: `my_instance`
    - API URL: `https://my.instance.com/api.0.6/`
    - Authentication: `OAuth 2`
With this I have read-only access to my instance.

I prepared a text key file containing this:
`my_instance api_oauth2_key <token> false empty https://my.instance.com/`
The token is a freshly generated Bearer access_token valid for scopes `read_gpx write_gpx read_prefs write_prefs write_api write_notes` and redirect uri `urn:ietf:wg:oauth:2.0:oob`. I followed the directions at https://wiki.openstreetmap.org/wiki/OAuth `Basics of the protocol`.

After importing that key file in Vespucci (`tool icon > Load keys from file...`), when I try to upload or authorize, I still get a blank screen with a toast: `No OAuth configuration found for API "my_instance"`.
I have tried variations of the URL in the key file (https://my.instance.com/, https://my.instance.com/api/, https://my.instance.com/api/0.6/, https://my.instance.com/oauth2/), to no avail.

I see no useful info related to an attempt to connect to my instance using logcat.

Thank you.

**Comment by simonpoole** [comment]
Are you sure you are using tabs as separators in the key file? The error message doesn't imply anything mysterious, just that it didn't find an appropriate entry in the key file, and it at that stage is just looking for the api name and the correct key type.

**Comment by spongebyte** [comment]
Thank you! I got it to work:

Indeed the key file needs to use *tabs*, not spaces, as delimiter. My bad.
The redirect uri for the Vespucci OAuth2 application in the OSM container needs to be set to `vespucci:/oauth2/`.
The `key` in the key text file is the OAuth2 `client_id`.

🙏
