### ISSUE TITLE
No preselection for traffic_sign?

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#2703]
Description:
---

I'm frequently mapping the traffic sign by using the tag traffic_sign.
However, Vespucci doesn't offer this tag within preselection menu. 
Means, I'm starting to write traff but all I get offered is traffic_calming and traffic_sign:forward. What about single "traffic_sign", without forward?

Device info:
---
<table>
<tr><td>App version</td><td>20.1.4.0</td></tr>
<tr><td>App version code</td><td>2909</td></tr>
<tr><td>Android build version</td><td>12234140</td></tr>
<tr><td>Android release version</td><td>14</td></tr>
<tr><td>Android SDK version</td><td>34</td></tr>
<tr><td>Android build ID</td><td>AP2A.240905.003.A1</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>akita</td></tr>
<tr><td>Device model</td><td>Pixel 8a</td></tr>
<tr><td>Device product name</td><td>akita</td></tr>
<tr><td>Device hardware name</td><td>akita</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a]</td></tr>
<tr><td>ABIs (32bit)</td><td>[]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td><A href="https://openstreetmap.org/user/Geo-Tobi"/>Geo-Tobi</A></td></tr>
</table>

**Comment by simonpoole** [comment]
Can you check that you are actually using a current version of the presets? A traffic_sign preset has been available for a long time.

See http://simonpoole.github.io/beautified-JOSM-preset/#Waypoints

PS: this really belongs in the preset repo and not here.

**Comment by simonpoole** [comment]
User was expecting to be able to use the traffic_sign preset item on ways and areas which is something we currently do not support in the default presets. User should use one of the traffic sign presets from JOSM if they need this for now.
