### ISSUE TITLE
Play voice records from OSMTracker GPX files

### ISSUE THREAD

**Issue by Binnette** [MarcusWolschon/osmeditor4android#2708]
[OSMTracker](https://github.com/labexp/osmtracker-android) allow users to record a GPX and record their voice to take a "vocal note".

The resulting waypoint in GPX looks like this:
````XML
<wpt lat="45.17022211" lon="5.74005175">
	<ele>269.78875732421875</ele>
	<time>2024-10-29T08:10:08Z</time>
	<name><![CDATA[Enregistrement vocal]]></name>
	<link href="2024-10-29_09-10-07.3gpp">
		<text>2024-10-29_09-10-07.3gpp</text>
	</link>
	<sat>24</sat>
</wpt>
````

OSMTracker (now) export the GPX + the voice records in "document" folder + track folder. So it looks like this :

- 📂 2024-10-29_09-08-43
  - 🗺 2024-10-29_09-08-43.gpx
  - 🔴 2024-10-29_09-10-07.3gpp
  - others files (images, etc)

Actually Vespucci nicely show the "voice record":
![image](https://github.com/user-attachments/assets/d10f8124-91b2-47f5-a8a7-8ec4998234c9)

When I unlock editing and click on this point, it show this popup:
![image](https://github.com/user-attachments/assets/4a9e3871-f6b4-4eb7-bcf3-8c05546da04b)

The only thing missing in this popup is an extra button to play the sound recorded in the audio file.

Note : file format will probably change to m4a or mp3 'since mp3 is in public domain).

TY and have a nice day 👍

**Comment by simonpoole** [comment]
Seems as if the _link_ element is even part of the "standard": https://www.topografix.com/GPX/1/1/gpx.xsd
