### ISSUE TITLE
How/why does this app make noises when my volume is off and ringer is silent

### ISSUE THREAD

**Issue by mattfbacon** [MarcusWolschon/osmeditor4android#2737]
## Vespucci Version

20.1.4.0

## Download source

Fdroid

## Device (Manufacturer and Model)

Google Pixel 5a

## Android Version 

Android 14, calyxos 5.6.3 unofficial

## Behaviour/Symptoms

App makes noises on interaction even though I have disabled that, volume is off, haptic is disabled, and ringer is on silent.

## Expected Behaviour

No noises

## How to recreate

Unlock the map and long press on a way

## Crash dump submitted (no or yes + date)

No

**Comment by simonpoole** [comment]
I assume you haven't actually set the warning beep volume to zero, not quite clear from your description of the issue. 

Set it to zero here https://vespucci.io/help/en/Advanced%20preferences/#beep-volume

**Comment by mattfbacon** [comment]
No I mean like how is it possible for the app to play sounds when my volume is off

**Comment by mattfbacon** [comment]
"Tap and click sounds" is disabled in my system settings. I think that should disable this beeping without extra in-app settings.

**Comment by mattfbacon** [comment]
Ok, if you consider that intended behaviour then I accept that.
