### ISSUE TITLE
Changes with opening hours date picker sometimes aren't saved

### ISSUE THREAD

**Issue by Discostu36** [MarcusWolschon/osmeditor4android#2752]
## Vespucci Version

20.2.1

## Download source

Google Play

## Device (Manufacturer and Model)

Mororola Edge 50 Neo

## Android Version 

14

## Behaviour/Symptoms

In some cases changes made with the opening hours date picker are not saved.

## Expected Behaviour

Changes should be saved 

## How to recreate

1. Edit [this node](https://www.openstreetmap.org/node/6169398731)
2. Select the opening hours
3. Edit the date using the date picker, e.g. to Jan 6th 2025 to Feb 20th 2025
4. Close the date picker
5. Save the opening hours 

## Crash dump submitted (no or yes + date)

No

## Any other potentially relevant information

[Screen Recording](https://cloud.familie-brandtner.de/s/i9kbFmRDZMFF3Mo)

**Comment by simonpoole** [comment]
That seems to be a regression that https://github.com/simonpoole/OpeningHoursFragment/pull/63 didn't fix.
