### ISSUE TITLE
preserve node id when merging

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#283]
Right now if i merge two nodes the resulting node gets the osm id of the node which is not selected (or the other way round? I always forget). 
It would be nice, if a node with an osm id would survive and a new node (negative id) would be deleted.

Same would be nice with joining ways, i am not sure if this is already implemented.

**Comment by simonpoole** [comment]
In general I've tried to preserved existing OSM ids on stuff that I've
redone, but it is true that merging nodes currently doesn't check if one
of them is a new one.

Simon

Am 12.05.2015 um 09:28 schrieb Holger Jeromin:

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/858ef17b1a7cecbf427b60d2fae3ebe9125c8bfa

**Comment by HolgerJeromin** [comment]
Thank your for your quick fix!

**Comment by HolgerJeromin** [comment]
I am surprised that this fix is not included in the new play store release https://github.com/MarcusWolschon/osmeditor4android/releases/tag/0.9.5.1.965
or it does not work :)

**Comment by simonpoole** [comment]
In general the release branch doesn't get behavioural changes except
with real issues (simply because it would require too much testing) the
change -is- included in the test build here:
https://drive.google.com/folderview?id=0B9pKLmh8s1h8bFI5bGd4VnhYWkk&usp=sharing

Simon

Am 17.05.2015 um 21:48 schrieb Holger Jeromin:

**Comment by HolgerJeromin** [comment]
sorry, i did not know that there were different branches active at the same time. 
No Problem, i can wait. Thanks for your quick answer. :)

**Comment by MarcusWolschon** [comment]
We should explain how the brances are used.

**Comment by simonpoole** [comment]
As I mentioned elsewhere I would suggest revisiting the issue post 0.9.6  Long lived public branches would seem to be at odds with git and githubs development model and would seem to end up confusing potential contributors that want to provide PRs.
