### ISSUE TITLE
No icons in 960

### ISSUE THREAD

**Issue by jiri-novacek** [MarcusWolschon/osmeditor4android#284]
After recent update (960) I cannot see any icons in Vespucci editor on my android phone (Xperia Z1 Compact). No icons on nodes (enabled in settings) and no icons while browsing presets either. Tryed uninstalling, clearing data, still no icons.
Is there something I could do to see the icons? Is it known problem?

**Comment by johnjohndoe** [comment]
Confirmed. I also noticed this. I could somehow make the icons appear when I click on another object and then press the *BACK* button.

**Comment by simonpoole** [comment]
Wrong preset file got included. Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/7d06a9526469d3744c4f63e52ce14dfeba60848a

**Comment by simonpoole** [comment]
Note on the side: as always if you can't wait for an updated version in the google play store https://drive.google.com/open?id=0B9pKLmh8s1h8OXUtQzRaNkM2TjQ&authuser=0 has the latest build (it is not signed with the proper key so you will need to uninstall/re-install)

**Comment by MarcusWolschon** [comment]
Released
https://github.com/MarcusWolschon/osmeditor4android/releases/tag/0.9.5.1.965

**Comment by jiri-novacek** [comment]
Problem solved, thanks everybody for (insanely) fast confirmation & fix & release
