### ISSUE TITLE
Get  dependencies from mavenCentral/jCenter

### ISSUE THREAD

**Issue by krt16s** [MarcusWolschon/osmeditor4android#285]
Instead if using jar files, you could add

````
compile "ch.acra:acra:4.5.0"
compile "com.adobe.xmp:xmpcore:5.1.2"
compile "oauth.signpost:signpost-core:1.2.1.2"
compile "oauth.signpost:signpost-commonshttp4:1.2.1.2"
````

into build.gradle's depdency section. Note that metadata-extractor is available from central as well ( as `compile "com.drewnoakes:metadata-extractor:2.8.1"`), but I didn't manage to find a matching nor working version.

**Comment by johnjohndoe** [comment]
@krt16s I decided to keep referencing the *.jar* files in the *libs* folder when I updated the project setup to enable Gradle builds for the reason that it would be harder to **maintain the version of the libraries in two locations**. When @MarcusWolschon decides to fully switch to Gradle build it will make sense to use Gradle dependencies over *.jar* files.

**Comment by MarcusWolschon** [comment]
I'm leaving the decision with Simon.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/commit/b1e5c9372abf5d3e581511371b36fc30e1e46892 not quite complete yet as I haven't looked at the Exif stuff yet.

**Comment by simonpoole** [comment]
No more libraries included in the repo https://github.com/MarcusWolschon/osmeditor4android/commit/2400802b38f8a5a866b20dd708164c403a9784f7

**Comment by johnjohndoe** [comment]
:smiley_cat: Well done!
