### ISSUE TITLE
Mismatching versions in AndroidManifest.xml and build.gradle

### ISSUE THREAD

**Issue by krt16s** [MarcusWolschon/osmeditor4android#286]
Both files specify version and versionCode, but differ. Either keep them in sync or just remove the declarations from one of the files.

**Comment by simonpoole** [comment]
Given that Eclipse supports gradle (builtin) from version Mars on it may be possible to simplify the whole build setup moving forward.

**Comment by johnjohndoe** [comment]
@krt16s This issue can be closed. Okay?

**Comment by krt16s** [comment]
Actually I think it is not necessary to set versionCode and versionName at all when they are present in the manifest, but the issue is solved, yes :).

**Comment by johnjohndoe** [comment]
If the migration to Gradle (IDE agnostic) is coming any time soon this workaround will become obsolete. Therefore, I think we are fine with it.
