### ISSUE TITLE
change key/value seperator in popup from : to =

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#287]
If you click on an element there is a popup with the name or house number. 
On other features the main tags are shown. 
For example a toilets node gives
amenity:toilets
but I think this should be 
amenity=toilets

**Comment by simonpoole** [comment]
The relevant method or rather the output of it  is used at least in 7-8 places through out the code that need to be checkd: From a graphical pov ": " might be better. It is true that hierarchical values with ":" seperator might cause confusion.

**Comment by HolgerJeromin** [comment]
I am no expert of this code, but it seems it is only used on text outputs (toast and debug logs) and one [menu.add()](https://github.com/MarcusWolschon/osmeditor4android/blob/019d9d017a34f748756323994f46efd33aa93d3e/src/de/blau/android/Main.java#L1927).
The output can be anything from a arbitrary name to "house xy" to the key=value string. Thats why i did no real indepth research.

**Comment by simonpoole** [comment]
"only text outputs" OSM is full of ugly stuff so I want to check legibitly and aesthetic impact befor changing things :-)

**Comment by HolgerJeromin** [comment]
For me it is important for the sake of consistency. 
Wiki, Taginfo and probably every documentation is using = all over the place. I never saw the : used.

**Comment by MarcusWolschon** [comment]
"it seems" is not enough. Need to be sure for the reasone Simon stated.

**Comment by simonpoole** [comment]
I've incoprated the suggested change in https://github.com/MarcusWolschon/osmeditor4android/commit/a27f59e7bc2d97d44cb4d9d71f4c86ea70bf4835 however it should be rarely to never be used now since the commit changes the behaviour to display the (translated) name of the best matched preset for unnamed features and the actual tag value is only used as a fallback.
