### ISSUE TITLE
Feature request: Add support for Google Location service(s).

### ISSUE THREAD

**Issue by gena01** [MarcusWolschon/osmeditor4android#289]
So right now on my smartphone when I turn off GPS "Show location" feature gets disabled and doesn't work until I turn the GPS back on. Would it be possible to use approximate location and somehow use the approximate location as the area i want to edit?

**Comment by MarcusWolschon** [comment]
No, we are absolutely not allowed to do that.
Google fixes you to the streets and wifi access points it knows and incorporating these locations
means incorporating Google map data.
Sorry.
This has been discussed in OSM before and a clear legal decision to not go there was made.

**Comment by simonpoole** [comment]
As Marcus writes: using google for this is likely out of the question, however, as mentioned in https://github.com/MarcusWolschon/osmeditor4android/issues/273 we might add support for MLS for rough positioning. This naturally depends on how MLS actually develops.
