### ISSUE TITLE
We need more inline-documentation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#3]
```
All classes and at least the most important methods need to be commented.
```

Original issue reported on code.google.com by `mattelac...@gmail.com` on 5 Mar 2009 at 1:53

**Comment by simonpoole** [comment]
An update nearly 9 years later: we currently have 4'564 methods of which (only) 1'285 don't have javadoc, in other words 70% of the methods have at least some documentation (there are still are fair number of javadoc errors though).

**Comment by simonpoole** [comment]
Down to 870 missing method javadoc (of which 115 are for tests).

**Comment by simonpoole** [comment]
10 years later: down to 438 of which 35 are for tests.

**Comment by simonpoole** [comment]
193 still missing

**Comment by simonpoole** [comment]
... and zero: https://github.com/MarcusWolschon/osmeditor4android/commit/3c3deac5a06324f41b400bc43cd3598656212a8b
