### ISSUE TITLE
File picker dialog

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#313]
We currently don't have a good builtin file picker for use where we want to read or save to an on device file. I did research this at the time, but at least then there were no suitable third party solutions that worked from a licence pov and at the same time over the whole range of Android versions we need to support.

If no suitable solution can be found, we should probably write one ourselves.

Things not to forget

- Themeing

**Comment by johnjohndoe** [comment]
The talk of @cketti [about the Storage Access Framework](http://droidcon.de/session/be-part-document-centric-android) might be helpful here.

**Comment by MarcusWolschon** [comment]
file picking on Android usually works by broadcasting an Intent and the user choosing what installed file manager/galery app/..  he/she wants to use to select the file or files of the types mentioned in the intent.

**Comment by simonpoole** [comment]
@MarcusWolschon thats what we currently do and the help files contain a pointer to the fact that there may have to be a third party app installed. 

However
* if there is no file manager/galery app/.etc. that supports the type file installed/available (typically true for early android versions and gallery apps) the user is screwed 
* I've yet to find a 3rd party solution that would support creating new files and overwriting, which is why that is done in a dialog in our code
* the aboves means you have two different UIs for reading and saving 

@johnjohndoe the storage access framework is neat and partially solves the issues .... for devices with >= 4.4 

I spent an inordinate amount of time on this when I first implemented JOSM compatible file writing/reading so I suspect I covered all the obvious avaenues available at that time, the question is if there is anything new available, or if somebody can muster enough engery to write something..

**Comment by johnjohndoe** [comment]
@simonpoole In the video recording you can listen to @cketti talking about options providing file pickers before 4.4.

**Comment by MarcusWolschon** [comment]
Should we plan this for 0.9.7 or leave it without a milestone as it's low priority anyway?

**Comment by simonpoole** [comment]
Pro memoria: when I was originally investigating this I had a look at https://github.com/iPaulPro/aFileChooser which would be compatible from a licence pov. Can't remeber right now what the reason was that I didn't use it at the time.

**Comment by simonpoole** [comment]
https://github.com/spacecowboy/NoNonsense-FilePicker is a good candidate for this and offers the required functionality (new file and new directory creation). It is currently released on terms of Mozilla Public License Version 2.0 which while not ideal, shouldn't create any significant issues, but to be on the safe side I'll likely leave the very simple file name selction code around.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/a1fb6e53d4e1d1db3e19a2a8a9b31270d18414db while it would be nice if it additionally supported SAF, this solution allows creating new directories and files which none of the other solutions does.
