### ISSUE TITLE
Make address tags used for address prediction/suggestion configurable

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#323]
In some areas adding addr:country and other tags is not necessary. Make the set of tags stored and used for address prediction configurable (likely with a MultiSelectListPreference).

Naturally this causes issues for pre API 11 devices

http://misha.beshkin.lv/android-multiselectlistpreference-for-sdk-11/

**Comment by MarcusWolschon** [comment]
Can you elaborate on that "not necessary" part?
Why should the schema be different in different parts of the same world?

**Comment by simonpoole** [comment]
This is actually a user request (but I would find it useful too), the addr:schema is not different but some parts are unnecessary. For example in Switzerland in general the addr:country and addr:city are most of the time not expicitly tagged (because they can be inferred from the boundaries). Current everything with a couple of exceptions with addr: is used which is very annoying if you keep on have to delete something just because somebody by mistake used more tags than normal,

**Comment by MarcusWolschon** [comment]
Not many programs have proper support for parsing polygon boundaries.
Could we determine if the currently downloaded area contains a polygon with addr:* attributes that the location is in and hide or pre-fill elements based on that?
I guess it would be quite unstable because the polygons are huge compared to the downloaded areas.

**Comment by HolgerJeromin** [comment]
I dont think there is a sane way Vespucci can detect if there is a proper boundary=administrative Multipolygon around the poi to hide addr:city. Country polygons should be ok, so imo no addr:country needed.

**Comment by simonpoole** [comment]
Essentially any automatic detection would require querying an online API, which while possible, probably doesn't make a lot of sense in the context of trying to avoid lots of features that depend on having connectivity.

In any case as it is now (see https://drive.google.com/folderview?id=0B9pKLmh8s1h8bFI5bGd4VnhYWkk&usp=sharing note only works for Android 3.0 and higher)), the only real difference to what was used before is that per default addr:country is not included, which given that we have country polygons for all countries in OSM should be a sane default

**Comment by simonpoole** [comment]
Done in https://github.com/MarcusWolschon/osmeditor4android/commit/0d4c87769ee61c4e42eb0772780104e3e25e321b Note for pre3.0 OS version the defaults are fixed.
