### ISSUE TITLE
WMS layer for background

### ISSUE THREAD

**Issue by yopaseopor** [MarcusWolschon/osmeditor4android#324]
With Vespucci I can make my editions a little bit easier with only one touch... but Bing imagery is not precisse as I need. Here in Spain we have PNOA and also other great regional services of imagery so...why not the option of a WMS layer to make the work with all these services possible?

**Comment by simonpoole** [comment]
Note: you can naturally simply proxy such services through MapProxy or a similar service if you need access "now" if the Spanish OSM community doesn't have the resources we could probably host them on SOSMs MapProxy instance as a stop gap measure.

**Comment by yopaseopor** [comment]
I think I have not explained me well. I want to have an option in settings' maps background with Spanish PNOA or others services working in WMS so why not an option in Settings map background with the possibility to insert WMS services?

**Comment by simonpoole** [comment]
WMS support would simply have to be programmed see https://portal.opengeospatial.org/files/?artifact_id=1081&version=1&format=pdf there maybe a suitable free implementation available, but that needs to researched etc. It is not just a question of adding an option.

**Comment by yopaseopor** [comment]
Ok , I don't know anything of programming. It was only an idea. I hope one day someone can implement it ;)

**Comment by simonpoole** [comment]
As said the short term solution is to proxy (make available as a tile service) the relevant WMS services.

**Comment by yopaseopor** [comment]
And how we can work with it in Vespucci?

**Comment by simonpoole** [comment]
Either add a custom tile server definition or add it directly to the https://github.com/osmlab/editor-imagery-index which is the basis for vespucci and iD tile server configuration.

**Comment by yopaseopor** [comment]
PNOA Spain is also there (at the index) , is any way to activate in Vespucci?

**Comment by simonpoole** [comment]
If it is the entry is for a tile server you don't have to "activate it" if it is an entry for the WMS server again you would need to configure a proxy somewhere and add the config data for that to the list.

**Comment by yopaseopor** [comment]
In Which option of Vespucci I can put PNOA to use it as I can use Bing?

**Comment by kcwu** [comment]
this is basically similar to this feature request https://github.com/MarcusWolschon/osmeditor4android/issues/250

**Comment by simonpoole** [comment]
@kcwu not at all. Supporting WMS servers require coding support for them which is a large amount of work and will impact the background rendering code substantially. Custom tile server configs have been possible since ages just not well documented.

**Comment by kcwu** [comment]
thanks for your information.

**Comment by simonpoole** [comment]
Support for WMS servers that provide EPSG:3857 or EPSG:900913 support was added in https://github.com/MarcusWolschon/osmeditor4android/commit/1ab5a4aa2261657e40878cc75cf18f6bf351ba47

**Comment by yopaseopor** [comment]
On Thu, Jan 18, 2018 at 11:30 PM, Simon Poole <notifications@github.com>
wrote:

> Support for WMS servers that provide EPSG:3857 or EPSG:900913 support was
> added in 1ab5a4a
> <https://github.com/MarcusWolschon/osmeditor4android/commit/1ab5a4aa2261657e40878cc75cf18f6bf351ba47>
>
Excuse me, How can I do that?

Thanks

**Comment by simonpoole** [comment]
You don't have to do anything at this point in time (since the version hasn't been released yet, not even as a beta), likely next week there will be a beta of sorts.

In any case this is most useful for sources that are in the editor layer index, they will be automatically be selectable (that around 70 additional sources).

**Comment by simonpoole** [comment]
See http://vespucci.io/tutorials/custom_imagery/ for some documentation ; i expect a 1st bublic beta of 10.1 sometime this week.
