### ISSUE TITLE
Vespucci tries to delete way with negative id

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#325]
I am not sure how to reproduce it, but I was cutting an outer member of a MP into three parts, closing the ways again. I wanted to delete a middle part of the polygon. 
Worked (could have done it with the split polygon feature) but Vespucci wanted to delete a way with id=-3. The API was not really happy :-)

**Comment by simonpoole** [comment]
In general it deletes newly created objects (which are those with a negative id)  only locally, the reported behaviour would indicate that the state of the element gets lost/is not set at some point. If you could remember anything about the sequence of operations that would be helpful.

**Comment by simonpoole** [comment]
Confirmed, removing a element from a relation update it status in a way that breaks the above convention.

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/bc58aee41982f25175e43f788029b7255b5901ae

**Comment by HolgerJeromin** [comment]
Thanks :-)
