### ISSUE TITLE
Documentation: screenshot link defunct

### ISSUE THREAD

**Issue by tilmanb** [MarcusWolschon/osmeditor4android#327]
The Link to the screenshots on code.google.com at https://github.com/MarcusWolschon/osmeditor4android/blob/gh-pages/index.html#L31 is pointing to nirvana.

**Comment by simonpoole** [comment]
Could you submit a pull request that points to the new location?

**Comment by tilmanb** [comment]
No, as I don't know the current/new location. Sorry.

**Comment by simonpoole** [comment]
It seems as if the screenshots didn't survive the move to github (they were rather dated in any case). 

The source of all the on device documentation is marked up in markdown https://github.com/MarcusWolschon/osmeditor4android/blob/master/markdown/en/  (with the intent of turning it in to a more flashy github hosted site when time permits) so there is  really no need to link to a extremely outdated external source. We just need to find a method of pre-processing the MD files so that we can remove any large images for the on-device version.

**Comment by simonpoole** [comment]
http://docs.vespucci.io/ is the first cut at replacing the current github pages, the documentation part of this is generated and deployed directly from the markdown files withhttp://www.mkdocs.org/. 

What is missing is way of generating the on device html files to, but it is already a big step forward.

**Comment by simonpoole** [comment]
Moved to http://vespucci.io/ now

**Comment by stephan75** [comment]
By the way: should we edit all external links from the former weblinks directing to
http://marcuswolschon.github.io/osmeditor4android/
now into
http://vespucci.io/ ?

especially in the OSM wiki at
http://wiki.openstreetmap.org/wiki/Vespucci
http://wiki.openstreetmap.org/wiki/DE:Vespucci
http://wiki.openstreetmap.org/wiki/RU:Vespucci ?

**Comment by simonpoole** [comment]
@stephan75 yes ... BUT I want to move everthing to the standard repo first, I'll give a heads up as soon as that is done (and I'm more than happy that I don't have to do it).

**Comment by simonpoole** [comment]
@stefan75 push to the standard repo just happened. .. fire away.

**Comment by stephan75** [comment]
Ok now! ...
But: do we have identical content now on http://marcuswolschon.github.io/osmeditor4android/ and http://vespucci.io/ ?

So no need for editing the OSM wiki pages?

Or is it technically a kind of "redirection" from vespucci.io to marcuswolschon.github.io ?

And do you want to have feedback about that freshly and nice styled website? We can mention that refresh at Wochennotitz / weeklyOSM if you want.

**Comment by simonpoole** [comment]
I would suggest changing everything to vespucci.io as the cannocial and provider independent domainname. A mention in weeklyosm would naturally be nice.
