### ISSUE TITLE
Provide means of closing multiple bugs at once

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#332]
In some areas you can find a large number of bugs tht have the same cause, being able to bulk close them would be nice.

**Comment by matkoniecz** [comment]
Is it really going to be that useful? Record for me was about 10 stacked reports from maps.me (foobar is no longer existing).

It seems to not be worth additional complexity of interface (Vespucci is already quite complex and confusing), add to that time to design, implement, test, maintain...

**Comment by simonpoole** [comment]
I was thinking less of Notes, but more of OSMOSE generated warnings here, but you are correct there doesn't really seem to be a way to do this in a non fiddly way. Closing for now.
