### ISSUE TITLE
Repo is unsearchable ATM

### ISSUE THREAD

**Issue by d1g** [MarcusWolschon/osmeditor4android#333]
https://github.com/search?utf8=%E2%9C%93&q=Vespucci
https://github.com/search?utf8=%E2%9C%93&q=vespucci+osm
https://github.com/search?utf8=%E2%9C%93&q=osm+editor

I suggest to use "Vespucci is an OpenStreetMap editor for Android"

**Comment by d1g** [comment]
You have to put it in *project_tagline* and not only in README file.

**Comment by simonpoole** [comment]
@d1g sorry @MarcusWolschon  needs to change that, the current tagline is from, as it says, the automatic export of the googlecode repo.

**Comment by MarcusWolschon** [comment]
Any idea where to change the tagline?
"Options" only allows to change the repository name.

**Comment by simonpoole** [comment]
http://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github claims that you can hover over it, but that doesn't work for me, Thats why I'm assuming that it is a permissions issue.

**Comment by johnjohndoe** [comment]
Just click the `Edit` text pointed out in the screenshot:

![edit1](https://cloud.githubusercontent.com/assets/144518/9573608/a5feac82-4fbe-11e5-8e01-2c2847b906b4.png)

Then input fields will show up:

![edit2](https://cloud.githubusercontent.com/assets/144518/9573610/a963957c-4fbe-11e5-8ee4-33ca7bd923b3.png)

**Comment by MarcusWolschon** [comment]
Done.
Thanks.
