### ISSUE TITLE
hide addresses too if "show node icons" is off

### ISSUE THREAD

**Issue by mnalis** [MarcusWolschon/osmeditor4android#344]
Even when option "show node icons" in Settings is unselected,  street addresses are shown in big red circles with numbers, which clutters a display (especially when zoomed out with locked screen).

I propose nodes with addresses should be hidden (like all other decorations) when "show node icons" is off

(Using vespucci  0.9.6.1.990 from f-droid)

**Comment by simonpoole** [comment]
Woudn't it be enough to simply apply the same logic to not show the numbers when zoomed out, as with the node icons?

**Comment by simonpoole** [comment]
Actually there is no such logic it seems outside of the general draw/don't draw data decsision.

Obviously their are various ways to solve this.

**Comment by mnalis** [comment]
yes, I did mean to suggest for nodes with addresses to be handled the same way as the other nodes, sorry if it sounded otherwise - my english is not so good. Whatever way you think is best!


(as for f-droid, perhaps one might collaborate with them to work toward something like Debian reproducable builds project? Because for end user, fetching/updating different apps from different places is nightmare. But that idea is for another issue maybe if you're interested)

**Comment by simonpoole** [comment]
Long resolved.
