### ISSUE TITLE
Check bing usage

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#345]
It seems as if bing is now enforcing usage limits, this is not directly an issue for vespucci as we use our own and different api key than iD, P2 and JOSM (which all use the same :-)), and it is unlikely that we will run in to the limit, however access to the bing account and the possibility to check usage would be good.

**Comment by MarcusWolschon** [comment]
How could we check and how could we react?

**Comment by simonpoole** [comment]
It seems as if the bing account associated with the key shows the usage limits (I've already asked Andrew if he still has access). 

If we actually run in to the limit the only realitic course of action would be to remove the bing option for now, for a large part of the world the mapbox imagery is the same (but better geo-referenced) so that is an alternative except for the parts which are not covered.

**Comment by andrewgoz** [comment]
Hi guys,

I've just checked the account and the T&Cs.

The Bing key is a Basic/Not for Profit, and on non-Windows platforms it allows up to 125,000 "billable transactions" in any 12-month period.

Usage for September was 9,862 and so far for October is 4,025. Estimating 10,000 per month, that's 120,000 - very close to the limit!

I don't know what happens when the limit is reached. I guess it just stops working?

**Comment by simonpoole** [comment]
The motivation for the question was that P2, iD and JOSM all use the same key and it seems that they hit a limit mid-week, according to Richard Fairhurst however the limit on that key is a 1'000'000 or so, he may have twisted bings arm a bit after the incident, in any case it seems to be working now. 

For vespucci the impact would likely be slightly larger if we hit the limit since haven't hardwired the URL (it seems as if the other editors do a volkswagen), but obviously we could change that :-). The other posibility it to nick Richards key :-).

**Comment by pnorman** [comment]
You could also ask Bing, letting them know this key is being used for OSM editing, like the other, and asking for the limit to be raised.

**Comment by simonpoole** [comment]
@andrewgoz could you re-cehck the bing account? could be that we hit the limit now (report from @datendelphin)

**Comment by adamthewebman** [comment]
I know the bing imagery does not work in the app right now

**Comment by simonpoole** [comment]
@adamthewebman where is supposed to be the case? There is not a general issue with bing that we currently know of (you may have to zoom out a bit anf back in if the max zoom is being misreported by bing).

**Comment by adamthewebman** [comment]
@simonpoole Bing imagery is now working for me in the app again, it started working about  a week ago.

**Comment by simonpoole** [comment]
Given that users can switch to  the imagery provided by DigitalGlobe if bing doesn't work this issue is moot.
