### ISSUE TITLE
Why targetSdkVersion 16?

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#347]
I noticed that [*AndroidManifest.xml*](https://github.com/MarcusWolschon/osmeditor4android/issues/new) and [*build.gradle*](https://github.com/MarcusWolschon/osmeditor4android/blob/4d6b561602fbe765c50b04668eeece077c856fa4/build.gradle#L29) both define `targetSdkVersion` set to `16` while the `compileSdkVersion` is set to `22`. Is there a particular reason why you are not increasing the target SDK version?

**Comment by simonpoole** [comment]
Why not? Seriously: I upped the target to 16 after it had been at 14 for a long time. Upping it simply makes more (new) SDK features available, but using those on the one hand increases the reliance on the compat libraries and given how far back we are supporting stuff right now typically the features will not be supported for at least a couple of early API versions. The later implies that we need to either disable such features of find workarounds.

I don't have anything -against- the above, but nobody has jumped up and said that they absolutely need something from a later API version  so there has been no reason to change.

**Comment by johnjohndoe** [comment]
Okay. Thank you. As soon as I discover a need I will point it out.
