### ISSUE TITLE
Missing Catalan translation for GPX visibility

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#351]
I noticed that the [values for the visibility spinner are missing for Catalan](https://github.com/MarcusWolschon/osmeditor4android/blob/master/res/values-ca/strings.xml#L260):

``` xml
<!-- res/values-ca/strings.xml#L260 --->
<string-array name="gpx_visibility"/>
```

---

Related: commit 5746fcd1a9c07662aee8dac62f5a82bd19451145

**Comment by johnjohndoe** [comment]
Here is the translation:

``` xml
<string-array name="gpx_visibility">
    <item>privat</item>
    <item>públic</item>
    <item>rastrejable</item>
    <item>identificable</item>
</string-array>
```

**Comment by simonpoole** [comment]
Note the translations are managed on transifex (see TRANSLATIONS.md) the versions in the repo are simply copies of what we pull from transifex (this makes the build process a bit easier for third parties and at the same time is our backup in the case something goes wrong), changes need to be made there or else they will be overwritten the next time we pull the translations (but I'll add the Catalan translation asap).

**Comment by johnjohndoe** [comment]
That's why I did not create a pull request. Feel free to put the translation into transifex.
