### ISSUE TITLE
Typo in English translation for GPX visibility

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#353]
The value `identifiable` should be `identificable`.
See: [*res/values/strings.xml*](https://github.com/MarcusWolschon/osmeditor4android/blob/4d6b561602fbe765c50b04668eeece077c856fa4/res/values/strings.xml#L474)

**Comment by simonpoole** [comment]
Definitely not see http://www.oxforddictionaries.com/definition/english/identifiable

**Comment by johnjohndoe** [comment]
:+1:

**Comment by simonpoole** [comment]
It would be really preferable if you would create a login on transifex (you can use your github login) and request to join the respective translation groups, fixing typos via creating here is really too heavyweight.
