### ISSUE TITLE
Typo in Spanish translation for GPX visibility

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#356]
The value `identicable` should be `identificable`.
See: [*res/values-es/strings.xml*](https://github.com/MarcusWolschon/osmeditor4android/blob/56d9dd0507d2c00494c4b6c16545ff23c7fbef11/res/values-es/strings.xml#L473)

* Reference: [dict.leo.org](http://dict.leo.org/esde/index_de.html#/search=identifizierbar&searchLoc=0&resultOrder=basic&multiwordShowSingle=on)

---

I mixed this up before in #353.

**Comment by simonpoole** [comment]
Fixed in transifex

**Comment by johnjohndoe** [comment]
Fix here: ebf27595e165c546f5b1289a29ad213c39225aaf
