### ISSUE TITLE
advance oauth configuration

### ISSUE THREAD

**Issue by RicoZ-OSM** [MarcusWolschon/osmeditor4android#357]
It would be nice to be able to do it in advance - before trying to upload anything. Is that possible? Did not find anything obvious.

This is because at the time of the first upload people may not have their password around.

**Comment by simonpoole** [comment]
Currently not implemented, needs some thinking. We don't want to add yet another button to a already fairly complex UI if not absolutely necessary (we don't want to recreate qgis/arcgis), potentially we could offer it as an option on first use.

**Comment by RicoZ-OSM** [comment]
Or as another point in the advanced settings.

**Comment by HolgerJeromin** [comment]
You have a user and password field in the settings. 
I was never able to use oauth, as I never found the settings. 
Please add both Auth methods or none in the advanced settings. 
When not finding such an option a user will try to upload something.

Is there a possibility to clear the username and password? I think I did not found it and iirc setting bogus data in the settings gave no possibility to change Auth method on upload.

**Comment by simonpoole** [comment]
@HolgerJeromin oauth is the default, you don't need to do/set -anything-.since 0.9 was released in August 2013. Manual intervention was only required if you installed 0.9x over one of the very very old pre-0.9 versions and was documented at the time: check the oAuth box in for the relevant API  in the Advanced Preferences (this is a per API setting for obvious reasons).

**Comment by HolgerJeromin** [comment]
My workflow for a new device is to go to the app settings and configure everything before use.
I remember that i had some trouble confusion with my new install.
But probably i am using oauth right now.

**Comment by RicoZ-OSM** [comment]
It appears it might also be useful to be able to view//delete auth tokens, perhaps even manage several identities. Imho that could be grouped in a submenu somewhere in the settings menu.

**Comment by simonpoole** [comment]
You can reset the token by turning OAuth off for the API entry in question, saving and turning it back on and to manage multiple tokens/identities you only need to add another API entry (each API entry stores tokens, and/or login/password tupels besides the URL). 

I'm not quite sure what the utility of adding fairly complicated UIs for stuff that is essentially never going to be used is. Note this doesn't really have anything to do with your original request which is quite reasonable

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/932c57c3433d2a19def5c5ca8dda5f0a2000a004 adds a reset and authorize OAuth entries to the tools menu.
