### ISSUE TITLE
Display notification when loading webpage(s)

### ISSUE THREAD

**Issue by RicoZ-OSM** [MarcusWolschon/osmeditor4android#358]
When uploading first time I got a glimpse of an error message and a bright white screen - looked like Vespucci died until I realised it was loading the OSM login page which took a very long time because of a slow network connection.

**Comment by simonpoole** [comment]
It does actually display a notice (toast) wrt what it is doing, but depending on timing that may not be noticed.

**Comment by simonpoole** [comment]
I'm not totally happy with the net result but https://github.com/MarcusWolschon/osmeditor4android/commit/d4283d7c55f9616460f90be340a431cacf749b8d addresses this.
