### ISSUE TITLE
missing way split point

### ISSUE THREAD

**Issue by datendelphin** [MarcusWolschon/osmeditor4android#371]
When trying to split following way: http://www.openstreetmap.org/way/67827208
The following node: http://www.openstreetmap.org/node/818905948 should be available as possible split point

**Comment by simonpoole** [comment]
Michael can you remember if it was in the closed way split mode or in the normal one?

**Comment by datendelphin** [comment]
I think it's the normal one. I can split it at another point and it doesn't prompt me for a second point

**Comment by simonpoole** [comment]
The root causes for this are on the one hand protection against generating invalid ways (aka with just one node) and the way the split position is determined. With other words fixing this needs some thinking, but isn't a big thing from a code pov.

**Comment by simonpoole** [comment]
The gods of code will hate me for this https://github.com/MarcusWolschon/osmeditor4android/commit/1615a661a22c9fea11f330f259b131d196e474c6
