### ISSUE TITLE
Website header display

### ISSUE THREAD

**Issue by maxerickson** [MarcusWolschon/osmeditor4android#375]
In a browser window narrow enough to get the Search Next Previous to drop down to a second line, the header obscures the top of the scrollable pane.

(Recent Firefox on Arch Linux)

**Comment by simonpoole** [comment]
Really fixing the issue would require some bootstrap foo. I've committed a partial fix by simply having less stuff in the nav bar.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/da91adabf8db6da6e18cca7b22e20c2dd8a45197
