### ISSUE TITLE
old data is reused after upload

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#379]
I often open the editor with geo indent via osmand. 
If i upload a change and afterwards reopening vespucci from osmand, the new place is opened with keeping the old data (good!). 
But often the osm data from before uploading is restored. If i do not check, vespucci wants to upload the old change and the new. This gives (solvable) conflicts.
My device is quite old (desire HD, with Android 4.0.4) so the app could be killed more often than expected. Latest release from play store.

**Comment by HolgerJeromin** [comment]
I am pretty sure i had this issue with 0.9.7b1036. But i will try to confirm.

**Comment by simonpoole** [comment]
the saving on upload was added in 1048

**Comment by HolgerJeromin** [comment]
Ok, imo we can close the issue then.

**Comment by simonpoole** [comment]
If possible I would like positive confirmation that the issue no longer happens. Thanks

**Comment by HolgerJeromin** [comment]
Ok for me. 
Waiting for an non existing event is more likely to be forgotten. 
Reopening if it is still an issue could be easier. :-)

**Comment by simonpoole** [comment]
its more of a mental note to me to investigate the specific constellation to be on the safe side if we can't confirm that the problem has gone away by other means

**Comment by HolgerJeromin** [comment]
I have not seen this problem since then. Feel free to close
