### ISSUE TITLE
Identify builds distributed and built by F-Droid

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#391]
Old problem: crash dumps from builds made for/by F-Droid are not identifiable as such. This is an issue when the APK is built slightly different (for example by using a different support library) than the builds released via google and amazon. For example during large parts of 2014 the build distributed via F-Droid had a serious build related issue that could only be identified in the end because the version number started lagging behind the regular build.

As a general rule I would suggest that distributors of (public) independent builds either:

- disable the crash reporting (not very sensible)
- identify the builds uniquely for example by modifying app_version and app_name_version
- and indentifying themselves here (so that they can be notified of any specific issues)

@krt16s is likely the current maintainer of the F-Droid build.

**Comment by MarcusWolschon** [comment]
If F-Droid doesn't use the numeric version code then F-Droid is broken.

**Comment by krt16s** [comment]
As requested, we append -fdroid to the version name and keep the versioncode specified in AndroidManifest.xml. We strip the versioncode and versionname found in build.gradle, since it has been touched in a while. It's still at `versionCode 41` and `versionName "0.9.5.1.955"`.

If you could add a reporting-free build flavor, we can use that. If there is anything other we can do to make our builds identifiable, I am open to suggestions.

**Comment by MarcusWolschon** [comment]
Why do you do a custom build anyway?
The same apk that is uploaded to play store is also uploaded to github.

**Comment by krt16s** [comment]
Well, because that is the purpose of F-Droid: We build apps from sourcecode. Long-term goal is to have reproduicble, blob-free builds.

**Comment by simonpoole** [comment]
@krt16s I don't have any issue with leaving the crash reporting in, it is in general helpful (regardless from where the build was obtained) and we don't ask for or require any personal information (aka e-mail address), not to mention that we would like it to never have to be used :-).

PS: BTW could you for now build from  0.9.7-MAINT-branch ? master is likely to be fairly volatile for a while.

**Comment by simonpoole** [comment]
Fixed by @krt16s
