### ISSUE TITLE
Typo in background service name notification title

### ISSUE THREAD

**Issue by CloCkWeRX** [MarcusWolschon/osmeditor4android#395]
Reproduce steps:
 * Open Vespucci
 * Start recording a GPS track or similar that will cause an ongoing notification
 * View current notifications

Actual notification:
Title: Ve**x**pucci background service
Vespucci is recording a GPS track....

**Comment by simonpoole** [comment]
This one was likel rather old, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/56382adb1eb4146b072a79b176e93777e934f65d
