### ISSUE TITLE
Opening new bug notifications opens google maps,  not vespucci

### ISSUE THREAD

**Issue by CloCkWeRX** [MarcusWolschon/osmeditor4android#396]
Not sure if I set some app handler default for lat/lon or similar unintentionally, but opening an osm bug notifcation opens google maps. 

Other notifications - ie background gps notification - launch vespucci as expected.

**Comment by simonpoole** [comment]
Notifications for Notes and OSMOSE bugs use geo: Uris, you likely currently have your device setup to start only google maps (instead of asking which app to start). You should be able to reset the behaviour somewhere in your settings (where depends very much on your Android version etc).
