### ISSUE TITLE
On new editing session, default source to 'survey', possibly also including current background layers if Bing/Mapbox/etc

### ISSUE THREAD

**Issue by CloCkWeRX** [MarcusWolschon/osmeditor4android#397]
The majority of the time when someone is running Vespucci is because they are walking around actually conducting survey type activities.

While after the first changeset is made the source, comments are retained; on first run of the application source defaults to blank.

It would be good to have this automatically inferred from current layers (similar to JOSM), and make the assumption its survey - coupled with a really easy way to override/wipe out text.

This might be best achieved with a text input placeholder approach; so if a user does not edit nothing is changed; but the moment the input is focused the user is prompted.

It seems like a small thing, but if you are editing infrequently - say walking a few hundred metres, noticing something interesting to map and starting editing - it becomes a usability annoyance. 

IE: Entering house numbers is a few clicks and a little input, with great autocompletes. Completing the commit process is actually more complicated/tedious for the first one (or if you restart multiple editing sessions).

**Comment by simonpoole** [comment]
0.9.8 already automatically documents used imagery sources using the same tag as iD and recent JOSM versions so you don't need to type those in at all.

As to the other fields: it is certainly possible to provide auto-complete, it is just "yet another state file" that has to be saved and reread plus some logic. I've not considered this as a priority up to now since the typical Android Keyboard will provide similar functionalitiy with additional flexibility (word by word suggestions of often used terms).

**Comment by ltog** [comment]
I'd also like to see this being implemented. It is similar (but distinct) to #430.

@simonpoole : As I learned today, you're the type of mapper that doesn't upload often when editing. For us other guys these things are important... ;-)

**Comment by simonpoole** [comment]
I guess typing survey once is an acceptable solution: see https://github.com/MarcusWolschon/osmeditor4android/commit/b62a483d3d6f6488e3981c3298012d60d78931fa 
Will be available in an upcoming build of 0.9.8

**Comment by simonpoole** [comment]
THere's a small issue with the current build with the on device softkeyboard that didn't turn up on the emulators that requires you to dismiss the keyboard with the back key before continuing. Will be fixed asap.

**Comment by simonpoole** [comment]
The remaining issue should be resolved with https://github.com/MarcusWolschon/osmeditor4android/commit/936c81cdedfe28c21de8e0c11cda02551d490523 and build 1112.
