### ISSUE TITLE
Allow copy and paste in debug info 

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#400]
Is the debug entry in the settings new? ☺
What ever, it would be great if I could copy the information to the clipboard. 
Perhaps with a button. Clickable (start a call) version number is not useful ☺

1.9.7 1085

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/3108a0b4bce03fb954bda9931c412c8ebfae3a51 already contains that.
