### ISSUE TITLE
Unable to edit tags on Fairphone 2

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#401]
Right now I cannot change a tag on Fairphone 2 with Android 5.1 and editor 1.9.7 r1085. 
Trying so is not saved on exit (button on the left) , so uploading says that I have not changed a thing. 
Creating or deleting nodes works and triggers the upload window.

**Comment by simonpoole** [comment]
Can't reproduce that here right now. 

Is it a specific object and tag that you were trying to change? Or is it a general symptom? 

On the debug info page there are three lines with
Relations
Ways
Nodes

Could you give the numbers before (no edits) and after you made a tag change? (You can simply attach a screenshot)

The whole thing sounds a bit weird as there where no changes to the PropertyEditor code and related bits between the last release and 1085 except a small change to PresetFragment. which however doesn't effect editing/storing of results.

**Comment by HolgerJeromin** [comment]
It is a regression compared to my desire HD phone with Android 4.0.4, no regression in the new r1085.

Yesterday there were an update to 1085. The version before (0.9.7.1.1079) had the same problem on this phone. Creating a new way worked, but changing tags worked not. I accidentally [uploaded a way](http://www.openstreetmap.org/changeset/36295249) with no tags:
http://www.openstreetmap.org/way/389003068/history
I did not realized the missing tags till now.

So the problem exists for all kind of objects (nodes, ways, new and old).

The rel, way, node values on the debug page do not change with an edit. But the state file and Bug state last changed date is updated.

**Comment by simonpoole** [comment]
OK, that is important information (that it is actually not a regression) because it implies that it is either an issue with
* your specific device or settings
* the Fairphone 5.1 Android version (5.1 causes no issues on any other devices)

Can you check developer settings on your device in particular "don't save activities" or similar? Further the memory allocation (from the debug info page) would be interesting.

However I suspect that the only way we can get to the bottom of this is by connecting your phone to a PC and enabling USB debugging and having a look at the log.

**Comment by HolgerJeromin** [comment]
The debug view is exactly identical, exept the dates:
![screenshot_2016-01-07-15-44-03](https://cloud.githubusercontent.com/assets/2410353/12173235/e7ea8146-b555-11e5-8c14-b672383bbce1.png)
![screenshot_2016-01-07-15-44-40](https://cloud.githubusercontent.com/assets/2410353/12173234/e7e3141a-b555-11e5-8719-da28574aeb2c.png)

I will try to get the logs.

**Comment by simonpoole** [comment]
"This is the first app with such a problem." Vespucci tends to uncover lots of things "normal" apps don't, particularly activity life cycle issues. However in this case it is specifically weird since it doesn't really do anyting special and simply returns the results via the Intent mechanism.

If you are successful with logcat (if the device has root access you should be able to get log information directly on device), I can make a special debug build if we don't get any further.

**Comment by simonpoole** [comment]
https://forum.fairphone.com/t/misbehaving-apps-fix-expected-for-next-update-workaround-re-enable-privacy-impact/11721 might be worth trying if you had turned the privacy impact setting off.

**Comment by HolgerJeromin** [comment]
I am waiting for the official documentation to get root on the device. I reported many bugs in mapillary with the logcat app on my rooted htc.
thanks for your help

**Comment by simonpoole** [comment]
If you have the Android SDK installed on a desktop somwhere you can use USB debugging to display the log, which doesn't require root.

**Comment by HolgerJeromin** [comment]
Chose the adb way thanks to wheezy backports :-)
With interesting results. 
I did not read your comment about the privacy impact. this was the right guess.
So the problem will be solved for all users in a few days by fairphone. 

Toggling the setting solved the issue for me. Feel free to decide to close this issue.

Just for reference:
````
D/SavingHelper(30800): preparing to save edit.state
I/SavingHelper(30800): saving  edit.state
D/SavingHelper(30800): renaming edit.state size 850 to edit.state.backup
D/SavingHelper(30800): renaming edit.state.1452205645390 size 1640 to edit.state
I/SavingHelper(30800): saved edit.state successfully
D/SavingHelper(30800): save thread finished
F/GrantAccessActivity(30766): GrantAccessActivity - onCreate
F/GrantAccessActivity(30766): GrantAccessActivity - start showPrivacyImpact
I/GrantAccessActivity(30766): GrantAccessActivity - de.blau.android
F/PrivacyImpactService(  866): Querying Package name: de.blau.android
F/PrivacyImpactService(  866): checking if it is in whitelist false
D/GrantAccessActivity(30766): popupDisabled true
D/GrantAccessActivity(30766): impactAccepted false
D/GrantAccessActivity(30766): isSystemApp false
I/GrantAccessActivity(30766): GrantAccessActivity - skip popup
F/GrantAccessActivity(30766): else
I/Timeline(30766): Timeline: Activity_launch_request id:de.blau.android time:4953986
I/ActivityManager(  866): START u0 {flg=0x10000000 cmp=de.blau.android/.propertyeditor.PropertyEditor (has extras)} from uid 1000 on display 0
W/ActivityManager(  866): Activity is launching as a new task, so cancelling activity result.
V/WindowManager(  866): addAppToken: AppWindowToken{167a0a48 token=Token{15cceb ActivityRecord{1800383a u0 de.blau.android/.propertyeditor.PropertyEditor t828}}} to stack=1 task=828 at 2
D/PropertyEditor(30800): Initializing from intent
````

**Comment by simonpoole** [comment]
Leaving it open for now just in case somebody else runs in to the issue ....

**Comment by simonpoole** [comment]
Has FairPhone release a update with a fix?

**Comment by HolgerJeromin** [comment]
No update till now...

**Comment by HolgerJeromin** [comment]
Update is being [prepared](https://forum.fairphone.com/t/call-for-testers-of-rc1-2-6/14970)...

**Comment by HolgerJeromin** [comment]
[Update 1.3.6](https://fairphone.zendesk.com/hc/en-us/articles/208342503-Fairphone-2-OS-Release-notes) of the Fairphone OS fixes this issue. 
I checked that this is solved at least with this update (could be the case even in April update).
