### ISSUE TITLE
Possibility to remove dark masked area from the map area

### ISSUE THREAD

**Issue by Myrtillus** [MarcusWolschon/osmeditor4android#403]
This issue is actually a derivative of discussion in here:
http://forum.openstreetmap.org/viewtopic.php?id=52346

Currently when you download a certain area from OSM database that is indicated with dark mask on top of the map background. It is a clear indication from which area the data has been downloaded but prevents using the map outside the mask. Typically the use case is such that the user compares the map background for the environment while wandering around. When the user spots an error or missing feature he/she downloads the data from a small area, does the modification and uploads changes. Then it would be beneficial to get rid of the dark mask and see the whole map background. 

Currently user has to download new areas to be able to reveal new map areas under dark mask. What is proposed is the same kind of behaviour that is used e.g. in JOSM. When you download data to Vespucci that is indicated with mask. When you have downloaded data you would have following options:
- discard all downloaded data and remove the dark mask
- modify data, upload changes and discard the data
- download more areas and all downloaded areas are indicated with dark mask.

**Comment by simonpoole** [comment]
There is actually a super simple workaround: you can modify the color of the "viewbox" item in the data style/profile entry you are using.

In 0.9.8 I'll simply disable the darkening when the screen is "locked".

**Comment by anissinen** [comment]
Sorry, I did not understood the above workaround. My version is 0.9.7 and I could not find any menu selection inside the application that would refer to viewbox. Did you modify the configuration files directly with editor or is it available only in the newer version of Vespucci?

**Comment by simonpoole** [comment]
Get https://drive.google.com/file/d/0B9pKLmh8s1h8VDMyNmNDSE9wXzA/view?usp=sharing edit the viewbox entry and then copy it (use "custom-profile.xml" or similar and set the profile name in the file too) to your Vespucci folder on your device.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/21736fb7fa49924cdc408228d46b26689a109d45
