### ISSUE TITLE
Display waypoints included in imported gpx files

### ISSUE THREAD

**Issue by larsbergengruen** [MarcusWolschon/osmeditor4android#417]
It would be great if not only the tracks of imported gpx files would be displayed, but also the potentially included waypoints and their labels (contained in `<name></name>`).
Reason: when out in the field tracking with osmand+, one can easily add waypoints and quickly label them to later add single nodes or track nodes at the respective positions. The additional labels of the waypoints are a great help at the later editing.

**Comment by simonpoole** [comment]
Currently the GPS track is drawn together with the map data. It likely would make sense to move this to a seperate layer for implementing this task.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/e527da8c28c727d2ebb74354fca2e2cc739ba2dc
