### ISSUE TITLE
http://vespucci.io/ translation

### ISSUE THREAD

**Issue by d1g** [MarcusWolschon/osmeditor4android#418]
http://vespucci.io/ only in English, but it contains previously translated information. However it also contains previously untranslated bits. I'm not sure what is the best migration plan and what should be reused and where.

**Comment by simonpoole** [comment]
PLEASE !

The current static site generator does not support i8n, however that is likely to happen in the future and then will display the already translated pages, When that happens the extra non-translated text will potentially be added to the Vespucci project on transifex. On device the content is multi-lingual as ever and can be translated on transifex as previously.

Do NOT start yet another translation effort of the same things.

**Comment by d1g** [comment]
@simonpoole, It would be nice to have non-translated text, so we can work on it and commit translations sooner :)
