### ISSUE TITLE
Include newlines in exported GPX track.

### ISSUE THREAD

**Issue by DFyson** [MarcusWolschon/osmeditor4android#419]
Would be much nicer if there were newlines between track points in the GPX file, make it more human readable. I was editing a gpx file exported by Vespucci in a text editor and it was pretty ugly, had to run it through html tidy.

**Comment by simonpoole** [comment]
Relevant result from googling http://stackoverflow.com/questions/3638283/how-to-indent-xml-properly-using-xmlserializer

**Comment by simonpoole** [comment]
Added in

https://github.com/MarcusWolschon/osmeditor4android/commit/ff55fa90048904af5cdd4c63819795b993187a04

and

https://github.com/MarcusWolschon/osmeditor4android/commit/b173cb5e062f882289dc5acab54311ec621fd29b

and will be included in the next builds.

**Comment by DFyson** [comment]
nice, thanks!
