### ISSUE TITLE
Government offices tagging scheme approved

### ISSUE THREAD

**Issue by Teiron** [MarcusWolschon/osmeditor4android#423]
With the new tagging scheme described here [link](http://wiki.openstreetmap.org/wiki/Proposed_features/Government_offices) number of presets are now outdated and should be changed. This include:

- _preset name; old tagging; new tagging_
- Register;  office=register; office=government + government=register_office
- Administrative; office=administrative; office=government
- Public buildng; amenity=public_building; **discouraged**

From what I seen that should be it, but if someone could double check it I would be grateful.

**Comment by simonpoole** [comment]
The default vespucci preset is not maintained here, see https://github.com /simonpoole/beautified-JOSM-preset
