### ISSUE TITLE
Zoom level and map position not maintained between crashes or when reopening

### ISSUE THREAD

**Issue by Kilkenni** [MarcusWolschon/osmeditor4android#424]
I have a feeling this functionality was in the earlier builds but is somehow gone now. When Vespucci crashes (or is accidently unloaded from memory) it preserves all the data (many thanks on that) but "forgets" the location you were editing, reverting to minimal world-view zoom. In earlier builds it somehow remembered it and restored the zoom and location after reopening. Now it doesn't (although it restores all the downloaded OSM data and background tiles just fine).
When mentioning "accident unloads" I mean a quite common for me situation when my device suddenly finds out it has ran out of memory and "drops" Vespucci out. Or terminates Vespucci when it is running in background.

**Comment by simonpoole** [comment]
In principle it stores both zoom and viewbox (it actually does that better that it use to, which may be what has changed its behaviour) but on a crash that information may not be written out correctly which is difficult to avoid (particularly when the device has run out of memory). Naturally it would be better to avoid crashing to start with and it defintely shoudn't be a regular occurance.

Could you indicate which vespucci version you are using, device and android version? Have you submitted crash dumps in the past?

**Comment by Kilkenni** [comment]
Wow. That was fast.
Sure. Vesp version 0.9.7.1.1071, f-droid build (https://f-droid.org/repository/browse/?fdid=de.blau.android). No changes from the main repository as far as I know.
Android version 4.1.1, the device if Fly IQ-442. 512 Mb RAM is not much as of today, but prefer not to change things that work ;)
And yes, I've submitted crash dumps when I had the occasion (i.e. internet) -- if Vespucci handled it correctly. Don't know how you can identify them though. In case my OSM login can help, it's the same as here on GitHub.

**Comment by simonpoole** [comment]
@Kilkenni we don't store any personal information in the crash dumps but typically the device is enough to identify crashes, Could you cut and paste here the information from the "debug page" (at the bottom of the preferences).

**Comment by simonpoole** [comment]
@Kilkenni I don't seem to have a current crash dump from your device, could you send one the next time you have a crash?

**Comment by Kilkenni** [comment]
Supposed so, but just in case.
Sure.
```
Vespucci (F-Droid) 0.9.7r1071
Maximum available memory 134217728
Total memory used 43573216
Tile Cache BING usage Size 16777216 of maximum 16777216 #entries 64
Tile Cache NONE usage Size 0 of maximum 16777216 #entries 0
State file size 176381 last changed 2016-03-24 09:22:34
Bug state file size 12606 last changed 2016-03-24 09:22:35
Relations (current/API) 116/0
Ways (current/API) 1160/0
Nodes (current/Waynodes/API) 7067/9076/0
Available location providers
network enabled false
passive enabled true
gps enabled false
```

Don't know why it marks network as "disabled" (my wifi is on if by "network" it means that).

**Comment by Kilkenni** [comment]
@simonpoole Will do. Can it be done manually, in case Vespucci won't be able to do it on its own? What are the steps?

**Comment by simonpoole** [comment]
@Kilkenni  it only makes sense to produce it when you have actually experienced a crash (because it will or at least should pinpoint where it crashed/ran out of memory in your case).

**Comment by Kilkenni** [comment]
Ok.
A thought on crash dumps - how is the device described in them? Because if it saves the Android software info, not the actual hardware, then it's different. My device has a custom Android build, it marks the phone not as the factory-made vanilla one does.

**Comment by simonpoole** [comment]
@Kilkenni we use ACRA which gives us enough info in most respects see https://github.com/ACRA/acra/wiki/ReportContent the crash dumps are deleted from the device once you've sent them so you still actually have to wait for a crash :-/

**Comment by Kilkenni** [comment]
My friend helped me test ACRA out. Seems like it grabs Android software info (i.e. OS build information), not the actual hardware information about the device. In my case it's following:

MANUFACTURER=Enspert
MODEL=CINK SLIM

Maybe you'll be able to find my reports using those. In the meantime I'm going to send any new crash dumps I get.

**Comment by Kilkenni** [comment]
Another crush. I've sent a dump in Vespucci, hopefully you'll get it.

**Comment by simonpoole** [comment]
Ok ... I found the correct dump, however the crash seems to not be related to the initial problem you reported. Unluckily the f-droid build is rather dated, it would be good if that was updated.

**Comment by simonpoole** [comment]
All issued should be addressed in the mean time, closing.
