### ISSUE TITLE
Failing upload resets Comment and Source field

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#430]
If an upload fails, the contents of the fields `Comment` and `Source` are reset and must be typed again.

I'd like to see these values staying until the upload succeeded (even if the user changed some nodes, etc. after the failed upload).

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/b62a483d3d6f6488e3981c3298012d60d78931fa 
Will be available in an upcoming build of 0.9.8

**Comment by ltog** [comment]
Nice! :-)

**Comment by simonpoole** [comment]
Build 1111 is available from google drive. Update is recommended.
