### ISSUE TITLE
Unable to clear bugs

### ISSUE THREAD

**Issue by DeeHants** [MarcusWolschon/osmeditor4android#431]
I currently have a map full of yellow bugs, and I can't clear them.
If I tap Up/download, Notes/Bugs..., Clear, they disappear, only to return after restarting Vespucci.
Attempting a download an area and then exiting (to save the state) doesn't make any difference.

Vespucci 0.9.7r1109 on Adroid 5.1.1.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/a5da442071bf4ad2ac059a3e5ce3be468d6933de and https://github.com/MarcusWolschon/osmeditor4android/commit/ece8d8389957ce14c2f82e5fb9c3327839169361 there was a reason the code was there, but I can't remember which .....
