### ISSUE TITLE
Crashes when editing some names

### ISSUE THREAD

**Issue by Janjko** [MarcusWolschon/osmeditor4android#433]
Open coordinates:
Lat: 45.79436 Lon: 15.91364
With radius of 50m

There should be a "Hrženička ulica". Select it and open tags. Click on name tag, and select the first option (the same as the current name). Then click on name again and the application crashes. 

It happens on certain streets, and I think it's the Croatian symbols that are to blame (žčćšđ).

**Comment by Janjko** [comment]
Now I tried this on several other streets, and it always crashes. I guess I found a bigger bug. Before only this and several other streets were breaking, and only when I tried to type something in.

**Comment by simonpoole** [comment]
I believe this is https://github.com/MarcusWolschon/osmeditor4android/commit/db5f1f0865a107bc8cf5e29d5c2c5ccc87f88660 if you are using 0.9.8, from where did you get your version?

**Comment by Janjko** [comment]
I'm on 0.9.8, that's it then. I'll try to find the other one.
