### ISSUE TITLE
Key:collection_times wrong Syntax

### ISSUE THREAD

**Issue by rza31** [MarcusWolschon/osmeditor4android#434]
collection times with vespucci are with vertical bar instead semicolon.
 
see: http://www.openstreetmap.org/node/2904387802

**Comment by simonpoole** [comment]
This is, if at all, a preset issue (and not  and exists in the original JOSM preset too: https://josm.openstreetmap.de/browser/josm/trunk/data/defaultpresets.xml

Please open an issue here: https://github.com/simonpoole/beautified-JOSM-preset/issues
