### ISSUE TITLE
Layer visibility / ordering without having to change via preferences

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#435]
It would be nice if layers coubd re re-orderd (and at the same time the whole configuration be made a bit more dynamic) and visibility changed without having to access the Preference activitities.

**Comment by gdt** [comment]
Specifically, I would like to set one map type and one imagery type (this can be as it is) and then be able to flip back and forth with very few touches, ideally 1 (but ideally it would not take up screen space either :-).

A further possibility is to change to imagery at say z18 and higher and map at lower.  But I may be odd for wanting that.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/d180a8940a27b82a4412eafa8a37c37451e406f1 (layer ordering not implemented), the new layer control has for the imagery layers a "most recently used" list.
