### ISSUE TITLE
Map tiles cache is indexed by OS (missing .nomedia marker)

### ISSUE THREAD

**Issue by Self-Perfection** [MarcusWolschon/osmeditor4android#436]
Vespucci stores its map tiles cache in `$SD/andnav2/tiles/.../XXX.png.andnav` files.

In SailfishOS media files indexer ([tracker](https://wiki.gnome.org/Projects/Tracker)) indexes png files regardless of extension and media library becomes polluted by thousands of map tiles.

I suppose Vespucci should put `.nomedia` file in `$SD/andnav2/tiles/` directory to prevent indexing.

**Comment by simonpoole** [comment]
Will fix asap.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/cdf888d6e9604692898a49819dee297d7f907e89 and https://github.com/MarcusWolschon/osmeditor4android/commit/f4c6d67345fff1b113152dac00b4f50afdf6bcdd
