### ISSUE TITLE
Populate recent tag list from manual entering

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#439]
If I select an preset it is added with an icon in a most recent used list in the tag editor. 

Often I am faster entering with the keyboard than the presets. 
It would be great if the first entered tag would get an icon, too. Perhaps only when a matching preset (for the icon?) is found.

**Comment by simonpoole** [comment]
I was thinking along the lines of adding the last matched preset(s) to the MRU list (given that the matching works far better in 0.9.8), further it would likely be nice to have the last used tags available.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/f422ce23858b4040ee9e57065f5748e56b0b8d3a
