### ISSUE TITLE
Map not following finger movements on low zoom levels

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#440]
If you choose a low zoom level and pan the map around, it does not properly follow the finger's movement. It either accelerates too fast or too slow in north/south direction but is ok in east/west direction. Maybe a conversion issue involving the Mercator projection?

Vespucci version 0.9.8b1124 on Fairphone 2 Open Source OS with Android 5.1.

**Comment by simonpoole** [comment]
Can you set the full screen mode to "never" in the advanced preferences? The issue may be related to https://github.com/MarcusWolschon/osmeditor4android/issues/441 Full screen mode on android phones is more than a bit iffy.

**Comment by simonpoole** [comment]
Previous comment didnßt make sense, could be anything.

**Comment by simonpoole** [comment]
IMHO at least on emulators it seems to be a "per drag" slight lag till the drag has been registered, real devices might behave slightly different naturally.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/3bf19840c08db2273bb573e518c90d54b6dae4e6
