### ISSUE TITLE
Can't swipe from top

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#441]
After installing Vespucci I got a message saying "to leave fullscreen swipe from top" or similar. On Fairphone 2 Open Source OS swiping from top just brings up the status bar`*` as usual. Nothing else happens.

`*` Not sure if status bar is the correct name. I mean the bar where you can see the current time, battery level, reception level, etc.

Vespucci version 0.9.8b1124 on Fairphone 2 Open Source OS with Android 5.1.

**Comment by simonpoole** [comment]
THe message is not generated by vespucci, what should work is swiping from the bottom (to show the nav bar), which should allow you to press the "back" key.

**Comment by ltog** [comment]
@simonpoole : Swiping from the bottom works just like you described. (Maybe I misread the message and it actually said "swipe _to_ the top"?)
