### ISSUE TITLE
Fullscreen mode issues

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#444]
After using the PropertyEditor soft keys don't disappear.

**Comment by simonpoole** [comment]
Recreated on Amazon tablet, the issue is likely due to the main activity not being paused and as a consequence onResume not being called when the PropertyEditor is finished. onWindowFocusChanged should really handle that case but perhaps not.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/a61f599cca15315a25356c5ddc77fed6f4006d6c implements a workaroud that while, not elegant, seems to work. it would naturally be nice to see if we could address the root cause. 

@mstock build 0.9.8b1154 contains the fix can you test when you have time?

**Comment by mstock** [comment]
Just tried this version, and I was not able to reproduce the issue anymore, definitely not in the same way I saw it before. Now the soft keys always disappeared after a short moment when leaving the PropertyEditor. Most of the time, this looks kind-of interesting though, as it seems like there might be two soft key 'toolbars' on the screen at the same time, the semi-transparent one and the non-transparent one over each other, so now I first see that the non-transparent one slides down, which allows me to see the semi-transparent one, which then slides down some milliseconds later, too. I'd consider this issue as fixed though, despite this effect, as the soft keys always disappeared.

**Comment by simonpoole** [comment]
@mstock well the solution is a hack, so some weirdness is to be expected. Likely the clean solution would be to use fullscreen mode in every activity in the app however this causes havoc with the soft keyboard which has to be available in the property editor.

**Comment by simonpoole** [comment]
There seems to be a remaining issue that after invoking the property editor the menu bar ends up in the wrong position till another element is selected:
![screenshot_1514495868](https://user-images.githubusercontent.com/1011860/34423589-4cfcdb92-ec1d-11e7-8ef4-e2ee999e6d3d.png)

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/5300f0fb78aa03eb32ca2316fc8676742d22fe06 seems to fix all known issues.
