### ISSUE TITLE
Nodes on ways: "double selection" to get to tags editor 

### ISSUE THREAD

**Issue by bjohas** [MarcusWolschon/osmeditor4android#446]
The described process can be seen more clearly here:
http://bjohas.de/wiki/Vespucci/selection_and_creation

1.  Find a way and look at a node on it.
2. Now tap (short tap) on the node. You'll see the "selection" popup
3. Choose the node and node is selected.
4. Tap the node again, and the selector appears again
5. If you select the node, you'll get to the tag editor. 

Step 4, with the selector re-appearing is potentially confusing. Moreover, if in step 4, you select the way, the way will be selected. You can the tap the node (way stays selected), then tap the way again, and you'll get to the tag editor for the way.

My suggestion is to either:

(A) Change the text in the 1st/2nd popup (steps 2 or 4), so that the user knows it's different. 
E.g. in Step 2, it could say "Select one of the objects in this location:".
In Step 4, it could say: "Re-select or edit tags..."

(B) Alternatively re-implement this as the following rule: "Tapping a selected object, opens the tag editor for that object." This would mean that to re-select, one would have to tap elsewhere to remove the selection. 

Thanks!

**Comment by simonpoole** [comment]
I suspect it already works as you intend (there are slight differences between versions and you haven't stated which version you are using). The disambiguation menu only appears if: it is turned on to always show when there are more than one element nearby, or the object is member of a relation, or it can't reliably determine which element was selected.

If you have zoomed in enough and there are no other objects are nearby then the first touch will select the object, the 2nd will open the property editor. 

Or put differently: selecting an already selected object either directly or via the disambiguation menu will start the property editor. Would seem to be fairly consistent to me.

**Comment by bjohas** [comment]
It's the latest version, 0.9.7.1.1141.

The disambiguation menu would always appear when selecting nodes on ways, right? 

My issue is that the disambiguation menu appears twice, but looks exactly the same, although it has different functions. So I kept going round in circles. My suggestion is that either the text in the two appearances of the disambiguation menu should be different (to let the user know that the first appearance is about selection, the 2nd about property editor or re-selection). Alternatively, the disambiguation menu should only be used for selection. If a selected object is tapped, the property editor appears directly.

I should also add that initially I didn't realise how the disambiguation worked. I had initially assumed it was just for information, rather than clickable. So a text like "Select object:" should be added to the first appearance in any case.

Hope that makes sense!

**Comment by simonpoole** [comment]
While in principle I would agree that giving some more visual feedback in the context menu would be good, this is limited by the available styling in the context menu itsself.

**Comment by simonpoole** [comment]
Partially addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/c1d0daa49529a17a4213280518d9c3a4a9ac4b38
