### ISSUE TITLE
Add "search" button to "Find" dialogue

### ISSUE THREAD

**Issue by bjohas** [MarcusWolschon/osmeditor4android#448]
When you select (three dots) > Find, the box only has a "cancel" button beneath. Search takes place by pressing the "search" on the keyboard. This menu would be clearer if there was a "search" button next to "cancel".

**Comment by simonpoole** [comment]
Actually that simply means press "enter" (on the soft keyboards it gets displayed as a magnifiying glass but on real keyboards the symbol naturally doesn't change). The underlying reason for not having a "search" button is that you will have just typed, on whatever Keyboard you are using, the search string, and simply touching or pressing "enter" would seem to be the natural choice and a search button redundant.
In any case I've added it as a enhancment request.

**Comment by HolgerJeromin** [comment]
I personally often searched for the button and after thinking  hit the key on the keyboard. 
Probably when I had  closed the keyboard.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/1433408478f0906b97f5e4002540309566b7ce4a
