### ISSUE TITLE
Highlight downloaded area

### ISSUE THREAD

**Issue by hike39** [MarcusWolschon/osmeditor4android#449]
Vespucci 0.9.8.0.1146

The downloaded current view area is not highlighted. You have to unlock the data to see what area my be modified.

Greetings
hike39

**Comment by simonpoole** [comment]
The change in behaviour is deliberate see https://github.com/MarcusWolschon/osmeditor4android/issues/403 not quite sure if I'm actually comfortable with the change, and it may move to a preference before release.

**Comment by hike39** [comment]
Sorry did not see #403. But due to the fact that in a lot of regions you don't have good coverage I download the areas I want to survey at home and not on site. And in such cases it is helpful to see which ones can be modified. But I can live with the new behavior.

So I would suggest to close this issue.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/ed39802eac53fc066e750a180eca181958d4b0f7 makes the behaviour a preference.
