### ISSUE TITLE
Java code in JOSM Preset

### ISSUE THREAD

**Issue by mihainiculita** [MarcusWolschon/osmeditor4android#453]
Hello,

I try to use a JOSM Preset and the values_from="JAVA code" feature (found it here https://josm.openstreetmap.de/wiki/TaggingPresets):

`<key key="TIME" values_from="String mydate = java.text.DateFormat.getDateTimeInstance().format(Calendar.getInstance().getTime());textView.setText(mydate);" />`

I try to insert the current time, but this is not working.

Is this JOSM Preset feature supported by Vespucci.

I have identified also other tags that appear not to be supported. Can someone confirm what kind of support is available for JOSM Presets for the latest version of Vespucci?

Thanks in advance!
Mihai

**Comment by simonpoole** [comment]
You just need to RTFM: http://vespucci.io/tutorials/presets/ 

There are all kind of issues trying to support it in the form JOSM does would raise, I suspect a light weight script language like LUA or similar might be a more viable solution.

**Comment by mihainiculita** [comment]
Thank you! I didnțt knew that page. Now is clear for me.

**Comment by simonpoole** [comment]
Note that there aren't potentially other ways to implement what you want to do, could you detail that a bit?

**Comment by mihainiculita** [comment]
I develop my own schema osm tags and I would need to insert the time a feature is created.

**Comment by simonpoole** [comment]
And the time set when uploading by the API is not good enough?

**Comment by MarcusWolschon** [comment]
values_from="JAVA code" can't be done on the Phone as there is no Java runtime that can interpret code. It is compiled to Dalvik Byte-Code before it is uploaded to the Play Store.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/commit/cf3e4bf44492131d932953f4bb34ffc0ab714346 for an initial test at supporting scripting.

**Comment by simonpoole** [comment]
Addressed in https://github.com/MarcusWolschon/osmeditor4android/issues/536
