### ISSUE TITLE
Dependency tracking via VersionEye

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#455]
I suggest setting up a project, team and organization on [_VersionEye_](https://www.versioneye.com) to track the dependencies of the project. The team will receive e-mail about updated libraries. I am happy to help with the setup.

**Comment by johnjohndoe** [comment]
Meanwhile, it is possible to configure a team for a project on VersionEye.

**Comment by stephan75** [comment]
... or what about https://greenkeeper.io as an alternative service, or additional? 

See the github repository of iD editor how that works via pull requests etc.

**Comment by simonpoole** [comment]
The absolute last thing yu want is to automatically use new versions of dependencies (see the mess with f-droid), getting the information that there is an update is OK naturally.

**Comment by HolgerJeromin** [comment]
Green keeper builds only  pull requests if there is an update.

**Comment by simonpoole** [comment]
Done. If you want to receive notification just drop me a mail.

@stephan75 @HolgerJeromin while not completely clear greenkeeper seems to be npm centric.

**Comment by johnjohndoe** [comment]
Yes, Greenkeeper is for Node.JS projects.
@simonpoole Are you going to add the VersionEye badge to the `README.md`?

**Comment by simonpoole** [comment]
@johnjohndoe if you point me to it .... if there is a pointer to it during the sign up process I missed it.

**Comment by johnjohndoe** [comment]
At the moment I cannot see the project on the VersionEye website. I can however see the `vespucci` organization as shown in the screenshot.

![versioneye-vespucci](https://cloud.githubusercontent.com/assets/144518/23590519/edf73b40-01e1-11e7-9cf3-861cf687781b.png)

**Comment by simonpoole** [comment]
The projects were assigned to the wrong team should be fixed now.

**Comment by johnjohndoe** [comment]
@simonpoole I noticed that _VersionEye_ allows to configure how often notifications are sent. This can be configured for **each** _Team_ as shown in the sceenshot:

![versioneye-notifications](https://user-images.githubusercontent.com/144518/28972442-f7d49142-792f-11e7-9288-1355a3454e91.png)

I think **once a week** is enough - the dependencies do not change that often.
