### ISSUE TITLE
opening vespucci on mobile devices from osm.org

### ISSUE THREAD

**Issue by TheFive** [MarcusWolschon/osmeditor4android#457]
Hi,

i am not an android user, but i have a question regarding https://github.com/openstreetmap/openstreetmap-website/issues/985. How is it solved on android to jump from osm.org direct to vespucci and edit.
Here I have suggested https://github.com/bryceco/GoMap/issues/98#issuecomment-235600730 a dedicated osmedit uri, but may be there is already a Solution on android.

**Comment by simonpoole** [comment]
vespucci has supported geo uris since September 2014. Matter of fact it has supported JOSM style remote control since then too, however since you don't get the edit button from osm.org on mobile devices and android doesn't pass the URL through to vespucci any way, that doesn't actually help.

**Comment by simonpoole** [comment]
See https://github.com/openstreetmap/openstreetmap-website/pull/1478 and http://vespucci.io/tutorials/vespucci_intents/
