### ISSUE TITLE
Merging nodes should keep oldest id

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#458]
Title says all. Too keep the history it is most of the time best to keep the oldest id when merging two nodes. 
Same with ways?

**Comment by simonpoole** [comment]
Currently we do a simplified version of this (both for nodes and ways)  and will prefer existing objects over new ones, no reason we coudn't take the version number in to account on top of that.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/76a671e718725ccc3a5c4e2fa0e15fb6c64c2c1d

**Comment by HolgerJeromin** [comment]
Thank you for your quick fix!
