### ISSUE TITLE
Export of notes

### ISSUE THREAD

**Issue by hike39** [MarcusWolschon/osmeditor4android#459]
A feature should be provided for the export of recorded notes. Proposed format is .osn.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/issues/337 too.

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/commit/a1fb6e53d4e1d1db3e19a2a8a9b31270d18414db
