### ISSUE TITLE
missing created_by tag in changeset metadata

### ISSUE THREAD

**Issue by tyrasd** [MarcusWolschon/osmeditor4android#463]
In http://www.openstreetmap.org/changeset/41453004 the mapper claims to have used the latest version of Vespucci (0.9.7.1.1141 most likely), but the changeset metadata doesn't contain a `created_by` tag.

**Comment by simonpoole** [comment]
As you can see the changeset after the edit in question and the preceeding ones excapt one. have the created_by tag, so it might be a bug, but without at least some indication of the settings and what the mapper was doing at the point in time, it is not clear what is supposed to be actionable in this report.

**Comment by tyrasd** [comment]
Hm. OK, let me do some more debugging:

I see that the affected changeset is a pretty long open one (most probably auto-closed by the API). So, maybe it has something to do with the way Vespucci handles not immediately closed changesets? Let's try it: change the respective setting in Vespucci and upload some changes: nothing spectacularly's happening (changeset has a `comment` and `created_by` tag). Then, change some more stuff and upload the data once more: Bam! The `created_by` just vanished (the `comment` tag is still there).

Here's my test changeset: http://www.openstreetmap.org/changeset/41520069

Is this enough information now? ;-)

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/d6699fa57db2203619cdd1371e18ef66da718a81 Fixed wording in wiki: http://wiki.openstreetmap.org/w/index.php?title=API_v0.6&type=revision&diff=1336967&oldid=1333601

Note: we currently can't update the version available from the google play store.

**Comment by tyrasd** [comment]
> we currently can't update the version available from the google play store

What about the version on f-droid? That one looks even more out of date.

**Comment by simonpoole** [comment]
We don't have any influence at all on what f-droid distributes. Further it is not clear how they determine when to publish a new version, so there is not an obvious way we could initiate a new build.

**Comment by tyrasd** [comment]
> We don't have any influence at all on what f-droid distributes.

Well, according to their FAQs, one needs to tag a (non-beta) release in order for them to be detected and built by f-droid (see https://f-droid.org/wiki/page/FAQ_-_App_Developers#What_about_versioning.3F ff., https://f-droid.org/manual/fdroid.html#Update-Check-Mode)

//cc @krt16s

**Comment by simonpoole** [comment]
Well that will only work if the configuration for f-droid for the app is set accordingly, and we have no idea if that is so, as already said we have nothing to do with f-droid (and given that you have to enable sideloading in any case, you can just as well download the apk from github).

In any case as a test I've  tagged the last 0.9.7 build lets see if anything happens.

**Comment by simonpoole** [comment]
Nothing happend, if you check https://f-droid.org/wiki/page/de.blau.android#Versions you can see that automatic building is disabled.

**Comment by tyrasd** [comment]
from this log entry it looks more like as if the build didn't compile properly:
https://gitlab.com/fdroid/fdroiddata/commit/b38478726fa402143b003534fba71c0dcc81d689

**Comment by simonpoole** [comment]
It should be building against acra-4.8.2 not 4.5 something. 0.9.7 was/is built using the classical android plugin in eclipse without retrieving dependencies during the build process (I've changed that for 0.9.8 with better gradle support in eclipse available now, bur am not going to retroactively change 0.9.7). 

As you can see the f-droid build tries to remove the included libraries and retrieves the dependencies via gradle except that they get the wrong version.

I've opened a new issue https://github.com/MarcusWolschon/osmeditor4android/issues/466 for this discussion, maybe the person responsible for the F-droid setup will respond
