### ISSUE TITLE
Improve conflict handling

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#464]
Various aspects need revisiting:
- [ ] when a version conflict happens and the only difference is in tags check if they can be merged without issues (a la iD)
- [ ] currently when a way (likely a similar argument may apply to relations) on server has different and potentially new nodes than the in editor version and we decide to use the editor version, such nodes will remain as unatached nodes on server, while this is safe it is also messy.  Just using the local version would seem to be problematic, probably we should try to merge.
- [ ] Add a button to display the ElementInfo dialog on the conflicting objects, this will allow zooming to and selecting the objects (as in the upload dialog), at the cost of interrupting the resolution of the conflict. 

Related: https://github.com/MarcusWolschon/osmeditor4android/issues/378

**Comment by HolgerJeromin** [comment]
At least it would be usefull to show the conflicting elements.
Right now the name / ref / main type is shown. But there could be multiple of them.
I have to decide blind which version (local or server) should survive with no easy possibility to redo my changes.
So please highlight the element on the map so i can remember the element for review.
