### ISSUE TITLE
F-droid build fails

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#466]
@krt16s see https://github.com/MarcusWolschon/osmeditor4android/issues/463

Further relevant issue: https://github.com/MarcusWolschon/osmeditor4android/issues/391

**Comment by krt16s** [comment]
Should be fixed in https://gitlab.com/fdroid/fdroiddata/commit/1946f07126476040d9331a6203091ca034c673a9. Sorry for net responding earlier, I tend to get a lot of mails/mentioning :/

**Comment by simonpoole** [comment]
Seems if it built 1147 now, however I created a tag for 1149 yesterday which however hasn't been build yet. This may simply be due to some lag in building so waiting with closing this issue for now.

**Comment by simonpoole** [comment]
@krt16s see https://github.com/MarcusWolschon/osmeditor4android/issues/474 1155 has a fair chance of buidling OK, however hasn't turned up in the f-droid repo. The other question is if there is an option to remove 1151 and 1153 ...

**Comment by krt16s** [comment]
I disabled 1151 and 1153 in the metadata,, they will be purged from the repo sometime tomorrow.
