### ISSUE TITLE
Jump to gps coordinates 

### ISSUE THREAD

**Issue by brunetton** [MarcusWolschon/osmeditor4android#467]
Hi all 
I often use vespucci on my phone to do some edits. Sometimes, like today, I've to add a POI that I only have gps coordinates. I find no way to center the card to given gps coordinates. 
Only a "center to..." would be okay. I can then zoom in to place my poi. 
I can't really be helped by tiles or satellite photos, there's no landmark around to place the poi. 

I don't think this is a big deal to implement, it'll be very useful! 

Thanks

**Comment by HolgerJeromin** [comment]
The first three entries of the transfer menu (arrows) are 

* Download current view
* Add current view to download
* Download other location

The third entry should be what you want, isn't it?

BTW: I often open an area in Osmand and use the "share" => "geo:" feature to open the area in Vespucci.

**Comment by simonpoole** [comment]
There are probably half a dozen ways to skin this particular cat. 

Another one is: 
- create the POI (long press and add tags)
- when you are back in the map display and still have the node selected: select "Position" from the Menu and enter the coordinates (the node will be moved there and the map will center on the position)

**Comment by brunetton** [comment]
Thanks for the share -> geo trick, it's a very precious thing to know. I
often use osmand with opentopo to locate things more precisely.
I know the "download other location" feature, but (logically) it's only
available online. In that case I was offline, seeing a point quite far from
me, localized it on osmand with opentopo card, and I wanted to "prepare" a
contribution.
Writing that, it's maybe not logical to use vespucci in that way.

**Comment by brunetton** [comment]
Thanks Simon, this resolve my problem. I'm using vespucci for a while and
never noticed that option.
