### ISSUE TITLE
Download traces from OSM (Future request)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MarcusWolschon/osmeditor4android#47]
```
Future request:

It would be very useful to download all my traces from OSM to this
application. So that I can see what areas are already traced.
```

Original issue reported on code.google.com by `Frodu...@gmail.com` on 20 Apr 2010 at 9:56

**Comment by brunetton** [comment]
Any hope in this ? I really miss it too, for a long time

**Comment by simonpoole** [comment]
@brunetton why isn't the GPS track layer sufficient?

**Comment by brunetton** [comment]
Thanks for answer.
Do you mean the GPS tracks recorded by Vespucci ? I often use an external
device to record tracks. Sometimes it is only a simple app that I can
quickly start while driving, or biking. Typically an app that provides a
widget to start recording really quick.
IMHO, importing a gpx track is a bare necessity for a mapping software.

**Comment by simonpoole** [comment]
Importing GPS tracks should work since 2014 see above (I don't know how much use the feature gets, but am not aware of any issues). I was referring to download of tracks via the OSM API, which we don't support currently, the replacement for that is to simply use the GPS track tile layer.

**Comment by brunetton** [comment]
Ok, I just didn't seen that track import isn't in file->import, but in GPS->Track management

Now It works !

Sorry for that

**Comment by simonpoole** [comment]
GPS track overlay and track import should cover all reasonable use cases.
