### ISSUE TITLE
Ignore format when pasting text into editor 

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#470]
When I paste text from opera browser into a tag value or changeset comment often the text is much larger than the rest. 
Could be an artifact from html styling which is not deleted.

**Comment by simonpoole** [comment]
How did you actually paste? The normal paste in to editable text field is provided by the "system", it may be possible to stop the formatting, but I need to test.

**Comment by HolgerJeromin** [comment]
I had a normal copy in the browser and paste into the editor. 
Leaving the tag editor normalizes the text, so everything is normal after that. 
Fairphone 2 with Android 5
I can provide Screenshots in a few days

**Comment by HolgerJeromin** [comment]
Long tab with the finger and paste from a menu.

**Comment by simonpoole** [comment]
This probably requires removing formatting in a TextWatcher callback, aka can of worms.

**Comment by HolgerJeromin** [comment]
![image](https://cloud.githubusercontent.com/assets/2410353/18609905/e91c36e2-7d0d-11e6-8440-ee78e9d11b5b.png)

Possible in the changeset comment, too:
![image](https://cloud.githubusercontent.com/assets/2410353/18609904/df2ea908-7d0d-11e6-9afb-63596cd947ce.png)

**Comment by simonpoole** [comment]
Again this is standard Android system behaviour and not easy to workaround, if you want to paste text from the system clipboard simply use the corresponding menu item and not the build in EditText function.

**Comment by HolgerJeromin** [comment]
I missed the menu till now. Thanks for the explanation.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/5caf45740222a7b940405d44a95c4374b5b9649a
