### ISSUE TITLE
Disable upload menu entry when nothing was changed 

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#472]
The position menu has many things which are gray / disabled if not useful, but the transfer menu has not.

**Comment by simonpoole** [comment]
This is a bit trickier than it sounds.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/14a72c8b06d3bb559c88855df71c91c9d5dddfab
