### ISSUE TITLE
"Some data parts were not uploaded"

### ISSUE THREAD

**Issue by Kilkenni** [MarcusWolschon/osmeditor4android#480]
I know it's an issue tracker, not a help forum. But what does that error supposed to mean?
Started to show every time I try to upload, effectively rendering Vespucci unusable.
More accurately, the text goes something like this:
"Some data parts were not uploaded to the server. Try again if it's a temporary problem."
I've tried everything I could think of quickly - relaunching the app, rebooting, switching to another wifi, disabling iptables firewall, renewing the OAuth marker. Not helping. I can still download a part of the map into Vesp, but I can't upload. The changes are still in the dump, I can pull them out to a save file, so my main concern is I'll be denied uploading in the future.

**Comment by simonpoole** [comment]
You need to indicate which version you were using.

When you upload you can see a list of the changes that it is trying to upload to the server. If it is nothing relevant any more simply do a clean download (with other words don't merge) and the problem should vanish. 

As I already pointed out in https://github.com/MarcusWolschon/osmeditor4android/issues/477 there was a bug in the OSM/JOSM file loading code version previous to 0.9.7r1159 and 0.9.8b1194 which is likely causing your problems (you didn't answer my question there BTW).

**Comment by Kilkenni** [comment]
@simonpoole 
Sorry about that. I thought it to be a new one - never saw that particular error window before.
"you didn't answer my question there BTW" Please repeat it in that thread, I must have missed it.

**Comment by simonpoole** [comment]
-> "I can upload your file or you can do it with JOSM or a fixed vespucci version 0.9.7r1159 or 0.9.8b1194. "

**Comment by Kilkenni** [comment]
Oh. That. The thing is, I can't find 1159 version on Github.

**Comment by simonpoole** [comment]
As I wrote it may take some time, and as seems look like now, likely we will be releasing 0.9.8 rsn (in a couple of days). In nay case I just wanted to know if you can wait or if I should upload your remaining changes from that file.

**Comment by Kilkenni** [comment]
Oh. Thanks, but I really don't wanna disturb ya. If that's a couple of days, my edits can wait.
