### ISSUE TITLE
UI glitch for zoom and location buttons in 0.9.8

### ISSUE THREAD

**Issue by ns130291** [MarcusWolschon/osmeditor4android#481]
The inner circles inside the buttons aren't centered.
Device: Nexus 5X, Android 6.0.1
![tmp_14517-screenshot_20160923-121040-959292271](https://cloud.githubusercontent.com/assets/1678202/18784641/464b0a74-818b-11e6-9e1a-6e9d40e339ea.png)

**Comment by kudlav** [comment]
Samsung Galaxy A3, Android 5.0.2, same issue.

**Comment by simonpoole** [comment]
This is the FAB (floating action button) as provided by google, visibility depends a bit on the background imagery, and naturally we could make it slightly less transparent.

**Comment by simonpoole** [comment]
Just for the record the same glitch can actually be seen on https://developer.android.com/training/material/design-library.html

**Comment by simonpoole** [comment]
Partial workaround https://github.com/MarcusWolschon/osmeditor4android/commit/e62c35184fbfd04f6e073fcc3c3db8d123ad3323 and https://github.com/MarcusWolschon/osmeditor4android/commit/e62c35184fbfd04f6e073fcc3c3db8d123ad3323
