### ISSUE TITLE
"Follow GPS" button layout settings

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#482]
At settings there's a option "Follow GPS button layout". It can be set to Left or Right, but the button is always on the left, regardless the settings.

And the font size at settings pages is so huge.

Samsung Galaxy A3
App: 0.9.8
Android: 5.0.2

![screenshot_2016-09-23-13-58-10](https://cloud.githubusercontent.com/assets/11516259/18791469/23d6357c-81b3-11e6-9168-52e1dceb6141.png)
![screenshot_2016-09-23-13-58-24](https://cloud.githubusercontent.com/assets/11516259/18791480/2ccd005c-81b3-11e6-9976-e4cb505054e8.png)

**Comment by simonpoole** [comment]
This is a regression. Will be fixed in the next build.

**Comment by simonpoole** [comment]
Ficed in https://github.com/MarcusWolschon/osmeditor4android/commit/4be8e4eedb06575b1e26bfbb61004a4579ec4ead
