### ISSUE TITLE
Use OpenAerialMap as additional source for imagery

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#484]
Instead of just relying on the imagery index add optional selection from OAM. Licence of OAM imagery is a bit iffy though.

**Comment by daveo30** [comment]
Would like to work on this issue. Any help as to how to go about it would be appreciated!

**Comment by simonpoole** [comment]
@daveo30 from a technical pov my basic idea was to query the "the" OAM server for sources with footprints intersecting with the current viewbox and add them to the imagery preference selector, IIRC you can't directly query the OAM index directly for tile server URLs so this is likely slightly more involved than it sounds. 

Legally it seems as if OIN/OAM is confused as to their imagery licence and one could argue that data derived from their sources is currently not suitable for inclusion in OSM so this issue isn't a high priority right now.

Related issues:  https://github.com/MarcusWolschon/osmeditor4android/issues/250 https://github.com/MarcusWolschon/osmeditor4android/issues/435

**Comment by adamthewebman** [comment]
I am not a lawyer but a cording to their website it is available for openstreetmap tracing. "All imagery is publicly licensed and made available through the Humanitarian OpenStreetMap Team's Open Imagery Network (OIN) Node. All imagery contained in OIN is licensed CC-BY 4.0, with attribution as contributors of Open Imagery Network. All imagery is available to be traced in OpenStreetMap." (http://openaerialmap.org/about/ )

**Comment by simonpoole** [comment]
A current workaround for this issue is to navigate to the OAM site and simply copy the  tileserver URL to the custom imagery form.

**Comment by simonpoole** [comment]
Added support for querying the OAM catalog in https://github.com/MarcusWolschon/osmeditor4android/commit/83131876b63ab588a6de9522f2df41273f47b775
