### ISSUE TITLE
Application action buttons overlay system buttons 

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#487]
The system buttons are overlayed by the action buttons at the bottom as shown in this short screen capture. 

![Vespucci 0.9.8r1199](https://cloud.githubusercontent.com/assets/144518/19049517/173ef25e-89ab-11e6-9c63-d6e28a466dbb.gif)
- It is very hard to find out **how to reach the system buttons** at all because of the fullscreen mode (?)
- When the system buttons overlay the applications buttons they are **barely visible**. The system buttons are in **white** color with transparent background color.

Observed in version 0.9.8r1199 on Android 5.1 on a Motorola Moto G phone.

**Comment by simonpoole** [comment]
Unluckily full screen mode in android is hit and miss, on some combinations of device and OS it will work OK in others it sucks (see https://github.com/MarcusWolschon/osmeditor4android/issues/444 ). In general i would recommend disabling it in the preferences if it causes too many issues.

**Comment by johnjohndoe** [comment]
Thanks for the helpful hint. I saw the Asus issue. Maybe, consider disabling fullscreen mode by default?

**Comment by simonpoole** [comment]
There was some explanatory text added in https://github.com/MarcusWolschon/osmeditor4android/commit/9b52f483969a23ec5853c579734c99876436498a and https://github.com/MarcusWolschon/osmeditor4android/commit/5300f0fb78aa03eb32ca2316fc8676742d22fe06 fixed IMHO most of the issues with full screen mode.

**Comment by kuba-orlik** [comment]
At first I thought that disabling fullscreen doesn't work, but changing the setting had an effect once I restarted the app

**Comment by simonpoole** [comment]
@kuba-orlik what device/Android version do you have?

**Comment by kuba-orlik** [comment]
LG Nexus 5X, Android 8.1.0 (LineageOS 15.1)

**Comment by simonpoole** [comment]
There shouldn't be any issues with full screen mode on Android 7 and later, what isn't working?

**Comment by kuba-orlik** [comment]
@simonpoole disabling fullscreen in settings doesn't take effect until the application is restarted. When I disable it in settings the app remains fullscreen, and I need to restart it in order for it to become non fullscreen

**Comment by simonpoole** [comment]
@kuba-orlik that bit was clear (and I've added a sentence to explain that to the normal docs, as it was only mentioned in the old release notes), I was just interested as to why you would want to turn it off.

**Comment by kuba-orlik** [comment]
@simonpoole oh, right. I wanted to turn them off because they obscure the action buttons and on multiple occasions I accidentally quit the app instead of opening the tag editor, for example.

BTW, maybe it would be nice to show a pop-up disclaimer informing the user that an app restart is necessary for the setting to take effect after disabling the fullscreen mode?

**Comment by simonpoole** [comment]
The system (aka Android) should show the soft buttons when a dialog or similar is shown and they then should disappear, any other behaviour is a bug (where need to be determined). If posible could you generate a video showing the issue?
