### ISSUE TITLE
Element information dialog: Align content and title

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#488]
I noticed the margin of the content of the _element information dialog_ are not in line with the title as shown in this screenshot:

![vespucci-elementinformationen](https://cloud.githubusercontent.com/assets/144518/19052406/f29d1f1e-89b6-11e6-8505-d2e4c777427f.png)

It would look better if the title and the content are aligned as described in the [Material design specs](https://www.google.de/design/spec/components/dialogs.html#dialogs-specs).

**Comment by simonpoole** [comment]
Yes there are a couple of places were this hasn't been fixed.

**Comment by johnjohndoe** [comment]
Feel free to link other places/issues here. I might have time to look into this in the near future.
