### ISSUE TITLE
Background image falls back from Bing to osm-carto

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#491]
I have no idea when this happens but sometimes vespucci does not load Bing background but loads tiles from osm.org
In the settings there is still Bing selected.

**Comment by simonpoole** [comment]
The standard style is used as a fallback when something goes wrong with the Bing imagery (loading it is substantially more complicated than any of the other sources) you could argue that we should simply show nothing, but that would be just as bad (as Bing would still be selected in the preferences).

**Comment by HolgerJeromin** [comment]
OK. What is not clear to me how could I retry Bing? Often I cannot continue my mapping plan without it.

**Comment by simonpoole** [comment]
Well for lots of places the mapbox imagery is the same and mostly better geo-referenced. Outside of that you don^t really hae a choice outside of exiting and re-starting.
