### ISSUE TITLE
Please allow removing GPS position button

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#492]
When I need goto position I want to find it in a menu. 
Right now it is in the middle of the window. 
I edited remote and instead of selecting a way I hit the GPS position icon and the view was shifted a few hundred kilometers without a possibility to get back. 
So please add "none" to the advanced option left / right.

**Comment by simonpoole** [comment]
While the enhancement is naturally possible (and easy to do), the workaround for now would simply be to quickly turn GPS off (which btw will hide the button).

Note: if you have a selected object you can use "Zoom to selection" to get back to your previous location.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/5a5b5f7f29272422ae449c33ff70d21debf349ae
