### ISSUE TITLE
No location detection when GPS is in "Battery Saving" mode

### ISSUE THREAD

**Issue by PetbkA** [MarcusWolschon/osmeditor4android#496]
If Vespucci is launched when device location detection is set to Battery Saving mode, app opens OS Location settings and locks the Follow GPS position button, instead of detecting the approximate position

**Comment by simonpoole** [comment]
Vespucci currently only uses the GPS location provider. The main reasons for this IMHO are:

- privacy (using wlan and cell reception data requires you to send your data to google or an other service provider).
- dependency on non-open code (for android devices this means dependency on google play services)
- the location data received may be tainted

For further discussion and a possible future solution see
https://github.com/MarcusWolschon/osmeditor4android/issues/273

**Comment by gdt** [comment]
It seems this should be closed as a dup of #273.

**Comment by simonpoole** [comment]
Support added in https://github.com/MarcusWolschon/osmeditor4android/commit/25929c845517912e8cc280d5f960ed3c3f1f99d1 (tracks are not possible with this).
