### ISSUE TITLE
"Directory for tiles and other files is not writeable" after update to 0.9.8r1214

### ISSUE THREAD

**Issue by lefterav** [MarcusWolschon/osmeditor4android#497]
After I updated to the version 0.9.8r1214, whenever I start the program, I get the error "Directory for tiles and other files is not writeable by Vespucci. This may be a permissions or technical issue with your device". The background map does not load. The foreground OSM map gets loaded, although it is hard to locate the map to load, since there is no background.

I tried uninstalling and installing the app. I also tried deleted all the data of the app. None of these worked

**Comment by simonpoole** [comment]
This is the same issue as https://github.com/MarcusWolschon/osmeditor4android/issues/495 and is already fixed with new builds coming asap.

**Comment by simonpoole** [comment]
@lefterav can you confirm that 1216 fixes your issue?

**Comment by simonpoole** [comment]
No response, closing.

**Comment by lefterav** [comment]
Yes, I confirm the issue has been solved after upgrading. Apologies for the late response and thanks.
