### ISSUE TITLE
wikipedia link in ElementInfo doesn't work

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#499]

**Comment by HolgerJeromin** [comment]
If I add Wikipedia link it would be great if the wikidata tag would be filled, too. 
Id does it this way, josm does it when Wikipedia comes from the addon

**Comment by simonpoole** [comment]
@HolgerJeromin that would naturally require that you have an Internet connection at the time. In any case could you open a separate feature request? Thanks.

**Comment by simonpoole** [comment]
The problem is due to an issue on WMFs side, on mobile devices http://wikipedia.org/wiki/xyz gets redirected to https://www.m.wikipedia.org/wiki/xyz which cannot be resolved (works on desktop).

**Comment by HolgerJeromin** [comment]
Ok, i probably missread the title.
Whatever, i opened #503

**Comment by simonpoole** [comment]
Workaround in https://github.com/MarcusWolschon/osmeditor4android/commit/87306783ea770a67cfbefe0263b9cddcaa4b374d
