### ISSUE TITLE
Add (or document) method to start new way from a node in an existing way.

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#506]
(Up-to-date from f-droid, CM 14.1)

In josm, I often want to start a way from a node in an existing way.  In fact, when I drew the previous way I often stuck in a node where I knew I would want to do this, even though that node wasn't needed for the first way's geometry.    I think this is just adding a + operation for this in the node selected menu.  (I tried to find this and read the docs while adding some parking lot aisles and nearby footways in my first vespucci session that added ways, tonight.)

**Comment by simonpoole** [comment]
I believe it is documented (http://vespucci.io/help/en/Introduction/#editing-with-vespucci ), but in any case: simply starting a new way at the node (long press) will do what you want (vespucci will only create a new node on the way it there is no existing node nearby).

**Comment by simonpoole** [comment]
I've added some further text in https://github.com/MarcusWolschon/osmeditor4android/commit/1f282c770d8ec17c151b425e72207d34ac796ad0 , pls feel free to add more.
