### ISSUE TITLE
Key/Value menu is confusing

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#507]
## Device (Manufacturer and Model)
Nexus 7 2013

## Android Version 
7.1.1 (CM 14.1)

## Behaviour/Symptoms
When editing tags and there aren't any (e.g., new node), and going to the details tab, I see two lines of Key/Value.  Not understanding why there are two, I click on the top key, and nothing happens.  (FWIW, I've been using JOSM since 2009.)

## Expected Behaviour
The user should understand that the top line is a label and the bottom line is where to click.

## How to recreate
Create a new node, push edit tags, and swipe to details.   Note that full reproduction requires finding a fresh user with my particular confusion each time.

## Crash dump submitted (no or yes + date)
no crash

## Any other potentially relevant information
Perhaps make the Key/Value bold, and make the line under it thicker, to make it visually obviously a title.  And dim the key/value proto-text, and make them "Key (press to edit)".

**Comment by simonpoole** [comment]
In the dark theme the header is red, so issue doesn't exist in that styling.

**Comment by simonpoole** [comment]
Tweaked styling a bit in https://github.com/MarcusWolschon/osmeditor4android/commit/25f13e55cafe6f7f5581dbe8fd1caf4dd540461c
