### ISSUE TITLE
Never add tags with +ABC function

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#508]
## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
Android 5.1

## How to recreate
Edit 
https://www.openstreetmap.org/node/316434030
current tags are:
````
addr:city	Bückeburg
addr:country	DE
addr:housenumber	1
addr:postcode	31675
addr:street	Schlossplatz
building	yes
historic	castle
name	Schloss Bückeburg
website	http://www.schloss-bueckeburg.de/
wikipedia	de:Schloss Bückeburg
````

Hit +ABC

## Expected Behaviour
Some tags are added with NO value. (very cool function BTW)

## Behaviour/Symptoms
ruins=no
is added! There is a high potential that i missed this new entry and added false information!

There are other combinations which adds key+value. I remember level=0 probaby with shops

**Comment by simonpoole** [comment]
This is purely a question of the preset and default for the value in question. ruins=no is in any case not wrong (except if you wanted to add ruins=yes). Adding default="off" will suppress the value if not checked.

See  https://github.com/simonpoole/beautified-JOSM-preset for issues etc.

**Comment by versat** [comment]
I experienced similar issues where tags with totally wrong values were added. So i am extremely careful when using this +ABC functionality or do not use it at all and i am with @HolgerJeromin that there should never be values automatically added for the tags, even when some preset suggests it. It would be nice if at least the automatically added values would be marked somehow (red font) if that is possible. Or maybe a message box with the values that would be added can pop up asking if it is ok to fill in the listed tags with the values from the preset?

**Comment by simonpoole** [comment]
"totally" wrong values is rather unlikely. It will add values from the currently best matched preset and that is displayed so you know what you are getting.

What can be an issue is that the best matched preset is wrong (will only happen in rare circumstances,  and I haven't seen this for a longish time), then obviously applying the preset is not a good idea.

**Comment by HolgerJeromin** [comment]
> "totally" wrong values is rather unlikely

"totally" in the sense of "unmatching the poi type": yes.
"totally" in the sense of "wrong related to the reality": no.

I added the [JOSM playground equipment](https://josm.openstreetmap.de/wiki/Presets/Playground_Equipment) presets.

Then i have an osm object with 
`leisure=playground`, `wheelchair=no`
Clicking `ABC+` i get 30+ new values with `=no`
For example `baby=no`, `playground:climbingframe=no`, `playground:playhouse=no`

**Comment by simonpoole** [comment]
If the preset actually behaved that way it would be broken.

checkboxes should have the disable_off="true" attribute set to avoid setting "no" values for unchecked values (other people will argue that you should be explicit about missing stuff, but that is a different topic). 

In any case the playground equipment preset actually sets the correct attribute with the exception of the baby checkbox, so you don't actually get 30 odd "no" entries, just baby=no.

**Comment by HolgerJeromin** [comment]
> so you don't actually get 30 odd "no" entries, just baby=no.

I trust my eyes more than your words! Sorry...

**Comment by simonpoole** [comment]
> The wheelchair=no makes the difference!
?

**Comment by HolgerJeromin** [comment]
Try it!
`leisure=playground` 
=> no 30+ `*=no`

`leisure=playground`, `wheelchair=no`
=> 30+ `*=no`

**Comment by simonpoole** [comment]
I tried and there isn't the slightest difference (outside of wheelchair=no)

**Comment by HolgerJeromin** [comment]
Example without third party presets:
naked `amenity=fuel` node
`ABC+`
=> 40+ entries without value (good), but one easy to miss `fuel:adblue=no` at position 36!

**Comment by simonpoole** [comment]
fuel:adblue=no that is likely an error in the preset, but nit a fundamental issue.

**Comment by versat** [comment]
I had exactly this issue with the playground preset:
https://www.openstreetmap.org/way/133669180/history
Somehow i missed that many values were set automatically to no and fixed it after a long time when i realized it.
Maybe this is fixed now, it was over a year ago.

**Comment by HolgerJeromin** [comment]
> Can you record eiether a video or a sequence of screenshots of what you are doing?

Vespucci 10.1.0-10
my preset options:
![image](https://user-images.githubusercontent.com/2410353/36225091-e09b5960-11c9-11e8-8754-1b57d7cd2229.png)
short screen capture
https://www.youtube.com/watch?v=jevdTgRMMKU

**Comment by simonpoole** [comment]
@HolgerJeromin and when did you install the preset in question?

**Comment by versat** [comment]
Another one:
For a node with entrance=main i got 6 tags (ramp, ramp:stroller, handrail:center, handrail:left and wheelchair) automatically set to "no" when clicking on "+ABC". Some others were correctly left blank.
But it only happens when the preset "Sidewalk wheelchair" is active.

**Comment by simonpoole** [comment]
As said that is a function of the preset, not anything we can do about in general without removing support for two state checkboxes completely.

**Comment by HolgerJeromin** [comment]
>  @HolgerJeromin and when did you install the preset in question?

I don't know. At least a few month ago. I had the feeling that the presets are updated automatically like josm.
After updating the preset in the settings i see the same like you. only baby=no is added.

I am still unsure if a preset should be able to add values on its own.

**Comment by HolgerJeromin** [comment]
Adding public_transport=platform via presets adds:
bin=no
Probably a bug in the preset but i am not convinced we can get all presets bug free...

**Comment by simonpoole** [comment]
The barrier=bollard is so on purpose, drinking_water and path have been fixed, please report such issues in the preset repo where they can be tracked properly. Thank you.
