### ISSUE TITLE
Add a Save button

### ISSUE THREAD

**Issue by jidanni** [MarcusWolschon/osmeditor4android#511]
It is very disconcerting to have filled in a big edit and be unable to find any Save button.

Please just add one even if it does nothing.

**Comment by jidanni** [comment]
Okay I figured it out. But maybe in the menus have a Save item that does two things as a shortcut. That is, closes edit mode and uploads the stuff.

**Comment by simonpoole** [comment]
@jidanni could you explain a bit more exactly what workflow you would like to have?

The typical workflow we currently support is

- download data
- make a change (for example move a node)
- make a change (change some tags)
- make a change (add a POI)
....
- upload data

If you are referring to the property editor, exiting the "screen" the standard android way (button in the top left corner) will "save" your changes to the  current downloaded data on the device. To publish to the OSM database you need to upload. See http://vespucci.io/help/en/Introduction/ or the same text on your device.
