### ISSUE TITLE
Background Contrast Value on ProgressBar does not change

### ISSUE THREAD

**Issue by daveo30** [MarcusWolschon/osmeditor4android#513]
Background Contrast progress bar resets to default value as soon as the Dialog closes. The Background Contrast changes but progress bar stays at default value.

Expected behaviour- Progress bar reflects current contrast value. 

Android Version 7.0

**Comment by daveo30** [comment]
Minor Issue which I just wanted to fix. 
@simonpoole Please let me know if I should continue

**Comment by simonpoole** [comment]
Pls feel free to fix. Note that, probably not for the next version, I want to re-jig how we handle the imagery layers from a configuration point of view (store the parsed configuration details in a DB instead of in memory).
