### ISSUE TITLE
Isolated nodes when creating paths

### ISSUE THREAD

**Issue by saraedum** [MarcusWolschon/osmeditor4android#516]
## Device (Manufacturer and Model)
Samsung Galaxy Alpha (aka G850F)

## Android Version 
Custom ROM ResurrectionRemix M 5.7.1-21060711

## Behaviour/Symptoms
When creating paths through the presets button, an extra isolated node gets created at a seemingly random locations.

## Expected Behaviour
Just the path should be created.

## How to recreate
1. Unlock the map
1. Create a path (long touch the map and the touch it again somewhere) with two nodes
1. Click the presets button

Now, before the interface changes to select a preset for this path, an extra isolated node gets created somewhere.
Often the node is not within the displayed area of the map but I can tell that it got created because afterwards the undo button does an "undo: insert" but does not remove my path.

## Any other potentially relevant information
What works is the following:
1. Unlock the map
1. Create a path as before
1. Click the ← button to create the path
1. Swipe left to get  to the presets page.

**Comment by simonpoole** [comment]
@saraedum which vespucci version are you using? I wasn't able to recreate the behaviour with 0.9.9. In any case could you recreate the issue and then display all undo information by long pressing the undo button (a screen shot would be nice).

**Comment by saraedum** [comment]
My version is 0.9.8r1228. The attached screenshots show the extra node and the undo list.

![screenshot_20170210-164802](https://cloud.githubusercontent.com/assets/373765/22845468/d4b8c1b4-efb0-11e6-9e65-2a461f938792.png)
![screenshot_20170210-164813](https://cloud.githubusercontent.com/assets/373765/22845469/d4bc1b0c-efb0-11e6-963c-564c844e6435.png)

**Comment by saraedum** [comment]
Can I find an apk for 0.9.9 somewhere already?

**Comment by saraedum** [comment]
Never mind, found it on the google drive.

**Comment by simonpoole** [comment]
I won't be able to test again 0.9.8 before Sunday, IIRC there were some changes in the relevant code for 0.9.9 so it may be possible to backport a fix for the issue.

**Comment by simonpoole** [comment]
Tentatively fixed for 0.9.8 in https://github.com/MarcusWolschon/osmeditor4android/commit/a15b77179dc710270e4a396432a1681cd15e03d7 for 0.9.9 in https://github.com/MarcusWolschon/osmeditor4android/commit/96798c002d873b44c814122a99784185922c8126

A new beta build (1230) incorporating the fix is available on google drive.

@saraedum could you test if your issue has now gone away, from a code pov there was some brokenness that could have caused your issue, however I couldn't directly reproduce is in either branch.

**Comment by saraedum** [comment]
@simonpoole: Thanks. It seems that this fixed it. I tried a few times and could not reproduce the problem anymore.
