### ISSUE TITLE
Add Exit button

### ISSUE THREAD

**Issue by prescott66** [MarcusWolschon/osmeditor4android#517]
I have device with software buttons(back,home,context) and i am very confused when trying to exit Vespucci.
It would be nice to have Exit button in context menu - besides the menu items: Tools, Find, Help

**Comment by simonpoole** [comment]
Both HW and SW back buttons exit vespucci, could you explain what the actual confusion about that is? Naturally we can duplicate standard Android UI elements again and again, however it would seem to not make a whole lot of sense.

**Comment by prescott66** [comment]
i mean that SW buttons are not visible.that is confusing because you cant press back button if you dont see it 😄

**Comment by simonpoole** [comment]
Well you can:

- turn full screen mode completely off

or 

- swipe from the bottom to make the buttons visible

How well the later works depends on the Android version and the maker of your device.

**Comment by simonpoole** [comment]
ping @prescott66 (see above)

**Comment by osmvermesser** [comment]
i would even like to have exit-button because my tablet is very difficult to end vespucci.

jan

**Comment by matkoniecz** [comment]
I have no experience with varied devices but it seems that "exit app" actions is typically handled by system-level interface.

Also, given that interface is already quite cluttered value of adding button for standard action that no/nearly no app has seems to be a poor idea.

**Comment by simonpoole** [comment]
No more feedback from original poster, closing.
