### ISSUE TITLE
Selection of motorway_link and motorway not visible 

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#518]
Selecting a way gives a different color on the map. But with motorways this highlighting is nearly invisible.

**Comment by simonpoole** [comment]
The width of both the selection and the object are style-able, potentially the selection style should be per object style or similar. See https://github.com/MarcusWolschon/osmeditor4android/issues/312 too.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/39b91ab13648df1584c43746bece553c529a8c6b
