### ISSUE TITLE
Multi selection should print the selection count somewhere 

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#519]
When multi selection I have a nice info of the tags:
Highway = footway (2)
Highway = service (3)
But I don't know how many ways I selected. 5 or 6?

This should be added in the tag editor and the map view. 

Thanks

**Comment by simonpoole** [comment]
On the main screen this is easy, in the property editor there is no obvious place to put such a notice

**Comment by HolgerJeromin** [comment]
`highway=footway (2 of 3)`
Not really nice 8-/

**Comment by simonpoole** [comment]
Unluckily that solution, while seeming simple, is really really messy to implement in practice.

https://github.com/MarcusWolschon/osmeditor4android/commit/020f076ad023d6bb5bec9bc225c82df34d1e4d77

Adds a count in the multi-select mode.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/5d512cb1ef3081d235d705ae9986d8ea09ae6853
