### ISSUE TITLE
Auto download does not work 

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#520]
If I checked auto download I thought that the editor should download osm data while panning the map into new regions. (even while multi select?) 
But nothing happens. 

Vespucci 0.9.8r1228

**Comment by simonpoole** [comment]
As the documentation says http://vespucci.io/help/en/Main%20map%20display/#available-actions "Auto download - download an area around the current location automatically (requires network connectivity) (requires GPS)". 

This is mainly support for surveying, a scroll/pan around continuous download a la iD or P1/P2 has a number of issues on mobile devices on top of the problems iD already has with it. Please feel free to a request for a new feature if you believe that it would be really useful.
