### ISSUE TITLE
Tag edit mode should allow multi select 

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#522]
I often only add tags like lit=*. I do not want to modify the geometry so the tag edit mode is nice. 
But I cannot select multiple ways, so I do not use this mode for lit adding.

**Comment by simonpoole** [comment]
This is a bit of a UI dilemma because the whole concept of the tag-editing mode is that you can immediately edit the tags of the selected object. But it definitely isn't impossible.
