### ISSUE TITLE
OAuth issues with master.apis.dev.openstreetmap.org for Android

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#523]
Retrieving the access token (well actually it fails already when trying to retrieve the request token) fails likely due to SNI not being supported in earlier Android versions.

While this has no immediate impact for normal users (it just impacts testing) it does mean that OAuth will break if OSM ever starts using SNI for the main website.

**Comment by HolgerJeromin** [comment]
SNI is supported in Android 4 according to 
https://www.ssllabs.com/ssltest/analyze.html?d=master.apis.dev.openstreetmap.org

**Comment by simonpoole** [comment]
supported != supported
According to google you've been able to use it in one way or the other since Android 2.something, however at least for early version use was not automatic and only for some libraries, as already said the issue is specific to the OAuth handshake not to browsing.

**Comment by simonpoole** [comment]
Tentatively fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/3cba894a4e80db47f847c5093ffad5829d42c6a7

My current understanding of the issue:
- the OAuth lib (signpost) doesn't use the standard java HttpUrlConnection on android because that causes issues
- we use  the apache httpclient instead, which was included with android up to 5.1.1
- the version of httpclient that was included both in the SDK and the android on device runtime is -old- and doesn't support SNI
- in 6.0 google removed httpclient from the SDK, but left it in the runtime
- with the result that you always pick up the old version of httpclient on device
- fix is to a) use a version of httpclient with different package names and b) modify the OAuth lib to use that instead of the on device one

Long term fix may be to move to a different OAuth lib ( https://github.com/scribejava/scribejava may be a viable alternative).

**Comment by HolgerJeromin** [comment]
Thanks for explaining!

**Comment by simonpoole** [comment]
The workaround doesn't work (yet) on Android API 8/ Android 2.2 (the oldest we support), see https://github.com/smarek/httpclient-android/issues/15

**Comment by simonpoole** [comment]
Given that we are dropping 2.2 support with this version, I'm closing this now.
