### ISSUE TITLE
Enable proguard?

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#529]
@MarcusWolschon @johnjohndoe 

Any arguments pro-con running proguard on the app? It currently shaves 2MB off the size of the release apk (not quite 30%). There are currently a couple of warnings that would need to be investigated before release so a bit of work that I would avoid if using proguard doesn't make sense.

See https://github.com/MarcusWolschon/osmeditor4android/commit/0ada5a81a0e73d7a8a90cd4ebe9685a7ba54a586

**Comment by johnjohndoe** [comment]
Smaller apps are always welcome. I understand that it would be a bit of work and maybe risky. The latter however could be minimized by using the **beta channel** or/and **staged rollouts** in Google Play.

**Comment by simonpoole** [comment]
While I'm not totally convinced, enabled in https://github.com/MarcusWolschon/osmeditor4android/commit/7f0a2f7b55c1468a428308ce7a59fdae2edb0284

**Comment by johnjohndoe** [comment]
:+1: I recommend executing automatic release builds (with some dummy keystore) on the CI if you haven't set this up already.
