### ISSUE TITLE
Validate preset after downloading 

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#530]
When you insert this URL you get no error. But the preset does not work:

https://josm.openstreetmap.de/wiki/Presets/Playground_Equipment
The message says: downloaded successful

**Comment by simonpoole** [comment]
Well the download is successful ... however what you downloaded was the JOSM wiki page, which causes the parser to fail and not enable the preset (yes it likely should pop up a dialog when that happens).

The download link is https://josm.openstreetmap.de/josmfile?page=Presets/Playground_Equipment&zip=1

**Comment by simonpoole** [comment]
An error message was added in https://github.com/MarcusWolschon/osmeditor4android/commit/6a584fe183c3c8f1b1fcc9df2a986edbce029040
