### ISSUE TITLE
Specify default folder for importing tracks

### ISSUE THREAD

**Issue by DFyson** [MarcusWolschon/osmeditor4android#532]
It would be nice to have an option to specify a default folder for importing tracks from. For example I frequently use OsmAnd to record tracks then later import them in Vespucci and would like it to start in the /emulated/0/osmand/tracks/rec/ folder.

**Comment by simonpoole** [comment]
Would it be good enough if simply the last location you imported from was stored and re-used. Adding yet another preference to the settings should be avoided if possible.

**Comment by DFyson** [comment]
Ya, that would be even better.

**Comment by simonpoole** [comment]
Done in https://github.com/MarcusWolschon/osmeditor4android/commit/b8ab55a83b0ed650e85475ed7575ff4b24b73959

A beta of 0.9.9 should be available rsn.

**Comment by DFyson** [comment]
thanks! that speeds things up
