### ISSUE TITLE
Share map position with other apps

### ISSUE THREAD

**Issue by DFyson** [MarcusWolschon/osmeditor4android#533]
Occasionally when editing an area other than the current location, I want to open up that same area in another mapping app such as OsmAnd. It would be nice if the current map position/zoom could be shared using the standard geo URI. Maybe 'location' → 'share position' menu? I could imagine copying the coordinates to clipboard would be useful too. So maybe a standard press would trigger geo uri intent and long-press would copy to clipboard.

**Comment by simonpoole** [comment]
What is the "current map position" supposed to be exactly? Center of the screen?

**Comment by DFyson** [comment]
ya, exactly, the coordinates of center of screen and the zoom. There isn't really any point of sharing the current GPS location since you can just jump to it on the screen then share it.

**Comment by HolgerJeromin** [comment]
Yes, i needed it once. 
Right now the only way if found is to open the history of an object and then use the geo url from osm.org :-)

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/6bb505549b1684c63c459673c8ea489e34585408 besides sharing the center of the map, if an object is selected the position shared is the centroid of the object.

**Comment by DFyson** [comment]
Thanks, that's awesome!

The position of a selected object isn't quite right when shared.
For example node [4356187741](http://www.openstreetmap.org/node/4356187741) is at 45.4234415, -75.6961515 in OSM. But in Vespucci, it shares it as 8.00000, -7.56962. The the longitude is just off by a decimal place, not sure about the latitude.

**Comment by simonpoole** [comment]
It works for ways, and for the map position for nodes, I forgot the scaling, fixed in: https://github.com/MarcusWolschon/osmeditor4android/commit/5a3b400f38a619999392bd37bca34bd1287b9609
