### ISSUE TITLE
Auto-correction days in opening_hours

### ISSUE THREAD

**Issue by osmvermesser** [MarcusWolschon/osmeditor4android#540]
normally days in opening_hours and other time-tags days will writen like Mo-Fr....

if the mapper makes mistakes like mo-fr it would be good to habe autocorrection.

german: es wäre eine Autokorrektur bei der Schreibweise von Tagen wünschenswert und würde die Erfassung an mobilen Geräten vereinfachen.

**Comment by simonpoole** [comment]
The opening hours editor will actually do that when it gets merged at last.

**Comment by simonpoole** [comment]
Done in https://github.com/MarcusWolschon/osmeditor4android/commit/e7f9e38428f8c04c0026041d0eaf95c18f6d6789
