### ISSUE TITLE
Show current position on openstreetmap.org

### ISSUE THREAD

**Issue by osmvermesser** [MarcusWolschon/osmeditor4android#548]
When activate the Funktion "share Position" i will be ask to open an other application like OSMAND.

I would prefer to open the osm-map in the location or alternative to put the coordinates info clipboard.

**Comment by simonpoole** [comment]
Currently the "share position" function simply tries to "open" a geo-url (geo:.....) browsers are unlikely to register for that (and even if they did, they would likely open gmaps), so this would need need a separate function to work reasonably.

The same goes for the the request to copy the coordinates to the clipboard. The system clipboard can only hold one item at a time, anything that copies there needs to be clearly labelled to avoid inadvertently overwriting existing contents.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/047a1d1d76e67816ca8b82bf61a038501af6ec96 adds an activity "Share on OpenStreetMap" that will listen to all geo Intents and if selected will open openstreetmap.org at the specified
![screenshot_1544016155](https://user-images.githubusercontent.com/1011860/49516171-43718d00-f899-11e8-84c0-41e0ea09c80f.png)
 position.
