### ISSUE TITLE
Add way to clear whole tile cache

### ISSUE THREAD

**Issue by gdt** [MarcusWolschon/osmeditor4android#550]
This suggestion is based on 0.9.8.1.1242-fdroid, CM 14.1, Nexus 7.

I did a separate adb backup of every app, and vespucci's backup was one of the larger, close to 100 MB.   I unpacked it and looked inside, and it's almost all tile cache.  That's fine, but I'm trying to make my backup smaller because the full "adb backup" is failing for reasons I don't understand (and are almost certainly not a bug in vespucci).

This led me to try to clear the cache.    I did "flush background tile cache", which shrunk things some, but the tile database was still large.   This is documented to clear only the current layer, and presumably that's to force getting fresh tiles or to recover from bad ones, not for cache management.  So I would like a "clear tile cache" option, and it can be in the same wrench menu.   I used the "rm" method of clearing the cache on my device, and then the uncompressed backup tar was 7.3M.

(Really I would like a global Android action to send a flush cache intent to all apps, running or not, but that's beyond the scope...)

**Comment by simonpoole** [comment]
Your observation is correct that only the cache for the current layer is flushed and, yes the intent is to essentially force a refresh. But obviously it is not an issue to add a function to clear the cache for all layers. The alternative is to simply delete the sqlite DB that holds the tiles.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/5eed17327a67ea6cfae4b8a666196f7105c7c954
