### ISSUE TITLE
Completely unclear error message on failed upload

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#556]
## Device (Manufacturer and Model)
Redmi 4 Xiaomi

## Android Version 
6.0.1 MMB29M

## Behaviour/Symptoms
On upload I got message "Some or all data was not uploaded. Try uploading again later if this was only a temporary problem."

## Expected Behaviour
I get explanation why upload is impossible so I can diagnose it (may be optional to not scare nontechnical users)"

For example "edit conflict", "internet connection missing", "OSM editing API is unavailable", "Vespucci upload code crashed" etc.

Also "Try uploading again later if this was only a temporary problem" is irritating as user has no idea whatever it is temporary problem, one is forced to try again and again anyway as it is the only available solution.

## How to recreate
No idea as error message gives no useful information to diagnose.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
(optional)

**Comment by matkoniecz** [comment]
From reading code - it is upload_problem_message message code.

It is triggered at https://github.com/MarcusWolschon/osmeditor4android/blob/5757a03b1474c090f909cb1077a207202856138a/src/main/java/de/blau/android/tasks/CommitTask.java#L85

for 

			case HttpURLConnection.HTTP_BAD_REQUEST:
			case HttpURLConnection.HTTP_NOT_FOUND:
			case HttpURLConnection.HTTP_INTERNAL_ERROR:
			case HttpURLConnection.HTTP_BAD_GATEWAY:
                        case HttpURLConnection.HTTP_UNAVAILABLE:

It seems that it should be expected for spotty or missing internet connection, but problem persists while other apps happily use Internet.

Maybe vespucci malforms edit request or is unable to handle (or even report) edit conflict?

**Comment by matkoniecz** [comment]
Hm, at least error message for edit conflict exist so...

It would be helpful to at least give http error code.

**Comment by matkoniecz** [comment]
For now (today?) I will keep data in Vespucci (fortunately it was nothing hard to recreate), in case that it would be helpful to diagnose what is going wrong.

**Comment by simonpoole** [comment]
1. please save your edits to a file (if we can't resolve the issue you can then always simply use that with JOSM).
2. as you've noticed already you get that error message when there isn't much else to say, other error cases are already handled in detail (for example with conflict resolution), but likely less flaky Internet connection, more issues with the API server.
3. can you state the vespucci version you are using? (top of the advanced preferences or on the debug information screen which is reachable via an entry at the bottom of the first preference screen),
4. can you determine if you are trying to upload over a mobile network or over wlan?
5. please check what API entry (advanced preferences) is being used for your connection (only switch them if you did (1))

**Comment by matkoniecz** [comment]
1) Maybe mention that in error message?
2) Maybe it is possible to distinguish between lack of any response (missing Internet or serious problem with editing API) and edit refused by server?
3) 0.9.8r1242
4) wlan (mobile network was disable entire time, I downloaded data over wifi, editined without internet connection and after retunrning home I attempted to upload over wifi)
5) OSM API URL is set to the first position, I never changed it and it matches https://github.com/MarcusWolschon/osmeditor4android/blob/7d746dba8776d97d0be8a88e6e487ddaf9e9172d/src/main/java/de/blau/android/contract/Urls.java#L8

**Comment by matkoniecz** [comment]
Upload failed also after saving, changing to http API, loading file and trying to upload, with the same message.

**Comment by matkoniecz** [comment]
Something weird is going on. After loading this file in OSM some bicycle parking nodes are displayed at 0,0 (in the middle of the ocean).

Is it possible that Vespucci lost some data because it was not in the foreground or because it was kicked from memory by Android?

File saved by Vespucci: https://gist.github.com/matkoniecz/74489c730817e0ca131f07ef64d57b80

**Comment by matkoniecz** [comment]
It is even weirder - bugged node is not displayed at 0,0 - but JOSM validator claims that it is there and selecting object over 0,0 catches it. 

But JOSM is not displaying its icon.

**Comment by matkoniecz** [comment]
I added prettified xml to the gist.

Asssuming that latitude is in degrees - that part makes absolutely no sense:

```
<node id="-7" action="modify" version="1" visible="true" lat="100.1688476" lon="39.7647151">
    <tag k="amenity" v="bicycle_parking"/>
    <tag k="bicycle_parking" v="stands"/>
    <tag k="capacity" v="8"/>
    <tag k="covered" v="no"/>
    <tag k="operator" v="ZIKiT"/>
</node>
```

**Comment by simonpoole** [comment]
Android apps are constantly removed from memory, saved, restarted and so on that definitely is not a general issue. Why the node has "interesting" coordinates is a good question.

I assumed you created the node via a long press? And is it displayed in the correct position?

Is that the only node with an error (you can dump the data to an OCS file which is easier to check).

**Comment by matkoniecz** [comment]
> I assumed you created the node via a long press? 

Yes. But I was trying to copy/paste tags - maybe it copy/pasted node?

> And is it displayed in the correct position?

Yes, though it is possible that I missed something.

> Is that the only node with an error (you can dump the data to an OCS file which is easier to check).

I se also

```
<node id="-8" action="modify" version="1" visible="true" lat="100.1688476" lon="39.7647151"/>
```

and

```
<way id="-3" action="modify" version="1" visible="true">
    <nd ref="-7"/>
    <nd ref="-8"/>
</way>
```

**Comment by matkoniecz** [comment]
And returning to the original problem - I am guessing that API refused edit (I prefer to not test it to avoid creating invalid node). Maybe it deserves a special error message, maybe combined with sending report that something went really wrong?

**Comment by simonpoole** [comment]
Yes I checked the data too, nodes -7 and -8 are affected node -9 is ok again. Can you remember if you copy pasted the way? It might be a bug somewhere in the positioning code there (however it then shouldn't display in the correct position).

**Comment by matkoniecz** [comment]
I was not trying to copy-paste the way (I was adding only nodes), but it is possible that I did it without trying.

**Comment by simonpoole** [comment]
Note on the side: to copy & paste tags only you need to do that in the property editor. In any case given that we've narrowed the problem down a bit, I'll get back as soon as I have more information.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/a2b7529c046d5a2434de55f8f74683f4220f0085 addresses the issue with displaying a "better" message on a 400 response.

Could you rack your mind again wrt what you were doing and how you tried to do it when you created that bicycle_parking? I've tried a an hour or so now to recreate such a situation with no "success"  so there is likely something that I'm missing.

**Comment by matkoniecz** [comment]
Maybe adding also asserts to detect appearance of nodes with completely invalid ids would be a good idea? It would also make reproduction attempt easier as immediately after problematic action there would be indication that something went wrong.

**Comment by matkoniecz** [comment]
What I was doing - I created note, locked phone, edited with StreetComplete. Later I added nore that glued itself to existing landuse, I unglued it and moved, added two more nodes. During this I unintentionally created at least one way - and I used undo to get rid of it. I locked phone again and attempted upload.

**Comment by simonpoole** [comment]
None of the ids was invalid, that is a misunderstanding, every editor uses negative ids as a placeholder for new objects, The placeholders are then replaced on upload with the new ids returned by the API. 

The thing that is wrong with the two nodes is that the coordinates are out of range, which indicates that an internal operation went wrong (as you can't generate invalid coordinates via the UI). Can you remember if you tried to paste at any point in time you initially mentioned that?

BTW to complete the upload of your data you simply need to remove way -3 and node -8 from the file and set the coordinates of node -7 to half of what they currently are (the last is a guess but likely seems to be right).

**Comment by matkoniecz** [comment]
I know that negative ids were OK and that only ```lat="100.1688476"``` was invalid.

> Can you remember if you tried to paste at any point in time you initially mentioned that?

Yes, I tried this and noticed no effect of that action (I tried copying bicycle parking node before ungluing it from landuse).

**Comment by matkoniecz** [comment]
> BTW to complete the upload of your data you simply need to remove way -3 and node -8 from the file and set the coordinates of node -7 to half of what they currently are (the last is a guess but likely seems to be right).

Thanks!

**Comment by simonpoole** [comment]
Wrt copying: that creates a new object with the same tags that can be pasted many times, you likely wanted to cut the node from the landuse way which will remove the node and allow you to paste it back somewhere else (as it is the same node that only works once). The other possibility is to use the extract node function (which leaves a new node in place).

**Comment by simonpoole** [comment]
I've found the problem that you have ran in to... 

Somehow you managed to create a way with length 0, aka start and end node are in the same position (the way -3), you either copied or cut that way. Now the problem is when you do that for a way it calculates a way center or centroid if the way is closed so that it can position the way correctly when you paste it. That doesn't give a sensible result if the way has length or area 0.

In 0.9.8 the condition wasn't caught correctly and that is why pasting the way created way off coordinates. I'll likely backport the code from 0.9.9 looking at that now.

**Comment by simonpoole** [comment]
The C&P fixes have been backported in https://github.com/MarcusWolschon/osmeditor4android/commit/1139051dd5b6036c44d8e3f38d3a888124420db8

**Comment by matkoniecz** [comment]
Thank you for fixing multiple aspects of this bug!
