### ISSUE TITLE
suggest recently/frequently used keys/values

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#557]
During my editing I use small set of tags. JOSM behaviour where recently used tags are suggested is very useful in such situation.

Currently Vespucci is showing possible keys/values in alphabetical order. Maybe at least part of that list may be reserved for popular/recently used keys/values?

**Comment by simonpoole** [comment]
Related to https://github.com/MarcusWolschon/osmeditor4android/issues/439

**Comment by simonpoole** [comment]
Support added in https://github.com/MarcusWolschon/osmeditor4android/commit/e2ae9087a4a717f373bc96b61afa38cac438d73e
