### ISSUE TITLE
use word prediction for freeform tag values

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#559]
For example for operator, name etc it would be nice to be able to use keyboard predictions. Changeset description text box currently has word prediction enabled.

**Comment by simonpoole** [comment]
What is addr:at supposed to be? 

In general I would prefer using normalized values as we already do for the name tag and not to run the risk of spelling checker induced errors.

**Comment by matkoniecz** [comment]
> What is addr:at supposed to be?

It was not supposed to appear, sorry (it is now removed).

> normalized values

It is proposing to reuse existing ones available in downloaded region, right?

**Comment by simonpoole** [comment]
No we use the same system as iD (see https://github.com/osmlab/name-suggestion-index ) which generates a list of (name) values from the whole planet and normalizes them (it does have a bit of a conceptual issue when proper nouns in one language are being used as names in a different one, but outside of that works OK). There is no reason we couldn't use it for operator too.

**Comment by matkoniecz** [comment]
It would be great! I wonder about practical effects, I guess that I should try editing in iD to check how suggestions for operator would work.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/59849a703023d6cd08500150407349b956a7f31f
