### ISSUE TITLE
list available Vespucci presets

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#561]
On entering "Presets" in settings there is no clear way to add presets. On clicking "add preset" one is supposed to provide Name and URL.

Typical user will have no idea what URL is supposed to be added there. It would be preferable to display list of available presets.

**Comment by simonpoole** [comment]
This is explained in the on device and online help: http://vespucci.io/help/en/Presets/

**Comment by matkoniecz** [comment]
I know, but it would be better to display list of presets (like it is done in JOSM).

And even after reading http://vespucci.io/help/en/Presets/ I still have no idea what URL I am supposed to provide (and currently I am trawling through JOSM website).

**Comment by simonpoole** [comment]
That would currently boil down to scraping the JOSM site (and possibly morphing the links) and/or having an own list.

**Comment by simonpoole** [comment]
Clarified how to add Preset from JOSM list in https://github.com/MarcusWolschon/osmeditor4android/commit/3e60c419f349cdb5aa62644b72bf6a657be39649
