### ISSUE TITLE
mention in documentation how one may locate presets

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#562]
#561 is a very big feature request - but maybe it would be possible to at least mention at http://vespucci.io/tutorials/presets/ where one can find JOSM presets?

I thought about something like

> Typical way to obtain preset is to use one made for JOSM. Go to https://josm.openstreetmap.de/wiki/Presets Names of presets link to archive files. Copy that URL into "Add preset" window in Vespucci preferences. You may select any name in "Add preset" window.

**Comment by matkoniecz** [comment]
In case that something like that would be OK I may make PR to change https://github.com/MarcusWolschon/osmeditor4android/blob/eb493ca0c57c1b160efbeb5b69ebb1e6265ddb33/documentation/docs/tutorials/presets.md

**Comment by simonpoole** [comment]
The documentation already mentions the location in http://vespucci.io/help/en/Presets/ (in the repo https://github.com/MarcusWolschon/osmeditor4android/blob/master/documentation/docs/help/en/Presets.md ) any text improvements should be made there (and they are welcome). The page you are referencing is not available on device and is not really directed at joe user that wants to load an additional preset in any case.

**Comment by simonpoole** [comment]
I believe this is already covered in the mentioned on-device and website documentation.
