### ISSUE TITLE
Don't try to connect to GPS when called from other app by "share position" (geo:.....) 

### ISSUE THREAD

**Issue by pebogufi** [MarcusWolschon/osmeditor4android#563]
When opened by an other app (ex. osmand) with "share position" (geo:.....) 
Don't try to connect to GPS. There is no need for in this situation and it is only annoying.
## Vespucci Version
0.9.8.1.1242

**Comment by simonpoole** [comment]
Could you detail what you mean by "connect to GPS" and why it is annoying?

**Comment by pebogufi** [comment]
The app needs a gps info and starts system to switch gps on. But in the case when Vespucci is called with gps coordinates this is not necessary and nothing good for.

**Comment by simonpoole** [comment]
@pebogufi are you using a device that has GPS turned off? Because if not then I don't quite see the issue. The moment I disable GPS in the scenario somebody is sure to complain that they want it on, requiring at leas a manual way to re-activate GPS.

**Comment by pebogufi** [comment]
Of course most time gps is switched off, due to saving battery. I only switch it on, if I need it for navigating (osmand) or very few other purposes. If I see new POIs I set a marker in osmand for later editing. For doing edits for osm it is not needed most times, because I have the position. (I don't stand in front of a cafe to make edits in Vespucci, such edits are done later... )
Peter

**Comment by simonpoole** [comment]
There is an advanced preference setting "Leave GPS disabled" that leaves GPS off when it is turned off, I've not tested it for your use case, but it might fit the bill.

**Comment by simonpoole** [comment]
@pebogufi ping, it would be good if you could conform or not if the above mentioned setting addresses your issue or not.

**Comment by pebogufi** [comment]
@simonpoole Are you MarcusWolschon ?
---
I think you talk about a different topic that I mean.

I try again to explain again what I mean:
When Vespucci is opened by an other app (ex. osmand) with "share position" (geo:.....), then it has already a geo position to work with. In this case it is nonsense to use the system gps functionality to fetch the CURRENT gps position, which may be dozends or hundreds of kilometers away from the position the user wants to work with. So it is only waste of battery and nothing good for. In this case fetching CURRENT gps position should be switched off.
Peter

**Comment by matkoniecz** [comment]
@pebogufi 

I can easily imagine somebody opening Vespucci from other app and expecting to see marker of the current position. Or intending to later use "move me to the current position".

**Comment by pebogufi** [comment]
> ...Or intending to later use "move me to the current position".
Then they can use the function  "go to current position" (gps double circle).
Peter

**Comment by simonpoole** [comment]
@pebogufi obviously I'm not Marcus. 

Your request in clearer now, I'll have a look if the behaviour can be changed without too much fiddling.

**Comment by simonpoole** [comment]
Addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/20858a0a713f8f0a31af2d5c79d030c52cf753d1
