### ISSUE TITLE
Copy all keys:tags

### ISSUE THREAD

**Issue by fatuuse** [MarcusWolschon/osmeditor4android#564]
## Vespucci Version
0.9.8r1242

I request an option to copy all keys:tags from one object (node/way) to paste it in an other object. Now you could only copy one pair of keys in groups.

**Comment by HolgerJeromin** [comment]
On the details screen you have the raw tag edit which allows selecting (and afterwards copy) all tags.

**Comment by fatuuse** [comment]
Thx. I missed the select button.


--- Ursprungligt meddelande ---
Från: Holger Jeromin <notifications@github.com>
Datum: 18 maj 2017 10:28:30
Till: MarcusWolschon/osmeditor4android <osmeditor4android@noreply.github.com>
Kopia: erik <fisensmosse@gmail.com>, Author <author@noreply.github.com>
Ämne: Re: [MarcusWolschon/osmeditor4android] Copy all keys:tags (#564)
