### ISSUE TITLE
allow moving presets on the list of presets

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#565]
I want to

- have a quick preset for adding things that I typically edit (so I can tune it manually)
- use standard presets for less frequent editing and map styling (maintained as part of the Vespucci editor/JOSM/whatever is the source of default preset)
- have my quick preset at the start of list in "Presets" tab on editing objects

At this moment the first two are doable but I see no way to change order of presets in Preferences | Advanced preferences | Presets.

As result I need to do one of following

- scroll through standard presets every time I want to do my typical edit
- disable standard presets and be without map styling and tag help on less typical edits
- disable default preset, replicate it (find its source) and keep it synchronised with real source of preset

The same issue will appear in slightly different situation with multiple presets - lets say that somebody has N presets. To add new one before them it is necessary to delete all of them, add new one and readd all that existed before.

**Comment by simonpoole** [comment]
> disable default preset, replicate it (find its source) and keep it synchronised with real source of preset

This is actually trivial and the recommended way to achieve what you want at this point in time, just click (on device) on the first link on this page http://simonpoole.github.io/beautified-JOSM-preset/

**Comment by simonpoole** [comment]
Added (ugly but works) in https://github.com/MarcusWolschon/osmeditor4android/commit/89bb7394731c693ca03173c3fb8061e3660ab70b
