### ISSUE TITLE
notes/bugs clear is not working

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#567]
## Device (Manufacturer and Model)

Redmi 4 Xiaomi

## Android Version

6.0.1 MMB29M

## Vespucci Version

0.9.8r1242

## Behaviour/Symptoms
Using clear on notes/bug menu is not doing anything

## Expected Behaviour
Bugs (yellow and green bug icons disappear)

## How to recreate
For me - use clear on notes bugs menu

## Crash dump submitted (no or yes + date)
No

**Comment by matkoniecz** [comment]
What kind of clarification is needed? What is supposed action on using clear in "notes/bugs" available through download/upload menu?

Would it be helpful to record what is happening on the screen?

**Comment by simonpoole** [comment]
As already pointed out the problem was IMHO fixed in 0.9.9 which simply needs to be verified.

**Comment by matkoniecz** [comment]
Great, ;in that case I am waiting for a new version. BTW, it seems that either I missed something or something went wrong because I completely missed before "already pointed out the problem was IMHO fixed in 0.9.9"

**Comment by simonpoole** [comment]
@matkoniecz sorry, I probably simply didn't actually press the comment button :-/ Anyway to recap: I can't recreate the issue in 0.9.9 and I remember fixing it a while back, but for some mysterious reason I embarrassingly haven't been able to pinpoint the commit, which is why I left the issue open for now.

There is in any case no real reason to not use 0.9.9 beta from the Play Store and more feedback and testing would be welcome.

**Comment by matkoniecz** [comment]
>  0.9.9 beta from the Play Store

Is it supposed to be available using method described at https://support.google.com/googleplay/answer/7003180?hl=en ? Because I see no option at app page to join beta testing.

AFAIK something like that would be displayed:

![jlqj3zvf2utx8ou3vahr](https://user-images.githubusercontent.com/899988/27030835-080bc116-4f6e-11e7-852c-67a43881b0bc.jpg)

**Comment by simonpoole** [comment]
@matkoniecz yes it should be available via the beta program.

@MarcusWolschon can you check if the beta stuff is still working?

**Comment by simonpoole** [comment]
Note: the apk available from "releases" on this site should be identical with the one available from the PlayStore (naturally enrolling in the beta program should still work).

**Comment by simonpoole** [comment]
@matkoniecz can you check if you can get the beta now?

**Comment by matkoniecz** [comment]
Unfortunately no. Maybe it will appear a bit later?

**Comment by MarcusWolschon** [comment]
Formerly the beta version was older then the production version. So nobody got the beta anymore.

Now there is a Beta 0.9.9.0.1286 rolled out to everyone.
It's newer then the 2 production versions:

20% of the users already have the production version 0.9.8.1.1285 (automatic, staged rollout).
80% still have the production version  0.9.8.1.1242 and are slowly upgraded to the current one or the Beta.

So everyone in the Beta program should see the 0.9.9 with version code 1286.

**Comment by matkoniecz** [comment]
Clearing bugs now works in version available from Play Store.

I still see no option to join beta.

**Comment by simonpoole** [comment]
Seems as if the "open beta testing" setting got reverted back to the old google group one, that is why it wasn't working.

@matkoniecz can you check icf you can get the beta now?

**Comment by matkoniecz** [comment]
> can you check icf you can get the beta now?

Now it works.

As now both discussed issues are fixed I will close this ticket.
