### ISSUE TITLE
Padlock won't stay white, so cannot edit

### ISSUE THREAD

**Issue by MikeParfitt** [MarcusWolschon/osmeditor4android#572]
## Vespucci Version 
0.9.8r1242
## Device 
Samsung Galaxy Tab S2 model SM-T715
## Android Version 
7.0
## Symptoms 
When I click on the locked red padlock icon it flicks to an open white one and then goes back to locked red one.  Ways have black border around them, documentation suggests borders should be red ?  Tiny white ringpull icon at very top of screen flashing continuously.

## Expected Behaviour 
Padlock is supposed to stay white so that I can edit

## How to recreate 
Launch app, select open map, scroll/zoom to see almost-junction, click on two-way arrow option at bottom right and select Download current view (Loading data into memory message appears very briefly) tap on node #1147172419 (Tertiary) at end of way (unlock to edit prompt appears) then click on padlock

## Crash dump submitted 
No, it didn't crash

## Any other potentially relevant information 
New user because ideditor no good on touch screens.

![screenshot_20170617-201711](https://user-images.githubusercontent.com/29509220/27255655-827c7546-539a-11e7-8164-a934f788c5bf.png)

**Comment by simonpoole** [comment]
Are you running the stock Samsung 7.0 ?

Wrt the lock: there is an auto lock feature that will lock the screen by default after 1 minute, can you check the corresponding setting  in the advanced preferences?

The "touch area" border should be semi-transparent and orange, definitely not black and non-transparent as in your screen shot, could you further check what the "Map profile" value in the preferences is set to?

Further could you in the preference screen  scroll down to the "Debug" entry and copy and paste the information from there here if possible?

**Comment by simonpoole** [comment]
Just for reference purposes, this is what it should look like with default settings (screen shot from a S7 running stock 7.0, outside of screen size essentially identical to the S2):
![screenshot_20170617-220400](https://user-images.githubusercontent.com/1011860/27255961-82e0e7d8-53a9-11e7-8263-12e65506c2ad.png)

**Comment by simonpoole** [comment]
Just realized what the "ringpull icon" is, it is the google pin/location icon that indicates that a location service is running/resp. when flashing that it is trying to determine the position (Vespucci normally assumes that you are outside and will want a GPS fix, you can either simply ignore it or disable GPS on your device if you find it annoying).

**Comment by MikeParfitt** [comment]
Hi Simon,

Thanks for the update, debug information below.  The auto-lock time was the 60-second default, I have changed it to zero, which should have disabled it.  The map profile was set to "" I have set it to default.  The tablet is standard Samsung OS as far as I know.  It isn't rooted.

Unfortunately, none of the above changed the behaviour.  I did notice that the black colour does flick to a semi transparent orange in synch with the padlock briefly going white.  So getting it to stay unlocked seems to be the key issue for me.

Vespucci 0.9.8r1242
Maximum avaliable memory 536870912
Total memory used 49928416
Tile Cache MAPBOX usage Size 7340032 of maximum 67108864 #entries 28
Tile Cache MAPBOX_LOCATOR_OVERLAY usage Size 262144 of maximum 67108864 #entries 1
State file size 2667 last changed 2017-06-19 08:00:49
Bug state file size 669 last changed 2017-06-19 08:00:49
Relations (current/API): 0/0
Ways (current/API): 3/0
Nodes (current/Waynodes/API): 82/83/0
Available location providers
passive enabled true
gps enabled true
network enabled true

**Comment by simonpoole** [comment]
Looks normal, plenty of memory etc, the default profile is the same as the "Colour round nodes", just as a test you can try switching to "Pen round nodes" but as the timer for locking the screen has nothing to do with the map style it is unlikely that will achieve anything.

Right now I would suspect either

- a corrupted install (assuming it isn't the apk itself), removing the data for the app will force it to reinstall from scratch
- a 3rd party app causing issues (can't image what though)

Probably worth checking: any display related developer options turned on?

0.9.9  (beta) (downloadable from the releases on this site) has a button on the "Debug" page that will send a more comprehensive error report, so it might be worth installing that if all else fails.

**Comment by MikeParfitt** [comment]
Hi Simon,

Progress !  I reinstalled the app, but the default layout had no satellite background.  I remember fiddling around with the Map Backround/Overlay values the first time around.  This time I ended on "Bing aerial imagery" and "none" respectively.  What values are you using ?

After downloading the OSM data I clicked on the padlock, this time it stayed white, so I moved the nodes around and now the junction looks as shown on the image below.  Is this sufficient, or do I need to join the end node of the side road to a node on the A9025 ?

Also, what are the two black lines joining the other side road to the A9025 ?

![my first edit](https://user-images.githubusercontent.com/29509220/27302926-e2581f3c-5530-11e7-8355-606c2749c004.png)

**Comment by simonpoole** [comment]
So far so good :-):

- imagery.  In the list it is ordered, as far as possible, by how "good" it is, right now Bing is likely to be best for you (the next update will include DigitalGlobe imagery which may be better).
- edit: nearly there :-) I would join all four roads in one place, first you need to delete those black lines (default rendering for ways which are either of an unknown type or have no tags). Then select the end node of one of the roads and move it to one of the other end nodes, you will see the"join" icon pop up, select that and repeat for the two remaining end nodes. Now you should have one node common to all four ways.
- you've probably asked yourself what the violet colour is: that highlights objects that have an issue, in this case a missing name or ref (if they don't have one, simply ignore the issue)

Documentation: all of the documenation and more is available on http://vespucci.io/
