### ISSUE TITLE
Inability to select nodes or ways in Vespucci to read OSM tags

### ISSUE THREAD

**Issue by silvermapper** [MarcusWolschon/osmeditor4android#575]
The whole screen on my existing version of Vespucci was grey. I thought I should install the latest update, anyway. Having done that plus a subsequent uninstall and new install, I am unable to select anything. No objects have halos of any sort, whatever the lock icon and the various one or two taps or long press do not display any tags. I am at fault somewhere, clearly. I should appreciate your help. I attach two screenshots: 1. unlock mode; 2. tag editing only mode.
![screenshot of tag editing only mode](https://user-images.githubusercontent.com/29659786/27485418-864447ec-5824-11e7-91d7-4dbde38ea79d.png)
![screenshot of unlock mode](https://user-images.githubusercontent.com/29659786/27485419-8647ea28-5824-11e7-8326-c3008edb69f2.png)

**Comment by silvermapper** [comment]
I uninstalled Vespucci once more, powered off my 'phone and on again and reinstalled Vespucci.  Opening it this time appeared to be different, immediately presenting me with a smallish-scale area around my location.  I zoomed in and downloaded the area using "Download current view".  Unlocking presented me with enlarged icons and the background highlights for all nodes and ways that allowed me to obtain tag information.  All is well!  I look forward to getting to know it again.

**Comment by simonpoole** [comment]
I was just going to point out, the issue was simply that you hadn't downloaded any data yet, this is initially always required, even if auto-download is enabled.

Pls feel free to ask any questions that arise, there is a fair bid of documentation on htto://vespucci.io/ in any case.
