### ISSUE TITLE
Vespucci can allow users to add data around "null island"

### ISSUE THREAD

**Issue by SomeoneElseOSM** [MarcusWolschon/osmeditor4android#576]
It's far from the worst offender, but it can happen: https://www.openstreetmap.org/changeset/49748659

Would it be possible to exclude nodes added at 0,0 (or at least warn the user)?

**Comment by simonpoole** [comment]
"allow" is the operative word here. vespucci normally does not use the current GPS position for adding data, there is an option to explicitly do so when creating a node, but IMHO it is not something you would accidentally do (but I can add a warning there).

**Comment by simonpoole** [comment]
Warning and block added in https://github.com/MarcusWolschon/osmeditor4android/commit/fe344984552cae41ebb419e9b2cef36033b38c41

**Comment by SomeoneElseOSM** [comment]
For completeness - we've just had another example of something a bit like this in https://www.openstreetmap.org/changeset/73828294 (the first one I've noticed in 2 years, so not worth an extra investigation, I don't think).

**Comment by simonpoole** [comment]
IMHO again it can have nothing to do with GPS position (which btw is not actually 0/0 for the nodes). I would tend to suspect on device or on upload corruption.
