### ISSUE TITLE
Adding JOSM-type history feature

### ISSUE THREAD

**Issue by silvermapper** [MarcusWolschon/osmeditor4android#577]
I find the History feature of JOSM most interesting when appraising OSM tags.  It is very useful to read who did what and when.  It can play a part in my further actions.  I wonder whether such a feature might be considered for Vespucci?

**Comment by simonpoole** [comment]
Adding such a function is clearly possible, needs some thinking though.

**Comment by silvermapper** [comment]
Simon
I appreciate your comment.  A further consideration: History in JOSM is the one place I know where I can view the data source for changes, as I reminded myself yesterday when I wished to replicate what I had written for a previous amendment.

**Comment by simonpoole** [comment]
Going forward this will require https://github.com/MarcusWolschon/osmeditor4android/issues/668 to be done

**Comment by simonpoole** [comment]
We had a 2021 GSoC project work on this, that is now completed and needs to be integrated https://github.com/zedlabs/ElementHistoryDialog
