### ISSUE TITLE
Enable Notes to be repositioned once created

### ISSUE THREAD

**Issue by SK53** [MarcusWolschon/osmeditor4android#578]
I've found that I may want to record notes when moving outside my target editing area (and therefore not downloaded on the phone). The easiest way to do this is to add the note at one's location, but this may lead to some ambiguity in a note: particularly if backgrounds aren't present in the cache. However, if notes were re-positionable before uploading (when additional imagery may also be available) they may be much more useful.

The note which I created which made me realise why this behaviour would be useful is this one: https://www.openstreetmap.org/note/1036699. One is much more likely to be terse when entering notes on the phone, and terseness associated with imprecision leads to ambiguity. So with these I have added clarifying comments once uploaded to OSM.

**Comment by simonpoole** [comment]
Current thinking:
- on clicking a non-uploaded note, select it and enter a specific ActionMode just as we would do with a node
- dragging the selected note will update its position
- the mode should provide menu entries/action bar buttons to edit the note, delete it and help.

**Comment by simonpoole** [comment]
Code for the specific action mode is there however needs a bit more thinking. potentially integrating https://github.com/MarcusWolschon/osmeditor4android/issues/711

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/442523fa9b929b04043a8c2bd766b1d10aae7fb4
