### ISSUE TITLE
How much mobile data does Vespucci use in the field, typically?

### ISSUE THREAD

**Issue by silvermapper** [MarcusWolschon/osmeditor4android#580]
I was checking Public Rights of Way in my area of Oxfordshire yesterday.  I wished to look at the existing tags for some of the ways.  I downloaded a large-scale current view but wondered, subsequently, what was the likely size of the downloaded data.  I have just 500MB per month data allowance.  I should be grateful to learn how the process works in these instances and the best actions.

**Comment by simonpoole** [comment]
That is a difficult question to answer, but I would expect that mobile data use normally would be dominated by download background tiles. That can be reduced by allocating a large tile cache and pre-downloading the area in question. 

As to the OSM data itself, in most cases that would at most be a couple of MBs even downloading fairly large and urban areas (you can test with the export function on openstreetmap.org), however as the transmission is compressed typically the actually transmitted data will only be roughly 1/10 in size.

I am working on a more complete offline solution for the actual OSM data (more geared towards situations in which you don't have Internet access for multiple days).

**Comment by silvermapper** [comment]
Simon
I thank you for your reply and efforts to help.  I had thought my question was somewhat like, "how long is a piece of string?".  I am rather clueless about tile caches, etc.  Do I assume correctly that if I check one parish at a time, say, I select that area to download where I have Wi-Fi available, to take on each occasion?  I read the preset tile cache size as 100MB, which would more than comfortably cover my area of interest.

**Comment by matkoniecz** [comment]
>  Do I assume correctly that if I check one parish at a time, say, I select that area to download where I have Wi-Fi available, to take on each occasion? 

At least for me it is unclear what is asked here.
