### ISSUE TITLE
Exiting Vespucci

### ISSUE THREAD

**Issue by silvermapper** [MarcusWolschon/osmeditor4android#582]
The three 'buttons' at the foot of my Moto 4G 'phone including the back arrow that I use to exit Vespucci, are hidden when I use the application, covered by its own row of 'buttons'.  Dragging upwards from the foot of the 'phone to exit brings up the GPS panel as often as not.  Does this happen with all 'phones?  Is there a technique to displaying my three 'buttons' or is there an alternative to exit Vespucci?

**Comment by HolgerJeromin** [comment]
The advanced settings have an option "fullscreen" which allows "never"

**Comment by simonpoole** [comment]
As @HolgerJeromin writes, if it is causing issues (see https://github.com/MarcusWolschon/osmeditor4android/issues/487 ) then the best approach is to turn fullscreen mode off.

**Comment by silvermapper** [comment]
I thank you both for your helpful information; a most satisfactory solution.
Bob

**Comment by simonpoole** [comment]
Well it would be more satisfactory if the full screen mode worked better, but the problem is that it was mainly designed in Android for gamers, not to maximize screen real estate for normal apps.
