### ISSUE TITLE
show upload confirmation flash also on uploading changes to notes

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#585]
Currently uploading map edits to OSM results in confirmation flash (at bottom of the screen). Uploading changes to notes is not confirmed in this way.

I think that for consistency and to avoid confusing users uploading changes to notes (and all other uploads resulting is saving data to external databases) should result in the same type of confirmation flash.

note: I enabled beta version

**Comment by simonpoole** [comment]
Just as a clarification are you referring to uploading Notes separately (either individually or all) or as part of a general upload operation (in the later case  it is a bit tricky to display multiple snackbars or toasts).

**Comment by matkoniecz** [comment]
Individual note upload - selecting note, marking it as closed, selecting upload in bottom left of note dialog.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/862ca8b2ef5759964a581bd4c1f533f6239f22ea

**Comment by matkoniecz** [comment]
Thanks!
