### ISSUE TITLE
Disabled "show position" breaks "goto position" in some cases

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#587]
Version 0.9.9b1286 on Fairphone 2 Android 6

<s>Goto gps position does not work if i hide the icon. Unhide activates the function again.</s>

"Goto gps position" does not work in some cases. "show gps position" is not checked (but i never changed it) . Activating "show gps position" activates "go to gps position" function again.

**Comment by simonpoole** [comment]
Can't recreate the behaviour on an emulator (and showing/hiding the button doesn't really affect the logic), is the checkbox checked after you select the "Follow GPS"  menu entry?

**Comment by HolgerJeromin** [comment]
strange can not reproduce anymore. :-/

**Comment by HolgerJeromin** [comment]
I found that the app forgot the option "show gps"  in some cases. 
Goto gps does nothing than. Activating "show position" made "goto gps" work again.

**Comment by simonpoole** [comment]
The behaviour shouldn't be any different than with the "GPS-button" visible (it really only hides it):
- checking the "Follow GPS position" will center the screen on the current position and continue to do so
- if you pan the screen manually and/or try to edit something it will fall out of the mode ("Follow GPS position" will be unchecked), till you re-enable it

The "Show location" setting should be unaffected by all of this, but it is naturally possible to accidentally uncheck it. Using the menu is really not a good solution for an operation that has to be done a lot, that is why we have the GPS button.

**Comment by HolgerJeromin** [comment]
Ignore my comments regarding 'gps button' hiding. It was a wrong observation.

I never disables "show gps" in the menu but often i find it disabled and "goto position" is not working.
(corrected first post)

**Comment by simonpoole** [comment]
The "show GPS position" internal flag really only gets turned off if you do so with the menu entry, or if no enabled GPS provider can be found. That is a common required state (enabled GPS provider) for both functions so could be a common root cause for the symptoms you are seeing.

**Comment by HolgerJeromin** [comment]
But enabling "show gps position" or "follow position" in the app should not enable a gps provider on my phone. 
So i am puzzled why one of those checkmarks unlocks the "goto position".

**Comment by simonpoole** [comment]
I believe I've seen this now too:

- outline arrow (indicating that we have a current GPS position)
- but at a stale location
- GPS button is hidden because of the first point
- panning sets the position marker to the state it should have and re-enables the  GPS button

But I haven't been able to recreate reliably yet.

**Comment by simonpoole** [comment]
I haven't seen the issue since https://github.com/MarcusWolschon/osmeditor4android/commit/ca82078e8da4cf47a528ca434239bd40b00c20e5 can anybody confirm that this has gone away in 10.0?

**Comment by HolgerJeromin** [comment]
As a workaround i always used "follow gps" instead of "goto gps". 
Testing right now: "show" and "follow" is off, "goto" works.

I think we can close this issue. Thanks for your work!
