### ISSUE TITLE
Map Background (OS7) not downloading

### ISSUE THREAD

**Issue by MikeParfitt** [MarcusWolschon/osmeditor4android#589]
## Vespucci Version
Vespucci 0.9.8r1285
Maximum avaliable memory 536870912
Total memory used 48086560
Tile Cache OS7 usage Size 0 of maximum 67108864 #entries 0
Tile Cache OSM_INSPECTOR-HIGHWAYS usage Size 5242880 of maximum 67108864 #entries 20
State file size 4902 last changed 2017-07-22 19:38:00
Bug state file size 7773 last changed 2017-07-22 19:38:00
Relations (current/API): 0/0
Ways (current/API): 4/0
Nodes (current/Waynodes/API): 222/224/0
Available location providers
passive enabled true
gps enabled true
network enabled true

## Device (Manufacturer and Model)
Samsung Galaxy Tab S2 SM-T715

## Android Version
7.0 (not rooted) with the security patch dated 1st April 2017

## Behaviour/Symptoms
For one location (mainland Scotland, NW of Kinerras) none of the Map Background image choices are appropriate, due to trees.  But when I switch to Ordnance Survey 7th Series, nothing downloads.  Not just for this location, but for the others that I have tried.  The background stays light yellow until I make a different choice of Map Background.

## Expected Behaviour
OS7 Mab Background images should be downloaded for all UK locations when selected.

## How to recreate
Select the 7th Series (OS7) option from the Map Background list

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
(optional)

**Comment by simonpoole** [comment]
We use, just as iD, https://github.com/osmlab/editor-layer-index for the layer meta information. This was updated immediately before the release. Could you check if it currently works in iD? There may naturally be an issue that just effects vespucci, but cross checking with iD would be a good idea.

**Comment by MikeParfitt** [comment]
The same problem occurs with iD

![screenshot_20170723-094301](https://user-images.githubusercontent.com/29509220/28497953-8cdfd71e-6f8b-11e7-9514-529325687510.png)

![screenshot_20170723-094039](https://user-images.githubusercontent.com/29509220/28497958-96fea162-6f8b-11e7-9051-806abf706bf2.png)

**Comment by simonpoole** [comment]
Closing this here as there is no action required and resolution can be discussed on the editor-layer-index issue.
