### ISSUE TITLE
on editing limit legth of tag values to length alowed by API

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#590]
## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

0.9.9b1286

## Device (Manufacturer and Model)
(required)

Xiaomi Redmi 4

## Android Version 
(required, please indicate if you are using a custom version)

6.0.1 MMB29M

## Behaviour/Symptoms

It is possible to enter tag value that is longer than accepted by OSM API.

## Expected Behaviour
(required)

Length of text that can be entered into value field is limited, message appears after reaching limit and still typing.

## How to recreate
(required)
Type very long text. Save edit. Receive error. 

Inscription tag is likely to be able to trigger this without making test edits.

## Crash dump submitted (no or yes + date)
(required)

## Any other potentially relevant information
(optional)

![screenshot_2017-07-23-14-38-56-510_de blau android](https://user-images.githubusercontent.com/899988/28499814-cdcd3d4c-6fbe-11e7-90dd-509399da2db9.png)

**Comment by simonpoole** [comment]
This is clearly a bug both here and that the limit is not documented and returned by the API capability call http://wiki.openstreetmap.org/wiki/API_v0.6#Capabilities:_GET_.2Fapi.2Fcapabilities (it is a bit low for values in any case).

**Comment by simonpoole** [comment]
Fixed for the ProprtyEditor in https://github.com/MarcusWolschon/osmeditor4android/commit/02717bd5703650a9ca81bcb2aec1aa87a5c3e027
