### ISSUE TITLE
Mistake in turn:lanes value

### ISSUE THREAD

**Issue by osmvermesser** [MarcusWolschon/osmeditor4android#592]
When add lurn:lanes the autocomplete value left;througt will weiten by seperator ":" - lists will usw ";"

Jan

**Comment by simonpoole** [comment]
Thanks, fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/2d37fe67c69def525a5a8af089037123f05554e9

This will be included in the next releases, likely some time next week, or you can download the corrected version here http://simonpoole.github.io/beautified-JOSM-preset/
