### ISSUE TITLE
Utility presets don't get added to MRU list 

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#597]
Presets that can't be matched do not get added to the MRU in 0.9.9

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/12f87f8a0e99d6bfc41b50ea841e7d8479f7ff47

**Comment by osmvermesser** [comment]
Hallo Simon,

bezogen auf unsere mails schreibe ich jetzt hier weiter.

Habe jetzt Version 0.9.9r1299 installiert und wollte meine Vorlagen nach dem Update nutzen.

Ersteinmal wurden diese nicht angezeigt. Dann habe ich die Vorlage gelöscht und  dann erneut eingetragen.

Die Dir übermittelten Vorlagen (2.9.2017) werden aber weiterhin nicht angezeigt!!!!

Gruß Jan

**Comment by simonpoole** [comment]
Jan kannst du mal ein Screenshot einerseits von der Einstellungsseite mit der Liste der installierten Vorlagen machen und anderseits vom Tab im "Property Editor" mit den eigentlichen Vorlagen? Danke.

**Comment by osmvermesser** [comment]
hallo Simon,

ich hoffe es sind die richtigen Bilder.

Sonst erst nächste Woche.

Gruß Jan
![screenshot_20170914-200709](https://user-images.githubusercontent.com/6803899/30446118-88bae422-9988-11e7-8685-cf75736b9da8.png)
![screenshot_20170914-200555](https://user-images.githubusercontent.com/6803899/30446130-92b983b6-9988-11e7-9909-617d83c887bd.png)

**Comment by simonpoole** [comment]
Das sieht eigentlich gut aus, der Preset für check_date unter Anmerkungen tut? Und wenn du einer deren aus Den Beispielen auswählt passiert dann einfach nichts?

PS: es hat jetzt einen eingebauten "öffentlichen Bücherschrank" Preset, allerdings noch ohne Icon.

**Comment by simonpoole** [comment]
@osmvermesser ich warte noch auf Feedback.

**Comment by osmvermesser** [comment]
Moin!
Sorry, hatte ich aus den Augen verloren!

Present Check_date kann angewand werden.

Aber sorry "Und wenn du einer deren aus Den Beispielen auswählt passiert dann einfach nichts?" hier verstehe ich nicht, was Du meinst?

Gruß Jan

**Comment by simonpoole** [comment]
@osmvermesser häte heissen sollen "aus deinen Beispielen", sprich Einträge aus den Presets die du geladen hast.

**Comment by osmvermesser** [comment]
Moin ! das einzige Present von mir ist derzeit das mit dem Bücherschrank (mit Icon) und das funktionert!

Gruß Jan

**Comment by osmvermesser** [comment]
Hallo Simon,

ich habe jetzt 0.9.9r1300 installiert, aber der gewünschte Effekt ist noch nicht eingetreten. Habe vermutet das mit dem Schließen und dem angebotenen Update das Problem gefixt sein soll.

Das Present wird weiterhin nicht angezeigt.

Habe es nochmals aus der Liste entfernt, Vespussic beendet und neu gestartet. Dann das Present wieder eingebunden und immer wird noch nichts angezeigt!!!!

App deinstallieren und dann neu installieren ?

Gruß Jan

**Comment by osmvermesser** [comment]
Ich habe heute nochmal Vespucci komplett deinstalliert und dann check_date und mein present eingebunden.

Check_date wurde angezeigt - meines (code unverändert) nicht ! Dann check_date entfernt - aber auch dann wird meines nicht angezeigt!

Jan

**Comment by simonpoole** [comment]
@osmvermesser kannst du mir nochmals ein link zu deinen presets schicken, oder noch besser, sie hier an ein Kommentar anhängen?

**Comment by osmvermesser** [comment]
Hallo Simon,

hier nochmal die unveränderte Datei.

Gruß Jan
[josm-preset_vespucci.zip](https://github.com/MarcusWolschon/osmeditor4android/files/1393996/josm-preset_vespucci.zip)

**Comment by simonpoole** [comment]
Der Fehler liegt darin, dass aus irgendwelchen Gründen das oberste Element in deinem Preset "annotations" ist und nicht wie es sein sollte "presets" Vespucci hat früher den Fehler ignoriert, jetzt aber nicht mehr.

[josm-preset_vespucci.zip](https://github.com/MarcusWolschon/osmeditor4android/files/1394126/josm-preset_vespucci.zip)

Tut bei mir jetzt.

**Comment by osmvermesser** [comment]
Moin!

ich habe das jetzt editiert und hochgeladen unter http://www.tappenbeck.net/osm/vespucci/josm-preset_vespucci.zip - aber es taucht bei mir noch nicht auf in dem Tab mit den Vorlagen !

Habe das Present extra nochmal entfernt, das Smartphone neu gestartet und neu eingebunden.

Immer noch kein Eintrag! Siehe Bilder.

![vespucci_20171018a](https://user-images.githubusercontent.com/6803899/31712984-043f42f8-b3fd-11e7-8594-957887ccbd7c.png)
![vespucci_20171018b](https://user-images.githubusercontent.com/6803899/31713010-177911b4-b3fd-11e7-8fe9-71f2e146159f.png)

Gruß Jan

**Comment by simonpoole** [comment]
Du musst schon korrektes XML draus machen, sprich das Toplevel Element presets auch richtig abschliessen, d.h. am Ende der Datei das "annotations" auch noch durch "presets" ersetzen (deshalb hatte ich oben ja auch eine bereits korrigierte Version hochgeladen).

Du musst übrigens einfach, nachdem du den Fehler korrigiert hast, in der Presetliste lange auf den Eintrag klicken und dann "Aktualiseren" wählen.

**Comment by osmvermesser** [comment]
Hi!
danke für den Hinweis - das kommt davon, wenn man nicht so oft mit XML-Strukturen arbeitet!

Jetzt ist alles wieder im Lot!

Das mit dem Aktualisieren war bekannt !

Gruß Jan
