### ISSUE TITLE
allow to switch language of application

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#598]
Feedback from showing Vespucci to an unexperienced mapper - after running into complications with poor/incomplete translation of app (https://github.com/simonpoole/beautified-JOSM-preset/issues/30) he wanted to switch to a different language and was surprised by lack of option allowing to do that.

Even after adding 600+ translations to Polish version it would be still useful for users in other languages preferring to use the English version (for example, because they are used to use English during OSM tagging as raw tag value is in English).

**Comment by simonpoole** [comment]
There are two parts to the answer:

- Android doesn't really support running an app in a different locale than what the device is set to, it is possible with some workarounds, but involves working against the system which is not a particular good idea and would involve special casing in a lot of places.
- it would be reasonably easy to do for the presets as we don't use the Android resource system for that.

**Comment by matkoniecz** [comment]
I think that there should be also option in Vespucci to make possible for a newbie to do that (somebody confused by broken presets may look to settings but is quite unlikely to figure out that it is possible to download somewhere a special not broken preset).

**Comment by simonpoole** [comment]
I've added a link to the preset help page https://github.com/MarcusWolschon/osmeditor4android/commit/fde598045cd6014afe05d1aaafe7daac44664581 (this is a short term workaround, adding a preference will take a bit longer).

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/ef6a3e841c3b7d02268546eae012d41c7fa1bf04 adds per preset options to use translations or not.

**Comment by georg-d** [comment]
see also https://github.com/MarcusWolschon/osmeditor4android/issues/915
