### ISSUE TITLE
show messages higher

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#600]
Currently messages like one about performing upload or undo are displayed at the bottom.

As result bottom menu blocked during displaying messages - after every undo or upload.

Especially flustrating is undoing multiple changes.

Maybe messages should appear above bottom menu?

**Comment by simonpoole** [comment]
The SnackBars are intended to be shown at the bottom, the alternative is to use toasts that we show at the top. Likely we simply should be using toasts instead of SnackBars for undo messaging.

**Comment by simonpoole** [comment]
Changed in https://github.com/MarcusWolschon/osmeditor4android/commit/1b09fdeaba3873199ebf1158a41c32ae968a286a
