### ISSUE TITLE
preset overwriting tags warning is too zealous

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#601]
## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

O.9.9 r1299

## Device (Manufacturer and Model)
(required)

Xiaomi Redmi 4

## Android Version 
(required, please indicate if you are using a custom version)

6.0.1

## Behaviour/Symptoms
(required)

Setting value of tag with unset value is considered as overwriting

## Expected Behaviour
(required)

Replacing type= with type=multipolygon is not triggering scary warning

## How to recreate
(required)

Select element like way, select create relation (at this point out relation has type tag with unset value) select multipolygon in preset.

## Crash dump submitted (no or yes + date)
(required)

## Any other potentially relevant information
(optional)

Only mobile access, may provide extra data like screenshots in week or two

**Comment by simonpoole** [comment]
Thanks for the report.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/5767b2401d8aec05a84accb7754864f3bfe92467
