### ISSUE TITLE
consider removing option to keep changeset open

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#602]
Currently settings are very overloaded. Maybe some settings may be removed, like option to keep changeset open? It maybe just me but usefulness of things setting send to not justify keeping it cluttering settings.

**Comment by simonpoole** [comment]
There is currently some work underway to improve the upload dialog https://github.com/MarcusWolschon/osmeditor4android/pull/579 As to the option: as people want to use it on a per changeset base it really can't go anywhere else. However as we may be splitting the dialog in to tabs, the whole thing might become less crowded.
