### ISSUE TITLE
allow deleting bugs also with unsaved changes

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#606]
It is useful in some situations to allow clearing notes despite fact that some changes remain unsaved

For example my bug database become corrupted, I already send error report and now on each upload I get window that Vespucci crashed.

I am unable to clear bug database as some changes remain unsaved (I suspect that problem is caused by note that was closed after I downloaded it to Vespucci, but I am unable to verify it as I am stuck with data that crashes Vespucci).

**Comment by simonpoole** [comment]
IMHO we should simply ignore the error when the note is already closed and mark the Note data as clean (aka no pending changes).

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/cc890e11fb3603503574109be632154d052336fa (will be included in the October update).

**Comment by matkoniecz** [comment]
Thanks!
