### ISSUE TITLE
Unable to locate help topic for .osc file

### ISSUE THREAD

**Issue by MikeParfitt** [MarcusWolschon/osmeditor4android#613]
After moving a lot of existing nodes and adding lots of new ones inbetween existing ones, the upload to OSM failed repeatedly, but didn't say why.  I then created an .osc file so that I didn't lose everything.

When I looked at the file with a text editor, as well as a few small ways being modified, a brand new way was created somehow with lots of old and new node ids, rather than the big existing way being modified.

I have decided that the safest course of action is to delete the xml for
 . . all the new nodes
 . . the new way
 . . changes to existing ways
So the .osc file now only contains the position changes to existing nodes.

The "Read from file" option doesn't  seem to do anything useful with the .osc file, so I'm guessing that it isn't JOSM-compatible.

How can I get the .osc file back into Vespucci ?

Can you point me at the help page for this ?

**Comment by simonpoole** [comment]
.osc files can currently only be written (see http://vespucci.io/help/en/Main%20map%20display/#available-actions), they can however be read in JOSM. 

What did vespucci display when the upload failed? It sounds as if there was a conflict of some kind.

**Comment by MikeParfitt** [comment]
When the upload failed, all I saw was a vague piece of text telling me that some, or all of my updates were not uploaded.  It went on to say that this might be a temporary problem.  I re-did the upload several times, but got the same vague piece of text each time.  At no time did I get any specific information about the actual error.

To save my work, I then picked the first entry on the "File..." menu (Export Changes) which creates a format that can not be imported back into Vespucci.  I suggest that this should me made clearer, perhaps by re-wording it as "JOSM Export (.osc)" to limit the number of users who make the same mistake as me.

If the file created by the "Save to file" option can be read by the "Read from file" option, then it would emphasise their usefulness to have them as the first two entries on the "File..." menu.

**Comment by simonpoole** [comment]
There was a general OSM API issue about the time when you had the problem, and the error message you are reporting is only shown when a more specific cause cannot be determined. So that that part of the issue is likely correct behaviour.

**Comment by simonpoole** [comment]
Menu entry wording improved in https://github.com/MarcusWolschon/osmeditor4android/commit/71449c5d35b77866181c07f1d99036a3394bf765
