### ISSUE TITLE
turn:lanes space after each entry

### ISSUE THREAD

**Issue by nurdafur** [MarcusWolschon/osmeditor4android#615]
When editing turn:lanes there is a wrong programming
After each edit there is a space.
example: "left| through| right| "
it should be "left|through|right|"

**Comment by HolgerJeromin** [comment]
Is this a problem from vespucci or your on screen keyboard?

**Comment by nurdafur** [comment]
Most likely it is a problem of vespucci.
I just tried on an other device with same results.
Every time I choose a turn option, it comes with that space after the |

**Comment by simonpoole** [comment]
Thus is a feature of the multi-select implementation, not quite sure why you believe it is an issue. You can safely ignore it.

**Comment by nurdafur** [comment]
No, I think it is not ignoreable. If people like me do not delete this space, the mapping will be wrong.
As I reloaded a section where I added this turn attributes it was showed as an error.
Now I no it, but in some months, when I do not use this feature for a while, I might forget to delete the space.
The result is that it will not render properly in navigation apps

**Comment by simonpoole** [comment]
I would consider any consumer of OSM data that does not ignore whitespace around tags severely broken.

**Comment by simonpoole** [comment]
Addressed (not fixed as there was nothing "wrong") in https://github.com/MarcusWolschon/osmeditor4android/commit/2d30111823f93bb9c49046a17586ed7cf6712df3 Note: I would strongly suggest fixing any consumers that don't trim white space, particularly when parsing multi-value tags.
