### ISSUE TITLE
Do not close find form when not sucessful

### ISSUE THREAD

**Issue by osmvermesser** [MarcusWolschon/osmeditor4android#616]
Moin!

wenn eine Suche ohne Erfolg war, dann wird die Funktion beendet.

Besser wäre, den Dialog wieder einzublenden mit dem soeben eingegeben Text - dann kann man Fehler korrigieren und es nochmal versuchen. Besonders im Ausland braucht man unter Umständen mehrere Versuche.

In diesem Zusammenhang wäre es auch gut irgendwie einfach an Sonderzeichen für fremde Sprachen zu gelangen.

Die Rückkehr zum Eingabedialog ware auch gut bei Erfolg um die Suche zu verfeinern.

Abschließend wäre darüber nachzudenken, ob sich Vespucci die letzte Eingabe merkt. Dann natürlich mit einem Löschbutton.

Jan

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/5a15ef2048988292f41a2a6cc400578f575f1528
