### ISSUE TITLE
loading data into memory, with only spinner as a feedback

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#617]
The biggest problem with Vespucci for me is that significant part of editing time is spent looking at "loading..." spinner.

Sometimes it is not clear what is happening - is data downloaded at all?

JOSM allows to distinguish between (a) loading data from disk (JOSM is frozen) (b) downloading data (download progress bar is moving) (c) connection unavailable (download progress bar is missing)

Especially for cases where download command was issued outside Vespucci it is not clear whatever waiting for completion of operation makes sense - spinner is spinning for minute or two, what happened? Buggy external app selected massive area? Area is downloaded, Vespucci is pushing it into memory? OSM servers are laggy or for some other reason Vespucci failed to even start connection? Vespucci is loading data from disk cache? Something else?

Without feedback I have no idea whatever problem is caused by third party app, laggy internet, overloaded OSM servers or poor Vespucci performance.

(For reference - I used edit link in OSMBugs app)

**Comment by HolgerJeromin** [comment]
This is a very good point. Thanks for opening this issue.
Often i abort loading and everything _seems_ to be fine (osm data is there and editable) which makes me puzzled why is should wait in this situation. 
To prevent data problems i often load fresh osm data which is done in < 1 second but this spinner took > 15-30 seconds before my abort.

**Comment by matkoniecz** [comment]
> Often i abort loading and everything seems to be fine (osm data is there and editable) which makes me puzzled why is should wait in this situation.

The same happens for me, but I am scared that data is corrupted/incomplete and I redownload again.

**Comment by simonpoole** [comment]
There are two and a half situations in which you get the spinner:
- when vespucci has been completely removed from memory and is restarted (then the saved state is loaded from on device storage) this should happen only rarely (aka when you actually terminated the app and restarted, or when you been using something else and return to vespucci and the OS has decided to pause vespucci). If this is happening a lot then we should check your Android setup.
- explicitly downloading data manually

In both cases the actual operation is completely asynchronous and dismissing the dialogue with the spinner does exactly just that and doesn't effect the operation going on, so no need to be concerned about that.   

Starting via an Intent, which seems to be where both of you are seeing issues is a bit special in that you may be doing both of the above operations slightly overlapping which shouldn't, but might cause the spinner not to be dismissed (could you both check if this is the case). In any case starting via an intent (aka from another app) always downloads and merges data in to the existing in-memory dataset, which will, with time, increases the in memory footprint and naturally tends to make merging slower and slower, particularly if you have many large relations in the dataset. The recommend way to address this is to upload your changes and download the current data as @HolgerJeromin does now and then, and as recommended in the FAQ. Naturally this all is rather device specific so may be very noticeable on some devices and on others not at all.

Note: the "Debug information" at the end of the preferences has information on the number of elements loaded, available memory etc. When things start to get slow could you both report those numbers?

**Comment by matkoniecz** [comment]
> In both cases the actual operation is completely asynchronous and dismissing the dialogue with the spinner does exactly just that and doesn't effect the operation going on, so no need to be concerned about that.

Great, that is nice to know.

**Comment by HolgerJeromin** [comment]
> Starting via an Intent, which seems to be where both of you are seeing issues is a bit special in that you may be doing both of the above operations slightly overlapping which shouldn't, but might cause the spinner not to be dismissed (could you both check if this is the case).

Yes, most of my issues were in cases where i change between apps with intents. 

> Note: the "Debug information" at the end of the preferences has information on the number of elements loaded, available memory etc. When things start to get slow could you both report those numbers?

i try to remember :)

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/b956a78d8fbe1b18b6301aaf2b084896f00e23b7 addresses the message issue (was likely a bit of a historic oversight).

**Comment by simonpoole** [comment]
Have either of you seen the spinner problem reoccur in any current version?

**Comment by HolgerJeromin** [comment]
Other case but: 
leaving the app while uploading spinner wait a few seconds and come back.
Last time i did this stunt the "upload finished" toast was shown, but the spinner "recovered" as the app state and was not closed (as the app was not active at the time the upload was done)

**Comment by simonpoole** [comment]
That is a general problem with Android apps that there is not a clean way to convey that something is "finished" and the dialog or whatever can be dismissed if the parent activity has been completely removed from memory and is restarting (the state of the dialog in this case the spinner will be restored, but because the thread that was doing something has already finished it will not get dismissed).

**Comment by simonpoole** [comment]
As the problem with the spinner confusion seems to be resolved, closing for now.
