### ISSUE TITLE
If nothing found in presets, dynamically search for valid tags

### ISSUE THREAD

**Issue by nicolas-raoul** [MarcusWolschon/osmeditor4android#618]
I wanted to tag a city gate so I searched for it:

![screenshot_20171012-190123](https://user-images.githubusercontent.com/99590/31529679-9dc88ace-b015-11e7-8767-164dae96b385.png)

Of course, city gate is such a minor/rare tag that it is not in the presets. There are [2500 documented tags](http://wiki.openstreetmap.org/wiki/Category:Tag_descriptions) and the vast majority of them are not in the presets, obviously.

However, when nothing is found in the presets and an Internet connection is available, I think that Vespucci should search online among the valid tags. I don't know if an API is available for that, but if not scraping http://wiki.openstreetmap.org/wiki/Category:Tag_descriptions could be an option.

Advantages:
- Users can tag more things, resulting in more quality data from Vespucci
- Less typing mistakes, as entering keys and values manually is very error-prone
- Better experience for Vespucci users, as having to remember arcane tag names is painful and time-wasting
Thanks, keep up the great work! :-)

**Comment by versat** [comment]
There is taginfo:
https://taginfo.openstreetmap.org/search?q=city+gate#values
Vespucci could search there for the most used keys/values.
But i guess it is hard for Vespucci to tell what is really useful and of good quality and should be presented/used.

**Comment by simonpoole** [comment]
There are already some thought on integrating taginfo, and potentially creating an artificial preset (including commonly used combinations). One of the problem with that is naturally that either we need the data on device or an Internet connection.

**Comment by matkoniecz** [comment]
I would argue that search of a valid term failing to find anything is an indicator of missing entries in tag preset (either because tag preset is missing something or because there is no tagging schema to map something in OSM).

In the first case tag preset should be fixed, in second searching taginfo would anyway fail to return anything useful.

So I think that proper way to fix this (and similar) issues is to improve tag preset.

**Comment by nicolas-raoul** [comment]
@matkoniecz So that means you want preset to contain thousands of items, right?
I have no idea whether having so many presets is feasible or not, but if feasible that's a good solution indeed.

**Comment by simonpoole** [comment]
Naturally the key point is what is a "valid term", If you look at https://github.com/simonpoole/beautified-JOSM-preset/issues/35 you will see that we are defintely not talking about 1000s of presets that we don't currently have, but 100s yes.

**Comment by matkoniecz** [comment]
> So that means you want preset to contain thousands of items, right?

I see nothing wrong with that.

**Comment by simonpoole** [comment]
Well there are no -fundamental- issues with having 1000s of presets, it would need some coding in vespucci to avoid reparsing and a more sophisticated icon cache. And then roughly 1-1.5 man years of effort per 1000 icons that need to be created and perhaps a quarter of that for generating the same number of presets. And probably a significant part of a FTE for maintenance.

**Comment by simonpoole** [comment]
Current ideas around querying taginfo or the wiki

1. do a keyword search (unluckily this not very fuzzy, which is the weak point in the whole scheme),  https://taginfo.openstreetmap.org/api/4/search/by_keyword?query=relocation&page=1&rp=10
2. if we find something do a combinations search on the key https://taginfo.openstreetmap.org/api/4/key/combinations?key=office&page=1&rp=10&sortname=together_count&sortorder=desc
this is not very useful as you can only search for combinations with a specific key not for a key/value tupel.
3. strip the result of 2. of all nonsense (a lot) which will likely nearly always only result in name=... remaining and use the original plus this as preset

Or alternatively query the wiki directly which may or may not result in something useful http://wiki.openstreetmap.org/wiki/Tag:office%3Dmoving_company is not really helpful wrt additional keys.

**Comment by simonpoole** [comment]
First cut added in https://github.com/MarcusWolschon/osmeditor4android/commit/29e9e0db66725abe683feb7f2997be6925bd17ba
