### ISSUE TITLE
magnifying glass decoration may confuse users

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#619]
## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

0.9.9r1300

## Device (Manufacturer and Model)
(required)

Xiaomi Redmi 4

## Android Version 
(required, please indicate if you are using a custom version)

6.0.1

## How to recreate

(required)

create a node

switch to presets tab

enter "preset search string" textbox

type lift gate

press search button

## Expected Behaviour
(required)

barrier=lift_gate is among results

## Behaviour/Symptoms
(required)

nothing happens

## Crash dump submitted (no or yes + date)
(required)

no

## Any other potentially relevant information
(optional)

I enabled beta testing on Google play and use preset provided in https://github.com/simonpoole/beautified-JOSM-preset/issues/31#issuecomment-330688537

**Comment by simonpoole** [comment]
Works for me ...  all three possible variants return the lift gate preset in the results ("lift gate", "lift", "gate").

Can you check if the preset is available by navigating manually to it?

**Comment by matkoniecz** [comment]
I did this (I forgot to mention that I tested this).

I also tested it with English language keyboard (Polish as secondary language) and now I tested again, with only default preset enabled.

As the next step I may test on a clean install (though it would again flush aerial images cache).

**Comment by matkoniecz** [comment]
Now I understand! I was clicking magnifying glass next to text field (that is only a decoration and is not doing anything), not one on the keyboard (that is a real button) (I was not getting even "Nothing found" toast).

Maybe removing magnifying glass from text field decoration would be a good idea? "preset search string" should be enough. Or maybe this image should disappear as user types (like the "Preset search string text")?

**Comment by simonpoole** [comment]
I don't think the fresh install is necessary.

I would suggest instead: going to the on-device preset help, at the bottom there is an entry "Update of default Preset", select that and install it. Then go to the Preset configuration in the Advanced Preferences and de-select the original Preset.

**Comment by simonpoole** [comment]
Ah that is an old annoyance that should be fixed as you say.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/c18cd9fbcd9dc61b5ae4f4e7948a099bec467ffd
