### ISSUE TITLE
No data displayed

### ISSUE THREAD

**Issue by bigfatfrog67** [MarcusWolschon/osmeditor4android#620]
When reporting issues, please use this template, if you are asking for an enhancement you can delete the text.

Please note that some components are maintained in upstream repositories and relevant issues should be reported there, these are specifically:

* background and overlay layers: 
* presets: 
* opening hours 
## Vespucci Version
0.9.9r1300

## Device (Manufacturer and Model)
Sony Xperia
## Behaviour/Symptoms
I choose download area, I see notes appear but no wire frame data, so have authorised with OSM

## Expected Behaviour
Wireframe with nodes so can unlock to edit

## How to recreate
Everytime

## Crash dump submitted (no or yes + date)
No
## Any other potentially relevant information
(optional)

**Comment by simonpoole** [comment]
Does this happen in any specific area or all over the place? 

In any case please try again and then go to to the bottom of the preferences screen and enter the "Debug Information" page, at the bottom there is a button that will send a crash dump to us (pls add a note point to this issue).

**Comment by bigfatfrog67** [comment]
It happens everywhere, have sent debug

**Comment by simonpoole** [comment]
Do you see a spinner when it is downloading?

**Comment by bigfatfrog67** [comment]
Just says "leaving data into memory" then all I see are osm bugs

**Comment by simonpoole** [comment]
Before I dig any deeper: when you've unlocked the screen (red lock -> white lock) Does the lock icon have a letter on it?

**Comment by bigfatfrog67** [comment]
No

**Comment by simonpoole** [comment]
And no "filter" icon in the middle of the right hand side?

**Comment by bigfatfrog67** [comment]
Yes there is an icon with lines

**Comment by simonpoole** [comment]
You have a filter (either Preset- or Tag-based) turned on but nothing configured, select the vertical Dot icon for the main menu and deselect whatever Filter was turned on.

The Debuginformtaion shows that it actually downloaded data too: 

Relations (current/API): 1/0<BR>Ways (current/API): 9/0<BR>Nodes (current/Waynodes/API): 124/132/

**Comment by bigfatfrog67** [comment]
OK I see, it's that new? Don't remember seeing that before? Thank you.

**Comment by simonpoole** [comment]
New with 0.9.9 http://vespucci.io/help/en/Tag%20filter/
