### ISSUE TITLE
second chance?

### ISSUE THREAD

**Issue by osmtools** [MarcusWolschon/osmeditor4android#622]
Working on the [OSM Latest Keys](http://osm.mueschelsoft.de/taginfo/newkeys.htm) list, i found the following (new as of 2017-11-04) keys used only once:
- second - chance youth _[node](http://www.openstreetmap.org/node/3959669219), [changeset](http://www.openstreetmap.org/changeset/53482819)_
- second chance _[node](http://www.openstreetmap.org/node/5209071183), [changeset](http://www.openstreetmap.org/changeset/53488042)_
- second chance key _[node](http://www.openstreetmap.org/node/5208379721), [changset](http://www.openstreetmap.org/changeset/53479585)_
- second-chance _[way](http://www.openstreetmap.org/way/403506725), [changest](http://www.openstreetmap.org/changeset/53482779)_
- secondchance youth _[node](http://www.openstreetmap.org/node/5208607359), [changeset](http://www.openstreetmap.org/changeset/53482993)_
- secondchanceyouth _[way](http://www.openstreetmap.org/way/400199057), [changeset](http://www.openstreetmap.org/changeset/53485940)_
- sscound chance youth _[node](http://www.openstreetmap.org/node/5208480621), [changeset](http://www.openstreetmap.org/changeset/53480975)_

Different user but all have used `Vespucci 0.9.9.1.1304` and all edits are on `Saint Lucia` ... so is this a Vespucci issue or a really strange and unbelievable coincidence

**Comment by osmtools** [comment]
additional information: 22x `second-chance youth` ([taginfo](https://taginfo.openstreetmap.org/keys/second-chance%20youth#values), [overpass](https://overpass-turbo.eu/?w=%22second-chance+youth%22%3D*+global&R)) on Saint Lucia, by several strange tag combinations?!

**Comment by osmtools** [comment]
Ok, i think i was too fast ... there are a lot more combinations of `second chance youth` ... and all the users are new (as of 2017-10-30) ... and there's nearly no changeset comment ...

**Comment by simonpoole** [comment]
I'm mit quite sure what you believe the issue is, if the user wants to they can enter essentially any key they want , just as with JOSM or iD.

Naturally who ever arranged the mapping should have created a present, but that is out of our control.
