### ISSUE TITLE
DEU-Bezeichnung power=substation

### ISSUE THREAD

**Issue by osmvermesser** [MarcusWolschon/osmeditor4android#624]
Moin!

power=substation wird als "Unterwerk" bezeichnet.

Im Wiki (http://wiki.openstreetmap.org/wiki/DE:Tag:power%3Dsubstation) findet sich dieser Begriff nicht.

Ich meine Trafo oder Umspannwerk ist passender.

Jan

**Comment by simonpoole** [comment]
Im Wiki steht noch vieles das nicht sinnvoll ist. Da substation mehrere subtags hat die nicht ein Umspannwerk bezeichnen würde, mache es meiner Meinung nach mehr Sinn ein generischer Oberbegriff zu verwenden.

**Comment by osmvermesser** [comment]
Moin!
aber den Begriff "Unterwerk" finde ich "völlig unpassend -  auch noch nie gehört!

Gruß Jan

**Comment by simonpoole** [comment]
Unterwerk ist IMHO völlig gebräuchlich mit der üblichen sprachlichen Unschärfen über mehrere Länder hinweg (und ich hab auch schon in der Stromversorgung gearbeitet).

**Comment by simonpoole** [comment]
Moved to upstream repo
