### ISSUE TITLE
Display when the user receives a message in OSM

### ISSUE THREAD

**Issue by naoliv** [MarcusWolschon/osmeditor4android#625]
Could Vespucci poll [/0.6/user/details](https://wiki.openstreetmap.org/wiki/API_v0.6#Details_of_the_logged-in_user) to see the number of unread messages and display something for the user if he receives a new message, please?

I can imagine 2 situations where displaying a message won't disturb the mapper:

* when he opens Vespucci it could verify if he has new messages and display some kind of toast message
* after he sends a changeset Vespucci could also poll if there are any new messages and also display something

In both cases it won't cause and disturbance if he is editing something on the map.

This should improve the communication with users that seem to ignore direct messages.

**Comment by simonpoole** [comment]
Vespucci has shown the user a message with the unread message post changeset upload count on openstreetmap.org since the day the information was added to the user details api call.  Current versions even provide a button that will directly open osm.org in a browser.
