### ISSUE TITLE
"Current location" button is not intuitive

### ISSUE THREAD

**Issue by naoliv** [MarcusWolschon/osmeditor4android#626]
It seems that the icons aren't very intuitive here.

![](https://user-images.githubusercontent.com/982338/32815980-c03a8a48-c99d-11e7-976d-d6376b9e653d.png)

`A` looks like a "current location" button, while in fact it isn't.
`B` is very difficult to understand sometimes; if we are using the phone with a bright sunlight, for example, we will never know that this is the proper "current location" button

And for some unknown reason it seems to get misaligned sometimes (as can be seen at the screenshot)

Could `A` have some other icon which doesn't ressemble the known "current location" one?
Could `B` maybe be a dark "current location" icon with a light background? Or a dark icon with a light border, maybe.

## Vespucci Version
0.9.9.1.1304

**Comment by simonpoole** [comment]
Can you give us the make, android version etc. of your device. Plus where you got the vespucci build from. 

Correct behaviour is that the "follow GPS button" (A) is dimmed and disabled when the display is centred on the current position, non-dimmed and enabled when it is not. See http://vespucci.io/help/en/Introduction/#using-gps or the on device help for how it works. (B) is the GPS related menu button (you can re-follow the GPS position there but using (A) is typically more convenient) .  

On every phone and tablet that we've tested on (and that is a lot) that works without issue, yours is the first that seems to have issues with the button rendering in a big way.

To increase the visibility of the menu buttons you can try the dark theme (light icons on a dark background), uncheck the corresponding "Light theme" option in the advanced preferences.

**Comment by simonpoole** [comment]
ping @naoliv

**Comment by naoliv** [comment]
Sorry for the delay.
Vespucci was installed from Google Play, using the beta channel.
The device is a Motorola Moto G2, with Android 6.0

It seems that by switching the theme it got better:
![](https://user-images.githubusercontent.com/982338/32906087-0a5bf4f4-cae3-11e7-917e-98801a0ba823.png)
Even if I switch back to the light theme:
![](https://user-images.githubusercontent.com/982338/32906085-0a36eace-cae3-11e7-864d-dcd50a7bab49.png)

But after taking a look at your diary post I saw that your icon is black:
![](https://wiki.openstreetmap.org/w/images/5/56/Screenshot_1510740239.png)

Should I be seeing it like this?

**Comment by simonpoole** [comment]
The button is provided by googles support library and isn't really any different than the zoom buttons (which are rendered OK). So right now I'm suspecting a corrupted install (I run Vespucci on multiple with 6.0 so it is not a general OS issue in any case).

The other weird thing is that none of your screenshots show the GPS marker. Wrt your final: question if the screen is c entered on the  GPS position the button is dimmed (you can see that effect on the zoom buttons by wither zooming completely out or in).

**Comment by simonpoole** [comment]
Two screen shots showing how it should look like:

GPS position centred (note I took the screenshot on an emulator without compass, on a normal devices the GPS position would typically be an arrow), "follow GPS" button disabled.

![screenshot_1510861277](https://user-images.githubusercontent.com/1011860/32912294-e164b23a-cb0e-11e7-88d4-e4865eed8c2b.png)

Screen moved, GPS position not in the middle, "follow GPS" button enabled.

![screenshot_1510861259](https://user-images.githubusercontent.com/1011860/32912306-e8edc096-cb0e-11e7-8a84-c0b7b8459944.png)

**Comment by naoliv** [comment]
Uninstalled and reinstalled it from github's vespucci-0.9.9r1304.apk
I can see the same misaligned icon after starting it:

![](https://user-images.githubusercontent.com/982338/32910595-d6f4675a-caf0-11e7-8c5b-466d374dcb35.png)

After switching to the dark theme, restarting the app and pressing to center at my location:
![](https://user-images.githubusercontent.com/982338/32910633-ea2b07a2-caf0-11e7-86c2-24a50438e06b.png)

I can live with this if it only happens with me, without any problem.
The only thing that maybe could be improved is changing that second "location" icon (the `B` one) to another different icon? (from `A`)

**Comment by simonpoole** [comment]
Seems as if the actual icon that should always be black is being replaced for some reason on your device. Weird.

**Comment by simonpoole** [comment]
I've seen the same effect on a pixel 2 with 8.1. However still not really clear why it is happening.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/78bee00757a9e5de252b21fea04f209e20553a82

Sorry for this taking so long, I was overlooking a key bit of information: that this was happening in full screen mode.

The test version here contains the fix https://drive.google.com/drive/folders/0B9pKLmh8s1h8bFI5bGd4VnhYWkk?usp=sharing The fix will be included in the January update for the google play apk.
