### ISSUE TITLE
Next version and new numbering

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#627]
@MarcusWolschon @johnjohndoe @HolgerJeromin @Zverik 

Given that I'm close to the first larger merge for the next version, I've created a maintenance branch for 0.9.9 https://github.com/MarcusWolschon/osmeditor4android/tree/0.9.9-MAINT

While I'm currently using 0.9.10 as the version number, I would suggest, for marketing reasons to do a Mozilla and switch to 10.0.0 for release. This allows us to drop incrementing a separate build number for minor fixes and in general terms looks cleaner (naturally semantic versioning is largely meaningless for end user apps, but hey this is -marketing-). 

The jump to version 10 will make it clear just how long vespucci has been around and continuously improved.

Any comments?

**Comment by Zverik** [comment]
Good idea, Simon!

**Comment by HolgerJeromin** [comment]
I never remembered the amount of small numbers at a specific position. So +1 for easier "major" numbers :-)

**Comment by johnjohndoe** [comment]
Sounds good to me. 👍

**Comment by simonpoole** [comment]
Changed in https://github.com/MarcusWolschon/osmeditor4android/commit/a6c6ad37d50907b98d774df24f735c06a3efe569
