### ISSUE TITLE
Using Google Keyboard Autosuggest on "Key" results in a blank key, and lost data if the user fails to realise

### ISSUE THREAD

**Issue by aftertea** [MarcusWolschon/osmeditor4android#628]
## Vespucci Version
0.9.9r1304

## Device (Manufacturer and Model)
Samsung Galaxy Note 4

## Android Version 
6.0.1

## Behaviour/Symptoms
On the "Details" tab of a node, when typing a key, if you select the Google Keyboard suggestion, the key textbox is left blank, instead of the autocomplete that was selected being used.

## Expected Behaviour
Google keyboard suggestions are entered into the "key" field

## How to recreate

1. Tested using Google Keyboard
2. Add a new node. Touch edit. Swipe left twice to Details.
3. Type 'nite' 
4. In Google Keyboards autocomplete bar, select the correct spelling 'note'

## Actual Behaviour

- Google keyboard text is ignored and not entered into the "key" textbox
- Typed text is cleared from the "key" textbox
- Popup of (all?) options for the "key" textbox appears, covering the "key" textbox

Additionally, if the user fails to realise the key was not entered successfully (since the popup covers the textbox, they may not realise), and they type in the "Value", then return to the main screen, their "Value" text is deleted with no notification. 

## Crash dump submitted (no or yes + date)
No - A crash did not occur

## Any other potentially relevant information

- I generally enter the text using Google Keyboards "Swipe" type feature
- My phone also has the Samsung keyboard available. If I select that, the text box works (well!) as a drop down selection box that filters as you type

Related issues:

- https://github.com/MarcusWolschon/osmeditor4android/issues/559 may be an enchancment requesting allowing keyboard predictions to work
- https://github.com/MarcusWolschon/osmeditor4android/issues/571 Similar issue reported with keyboard "MessagEase", and closed as likely invalid.

**Comment by simonpoole** [comment]
As pointed out in #571 the text fields have android:inputType="textNoSuggestions"  set. IMHO not respecting this is clearly a bug in the Google keyboard. #559 would do exactly the opposite (always allow text suggestions).

Have you checked for any other reports of the keyboard misbehaving?

**Comment by simonpoole** [comment]
I'm able to recreate the "problem" as such, however given that both the UI element in question (an unmodified AutoCompleteTextView) and the keyboard just happens to be from the same company it is fairly clear where you should be creating a bug report.

**Comment by simonpoole** [comment]
@aftertea have you been able to find out anything more on the issue?

**Comment by simonpoole** [comment]
No feedback, assuming problem is fixed.
