### ISSUE TITLE
Selecting tags not working anymore

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#631]
Vespucci 0.9.10b1314 on Fairphone 2 with Android 6

When editing a way i can not select tags/table lines anymore with touch. Via menu works

**Comment by simonpoole** [comment]
Sorry, this is not quite clear. 

Are you referring to the "Details" ab in the Property Editor or are you referring to something else?

**Comment by HolgerJeromin** [comment]
Sorry. Yes, all checkmarks on the details page are not working

**Comment by simonpoole** [comment]
The code for that hasn't really changed between 0.9.9 and 09.10, and the issue isn't trivially repeatable here.

Is what you are seeing a general issue, or does it work for nodes and relations?

**Comment by HolgerJeromin** [comment]
My display does not react on touch events in this area of the screen (all pixel with 0 < x < 40 px). Tested with a paint debug program from fairphone itself.
Will change my screen with a replacement.

**Comment by simonpoole** [comment]
Sorry about that.
