### ISSUE TITLE
Wiki link change to https

### ISSUE THREAD

**Issue by erdmark** [MarcusWolschon/osmeditor4android#634]
When editing tags like namr of an object you can press Options and select "Map-Features-Wiki".
That opens the related wiki site in a browser. Currently this is done using http so an attacker not only knows username x is uploading that but also knows which device is interested in editing what (e.g. surveillance).
Correction should be easily done changing a variable to https.

**Comment by simonpoole** [comment]
The links are configured in the preset so any pull requests etc should go to the preset repo. In any case your assumption that a username and / or  password or similar is used when accessing wiki pages is mistaken. The other problem is that older android versions do not have root certificates for recent certs (Let's encrypt etc) and will have issues accessing such pages (for no really good reason).

**Comment by simonpoole** [comment]
The links are configured in the preset so any pull requests etc should go to the preset repo. In any case your assumption that a username and / or  password or similar is used when accessing wiki pages is mistaken. The other problem is that older android versions do not have root certificates for recent certs (Let's encrypt etc) and will have issues accessing such pages (for no really good reason).

**Comment by simonpoole** [comment]
This request was made obsolete by https://github.com/MarcusWolschon/osmeditor4android/commit/b936dc2b776f1dabb31924d6b13e65d860019984
