### ISSUE TITLE
Relation members are not visible

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#635]
On my fairphone 2 the member editor shows white text on white background for all but the role.

Android 6 patch level dec 1st :) 

This is not new but since many month (years?).

Vespucci 0.9.10b1314
![rps20171207_232528_902](https://user-images.githubusercontent.com/2410353/33741775-f47cd9c2-dba5-11e7-83d2-90b9cde6c460.jpg)

**Comment by simonpoole** [comment]
Can you switch to the light theme and see if you have the same issue? The green for the roles is interesting too.... Are you sure you don't have something installed that messes around with the colors?

**Comment by simonpoole** [comment]
OK I think I've found the bug, weird that nobody complained before, likely just a typo in the layout file for a member.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/c8aba50892f3e0321b9a7f7423fd7f2e58364ed3

**Comment by HolgerJeromin** [comment]
Thanks!

> The green for the roles is interesting too

Green? I dont know what you mean. 
Perhaps an artefact of the image resize.

**Comment by simonpoole** [comment]
Note you just missed the December update, the work around till at least the next beta update is to use the light theme.

**Comment by HolgerJeromin** [comment]
I lived with the bug since late 2016/early 2017. :)

So as i have now a workaround i can wait.
