### ISSUE TITLE
Error in translation strings in maxspeed long_text

### ISSUE THREAD

**Issue by kielein** [MarcusWolschon/osmeditor4android#636]
## Vespucci Version
0.9.10

## Android Version 
I noticed this while translating into Finnish on https://www.transifex.com/openstreetmap/presets/translate/#fi/presetpot/112986689?file=speed

## Behaviour/Symptoms
incorrect translation string

## Any other potentially relevant information
https://github.com/simonpoole/beautified-JOSM-preset/blob/master/master_preset.xml
line 52:        	<text key="maxspeed:backward" text="Max speed ←" long_text="Maximum speed in way direction specified in km/h" />
line 2692:            <text key="maxspeed:hgv:backward" text="Max. speed HGV ←" long_text="Maximum speed for heavy goods vehicles in way direction specified in km/h" match="key" />
line 2693:            <combo key="maxspeed:hgv:backwardward:conditional" text="Max speed HGV ← @" long_text="Condiditonal maximum speed for heavy goods vehicles in way direction specified in km/h"

The word "opposite" is missing in the long_text strings.

**Comment by simonpoole** [comment]
Thanks for the report @kielein  Note that this really belongs in the preset repo, but we can leave it here for now.

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/032ba3eb2f50b9a0b2b582cb960d2741f544f714
