### ISSUE TITLE
Validator preferences causes crashing of app

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#637]
## Vespucci Version
Vespucci 0.9.10b1324

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
Android 6.0.1

## Behaviour/Symptoms/Expected Behaviour/How to recreate
1. Remove all entries from Validator preferences except one re-survey entry
2. Set key "shop" and value to "*", max. age to "0" 
3. Press DONE and go back to the main screen.
3. The app immediately crashes when there are already downloaded data. If not, try to download view and the app crashes.

Next time, just visit Validator preferences and leave it without saving, just go back to the map and it crashes as well. Even removing of the entry doesn't solve the problem, you have to reset the app after that.

## Crash dump submitted (no or yes + date)
12.12.2017 (19:30 UTC+1) 2 reports containig email adress xxxxxxx
## Any other potentially relevant information
Language: cs_CZ

**Comment by simonpoole** [comment]
Yes there is an issue when either of the lists is empty. Workaround: leave a dummy entry in both (one that wont match).

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/9276e28407a54ef831dc9e0f61015a7f0cde6a83 Leaving the issue open till the next beta relase.

**Comment by simonpoole** [comment]
The build signed with my debug key here https://drive.google.com/drive/folders/0B9pKLmh8s1h8bFI5bGd4VnhYWkk?usp=sharing has both crashing issues you reported fixed (wou will need to deinstall the version from the playstore).

**Comment by kudlav** [comment]
Seems ok in vespucci-0.9.10b1325

**Comment by kudlav** [comment]
And I'd like to point out that Key label overflows to the input element when using Czech language.

![screenshot_2017-12-17-16-39-16](https://user-images.githubusercontent.com/11516259/34081107-d8f0df96-e348-11e7-9167-13f3d09870bd.png)

**Comment by simonpoole** [comment]
@kudlav please don't add unrelated issues to an existing one, thanks. THe layout issue has been addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/0ba13fa64995ea6fbb0b01aedfe309432b24356a
