### ISSUE TITLE
Unable to press GPS floating button more times

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#638]
## Vespucci Version
Vespucci 0.9.10b1324

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
Android 6.0.1

## Behaviour/Symptoms/How to recreate
1. On the earth view press GPS floating button (img1)
2. Zoom-in using + plus button
3. After few clicks to the plus button you are unable to see your GPS position (img2)
4. GPS button is disabled even your GPS position is not centered

## Expected Behaviour
GPS floating button shouldn't be disabled or zooming button should zoom-in to the GPS position not to somewhere else.

## Crash dump submitted (no or yes + date)
no, app doesn't crash

## Any other potentially relevant information
Language: cs_CZ

## Images
img1
![img1](https://user-images.githubusercontent.com/11516259/33905270-5e5a5cc6-df7e-11e7-9751-37ab74b894b6.png)

img2
![img2](https://user-images.githubusercontent.com/11516259/33905282-67ff9a7a-df7e-11e7-92ed-13bb95e2ef7d.png)

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/ca82078e8da4cf47a528ca434239bd40b00c20e5
