### ISSUE TITLE
Add empty name= as default in tag editor

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#639]
The auto complete feature derived from name (name mcdonalds -> fast food) is really powerful. 
But adding an empty name= tag would make it even more useful as we could have this workflow:
Add node, click edit, directly enter name -> amenity/shop... would be filled by vespucci 

As an empty tag line is not uploaded there would be no harm

**Comment by simonpoole** [comment]
I'm not quite sure how that would be different from the already possible workflow:

- long press 
- press "Name" button
- enter name
....

The downside is that you can't use it for closed ways, but that is going to be the exception in any case.

**Comment by HolgerJeromin** [comment]
I never found the long press special menu :-)

> but that is going to be the exception in any case.

I don't know what you mean by that?

**Comment by simonpoole** [comment]
> I don't know what you mean by that?

If you draw a building or something like that ...
