### ISSUE TITLE
add report bug button like in JOSM

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#640]
JOSM has a very nice button linking to bug tracker and prefilling debug data like program version.

Having something like that in Vespucci would be great to avoid repetitive filling bug report data.

## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

0.9.10b1324

## Device (Manufacturer and Model)
(required)

Xiaomi Redmi 4

## Android Version 
(required, please indicate if you are using a custom version)

6.0.1

## Behaviour/Symptoms
(required)

## Expected Behaviour
(required)

## How to recreate
(required)

## Crash dump submitted (no or yes + date)
(required)

## Any other potentially relevant information
(optional)

**Comment by simonpoole** [comment]
This is on the "todo" list but requires an issue tracker that people can use with their OSM login/OAuth 1.0a first (all other solution create essentially anonymous reports which are not really useful).

**Comment by matkoniecz** [comment]
Even version that works only after logging into github would be useful.

**Comment by simonpoole** [comment]
Pushed back after some further investigation.

**Comment by simonpoole** [comment]
Functionality added in https://github.com/MarcusWolschon/osmeditor4android/commit/28cd0b61e27dff9fe9daa959d476d1415e58476f

See https://github.com/MarcusWolschon/osmeditor4android/issues/806 for an example.

**Comment by matkoniecz** [comment]
Thanks!
