### ISSUE TITLE
weird pink with unclear meaning

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#641]
## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

0.9.10b1324

## Device (Manufacturer and Model)
(required)

Xiaomi Redmi 4

## Android Version 
(required, please indicate if you are using a custom version)

6.0.1

## Behaviour/Symptoms
(required)

Some time ago I noticed mysterious pink outlines around some shops. I guessed that it is market of objects not edited in long time that are volatile, frequently change and may be easily marked as surveyed by adding some more detailed tags.

Since latest update what may or may not be related I started to notice them around objects like administrative boundaries and street lamps that are neither volatile and without obvious normal tags to add to mark them as resurveyed.

## Expected Behaviour
(required)

Old objects are marked by pink outlines of are frequently getting outdated and are ready to mark as resurveyed without making useless edits.

## How to recreate
(required)

## Crash dump submitted (no or yes + date)
(required)

## Any other potentially relevant information
(optional)

I may be guessing meaning of pink outlines incorrectly.

**Comment by simonpoole** [comment]
You really need to read the release notes, not only, but particularly when you are using the beta version https://github.com/MarcusWolschon/osmeditor4android/blob/master/documentation/docs/help/en/0.9.10%20Release%20notes.md

Selecting the highlighted object will display what is wrong with it, in particular you shouldn't see anything for street lamps,, except if the preset that they correspond to has an error. The default setting current check for name, opening_hours and wheelchair tags,. Further the age check runs on shops and a small selection of amenities.

**Comment by matkoniecz** [comment]
> Selecting the highlighted object will display what is wrong with it,

When and how it will be displayed? I tried again and looked for it and I see no place where validator explanation is available.

**Comment by HolgerJeromin** [comment]
There is this small text popup on the top of the screen after selecting

**Comment by simonpoole** [comment]
@matkoniecz alternatively just give us a link to such an element.

**Comment by simonpoole** [comment]
I suspect that it is an opening_hours tag on street lamps, that is IMHO a preset error as we in general don't know that and at best it should be optional.

**Comment by matkoniecz** [comment]
For example

https://openstreetmap.org/node/2711732137/history and other nearby street lamps

https://www.openstreetmap.org/way/239933569/history

https://www.openstreetmap.org/way/518694169/history


Problems remains after disabling custom presets. I never modified validator settings.

I get no popup on selecting linked elements.

**Comment by simonpoole** [comment]
Yes, see above: the standard JOSM/Vespucci preset had a recommended opening_hours Tag for street lamps that I've removed now.

BUT you should -always- (as in something like since 5 years or so) be seeing the toast on selecting an element,  See https://github.com/MarcusWolschon/osmeditor4android/commit/bb5e49c139d0408c123b8b2d34290621bca75cbd

**Comment by matkoniecz** [comment]
What about administrative boundaries? I linked over example above.

**Comment by matkoniecz** [comment]
Either toast is not working properly or I am missing something
![gif-171218_140210](https://user-images.githubusercontent.com/899988/34107425-11d5fff2-e3f4-11e7-8195-6711786daba8.gif) is a video of selecting https://www.openstreetmap.org/way/518930938/history#map=17/50.07950/19.94976

**Comment by matkoniecz** [comment]
As I mentioned I failed to notice any explanation from validator what is wrong. I am not remembering disabling or changing any validator related settings.

**Comment by simonpoole** [comment]
In the video the element is already selected, you should see the toast when initially touching it for selection.

**Comment by matkoniecz** [comment]
I am not getting such toast, at least for this object. Different crop of the same video.

![gif-171218_170657](https://user-images.githubusercontent.com/899988/34115569-efbf0dea-e40d-11e7-92d4-148e051bc0ba.gif)

**Comment by simonpoole** [comment]
If you go to the "Info" menu item once you've selected an object it will display the issues too, but that is a bit of a roundabout way to find that out (I've tested in Kraków and the main issues I've see are:

- admin boundaries without a name tag (arguably a mistake)
- natural=wood without a name, which should likely only be optional

**Comment by matkoniecz** [comment]
There is plenty of unnamed natural=wood and spamming noname is not helpful.

I am pretty sure that admin boundaries are named - on relations.

I have no popup blocker, I may try testing how it works on the same phone with different environment (other family members bought the same phone) of it is mysterious what is causing these issue.

**Comment by simonpoole** [comment]
I would say it is totally unclear what is going on ... do you see toasts from any other app?

**Comment by matkoniecz** [comment]
I will make a test app to verify what happens here.

**Comment by simonpoole** [comment]
I've created a separate issue for the Toast issue https://github.com/MarcusWolschon/osmeditor4android/issues/653
