### ISSUE TITLE
Offset server And OSMOSE Server are equal settings

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#642]
## Vespucci Version
Vespucci 0.9.10b1325

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
6.0.1

## Behaviour/Symptoms/How to recreate
1. Open settings -> Advanced settings
2. There is Offset server and OSMOSE Server option
3. They are both opening dialog for setting Offset server.

## Expected Behaviour
There should be two different dialogues allowing to set two different and independent servers.

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
Language: cs_CZ

![screenshot_2017-12-17-14-49-15](https://user-images.githubusercontent.com/11516259/34081085-67eefd6e-e348-11e7-9207-722951eaad87.png)

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/c7748be93ccfcf2f981ea1a601387c90f9983197
