### ISSUE TITLE
validator setting - dead checkboxes

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#643]
## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

0.9.10b1324

## Device (Manufacturer and Model)

(required)

Xiaomi Redmi 4
## Android Version

(required, please indicate if you are using a custom version)

6.0.1
## Behaviour/Symptoms

Check opt. Checkboxes in validator settings are grayed out and impossible to select.

## Expected Behaviour
(required)

Settings may be changed if displayed

## How to recreate
(required)

In my case - go to validator settings

## Crash dump submitted (no or yes + date)
(required)

## Any other potentially relevant information
(optional)

**Comment by matkoniecz** [comment]
![screenshot_2017-12-18-07-11-20-575_de blau android](https://user-images.githubusercontent.com/899988/34092293-a8828eb4-e3ba-11e7-88e5-fbb4b209de70.png)

**Comment by simonpoole** [comment]
That is intentional, you need to click on the entry and edit it in the form that is displayed then, I might change the layout to not show the checkbox itself, which should be clearer.

**Comment by matkoniecz** [comment]
Yes, churches are typically clickable. If Manning them clickable is not viable - maybe change display to text? "Mandatory"/"optional" or "enabled"/"disabled"? Text is not suggesting that one may toggle it by clicking.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/ffc6f8ed7fb6e6ff587616804d05999c25dccd66
