### ISSUE TITLE
stop considering opening hours and name as mandatory for parking

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#645]
## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

0.9.10b1324

## Device (Manufacturer and Model)
(required)

Xiaomi Redmi 4

## Android Version 
(required, please indicate if you are using a custom version)

6.0.1

## Behaviour/Symptoms
(required)

Parkings are mostly unnamed, opening hours are almost always 24/7 and tagging that is not useful.

**Comment by simonpoole** [comment]
This belongs in the preset repo (the name issue has been fixed)

**Comment by matkoniecz** [comment]
Moved to correct repo, except name part that was fixed (thanks)
