### ISSUE TITLE
after making wheelchair and opening hours tags optional in validator settings are sometimes ignored

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#646]
## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

0.9.10b1324

## Device (Manufacturer and Model)
(required)

Xiaomi Redmi 4

## Android Version 
(required, please indicate if you are using a custom version)

6.0.1

## Behaviour/Symptoms
(required)

For example https://www.openstreetmap.org/node/490986511/history is still marked in pink outlines and info lists missing wheelchair and opening hours tags as issues (note that it is not complaint about an old age of object).

**Comment by simonpoole** [comment]
The checkbox -adds- the option tags, ... you need to remove the check or fix the preset to avoid getting the warning (which I've done for natural=wood).

**Comment by simonpoole** [comment]
This belongs in the preset repo

**Comment by matkoniecz** [comment]
Maybe renaming "check optional" to "require also optional" during editing preferences would be helpful? Current "check optional" at least for me had clear meaning of "make check optional" what turned out to be wrong.

**Comment by simonpoole** [comment]
Wording change https://github.com/MarcusWolschon/osmeditor4android/commit/877e656ae7a29a88e2882e91175372a7e0e5d6ef
