### ISSUE TITLE
on start zoom in more

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#647]
## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

0.9.10b1324

## Device (Manufacturer and Model)
(required)

Xiaomi Redmi 4

## Android Version 
(required, please indicate if you are using a custom version)

6.0.1

## Behaviour/Symptoms
(required)

On fresh start on first use and sometimes on subsequent using Vespucci it is zoomed out to worldwide map.

I would expect that with available GPS it would zoom in more (at least to level of country/city maybe even further).

**Comment by simonpoole** [comment]
That really only happens if there is no existing data and saved state (or it can't be read). Selecting "Go to GPS position" from the GPS menu will however do what you want (not just center on the current position but zoom in).

**Comment by matkoniecz** [comment]
> if there is no existing data and saved state (or it can't be read).

So on fresh start after installing it will not zoom in?

**Comment by simonpoole** [comment]
It typically loads a lot faster (particularly with no  previous saved state) than phones get a GPS fix, so in reality it would start up, wait a bit, in the time you've already started doing something, then zoom to where ever the likely very rough initial GPS fix is .... you start screaming ....

**Comment by matkoniecz** [comment]
I may be wrong but what I have seen is Vespucci starting and showing introduction note. After clicking OK I got worldwide map with marked location.

**Comment by simonpoole** [comment]
In the situation described, you can simply use the "Zoom to current location" function (aka when you actually have a fix).
