### ISSUE TITLE
Lock icon disappears after unsuccessful authentication

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#648]
## Vespucci Version
Vespucci 0.9.10b1325

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
6.0.1

## Behaviour/Symptoms/How to recreate
1. Try to upload data to OSM Server without authorization
2. If this error occurs due to slow connection: "Timeout during authentication handshake, please retry.". The app return you to the main screen.
3. The lock icon is missing.
4. If you repeat that, the icon appears, with another try, it disappears, ...

## Expected Behaviour
Lock icon shouldn't disappears.

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
Language: cs_CZ

![screenshot_2017-12-20-11-49-20](https://user-images.githubusercontent.com/11516259/34248110-1adb0a82-e635-11e7-8cf4-8c9e2f34a4c1.png)
![screenshot_2017-12-20-11-48-38](https://user-images.githubusercontent.com/11516259/34248115-1d90f76e-e635-11e7-80ed-9c01b8707d6c.png)

**Comment by simonpoole** [comment]
The workaround for now is "then don't do that" ... we'll have a look at it for the next release.

**Comment by kudlav** [comment]
Persists in 10.0.2.

**Comment by simonpoole** [comment]
I haven't been able to repeat this in current builds, closing for now, if it does continue to turn up. Pls reopen.
