### ISSUE TITLE
Floating GPS button during authentication

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#649]
## Vespucci Version
Vespucci 0.9.10b1325

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
6.0.1

## Behaviour/Symptoms/How to recreate
1. Try to upload data to OSM Server without authorization. Login page is loaded.
2. Switch to another app.
3. Go back to the Vespucci.
4. Floating GPS button appears on login screen.

## Expected Behaviour
There shouldn't be Floating GPS  button.

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
Language: cs_CZ

![screenshot_2017-12-20-12-00-45](https://user-images.githubusercontent.com/11516259/34248224-840a41a8-e635-11e7-8fcd-fe5df2a59559.png)

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/issues/648

**Comment by simonpoole** [comment]
I've uploaded a test build of 10.0.2 to google drive, could you check if the behaviour is better now (for both bugs)? It is rather difficult to test against this as it is far too involved to mock the OAuth server.

**Comment by kudlav** [comment]
Floating GPS button during authentication #649 is fixed in 10.0.2
Lock icon disappears after unsuccessful authentication #648 persists in 10.0.2.
