### ISSUE TITLE
Dark theme text colour

### ISSUE THREAD

**Issue by JonnyTech** [MarcusWolschon/osmeditor4android#650]
## Vespucci Version
Vespucci (F-Droid) 0.9.9r1311-fdroid

## Download source
f-droid

## Device (Manufacturer and Model)
Wileyfox Spark+

## Android Version 
7.1.1 Custom ROM

## Behaviour/Symptoms
In dark (non-light) theme (set from `preferences > advanced preferences > enable light theme > disabled`), the dialog boxes (ie upload changeset) are all white because both the background colour and the text colour are set to white.

## Expected Behaviour
The text colour should be set to something different than the background colour in order for the text to be visible and readable.

## How to recreate
Disable the light theme then make a map change and go to upload dialog

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
None

![screenshot_20171230-105425](https://user-images.githubusercontent.com/3584732/34453615-a2980994-ed50-11e7-83ed-a04aef951601.png)

**Comment by simonpoole** [comment]
This only happens if you have switched to the dark theme and haven't restarted the app as required (exit with the back button and then start the app again).

**Comment by simonpoole** [comment]
I had a look at this today, sorry we will have to stay with exiting the app and restarting after a theme changes for now.

**Comment by hubgitti** [comment]
After switching to the dark theme and closing Vespucci using the back button, the info window (long press on a feature in locked layer) still is white and the text is invisible (also white?).

The upload window works fine.

Vespucci version: 10.0.5-fdroid

**Comment by simonpoole** [comment]
@hubgitti yes that is a separate issue from the one in described in this ticket, opening a new one in  https://github.com/MarcusWolschon/osmeditor4android/issues/682
