### ISSUE TITLE
Creating empty relation shows crash report dialog

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#654]
## Vespucci Version
10.0.5

## Download source
Google Play

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
6.0.1

## Behaviour/Symptoms & How to recreate
1. Select existing element
2. Choose "Create relation"
3. Select left arrow to get to the relation properties
4. Remove all entries under Members tab
5. Go back to the map
6. Crash report is generated

## Expected Behaviour
Empty relation shouldn't be probably created. I don't expect a crash.

## Crash dump submitted (no or yes + date)
yes (10.1.2018 21:33 GTM+1)

## Any other potentially relevant information
lang: cs_CZ

**Comment by simonpoole** [comment]
Thanks for submitting the report.

Just to be clear the app didn't actually crash? It just asked you to submit a report?

We should probably show an option to either not delete the last element or delete the relation.

**Comment by kudlav** [comment]
Hmm, actually it seems that the app doesn't really crash.
![2018-01-10-22-19-26_screenrecording](https://user-images.githubusercontent.com/11516259/34796088-bc188616-f654-11e7-8fa5-8b57864918ff.gif)

**Comment by simonpoole** [comment]
Yes, you get the crash report dialog because creating a empty relation could in principle be a real bug. However in this case it is really just something we have to fix in the UI.

**Comment by simonpoole** [comment]
Better handling added in https://github.com/MarcusWolschon/osmeditor4android/commit/98e8525627bc4fe8a35f705621cff86031a073e7
