### ISSUE TITLE
Unable to see whole "Position" dialog in Czech (cs)

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#655]
## Vespucci Version
10.0.5

## Download source
Google Play

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
6.0.1

## Behaviour/Symptoms & How to recreate
Vespucci in Czech (cs):
1. Select existing element
2. Choose "Position"
3. Position dialog appears
4. Unable to see "Lat." entry

## Expected Behaviour
There are two options:
- I can trim the translation text using transifex
- Or it would be better to make the dialog resposive

## Crash dump submitted (no or yes + date)
no, doesn't crash

## Any other potentially relevant information
lang: Czech (cs)
![screenshot_2018-01-10-21-55-34](https://user-images.githubusercontent.com/11516259/34795517-e6da3a5e-f652-11e7-9dea-947c1f58a1ad.png)
![screenshot_2018-01-10-21-55-43](https://user-images.githubusercontent.com/11516259/34795519-e6fb168e-f652-11e7-8777-73fe6ec31f6b.png)

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/f8b5771c4eba3b3325c5596c2d4cc43176402abe
