### ISSUE TITLE
SubMenus GPS / Trackverwaltung don't open

### ISSUE THREAD

**Issue by pebogufi** [MarcusWolschon/osmeditor4android#660]
## Vespucci Version
latest (10.1.0)

## Download source
https://github.com/MarcusWolschon/osmeditor4android/releases

## Device (Manufacturer and Model)
Samsung Tablet A 10.1 (SM-T585 LTE)

## Android Version 
7.0

## Behaviour/Symptoms
When opening GPS / Trackverwaltung 
I expect that menues 
	GPS-Tracks hochladen 
	GPS-Tracks exportieren
	GPS-Tracks importieren
are shown, but nothing happens.

## Any other potentially relevant information
On device Smartphone Samsung S5 Neo (SM-G903F), Android 5.1.1
everything works ok. (the expected menues are shown and work (GPS-Tracks importieren)).

I uninstalled the app and reinstalled 10.0.5 (same which work also on Smartphone), but same problem.
After new install I downloaded map of a smalll village (ok), all questions for permissions are anwered with "allow".
NO change whether GPS or WLan is on or off.

**Comment by simonpoole** [comment]
@pebogufi danke für den Report, kannst du noch ein Screenshot machen mit dem GPS Menu offen?

**Comment by pebogufi** [comment]
Screenshot vom Smartphone

![gps-trackverwaltung](https://user-images.githubusercontent.com/18628183/35515642-01b095ba-050a-11e8-80e3-59fbda3f6460.png)

**Comment by simonpoole** [comment]
Sorry meinte auf dem Tablett wo's nicht tut, eigentlich wäre sogar einfach ein Photo mit dem Handy gemacht besser.

**Comment by pebogufi** [comment]
Wenn ich auf Trackverwaltung tippe passiert gar nichts (beim Smartphone geht das menu weiter auf)

![20180129_153931](https://user-images.githubusercontent.com/18628183/35516056-09b94076-050b-11e8-9a81-9fc58d99977f.jpg)

**Comment by pebogufi** [comment]
... gar nichts ist falsch, der Hintgergrund von "Trackverwaltung" wird kurz grau, aber sonst passiert nichts.

**Comment by pebogufi** [comment]
...und ebenso bei 
Transfer / Datei 
und 
Transfer / Notizen/Fehler.

**Comment by simonpoole** [comment]
Kannst du mal in den 'Erweiterten Einstellungen' 'Geteilte Action Bar erlauben' abschalten aus der App raus und wieder rein und nochmas testen?

**Comment by pebogufi** [comment]
hat leider nichts gebracht.

**Comment by simonpoole** [comment]
Ich versuch das ganze mal soweit wie möglich einzugrenzen, spekulativ hab ich den Verdacht, dass die Menus off screen angezeigt werden.

**Comment by simonpoole** [comment]
Ich nehme an das Problem besteht auch wenn das Tablet um 90° gedreht ist? Sprich in landscape Mode?

**Comment by pebogufi** [comment]
Ja, hatte ich schon versucht.
Bin ab ca. 18:30 weg.

**Comment by simonpoole** [comment]
Also die gute News ... ich hab das jetzt im Emulator nachvollziehen können, und ja mein Verdacht, dass die Menus offscreen angezeigt werden hat sich bestätigt. Jetzt ist die Frage nur noch wieso ....

**Comment by pebogufi** [comment]
Super!

**Comment by simonpoole** [comment]
Im Emulator wenn ich ich die Menuleiste unten abschalte tut es aber mit dem Menu oben, bist du als du getestet hast ganz aus Vespucci raus (also back button bis es dich frägt ob du Vespucci verlassen willst), und dann wieder gestartet?

**Comment by pebogufi** [comment]
On 29. Januar 2018 18:31:26 MEZ, Simon Poole <notifications@github.com> wrote:
>Im Emulator wenn ich ich die Menuleiste unten abschalte tut es aber mit
>dem Menu oben, bist du als du getestet hast

 ganz aus Vespucci raus
>(also back button bis es dich frägt ob du Vespucci verlassen willst),
>und dann wieder gestartet?

Ja, genaus so, gerade nochmals versucht.

**Comment by simonpoole** [comment]
Also scheint fast eindeutig ein google Bug zu sein ab API 24/Android 7 und grosse Geräte. Ich habe mal einen ganz hässlichen Workaround gemacht, nämlich keine Submenus für Android Versionen ab 7 auf Tablets.

Eine angepasste Version ist hier https://drive.google.com/open?id=1xg-ML80lNn48BSFwNtfGJcIsmdICdnEc (mit meinem Debugschlüssel unterschrieben, du wirst also deinstallieren/reinstallieren müssen).

Man kann das Layout dann schon noch besser machen, braucht aber zuerst Icons etc.

**Comment by simonpoole** [comment]
Workaround in https://github.com/MarcusWolschon/osmeditor4android/commit/98890f42e28728b8be576c0bb0775285ba1a5a02

**Comment by simonpoole** [comment]
Fixed in 11.2 with more recent support library (not in the legacy flavor).
