### ISSUE TITLE
Improve dialogs layouts

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#661]
## Vespucci Version
10.1.0-4
but it's not caused by 10.x version
## Download source
Google Drive (Beta and Test Builds)
## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)
## Android Version 
6.0.1

## Text overlapping
I'm using Vespucci in Czech (cs_CZ) and these 2 dialogs are not displayed properly:

**1. Edit Note**
Click on existing note and you'll get a dialog where title and state are overlapped:
![screenshot_2018-01-14-16-25-50](https://user-images.githubusercontent.com/11516259/35595296-7a3d7108-0616-11e8-9849-bea51e38aa59.png)

**2. Upload? (GPS track)**
Record GPS track and go to: *GPS... ->Track management... -> Upload GPS track*
Visibility overflew into select box.
![screenshot_2018-01-14-16-25-25](https://user-images.githubusercontent.com/11516259/35595250-4e1e1078-0616-11e8-8833-a7649a5ad90d.png)

## Unable to see whole dialog
I'm unable to scroll to the _Zoom_ entries in _Edit layer entry_ dialog if the URL is too long. Even in English.
Go to: _Tools ->Add imagery from OAM -> Select something_
![screenshot_2018-01-30-23-47-30](https://user-images.githubusercontent.com/11516259/35596091-1ceff05e-0619-11e8-8500-587be015cb32.png)
... same with shorter URL:
![screenshot_2018-01-30-23-47-44](https://user-images.githubusercontent.com/11516259/35596093-20c99fc2-0619-11e8-8536-8dd036637999.png)

**Comment by simonpoole** [comment]
Layer dialog issue fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/fc3527f75726c7b11c9851a9f565351bc9670f73

**Comment by simonpoole** [comment]
Upload dialog fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/bc053d49c0ebc333ba8dc77ddf21140594e29a8c

**Comment by simonpoole** [comment]
Note / bug layout partially fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/0220114eaa7d6c86427f59db368ec5728741de23
