### ISSUE TITLE
"Name" field in Layer entry dialog

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#664]
## Vespucci Version
Vespucci 10.1.0-8
Valid for all 10.1.x versions.

## Download source
Google Drive (Beta and Test Builds)

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
6.0.1

## Add layer entry
Unable to create new layer. The form always says: "Name cannot be empty". Even when i copy all values form existing entry, there's always same error message. How does it should work?
![screenshot_2018-02-01-09-23-43](https://user-images.githubusercontent.com/11516259/35708290-a5eddaac-07ad-11e8-9833-cd0fda3fa22c.png)

## Edit layer entry
Unable to rename existing entry. Change name, hit Save button and nothing will be changed. It should work or it should be disabled.
![gif](https://user-images.githubusercontent.com/11516259/35708350-e987897a-07ad-11e8-8542-2aae8f3bc173.gif)

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
Language: cs

**Comment by simonpoole** [comment]
That was a regression (was trying to avoid duplicating two lines of code, my bad). Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/6a89d00855efaa56fa856050724f0eb2b75cd751 and 10.1.0-9
