### ISSUE TITLE
After failed upload note should be blue

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#665]
To reproduce: 

- close note
- enable WiFi to allow upload
- be outside WiFi range to ensure upload failure
- upload note
- upload fails, note should be blue as it is waiting for upload
- note is green

**Comment by simonpoole** [comment]
Which version did you see the behaviour?

**Comment by simonpoole** [comment]
Ah this is not really a bug. The problem is that there is no icon color coded for "closed but not uploaded", and it just happens to be that the "closed" flag takes precedence over the "changed" flag when determining which colot to display.

**Comment by matkoniecz** [comment]
> Ah this is not really a bug

I know, that is why I was following instructions for feature request.

> With which version did you see the behaviour?

10.1.0-1

**Comment by simonpoole** [comment]
Done in https://github.com/MarcusWolschon/osmeditor4android/commit/9e3a32c67509b5b2f28c9d7f7179fc750293e63f (the icon could be improved on though)
