### ISSUE TITLE
Attempting to use Geoportal aerial images crashes app, app crashes on every attempt to start it

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#666]
## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

10.1.0-1

## Device (Manufacturer and Model)
(required)

Xiaomi Redmi 4

## Android Version 
(required, please indicate if you are using a custom version)

6.0.1

## Behaviour/Symptoms
(required)
App crashes.

## Expected Behaviour
(required)
App is not crashing.

## How to recreate
(required)
Switch background tiles to Geoportal, exit settings.

## Crash dump submitted (no or yes + date)
(required)
no, but https://gist.github.com/matkoniecz/cac1909b5b70371cb64550b3c8bc0484 is log of failure on restart and https://gist.github.com/matkoniecz/30f671f4606b8a5ba5c0349bb967d9cf is log after enabling Geoportal layer immediately after reinstall

I will be happy to follow any debugging instructions to provide more info.

## Any other potentially relevant information
(optional)

I encountered this crash several time before making this report and I allowed app to call home with crash info.

This bug is quite important as it block using aerial images in Vespucci (alternatives to Geoportal are useless in my editing due to low quality, I may as well edit without aerial images).

**Comment by simonpoole** [comment]
I'm fairly sure this was fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/ef4edf6897e270acfc6c9a4ed0a5cdf460a3a985

Can you retry with the current beta?

**Comment by matkoniecz** [comment]
Heh. I reinstalled, left beta, enabled beta, updated several times, but now reinstalling app once more worked.

**Comment by matkoniecz** [comment]
Thanks, now I no longer feel like I made a stupid mistake during debugging.
