### ISSUE TITLE
GPS unavailable in app

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#667]
## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

10.1.0-10

## Device (Manufacturer and Model)
(required)

Xiaomi Redmi 4

## Android Version 
(required, please indicate if you are using a custom version)

6.0.1

## Behaviour/Symptoms
(required)
App behaves like GPS signal is unavailable,

## Expected Behaviour
(required)
App is using GPS signal.

## How to recreate
(required)
No idea at this moment.

## Crash dump submitted (no or yes + date)
(required)
no

## Any other potentially relevant information
(optional)
Other apps are using GPS signal without issues, I see nothing relevant in Android log, I will try to debug situation later.

**Comment by simonpoole** [comment]
Can you check that the app has the location permission? That is about the only thing I can see being different at an app level.

**Comment by matkoniecz** [comment]
It had and has but now, during debugging attempt it started working again without any obvious reason.
