### ISSUE TITLE
Wrong osmose warning after "Download current view "

### ISSUE THREAD

**Issue by PontiacCZ** [MarcusWolschon/osmeditor4android#670]
When reporting issues, please use this template, if you are asking for an enhancement you can delete the text.

Please note that some components are maintained in upstream repositories and relevant issues should be reported there, these are specifically:

* background and overlay layers: https://github.com/osmlab/editor-layer-index
* presets: https://github.com/simonpoole/beautified-JOSM-preset
* opening hours user interface: https://github.com/simonpoole/OpeningHoursFragment

## Vespucci Version
10.0.5

## Download source
Google Play

## Device (Manufacturer and Model)
Motorola Nexus 6

## Android Version 
Android 7.1.1

## Behaviour/Symptoms
After downloading current view from area http://www.openstreetmap.org/#map=19/49.10386/17.50663 an intersection node was displayed as a yellow bug. After tapping it the first line says:
"Osmose: Duplicated node without tag".
That was true. I merged those nodes using ID (I was sitting at a PC) and then tapped again in Vespucci "Download current view" to refresh the data. But it still displays the yellow bug with the same warning message.

![image](https://user-images.githubusercontent.com/9153595/36260657-5cfd8ca6-1262-11e8-8aac-b688a4704379.png)

## Expected Behaviour
Refresh the data from OSM database and get rid off the yellow bug and the no longer relevant warning.

## How to recreate
Not sure if that's possible. Looks like cached data in my Vespucci and maybe your download will be OK. The link to the are is above.
This is how it looks on my device:
![image](https://user-images.githubusercontent.com/9153595/36260570-1c18f4d2-1262-11e8-99e7-4b5dabfc098b.png)

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
(optional)

**Comment by simonpoole** [comment]
I believe that is a misunderstanding, the OSMOSE bugs are retrieve from the French OSMOSE site they regenerate their data I believe roughly once per day. So either you need to close the bug and upload it, or check after a day or two (iirc you may need to reset the OSMOSE data manually).

**Comment by PontiacCZ** [comment]
I see, thank you for clarifying. I did "Download current view" now and no changes on the battlefield, the bug's still there.

I have gone through the settings and switched off the OSMOSE errors/warnings/minor issues in Advanced -> Filter for Notes / Bugs so I am okay now. This thing is apparently not reliable.

The only questing remaining is why it is by default on....

**Comment by simonpoole** [comment]
As said the conventional way of removing the bugs that you know are no longer valid or have fixed is to close them.
