### ISSUE TITLE
taginfo.json's icon_url's destination is missing

### ISSUE THREAD

**Issue by goldfndr** [MarcusWolschon/osmeditor4android#671]
Currently, [the taginfo.json file](https://github.com/MarcusWolschon/osmeditor4android/blob/master/taginfo.json) has a "icon_url" near the top pointing to "https://raw.githubusercontent.com/MarcusWolschon/osmeditor4android/master/res/drawable/osm_logo.png", which is resulting in a 404 (not found) error at [the taginfo site](https://taginfo.openstreetmap.org/projects/vespucci).

Around January 26 some directories were moved. The new location is "https://raw.githubusercontent.com/MarcusWolschon/osmeditor4android/master/src/main/res/drawable/osm_logo.png" or perhaps "https://raw.githubusercontent.com/MarcusWolschon/osmeditor4android/master/src/main/res/drawable/vespucci_logo.png" if the new logo is desired.

**Comment by simonpoole** [comment]
Thanks for the report (the directory change was 2017 or 16 btw), fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/125e66d91853ee53040da448c29d84222ca142ff

**Comment by goldfndr** [comment]
You're generating the taginfo.json in the app? Do end-users have the ability to create it? I wasn't aware that there was any use they could make of it.

https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/java/de/blau/android/presets/Preset.java#L2894 looks wrong to me, unless you're somehow defining appliesToClosedway as area and appliesToArea as area=yes. I'd expect appliesToClosedway to apply to way, not area, as far as taginfo is concerned. I'll admit that I haven't looked at the preset data.

**Comment by goldfndr** [comment]
Amendment to last comment: https://taginfo.openstreetmap.org/tags/highway=service#projects (last page) has Vespucci considering highway=service to apply to areas.

**Comment by simonpoole** [comment]
The preset parsing code currently has relatively strong links to Android for handling the icons so the dumping to taginfo format runs in an Android emulator (might change one day), but is not usable in any way in normal use.

The JSOM closed way preset object type is used for areas (together with multipolygon) , which as you probably know don't exist as actual OSM objects, which makes this all a bin handwavy. Wrt highway=service as you can see from the taginfo pages both the map features wiki page as the JOSM presets do exactly the same.

**Comment by goldfndr** [comment]
I see. Thanks!
