### ISSUE TITLE
https and tls 1.0 issues

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#672]
Java and Android have two issues with the current move towards https for everything:

- java will not follow a redirect from http to https automatically (even if automatic following of redirects has been turned on)
- android versions prior to 5.0 do not support TLS 1.1 and 1.2 by default and prior to 4.1 at all 

I've fixed the former for reading from the OSM API and for downloading presets, however there are plenty of additional places that need to be addressed (while the default URLs are now nearly all https, for the configurable ones, users can naturally set non-https destinations, so the problem doesn't go away).

This is further compounded by the lack of TLS 1.1 and 1.2 support, given that lots of sites are dropping tls 1.0.

Essentially we should be doing the following when opening a connection to a http based service

- determine if  it is an http or https url (we can't use the the automatic detection of HttpUrlConnection any more, see below)
- if it is a https url explicitly use HttpsUrlConnection and pass a custom socket factory as argument, see https://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/  
- do the same detection and action if we get a redirect to https after connecting to a http url 

Naturally the big thing to do is to drop support for all devices running 4.0 and older.

See https://github.com/MarcusWolschon/osmeditor4android/issues/305

**Comment by johnjohndoe** [comment]
@simonpoole, for your reference - I had to do the same [here](https://github.com/EventFahrplan/EventFahrplan/commit/ed0097f8f2e66916d6340ec4f2dedb2809e5559f).

**Comment by simonpoole** [comment]
Alternative way of addressing this might be to simply use okhttp for everything which seems to do all of this automagically.

See https://github.com/MarcusWolschon/osmeditor4android/issues/668 for something further to implement at the same time

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/5026bafc45c07e1ba8ff088a4bb8ff55113262a5 note #668 needs a per API config option that it makes sense, skipped for now.
