### ISSUE TITLE
exclude notes from selectable objects during splitting ways

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#673]
To reproduce:

- find/create note
- create way with its middle node near note
- select way
- select split tool
- select note and node

Expected: node is selected or if many objects are nearby list of selectable objects is not including notes

What happens: note is listed

**Comment by simonpoole** [comment]
That is a bug :-/

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/7bb43f5ae8ef651f51b69749240993d9fe677231
