### ISSUE TITLE
Upload dialog: History entries blocking view on comment text field

### ISSUE THREAD

**Issue by versat** [MarcusWolschon/osmeditor4android#674]
## Vespucci Version
Vespucci 10.1.0

## Download source
Google Play Store

## Device (Manufacturer and Model)
Sony Xperia XZ (F8332)

## Android Version 
8.0.0

## Behaviour/Symptoms
When clicking on the comment text field a list with the recently submitted comments and the keyboard are shown on the screen. The comment text field then is not visible any longer (at least when there are some entries in the comment history). I can not make a screenshot because then the history is not shown any longer (i guess because the focus is lost when the power menu is shown). The history is even shown when i type/delete something. I can only make it go away by clicking outside the history list. But as soon as i start typing again or clicking into the comment text field it opens again and blocks the view on the comment text field. So i have to type comments blindly.
What i can observe sometimes:
When the keyboard comes up from the bottom the upload dialog is moved up a bit. But the history list seems to be not moved up accordingly.

## Expected Behaviour
When the comment text field is selected i can always see it, at least when typing.

## How to recreate
Edit anything and open the upload dialog. Then click into the comment text field. Maybe this must be done some times so the history is long enough to block the view. Maybe it depends on the screen size. 

## Crash dump submitted (no or yes + date)
no, it does not crash

## Any other potentially relevant information
I'm not sure how to best solve this, there are several things that i can imagine that help.
Maybe the history list could be simply hidden as soon as i start typing in the text field.
Or maybe it is possible to make sure that the history list is always small enough to fit into the upper part of the screen (between top of screen/app window and comment text field).

I observe this issue since some (not many) versions. I think there was a rework of the upload dialog which might have caused this behaviour.

**Comment by simonpoole** [comment]
Which keyboard are you using?

**Comment by versat** [comment]
I am using the default keyboard delivered with the stock firmware which is SwiftKey.

**Comment by simonpoole** [comment]
Yes that is a known problem with SwiftKey, for now the workaround is to use a different keyboard. There are more general plans to refactor the upload dialog which should avoid triggering the broken behaviour of SwiftKey, see  https://github.com/MarcusWolschon/osmeditor4android/issues/658

**Comment by versat** [comment]
Do you know what exactly is broken with SwiftKey? This is the first time i hear this.
Until now i never had problems with SwiftKey and like the keyboard.
But i will have a look if there is a better keyboard for me (any recommendations?).

**Comment by simonpoole** [comment]
Exact reason is unknown, but the keyboard essentially needs to indicate how much space it will need and SwiftKey is obviously off. 

In any case you can easily switch keyboards on the fly once you have more than one installed, so it is not really a big issue (for exampel I often use AnySoftKeyborad, but there are literally dozens).

**Comment by versat** [comment]
Thanks, good to know.
I will try other keyboards and close this issue since it is not really an error in Vespucci.

**Comment by versat** [comment]
I have now tried Googles keyboard Gboard and AnySoftKeyboard. With all keyboards I have exactly the same problem. So it seems to be no problem with SwiftKey.

**Comment by simonpoole** [comment]
Interesting, note that you may have to start typing for things to work.

**Comment by versat** [comment]
Yes, typing does not help.
I can try to do a screenrecording if that helps. Do you know a recorder app for such a case? There are so many.

**Comment by simonpoole** [comment]
Don't think that there's a need for a recording as in any case it isn't something that IMHO we can do about outside of a refactoring to avoid triggering the issue in the first place (which implies simply having more space).

**Comment by simonpoole** [comment]
With the dual tab layout added in https://github.com/MarcusWolschon/osmeditor4android/commit/354eaa1e389ed541932488ac338986a023748e98 this shouldn't be an issue anymore.

**Comment by versat** [comment]
Great, thank you. Can't wait to check it out 😁

**Comment by simonpoole** [comment]
I hope that the beta of 10.2 will be available in a few days.
