### ISSUE TITLE
Too long text and keeping gps on

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#675]
Vespucci 10.1.0

Vespucci keeps gps on with a message in the android notification bar:
"Vespucci is logging a gps track or..." I can not see more
The gps log is off.

The message could not be expanded with the finger

**Comment by HolgerJeromin** [comment]
![rps20180308_134411_968](https://user-images.githubusercontent.com/2410353/37151685-ded530ce-22d6-11e8-9126-12822adcda9c.jpg)

**Comment by simonpoole** [comment]
It's the other way around really, we display a message as long as you are recording a GPS track or you haven't existed the app and still have auto-download of data or bugs enabled.

Except if you actually want to continue recording a track you should pause recording before exiting.

As to not being able to expand the message: we currently don't do anything special so you get the default Android behaviour, I can have a look if we can improve that now (the support library we are using now is a lot more recent than when that code was added).

**Comment by simonpoole** [comment]
Addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/5ca0c1444d117b0fdb5c227eef1b4e3925d62ea6

**Comment by HolgerJeromin** [comment]
Ah, auto download was the "problem".
good to know that the keyword is now visible.

Perhaps there is still a bug:
Start vespucci 
Auto download on => gps on
Back button, yes close  => gps off
Start vespucci => gps on
Ok

But:
Start vespucci 
Auto download on => gps on
Push home => gps on
Android square button with the recent apps, swipe away vespucci => gps on, ups
Start vespucci  => gps on
Back button, yes close  => gps on!

At least sometimes with my fairphone with android 6
