### ISSUE TITLE
Tanning establishment

### ISSUE THREAD

**Issue by debyos** [MarcusWolschon/osmeditor4android#676]
Dear All,

in presets, leisure=tanning_studio should be changed to leisure=tanning_salon
More info: https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dtanning_salon
Thanks in advance

Gábor

**Comment by simonpoole** [comment]
Wrong repo, but fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/1d66512ebde978624b3ac564943eeb82d138d561
