### ISSUE TITLE
location sensitive validation

### ISSUE THREAD

**Issue by westnordost** [MarcusWolschon/osmeditor4android#681]
I noticed in the [10.1.0 release notes](http://vespucci.io/help/en/10.1.0%20Release%20notes/) this:

> Geo-location sensitive validation
> 
> We've done some initial work on providing support for location sensitive validation, currently this is limited to missing "mph" units in speed tags in countries that use such units.

I now completed working on a library that I am going to use for StreetComplete to find the country of a geolocation quickly. If you are interested to use it, you are welcome:
https://github.com/westnordost/countryboundaries

In any case, feel freee to close this issue once you read it, I just wanted to inform you about it.

**Comment by simonpoole** [comment]
Hallo Tobias

Ich werde es mal anschauen, ich hab auch schon etwas Arbeit in Abklärungen für so was aufgewendet (vor allem wie weit man die Grenzpolygone vereinfachen kann mit noch guten Resultaten) , aber hab dann immer etwas Bedenken gehabt wegen dem Verhalten in Grenznähe. Etwas das hier natürlich häufig ein Problem wäre, Genf, Basel, Kreuzlingen um nur ein paar grössere Beispiele zu nennen.

PS: LGPL ist natürlich ein Problem.

**Comment by westnordost** [comment]
Die erwähnte Lib nutzt [diese Daten](https://josm.openstreetmap.de/export/HEAD/josm/trunk/data/boundaries.osm) aus dem JOSM-Projekt. Da abgemalt von der OpenStreetMap Karte, ist die Lizenz dieser Datei die ODBL.
Hier konvertiert [zu einem GeoJSON](https://github.com/ENT8R/blacklistr/blob/master/assets/boundaries.geojson) zum angucken. 
Das Python-Skript dass es konvertiert, habe ich [in diesem Commit](https://github.com/westnordost/StreetComplete/commit/12fc4c3fecc7d15b5a1df58d21d0318e0d0c72a1#diff-7a02f9fffb986cea1fad284155d6d63c) aus meinem Repository gelöscht, weil das GeoJSON von der erwähnten Lib abgelöst wird.

Ich erwähne die `boundaries.osm` aus dem JOSM-Projekt, weil sie die Grenzen *sehr* genau abbildet und doch, u.a. dank selektiver Genauigkeit (genauer Grenzverlauf in den Himalayas egal, Grenzen auf Wasser egal) dafür sehr klein, 883KB als GeoJSON. Die Daten nutzt meine Library halt auch, nur indiziert als binären Blob.

Ist LGPL wirklich ein Problem? Ich hatte gelesen, dass Vespucci als Gesamtpaket wegen bestimmter Abhängigkeiten nur unter der GPL weitervertrieben werden kann. Welche Lizenz wäre denn kein Problem?

**Comment by simonpoole** [comment]
Wegen Lizenz: das GPL betrifft nur das Default-Preset und ein paar noch nicht ersetzte Icons zum Preset (ob da die GPL überhaupt greift ist noch die andere Frage,),. Normalerweise versuchen wir ansonsten nur Apache 2.0 lizenzierte Sachen oder kompatibel zu verwenden.

**Comment by westnordost** [comment]
Also ich denke das sollte kein Problem sein, denn es ist ja **L**GPL. Das heißt nur wenn du den Source-Code der Library verändern möchtest, musst du es auch unter die (L)GPL stellen. Bindest du die Lib per Gradle ein, sollten sich daraus meines Wissens keine Verpflichtungen ergeben die über das hinausgehen was bei einer Lib die per Apache lizensiert ist, notwendig ist.
Jedenfalls denke ich mir das so, deswegen habe ich LGPL gewählt, weil ich möchte, dass der Source auch weiterhin "Share alike" bleibt.

Aber die Lizenzfrage spielt ja sowieso erst eine Rolle für den Fall dass du entscheidest, den location sensitive validation support auszubauen und zur Land-Bestimmung dafür diese Lib in Betracht ziehst.

**Comment by simonpoole** [comment]
Ich habe mich heute mal schlau gemacht, und die LGPL ist tatsächlich ein Problem im Android Umfeld mit statisch gelinkten Binaries. 

Wie immer gibt es natürlich viele verschiedene Stimmen und Ansichten, aber es scheint schon ein Konsens da zu sein, dass die weniger strikten Bedingungen der LGPL nur dann greifen wenn, die Library dynamisch gelinkt ist  / tatsächlich separierbar ist. Die Distribution in Source und zum selber builden wäre dann immernoch OK, eine APK via google, amazon oder f-droid nicht. 

Eine einfache Lösung hab ich grad nicht zur Hand, muss ich mir mal überlegen.

**Comment by westnordost** [comment]
Laut [FAQ](https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic):
> (1) If you statically link against an LGPL'd library, you must also provide your application in an object (not necessarily source) format, so that a user has the opportunity to modify the library and relink the application.

Das ist ja momentan möglich. Der Source von Vespucci ist hier auf GitHub für die Öffentlichkeit zugänglich, ergo hat jeder die Möglichkeit, die Library zu editieren und neu zu linken. Nur wenn der Source der App irgendwann nicht mehr öffentlich zugänglich ist, wäre das ein Problem. 

Die Apache-Lizenz erlaubt, dass Derivate unter einer anderen Lizenz veröffentlicht, also auch wiederum closed-source werden können. Erst dann gäbe es ein Problem mit statisch verlinkten LGPL-Libraries. Also, erst dann wenn (ein Derivat von) Vespucci _nicht mehr_ Apache-lizensiert ist.

Aber ich denke, dazu [=irgenwie dynamisch linken] eine Lösung zu finden kann man getrost denen hypotetischen Menschen überlassen, die diese App als Gesamtprodukt closed-sourcen wollen.

Das ist mein Verständnis dazu.

**Comment by simonpoole** [comment]
FIrst cut added in https://github.com/MarcusWolschon/osmeditor4android/commit/6d7f89d95fcede85aac31411eb3c5e0b71ffe159

**Comment by westnordost** [comment]
Übrigens, hast du das gesehen?
https://github.com/MarcusWolschon/osmeditor4android/commit/6d7f89d95fcede85aac31411eb3c5e0b71ffe159#commitcomment-29121523
