### ISSUE TITLE
Element info dialog has white instead of dark background in dark theme

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#682]
From @hubgitti

After switching to the dark theme and closing Vespucci using the back button, the info window (long press on a feature in locked layer) still is white and the text is invisible (also white?).

The upload window works fine.

Vespucci version: 10.0.5-fdroid

**Comment by hubgitti** [comment]
Thank you! Nice editor, a must have on every OSM user smart phone!

**Comment by simonpoole** [comment]
Thanks!

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/7c7a2abb9037c24694ef4231fa5af31689b263c4
