### ISSUE TITLE
wrong analytic of opening_hours

### ISSUE THREAD

**Issue by osmvermesser** [MarcusWolschon/osmeditor4android#683]
Hi !

i verwende aktuell die Version 10.1.2 .

Gestern habe ich folgenden Node kontrolliert: https://www.openstreetmap.org/node/2410714455

Dabei wurden mir folgende Zeiten angezeigt:

![moeller_open](https://user-images.githubusercontent.com/6803899/37754839-198973fa-2d9b-11e8-9e70-0200473e8683.png)

In JOSM wird aktuell folgendes angezeigt: Mo-Th 11:00-04:00, Fr,Sa 11:00-06:00, Su 11:00-03:00

Ich würde das in JOSM etwas anders schreiben - aber bis 30 Stunden ist wohl etwas falsch. .-)

Gruß Jan

**Comment by simonpoole** [comment]
Hall Jan, das ist richtig. Die OH Spezifikation sieht eigentlich vor das Zeiten > 24:00 auch so geschrieben werden als Endzeit, als Input unterstütze wir im beides solange die Zeit eindeutig ist, ausgeben tun wir (logischerweise) nur eine Variante.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/3a012b7287a6a3c3daaa3367119419d432bed6d0 ändert das verhalten, d.h. wenn der Abstand zwischen Start- und Endzeit < 24 Stunden ist wird die Endzeit als "normale" Zeit ausgegeben, ansonsten wie bis an hin. Allerdings finde ich das persönlich noch deutlich verwirrender als bisher.
