### ISSUE TITLE
Confusing Icon for Barrier:Cycle_Barrier/Hapshire_Gate

### ISSUE THREAD

**Issue by nurdafur** [MarcusWolschon/osmeditor4android#684]
Hallo

By chance I discovered that the Icon you use for Barrier:Hampshire_Gate looks like an interpretation of what in reality looks like a Bicycle-Barrier according to OSM-Wiki. 
Despite this the German text used for Barrier:stile is wrongly translated to Drehkreuz. Drehkreuz is a Barrier:turnstile. You better translate Barrier:stile as Tritt (singular) or Tritte (plural).

Kind Regards
Urs

**Comment by simonpoole** [comment]
Thank you for the report.

However please note that preset related issues should be created in the preset project https://github.com/simonpoole/beautified-JOSM-preset not here, as the issue template points out.

Translations for all the related projects are on transifex, however the German translation of stile would seem to be correct, it was however wrong for de_CH (fixed now, likely a C&P error) https://www.transifex.com/openstreetmap/presets/translate/#de_CH/presetpot/50934400?q=stile .
