### ISSUE TITLE
Unable to scroll on Properties tab when uploading changes

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#685]
## Vespucci Version
10.2.0-3

## Download source
Google Play

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
6.0.1

## How to recreate
1. Make some changes
2. Select Upload data to OSM server
3. On the second tab, I am unable to scroll down to see Close changeset tick box
On the first tab, scrolling is avaiable.
![screenshot_2018-03-25-23-43-53](https://user-images.githubusercontent.com/11516259/37880520-02d709aa-308a-11e8-9e9b-f1f8e3a128d6.png)

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
Language: cs_CZ

**Comment by simonpoole** [comment]
Does this only happen in landscape mode?

**Comment by kudlav** [comment]
There is not enought space to display everything only in landscape mode, so it's hard to answer.

**Comment by simonpoole** [comment]
Could you try 10.2.0-4 from google drive, it contains https://github.com/MarcusWolschon/osmeditor4android/commit/68915eb37b81460918a3d7986ad9cd5400780db5 which hopefully should fix the issue.

**Comment by simonpoole** [comment]
OK. closing in that case
