### ISSUE TITLE
GRAFCAN - Canary Islands WMS Layer

### ISSUE THREAD

**Issue by javiersanp** [MarcusWolschon/osmeditor4android#686]
## Vespucci Version
10.1.2-fdroid

## Download source
f-droid

## Device (Manufacturer and Model)
HUAWEI ALE-L21

## Android Version 
6.0

## Behaviour/Symptoms
GRAFCAN - Canary Islands WMS Layer is not present in the background image settings list.

## Expected Behaviour
This layer should be listed besides other Spanish data sources like PNOA or Catastro.

## How to recreate
Move the map to 28.46984/-16.25471 and open Settings > Background image

## Crash dump submitted (no or yes + date)
not apply

## Any other potentially relevant information

This layer is defined in 
https://raw.githubusercontent.com/osmlab/editor-layer-index/gh-pages/sources/europe/es/GRAFCAN-CanaryIslands.geojson
This is available within iD and Potlatch

**Comment by simonpoole** [comment]
EPSG:4326 wasn't supported in 10.1 it is in 10.2
