### ISSUE TITLE
consider dropping "delete way only" and "delete way and nodes" distinction

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#687]
In my experience JOSM handling of way deletion is perfectly OK.

In Vespucci I get irritating "delete way only" and "delete way and nodes" question.

In my experience it also highly confuses newbie mappers.

**Comment by simonpoole** [comment]
I believe the reasoning behind the question was actually to duplicate JOSM functionality, but without having to add a separate action for just deleting the way object.

**Comment by simonpoole** [comment]
Done in https://github.com/MarcusWolschon/osmeditor4android/commit/2766e2e008e4a65b56de6025851befb15a0a5113

**Comment by matkoniecz** [comment]
Thanks, Vespucci should be now be a tiny bit less confusing!
