### ISSUE TITLE
"delete way only" / "delete way and nodes" asked when it does not matter

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#688]
Potentially obsoleted by #687

When reporting issues, please use this template, if you are asking for an enhancement you can delete the text.

## Vespucci Version
(required, see advanced preference of debug information screen in the preferences)

10.2.0

## Download source
(from where did you obtain the app? google play store, amazon, f-droid, github, ...)

google play store

## Device (Manufacturer and Model)
(required)

Xiaomi Redmi 4

## Android Version 
(required, please indicate if you are using a custom version)

6.0.1

## Behaviour/Symptoms
(required)

1a) Select existing way, split it twice so new way with just two nodes is created.

1b) Create way with every node tagged

2) Select the new way.

3) Delete it

## Expected Behaviour
(required)

"delete way only" / "delete way and nodes" is not asked as both result in the same (no nodes are deleted)

## How to recreate
(required)

See above

## Crash dump submitted (no or yes + date)
(required)

no

## Any other potentially relevant information
(optional)

Deleting single section from way occurs quite often (at least in my editing) and this dialog is quite irritating, especially in cases where it changes exactly nothing

**Comment by simonpoole** [comment]
While the behaviour might be irritating, the actual example is rather constructed (that every node in a way is tagged).

**Comment by matkoniecz** [comment]
"each node tagged" is fairly rare, but deleting way with just two nodes (and start/end node are used by other ways) is fairly common in my editing.

Unusual with mapping from scratch but it frequently happens with editing existing data. For example during splitting area into two separate areas.

**Comment by simonpoole** [comment]
Moot after https://github.com/MarcusWolschon/osmeditor4android/commit/2766e2e008e4a65b56de6025851befb15a0a5113
