### ISSUE TITLE
editing MapRoulette tasks?

### ISSUE THREAD

**Issue by govvin** [MarcusWolschon/osmeditor4android#690]
## Behaviour/Symptoms
I would like to be able to open MapRoulette tasks on Vespucci.

## Expected Behaviour
Some of the available tasks on MapRoulette is simple (that's what the tasking manager hopes to focus on) but on mobile devices, editors are limited to just iD, and Vespucci is a much better editor on mobile.

## How to recreate
Not curretnly supported.

## Any other potentially relevant information
For example, this MapRoulette [challenge](http://maproulette.org/mr3/challenge/2994) requires a user to review particular edits, and extract information from the free text added by the original editor. This seems quite doable and mobile, a task that could easily worked on while you're on the move, without having to get the laptop out.

**Comment by matkoniecz** [comment]
Maybe it is just my grumbling and bad luck.. But my experience with trying to do anything with, Maproulette is that it is very buggy. What worse, reported bugs are ignored (unlike with say Vespucci or JOSM). I reported just some that I encountered with plan of reporting more later but given that ones that I reported are still waiting...

**Comment by govvin** [comment]
@matkoniecz I'm sorry to hear about your unlucky experience. I mostly work with MapRoulette tasks with JOSM, and I've yet to notice any bugs. It may depend on the tasks you're working though.

I feel that Vespucci is in a perfect position to fill a gap for a mobile editor that works with a micro-tasking manager. Within OsmAnd, I would share an area to Vespucci to edit polygons and more complex stuff.

**Comment by matkoniecz** [comment]
> I mostly work with MapRoulette tasks with JOSM, and I've yet to notice any bugs.

I was trying to create new challenges and solve tasks via their website. I was not trying it in JOSM, maybe I will do that (thanks for recommending it, I was unaware that it works properly!).

**Comment by simonpoole** [comment]
Pro memoria API documentation link http://maproulette.org/docs/swagger-ui/index.html?url=/assets/swagger.json

**Comment by simonpoole** [comment]
I'm currently working on this (no ETA though). The current implementation simply integrates maproulette tasks with Notes & Osmose bugs. With other words the selection is based on the current area not on the selection of a specific challenge. 

If somebody has a better idea pls speak up.

**Comment by mvexel** [comment]
@matkoniecz I'm sorry you have had a poor experience with MapRoulette. I think the project is now in better shape, both technically and in terms of responding to bugs. Let me know if there is anything I can do to help you get started with MapRoulette again. 

I am happy to support this integration in any way I can. I created a sibling issue over in the MapRoulette repository as an FYI for us.

**Comment by simonpoole** [comment]
@mvexel question is there a sandbox version of the API available anywhere?

**Comment by govvin** [comment]
@simonpoole Could you elaborate a bit? What does "the selection is based on the current area not on the selection of a specific challenge."  mean exactly?

**Comment by mvexel** [comment]
@simonpoole not currently but I opened https://github.com/osmlab/maproulette3/issues/461 for you. In the mean time, the back end is reasonably easy to stand up [using docker images](https://github.com/maproulette/maproulette2-docker).

**Comment by simonpoole** [comment]
@govvin When using maproulette conventionally you go to the website, choose a challenge that interests you and get a (random) task to work on, then the next and so on.  

The workflow I've implemented is: download tasks in your area of interest (maybe where you happen to be), select task from map, fix, choose next one and so on.

Obviously supporting the first workflow would be possible too, but likely it would make more sense to do challenge selection via the maproulette website and simply have a look at the integration when starting the editor. There is naturally no reason why we can't do both.

**Comment by govvin** [comment]
That sounds good @simonpoole . Thank you for elaborating.

**Comment by simonpoole** [comment]
@mvexel np, if there had been one already around I would have used that obviously.

**Comment by simonpoole** [comment]
https://twitter.com/vespucci_editor/status/1063866995517595648 is essentially more or less finished.

**Comment by simonpoole** [comment]
Merged in https://github.com/MarcusWolschon/osmeditor4android/commit/bd39b9c1df9499d24db53d629bff471a8333c922
