### ISSUE TITLE
WebView state lost after device rotaton

### ISSUE THREAD

**Issue by calbee633810** [MarcusWolschon/osmeditor4android#691]
## Vespucci Version
10.2 Release

## Download source
github

## Device (Manufacturer and Model)
Nexus 4

## Android Version 
Android 23

## Behaviour/Symptoms
Open Help in the menu, navigate through several links, such as click Tag filter. Then rotate device, WebView refreshes and roll back to its original page when open Help. It should persist its state after device rotation. It's annoying because user have to manually navigate to its expected state.

![screen shot 2018-04-14 at 8 15 51 pm](https://user-images.githubusercontent.com/38213896/38768079-aee27806-4020-11e8-8309-20aa0c945095.png)
Screenshot before device rotation

![screen shot 2018-04-14 at 8 15 59 pm](https://user-images.githubusercontent.com/38213896/38768080-b3f09602-4020-11e8-936c-def2abfdc1fb.png)
Screenshot after device rotation

**Comment by simonpoole** [comment]
Fixed (I hope) in https://github.com/MarcusWolschon/osmeditor4android/commit/8a0c2d73f984a839d60b6fa1e3accba04746ce88
