### ISSUE TITLE
Additional objects to render from data

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#694]
- [x] Tree rows
- [x] Turn restrictions
- [x] Road signs in general (add to presets)

**Comment by rich123** [comment]
- [ ] Speed limit sign nodes

Currently they show as blank nodes.

**Comment by simonpoole** [comment]
@rich123 icons on nodes are not determined by the style, but by the presets. If you want icons for traffic signs it is simply a question of loading a corresponding preset (with png icons).

**Comment by rich123** [comment]
Ah, ok, that explains it then.  The preset for speed limit signs is there, but it is the JOSM standard preset bundle, which uses SVG's.  I can fix this myself now that I know why  they are unlabeled.  Thanks.

**Comment by simonpoole** [comment]
I've included some support in the default preset now.

**Comment by simonpoole** [comment]
TRs added in https://github.com/MarcusWolschon/osmeditor4android/commit/772769be38ff245c088653fb1f79124e0aa1c677
Tree rows https://github.com/MarcusWolschon/osmeditor4android/commit/e1198eb8521455e003adb7823a3cfaa776bff597
