### ISSUE TITLE
incremental search in preset selection

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#697]
Current behavior:

to find some preset one needs to enter search term, select search and see results.

Proposed behavior:

after changing anything in the text field search is run and currently matching entries are displayed

It would reduce need for typing - maybe some entries are found faster than user expects? For example to find wall, just "wa" is needed. It would always remove one click (to trigger search)

**Comment by simonpoole** [comment]
Note this is fairly tricky and conflicts with the new auto-preset feature.

**Comment by matkoniecz** [comment]
> Note this is fairly tricky

I hoped that it would be as simple as "add listener, run entire search after every change in the textbox and show results is area displaying categories".

Feel free to close if that is not worth implementing.

**Comment by simonpoole** [comment]
It is not that it isn't possible, but probably to work reasonably requires steming and a larger index and some way of handling stuff (for example taginfo for which we can't reasonably incrementally search).

**Comment by simonpoole** [comment]
Wit https://twitter.com/sp8962/status/1162459329112547330

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/2850edc680a0f32570024e445ba29335950f6af0

**Comment by HolgerJeromin** [comment]
Will probably solve #722 too
