### ISSUE TITLE
Preset icon not rendering on node in map

### ISSUE THREAD

**Issue by rich123** [MarcusWolschon/osmeditor4android#698]
When reporting issues, please use this template, if you are asking for an enhancement you can delete the text.

Please note that some components are maintained in upstream repositories and relevant issues should be reported there, these are specifically:

* background and overlay layers: https://github.com/osmlab/editor-layer-index
* presets: https://github.com/simonpoole/beautified-JOSM-preset
* opening hours user interface: https://github.com/simonpoole/OpeningHoursFragment
* name-related tag suggestions database: https://github.com/osmlab/name-suggestion-index

## Vespucci Version
10.2.4

## Download source
google play store

## Device (Manufacturer and Model)
Lenovo, Moto E4

## Android Version 
7.1.1 (Moto E4 stock, latest released update [March 1, 2018 security patch level])

## Behaviour/Symptoms
Loading preset file with png icon for speed limit sign does not render icon on map.  In #694 it was stated that node icons were rendered from presets containing png icons.

## Expected Behaviour
Icon should render on map.

## How to recreate
Load this attached preset file, add a node, use the preset to label it as a "speed limit sign".  
[test.zip](https://github.com/MarcusWolschon/osmeditor4android/files/1992443/test.zip)

The preset XML is lifted from JOSM's presets, with the icon changed to reference the included png instead of the original svg.  Loading the preset zip reports "Presets loaded successfully".  The icon does appear in the button on the "select a preset" screen, but does not appear on the node on the map.

## Crash dump submitted (no or yes + date)
No - app does not crash, so no crash dump to submit.

**Comment by simonpoole** [comment]
See http://vespucci.io/tutorials/presets/#extensions object_keys, for matching we need to know if the preset in question represents a rea l world object or if it is just a property preset.

**Comment by rich123** [comment]
Thank you.  Adding an object_keys attribute fixed the lack of icon rendering onto nodes.

Note that the URL on the page you reference that should like to the xmas-preset example currently returns 404 when clicked.

But had you not directed me to that attribute specifically I would never have determined that the object_keys attribute was responsible for providing Vespucci the 'link' info it needed to render the icon on the nodes from the text that is on that page.
