### ISSUE TITLE
The Address tool fills in more postcodes than is desirable in some countries

### ISSUE THREAD

**Issue by AndrewHain** [MarcusWolschon/osmeditor4android#699]
When reporting issues, please use this template, if you are asking for an enhancement you can delete the text.

Please note that some components are maintained in upstream repositories and relevant issues should be reported there, these are specifically:

* background and overlay layers: https://github.com/osmlab/editor-layer-index
* presets: https://github.com/simonpoole/beautified-JOSM-preset
* opening hours user interface: https://github.com/simonpoole/OpeningHoursFragment
* name-related tag suggestions database: https://github.com/osmlab/name-suggestion-index

## Vespucci Version
10.0.5-fdroid

## Download source
F-droid

## Device (Manufacturer and Model)
Samsung J3

## Android Version 
7.0

## Behaviour/Symptoms
The Address tool always copies the postcode from the previous addressed building if there is one.

## Expected Behaviour

Whether postcodes are copied should depend on whether it is suitable in the country being mapped.
Postcodes in some countries are more specific than towns. In the UK for instance:
Addresses on different streets have different postcodes.
Apart from very short streets, addresses on opposite sides of a street have different postcodes.
Blocks of flats generally have a postcode specific to the building.
Certain businesses such as most banks have a postcode specific to the business.

## How to recreate
Use the Address tool on an address with a postcode then another building.

## Crash dump submitted (no or yes + date)
Not a crash.

**Comment by simonpoole** [comment]
You can change which keys are used when automatically generating addresses by changing the "Address tags" preference,, in 10.0 the setting was near the bottom of the 1st Preferences page, in the upcoming version 11 it is in the Advanced Preferences (but documented).

**Comment by simonpoole** [comment]
No reponse, closing.
