### ISSUE TITLE
debug information screen is not present in the preferences

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#702]
## Vespucci Version
Vespucci 11.0 BETA

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
open setting to look for Vespucci Version for submitting ticket "required, see advanced preference of debug information screen in the preferences"

fail to find it anywhere

## Expected Behaviour

debug information screen is in the preferences

## How to recreate
see above

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
Vespucci 11.0 BETA Highlights mentions "The Authors and Licence screen has been move to the main menu, just as the Debug screen has."

I searched for it several times but I still failed to find it

**Comment by simonpoole** [comment]
This is mentioned in the release notes, but the issue template wasn't updated. Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/503b57b22988a635f4dca23e50ff5beb8499fc7c

**Comment by matkoniecz** [comment]
oh, main menu of Vespucci, not main menu of preferences
