### ISSUE TITLE
crash in preset search

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#705]
## Vespucci Version
Vespucci 11.0 BETA

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
I was unable to get opening hours editor.

## Expected Behaviour
All of following or at least some allow to get it:

- adding opening_hours tag from tag list editor (it showed as dropdown menu with some useless values)
- opening hours search in preset search triggers it directly (Vespucci crashed instead, I send a crash report with description within the app)
- opening hours search in preset search allows to select it what opens interface (Vespucci crashed instead, I send a crash report with description within the app)
- adding object with opening_hours in preset has interface editor in tag list or way to open it from tag list (result is the same as first position)

## How to recreate
I created amenity=drinking_water (it had posted opening hours info) and tried methods above

## Crash dump submitted (no or yes + date)
yes, from app

## Any other potentially relevant information
It worked in the past.

**Comment by simonpoole** [comment]
These are two different issues: the crash in the preset search which is due to a layout issue (needs to be investigated) and that currently none of the form based value entry methods are supported in the tag-list editor.  You need to switch to the form based editor for those, as has "always" been the case.. It is not impossible to add support however this will conflict with directly entering values (which is the point of the tag list).

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/cd6afb5d9e1b1f2f83d5f3e9319ea78c95940983 note that we actually don't find anything for opening_hours (which is what is expected).

**Comment by matkoniecz** [comment]
> You need to switch to the form based editor for those, as has "always" been the case

How can I do this? Some time ago I figured it out but I am unable to do it now (I searched for "form based editor" and found http://vespucci.io/help/en/0.9.8%20Release%20notes/ that mentioned that it can be disabled, but I see nothing in my settings that indicates that I did it)

**Comment by matkoniecz** [comment]
https://github.com/MarcusWolschon/osmeditor4android/blob/master/documentation/docs/help/en/Advanced%20preferences.md

**Comment by matkoniecz** [comment]
@simonpoole I had this option enabled for some reason.

**Comment by simonpoole** [comment]
disabled I assume?
