### ISSUE TITLE
Logo license

### ISSUE THREAD

**Issue by ghost** [MarcusWolschon/osmeditor4android#707]
I'm just wondering what the license of the Vespucci logo is, as i can't seem to find any reference to it in the license files (could very well just be me missing it).

**Comment by matkoniecz** [comment]
If there is nothing mentioned I would expect it to be also under the same license as entire project (see https://raw.githubusercontent.com/MarcusWolschon/osmeditor4android/master/src/main/assets/LICENSE.txt for that)

**Comment by simonpoole** [comment]
@Swedneck what is the actual issue?

**Comment by Swedneck** [comment]
The issue was simply what the license of the icon is, i don't know where it would've been better to ask this.

**Comment by simonpoole** [comment]
SO you customarily spend your time browsing repo, trying to determine what the licence of the logo is? I think not. Just say what you want to do with it and you'll get a reasonable answer.

**Comment by Swedneck** [comment]
well the reason i wanted to know the license of the logo was so i could determine if i could use the logo as a base for the one i'm making.
I figured it was better to figure out what the license was than to just ask "hi can i use this logo?".

**Comment by simonpoole** [comment]
That is completely OK if the end result is far enough away that it can't be confused with the one being used for this project (because if it wasn't we would have to change again, something that we would like to avoid obviously).

**Comment by Swedneck** [comment]
Well it's for an icon pack, and specifically meant to be an alternate icon for this app.
