### ISSUE TITLE
consider simplifying download menu

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#708]
Following is attempt to propose better download interface based on my experience and attempts to show how one may edit OSM using Vespucci. I am not entirely sure how valuable it will be, feel free to tell me that this kind of issue is not useful/very useful/something in between or should be reported in a different way (separate issue for every aspect? published as a diary entry?).

Vespucci offers multiple complex and advance download options, giving very powerful tools.

Unfortunately currently download menu is quite complex, even for somebody experienced in editing OSM I think that I can call myself experienced OSM mapper and I am still getting confused by it. Somebody new to Vespucci, especially somebody also who is also an OSM newbie will be really confused by it.

Some of more confusing interactions include:

 - many download options for a new user
 - "Download at other location" - at least in my experience I have no idea how it may be useful and I never used it. I am pretty sure that at least new mappers also do not need this particular feature
 - download deleting data. In areas with existing but laggy/expensive/intermittent mobile connection it may be useful to predownload area and keep uploading changes, sometimes download small area outside of prefetched area. Multiple times I deleted prefetched area as I forgot that I should use "Add current view" rather than "Download current view"
 - outdated bugs/notes staying forever on the map

Some of my ideas to solve problems above:
 - on downloading data clear bugs/notes in downloaded area and fetch updated data. it would allow to solve problems of outdated bugs staying forever even if notes were closed by other users (or the same user)
 - introduce expert mode like in JOSM or add special option (off by default) that would hide "download at other location" (I considered removing this option, but given that somebody spend time to develop it I assume that in some specialized workflow it is useful)
 - move autodownload to preferences (I may be wrong, but I assume that it is useful to toggle it on leaving/entering area with good mobile internet - so I would not expect it to be frequently used)
- consider reworking "download current view" - to make accidental deletion of prefetched data less likely (ask user "are you sure?", remove it and add "Delete downloaded map data"? add gap to prevent missclicks?)

**Comment by simonpoole** [comment]
I'm not quite sure what the issue with Notes/Bugs is supposed to be,, that is why there is a "Clear" function. 

In general I've been thinking of moving the data download to a similar model: the normal "Download current view" would always merge and the non-merging default would go away with the addition of a "Clear" function as with Notes. The "Download at other location" has essentially similar functionality  to the JOSM download dialogue, just as there likely not used often.

**Comment by simonpoole** [comment]
Some changes made in https://github.com/MarcusWolschon/osmeditor4android/commit/791160fb6a108c95c5c2a5dd633d6da0c896b053
