### ISSUE TITLE
resolved uploaded bugs rendered as blue + green

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#709]
Since update unresolved bugs are yellow and resolved are blue with green head.

IMHO green ones were better as display was less noisy.

**Comment by simonpoole** [comment]
Blue with green head == resolved but not uploaded, uploaded resolved bugs have remained green.

**Comment by matkoniecz** [comment]
Not for me, clearing bugs and downloading ones from OSM server has some blue + green.

## Vespucci Version
Vespucci 11.0 BETA

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

**Comment by matkoniecz** [comment]
As usual, I would be happy to provide any additional info that may be helpful.

**Comment by simonpoole** [comment]
Was a typo fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/b07cdf25f6cb6cdd3937f134ebebc2cbcab46977
