### ISSUE TITLE
question regarding beta vs release versions

### ISSUE THREAD

**Issue by Bubu** [MarcusWolschon/osmeditor4android#710]
Hey,
I wanted to ask what the policies for beta versions vs release versions are.

I noticed that under the github release section there is 11.0.0-3 marked as release version but named beta 3. Is this a beta version or not? 

![image](https://user-images.githubusercontent.com/105185/40232768-7296e1a8-5aa0-11e8-8322-96cba8158e01.png)

Also is there a  way to distinguish beta version form non-beta version by looking just at the git repo? I.e. is everything tagged with `a.b.c-x` supposed to be a beta whereas a tag like `a.b.c` is a release?

This way fdroids updater could filter the tags to not automatically add beta versions.

**Comment by simonpoole** [comment]
That was just two left thumbs (fixed). As to a fail safe: yes currently we are numbering beta versions with -n (hyphen and number).
