### ISSUE TITLE
make multipolygons easier to edit

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#712]
I noticed that any time I need to create/update multipolygon I just leave a note.

"create multipolygon" and "update multipolygon" from JOSM may be worth copying.

**Comment by matkoniecz** [comment]
Multipolygons are editable but not in a reasonable way. For example creation of multipolygon requires not only selecting ways and creating relation but also manual moving of tags and setting multipolygon roles.

**Comment by matkoniecz** [comment]
I will close it and open one with a better description in a future.

Maybe I should try more editing of multipolygons.

**Comment by matkoniecz** [comment]
That is 8 steps. In JOSM it is - select relation, select easy, select "update multipolygon".

**Comment by simonpoole** [comment]
How does it know which way to add?

**Comment by matkoniecz** [comment]
I updated my comment to fix broken word.

**Comment by MegaArthur** [comment]
It's pretty easy to deduce when a way is outer or inner

**Comment by simonpoole** [comment]
> 
> 
> > How does it know which way to add?
> 
> It's pretty easy to deduce when a way is outer or inner

Actually it isn't.

It requires
a) downloading all involved elements
b) correctly building rings from all elements (as far as that is unambiguous and there are no errors), including those with missing or wrong role values
c) then the easy part: determining if a ring is an outer or an inner ring and setting the role of the element from that.

In general the exericse is considered to be the most error prone and complicated subject matter in OSM, so it is only "pretty easy" compared say to building a nuclear bomb.

**Comment by simonpoole** [comment]
Basic support added in https://github.com/MarcusWolschon/osmeditor4android/pull/1266
