### ISSUE TITLE
Optional section seems to be ignored in presets for chunks

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#714]
Seems that there is a regression wrt handling chunks that are in optional sections.

**Comment by matkoniecz** [comment]
To confirm: I have "Check optional" disable in settings for name, after enabling it I get even bigger spam of requested name tags (as expected).

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/59ccd414cad3d5a576dcbfdf8ab59384990a3af1
