### ISSUE TITLE
Selfconflict, without a reproducable example

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#720]
## Vespucci Version
Vespucci 11.0.0-5

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
Edits conflict with itself (way deleted during editing is not deleted in changeset and blocks deletion of nodes)

## Expected Behaviour
Edit is not conflicting with itself

## How to recreate
No idea. Appeared several time, once crashed (I submitted crash using in-app reporter).

## Crash dump submitted (no or yes + date)
yes

## Any other potentially relevant information
for example I deleted all nodes of way without causing it to become deleted. On attempt to reproduce it I failed to achieve this effect.

**Comment by simonpoole** [comment]
Hmm nothing in particular that I was able to see from the crash dump, you seem to have a preset search running like made in the background (can you remember what you where searching for?) so there was only really two relevant messages.

When you uploaded the changeset did the upload information indicate that the way would be deleted?

"Appeared several times" - with the same way (that would be no surprise as Vespucci is detecting an inconsistent state or was this with different ways?

**Comment by simonpoole** [comment]
Question did you use undo on the way in question? The beta has a bug (that I just fixed) in restoring Ways and Relations that potentially could cause the issue.i

**Comment by matkoniecz** [comment]
> When you uploaded the changeset did the upload information indicate that the way would be deleted?

At least in two cases - yes. That is how I was able to discover that I "deleted all nodes of way without causing it to become deleted".

> "Appeared several times" - with the same way (that would be no surprise as Vespucci is detecting an inconsistent state or was this with different ways?

With different separate edits, in separate areas, with successful uploads between problems, boyth yesterday and today.

> Question did you use undo on the way in question?

No, but hopefully it will fix also this issue.

**Comment by matkoniecz** [comment]
I updated version to correct one (Vespucci 11.0.0-5). Sorry, I copied info from older report and forgot to update version.

**Comment by matkoniecz** [comment]
> can you remember what you where searching for?

Sorry, no. I see that "nothing found" n longer crashes Vespucci so I will report any new reproducible preset-search related crashes.

**Comment by simonpoole** [comment]
I don't think it is related to the undo issue, to clarify a bit more:

- you deleted the way with the normal delete function
- the way is correctly deleted in OSM (at least the example I looked at seems to have been removed)
- the problem is that you can't merge in new data because of the conflict

Question did you try the download immediately after deleting the way? There are one or two weird things that I don't quite understand yet about the situation.

**Comment by matkoniecz** [comment]
> you deleted the way with the normal delete function

In one case - I think so, but I am not 100% sure. I was trying to remove https://www.openstreetmap.org/way/30597068 and initially I was hit by edit conflict. Nodes were removed, way was not removed - and on each upload attempt I was getting message that I have edit conflict with one more note. In the end I scrapped edit.

I am nearly certain that I used delete way option as it had many nodes.

> the way is correctly deleted in OSM (at least the example I looked at seems to have been removed)

Yes, in all cases discarding local data and downloading from OSM allowed to continue editing.

> the problem is that you can't merge in new data because of the conflict

In that case yes.

**Comment by matkoniecz** [comment]
> you deleted the way with the normal delete function

In one case - no, I deleted way by removing all its nodes except one (easy to do by accident with way that have only two or three nodes) and noticed that no way deletion is listed in changes.

I attempted to reproduce it (with test edits like https://www.openstreetmap.org/changeset/59406943 ) but I failed.

In this case some of splitting, moving nodes, merging nodes and joining nodes to ways was involved.

> the way is correctly deleted in OSM (at least the example I looked at seems to have been removed)

No, edit that was supposed to include way deletion failed as it contained node deletions without deletion or modification of way that had this nodes.
 
> Question did you try the download immediately after deleting the way?

Quite likely, I like to make changes as small as possible especially as I was trying to avoid edit conflict bug that attacked me during park editing.

Again, discarding local data and downloading from OSM allowed to redo my edit and continue.

**Comment by simonpoole** [comment]
Ok maybe we have two unrelated issues here

- the crash dump involves way 30'597'068 which was correctly deleted in CS 59'402'486, but for some reason was still included in the download you tried to add, This could be due to replication lag, but would seem to be weird.
- what happens when you delete all nodes except one from a way.

**Comment by matkoniecz** [comment]
I am going to blame my phone, cosmic radiation and lag on OSM servers.
