### ISSUE TITLE
Search in preset results in two dialogs when hitting search with keyboard MessagEase

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#722]
## Vespucci Version

Latest play store beta

Debug menu entry crashes app, crash submitted  :)

## Download source

Play store

## Device (Manufacturer and Model)

Fairphone 2
## Android Version 

6

## Behaviour/Symptoms

Search inside the preset, for example "playground"
## Expected Behaviour

One Result dialog
## How to recreate

I got one dialog. Selected leisure playground 

After that the same dialog reopened again

**Comment by simonpoole** [comment]
The crash in the debug display isn't that just a misunderstanding? By pressing the button you simply trigger the same code that gets executed when a real crash happens.

Are you sure you didn't click twice in the preset search, it currently isn't debounced and will search twice ... or more if you click more than once.

**Comment by HolgerJeromin** [comment]
> The crash in the debug display isn't that just a misunderstanding? By pressing the button you simply trigger the same code that gets executed when a real crash happens.

The issue template in github wants the version number. In the settings i did not find the version information anymore. The issue template says:
""
So i thought that clicking the debug menu would give me the version string somewhere.

**Comment by HolgerJeromin** [comment]
> Are you sure you didn't click twice in the preset search, it currently isn't debounced and will search twice ... or more if you click more than once.

My keyboard MessagEase seems to fire two searches. (ref #571).
I have no double search when clicking the magnifier in the text row or switch to google default keyboard.

**Comment by simonpoole** [comment]
Sigh ... I was thinking of debouncing this (because with the online search it potentially takes longer and the danger of people starting the search twice increases). Will see what can be done.

**Comment by HolgerJeromin** [comment]
![rps20180604_125643_803](https://user-images.githubusercontent.com/2410353/40913983-c5152f30-67f6-11e8-8f04-080e7de81838.jpg)

**Comment by simonpoole** [comment]
The crashes in the debug and licence viewer activity are due to a theme issue, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/8f0358f05c1f49a4edd41280f47604d98600d49c Workaround till the next beta is out: switch to the light theme.

**Comment by simonpoole** [comment]
Debounced in https://github.com/MarcusWolschon/osmeditor4android/commit/478a8b3b0ce812824f34a5cb4b4ad84e764d8422 (no guarantee that it actually fixes the MessageEase issue).

**Comment by HolgerJeromin** [comment]
> Debounced in 478a8b3 (no guarantee that it actually fixes the MessageEase issue).

No, it does not :-(
