### ISSUE TITLE
Support `unsigned=yes` for disabling the “no name” warning

### ISSUE THREAD

**Issue by Ekleog** [MarcusWolschon/osmeditor4android#723]
I guess everything is in the title.

Thank you for your work doing this great application!

EDIT: After a bit more thought, let's put in https://wiki.openstreetmap.org/wiki/Proposed_features/Noname for a few more tags that could be considered as disabling the “no name” warning. `unsigned` being the first on the list it's the one I used, but others may be supported too.

**Comment by simonpoole** [comment]
Actually noname or validate:no_name should actually work for all objects that require a name, I'll consider adding unsigned (it is not quite the same thing though).

**Comment by Ekleog** [comment]
Hmm indeed it's not the same, that said I must say I personally regard vespucci as a mapping tool “on the ground”, preferring eg. iD when editing from home, for the comfort of using a computer. And when “on the ground”, I usually mostly care about whether there is a sign or no, even though asking locals is sometimes a solution.

Maybe with a toggle-able switch “passive surveyer”?

**Comment by simonpoole** [comment]
There's actually a more or less simple solution to this,. While currently the keys used for suppressing the "missing tag" validation are not configurable (_noname_ etc), what you can simply do is:

- add _unsigned_ to the tag check validation entry, change _name|ref_ to _name|ref|unsigned_
- add a non-optional check element for _unsigned_ to the preset item for the relevant road types (you would probably want this any way if you are using it a lot).
