### ISSUE TITLE
Improved warning handling

### ISSUE THREAD

**Issue by Ekleog** [MarcusWolschon/osmeditor4android#724]
So I'm just throwing an idea in the air here.

First, two data points: I'm mostly filling-in warnings with Vespucci, and I've only started contributing to OSM a few days ago.

Basically, I currently believe the warning system is wonderful: it helps beginners like me have an idea of things they could go survey in order to improve OSM (in a similar way to StreetComplete, but more feature-full in that it wouldn't be limited to tag editing).

But I think this warning system could be improved: there are places with *lots* of warnings, and places almost without them. Here is what I am thinking:

## Compile a list of wanted tags

This would include `wheelchair=*`, `opening_hours=*`, etc.

Basically, the format would be similar to this:
```
POI => name (weight 100)
POI, shop=* => opening_hours (weight 95)
POI, tourism=hotel => contact:phone (weight 95)
Street => name (weight 100)
Street => maxspeed (weight 95)
* (outdated) => ø (weight 90)
[etc.]
Street => surface (weight 5)
```

So for a set of preconditions on the type of item, define expected tags, with a weight that means the “importance” of the tag.

## Display warnings uniformly

Then, the idea is that on almost-unmapped areas, the most important is to map names, but in already-well-mapped areas, maybe the only thing missing is street surface (or adding items, but that's outside of the scope of the warning system IMO).

So what I think is that vespucci could basically display a uniform number of warnings: depending on the number of warnings, increase or decrease the weight threshold for which warnings are displayed. Obviously, when listing the warnings for an item, all warnings would be displayed (or even better editing tags on a warned-about item could highlight the missing fields).

This way, there are neither too many warnings (which could overwhelm the user), and at the same time there are always warnings (until the map is “perfect”, ie. needs only addition of new unmapped items -- and having a warning on streets' `survey:date` could even handle this case cleanly by integrating it into the warning hierarchy system)

What do you think about this?
Anyway, thank you for your wonderful work on this application!

**Comment by simonpoole** [comment]
I need to think a bit about this, in general Vespucci can't know if an area is undermapped or not on its own, so it would likely need a manual setting.

**Comment by Ekleog** [comment]
Hmm, so I was mostly thinking of adding more “warnings” in my initial post, and using weights to not overwhelm the user with too many warnings at once.

That said, I think with using the “survey:date” tag on streets it could warn (in C-mode) with messages like “this street has never been exhaustively surveyed, please add in relevant POIs and set the `survey:date` tag on it” (or an equivalent formulation if survey:date is too old, likely with a lower weight if following the initial post idea)?

**Comment by matkoniecz** [comment]
Add I understand this proposal it would not require Vespucci to guess how well area is mapped.

In every case some fixed number of warnings would be displayed, starting from the most important ones.

BTW

> well, StreetComplete exists too, but going survey the type of surface of roads isn't among the things that would motivate me).

Ate you aware that you can disable StreetComplete quests that are uninteresting for you?

**Comment by Ekleog** [comment]
That's exactly it ; with absence or out-datedness of `survey:date` being a relatively high-importance warning, so that Vespucci “implicitly guesses from provided data” (sorry, can't find a better wording) how well the area is mapped, and can tell people “please survey this street and add all relevant POIs before adding/updating the `survey:date` tag”

About StreetComplete, what I mean is that in my area StreetComplete only detects type of surface while Vespucci pointedly noted that a lot of shops missed `opening_hours` (and I haven't disabled the opening hours quest). And StreetComplete doesn't allow actually full-blown editing, which would be required for solving warnings of “this street has never been surveyed”. But you're right, this sentence was mean (having a simple-to-use editor is really important too) and added nothing to the post, so I've now edited to remove it, thank you and sorry about that!
