### ISSUE TITLE
Elementinformationen mit Verlinkung auf Webseite

### ISSUE THREAD

**Issue by osmvermesser** [MarcusWolschon/osmeditor4android#728]
Es wäre klasse, wenn man direkt aus den Elementinformationen auf die Objekt-Webseite im Browser wechseln könnte.

**Comment by HolgerJeromin** [comment]
Hab ich auch schon oft vermisst.
Geht bisher nur über die "chronik" funktion. Dies ist zwar die /history seite des elements, aber immerhin.

**Comment by osmvermesser** [comment]
Wege gibt es immer viele, aber es sollte doch immer relativ einfach sein und hier sollte es technisch nicht das Problem sein.

Jan

⁣Gesendet mit TypeApp ​

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/9cd3e71fbcc8d61e52a397579abcca82b0b8d0c1
