### ISSUE TITLE
Some Osmose bugs are displayed multiple times

### ISSUE THREAD

**Issue by RedEye2063** [MarcusWolschon/osmeditor4android#731]
## Vespucci Version
10.2.6

## Download source
google play store

## Device (Manufacturer and Model)
Samsung Galaxy A3 2017

## Android Version 
8.0

## Behaviour/Symptoms
Some Osmose bugs are displayed multiple times. 

![image](https://user-images.githubusercontent.com/40234965/41347729-dff45f18-6f0a-11e8-9027-040c5195579f.png)

It's only one bug! Not several bugs close to each other. 
Only certain bugs seem to be affected by this problem. Can't find any regularity.

## Expected Behaviour
Every bug should be displayed only once.

## How to recreate
Tap a yellow bug in unlocked mode

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
Do you have a specific example? And did you check on the osmose website?

**Comment by RedEye2063** [comment]
Ok, on the Osmose website the bugs appear several times, too. It seems there actually are multiple identical bugs on one object. So this is rather an Osmose issue. I'm closing the thread.
