### ISSUE TITLE
Vespucci crash when searching preset

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#734]
## Vespucci Version
11.0.0-8

## Download source
Google play (beta testing)

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
6.0.1

## How to recreate
1. Open new or existing node
2. Go to presets
3. Enter: "sweet" or "foo"
4. Submit
5. The app will crash

Tried both on WiFi and mobile connection.

## Crash dump submitted (no or yes + date)
3 times, 16.6.2018 17:07 GMT+2
containing email: "vladankudlac@gmail.com"

## Any other potentially relevant information
Language: cs_CZ

**Comment by simonpoole** [comment]
Thanks for the report, this has was reported in https://github.com/MarcusWolschon/osmeditor4android and is already fixed. I expect an updated beta likely next week.

**Comment by simonpoole** [comment]
The beta in the play store has been updated and now contains the fix.
