### ISSUE TITLE
vespucci not filtering out highway tagged with level tag in indoor mode without level tags

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#737]
## Vespucci Version
Vespucci 11.0.0-10

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
I enabled indoor mode, switched to displaying missing level tag. Objects with level tag got displayed.

## Expected Behaviour
On "-" indoor mode I do not get displayed object with level tag.

## How to recreate
May be related to public transport relations.

## Crash dump submitted (no or yes + date)
not relevant

## Any other potentially relevant information

affects for example https://www.openstreetmap.org/way/546946438

![screenshot_2018-06-20-14-35-07-644_de blau android](https://user-images.githubusercontent.com/899988/41659070-8f7b9a04-7498-11e8-8ecd-c23fd2a1f657.png)

**Comment by matkoniecz** [comment]
Edit note: affects for example https://www.openstreetmap.org/way/546946438

**Comment by simonpoole** [comment]
Yes this is a consequence of the way being a member of a relation that when you invert the filter is visible (and which makes sense as the only way you can select a relation is via its members).  

With other words the behaviour is as intended. There is a potential issue wrt relation handling in general in the Indoor mode see: https://github.com/MarcusWolschon/osmeditor4android/issues/738

**Comment by matkoniecz** [comment]
I am curious what usecase I missed.

> With other words the behaviour is as intended.

Can you give example of situation when showing way tagged with level is desirable in this mode?

> which makes sense as the only way you can select a relation is via its members

I am unable to imagine situation where it would be a good reason to show level-tagged ways in this mode (after all, one may change mode if wishes to select something with tagged level or one of relations where it belongs).

**Comment by simonpoole** [comment]
Example  any relation that is reusing a way tagged with a level, for example it might be an inner of a MP with non-building related properties.

It is imaginable to change the behaviour so that it would only show the way if there are no unfiltered members that are being displayed (but if that is less surprising is doubtful).

**Comment by matkoniecz** [comment]
> any relation that is reusing a way tagged with a level, for example it might be an inner of a MP 

Why way tagged with level would be used by MP that is not on the same level? Can you link some correctly tagged example?
