### ISSUE TITLE
Readme badges link to images itself rather than to metrics

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#742]
StreetComplete is using following code to display image that is a link at https://github.com/westnordost/StreetComplete/blob/master/README.md#download:

```[<img src="https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png" alt="Get it on Google Play" height="80">](https://play.google.com/store/apps/details?id=de.westnordost.streetcomplete)```

**Comment by matkoniecz** [comment]
my proposed links:

https://sonarcloud.io/component_measures?id=osmeditor4android&metric=bugs

https://sonarcloud.io/component_measures?id=osmeditor4android&metric=Maintainability

https://sonarcloud.io/component_measures?id=osmeditor4android&metric=Security

https://sonarcloud.io/component_measures?id=osmeditor4android&metric=Reliability

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/4a93fd1eab47bb696cca9a1d50bc742598103713 (ugly)
