### ISSUE TITLE
stop translating unstraslatable

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#744]
Maybe I missed something but  layer_geojson, layer_gpx keys are useless - AGAIK GPX and GeoJSON are not translatable in any language.

**Comment by simonpoole** [comment]
These all can potentially have transliterations in non latin scripts.

**Comment by matkoniecz** [comment]
I admit that my experience is extremely limited but I noticed that non latin scripts at least sometimes keeps given names (I know about it only because it was mentioned as one of issues with RTL writting systems - as RTL text may include LTR segments with names like that). Maybe it is not always done...

**Comment by simonpoole** [comment]
The thing is I can't give a definite answer either so rather err on the side of making it possible to add a script specific version (given that we "have" to externalize the strings anyway to make the linters happy).
