### ISSUE TITLE
untranslatable key offered for translating

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#745]
I opened https://www.transifex.com/openstreetmap/vespucci/translate/#pl/$/64995173?q=translated%3Ano

voice_left key was listed

on attempt to translate it "The resource of this source string is not accepting translations." was displayed.

It probably should not be offered in "Untranslated" view.

**Comment by simonpoole** [comment]
This seems to be a transifex issue, the whole file voice.xml is not available for translation currently and should not turn up in your UI.

**Comment by matkoniecz** [comment]
I can try reporting, are you aware whatever it is waste of time or not in case of transifex?

**Comment by simonpoole** [comment]
They have in the past responded to issues, so you could give it a try.

**Comment by simonpoole** [comment]
Setting on transifex website
