### ISSUE TITLE
Object selection disappears quickly in locked mode

### ISSUE THREAD

**Issue by RedEye2063** [MarcusWolschon/osmeditor4android#750]
## Vespucci Version
11.0.0

## Download source
google play store

## Device (Manufacturer and Model)
Samsung Galaxy A3 2017

## Android Version 
8.0

## Behaviour/Symptoms
In locked mode it is possible to tap and hold an OSM-object on the map to show its element information. When there are several objects close to or on top of each other a context menu appears that lists all the objects in the vicinity of the tap. Normally one would select an object from the list. But the context menu disappears after a fraction of a second so it is not possible to select an object.

## Expected Behaviour
When I tap and hold on the screen a context menu pops up where I can select an object to show element information. The menu stays until I select an object.

## How to recreate
In locked mode tap and hold an area on the display with several objects close to each other.

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
@matkoniecz @HolgerJeromin could you check if you see this issue in your devices? I can recreate on samsung phones with 8.0 but other devices don't seem to exhibit the issue (just as emulators running stock 8.0 don't show the problem).

**Comment by HolgerJeromin** [comment]
Works fine with Android 6 on Fairphone2.

**Comment by matkoniecz** [comment]
Works fine with Android 6 on Xiaomi Redmi 4 (finally a phone-specific issue that is NOT present on my phone!)

**Comment by simonpoole** [comment]
@RedEye2063 I wasn't able to find any specific bug report from other devs for any kind of similar issue, however as essentially the same code works for the context menu in non-locked mode, the long press/click seemed to be an obvious potential culprit. I've tried setting the "Touch and hold delay"  up from short (0.5s) to 1 second on both my samsung 8.0 devices and hey presto the problem went away. Can you test too? See https://support.google.com/accessibility/android/answer/6006989?hl=en

@matkoniecz & @HolgerJeromin thanks!

**Comment by RedEye2063** [comment]
Increasing the touch and hold delay solves the problem. Thank you!

**Comment by simonpoole** [comment]
@RedEye2063 I'm reopening for now for documentation purposes till I've created something better.

**Comment by hubgitti** [comment]
Just to clarify: The "Touch and hold delay" is a setting of the Samsung Android system. The problem also occurs on a Samsung Galaxy Note 8, Android Pie (Android v9), but the workaround solves the issue.

**Comment by simonpoole** [comment]
@hubgitti see the link from 8 months ago, the setting is not Samsung specific. However the too low default value is likely a Samsung bug.

**Comment by simonpoole** [comment]
This continues to be an issue on Samsung devices running 9.0.

**Comment by johnjohndoe** [comment]
## Vespucci Version
14.0.0 BETA 1

## Download source
Google Play store

## Device (Manufacturer and Model)
Pixel 2

## Android Version 
10 (Q)

## Behaviour/Symptoms
Context menu opens and closes immediately

## Expected Behaviour
Context menu opens and stays open

## How to recreate
Long tap an element in lock mode (see video recording)

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
![vespucci-touch](https://user-images.githubusercontent.com/144518/65183286-75886000-da63-11e9-9f77-785e381966b0.gif)

**Comment by alexs77** [comment]
I've got the same issue on a OnePlus 7. See #1176 

For me, the workaround with changing the delay does NOT work.

Description:
---

when there are multiple relations at one location and I long press to get information about what's there, I can shortly see a window "flash". it closes directly.

using Vespucci 14.1.4.0 on a OnePlus 7.

you can see a screen recording at https://photos.app.goo.gl/p94wpyvm3b2fZZkJ8

Device info:
---
<table>
<tr><td>App version</td><td>14.1.4.0</td></tr>
<tr><td>App version code</td><td>1407</td></tr>
<tr><td>Android build version</td><td>2003131900</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>GM1900_14_200322</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus7</td></tr>
<tr><td>Device model</td><td>GM1900</td></tr>
<tr><td>Device product name</td><td>OnePlus7</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by simonpoole** [comment]
@alexs77 do long presses work in "non-simple" mode for you?

**Comment by alexs77** [comment]
yes, in non simple mode, it works.

Simon Poole <notifications@github.com> schrieb am Sa., 6. Juni 2020, 19:44:

**Comment by simonpoole** [comment]
I believe I've tracked this down to an, at least, 9 year old issue that I've fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/6942dc9a962b1e6fb5184b4603f7a6284d34bb7a
