### ISSUE TITLE
Delete photo from Vespucci

### ISSUE THREAD

**Issue by Ekleog** [MarcusWolschon/osmeditor4android#751]
I'm taking quite a lot of geolocalized pictures with Vespucci. The missing feature I can't find is a way to delete a picture once it's been handled.

I've tried with both com.android.gallery and com.simpletools.gallery, and when opened in the gallery, the gallery doesn't show the option to delete the picture. And Vespucci doesn't provide it either.

Maybe there is a way for Vespucci to either add an option to delete a picture or (preferably) allow gallery apps to delete pictures? That'd be great for mapping based on pictures!

Thank you for your work anyway!

**Comment by simonpoole** [comment]
Assuming you took the photo via the photo menu button, you should just delete the photo(s) from the Vespucci/Pictures directory. If you don't have any kind of "file explorer" app available, essentially any of those available from google play or f-droid will do.

**Comment by Ekleog** [comment]
I can indeed, the problem is in my last mapping session I took 97 pictures, sometimes very close in location. Being able to remove them “on the go” while I actually map them would be great!

(FTR, it's for mapping quite heavy relations, so I'm doing it on JOSM with a big screen and a mouse when I come back, hence the big number of pictures)

**Comment by simonpoole** [comment]
Yes I can understand that, that's why I didn't close the issue :-)

**Comment by simonpoole** [comment]
Implementing this essentially requires integrating a photo viewer in the app. 

https://github.com/davemorrissey/subsampling-scale-image-view seems to be a good choice and supports a min-sdk of 14.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/06ac065f9c909dbf5cee18d7c5833665352f5117
