### ISSUE TITLE
Selectioning relations

### ISSUE THREAD

**Issue by Ekleog** [MarcusWolschon/osmeditor4android#753]
## Vespucci Version

10.2.6

## Download source

F-Droid

## Behaviour/Symptoms

When selecting a way, only the parent relation and the parent-of-parent relation are select-able.

## Expected Behaviour

All parent relations should be select-able, as this is the only way to select a relation that I could think of. Another option would be to make it possible to select a relation from the “Relations” tab of the tag editor.

## How to recreate

For instance, in ふじみ野, I am currently unable to select relation 清見 (id 8,434,124) by one of the borders of its sub-subareas, and I can't remember where I put the label point (and esp. don't really want to look for it when mapping the border of the area while walking the street :))

As usual, thank you for your work on Vespucci!

**Comment by simonpoole** [comment]
Yes, this is a bit of an issue, with the current architecture (property editor is a separate activity) it doesn't make a lot of sense to implement object selection via the members/parents tabs. This is one of the reasons I'm considering changing it to be a Fragment.

But it is clearly possible to add further up in the hierarchy relations to the selection list as the short term fix.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/bdad624a32ca55b2d669c5a8ecfdedc131f62579

**Comment by Ekleog** [comment]
Wow that was fast. Thanks! :1st_place_medal:

**Comment by simonpoole** [comment]
Well it on't be actually available before the next monthly update, which will likely be around SOTM and after my upcoming vacation ....

**Comment by Ekleog** [comment]
Yes of course, I meant it's 3 hours from bugreport to push :100:

**Comment by simonpoole** [comment]
11.0.1 that is rolling out now has the fix.
