### ISSUE TITLE
Bugs don't show up

### ISSUE THREAD

**Issue by Constable13** [MarcusWolschon/osmeditor4android#755]
## Vespucci Version
11.0.1

## Download source
github

## Device (Manufacturer and Model)
lg g3, d855

## Android Version 
lineageOS 14

## Behaviour/Symptoms
If I tap "download bugs for current view" nothing happens.

## Expected Behaviour
bugs should show up

## How to recreate
Try download bugs

## Crash dump submitted (no or yes + date)
no crash dump to submit

**Comment by simonpoole** [comment]
Can you check if there is an entry for the layer in the layer display? If no, then you should enable the layer in the preferences. The setting should have been retained when upgrading, but maybe something went wrong.

**Comment by Constable13** [comment]
Hi Simon, thanks for the quick reply. Well, one way or another I managed not to see the "enable bug and notes display" entry in the setting, sorry for that. It's working as it should right now.
Keep up the good work, your app is awesome!
