### ISSUE TITLE
Key "foot" is prefilled with the value "no"

### ISSUE THREAD

**Issue by RedEye2063** [MarcusWolschon/osmeditor4android#756]
## Vespucci Version
11.0.0

## Download source
google play store

## Device (Manufacturer and Model)
Samsung Galaxy A3 2017

## Android Version 
8.0

## Behaviour/Symptoms
When adding the key "foot" to an object tagged as barrier=gate the value "no" is filled in automatically. It's not possible to delete it in order to type a different value. It's the same behaviour as described here: #713. But in this case the dropdown isn't much good as workaround because the menu has only two entries: "yes" and "no".

By the way the same happens with other "barrier"-tags, too. E.g. barrier=bollard or barrier=stile.

## Expected Behaviour
Instead of prefilling the value "no" the regular dropdown for the "foot"-key should appear. With the values "permissive", "private" etc.

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
This is a preset issue and really belongs in https://github.com/simonpoole/beautified-JOSM-preset .

Currently the access fields for barriers are defined as default config check boxes (as they are already in the original JOSM preset), which have exactly two states yes and no.  So this is actually a different than https://github.com/MarcusWolschon/osmeditor4android/issues/713 it just coincidently looks the same.

Probably the best fix would be to use the general access tags chunks. See https://github.com/simonpoole/beautified-JOSM-preset/issues/101 for the issue in the preset repo.
