### ISSUE TITLE
plural handling in translations

### ISSUE THREAD

**Issue by roptat** [MarcusWolschon/osmeditor4android#759]
This is an issue in translation I spotted in transifex. For instance, these two sentences:

> You have %1$d unread OSM messages

> You have an unread OSM message

Although the distinction is correct in English, it is not the case in other languages. For instance in French (my native language), the first sentence is correct for quantities other than 0 or 1, while the second is only for 1. 0 is singular in French, but the application doesn't give me that possibility. Other languages like Japanese don't use plural forms, other like Polish have more than two possibilities.

With that said, it seems that Android supports proper plural strings, see https://developer.android.com/guide/topics/resources/string-resource#Plurals

Thank you!

**Comment by simonpoole** [comment]
I'll have a look at this for 11.2 or 12.  There are three strings in total that would profit from doing this properly if I didn't miss any, the one mentioned in the issue and the following two.

toast_imported_track_points
toast_imported_track_points_single_way_point

actionmode_one_object
actionmode_object_count

**Comment by simonpoole** [comment]
Done in https://github.com/MarcusWolschon/osmeditor4android/commit/eef2bf9968eb440a10a258b46a096e4aa06d76b7
