### ISSUE TITLE
Warning notifications after launching Vespucci

### ISSUE THREAD

**Issue by govvin** [MarcusWolschon/osmeditor4android#763]
## Vespucci Version
11.01

## Download source
F-Droid

## Device (Manufacturer and Model)
Pixel XL

## Android Version 
Oreo

## Behaviour/Symptoms
Warning notifications after launching Vespucci:
```Tile database issue
Attempt to invoke virtual method 'java.io.FileDescriptor android.os.ParcelFileDescriptor.getFileDescriptor()' on a null object reference
```

## Expected Behaviour
No such warning in previous versions

## How to recreate
It's just there every time I launch Vespucci, and the editor is still useful as far as I can tell.

## Crash dump submitted (no or yes + date)
Yes 2018-08-08

## Any other potentially relevant information
![image](https://user-images.githubusercontent.com/5821688/43808480-db86912a-9adf-11e8-82ed-0c5d0e85936e.png)
![image](https://user-images.githubusercontent.com/5821688/43808488-e176bdc6-9adf-11e8-85bc-8329a7ce87bc.png)

**Comment by simonpoole** [comment]
This loois like as if the tile database is corrupted see http://vespucci.io/tutorials/faq/#other-tile-database-related-issues for how to potentially fix the issue. I haven't looked at the crash dump yet but will do.

**Comment by govvin** [comment]
On the day I posted this issue, I was unsuccessful with clearing these messages. I tried Vespucci again today, it seems to have cleared itself of that.
