### ISSUE TITLE
please add barrier =  height_restrictor to presets

### ISSUE THREAD

**Issue by pebogufi** [MarcusWolschon/osmeditor4android#764]
https://wiki.openstreetmap.org/wiki/DE:Key:barrier
 height_restrictor 	Knoten oder Punkt 	Combine with maxheight=*. 

## Vespucci Version
11.0.1

## Download source
github

**Comment by simonpoole** [comment]
Hi this is a preset issue and should be opened in  https://github.com/simonpoole/beautified-JOSM-preset/issues , which I've just done: https://github.com/simonpoole/beautified-JOSM-preset/issues/105

**Comment by simonpoole** [comment]
Added in https://github.com/simonpoole/beautified-JOSM-preset/commit/dff2c5cf4b0dbe7868ff2b5ea8546fb77476fd4e
