### ISSUE TITLE
Unable to edit. Very faint lines in edit mode

### ISSUE THREAD

**Issue by govvin** [MarcusWolschon/osmeditor4android#765]
## Vespucci Version
11.01

## Download source
F-Droid

## Device (Manufacturer and Model)
Pixel XL

## Android Version 
Oreo

## Behaviour/Symptoms
![image](https://user-images.githubusercontent.com/5821688/44064269-bbc9b838-9f96-11e8-9782-110656f531f5.png)
Whenever I try to edit an area, it displays these very faint white objects (nodes, ways, etc.) which I couldn't  edit. This behavior started after my recent upgrade to Vespucii, where I also encountered another issue #763 

## Expected Behaviour
In previous versions, in edit mode, I'd see colored objects that I can manipulate

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
You have an (unconfigured) filter turned on (see filter icon in the middle of the right hand side). You can turn them on and off in the main menu.
