### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by omideleayo** [MarcusWolschon/osmeditor4android#772]
May I contribute to this project, by creating a FAQ document for the wiki section and the project site.

**Comment by simonpoole** [comment]
Hi, contributions to the documentation are always welcome, however the wiki hasn't really been used for multiple years and is massively out of date and it doesn't really make any sense to add stuff there. 

Current developer documentation is mainly in the documentation files on the top level directory, that is README.md, BUILDING.md, TRANSLATIONS.md, and DOCUMENTATION.md.

Further docs can be found on the vespucci.io website, which is generated from the files in the "documentation" directory.

**Comment by omideleayo** [comment]
Hello 
I can send a PR with the document which would be added to the project's website via the documentation directory.

**Comment by matkoniecz** [comment]
> however the wiki hasn't really been used for multiple years and is massively out of date and it doesn't really make any sense to add stuff there

Is there anything useful there? Maybe it should be deleted to avoid confusion?

**Comment by simonpoole** [comment]
There some stuff of historic value potentially :_)
