### ISSUE TITLE
CycleMap layer is missing API key

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#775]
I know that background and overlay layers are typically to be reported at https://github.com/osmlab/editor-layer-index - but it seems that each application should use its own API key

## Vespucci Version
11.0.4

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
After switching to Thunderforest OpenCycleMap "API Key Required" is visible in map tiles.

## Expected Behaviour
Normal tiles.

## How to recreate
Enable Thunderforest OpenCycleMap tiles.

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
I can submit a screenshot if that would be useful.

**Comment by simonpoole** [comment]
This is a known issue, my take on this would really be "then don't use it". 

The editor layer index (@bhousel @Marc-marc-marc @grischard ) afaik doesn't have a policy on the inclusion of such layers right now and further doesn't have a method to specify the requirement and corresponding place holders in the configuration. With other words: using API keys that are specific to an application requires special casing such layers in code (historically this has been limited to the Bing layer which can be justified for exactly such historical reasons).

**Comment by simonpoole** [comment]
Mentioning @gravitystorm for good measure.

**Comment by matkoniecz** [comment]
So it is something that should be changed first on editor-layer-index side?

**Comment by gravitystorm** [comment]
I'm happy to provide an API Key for Vespucci, if desired.

**Comment by simonpoole** [comment]
@matkoniecz well it would make a lot more sense than special casing TF layers, then the next ones that come along and so on, particularly considering that it apikeys are likely to be much more popular going forward.

Not to mention that having publicly available "global" OSM apikeys as we have for a number of layers dowsn't really make sense on first principles.

**Comment by grischard** [comment]
@gravitystorm would it be ok if all OSM editors shared one key, like we do for the mapbox layers? If all editors have to include their own api key mechanism, this will mean a lot of new code to write and debug. It also means that the editor layer index can't really check whether a layer works.

**Comment by simonpoole** [comment]
@grischard @gravitystorm there is naturally no reason that ELI couldn't use a set of its own API keys for testing. I don't think expanding the scope of a quite broken concept (OSM wide API keys) is a particular good idea.

**Comment by grischard** [comment]
You probably understand that from my perspective, with an inevitably limited amount of free time, I'd rather focus on something other than chasing API keys. It would also enable those who'd like every user to request an API key, creating additional barriers to mapping for no benefit to us.

The French orthoimagery server whitelists some user agents and referers, and only checks the API key for the others. I think that's the best way of doing it.

**Comment by gravitystorm** [comment]
> the problem is more that I would actually have to special case your layers instead of just having an apikey store (holding the keys for your layers) and the rest being driven by configuration. See osmlab/editor-layer-index#548

Sure, I understand. I just wanted to mention my offer, for clarity.

**Comment by simonpoole** [comment]
@grischard naturally the "chasing keys" bit already happens in the form of Mapbox and DG and maybe others rotating the respective API keys which isn't frictionless either, including the layers not working for end users that have "old" versions of ELI when that happens.

In any case nothing in my suggested PR stops us from having global public api keys (stored in the URL or separately) it just makes it possible to add layers where we don't have them to the index in a reasonable fashion (they would have to be skipped in automated testing, but that's life).

**Comment by simonpoole** [comment]
As nobody seems to be interested in fixing this properly outside of myself, I've overridden the relevant ELI entries in https://github.com/MarcusWolschon/osmeditor4android/commit/7edbbf98a0de0de260a0df76519158c6db8fff29
