### ISSUE TITLE
"Could not save bug changes" on attempt to close osmosis report

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#776]
I plan on testing further what is happening by looking at osmosis database before and after the close attempt

## Vespucci Version
11.0.4

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
Attempts to marks osmosis issues as false positives or close them result in an appearance of red "Could not save bug changes" toast message. I see no way to obtain info what went wrong.

## How to recreate
? - for me it happened with all osmosis issues that I tried to mark as fixed

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
I recently resolved issues with toast messages not appearing, it is possible that for me it was happening also in earlier versions

**Comment by matkoniecz** [comment]
one by one

**Comment by simonpoole** [comment]
It was actually simpler, the condition for determining  if to display the success message was inverted (for historic reasons), fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/7643b7ba5f9cb6d4eca8e10ac791fba3d9670e9b

**Comment by matkoniecz** [comment]
Thanks!
