### ISSUE TITLE
Vespucci crash when opening documentation, debug page or preferences

### ISSUE THREAD

**Issue by kudlav** [MarcusWolschon/osmeditor4android#777]
## Vespucci Version
11.1.0-1

## Download source
Google Play (beta testing)

## Device (Manufacturer and Model)
Samsung Galaxy A3 (SM-A300FU)

## Android Version 
6.0.1

## Behaviour/Symptoms/How to recreate
1. Open Vespucci app
2. Select "Help", "Authors and licenses", "Privacy", "Share position", "Preferences", "Camera" or "Download at other location"
3. Main app crashed, unable to go back, the app get's closed.

## Crash dump submitted (no or yes + date)
yes, ~21:30 30. 8. 2018  UTC+2 

## Any other potentially relevant information
lang: cs_CZ, en_GB

**Comment by kudlav** [comment]
Selecting node or way causes the crash as well.

**Comment by simonpoole** [comment]
This is an issue with the re-factored tag copy and paste, the saved data format has changed. Deleting the app data or a new install (which unluckily will make your settings go away ) for the app should fix the issue  for testing. Will add a fix for this for the next beta.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/2951f04c27a69ed55c8db4360375bace4cce1d7c

**Comment by kudlav** [comment]
Hi,
I've update app to 11.1.0.2.
Now I am unable to open Preferences even after clearing app data.

Crash report sent 31.8.2018 ~8:55 UTC+2

**Comment by simonpoole** [comment]
@kudlav that is unrelated to this bug and not a general problem, I'm opening a new issue for it:

https://github.com/MarcusWolschon/osmeditor4android/issues/778
