### ISSUE TITLE
Crash when sorting background layers

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#778]
From @kudlav

I've update app to 11.1.0.2.
Now I am unable to open Preferences even after clearing app data.

Crash report sent 31.8.2018 ~8:55 UTC+2

**Comment by simonpoole** [comment]
@kudlav this is an elusive issue that we've seen rarely on and off since v10. It likely only happens in specific circumstances. Can you remember what was displayed on the map screen (the area and which layer) when you tried to open the preferences?

**Comment by kudlav** [comment]
I opened the app (11.1.0.2) for the first time, went through intro, skipped downloading data and then tried to open preferences, see below:
![gif](https://user-images.githubusercontent.com/11516259/44901780-9cfd7500-ad08-11e8-9b38-2ecafa7ba54e.gif)

**Comment by simonpoole** [comment]
Do you have any custom imagery added to your configuration?

**Comment by kudlav** [comment]
I've reset the app data and I haven't modified any config file, so there shouldn't be any.

**Comment by kudlav** [comment]
I've removed `/Vespucci` folder and `/Android/data/de.blau.android`, reset data again, still persist.
report: 31.8.2018 11:55 UTC+2

**Comment by simonpoole** [comment]
https://drive.google.com/file/d/1a7IeDF3qiNQfFmq5E1t0oWyDzcuUejiH/view?usp=sharing is a debug build we some extra logging that might allow us to pin point which layers are causing the crash, if you can run and submit the crash dump that would be great.

**Comment by HolgerJeromin** [comment]
Could not install the apk. Does it has different signature compared to the play version?

**Comment by simonpoole** [comment]
@HolgerJeromin it is signed with my debug key.

**Comment by simonpoole** [comment]
@kudlav the only direct conclusion from the dump was that the the sorting algorithm seems to be slightly different which is likely why you see the crash on some devices and not on others. I suspect however that zooming right in makes the problem go away (because that changes the sorting), that's why there haven't been more reports).

In any case I've uploaded a 2nd debug build that removes the date criteria for sorting which I suspect might be the culprit, could you test when you have time.

**Comment by simonpoole** [comment]
Ok 3rd debug build should contain a proper fix. Would be grateful for a confirmation that it is OK.

**Comment by simonpoole** [comment]
OK that dosen't seem to fix it (found a device that show the issue at last)

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/8f5c6404d961587e9a4302f74ba2314f369c20f5 there is a build signed with my key on google drive.

**Comment by matkoniecz** [comment]
>  added the FIXED! label 7 days ago

Is it supposed to stay open?

**Comment by simonpoole** [comment]
Till the next beta apk without the issue,, yes.

**Comment by HolgerJeromin** [comment]
Newest Google beta has a fix for this. Thanks!
