### ISSUE TITLE
Bugs and grid can be removed in layer list window, but it is impossible to add display of them back in the same window

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#781]
I deleted tasks and grid from layer list. I expected to be able to add them back in the same menu, but it appears to be impossible.

## Vespucci Version
11.1.0-2

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
I deleted tasks and grid from layer list.
 
## Expected Behaviour
In the same menu I can add them back.

## How to recreate
Delete tasks and grid from layer list.

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
I can submit a screenshot if that would be useful.

**Comment by simonpoole** [comment]
THe current behaviour is documented i nhttp://vespucci.io/help/en/11.0.0%20Release%20notes/

**Comment by simonpoole** [comment]
Support add in https://github.com/MarcusWolschon/osmeditor4android/commit/85008bca46fba11de8a3ed04779140f9836558de
