### ISSUE TITLE
when objects are edited show unfilled mandatory tags from matching presets

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#782]
## Vespucci Version
11.1.0-5

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
values that are mandatory empty fields are displayed only on just created objects.

## Expected Behaviour
values that are mandatory empty fields are displayed also on editing existing objects.

## How to recreate
create highway=footway, leave edit menu, select object again and go to tag view

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information

This change will allow to quicker add missing data, as it should be far easier to fill data in one of present keys than to enter new one.

It would be especially useful for keys like surface for highway=footway, path, cycleway, track, residential.. where typing surface over and over again is quite boring (I know about StreetComplete but edit conflicts are not fun).

Previously misreported as https://github.com/simonpoole/beautified-JOSM-preset/issues/73

**Comment by simonpoole** [comment]
PS: on this, there is no reason to type surface in any case simply applying the preset -with- optional fields will provide the tag, simply with the "optional" tags there tend to be a lot.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/a04da6db50b68ad17073cc5cd27e5d235c744569
