### ISSUE TITLE
self_checkout vs. payment:self_checkout

### ISSUE THREAD

**Issue by mueschel** [MarcusWolschon/osmeditor4android#786]
Hi,
it looks like Vespucci promotes the use of "payment:self_checkout". Before, there were a few cases of "self_checkout" in the database. Neither of them is used often (I changed a few to the already existing tag, so current statistics are skewed), but I would prefer the option "self_checkout" - self-checkout is not directly related to methods of payment, it's just another thing the shop offers. What do you think about it?

**Comment by simonpoole** [comment]
There is naturally nothing stopping somebody from adding the tag manually or using a JOSM custom preset or private one to add the key. But it has definitely never been directly supported by the default preset.
