### ISSUE TITLE
called from intent after update results in no imagery

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#789]
Google play store updated Vespucci on my tablet.

After that i called Vespucci with the geo: intend from Osmand.
This worked, but i got no background imagery.
The list in the settings was empty.
After that i closed Vespucci and reopened it again.
I got the known "updating imagergy database" dialog, after that the background was back.

**Comment by simonpoole** [comment]
Do you you actually have imagery in the list? If no I would suggest updating the list over the net as a workaround for now.

**Comment by simonpoole** [comment]
Back from vacation and was able to test quickly. As far as I can see it behaves as designed: the existing imagery database will be used if you start via intent, and it will only be upgraded if you start via the normal launcher (which kinds of makes sense). 

This will not work if the upgrade was from pre-10.1 as there will be no database to retain (which will result in no background layer being selected, as there are none that can be selected). Simply starting Vespucci normally and then selecting a background layer should resolve the issue.

**Comment by HolgerJeromin** [comment]
> and it will only be upgraded if you start via the normal launcher (which kinds of makes sense).

Why that? As i understand it the database upgrade is an internal thing. Why not trigger with a start via intent, too?

> Simply starting Vespucci normally and then selecting a background layer should resolve the issue.

It did as i wrote. But got me puzzled a minute.

**Comment by simonpoole** [comment]
> 
> 
> > and it will only be upgraded if you start via the normal launcher (which kinds of makes sense).
> 
> Why that? As i understand it the database upgrade is an internal thing. Why not trigger with a start via intent, too?

Because it can take a fairly long time on slower devices, time that you likely don't want to wait for in such a situation (note that while the upgrade itself happens async, Vespucci can't actually run before it is finished), and except on the upgrade from pre-10.1 (which was months back) it shouldn't cause an issue at all (you simply don't have the most current imagery list).

**Comment by HolgerJeromin** [comment]
Yes, i rarely use my tablet for Vespucci, so probably it was pre-10.1 before. 
Thanks for clarification. I agree that via intent we should open as soon as possible.

I thought this logic was an oversight.
