### ISSUE TITLE
On selecting object from list of close ones describe closed notes as closed

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#793]
## Vespucci Version

11.1.3

## Download source

Google Play with beta enabled

## Device (Manufacturer and Model)

Xiaomi Redmi 4

## Android Version 

6.0.1

## Behaviour/Symptoms

Notes are not described as closed when listed on objects for selection

## Expected Behaviour

Open note entry starts, as now, from "Note", closed note from "Closed note" or "Note (closed)"

## How to recreate

Report multiple notes at one location (using maps.me frequently leads to multiple at exactly the same position).

Close one.

Download area in Vespucci, attempt to select still open one.

## Crash dump submitted (no or yes + date)

No

## Any other potentially relevant information

I may submit screenshot of that would be useful.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/eb207318710a0a83efc6887a14732c7f92ab8bd7

**Comment by matkoniecz** [comment]
Thank you, it will make Vespucci even better at note processing - and it is already the best tool for that!
