### ISSUE TITLE
Oreo adaptive icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [MarcusWolschon/osmeditor4android#794]
Please add support for icon shape

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

**Comment by simonpoole** [comment]
The icon change is just a nicety and not strictly necessary, the actually required updates were done in https://github.com/MarcusWolschon/osmeditor4android/issues/773 Note the XDA article is rather misleading and doesn't touch on the main reasons why devs have been reluctant to update short term.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/81f1f7fd389f4214039b3b34038e8d58156ec7d0 (easily the silliest one hour of wasted time on the whole project)
