### ISSUE TITLE
Presets: Display in alphabetical order

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#795]
# Current state
- Presets (`Vorlagen`) are show in **random** (?) order on the screen, see screenshot.

![vespucci-vorlagen](https://user-images.githubusercontent.com/144518/48301957-fbf41d00-e4f5-11e8-889b-ce21bcebc54f.png)

# Target state
- Presets (`Vorlagen`) are show in **alphabetical** order on the screen.
- I think this will make it easier to find a preset.
- The alphabetical order should not be hardcoded so it can be dynamically applied when the system language is changed such as from English to German.

**Comment by simonpoole** [comment]
Actually the order of preset groups and items is pretty deterministic :-), it's the order they are in the preset file. I was already mulling a bit over the issue and might add an attribute to the group elements to suggest sorting of the child elements. This is naturally mainly an issue for the groups that contain a lot of items without further structure, so mainly office and craft keys.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/78a7c47e7e33755c8617d64d0d781769bb97c97c
