### ISSUE TITLE
F-Droid support for new builds

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#796]
@Bubu & @roptat the 11.2 release build now generates 2 APKs:

- **osmeditor4android-current...** with support for Android 4.0 (SDK 14) and higher with a current support library version.
- **osmeditor4android-legacy...** with support for Android 2.3 (SDK 9) and higher with an old support library version.

If there needs to be a choice using the "current" flavor is preferable, both use the same Android version code (801) but that could in principle be changed.

**Comment by simonpoole** [comment]
It seems as if f-droid is also providing beta builds https://github.com/MarcusWolschon/osmeditor4android/issues/813 I don't have anything against that, except that the status really really really needs to be indicated.

**Comment by simonpoole** [comment]
@Bubu the 12.0.0.1 on f-droid should really really be removed (beta build with a big on older devices) anyway that can be done?

**Comment by Bubu** [comment]
Yes, will do that later today.

On December 18, 2018 9:05:23 AM GMT+01:00, Simon Poole <notifications@github.com> wrote:
>@Bubu the 12.0.0.1 on f-droid should really really be removed (beta
>build with a big on older devices) anyway that can be done?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarcusWolschon/osmeditor4android/issues/796#issuecomment-448131335

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by simonpoole** [comment]
Thanks a lot.

**Comment by Bubu** [comment]
Done. We need to figure out a way to prevent that automatic updating to betas in the future. I have no time to look into this right now though.

**Comment by simonpoole** [comment]
I do set the pre-release flag on such releases and in the past that never caused an issue (except naturally the one-time I forgot to do so).

**Comment by Bubu** [comment]
The pre-release flag is just a specific in githabs UI, it's not something the fdroid tools can see when looking at got commits and tags.

On December 18, 2018 10:43:57 AM GMT+01:00, Simon Poole <notifications@github.com> wrote:
>I do set the pre-release flag on such releases and in the past that
>never caused an issue (except naturally the one-time I forgot to do
>so).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarcusWolschon/osmeditor4android/issues/796#issuecomment-448159097

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by simonpoole** [comment]
The beta tags in our case have the fourth digit set to non-null, so
12.0.0.0 12..0.1,0 etc are proper releases, 12.0.0.1 12.0.0.2 12.0.1.1 would all be betas.

**Comment by Bubu** [comment]
That's good to know, thanks!

On December 18, 2018 11:01:01 AM GMT+01:00, Simon Poole <notifications@github.com> wrote:
>The beta tags in our case have the fourth digit set to non-null, so
>12.0.0.0 12..0.1,0 etc are proper releases, 12.0.0.1 12.0.0.2 12.0.1.1
>would all be betas.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarcusWolschon/osmeditor4android/issues/796#issuecomment-448164439

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Unamely00** [comment]
No Face No Name

**Comment by simonpoole** [comment]
@Bubu & @roptat there's a release of 12.0.0 available now so that could be distributed by f-droid however it doesn't seem to being picked up.

**Comment by roptat** [comment]
Version 12.0.1 was added here: https://gitlab.com/fdroid/fdroiddata/commit/499391c435b925b5603397a78b9ce20836c97341.

Do you mean that that wasn't correct, or simply that 12.0.0 is missing?

**Comment by simonpoole** [comment]
The build metadata was missing in general so it wasn't possible to determine if it was in the queue to be build or not.

**Comment by simonpoole** [comment]
@Bubu @roptat the build of 12.1 is currently failing https://f-droid.org/wiki/page/de.blau.android/lastbuild seems as if somebody needs to accept the licence for the build tools version we are using.

**Comment by Bubu** [comment]
On January 22, 2019 7:35:23 AM GMT+01:00, Simon Poole <notifications@github.com> wrote:
>@Bubu @roptat the build of 12.1 is currently failing
>https://f-droid.org/wiki/page/de.blau.android/lastbuild seems as if
>somebody needs to accept the licence for the build tools version we are
>using.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/MarcusWolschon/osmeditor4android/issues/796#issuecomment-456286869

Most builds are failing with this error. Google somehow pushed a license change 2 days ago... :-/

**Comment by simonpoole** [comment]
Sigh.

**Comment by simonpoole** [comment]
@Bubu @roptat

Currently f-droid is stuck trying to build 13.0.0.2 beta because of a repo f-droid doesn't like, I've changed to an alternative version in https://github.com/MarcusWolschon/osmeditor4android/commit/a6e6bf8683fe99e36740a61c75cc401c74b680cf so that should work when 13.0 is released. 

However we still have the more fundamental issue of F-Droid trying to build betas instead of updates to to the released version (in this case 12.1.5), if F-Droid can't evaluate the github "pre-release" flag (that used to work though), then you should be using the the fourth version number field to determine if the the tag is for a release or beta build as I've previously described.

**Comment by Bubu** [comment]
>  F-Droid can't evaluate the github "pre-release" flag (that used to work though)

F-Droid really doesn't know anything of github. It looks only at the git repo (and only ever did.). There's no such thing as pre-release flag there.

**Comment by Bubu** [comment]
> then you should be using the the fourth version number field to determine if the the tag is for a release or beta build as I've previously described.

I'm sorry, I currently don't understand this.

Have a look here: https://f-droid.org/docs/Build_Metadata_Reference/ -- Crtl -f "append a regex pattern". This is how we can match beta-non-beta releases.

Usually you have releases in the form vX.Y.Z and vX.Y.Zb1 for beta versions.

**Comment by simonpoole** [comment]
1.2.3.1 is the first beta, 1.2.3.2 the second,  and so on  1.2.3.0 is the release. 

Am 14. März 2019 17:44:35 MEZ schrieb Marcus Hoffmann <notifications@github.com>:
>> then you should be using the the fourth version number field to
>determine if the the tag is for a release or beta build as I've
>previously described.
>
>I'm sorry, I currently don't understand this.
>
>Have a look here: https://f-droid.org/docs/Build_Metadata_Reference/ --
>Crtl -f "append a regex pattern". This is how we can match
>beta-non-beta releases.
>
>Usually you have releases in the form vX.Y.Z and vX.Y.Zb1 for beta
>versions.

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit Kaiten Mail gesendet.

**Comment by roptat** [comment]
Ah, so that means there should be:

```
UpdateCheckMode: Tags ^[0-9]*\.[0-9]*\.[0-9]*\.0$
```

(or similar) instead of

```
UpdateCheckMode: Tags ^[0-9.]*$ 
```

right?

**Comment by simonpoole** [comment]
Yes that looks right.

BTW if I understood the docs correctly you seem to be able to build flavours now, if that is true then it would nice to build the legacy flavour too.

**Comment by Bubu** [comment]
What does the legacy flavour do?

**Comment by simonpoole** [comment]
Supports pre-Android 4.0 devices.

**Comment by Bubu** [comment]
How does this work for gplay releases? they get a different versioncode?

While this is possible to do in f-droid this would mean back to manually updating again. (it'd need to build entries per version one per flavour. auto update can;t deal with that currently)

**Comment by simonpoole** [comment]
> 
> 
> How does this work for gplay releases? they get a different versioncode?

Google stopped supporting anything pre 4.0 last year. We only distribute such builds via the github repo.
> 
> While this is possible to do in f-droid this would mean back to manually updating again. (it'd need to build entries per version one per flavour. auto update can;t deal with that currently)

That doesn't really make sense then, the question is what will f-droid do when google ratchets up a couple of notches more ....
 
> (Also pre-android 4.0? That's reeeeeaaaallly old at this point.)

Well I have a HTC Desire HD here with 2.3 that can still run the app, naturally the goog and there are still a large number of 2.3 devices out there, they just don't turn up on many statistics. That said the main reason I added the flavour is because google will ratchet up more and more so even if in our typical user base 2.3 is not popuplar, there are still lots of people with 4.1 tablets and similar.

**Comment by Bubu** [comment]
>  the question is what will f-droid do when google ratchets up a couple of notches more ....

What exactly do you mean? TargetSDK version? But this should be ~independent from minsdkversion?
Or is this something different altogether?

**Comment by simonpoole** [comment]
google does it by dropping support in the support libraries, which means you are stuck at a certain support library version and can't upgrade, which turn causes lots of stuff to complain when you up the target version, which you have to do to remain listed on the play store.

**Comment by simonpoole** [comment]
BTW https://f-droid.org/wiki/page/de.blau.android doesn't seem to be updating.

**Comment by roptat** [comment]
So I've submitted this: https://gitlab.com/fdroid/fdroiddata/merge_requests/4621

**Comment by simonpoole** [comment]
@roptat doesn't seem to have stopped f-droid from building 13.0.0.3 https://f-droid.org/wiki/page/de.blau.android/lastbuild

**Comment by simonpoole** [comment]
@roptat & @Bubu in the mean time I've released 13.0.0 and according to the f-droid build log it has been built, but see https://f-droid.org/de/packages/de.blau.android/ (I note that same goes for 12.1.7 that was built but never showed up).

**Comment by simonpoole** [comment]
This seems to be working smoothly right now, so closing.

**Comment by simonpoole** [comment]
Seems as if the f-droid build is stuck again, rather annoying because that was the soft release of 14.1.

**Comment by Bubu** [comment]
Soft release? 🤔 what does that mean?

**Comment by simonpoole** [comment]
Soft release or launch: https://en.m.wikipedia.org/wiki/Soft_launch?wprov=sfla1 In our case it is essentially staging so that we can catch any issues before everybody gets it,  mainly a reaction to beta testing being so unpopular.

**Comment by Bubu** [comment]
I added the update manually now. Autoupdate is broken for some reason, but the build script also needed small changes this time.

(I'm starting to work on fundamentally improving the auto-update process, it'll be better soon-ish)

**Comment by simonpoole** [comment]
Thanks.

**Comment by simonpoole** [comment]
@Bubu f-droid has been distributing an early beta of 15.1 (actually the first) since November, naturally as it was a beta there are numerous issues with it and it should be removed, there is long long time a release version, actually we're at 15.1.7 in the mean time. 

Next week, maybe tomorrow, we will be releasing the 1st beta of 15.2. Could you check that this doesn't get put on f-droid without corresponding warnings.

**Comment by Bubu** [comment]
What happened here was that I added the beta as an unstable release for manual install to f-droid last November and the update bot then bumped the recommended version past the beta but didn't add any new releases. (I've completely disabled that update check now as well).

I also added 15.1.7 and disabled the beta.

Going forward I don't think I'll be the best person to maintain vespucci in f-droid. I'm at most using it twice a year and am thus not keeping up with releases.

**Comment by simonpoole** [comment]
@Bubu there's at least a maintenance release every month, so from my pov best would be to have auto-updating back to a stable working order and not have to rely on anybody having time/following releases closely/etc

**Comment by simonpoole** [comment]
@Bubu any chance you could get https://github.com/MarcusWolschon/osmeditor4android/releases/tag/15.2.1.0 on f-droid?

**Comment by Bubu** [comment]
Done.

**Comment by simonpoole** [comment]
@Bubu we might have a chance to get autoupdate working again, see https://github.com/MarcusWolschon/osmeditor4android/issues/1163#issuecomment-863175665

**Comment by simonpoole** [comment]
Seems to be working stable now. Keeping fingers crossed.
