### ISSUE TITLE
Empty suggestion boxes in the upload dialog

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#797]
## Vespucci Version
11.2.0-1

## Download source
F-Droid

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
6.0.1 Fairphone Opensource OS (not the regular Fairphone OS)

## Behaviour/Symptoms
I try to upload a changesets. In the "Properties" tab, there are the fields `Comment:` and `Source:`. When using a fresh install of Vespucci, when I click into one of those fields, there appears an empty box below or above the mentioned fields. The box looks like there should be suggestions/auto-complete values in it, but it is empty.

## Expected Behaviour
When there are no suggestions to show, there should also be no such boxes.

## How to recreate
Make a fresh install of Vespucci, download some data, make a change to the downloaded data, try to upload it.

## Crash dump submitted (no or yes + date)

No

## Any other potentially relevant information

I'm not using the regular Fairphone OS.

**Comment by simonpoole** [comment]
This is just a side effect of always providing an empty entry so that you can delete the contents of the EditText fields without having to delete the text via another mechanism.

**Comment by simonpoole** [comment]
PS 11.2.0-1 is a beta build and f-droid shouldn't have it.....

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/84aa816d810d43738e3e1f9ec76ed5ba8f3273fa

**Comment by ltog** [comment]
@simonpoole : Super! Vielen Dank!
