### ISSUE TITLE
Element information dialog should show changes applied to tag more clearly

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#798]
I would like to see a change made to the upload dialog: When looking at the original and current tags, currently it is hard to see, which tags were changed and what the changes were. That should be shown more prominently:

- Names of tags that were changed: e.g. using bold or underlined font 
- Tag contents that were changed: using colors: deleted/changed content in the "original" column red, changed/additional content in the "current" column green (or blue for people with color vision deficiency).

**Comment by simonpoole** [comment]
Done in https://github.com/MarcusWolschon/osmeditor4android/commit/4205ef65e2064c1b3fa3bb200c2cd4db3f7d6d0e
