### ISSUE TITLE
notifications group plays phone sound for every element

### ISSUE THREAD

**Issue by fansanelli** [MarcusWolschon/osmeditor4android#800]
## Vespucci Version
11.2.0.0

## Download source
Play Store

## Device (Manufacturer and Model)
LG G6

## Android Version 
8.0.0 STOCK

## Behaviour/Symptoms
the new notifications group is not ok, I get only one system notification, but the phone sound plays for every element inside

## Expected Behaviour
Phone notification sound only plays only once

## How to recreate
Select an area with many warnings and sync with the server

## Crash dump submitted (no or yes + date)
No

**Comment by simonpoole** [comment]
Note: you can turn sounds for notifications off in the settings for the resp, group. Having only the gtoup notification make a sound does seem to be possible now that we build the current flavor against a 27 support library. Will likely require a preference as it is not clear if everybody would want such behaviour.

**Comment by simonpoole** [comment]
Made configurable in https://github.com/MarcusWolschon/osmeditor4android/commit/7d6a7c5c7a3fab7f04fce0610f60141e201e5980
