### ISSUE TITLE
Test 3

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#806]
Description:
---

Vespucci feedback test drive

Device info:
---
<table>
<tr><td>App version</td><td>12.0.0.1</td></tr>
<tr><td>App version code</td><td>900</td></tr>
<tr><td>Android build version</td><td>4931629</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>sdk_gphone_x86-userdebug 8.1.0 OSM1.180201.023 4931629 dev-keys</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>generic_x86</td></tr>
<tr><td>Device model</td><td>Android SDK built for x86</td></tr>
<tr><td>Device product name</td><td>sdk_gphone_x86</td></tr>
<tr><td>Device hardware name</td><td>ranchu</td></tr>
<tr><td>ABIs</td><td>[x86]</td></tr>
<tr><td>ABIs (32bit)</td><td>[x86]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>SimonDev</td></tr>
</table>

**Comment by don-vip** [comment]
Do you always report the username?
