### ISSUE TITLE
Opening tag list of object crashes Vespucci

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#813]
## Vespucci Version
12.0.0

## Download source
F-Droid

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
Fairphone OpenOS (not stock!) 18.04.1

## Behaviour/Symptoms
Opening tag list of object crashes Vespucci

## Expected Behaviour
No crash

## How to recreate
Select an object, then click the tag/label symbol

## Crash dump submitted (no or yes + date)
Yes, 2018-12-10

**Comment by simonpoole** [comment]
Isn't this https://github.com/MarcusWolschon/osmeditor4android ?

**Comment by ltog** [comment]
I'm not sure if it's the same: My instance crashes a bit earlier: Download region -> Press "add symbol" -> tagged node -> tap a screen position -> crash

BTW: I did look for existing Github issues, but didn't check the closed ones.

**Comment by simonpoole** [comment]
Could you check with 12.0.0.1 in any case, essentially anything that was preset related crashed on devices that were affected.

**Comment by ltog** [comment]
@simonpoole : Can you provide the .apk file?

**Comment by simonpoole** [comment]
f-draoid has it https://f-droid.org/en/packages/de.blau.android/ Note I think it is a really bad idea that f-droid is distributing betas without indicating that they are actually beta builds.

**Comment by ltog** [comment]
@simonpoole : I'm a little confused regarding the version numbers:

The debug menu says I have 12.0.0 whereas F-Droid says I have 12.0.0.1 (already installed). That probably means that I should have written that my bug report is for version 12.0.0.1?

**Comment by simonpoole** [comment]
Sorry, my bad, the -current- beta is 12.0.0.3 (we never built an APK for 12.0.0.1 so published betas we're at the 2nd one now) see https://github.com/MarcusWolschon/osmeditor4android/releases

**Comment by ltog** [comment]
The mentioned issue doesn't occur anymore. I think this issues can be closed. Thank you for the fast response.

**Comment by simonpoole** [comment]
Thanks
