### ISSUE TITLE
The handy report tool has no way to submit report to preset repo

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#817]
Description:
---

For example I noticed and wanted to report that primary tag advertising=column is described in tag list as "additional property"

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>12.0.0.3</td></tr>
<tr><td>App version code</td><td>901</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by matkoniecz** [comment]
advertising=column issue is now reported as https://github.com/simonpoole/beautified-JOSM-preset/issues/123

**Comment by simonpoole** [comment]
This was already "planned" however needs some thinking about where to put and how to label the facility as not to have issues landing in the wrong place.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/f51bee0263e80bf4928417671824e1ea9463192a
