### ISSUE TITLE
spammed gallery

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [MarcusWolschon/osmeditor4android#818]
Due to /sdcard/Vespucci/autopreset/*.png my galley is bloated with a lot of pictures:

![screenshot_20181216-162943_gallery](https://user-images.githubusercontent.com/14617699/50054129-ff5f7180-014f-11e9-8418-bd7482eccb50.png)

**Comment by stephan75** [comment]
so we need a null-bytes-file in that directory with filename ".nomedia" ??

**Comment by c-e-p-x-u-o** [comment]
you shouldn't use user storage for system files!

moreover, i've created .nomedia file in autopreset directory and rebooted the phone but still see images in the gallery

**Comment by simonpoole** [comment]
The generated autopreset preset file is intended to be able to be accessed by the user, so it is in exactly the right place. I'll add a nomedia file to the directory though (IMHO the media index doesn't retroactively remove directors with .nomedia in them).

**Comment by simonpoole** [comment]
Added .nomedia file in https://github.com/MarcusWolschon/osmeditor4android/commit/b2d13bd918341b5cb8b2932edf34ba09370f11b0

**Comment by c-e-p-x-u-o** [comment]
Some time later it gallery has been updated and I don't see it more.
But could you explain the case when it should be accessed by the user?

**Comment by simonpoole** [comment]
You can use the autopreset as a starting point for an own "proper" preset, the other aspect is persisting it in the user storage persists it even over de-install - install cycles.

**Comment by simonpoole** [comment]
> 
> 
> As for me I don't need to create my own preset, I don't need these files after application purge, and them looks like a garbage. 

Well then don't use them.

> Moreover it requires additional permission.

Nope, we need to be able to read and write to the directory for a number of reasons, for example for saving and reading data files, additional configuration, storing photographs, emergency OSC exports and so on.

> The OSM, for example, allows to set the storage for maps (internal or shared). Could you make similar setting?

What is "The OSM" supposed to be? 

> There is an /sdcard/Android/ folder. As I understand it doesn't require storage permission, accessible by user, and will not survive re-install cycle.

> 
> May be it's better to add backup-restore feature and don't depend on persists over re-install?

There are situations where  users may want to install an app from a different source, for example f-droid vs. google play store and similar where being able to persist files independently is useful (over what I've already pointed out).

**Comment by c-e-p-x-u-o** [comment]
> What is "The OSM" supposed to be?

osmand, sorry

**Comment by c-e-p-x-u-o** [comment]
For example, in https://gitlab.com/axet/android-call-recorder Storage Path is ```/storage/emulated/0/Android/data/com.github.axet.audiorecorder/files``` by default so it doesn't requires storage permission, but you can change it to everything you want (/storage/emulated/0/io.mapsquare.osmcontrubutor, for example and only then you'll need to provide storage permission).
