### ISSUE TITLE
Unreadable or corrupt state

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#819]
Description:
---

This message appeared on the first launch after the Vespucci update 6 hours ago.

Feel free to ignore of it happens only on my phone.

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>12.0.0.4</td></tr>
<tr><td>App version code</td><td>902</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
See http://vespucci.io/help/en/12.0.0%20Release%20notes/#state-saving-changed

**Comment by matkoniecz** [comment]
Is it reasonable to make special message for first load of version along lines of "Now data is saved in a smarter way. During upgrade it was necessary to erase old data to make it possible. Preferences are unaffected.".

Though it may be too long and not worth adding.

**Comment by simonpoole** [comment]
You underestimate the complexity ... loading the state is completely asynchronous,. To be able to show the message, the state loading code has to know if this is a new install or simply an update, so the code has to be modified to start the state loading after the new install whatever status has been determined, pass that to the state loading code and then load the state. That additionally to already 3-4 similar load operations that already depend on each other (for example the notes etc saved state is dependent on the layer state being loaded first and so on). 

So while definitely possible,  it means adding complexity for what is hopefully a one time event.

**Comment by matkoniecz** [comment]
In that case it makes no sense to do that.

At that point I would close it but I am not the issue owner.
