### ISSUE TITLE
waterway=riverbank should not have arrows, unlike other waterways

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#824]
moved fom https://github.com/simonpoole/beautified-JOSM-preset/issues/127#issuecomment-450136714

**Comment by simonpoole** [comment]
Currently the rendering of oneway arrows is hardwired and not driven by configuration. This will likely be adressed in 12.1

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/1015452eae1db99337e52717aec2e016f6463aa8
