### ISSUE TITLE
Make names optional for major roads with ref tag

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#825]
I see little value in adding noname tags to say `highway=primary` in rural regions.

Maybe requiring either `ref` or `name` tag would be better?

Moved from https://github.com/simonpoole/beautified-JOSM-preset/issues/125

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/e3aee4d9eeafc57a6e2a2e28280f0de6b301dd3b provides an "alternatives" syntax for the keys, for example: name|ref
