### ISSUE TITLE
Preserve changeset comment when canceling upload

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#826]
I don't know about others, but my personal workflow is to create a changeset comment and extend it as I edit. Vespucci doesn't permit this, because the changeset comment is erased if I press Back at the upload dialog.

Vespucci v11.2.2.0 from F-Droid, Android v9 (Pie), Nokia 6.1

**Comment by simonpoole** [comment]
If I understand you correctly you are essentially using the changeset comment field as a note pad for what you've done? 

This can currently be achieved by uploading and leaving the changeset open, but has the downside of having to upload and it suffers from the issue that is the underlying reason why we don't store the current text; polluting the changeset comment history  (and imho if I had such a workflow I would consider going through the upload dialog just to jot something down a bit cumbersome). 

So this needs some thinking.

**Comment by contrapunctus-1** [comment]
I'm actually not sure what you mean by 'polluting changeset comment history' 🤔 I thought you meant that 'if the changeset comment field is remembered when cancelling an upload, it would be extra work for the user to clear it if they changed their mind', which is why I suggested (on #osm) a ❌ button to clear the field and do away with the 'blank suggestion entry'.

By way of clarification, I don't mean preserving the comment _after_ upload.

Some loud thinking - something like OsmAnd's automatically generated changeset comments might make this less necessary - anything that lets the user get a higher level overview of their edits. The current Vespucci UI is good at describing the _individual_ changes, but 'adding it up' is still something the user has to do. Of course, this is veering into the precarious territory of what a changeset comment should actually contain...

**Comment by HolgerJeromin** [comment]
I often enter a changeset comment and after doing so i remember that i forgot an important change for example of one changed osm element. Uploading would pollute the version history. 
So I cancel and have to reenter the comment after my element change.

**Comment by ltog** [comment]
For me it's exactly the same as described by @matkoniecz.

**Comment by marcows** [comment]
Sometimes while writing the comment, I have to look back at the changes to recall some details of my changes or to copy some text like from the name key for inclusion in the comment.
JOSM also keeps the changeset comment when cancelling the upload form.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/6f5fc4f11b4a1f2831c70c2ec4c1806f48772ede
