### ISSUE TITLE
Rotating the opening hours template dialog from portrait to landscape crashes Vespucci

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#830]
## Vespucci Version
12.0.0.3

## Download source
F-Droid or .apk download (can't remember)

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
6.0.1 (FP Open OS, NOT the default one)

## Behaviour/Symptoms
When one rotates the phone while the dialog to select the opening hours template is open, Vespucci crashes.

## Expected Behaviour
no crash, dialog should be shown in landscape mode

## How to recreate
see above

## Crash dump submitted (no or yes + date)
yes, 2019-01-04

**Comment by simonpoole** [comment]
This is an issue in the OpeningHoursFragment lib see https://github.com/simonpoole/OpeningHoursFragment/issues/31

Note: you shouldn't have rotation enabled when using Vespucci anyway :-).

**Comment by simonpoole** [comment]
Has been "fixed" upstream (currently the dialog is simply dismissed), https://github.com/MarcusWolschon/osmeditor4android/commit/98480002a76c6464f7c8e1b718f52b2dec14132a
