### ISSUE TITLE
unexpected mouse wheel behavior for zooming

### ISSUE THREAD

**Issue by govvin** [MarcusWolschon/osmeditor4android#831]
## Vespucci Version
Tested on versions,  12.0.0.4, 11.2.2

## Download source
F-Droid

## Device (Manufacturer and Model)
Google Pixel XL, Samsung Galaxy Tab S4

## Android Version 
9, 8.1

## Behaviour/Symptoms
When a mouse with a scroll wheel is attached to a device, the scrolling behavior is the reverse of the typical. A scroll up zooms out, while a scroll down zooms in.  

## Expected Behaviour
Follow the typical mouse scroll behavior: scroll up zooms in, and a scroll down zooms out.

## How to recreate
Attach a mouse with a scroll wheel.

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
I used a Bluetooth mouse.

**Comment by govvin** [comment]
> IIRC this was added on a specific request and the user seemed to be happy, so maybe the behaviour needs to be in a preference?

That sounds like a reasonable option. The default behaviour should be what's typically available, and could be changed to user's preference.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/bdbe46fcf70653cc815e4ea0b12c6ad136f775d4
