### ISSUE TITLE
Classify "too many nodes in way to move" as warning message

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#834]
Description:
---

I think that red ones should be reserved for unexpected unhandled failures like "all your unoploaded changes were discarded"

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>12.0.0.4</td></tr>
<tr><td>App version code</td><td>902</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by matkoniecz** [comment]
And red message at least for me is quite scary.

**Comment by simonpoole** [comment]
Addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/e5087a7a228c44fcf54ae5ec954783d048f66cec

This changes the behaviour to allow the moves (as they can easily be undone) and simply show a warning indicating how many nodes were moved.
