### ISSUE TITLE
Make description field larger in feedback to developers form

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#835]
Description:
---

Currently it is too small to even scroll it properly.

Maybe it can get bigger to accommodate all text inside?

Device info:
---
<table>
<tr><td>App version</td><td>12.0.0.4</td></tr>
<tr><td>App version code</td><td>902</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
Partial fix in https://github.com/MarcusWolschon/osmeditor4android/commit/5a2725438e930451588e1daf5b861152c4f87830 The field should be scrollable but due to issues in the underlying library seems to not be.

**Comment by simonpoole** [comment]
Close (further actions in #956
