### ISSUE TITLE
Show create new node cross on way earlier

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#836]
Description:
---

On selecting way and zooming in on middle between nodes crosses are appearing.

It allows to detail way geometry.

I frequently zoom in solely to make this crosses appear despite that I want to edit on more zoomed out level.

Maybe this part of interface can appear earlier?

Device info:
---
<table>
<tr><td>App version</td><td>12.0.0.4</td></tr>
<tr><td>App version code</td><td>902</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
This is in principle styleable as it depends on the node tolerance radius size (the minimum on screen length to show the handles is 5 x the radius), which I would rather not change as making it less makes the handles very difficult to hit. However there is a bug in that the minimum length doesn't actually get reset when the style changes so currently is fixed.

**Comment by simonpoole** [comment]
This is now directly configurable see https://github.com/MarcusWolschon/osmeditor4android/commit/6357d753ffc24d815018d03fe49372392316163e
