### ISSUE TITLE
Authentication should use external browser instead of embedded webview

### ISSUE THREAD

**Issue by HolgerJeromin** [MarcusWolschon/osmeditor4android#840]
See [OAuth 2.0 for Native Apps (draft)](https://tools.ietf.org/html/draft-ietf-oauth-native-apps-11). The best practice for OAuth in native mobile apps is to open the (default external) browser, not to embed the authentication flow in a webview inside the app.

## Vespucci Version
12.0.0

## Any other potentially relevant information
StreetComplete had the same:
https://github.com/westnordost/StreetComplete/issues/265

**Comment by simonpoole** [comment]
We used to do this. It doesn't work reliably or in any fashion in an acceptable way for end users, so not going to happen (and if you look what JOSM does, the complaint is laughable).

**Comment by simonpoole** [comment]
PS: google has been pushing for this for a long time, naturally they have a vested interest in end users using the, typically google connected, standard browser on devices instead ob bypassing them. The security downside of using a webview is that you have to trust the app developer not to fake the login screen and so on, but in the end you have to do that in any case.

**Comment by HolgerJeromin** [comment]
I only know from problems with LineageOS: https://github.com/westnordost/StreetComplete/issues/413#issuecomment-328339064

There are many levels of trust IMO. Giving an app my password requires a quite high level.

**Comment by simonpoole** [comment]
> There are many levels of trust IMO. Giving an app my password requires a quite high level.

Except naturally you are -not- actually giving it to the app, accessing what you are entering in the webview would require malicious intent, what you are typing in the webview is not available to the app.

The whole thing is at best a 3rd level consideration. google does has a point that if you are using a third party login to access OSM, aka google, re-authenticating is not strictly necessary, as you will already be authenticated and tracked in the on device browsers, but you shouldn't be using the goog to access OSM in the first place and you should have a completely separate login if you are security conscious.
