### ISSUE TITLE
Feature request: catch openstreetmap.org node and other links 

### ISSUE THREAD

**Issue by pataquets** [MarcusWolschon/osmeditor4android#844]
OSMAnd app for Android displays a clickable link to OSM node/way page for POIs.
On my device, tapping it currently offers Chrome and Locus Map as choices.
It would be very helpful and straightforward for mappers to launch also Vespucci using that link.
TIA.
![screenshot_20190112-180141](https://user-images.githubusercontent.com/1286254/51076187-70ce0980-1695-11e9-8e6d-6851c82adf8a.png)

**Comment by simonpoole** [comment]
The question is more if this would be a feature or just an annoyance (takes about 10 min to implement).

**Comment by HolgerJeromin** [comment]
we can use the share location in Osmand. 
I would call it surprising to have the editor in the list

**Comment by contrapunctus-1** [comment]
I agree that there is some duplication between this and the geo: link handling, which makes this low priority/of questionable utility. However, it certainly wouldn't be surprising, because I regard any OSM.org link as something meant solely for mappers to begin with, as they are the prime audience of the website.

**Comment by simonpoole** [comment]
Twitter poll https://twitter.com/vespucci_editor/status/1229719931090063363

**Comment by jidanni** [comment]
for me, sharing openstreetmap map link, bring up a choice of many places to share it with. With only one missing, this app. If it was implemented, then I could zoom  right away to where I want to edit , without having to  use my fingers to blow it up on the map somewhere.

**Comment by simonpoole** [comment]
@jidanni you can simple use a geo: url for now.

**Comment by jidanni** [comment]
> @jidanni you can simple use a geo: url for now.

Yes, however we might not even have the lat/lon in the URL that we clicked on. Or if we do we have to arduously manually rewrite the URL.

**Comment by pataquets** [comment]
@simonpoole : Also, the original feature request is for http osm.org links, that can appear quite frequently, as shown in the OP.
For that cases, it would make very easy and seamless to jump back and forth between viewing and editing. A helpful workflow for edit sessions, indeed.

**Comment by contrapunctus-1** [comment]
Chiming in on this issue again - this would be very useful. In fact, not just osm.org node  way, and relation URLs, but also links to notes and Osmose issues. I have an RSS feed for notes and Osmose issues in my city, and I'd like to open those links in Vespucci more easily. Currently, it's fairly roundabout to open even one of those.
