### ISSUE TITLE
wheelchair:description key is not autocompleted

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#845]
Description:
---

To reproduce - go into tag view of any object that had `wheelchair` in its presets and start typing `wheelchair:`.

Device info:
---
<table>
<tr><td>App version</td><td>12.0.1.0</td></tr>
<tr><td>App version code</td><td>904</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
The current behaviour is "as designed" as the field is supposed to be a detailed description of the facilities present, and nothing structured that you would want to reuse.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/cd8a971032f3b9771457eea4f09157d152e0f850
