### ISSUE TITLE
Unuploaded notes are getting lost

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#846]
Description:
---

Feel free to dismiss it as "your phone is broken", but saved, not uploaded notes (blue) are very often dissapearing from my phone - on reboot, exiting application etc

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>12.0.1.0</td></tr>
<tr><td>App version code</td><td>904</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by matkoniecz** [comment]
As reminder - my phone is for example sometimes not showing toast messages.

**Comment by simonpoole** [comment]
The notes issue should definitely not happen. Any specifics about the concrete situation would be helpful.

**Comment by matkoniecz** [comment]
New notes, I was not trying today to add comments to old ones.

Some time before I suspected that something like this is happening but I never confirmed it conclusively, and typically I upload notes immediately unlike today so it is hard for me to pinpoint the version.

I may try to compile old version and put vl them on my phone for testing to try detecting it.

One additional thing that changed recently - my phone started running out of memory on main drive (<1GB). Is it possible that data saved by Vespucci is deleted as an unimportant cache?

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/0859df13c65beb1b7bf362644c112ab6d3a031f9
