### ISSUE TITLE
Let users control which notifications are shown

### ISSUE THREAD

**Issue by johnjohndoe** [MarcusWolschon/osmeditor4android#851]
This feature request is to discuss whether users should gain more control over which notifications are shown by the app.

## Vespucci Version
- 12.1.0

## Download source
- Google Play

## Device (Manufacturer and Model)
- Google Pixel 2

## Android Version 
- 9

## Behaviour/Symptoms
- The app shows different kinds of notifications in the status bar.
- Notification types:
  - `Nearby OSM bug detected`
  - `OSM data issue detected`

![vespucci-notification-pulldown](https://user-images.githubusercontent.com/144518/51803997-97766d80-225b-11e9-8a64-7620c0ae7a1e.png)

- The system notification settings expose two types of notifications which can be enabled or disabled:
  - `Vespucci`,
  - `Vespucci QA` 

![vespucci-notification-settings](https://user-images.githubusercontent.com/144518/51804005-9f361200-225b-11e9-87e2-e08292cb3d62.png)

## Expected Behaviour
- The system notification settings expose different types of notifications for users to enable or disable.
- Example naming:
  - `Nearby OSM bug detected`
  - `OSM data issue detected`
  - `Vespucci QA` 

## How to recreate
- Android supports to use different [notification channels](https://developer.android.com/training/notify-user/channels) starting in Android 8.0 (API level 26).

**Comment by simonpoole** [comment]
Given that you can:

- turn notifications off completely in the app
- limit the total number of notifications per channel in the app
- turn off the channels on the device
- turn off individual audio notifications

I'm not quite sure what extra configuration you actually want.

**Comment by simonpoole** [comment]
Yes the names are not particularly descriptive ... will think about it.

**Comment by simonpoole** [comment]
I think this is more a question of the Android UI, I've expanded the description of the two channels https://github.com/MarcusWolschon/osmeditor4android/commit/8e6b5f4f133b5c813bc6b6c81dcd3c9153ef689c but you only get to see that a) if you have a notification, and b) you click on the channel name in UI.

Currently all QA alerts go to the same channel, the default one gets the notification for the foreground GPS track service.

**Comment by johnjohndoe** [comment]
Thank you for the update.
