### ISSUE TITLE
Preset fills object with recently used tags

### ISSUE THREAD

**Issue by scaidermern** [MarcusWolschon/osmeditor4android#852]
Applying a preset to an object fills it with recently used(?) tags. For example by using the restaurant preset I get an object with

- `amenity=restaurant`
- `name=Little Tony's Pizza`
- `cuisine=pizza`
- `wheelchair=limited`
- `website=http://littletony.it`

All that I wanted was  `amenity=restaurant` and a list of suggested keys to use. But with the current behavior I have to remove a lot of bogus key-value pairs that I've used on a previous restaurant but which are definitely wrong for the new restaurant I want to add.

Is this intended behavior or a bug?

**Comment by simonpoole** [comment]
Essentially it's a feature that in some circumstances is great, in others, not so. In any case it^s been removed in 12.1.2, see https://github.com/MarcusWolschon/osmeditor4android/commit/838ebfa0841d873d2ec0861bae12d9d0861dce61

**Comment by scaidermern** [comment]
That's good to know :)

**Comment by simonpoole** [comment]
12.1.2 with the fix is now available on the play store.
