### ISSUE TITLE
Galician language

### ISSUE THREAD

**Issue by IVAN-RSM** [MarcusWolschon/osmeditor4android#853]
Hi! The Galician translation is already more advanced than the Spanish. Spanish is implemented, Galician is? It would have its logic! https://www.transifex.com/openstreetmap/vespucci/dashboard/

I also want to mention, that many people would like there to be the option to change the language apart from the system in the settings.

**Comment by simonpoole** [comment]
Tranealations are integrated and updated on every release, including Galician. You might need to explain what you believe is not working.

As has already been pointed out in other issues, Android does not provide per app language settings.

**Comment by IVAN-RSM** [comment]
There are many applications like OsmAnd that allow the change of language in application. It is very useful for those who know several!

**Comment by simonpoole** [comment]
Yes there are -hacks- to support other languages in app, but they are not supported by google and create additional work, which contrary to OsmAnd nobody is paying for.

You haven't actually answered my question I may note, can I assume that there is not actually an issue?

**Comment by IVAN-RSM** [comment]
My only big question was about the change of language. The rest OK :)
