### ISSUE TITLE
Setzt automatisch falsche Werte

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#854]
Description:
---

Wird eine Vorlage für ein Objekt ausgewählt, setzt der Editor nicht mehr nur die passenden keys, sondern Werte gleich mit. Die sind natürlich mit großer Wahrscheinlichkeit falsch. 

Device info:
---
<table>
<tr><td>App version</td><td>12.1.0.0</td></tr>
<tr><td>App version code</td><td>1000</td></tr>
<tr><td>Android build version</td><td>3677123758</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>47.2.A.6.30</td></tr>
<tr><td>Device brand</td><td>Sony</td></tr>
<tr><td>Device manufacturer</td><td>Sony</td></tr>
<tr><td>Device name</td><td>G8441</td></tr>
<tr><td>Device model</td><td>G8441</td></tr>
<tr><td>Device product name</td><td>G8441</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>BS97n</td></tr>
</table>

**Comment by simonpoole** [comment]
Siehe https://github.com/MarcusWolschon/osmeditor4android/issues/852 und https://twitter.com/vespucci_editor/status/1090304986179923969

**Comment by simonpoole** [comment]
12.1.2 with the fix is now available on the play store.
