### ISSUE TITLE
Improve open changeset UX

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#856]
Currently, working with open changesets has some issues -
1. It is not clear if one is about to create a new changeset or add to an existing open changeset (I've unintentionally squashed together two changesets this way, even though I created a new changeset comment for the second one - not sure if bug or user error)
2. It is not possible to change the comment of an open changeset

I suggest listing open changesets (when present - please check automatically when the dialogue is opened, unlike JOSM which makes you check manually) under the changeset comment field. The user should be able to select between 'new changeset' and any open changeset.

 When an existing changeset is selected, the comment field should contain its comment. Editing the comment and uploading to that changeset should edit that changeset's comment.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/c4ac7f06964cd809a930235f992bb6bcd5dfe096 fixes an issue that caused an upload to an open changeset not to update the changeset tags.

https://github.com/MarcusWolschon/osmeditor4android/commit/4feca6dcb8936731a01496810780aaca05b2bb11 adds a checkbox to close an already open changeset before uploading (doubling as a hint that the changeset is still open), and preserves the open changeset id over Android lifecycle events.

**Comment by contrapunctus-1** [comment]
Thanks a lot, this is working very well now! A minor refinement could be to show, in addition to the checkbox, the changeset comment of the open changeset, so we know exactly which one is open and will be acted upon in closing or appending. (Currently, the previous comment is shown unconditionally, but that's to ease typing - it doesn't indicate what the previous changeset was... 🤔)
