### ISSUE TITLE
Contact information UX improvements

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#857]
1. Vespucci suggests previously-entered phone numbers, which is usually not what one wants because POIs usually don't have the same phone numbers. Instead, the last entered country code could be auto-filled (e.g. "+91-")

2. I often have to add the phone/email/website field for POIs manually. It would be preferable to have a single button (similar to 'Add address tags') to toggle all contact fields.

3. POIs often have more than one phone number, but not all keyboards have a semicolon in their 'phone number layouts'. Perhaps Vespucci could have a UI for adding >1 phone number, so the user doesn't have to type semicolons?

(Alternatively, Vespucci could just use the usual keyboard layout for phone number fields. I personally wouldn't mind, because the phone number layout comes up so rarely in general use that one is usually faster at typing the phone number in the alphanumeric layout.)

**Comment by simonpoole** [comment]
On 2: you can use either the conventional "Contact" or the contact: namespaced utility preset http://simonpoole.github.io/beautified-JOSM-preset/#Addresses%20and%20Contact (the former is a linked preset for lots of the presets so should typically always be shown in the MRU presets regardless of if you've already used it). Definitely no need to enter the keys manually.

**Comment by contrapunctus-1** [comment]
Oh, I never saw that. It's pretty nice, thanks for the tip!

**Comment by contrapunctus-1** [comment]
Another possible refinement - email and websites are often similar. If one has entered email as foo@bar.tld, https://bar.tld could be suggested as the website. Likewise, if one has entered https://bar.tld as the website, "@bar.tld" could be auto filled when entering the email.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/92d8990e033d3b56210f2b56cfd8b42850c54001
