### ISSUE TITLE
Cannot see/edit osm data

### ISSUE THREAD

**Issue by thuryn** [MarcusWolschon/osmeditor4android#858]
Description:
---

I try to download the local area, but I cannot edit a road nor cannot see the road. I can provide movie with the issue.

Device info:
---
<table>
<tr><td>App version</td><td>12.0.1.0</td></tr>
<tr><td>App version code</td><td>904</td></tr>
<tr><td>Android build version</td><td>562(C432)</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>FRD-L19 8.0.0.562(C432)</td></tr>
<tr><td>Device brand</td><td>HONOR</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWFRD</td></tr>
<tr><td>Device model</td><td>FRD-L19</td></tr>
<tr><td>Device product name</td><td>FRD-L19</td></tr>
<tr><td>Device hardware name</td><td>hi3650</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by thuryn** [comment]
[SVID_20190210_111102_1.zip](https://github.com/MarcusWolschon/osmeditor4android/files/2848736/SVID_20190210_111102_1.zip)

**Comment by simonpoole** [comment]
You've turned on a filter mode and likely haven't configured anything to display.

See the big filter button /icon on the right hand side.

To disable filters uncheck the options in the main menu.

See http://vespucci.io/help/en/Introduction/#filters
