### ISSUE TITLE
Jump to object from upload dialogue

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#860]
It may be useful to be able to jump to an object from the upload dialogue (I personally have wanted to do this on at least two occasions.) The object details dialogue has space for this. Or maybe there can be a geo: link instead of the latitude/longitude information.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/7d8af9e9d325b1e08676e13da8dc40c4cadb4c56
