### ISSUE TITLE
Languages: translation of various expessions into various languages

### ISSUE THREAD

**Issue by debyos** [MarcusWolschon/osmeditor4android#862]
Dear All,

I have been translating Vespucci for a while and I find it a great application. However, it is often (and, as the app is evolving, more and more often) a problem that **an English expression has more than one translations** in Hungarian (and, I suppose, also in other languages).

E.g. **pier**
If it is a construction, kind of bridge going from the coast or bank to the sea or a river, it is called **"móló"**.
However, if it is a bridge support construction, it is called **"pillér"**.

In Hungarian, it is incomprehensible when one of these words is replaced by the other since they do not have anything in common. The same applies to "monastery" and also to many others.

Thus, I would suggest to restructure the vocabulary of Vespucci in a way that _one expression has only one context_.

Thanks a lot!

Gábor Babos

**Comment by simonpoole** [comment]
Hi Gábor

I'm assuming that you are mainly referring to the preset translations. It would be rather wasteful to add context for every term that needs to be translated (both from a size and a work pov), but we naturally already have those for lots of terms, and if you an example that doesn't work for you, please simply open an issue in the preset repo and we'll add context for the term.

**Comment by simonpoole** [comment]
Closing as @debyos hasn't responded.
