### ISSUE TITLE
App freezes when Merge node press more times

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#868]
Description:
---

1. Two ways crossing each other, not connected.
2. Create node connected to one of the ways
3. Press Merge button
4. Press Merge button
=> App gets frozen.

Device info:
---
<table>
<tr><td>App version</td><td>12.1.4.0</td></tr>
<tr><td>App version code</td><td>1004</td></tr>
<tr><td>Android build version</td><td>A300FUXXU1CRF1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.A300FUXXU1CRF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a3ulte</td></tr>
<tr><td>Device model</td><td>SM-A300FU</td></tr>
<tr><td>Device product name</td><td>a3ultexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>kudlav</td></tr>
</table>

**Comment by kudlav** [comment]
I'm the author of the report, but I'm using two factor authentication, so there is no way to report it from app.

Crash report sent: yes, twice, mentioned my email address: vladankudlac@gmai...

**Comment by simonpoole** [comment]
Thanks for the report .

Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/a816c55925e8e4b893905d451f9440d8f2bca900
