### ISSUE TITLE
Error when using check date preset

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#869]
To reproduce -
1. Exit Vespucci
2. Remove Vespucci from recently used apps
3. Use Check Date preset

The following error appears - `Function importClass must be called with a class; had "[JavaPackage de.blau.android.util.GeoMath]" instead `, and the tag "automated_check_date" is added.

Vespucci v12.1.5.0 from F-Droid

**Comment by simonpoole** [comment]
This doesn't occur on any system I've tested on, but may be fixed by updating the wrapper around rhino for Android, which I've done for both 12.1 and 13.0.

**Comment by simonpoole** [comment]
Just as a clarification, uses after the first time invocation work correctly?

**Comment by contrapunctus-1** [comment]
Yes. Also, neglected to mention that this is on Android v9 on a Nokia 6.1

**Comment by contrapunctus-1** [comment]
Was not fixed by v12.1.6

**Comment by simonpoole** [comment]
Hmm that creates a bit of an issue, as I've not been able to re-create the issue anywhere else and will need to poke in the dark a bit.

**Comment by simonpoole** [comment]
This was "yet another proguard" issue, fixed in: https://github.com/MarcusWolschon/osmeditor4android/commit/5776eff783f2cec0da72e32326357828ff6f9e8d (as the check_date script doesn't actually use any of the classes in question, it would still run when invoked the next time).
