### ISSUE TITLE
Error in German translation for cycleway=track

### ISSUE THREAD

**Issue by scaidermern** [MarcusWolschon/osmeditor4android#870]
The German translation for the value `track` for the tag `cycleway=track` is wrong. `track` is translated to "Bahn" which doesn't really make sense. A better translation is "Bordsteinradweg" or Baulich abgesetzt".

(I've just requested to join the German translation team on Transifex)

**Comment by simonpoole** [comment]
This is a preset issue (likely it needs a translation context) please open the issue [there]( https://github.com/simonpoole/beautified-JOSM-preset), as I can't move issues out of this repo, Sorry.
