### ISSUE TITLE
"no" values not selectable via presets

### ISSUE THREAD

**Issue by scaidermern** [MarcusWolschon/osmeditor4android#871]
For several POIs typical `no` values are not selectable since the check button only has two states - `yes` and unchecked.

Typical cases where entering a `no` value is useful:

- amenity=restaurant:
  - outdoor_seating=no
  - toilets=no
- highway=bus_stop:
  - shelter=no
  - bench=no
- tourism=camp_site
  - tents=no
  - caravans=no

Is there a particular reason against a three-state button for these typical tags?

**Comment by simonpoole** [comment]
This is again a preset issue, and it is one where the opinions differ very much. 

Essentially there is the one group which believes that there should be no implicit default values, taking a random example: if outdoor_seating is missing the implicit value is unknown. And the other group which has the view that there are sensible implicit default values, to re-use the example a missing outdoor_seating value means that there is no outdoor_seating.

The first group tends to concentrate on their favourite tag of the day, and forgets, that thought to the end, it means that most objects will have in the 100s of tags. Not to mention untagged nodes, which will have tens of 1'000s. 

Technically the choice between dual- and tri-state checkbox is controlled by the disable_off attribute in the presets, if it is set to true, a dual-state checkbox will be used.

**Comment by scaidermern** [comment]
Thanks for the hint, I've created a corresponding preset issue (as you've probably noticed :)) at https://github.com/simonpoole/beautified-JOSM-preset/issues/140

I can understand that `no` is the default value for various tags, e.g. `oneway=no`. However this doesn't apply to all tags with a yes/no value as you can see from the examples above.
