### ISSUE TITLE
Warning when deleting node

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#876]
Description:
---

1. Download area
2. Select node (simple without relations)
3. Choose Delete
4. The app warns you that you should Download more data to edit this area.

Ways are fine.

Lang: en, cs_CZ

Device info:
---
<table>
<tr><td>App version</td><td>13.0.0.2</td></tr>
<tr><td>App version code</td><td>1101</td></tr>
<tr><td>Android build version</td><td>A300FUXXU1CRF1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.A300FUXXU1CRF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a3ulte</td></tr>
<tr><td>Device model</td><td>SM-A300FU</td></tr>
<tr><td>Device product name</td><td>a3ultexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>kudlav</td></tr>
</table>

**Comment by kudlav** [comment]
![2019-03-14-22-13-29_screenRecording](https://user-images.githubusercontent.com/11516259/54392468-0abb2e00-46a8-11e9-87a8-879533a5ed55.gif)

**Comment by simonpoole** [comment]
Thanks for the report.

This was actually a regression in 12.1, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/e6b6a0e2d52097b73bfa8d3bee96cc5289422e50
