### ISSUE TITLE
Connection test - false positives with footways mapped as separate ways

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#878]
Description:
---

Warning message is "Node is near element it could be connected too"

I see no way to attach image, I can add one if it is not happening everywhere where sidewalks are not mapped separately

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.0.0.2</td></tr>
<tr><td>App version code</td><td>1101</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
I don't think this is easily fixable as any heuristic is going to lead to real issues being missed (JOSM has the same issue).

**Comment by matkoniecz** [comment]
JOSM works well with the same data.

For example Vespucci complained about https://www.openstreetmap.org/node/5932836882 https://www.openstreetmap.org/node/5932836880 https://www.openstreetmap.org/node/262201254

**Comment by simonpoole** [comment]
But that isn't a fundamental difference, it is just one of the distance at which a connection is suspected to be missing or not. 

In any case https://github.com/MarcusWolschon/osmeditor4android/commit/9409b319f8c13a162c8dc5bff4249255fd9efacf sets the default tolerance distance to 2 meters and makes it user settable. Don't see anything else that could be done right now.

**Comment by matkoniecz** [comment]
> it is just one of the distance at which a connection is suspected to be missing or not.

I suspect that JOSM may take into consideration also topology of ways, not only distance of node to other nodes.
