### ISSUE TITLE
Reversed coordinates

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#879]
Description:
---

When changing position coordinates for a node, the input fields are reversed! Longitude (W-E) on first field, then Latitude (N-S). Very confusing when you want to paste a position from other service. Everyone use Latitude-Longitude!

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Jonas E</td></tr>
</table>

**Comment by simonpoole** [comment]
> 
> ## Description:
> 
> When changing position coordinates for a node, the input fields are reversed! Longitude (W-E) on first field, then Latitude (N-S). Very confusing when you want to paste a position from other service. Everyone use Latitude-Longitude!

A guick google would have shown you that that is not the case at all, and it is something of considerable debate.

**Comment by simonpoole** [comment]
Changed in https://github.com/MarcusWolschon/osmeditor4android/commit/3d9964f2c8d04a243cb3ffc0c003ab2b54b6b492
