### ISSUE TITLE
MapRoulette API key could not be saved 

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#880]
Description:
---

I always get this error message when trying to save the API key.

Device info:
---
<table>
<tr><td>App version</td><td>12.1.6.0</td></tr>
<tr><td>App version code</td><td>1006</td></tr>
<tr><td>Android build version</td><td>1629831864</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>41.3.A.2.192</td></tr>
<tr><td>Device brand</td><td>Sony</td></tr>
<tr><td>Device manufacturer</td><td>Sony</td></tr>
<tr><td>Device name</td><td>F8332</td></tr>
<tr><td>Device model</td><td>F8332</td></tr>
<tr><td>Device product name</td><td>F8332</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>versat</td></tr>
</table>

**Comment by simonpoole** [comment]
See http://vespucci.io/help/en/12.0.0%20Release%20notes/#support-for-maproulette this was actually a change outside of our control to the OSM API authorisation system.
