### ISSUE TITLE
Ohne Standort zu aktivieren funktioniert es nicht gut

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#882]
Description:
---

Beim jedem Start werde ich nach der Aktivierung meines Standorts gefragt, das nervt schon mal, wenn ich es gar nicht nutzen möchte, z. B. wenn ich eh an einem anderen Ort etwas ändern möchte oder drinnen eh kein guten Standort Empfang habe. Dann startet die App immer mit der Weltkarte, es ist umständlich an meinen Ort zu zoomen, eine Ortssuche wäre hier sehr hilfreich, oder dass die App sich meine letzten Orte länger merkt, auch nachdem die App komplett beendet wurde. Aber wenn es nur beim Start wäre, könnte ich noch damit leben, jedoch funktionieren die 'Aufgaben' so auch gar nicht gut, jedes mal wenn ich Aufgaben aufrufe und in meiner Benachrichtigungsleiste etwas auswähle, kommt immer wieder der Standort-aktivieren Bildschirm und dann wird lange irgend etwas geladen und wo ich dann auf der Karte die Aufgabe finde weiß ich erst nicht. So bringt mir das nicht viel. Ich weiß nicht ob ich noch nur zu ungeschickt anstelle, ob es darauf ausgelegt sein soll nur mit Standortfreigabe genutzt werden zu können oder ob sich das zukünftig verbessern lässt.
Ich kann euch auch gerne ein screen Video zukommen lassen, vielleicht habe ja auch nur ich das Problem dass es bei jeder fast neu zu starten scheint anstatt direkt zu der Aufgabe zu gehen.
Ansonsten (oder wenn ich es tatsächlich mit gps vor Ort nutze) ist die App super,aber ohne Standort geht gar nicht gut. 
Viele Grüße
Claudia 

Device info:
---
<table>
<tr><td>App version</td><td>12.1.6.0</td></tr>
<tr><td>App version code</td><td>1006</td></tr>
<tr><td>Android build version</td><td>3761073091</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>32.4.A.1.54</td></tr>
<tr><td>Device brand</td><td>Sony</td></tr>
<tr><td>Device manufacturer</td><td>Sony</td></tr>
<tr><td>Device name</td><td>E5823</td></tr>
<tr><td>Device model</td><td>E5823</td></tr>
<tr><td>Device product name</td><td>E5823</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>claudia10</td></tr>
</table>

**Comment by simonpoole** [comment]
Siehe http://vespucci.io/tutorials/faq/#why-do-i-have-to-have-gps-turned-on (2. Absatz), einfach die Einstellung setzten, dann sollte nicht nach dem GPS gefragt werden.

An und für sich merkt sich die App den letzten bearbeiteten Bereich und sollte beim nächsten mal wieder dorthin zoomen, könnte aber eine Interaktion mit obigen GPS Problem sein.

**Comment by simonpoole** [comment]
Kein weiterer feedback.
