### ISSUE TITLE
Identical EN forms for different HU forms

### ISSUE THREAD

**Issue by debyos** [MarcusWolschon/osmeditor4android#883]

**Comment by simonpoole** [comment]
You already opened an issue https://github.com/MarcusWolschon/osmeditor4android/issues/862 for this and didn't respond to the answer.

**Comment by debyos** [comment]
Dear All,

as you suggested before, I now suggest to make some distinction for English original terms. Please divide following terms into separate ones in the [preset list:](https://www.transifex.com/openstreetmap/presets/dashboard/)

monastery - in general
monastery - a specific monastery type (a facility for monastic religious orders)

pier - facilty going into the sea e.g. for ships
pier - bridge support structure

Thanks

Gábor

**Comment by debyos** [comment]
Sorry, I made a mistake sending it without any text. Could you reopen it, please?
Thanks
