### ISSUE TITLE
[feature request] Opening a location (ala JOSM)

### ISSUE THREAD

**Issue by govvin** [MarcusWolschon/osmeditor4android#884]
I use JOSM, and I love its ability to open a location URL (e.g., "https://www.openstreetmap.org/way/660066970#map=19/14.53403/121.10713" ) to edit an area or an object . 

I wish that a future version of Vespucci can do the same. Right now, it's kinda possible to do that by inputing (cut & paste) the geographic coordinates from OSM in the open other location option using coordinates, but I hope it could become more convenient by simply pasting a URL, or the object id.

A future version may have an additional option where a URL (e.g. "https://www.openstreetmap.org/way/660066970#map=19/14.53403/121.10713" or a feature (e.g. w660066970) is inputed.

![Screenshot_20190330-121622_Vespucci](https://user-images.githubusercontent.com/5821688/55271320-0e74c480-52e6-11e9-840d-6f1aac37117e.jpg)

![Screenshot_20190330-122045_Vespucci](https://user-images.githubusercontent.com/5821688/55271463-dbcbcb80-52e7-11e9-861e-713d4db3c8cd.jpg)

**Comment by simonpoole** [comment]
Related https://github.com/MarcusWolschon/osmeditor4android/issues/510

**Comment by govvin** [comment]
![image](https://user-images.githubusercontent.com/5821688/55304341-9a6d2480-547d-11e9-8b66-ab127129fcbf.png)

Another simple editor with interface options that I find useful for opening a location or object is [Level 0](http://level0.osmz.ru/). It can read areas, or objects inputted as follows:

- **Objects as a URL** -  `https://www.openstreetmap.org/node/198502895`
- **a URL of an area or location** `https://www.openstreetmap.org/#map=19/14.60470/121.03128`
- **a list of IDs in short-hand notation** - `w360962206, w360962211`

The ability to open an area or an object is helpful for editing HOT tasks, too, where currently Vespucci is not in the list of editors support by HOT. 

But you can select iD option then start the editor, and copy the URL created in your browser to the Vespucii editor , extracting just the coordinates.

![image](https://user-images.githubusercontent.com/5821688/55305863-c213bb00-5484-11e9-9662-27d3d8adf44b.png)
![image](https://user-images.githubusercontent.com/5821688/55305917-e8395b00-5484-11e9-8690-bbc0f01bb469.png)
![image](https://user-images.githubusercontent.com/5821688/55305924-ebcce200-5484-11e9-9c47-3ea914cbe83d.png)
![image](https://user-images.githubusercontent.com/5821688/55305933-f4251d00-5484-11e9-985b-6faa0b130006.png)
![image](https://user-images.githubusercontent.com/5821688/55305939-f7b8a400-5484-11e9-8934-c059124bfcbf.png)
![image](https://user-images.githubusercontent.com/5821688/55305947-fab39480-5484-11e9-966d-e0b75fa5fd53.png)

**Comment by simonpoole** [comment]
Note on the side, Vespucci has supported JOSM style remote control for a very long time, that should simply work. The reason that they don't support Vespucci has political reasons (no associated money flow that they could take a cut out of) not technical ones.

**Comment by govvin** [comment]
I know that I can trigger the geo URL intent from OsmAnd, and select Vespucci as an editor, but didn't realize how much more Vespucci is already capable of. Thank you for the update Simon.

**Comment by simonpoole** [comment]
Im proved in https://github.com/MarcusWolschon/osmeditor4android/commit/0cc8cb94989ecb5b6ed1c4f7b90ee201806b54e2 and added some documentation on how the URLs in a web page/app should look like.
