### ISSUE TITLE
read-only API URL is only changed each second time

### ISSUE THREAD

**Issue by datendelphin** [MarcusWolschon/osmeditor4android#885]
## Vespucci Version

13.0.0

## Download source

google drive beta

## Device (Manufacturer and Model)

S5 neo

## Behaviour/Symptoms

read-only API URL is only changed each second time

## Expected Behaviour

changed on the first try :)

## How to recreate

With mbtiles offline data file (change name)

## Crash dump submitted (no or yes + date)

no

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/ba96c62d185e10fff3d9a8c12bf99d6bd573d8b6 (the value was actually being changed in the underlying database, but the values used for display were not).
