### ISSUE TITLE
Preset matching with auto-presets can go wrong

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#886]
Description:
---

Case in hand: shop= cannabis matches with building

Device info:
---
<table>
<tr><td>App version</td><td>13.0.0.3</td></tr>
<tr><td>App version code</td><td>1102</td></tr>
<tr><td>Android build version</td><td>N950FXXS5DSB4</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.N950FXXS5DSB4</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>greatlte</td></tr>
<tr><td>Device model</td><td>SM-N950F</td></tr>
<tr><td>Device product name</td><td>greatltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>SimonPoole</td></tr>
</table>

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/b6d384f8a2065cf9b9c1a8eec8aaea5c8f235429
