### ISSUE TITLE
Disable map roulette by default or provide automatic way of getting map roulette API key

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#888]
Description:
---

Vespucci already suffers a bit from being complicated, for a typical user unexplained "enter  map roulette API key" will make it even worse.

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.0.0.3</td></tr>
<tr><td>App version code</td><td>1102</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
There is currently no way of getting the maproulette key automatically, you need to take this up with the maproulette authors, see https://github.com/maproulette/maproulette2/issues/476

**Comment by matkoniecz** [comment]
In this case - maybe given that configuring Maproulette is very complicated it should be disabled by default?

**Comment by HolgerJeromin** [comment]
Disabling would be the best. I am too lazy to get a key. 
Right now on **every** upload i have a dialog with "enter map roulette API key" and no possibility to clear the maproulette upload queue.

**Comment by simonpoole** [comment]
There's a reason the issue has been closed for over a month. If you have MR enabled turn it off and clear the task data.

Naturally asking MR to make the 5 minute change to store the key in the user preferences would also help.

**Comment by matkoniecz** [comment]
Is it possible that initial change enabled map roulette (broken due to https://github.com/maproulette/maproulette2/issues/476) for all users and later fix changed default only for new users and all current Vespucci users are left with hard-to disable annoying and useless message? Maybe it would be better to disable it for all, and let people reenable if they really want it?

**Comment by simonpoole** [comment]
> 
> 
> Is it possible that initial change enabled map roulette (broken due to [maproulette/maproulette2#476](https://github.com/maproulette/maproulette2/issues/476)) for all users and later fix changed default only for new users and all current Vespucci users are left with hard-to disable annoying and useless message? 
Yes, but it isn't "hard to disable".

> Maybe it would be better to disable it for all, and let people reenable if they really want it?
That is obviously not possible as there is no way to differentiate between automatic and manually enabled settings.

**Comment by matkoniecz** [comment]
> Yes, but it isn't "hard to disable".

Maybe it can be assumed that Vespucci mapper differs significantly from typical user, but based on my experience 90%-98% of users are not changing default settings and anything that requires this would be "hard to disable".

**Comment by HolgerJeromin** [comment]
To backup @matkoniecz text: I pushed about 50 times the "ok" button and did not dive into the settings or searched in the submenu for a "clear tasks" entry. 

Even for me as a power user my changed osm data, changed osm notes and maproulette changes are **all the same**. maproulette is uploaded after pushing "upload to osm server", same should be done with osm notes. 

It was surprising that osm notes and maproulette answers are not cleared when downloading a new region.

**Comment by simonpoole** [comment]
Locking this down now:
- as I pointed out maproulette support it is no longer enabled by default since nearly two months
- both how to disable and how to clear downloaded tasks is in a very obvious place and documented  both in the on device help and (searchable) on vespucci.io
