### ISSUE TITLE
auto download with offline data

### ISSUE THREAD

**Issue by datendelphin** [MarcusWolschon/osmeditor4android#890]
## Vespucci Version
13.0.0

## Download source
google drive beta

## Device (Manufacturer and Model)
S5 neo

## Android Version 
6.0.1

## Behaviour/Symptoms
Auto load does not work when offline, but offline data is available

## How to recreate
No sim card, wifi turned off, but mbtiles offline data loaded

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
Fixed in https://github.com//MarcusWolschon/osmeditor4android/commit/0fb002f
