### ISSUE TITLE
Some questions regarding Presets

### ISSUE THREAD

**Issue by westnordost** [MarcusWolschon/osmeditor4android#894]
Hey Simon

I have a few questions regarding presets in Vespucci. I am currently building a Java library  whose purpose is to translate (a bunch of) tags to localized names and the other way round. So for example, searching for `amenity=bakery`  yields `Bäckerei` and searching for `Bio-Supermarkt` yields `shop=supermarket + organic=only` with German locale.

I am building this because I need to refer to certain elements in StreetComplete by name even if no `name` property is set, but I would want it to be eligible also in other use cases, such as, finding the right tag(s) for adding features in an OSM editor or more. So I want to check what would be your requirements for this if you are interested in using it at all. Are you?

Question:
- Does Vespucci define its own presets or is it reusing presets from JSOM or iD?
- Does Vespucci currently use any other or an own mechanism to do this translation? If yes, based on what data?
- If you are interested at all, what are the features that come to your mind would be important for your use case beyond the basic functionality I mentioned above?

Cheers
Tobias

**Comment by simonpoole** [comment]
Vespucci already does all of the above so the interest in "outsourcing" it would be small (if at all it would make sense the other way around,  icon and io handling tend to be rather Android specific so it would not be totally straightforward), details on the Vespucci preset system can be found here: http://vespucci.io/tutorials/presets/

In general this is a rather old wheel to reinvent (iD and JOSM naturally have similar functionality) and on the list of things we (as in all of OSM) really don't need, yet another preset system is very very high up.

**Comment by westnordost** [comment]
The library will use the iD preset data.

**Comment by simonpoole** [comment]
> 
> 
> The library will use the iD preset data. I did not look at the JOSM preset data yet.

I wouldn't for reasons that I outlined in my talk at SotM last year, and on top of that you need to realize that they don't care shit about third parties and their system is very closely tied to iDs UI. But it is your decision.

**Comment by westnordost** [comment]
This one? https://www.youtube.com/watch?v=FbeAlf80lC8

**Comment by simonpoole** [comment]
You will  need the slides to follow it properly though (which should be somewhere on the SOTM website).

**Comment by westnordost** [comment]
Nothing is set in stone yet, I am still looking at the options for this. The existence of this ticket should be a hint that I am trying to find a solution that not only fits for my use case.

Thank you for the links to the Vespucci preset documentation and the talk, I will look through it this evening!

**Comment by westnordost** [comment]
I had a look at your presentation and JOSM presets in general more.

My use case doesn't really care about presets as a whole with all the **properties of** primary features. My case instead is only really about **finding and localizing** primary features - _search term → tags_ and _tags → primary feature name_, "full preset data support" would only be a side effect depending on what data (iD, JOSM, something else) I used.
So maybe the title of this question issue was wrong, it's just that iD calls the info on primary features [`presets`](https://github.com/openstreetmap/iD/tree/master/data/presets/presets) and the info about properties of these [`fields`](https://github.com/openstreetmap/iD/tree/master/data/presets/fields), which is convenient (for me) because I only need the former.
At least for _search term → tags_, it looks like iD is ahead, because for each preset (=primary feature), iD provides terms (= search keywords) with which this feature can also be found ([example](https://github.com/openstreetmap/iD/blob/master/dist/locales/de.json#L7730)), so I will stick with iD data.

I understand this is then not an option for you, as you already got a pretty powerful preset system in Vespucci and don't want possibly conflicting (iD vs JOSM) preset definitions there, just wanted to give you a heads-up since I opened this issue.

**Comment by simonpoole** [comment]
> At least for _search term → tags_, it looks like iD is ahead, because for each preset (=primary feature), iD provides terms (= search keywords) with which this feature can also be found ([example](https://github.com/openstreetmap/iD/blob/master/dist/locales/de.json#L7730)), so I will stick with iD data.
Vespucci uses both the contents of the presets themselves and the synonyms from iD to build a search index (JOSM I believe just uses the presets themselves).
