### ISSUE TITLE
Purple or brown or gray would be better than green for landuse=railway

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#895]
Description:
---

I expected mistagging based on how it looked like

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.0.0.3</td></tr>
<tr><td>App version code</td><td>1102</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
green is simply the default landuse colour see lines 51 and 157 https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/main/assets/Pen-round-profile.xml

**Comment by simonpoole** [comment]
Added a specific colour in https://github.com/MarcusWolschon/osmeditor4android/commit/c83d788564ec4a1e73afffcfda2637a71474b1e8 (adding things to the data style is one of the easy things and in general work and PRs on this are welcome).
