### ISSUE TITLE
Start turn restriction editor by selecting crossing node

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#896]
Description:
---

Probably the best part of iD is amazing editor of turn restrictions.

Something like that in Vespucci would be great

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.0.0.3</td></tr>
<tr><td>App version code</td><td>1102</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
Vespucci has had a special mode to add turn restrictions long before iD. That said if you supply two highly paid full time developers, plus the additional support of a company with 400 employees for design and so, yes we'll gladly add a iD look alike turn restriction editor.

**Comment by matkoniecz** [comment]
I just tried it and it works wonderfully! Is it possible to allow triggering it when crossing node is selected (like in iD)? It would ask about incoming way, outgoing way and skip question about via node.

**Comment by simonpoole** [comment]
That is possible, but would only reasonably work for via nodes.

**Comment by matkoniecz** [comment]
Yes, via nodes would be sufficient (and method likely to be used by people familiar with iD interface).

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/6cc6d991e0cce71ea2a41510686f7f70ef509d39
