### ISSUE TITLE
Toggling auto download should not be disabled in missing mobile internet

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#897]
Description:
---

It is disabled now.

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.0.0.3</td></tr>
<tr><td>App version code</td><td>1102</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
What is "now" in this context? All download options will be disabled if there is no connectivity, but we don't differentiate between mobile/wlan.

**Comment by matkoniecz** [comment]
I had no internet access and I was unable to disable "auto download" option.

**Comment by simonpoole** [comment]
Well yes, but it for all practical purposes it doesn't matter as auto-download will only work -when- you have internet access.

**Comment by matkoniecz** [comment]
In my case I enabled it by accident and wanted it to disable to prevent pointless downloading once it got access to the internet (disabling it required babysitting it and catching moment when internet was available again).

**Comment by simonpoole** [comment]
I don't think this can be fixed without impacting the normal use case.
