### ISSUE TITLE
Remove node from way function

### ISSUE THREAD

**Issue by simonpoole** [MarcusWolschon/osmeditor4android#901]
It is now and then necessary to remove a node from a specific way without deleting it.

**Comment by simonpoole** [comment]
@HolgerJeromin just as a note: there has been an extract node function for ages, the problem this issue is supposed to address is removing a node that is the member of multiple ways from a specific way without affecting the others.

**Comment by HolgerJeromin** [comment]
Seems I never realized what this icon should be. Now I tested it :)

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/27aeb3504ab06c0809205e40c4f3776813bc2520
