### ISSUE TITLE
Cannot import gpx files

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#904]
Description:
---

Would be interesting feature

Device info:
---
<table>
<tr><td>App version</td><td>13.0.2.0</td></tr>
<tr><td>App version code</td><td>1105</td></tr>
<tr><td>Android build version</td><td>A530FXXU4CSD7</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.A530FXXU4CSD7</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>jackpotlte</td></tr>
<tr><td>Device model</td><td>SM-A530F</td></tr>
<tr><td>Device product name</td><td>jackpotltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7885</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Fredi</td></tr>
</table>

**Comment by simonpoole** [comment]
Why do you believe that you can't import GPX files it has been possible literally for years?

**Comment by fparrel** [comment]
Hello
I went to every possible menu in Vespucci, and the only kind of file that I could import is .geojson
I can as well import the .gpx files that are on osm server.
But there is no menu to import .gpx files from my Android device.
This would be an interesting feature.

Regards

**Comment by simonpoole** [comment]
You don't have the following?

![Screenshot_1557478452](https://user-images.githubusercontent.com/1011860/57515178-4eca5800-7312-11e9-95d9-2df6fcd4f456.png)
![Screenshot_1557478459](https://user-images.githubusercontent.com/1011860/57515182-512cb200-7312-11e9-822f-c7a6ff692b8b.png)

**Comment by fparrel** [comment]
Thanks! I didn't tried the second bottom button, because I thought it was only to switch on/off GPS.
