### ISSUE TITLE
Multi-line text fields

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#905]
In both tag values and changeset comments, multiline fields would make editing of long values less troublesome.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/003c417baae6d951829b9da57a52449eea58e170 adds multiline fields in the upload dialog

See https://github.com/MarcusWolschon/osmeditor4android/issues/907 for the 2nd part
