### ISSUE TITLE
Upload changes dialog: Comment/Source: Add a delete button

### ISSUE THREAD

**Issue by hubgitti** [MarcusWolschon/osmeditor4android#906]
In the upload and changes dialogue, the source and comment fields show the last entry. That makes sense, but a delete button (maybe an x?) next to the text (perhaps on the left or right side) would be comfortable.

To enter a completely new entry, currently I have to:
1) long press the text -> a single word is highlighted
2) open the edit menu (three dots show up after highlighting)
3) I choose "mark all"
4) I delete the text

Just pressing an x button right next to the form entry would be more comfortable! ;-)

**Comment by simonpoole** [comment]
There is (always except if the field is already empty or there is just a draft entry) an empty entry in the drop down list that can be used to erase the current content.

**Comment by hubgitti** [comment]
Thanks, that would work for me (just didn't see it)!

**Comment by simonpoole** [comment]
I'm doing some redesign of that page in any case so maybe there will be room for a dedicated button somewhere in the future.

**Comment by simonpoole** [comment]
Changed the way this works in https://github.com/MarcusWolschon/osmeditor4android/commit/003c417baae6d951829b9da57a52449eea58e170
