### ISSUE TITLE
For some tags like lit or fee, adding "yes" is not possible

### ISSUE THREAD

**Issue by georg-d** [MarcusWolschon/osmeditor4android#909]
## Vespucci Version
13.0.2

## Download source
google play store

## Device (Manufacturer and Model)
Samsung Galaxy S7 

## Android Version 
Android 8.0 stock

## Behaviour/Symptoms
create a way, choose template bycicle parking, try to set fee or lit - you can now choose between "opening hours" or "text values", but when choosing "text values", no text field appears so you cannot enter e.g. "yes" if you simply do no know the exact times

## Expected Behaviour
text field appears

## Crash dump submitted (no or yes + date)
no

## Any other potentially relevant information
no

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/issues/872#issuecomment-471527290

**Comment by georg-d** [comment]
Thank you, I did forget to remove default "open issues only" filter from search field :-/
