### ISSUE TITLE
Changeset comment not always saved

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#911]
It seems that a changeset comment is only saved when tapping "No", but not when one cancels the upload by tapping somewhere else on the screen or pressing the back button. Vespucci v13.0.4.0 from F-Droid.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/cd85fa9be4218be42b72c6d1e380e2f69e4a16e8
