### ISSUE TITLE
markdown-gradle-plugin version problem

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#917]
## Vespucci Version
I tried compiling 492991e3

## Download source
Github repository

## Device (Manufacturer and Model)
Not applicable, compilation fails

## Android Version 
Not applicable, compilation fails

## Behaviour/Symptoms
```
ERROR: Could not find org.kordamp:markdown-gradle-plugin:2.0.0.
Searched in the following locations:
    https://plugins.gradle.org/m2/org/kordamp/markdown-gradle-plugin/2.0.0/markdown-gradle-plugin-2.0.0.pom
    https://plugins.gradle.org/m2/org/kordamp/markdown-gradle-plugin/2.0.0/markdown-gradle-plugin-2.0.0.jar
    https://repo.maven.apache.org/maven2/org/kordamp/markdown-gradle-plugin/2.0.0/markdown-gradle-plugin-2.0.0.pom
    https://repo.maven.apache.org/maven2/org/kordamp/markdown-gradle-plugin/2.0.0/markdown-gradle-plugin-2.0.0.jar
    https://dl.bintray.com/content/simonpoole/osm/org/kordamp/markdown-gradle-plugin/2.0.0/markdown-gradle-plugin-2.0.0.pom
    https://dl.bintray.com/content/simonpoole/osm/org/kordamp/markdown-gradle-plugin/2.0.0/markdown-gradle-plugin-2.0.0.jar
    https://dl.google.com/dl/android/maven2/org/kordamp/markdown-gradle-plugin/2.0.0/markdown-gradle-plugin-2.0.0.pom
    https://dl.google.com/dl/android/maven2/org/kordamp/markdown-gradle-plugin/2.0.0/markdown-gradle-plugin-2.0.0.jar
    file:/home/mateusz/Documents/install_moje/OSM software/osmeditor4android [vespucci]/lib/markdown-gradle-plugin-2.0.0.jar
    file:/home/mateusz/Documents/install_moje/OSM software/osmeditor4android [vespucci]/lib/markdown-gradle-plugin.jar
Required by:
    project :

```

## Expected Behaviour
Vespucci compiles

## How to recreate
Fetch recent master and try compiling in Android Studio.

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
Changing https://github.com/MarcusWolschon/osmeditor4android/blob/master/build.gradle#L16

to

`        classpath 'org.kordamp:markdown-gradle-plugin:1.2.0'`

allows Vespucci to compile. 

Note that 1.2.0 is recommended at https://github.com/aalmiray/markdown-gradle-plugin#installation

Android Studio claims that version 1.4 is available but fails to install it after changing line to

`        classpath 'org.kordamp:markdown-gradle-plugin:1.4.0'`

or

`        classpath 'org.kordamp:markdown-gradle-plugin:1.4'`

**Comment by simonpoole** [comment]
The plugin is used to convert markdown format files to html for on-device help, as the current html files are stored in the repo too, it is in general not used for the build. 

None of the original versions actually work due to gradle changes, but I have a forked version that works but simply isn't ready for publication yet (that will have to wait till I have a couple of days time), that is the version 2.0.0. And yes that shouldn't have leaked in to the current build file.
