### ISSUE TITLE
"Node is near element it could be connected to" should not be reported outside downloaded area

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#920]
Description:
---

Ways may lead from downloaded areas and meet outside in not downloaded area.

In not downloaded area connector may be missing. So any detected topology errors that report missing features may be false positives.

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.0.2.0</td></tr>
<tr><td>App version code</td><td>1105</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/?mlat=50.06645&mlon=19.97207#map=19/50.06645/19.97207

![Screenshot_2019-06-13-13-27-25-228_de blau android](https://user-images.githubusercontent.com/899988/59448710-08cb4d00-8e06-11e9-82a4-77b8ab304e82.png)

**Comment by simonpoole** [comment]
"fixed" in https://github.com/MarcusWolschon/osmeditor4android/commit/92af39e31119f81d84e8cb2d43b8d4df9ebc806f
