### ISSUE TITLE
Stop considering visitor info as mandatory for office=company

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#921]
Description:
---

Opening Hours and wheelchair tag should not be required by validator for `office=company` as in almost all cases it is a workplace without opening hours relevant for a general population or with surveyable wheelchair status.

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.0.2.0</td></tr>
<tr><td>App version code</td><td>1105</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
Not sure what this was doing in this repo, but fixed in https://github.com/simonpoole/beautified-JOSM-preset/commit/4b117ad1c2bdb90eb1a9f18752d84659cdacdfc9

**Comment by matkoniecz** [comment]
Thanks for fixing!

> Not sure what this was doing in this repo

I reported it using in-program feedback option that is not allowing to create reports in beautified-JOSM-preset repo.

**Comment by HolgerJeromin** [comment]
> i  reported it using in-program feedback option that is not allowing to create reports in beautified-JOSM-preset repo.

Use the context menu in the preset area of the poi editing. :-)
