### ISSUE TITLE
Checkbox behavior consistency

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#922]
Vespucci v13.0.4.0 from F-Droid

When I use the public transport platform preset, for the key `bench`...
unchecked = unknown value
checked = "yes" value
grey out (long press) = unknown value

For the key `atm` in the bank preset, however...
unchecked = "no"
checked = "yes" value
grey out (long press) = unknown value

Can we please have a single consistent behavior? I think the behavior for `atm` as described above is good, although it would be preferable that an action not be hidden away behind a long press, and that the check box should cycle through the three states using only taps.

**Comment by simonpoole** [comment]
The behaviour is perfectly consistent

- platform preset has <check key="bench" text="Bench" disable_off="true"/>

- the bank preset <check key="atm" text="Automated Teller Machine" default="on"/>

with other words the code is doing exactly what it is supposed to do. Now if the preset should be different is an other question (but it depends very much on what assumptions are being made), but in any case, if even necessary, should be discussed in the preset repo.

**Comment by contrapunctus-1** [comment]
This may be consistent with the preset data, but it's quite inconsistent from a UI perspective. Within the same app, you expect all checkboxes to behave the same way, and result in the same outcome for a given state...
