### ISSUE TITLE
Osmose - "<something> observed around but not associated tags" displayed un Vespucci as "Error" without any info

### ISSUE THREAD

**Issue by matkoniecz** [MarcusWolschon/osmeditor4android#923]
## Vespucci Version
13.1.0

## Download source
google play store

## Device (Manufacturer and Model)
Xiaomi Redmi 4

## Android Version 
6.0.1

## Behaviour/Symptoms
Osmose issues of "{something} observed around but not associated tags" type are malformed in Vespucci, probably due to a different format than other Osmose issues.

For example see ones around http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.065054&lon=19.951504&item=8xxx&level=1%2C2%2C3&tags=&fixable=

## Expected Behaviour
Such issues are not displayed or displayed with useful info, not just "Osmose: Warning" or "Osmose: Error".

## How to recreate
Open area with green marks ( http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=50.065054&lon=19.951504&item=8xxx&level=1%2C2%2C3&tags=&fixable= ) in Vespucci, download area, open Osmose issue.

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
This seems to be a non-backwards compatible change in osmose. Investigating.

**Comment by simonpoole** [comment]
Seems as if they fixed an old issue that the important information was in the subtitle field, but now is in the title field. Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/751c240e5af61d29a89949941400fd84106db904
