### ISSUE TITLE
Removing highway yeah should clear connection error

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#924]
Description:
---

In one case topology connection error was caused by invalid tagging way as highway=footway

After tag was removed the error stayed.

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.1.0.2</td></tr>
<tr><td>App version code</td><td>1201</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by matkoniecz** [comment]
In this case bug was triggered during making https://www.openstreetmap.org/changeset/71265878

https://www.openstreetmap.org/way/288303891 was tagged as highway=footway and detected as missing connection, after removing this tag nodes were still marked as pink

**Comment by simonpoole** [comment]
Fixed https://github.com/MarcusWolschon/osmeditor4android/commit/ee03a66b3ee92b7eb9e7c74b698c61ce305566db
