### ISSUE TITLE
On the fly preset creation

### ISSUE THREAD

**Issue by omgitsgela** [MarcusWolschon/osmeditor4android#926]
I am doing some editing that doesn't have a preset file already created for it, and it's beyond me how to create any kind of preset import file, per the manual. What I do know is I'd like to have presets where I can specify what tags I want, and it automatically applies it. Perhaps being able to make them on the fly within the app.

For example, I want to tag sidewalk features, which are highway=footway, footway=sidewalk. There's no preset that automatically applies both those tags to the feature I'm trying to edit. Because of this, I need to manually type in the tags for each and every feature, which is obnoxious. It would be so much more helpful to just set this combination of tags as an instant preset, and recall that preset for future edits.

**Comment by simonpoole** [comment]
While not a 100% solution, if you use the online preset search facility it will create a preset for you from the results that you can then later refine (creating presets is in any case very simple), but this just works for top-level tags that currently don't have a preset..

Note. there -is- a preset for highway=footway which includes footway=sidewalk (see "Dedicated footway").

**Comment by omgitsgela** [comment]
I just played with that +ABC button to apply preset with best tags. What it seems to do is look up the most appropriate tags for the root item type and bring them up as editable options where you can then add values for optional fields. This is a different behavior than what I'm looking for.

If I'm drawing multiple features over and over again, having to type out, or even tap, the optional values becomes tedious. I might draw a sidewalk, and then a flush kerb, and then a marked crossing, and go between them all. With hundreds of edits in a power user's edit session, this means a ton of extra taps that could be avoided. In the current implementation, the best I can do is copy and paste from an existing feature's tags, but that only works when you're editing the exact same type of feature over and over again.

What I'm looking for is to edit the first feature I want with the tags I need, then save that set of tags to the preset quick selector. In future items, I could just pick the preset quick pick from the right and automatically have the tags I had preconfigured for that item get added to the selection. It would massively cut down on keystrokes, allow infinite user customizability options for presets, and really make power editing a reality with Vespucci.

The implementation would be pretty simple on the GUI side of things... just add a button above the property tag editor "Add to presets". The configuration would appear as a tile on the right top quick pick preset list. Deleting presets would use the same mechanism currently used... holding the tile until it disappears.

What do you think?

**Comment by simonpoole** [comment]
UI-wise it can't be quite that simple (at least not if you want to be able to use it at any point during the tagging process), as you need to be able to indicate which tags should be retained in the generated preset with (potentially fixed) values, and which ones should be key only. For example typically you would never want to include the value of a name tag.

**Comment by simonpoole** [comment]
https://github.com//MarcusWolschon/osmeditor4android/commit/63219f3 adds a basic implementation that tries to "do the right thing", but provides no per tag customisation.

**Comment by HolgerJeromin** [comment]
Just as a note: You can copy tags for an element an paste it on other elements.
Not sure if you know that feature.

**Comment by simonpoole** [comment]
> 
> 
> Just as a note: You can copy tags for an element an paste it on other elements.
> Not sure if you know that feature.

IMHO not quite the same use case https://twitter.com/sp8962/status/1163356603208351745
