### ISSUE TITLE
receive geo-tagged pictures via Share menu

### ISSUE THREAD

**Issue by olafhering** [MarcusWolschon/osmeditor4android#927]
It would be nice if the app would be able to receive geo-tagged pictures via the Share menu. That way one can browse pictures in the Gallery, and send one (or a batch?) to Vespucci which in turn should extract the location info from the picture and go straight to that position. In case the picture has no location info, a short info should be shown.

While the app has a feature to show also geo-tagged pictures, it is not obvious which one is the picture with the POI info. There are certainly ways to guess based on the shown filename.

**Comment by simonpoole** [comment]
Added https://github.com/MarcusWolschon/osmeditor4android/commit/d21fdbe21cf27a5e18a6cc3f6951ed51a5b53590

Note due to the in and outs of Android (file) permissions this is less intuitive than it should be.
