### ISSUE TITLE
Copying, deleting individual tags on detailed view

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#929]
Description:
---

I am not sure whatever I do something wrong, but it seems that I was able to copy/delete individual tags in past

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.1.0.2</td></tr>
<tr><td>App version code</td><td>1201</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by Mannivu** [comment]
I can copy or delete individual tags in detailed view.￼

￼

Don't you have these two icons￼

After selecting tags?

**Comment by matkoniecz** [comment]
I now managed to reproduce it - after few "select some tags, rotate phone, repeat" this two icons are gone and not appearing despite selected tags.

**Comment by simonpoole** [comment]
Yes this seems to be a defect, reason currently unknown (that said, I would never ever have screen auto-rotation turned on when using vespucci).

**Comment by simonpoole** [comment]
It seems that the configuration changes would eventually cause the action mode callback handler not to get nulled, the unexplainable bit is why that survives termination of the activity. In any case https://github.com/MarcusWolschon/osmeditor4android/commit/bf4620e2882e85d31e505166a3c9a66bd98eb8c4 explicitly finishes the action mode and nulls the callback reference.

**Comment by matkoniecz** [comment]
> In any case bf4620e explicitly finishes the action mode and nulls the callback reference.

Thanks for a quick fix! And again thanks for maintaining this great editor, editing directly during walk is so much better than making notes and later throwing them out without using them :)

> that said, I would never ever have screen auto-rotation turned on when using vespucci

In my case I quite rarely go on Vespucci-only trips. Usually it is one of many things that I do, often I start editing on noticing that something changed or that map that I using is showing wrong data. So I rarely bother with locking screen rotation.

**Comment by simonpoole** [comment]
You know you can lock separately in vespucci?

**Comment by matkoniecz** [comment]
No, I was not aware about it. I will use it once rotation irritates me.
