### ISSUE TITLE
request to enter inappropriate tags

### ISSUE THREAD

**Issue by olafhering** [MarcusWolschon/osmeditor4android#931]
Since a while I notice that some POIs are flagged as "incomplete". When selecting them, the missing info is `wheelchair` and `opening_hours`. These tags seem to be not helpful for `amenity=recycling;recycling_type=container`. Also other types are shown like that, I do not have a specific exampe at hand. Perhaps there should be a whitelist for types that definitly need such info, as well as a blacklist where such tags are not helpful?

Lat: 49.4540378
Lon: 11.0801691

**Comment by simonpoole** [comment]
The warnings are driven by a combination of 

a) the validation configuration (which tags are considered to be important, and if even optional tags should be considerd) 

and

b) the tags that are expected to be present for a certain object (driven by the presets https://github.com/simonpoole/beautified-JOSM-preset )

More information: http://vespucci.io/help/en/Introduction/ "Configuring Checks"

If you think that a warning is mistaken, you should consider opening an issue in the preset repo. 

For the example at hand, I have yet to see a recycling facility here that doesn't have explicit opening hours, including hefty fines when not observed. So adding opening_hours is, well, useful.

**Comment by olafhering** [comment]
This is partly discussed in https://github.com/simonpoole/beautified-JOSM-preset/issues/111
