### ISSUE TITLE
Lock mode: Drop-drown closes too quickly

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#932]
Description:
---

Hi, in lock mode (after downloading the map section of course) I want to check on objects by long-pressing the drop-down to select the objects appears, but only very very briefly, so I cannot select the object at all!  I tried with several different objects, different locations, restarting all apps incl. Vespucci, but nothing helps.
Can you give advice or fix it, thank you! Best, Stephan

Device info:
---
<table>
<tr><td>App version</td><td>13.0.6.0</td></tr>
<tr><td>App version code</td><td>1109</td></tr>
<tr><td>Android build version</td><td>G930FXXS4ESC3</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>R16NW.G930FXXS4ESC3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>herolte</td></tr>
<tr><td>Device model</td><td>SM-G930F</td></tr>
<tr><td>Device product name</td><td>heroltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8890</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>peppone84</td></tr>
</table>

**Comment by simonpoole** [comment]
This is a Samsung specific issue see https://github.com/MarcusWolschon/osmeditor4android/issues/750 for details and a workaround.
