### ISSUE TITLE
Go to coords crash with empty input

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#933]
Description:
---

Go to coordinates -> press OK without filling input -> the app crashes.

Report sent twice,  ~30. 6. 2019 0:40 UTC+1

Device info:
---
<table>
<tr><td>App version</td><td>13.1.0.3</td></tr>
<tr><td>App version code</td><td>1202</td></tr>
<tr><td>Android build version</td><td>A300FUXXU1CRF1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.A300FUXXU1CRF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a3ulte</td></tr>
<tr><td>Device model</td><td>SM-A300FU</td></tr>
<tr><td>Device product name</td><td>a3ultexx</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>kudlav</td></tr>
</table>

**Comment by kudlav** [comment]
@kudlav
report sent from app (two factor authentication still not supported...)

**Comment by simonpoole** [comment]
Thanks for report, fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/5c07c62bf277f227beb2eabf45585fd99e6e04ef

Wrt to 2-Factor authentication none of the "report issue to github" libraries that were feasible to use at the time support two factor authentication.
