### ISSUE TITLE
"aed" is unable to find aed in presets while using Polish translation

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#937]
Description:
---

@matkoniecz

I am assuming here that aed is in presets

Device info:
---
<table>
<tr><td>App version</td><td>13.1.0.3</td></tr>
<tr><td>App version code</td><td>1202</td></tr>
<tr><td>Android build version</td><td>V8.0.3.0.0.MCECNDG</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>prada</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>prada</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
This is not a surprise as neither the polish translation of the preset, not the original preset text, nor the polish synonyms (from iD) contain the abbreviation.

**Comment by matkoniecz** [comment]
Thanks!

> nor the polish synonyms (from iD) contain the abbreviation.

I attempted to add "aed" to synonyms in Polish translation of iD (and I think that I succeeded!).

**Comment by simonpoole** [comment]
Note that it will take a while to propagate into Vespucci as iD needs to pull the translations first.

**Comment by simonpoole** [comment]
Resolved in https://github.com/MarcusWolschon/osmeditor4android/commit/ee7d90a5e01c976fbf41950190eb01c36d8f2e4b
