### ISSUE TITLE
Bug while merging ways.

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#938]
Description:
---

Hallo there

Some other user told me, that some action I did (merging two way-segments) causes problem if the segment contains only two nods.
In these places the problem happened  because I did not delete the short segment to merge the adjacent way-segments. In one case it was a bridge which is properly mapped as a road with a stream in a culvert below.
Anyways if a segment of a road which contains only 2 nods is merged, your programming should delete the way and one of the nods.
If I got this right from the user who wrote me JOSM is doing this.
In the meantime I try not to merge in such situations any more.

Kind regards
Urs

Device info:
---
<table>
<tr><td>App version</td><td>13.0.6.0</td></tr>
<tr><td>App version code</td><td>1109</td></tr>
<tr><td>Android build version</td><td>gms-dc48370a</td></tr>
<tr><td>Android release version</td><td>7.1.2</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>19.02.1</td></tr>
<tr><td>Device brand</td><td>Fairphone</td></tr>
<tr><td>Device manufacturer</td><td>Fairphone</td></tr>
<tr><td>Device name</td><td>FP2</td></tr>
<tr><td>Device model</td><td>FP2</td></tr>
<tr><td>Device product name</td><td>FP2</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>nurdafur</td></tr>
</table>

**Comment by simonpoole** [comment]
Could you provide a link to your changeset that supposedly caused issues? 

Naturally merging ways works exactly as you say it should, so either there is an edge case that causes problems or there was a issue with the data already before you edited.

**Comment by nurdafur** [comment]
CS 71835031 way 167014964
CS 71650146 Node 993964781 
CS 71624648 Node 1843109030

**Comment by simonpoole** [comment]
So ich bin aus den Ferien zurück. Keiner der changesets hat ein Kommentar, wer hat reklamiert und was ist genau der Fehler?

**Comment by nurdafur** [comment]
Hallo Simon
Wie oben erwähnt, hat mich ein anderer User aufeinnen Fehler hingewiesen.
Was ich gemacht habe:
Ich habe einen Wegpunkt einer Linie mit einem anderen Wegpunkt verschmolzen. Diese Linien, Teilstücke von Strassen, bestanden nur aus je 2 Punkten. Vespucci hat dann die Linie zwar gelöscht, jedoch nicht Korrekt. Es blieb anscheinend Information der Linie oder eines Punktes zurück. Beim neu Laden des entsprechenden Abschnittes zeigte mir Vespucci oft keine Linien an.

**Comment by simonpoole** [comment]
Das tönt komisch, denn wenn du zwei Wege hast und einen Wegpunkt mit einem anderen verschmilzts, hast du am Schluss immer noch zwei Wege, ausser im degenerierten Fall in dem alle Wegpunkte miteinander verschmolzen werden. In dem Fall wird der Weg entfernt, kann das sein, dass du das gemacht hast?

Das Problem beim Wegeverschmelzen, ist in der Zwischenzeit behoben, war aber nur ein Darstellungsproblem und nicht ein Datenkonsistenzproblem. Aber eben Wegeverschmelzen (d.h. 2 Wege durch einen ersetzen mit den gleichen Wegpunkten) ist nicht das gleiche wie Wegpunkteverschmelzen (in keinem Editor).

**Comment by simonpoole** [comment]
Ich hab den Fehler gefunden, aus irgendeinem Grund wird der Weg eben nicht entfernt wenn man einen Weg so zum "verschwinden" bringt.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/77fad024ab9fced026abe276068c36936ed6edc3
