### ISSUE TITLE
Pas du tout intuitif

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#940]
Description:
---

Habitué à josm osm contributor... Vespucci n'est pas du tout ux design

Device info:
---
<table>
<tr><td>App version</td><td>13.0.6.0</td></tr>
<tr><td>App version code</td><td>1109</td></tr>
<tr><td>Android build version</td><td>gms-404195ba</td></tr>
<tr><td>Android release version</td><td>7.1.2</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>19.05.3</td></tr>
<tr><td>Device brand</td><td>Fairphone</td></tr>
<tr><td>Device manufacturer</td><td>Fairphone</td></tr>
<tr><td>Device name</td><td>FP2</td></tr>
<tr><td>Device model</td><td>FP2</td></tr>
<tr><td>Device product name</td><td>FP2</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>maferikotupi</td></tr>
</table>

**Comment by simonpoole** [comment]
Not actionable / rant
