### ISSUE TITLE
Changeset tag locale

### ISSUE THREAD

**Issue by c933103** [MarcusWolschon/osmeditor4android#942]
From an edit I made via Vespucci https://www.openstreetmap.org/changeset/72204360 , it indicate the changeset have been tagged with locale=zh_HK_#Hant. What's the meaning of that "#" preceding Hant? Can that be removed?

**Comment by simonpoole** [comment]
I need to check this but imho we simply add the current locale value as a string. Android mangles some locale subvalues a bit, and the # is likely a result of that. In any case is this a serious concern or just an annoyance?

**Comment by c933103** [comment]
For now it's just an annoyance to me, but I wouldn't rule out the chance that some other tools might be failed to understand this locale value when they need such information for different purpose

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/d3d4fd991656f63a26c52077500458c8ff53a89f
