### ISSUE TITLE
Suggest https for website

### ISSUE THREAD

**Issue by blackboxlogic** [MarcusWolschon/osmeditor4android#943]
When adding a website tag, it is currently pre-populated with http://

https://github.com/MarcusWolschon/osmeditor4android/blob/5a2948f5651ff8b57589bda009a7c06981a0d9f9/src/main/java/de/blau/android/propertyeditor/TagEditorFragment.java#L2469
and
https://github.com/MarcusWolschon/osmeditor4android/blob/5a2948f5651ff8b57589bda009a7c06981a0d9f9/src/main/java/de/blau/android/propertyeditor/TagEditorFragment.java#L2470

I suggest changing Tags.HTTP_PREFIX to Tags.HTTPS_PREFIX so that the website tag will be pre-populated with the more secure version of a website.

**Comment by simonpoole** [comment]
As a tendency I would rather remove the pre-filling and determine the suitable protocol automatically.

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/cbbf16679f9cc0abf0357e54c3638cc7c6b5e3ac allows to manually start a check that will determine how the domain/url is reachable (if at all).
