### ISSUE TITLE
Vespucci should not autocomplete denomination=catholic for historic=wayside_cross

### ISSUE THREAD

**Issue by CRCulver** [MarcusWolschon/osmeditor4android#944]
## Vespucci Version
13.1.0

## Download source
F-Droid

## Device (Manufacturer and Model)
LineageOS

## Android Version 
LineageOS 16

## Behaviour/Symptoms
When Vespucci autocompletes for a historic=wayside_cross POI, the tag denomination=catholic is added. This is not an appropriate generalization, inasmuch as Romania holds a significant amount of the wayside crosses in Europe and these are overwhelmingly denomination=orthodox. 

## Expected Behaviour
Vespucci should not autocomplete the denomination for this tag.

## How to recreate
Create a node, enter historic=wayside_cross into the tag editor, then tap the +ABC button to autocomplete.

## Crash dump submitted (no or yes + date)
no

**Comment by simonpoole** [comment]
This is a preset issue (imho adding the denominator value is a recent change), and needs to be created in the preset repo

**Comment by CRCulver** [comment]
Done. Sorry, I was unaware that these presets are separate from the Vespucci project.
