### ISSUE TITLE
Vespucci very slow (about 7fps)

### ISSUE THREAD

**Issue by MegaArthur** [MarcusWolschon/osmeditor4android#946]
Hey,

I really like the app, it works really well for editing OSM from a mobile device, but it is very slow on my devices.

I have tested it on an LG G6 and a Galaxy S5 Neo and it averaged about 7 frames per second in the main UI.

Online tiles also load very slowly and at some zoom levels not at all.

**Comment by simonpoole** [comment]
I regularly test on an original S5, and while there are some underlying reasons why the app can't be a speed daemon, this sounds rather slow.

Have you checked the FAQs? In particular

http://vespucci.io/tutorials/faq/#vespucci-is-getting-slower-and-slower

and

http://vespucci.io/tutorials/faq/#running-vespucci-on-old-and-small-devices

 Further you haven't indicated which Vespucci version you are using and which background layers. making it difficult to determine what might be the actual issue. For example you might want to try the data style that doesn't render multi-polygons with 13.1.

**Comment by MegaArthur** [comment]
I am using Vespucci v. 13.1 on a rooted android Pie phone and a rooted Android Nougat phone. Both show the same results.

Changing the data style doesn't help, same with changing the underlay.

![No underlay](https://imgur.com/56zZ7pC)

![With mapnik underlay](https://imgur.com/A8TuDqI)

It's as if Vespucci just refused to utilise the full processing power of the devices.


Pretty much the same thing happens on the S5 Neo when Vespucci has been freshly installed and no settings changed

**Comment by simonpoole** [comment]
The area looks very large and while it doesn't have  so many elements in it, expecting smooth panning is rather optimistic, have you tried switching to the data style that doesn't render multi-polygons?

**Comment by MegaArthur** [comment]
Not rendering multipolygons, disabling tasks, zooming in and disabling the map backgrounds does solve it somewhat. It seems the most laggy thing is using a map background. Gotta wait for HW accel I guess

**Comment by simonpoole** [comment]
How large is the imagery cache you have configured? You may want to tweak that and the number of imagery download threads.

**Comment by MegaArthur** [comment]
I increased the DL threads to 16, which helped speed up tile loading, which is nice. Changing the size of the tile cache (to 500MB and back to 50MB) didn't really help, but with conservative operations I can get a stable 12-13 fps

**Comment by simonpoole** [comment]
BTW one thing that will help when displaying a lot of data (when the app is "unlocked") is turning off drawing of the tolerance areas around objects .
