### ISSUE TITLE
Text in Find Dialog out of range

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#948]
Description:
---

In the Find Dialog, I can't see all of the text. I will try to add a screenshot.

Device info:
---
<table>
<tr><td>App version</td><td>13.1.0.0</td></tr>
<tr><td>App version code</td><td>1203</td></tr>
<tr><td>Android build version</td><td>G955FXXU5DSFB</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.G955FXXU5DSFB</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dream2lte</td></tr>
<tr><td>Device model</td><td>SM-G955F</td></tr>
<tr><td>Device product name</td><td>dream2ltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>David Baumann</td></tr>
</table>

**Comment by simonpoole** [comment]
Typically samsung phones create a screenshot if you swipe over the whole screen with the side of your hand.

**Comment by simonpoole** [comment]
I suspect the issue was fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/c51bdf44b26432e0ce74c3647b623457e44d6555 in any case, closing as no further input.
