### ISSUE TITLE
Redo button

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#949]
Description:
---

I keep accidentally hitting the undo button too many times and destroying edits in progress. Please add an easily accessible redo button.

I apologize if I'm just not aware of a redo button that already exists.

Thanks!

Device info:
---
<table>
<tr><td>App version</td><td>13.1.0.0</td></tr>
<tr><td>App version code</td><td>1203</td></tr>
<tr><td>Android build version</td><td>1905271747</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>ONEPLUS A5010_43_190527</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus5T</td></tr>
<tr><td>Device model</td><td>ONEPLUS A5010</td></tr>
<tr><td>Device product name</td><td>OnePlus5T</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Aloftheabove</td></tr>
</table>

**Comment by simonpoole** [comment]
How to access the redo function is documented both in the on device help and here: http://vespucci.io/help/en/Main%20map%20display/#undo (the website is searchable so you would have only needed to search for "redo").
