### ISSUE TITLE
Feature-Suggest: Positions-Bookmark

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#951]
Description:
---

Ich würde gerne oft an Stellen zurück gehen, an denen ich gerade nicht per GPS bin. Und die Suche ist u.U. mühsam. Eine Favoriten Funktion wäre dafür toll!

Device info:
---
<table>
<tr><td>App version</td><td>13.1.0.0</td></tr>
<tr><td>App version code</td><td>1203</td></tr>
<tr><td>Android build version</td><td>G800FXXU1CRG4</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29K.G800FXXU1CRG4</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>kminilte</td></tr>
<tr><td>Device model</td><td>SM-G800F</td></tr>
<tr><td>Device product name</td><td>kminiltexx</td></tr>
<tr><td>Device hardware name</td><td>universal3470</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>geohobbes</td></tr>
</table>

**Comment by simonpoole** [comment]
This somewhat overlaps with https://github.com/MarcusWolschon/osmeditor4android/issues/936

**Comment by simonpoole** [comment]
Bump to 14.1

**Comment by Akaash7** [comment]
Hi Simon, I'd like to work on this issue.
I was thinking about adding a bookmark toggle button in the element info dialog which would be only visible for nodes and ways.

(something like this)
![5ddd78dd-83c0-4796-8e9c-b3ceba12da68](https://user-images.githubusercontent.com/44320387/111536942-e1e73b00-8790-11eb-96df-aabba3b97c76.jpg)

Do you think this is preferable?

**Comment by simonpoole** [comment]
My thinking was more around having an entry in the GPS/Location menu that adds a bookmark and giving it a name (storing the current viewbox, so not specifically associated with an element as your suggestion would be). Then have a further option to select the bookmark you want to go back to.

In any case I wouldn't add the functionality for a bookmarked element to the info dialog, as the element is already selected at this point in time, so you could directly have a "bookmark this element" function in the element selection modes (as this could save a bounding box both functionalities could be provided).
