### ISSUE TITLE
Bing Hintergrund mögliche Zoomlevel

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#952]
Description:
---

Habe in Vespucci Bing als Hintergrundbild. Wenn ich in Felm (Schleswig-Holstein, Nordwestlich von Altenholz und Kiel, https://www.openstreetmap.org/#map=16/54.4101/10.0664) habe ich bei Bing immer ein schlecht aufgelöstes Hintergrundbild, egal wie weit ich hineinzoome. Wenn ich zum Vergleich  mit Josm am Laptop hineinzoome, habe ich zunächst das gleiche schlecht aufgelöste Hintergrundbild, wenn ich jedoch weit genug hineinzoome, kommt irgendwann ein höher aufgelöstes Hintergrundbild,  welches ich in Vespucci nicht erreichen kann. 

Device info:
---
<table>
<tr><td>App version</td><td>13.1.0.0</td></tr>
<tr><td>App version code</td><td>1203</td></tr>
<tr><td>Android build version</td><td>G950FXXU5DSFB</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PPR1.180610.011.G950FXXU5DSFB</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dreamlte</td></tr>
<tr><td>Device model</td><td>SM-G950F</td></tr>
<tr><td>Device product name</td><td>dreamltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>kielius</td></tr>
</table>

**Comment by simonpoole** [comment]
Danke für die Fehlermeldung, behoben in https://github.com/MarcusWolschon/osmeditor4android/commit/7f261f2c0cdc7f77ad0c0cbe02e25a37b993cac6
