### ISSUE TITLE
In map mode main phone navigation menu is hidden

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#955]
Description:
---

Xiaomi A2 Lite is infestated with next "great" idea - back/main menu/alt-tab buttons at the bottom are now emulated by screen.

In most cases bottom 1 cm of screen is used to display them.

But in Vespucci, in map mode this buttons are hidden, what makes displayed map a bit larger.

But using bottom of the screen is now somehow raising them, as result editing is often interupted by unintentional triggering them or it v is necessary to wait for them to disappear.

Would it be possible to make this buttons permanently visible to stop such conflicts, like it is already done during viewing settings, changing details or object or in this feedback menu?

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.1.2.0</td></tr>
<tr><td>App version code</td><td>1205</td></tr>
<tr><td>Android build version</td><td>V10.0.12.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.12.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
See http://vespucci.io/tutorials/faq/#fullscreen-mode-doesnt-work-properly

Still with modern Android version there shouldn't really be an issue (and for example we have multiple android 9.0 devices with soft keys that work just fine). If you select a menu the soft keys will show, but either selecting a menu item, or dismissing by tapping on the screen, or using the back button should remove them (this is actually not different than on a device with hardware buttons to get rid of the displayed menu).

If this is not working a video or similar would be helpful.

**Comment by simonpoole** [comment]
@matkoniecz still waiting for input on this one.

**Comment by matkoniecz** [comment]
Thanks for a reminder!

It feels at best clunky, but is completely broken during creating new notes - it impossible to create any and all attempts to bring menu to get back button allowing to hide keyboard fail.

After disabling full screen menu - layout is better and keyboard is not blocking screen.

![ezgif-3-3d538a9c9e4e](https://user-images.githubusercontent.com/899988/63215856-f551a080-c12c-11e9-9df5-3e478cb21a6e.gif)

**Comment by simonpoole** [comment]
That looks like a skin/keyboard issue, this is 
![Screenshot_1566066690](https://user-images.githubusercontent.com/1011860/63215977-79f0ee80-c12e-11e9-8dd3-b0c9301d9bc3.png)
what it looks like on stock android 8.1 in the emulator, on my phone it is very much the same (samsung with 9.0)

**Comment by matkoniecz** [comment]
> That looks like a skin/keyboard issue

Weird. It was supposed to be Android One system and I am using default keyboard. Is there something that I can run/check in logs to give chance to debug this?

**Comment by simonpoole** [comment]
> Weird. It was supposed to be Android One system and I am using default keyboard. Is there something that I can run/check in logs to give chance to debug this?
That doesn't mean that there are no bugs. You could try changing the keyboard background in your devices settings. If the device has theme support or even just dark mode, try playing around with that.

**Comment by devsnd** [comment]
I had the same problem using the stock system of the samsung galaxy s8. the bottom bar being overlaid by the on-screen android keys.

As a workaround I disabled the fullscreen mode:
preferences -> advanced preferences -> user interface settings -> full screen mode = "Never"

The app needs to be restarted for that setting to take effect.

See here an image of the problem:
![20190822_163610](https://user-images.githubusercontent.com/1980794/63524288-09661b00-c4fc-11e9-9c1b-503852403dd1.jpg)
(This happens when clicking any button on the bottom bar; accidentally hitting a button twice will therefore launch an android action instead of cloaing the bottom menu again)

**Comment by simonpoole** [comment]
@devsnd what is the issue with that? It doesn't stop menu selection and both if something is selected or the menu is dismissed, the soft keys vanish (they are shown by the OS, so even if we wanted to hide them in that case we can't).

**Comment by devsnd** [comment]
It caused me to accidentally hit the android soft keys, as they are barely visible on many occasions.

On some other fullscreen apps the soft keys would pop up below the app (moving the whole app up a bit), when swiping from the bottom of the screen, which is more acceptable from an UX standpoint IMO.

**Comment by simonpoole** [comment]
As said this is a feature of the OS/the Android UI libs that invoking a menu shows the soft keys, swipe up to show them works as expected independently of that. Iirc from testing it is possible to move the bottom of the screen up when the buttons are shown however that moves the menus up under your fingers which is extremely annoying.

You can, in the advanced settings, turn of the split action bar, and get all actions at the top of the screen.

**Comment by simonpoole** [comment]
Don't think there is anything actionable here. I did some more testing and research on if we could force hide the soft keys when a menu is shown but the conclusion is that it is currently not possible. The original problem seems to be skin related (as the buttons are there if I understood correctly, just not visible) and something clearly outside of what we can fix.

The workaround for all the issues is simply to turn off fullscreen mode off as already stated here and in the FAQs.

**Comment by matkoniecz** [comment]
> The workaround for all the issues is simply to turn off fullscreen mode off as already stated here and in the FAQs.

Also, maybe turn off fullscreen by default (not sure what kind of negative consequences it would cause).
