### ISSUE TITLE
Make description field scrollable in feedback menu

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#956]
Description:
---

Technically, there is scroll on the right side but it is almost always hidden, without reliable way to trigger it, disappearing very quickly and so small for larger terrorism that catching it is unfeasible. Based on my testing it is likely that it cannot be used for scrolling at all.

Maybe resizing the text box to show all what is typed at one would be ok? The entire screen is scrollable, and scrollable field inside scrollable field seems to be suboptimal.

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.1.2.0</td></tr>
<tr><td>App version code</td><td>1205</td></tr>
<tr><td>Android build version</td><td>V10.0.12.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.12.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
This is an upstream issue with com.heinrichreimersoftware.androidissuereporter we already fudge around some other issues with the library fixing this and some other problems would essentially require a full blown fork.

**Comment by simonpoole** [comment]
This is the same as https://github.com/MarcusWolschon/osmeditor4android/issues/835

**Comment by HolgerJeromin** [comment]
reported (years ago) upstream as https://github.com/heinrichreimer/android-issue-reporter/issues/134

**Comment by simonpoole** [comment]
Replaced by https://github.com/MarcusWolschon/osmeditor4android/issues/2426
