### ISSUE TITLE
Area rendering for leisure=garden would be nice

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#957]
Description:
---

Currently it has no area rendering

@matkoniecz (note to self: add to a to-do list, sounds easy to fix)

Device info:
---
<table>
<tr><td>App version</td><td>13.1.2.0</td></tr>
<tr><td>App version code</td><td>1205</td></tr>
<tr><td>Android build version</td><td>V10.0.12.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.12.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/5a6c53b93e34fc40c0cf9749effd8035f303cab5
