### ISSUE TITLE
The map changes the zoom in Main activity after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [MarcusWolschon/osmeditor4android#959]
When I change the orientation of the device screen, the map changes the zoom
![2019-07-20 12-17-09_before](https://user-images.githubusercontent.com/53469180/62284827-b3e6a300-b454-11e9-8446-bc43e8b6ce23.png)
![2019-07-20 12-17-09_after](https://user-images.githubusercontent.com/53469180/62284829-b3e6a300-b454-11e9-8eca-e5fe190d1a67.png)

**Comment by simonpoole** [comment]
When zoomed completely out we fit map as best as possible in the available screen real estate, which means the the zoom level will change, zoomed (that is the mercator projection square is larger than the screen in all dimensions) in the zoom level remains constant.

With other words this is working as designed and not an issue.
