### ISSUE TITLE
Layer dialog destroyed by configuration change

### ISSUE THREAD

**Issue by dlicse** [MarcusWolschon/osmeditor4android#960]
When I change the orientation of the device screen, PrefEditor activity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The textView disappears
![2019-07-20 12-39-03_before](https://user-images.githubusercontent.com/53469180/62284988-0e7fff00-b455-11e9-8510-7d69041cea74.png)
![2019-07-20 12-39-03_after](https://user-images.githubusercontent.com/53469180/62284990-0f189580-b455-11e9-8777-1cae1b39fdca.png)

-- second case --
It loses the scroll position
![2019-07-20 12-15-05_before](https://user-images.githubusercontent.com/53469180/62284991-0f189580-b455-11e9-94fd-3ff644fbf26a.png)
![2019-07-20 12-15-05_after](https://user-images.githubusercontent.com/53469180/62284992-0f189580-b455-11e9-8958-38d2121438ef.png)

**Comment by simonpoole** [comment]
Currently there are a number of less important Dialogs that are not wrapped  in a DialogFragment and do not save their state over an orientation change, this is one of them.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/3f9e5b56084144325bd2be82c1b1947bb3af58c0
