### ISSUE TITLE
Dialog disappears in PresetEditorActivity after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [MarcusWolschon/osmeditor4android#961]
When I change the orientation of the device screen, the textView inside PresetEditorActivity disappears
![2019-07-21 00-33-30_before](https://user-images.githubusercontent.com/53469180/62285178-64ed3d80-b455-11e9-9207-19b3bc60f673.png)
![2019-07-21 00-33-30_after](https://user-images.githubusercontent.com/53469180/62285179-64ed3d80-b455-11e9-9f6a-3b175d9844b9.png)

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/issues/960#issuecomment-517265715

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/3f9e5b56084144325bd2be82c1b1947bb3af58c0
