### ISSUE TITLE
Options disappear in TagFilterActivity after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [MarcusWolschon/osmeditor4android#963]
When I change the orientation of the device screen, the options disappears
![2019-07-20 20-28-15_before](https://user-images.githubusercontent.com/53469180/62285371-c31a2080-b455-11e9-9430-7516cea3db61.png)
![2019-07-20 20-28-15_after](https://user-images.githubusercontent.com/53469180/62285373-c31a2080-b455-11e9-9d16-947f72345977.png)

**Comment by simonpoole** [comment]
Addressed in https://github.com/MarcusWolschon/osmeditor4android/commit/ee295d679298b02b725a9f444799f6bbfcf5aeb1
