### ISSUE TITLE
ThemedFilePickerActivity loses the scroll position after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [MarcusWolschon/osmeditor4android#964]
When I change the orientation of the device screen, ThemedFilePickerActivity loses the position of the scroll
![2019-07-20 14-46-55_before](https://user-images.githubusercontent.com/53469180/62285477-f361bf00-b455-11e9-8c20-893362a91262.png)
![2019-07-20 14-46-55_after](https://user-images.githubusercontent.com/53469180/62285478-f361bf00-b455-11e9-8d31-94068e9b8b39.png)

**Comment by simonpoole** [comment]
This is an upstream issue that is very very unlikely to get fixed as it essentially has lost its purpose for devices >= Android Kitkat, 4.4 / 19 and is essentially unmaintained. 

As Vespucci uses the SAF now for 4.4 and later devices the interest to pursue this is miniscule, if you can convince the upstream to release a new version with a fix, I'll naturally update. But outside of that, as there is nothing actionable, closing for now.
