### ISSUE TITLE
Different colours/icons for notes and data issues

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#968]
## Vespucci Version

13.1.0

## Behaviour/Symptoms

Vespucci uses the same icon (yellow bug) for different kinds of open tasks:

- Notes
- Osmose errors/warnings/minor issues
- (maybe more...)

## Expected Behaviour

I'd like to be able to visually differentiate between notes and other tasks. This could be realized using different colours and/or different icons.

**Comment by simonpoole** [comment]
Colours would be a bit difficult imho.

**Comment by simonpoole** [comment]
Note specific icons in https://github.com/MarcusWolschon/osmeditor4android/commit/ff24f44ff13768bdb1898eef304c98bd43f494e3
