### ISSUE TITLE
Add presets for keys changing_table=... and changing_table:...=...

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#969]
## Vespucci Version

13.1.3

Vespucci should support mappers by proposing autocompletion/values for the keys described in https://wiki.openstreetmap.org/wiki/Key:changing_table (which replace the older key `diaper=...`).

**Comment by simonpoole** [comment]
Wrong repo .......

**Comment by simonpoole** [comment]
See issue in the preset repo.
