### ISSUE TITLE
Template preview as you type

### ISSUE THREAD

**Issue by chatelao** [MarcusWolschon/osmeditor4android#971]
Actually:
- I don't like to hit the "search" Button 😊

Should:
- If I'm searching a temple, e.g. "tree", I expect the icon list to be reduced to all templates matching "tree" as I type the letters.

Else: Great tool - thank you

**Comment by simonpoole** [comment]
See https://github.com/MarcusWolschon/osmeditor4android/issues/697 (coincidently I'm actually just working on this as you opened the issue, but no promises at this point in time).

**Comment by chatelao** [comment]
Ups, sorry Simon, Grüsse Oli
