### ISSUE TITLE
Reopening Osmose issues is not possible, Vespucci allows this

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#974]
Description:
---

To reproduce:
Close Osmose issue as false positive
Upload this change
Select issue and switch state to open
Upload

Now I get red message about failure that refuses to go away (reinstall time?)

Device info:
---
<table>
<tr><td>App version</td><td>13.1.2.0</td></tr>
<tr><td>App version code</td><td>1205</td></tr>
<tr><td>Android build version</td><td>V10.0.12.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.12.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
> 
> ## Description:
> 
> To reproduce:
> Close Osmose issue as false positive
> Upload this change
> Select issue and switch state to open
> Upload
> 
> Now I get red message about failure that refuses to go away (reinstall time?)
Just clear the tasks.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/6aa3b29fc2ff06c5b9cb28b1bb0900cb37cbfad5
