### ISSUE TITLE
Copy multiple ways

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#975]
Description:
---

I realize that there is a JOSM way of doing this, but sometimes I just want to use my phone to create a column of parking spaces then copy and paste the first group of parking spot ways into other sections of the parking lot that are similar.

Device info:
---
<table>
<tr><td>App version</td><td>13.1.2.0</td></tr>
<tr><td>App version code</td><td>1205</td></tr>
<tr><td>Android build version</td><td>5674421</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PQ3B.190801.002</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>bonito</td></tr>
<tr><td>Device model</td><td>Pixel 3a XL</td></tr>
<tr><td>Device product name</td><td>bonito</td></tr>
<tr><td>Device hardware name</td><td>bonito</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>MapRogers</td></tr>
</table>

**Comment by simonpoole** [comment]
This is a duplicate / contained in of https://github.com/MarcusWolschon/osmeditor4android/issues/881
