### ISSUE TITLE
Allow selective uploading

### ISSUE THREAD

**Issue by contrapunctus-1** [MarcusWolschon/osmeditor4android#976]
It'd be cool if Vespucci allowed users to select the changed objects they want to upload (akin to selective staging with Git), to alleviate situations like this -
1. Edit in area A
2. Move to area B (which is far from A) and edit there too
3. Realize you forgot to upload the edits in area A and now you have a changeset covering a bigger area than you wanted.

**Comment by contrapunctus-1** [comment]
Simpler alternative to avoid aforementioned problem - a more visible indicator to let the user know that they have un-uploaded changes. (cf. iD editor)

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/facf90a98fcc9d6ca95a7eb17a12789de20c3f6d

A badge indicating the number of outstanding elements to upload has been added to version 15 in an earlier commit.
