### ISSUE TITLE
Upload dialog should colour values of tags too, not only keys

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#979]
## Vespucci Version
Vespucci 13.1.6

## Download source
F-Droid

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
7.1.2

## Behaviour/Symptoms
The upload dialog colours *keys* of changed OSM tags, based on #798 . However, the *values* should be coloured as well: When changing tags where the key (and possibly the value too) has a significant length and looking at the values, the key column my be hidden. In this case it's not possible to quickly recognize changed tags.

## Expected Behaviour
Changed keys should be coloured as well.

**Comment by simonpoole** [comment]
Added in https://github.com/MarcusWolschon/osmeditor4android/commit/550ff18396ff71d725b4191cf60f27bde20c0565
