### ISSUE TITLE
Support membership_expression in role tags in presets. Was: [Enhancement] Automatically add public_transport=stop_area roles

### ISSUE THREAD

**Issue by Atrate** [MarcusWolschon/osmeditor4android#981]
Vespucci Version

Vespucci 13.1.6

Download source

F-Droid

# Description 

It would be really nice if when creating a public_transport=stop_area relation, some of the roles of the members were filled in automatically: the platform in the relation would be given the platform role and the stop position the stop role.

**Comment by simonpoole** [comment]
We currently don't do anything with the member_expression attribute in the presets see http://vespucci.io/tutorials/presets/#supported-josm-preset-elements-and-attributes which would be necessary to support this.

**Comment by simonpoole** [comment]
Groundwork for this done in https://github.com/MarcusWolschon/osmeditor4android/commit/35945449e14f660faea1423ddb12c00b425feae5

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/pull/1257 has support for this, however not well tested yet. The other problem is that the role can only be automatically applied if there is exactly one matching role. However stop_position seems to be the only one were this is actually true.
