### ISSUE TITLE
Adjusting Bing imagery offset with high zoom level crashes Vespucci

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#987]
## Vespucci Version
13.1.7

## Download source
F-Droid

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
7.1.2 (Fairphone Open OS (not the standard version))

## Behaviour/Symptoms
Vespucci crashes when trying to align Bing imagery offset.

## Expected Behaviour
Vespucci should not crash but align the background imagery.

## How to recreate
 Select Bing background imagery -> Zoom in as much as you can -> Tools... -> Align background -> Drag background -> Boom.

## Crash dump submitted (no or yes + date)
Yes, 2019-09-15 9:53 (UTC) and also about a week ago.

## Any other potentially relevant information
This doesn't happen for low zoom levels. It also doesn't happen for "ESRI World Imagery (Clarity) Beta" or "Mapbox Satellite" imagery.

**Comment by simonpoole** [comment]
Yes this is a bing specific issue as it is (currently at least) the only layer were the maximum zoom can increase after the actual layer configuration object has been created. 

https://github.com/MarcusWolschon/osmeditor4android/commit/f00abebe88d5bbc290e528014d665957c1160a64 reallocates the array holding the offsets if this happens.
