### ISSUE TITLE
Vespucci highlights keys as changed although they are not

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#988]
## Vespucci Version
13.1.7

## Download source
F-Droid

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
7.1.2 (Fairphone Open OS (not the standard version))

## Behaviour/Symptoms
When trying to upload a changed POI with a key `website=...` or `contact:website=...` (and maybe others), Vespucci marks such tags (keys and values) as changed (blueish-greenish color) in the upload menu, even when they haven't been changed.

## Expected Behaviour
Vespucci should neither highlight keys, nor values (in this case URLs) of tags that haven't been changed.

## How to recreate
Download the area around https://www.openstreetmap.org/node/1002391792 , change tag `name=...` to something else, try to upload the change, review the changes, select this node.

## Crash dump submitted (no or yes + date)
No

## Any other potentially relevant information
This has some similarity to https://github.com/MarcusWolschon/osmeditor4android/issues/979 .

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/975aebd32b5b33c67aa89743a7d7e27733865358 (learned something!)
