### ISSUE TITLE
Vespucci doesn't recognize `opening_hours:kitchen=...` to be opened by the integrated opening hours editor.

### ISSUE THREAD

**Issue by ltog** [MarcusWolschon/osmeditor4android#989]
## Vespucci Version
13.1.7

## Download source
F-Droid

## Device (Manufacturer and Model)
Fairphone 2

## Android Version 
7.1.2 (Fairphone Open OS (not the standard version))

## Behaviour/Symptoms
Vespucci doesn't recognize tag `opening_hours:kitchen=...` to be opened by the integrated opening hours editor.

## Expected Behaviour
When opening a node with a tag `opening_hours:kitchen=...` (or any tag `opening_hours:*=...`) in the tab `Properties`, tapping this tag should open the opening hours editor, as it is the case with POIs with the tag `opening_hours=...`.

## How to recreate
Open https://www.openstreetmap.org/node/1032168886, try to edit the kitchen opening hours.

## Crash dump submitted (no or yes + date)
No

**Comment by simonpoole** [comment]
Not a bug.

As nearly everything tag related this is driven by configuration aka the presets. 

The current preset does have a corresponding opening_hours:kitchen for amenity=restaurant,  I'm not completely sure if the version included in .7 already had that, but if not you can update your preset from the online version or add a custom one, to get the entry.
