### ISSUE TITLE
Uploading closures of OSM notes is incredibly slow

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#990]
Description:
---

Minutes of "uploading" screen that is not going away after tapping background

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>13.1.6.0</td></tr>
<tr><td>App version code</td><td>1209</td></tr>
<tr><td>Android build version</td><td>V10.0.13.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.13.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
Do you just have notes enabled? Or OSMOSE too?

**Comment by matkoniecz** [comment]
Osmose is also enabled but in that case I had no changed Osmose tasks, only closing notes.

**Comment by simonpoole** [comment]
Any idea how many notes it was in total? There is no "bulk" upload for notes so every one is closed separately which naturally makes it more likely for a connectivity glitch to effect something. 

The progress display should always be dismissible so that sounds funny.

**Comment by matkoniecz** [comment]
A single note.

**Comment by simonpoole** [comment]
Is the timeout closed or whatever now? Or put differently did the upload eventually succeed?

**Comment by simonpoole** [comment]
ping @matkoniecz

**Comment by simonpoole** [comment]
Stale, closing
