### ISSUE TITLE
Upgrading Vespucci initiates crash loop

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#994]
Description:
---

I simply upgraded Vespucci, and I got crashes over and over again.

I submitted reports as requested.

Device info:
---
<table>
<tr><td>App version</td><td>14.0.0.1</td></tr>
<tr><td>App version code</td><td>1300</td></tr>
<tr><td>Android build version</td><td>V10.0.13.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.13.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by matkoniecz** [comment]
I reinstalled Vespucci as it was crashing constantly. Hopefully crash reports provided enough info.

BTW, thanks for simplifying download menu! It is a bit sad to remove features but in this case it is step in a good direction.

**Comment by simonpoole** [comment]
Nope (wrt providing enough information) well it is some iteration of the serialisation issues caused by the "upgrade" to Android 28 (see https://github.com/RuedigerMoeller/fast-serialization/issues/288), did you have stored imagery offsets be any chance?

**Comment by simonpoole** [comment]
https://github.com/MarcusWolschon/osmeditor4android/commit/34ee890562333c8767db8c103dd5398333dcd4ac uses the built-in serialization for saving the edit state which seems to be what is causing the problem.
