### ISSUE TITLE
DE - Bank vs. Sitzbank

### ISSUE THREAD

**Issue by chatelao** [MarcusWolschon/osmeditor4android#996]
A bench (de: Sitzbank) is not found with the shortterm "Bank" but only the long term "Sitzbank"

**Comment by simonpoole** [comment]
This is not really a bug, "Bank" is found, but as we only display the 10 most relevant results, it gets buried in the large number of specific banks found. While some of those will be thrown out when their entry in the NSI gets narrowed down, there are likely always to be dozens of results.

tl;dr I'm not sure there is anything actionable here.

**Comment by chatelao** [comment]
Thanks Simon

Simon Poole <notifications@github.com> schrieb am Mi., 25. Sep. 2019, 19:06:
