### ISSUE TITLE
Imagery selection list not displayed in full and not scrollable

### ISSUE THREAD

**Issue by vespucci-reporter** [MarcusWolschon/osmeditor4android#997]
Description:
---

Maybe it is fault of my phone again

In horizontal view it is smaller but scrollable

@matkoniecz

Device info:
---
<table>
<tr><td>App version</td><td>14.0.0.1</td></tr>
<tr><td>App version code</td><td>1300</td></tr>
<tr><td>Android build version</td><td>V10.0.14.0.PDLMIXM</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PKQ1.180917.001.V10.0.14.0.PDLMIXM</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>daisy_sprout</td></tr>
<tr><td>Device model</td><td>Mi A2 Lite</td></tr>
<tr><td>Device product name</td><td>daisy</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Extra info:
---
<table>
<tr><td>OSM display name</td><td>Mateusz Konieczny</td></tr>
</table>

**Comment by simonpoole** [comment]
Could you make a screenshot and perhaps indicate where the map was centered at?

**Comment by simonpoole** [comment]
@matkoniecz ping.

**Comment by matkoniecz** [comment]
I tried to reproduce it and failed for now.

**Comment by simonpoole** [comment]
Stale, closing.
