### ISSUE TITLE
Drawing next to roof type options disappeared

### ISSUE THREAD

**Issue by giocomai** [MarcusWolschon/osmeditor4android#998]
## Vespucci Version
Vespucci 13.1.8

## Download source
f-droid

## Device (Manufacturer and Model)
Samsung S8

## Android Version 
Android 9

## Behaviour/Symptoms
Drawing next to roof type not visible. See picture
![randomTemp14331300504707600341](https://user-images.githubusercontent.com/11276752/65490302-31ef8500-dead-11e9-9998-24ca9eaa116c.png)

## Expected Behaviour
Drawing should be visible.

## How to recreate
All worked fine, until when I either cancelled or could not upload some edits, and since then I cannot see the drawing next to the roof type options that I used in that specific session. I am not sure what actually caused it, but it would be nice if there was a way to restore it (e.g. updating Vespucci did not solve this). 

## Crash dump submitted (no or yes + date)
It doesn't crash.

**Comment by simonpoole** [comment]
That is likely due to the most-recently used facilities not maintaining the link to the icon.

Thanks for the report.

**Comment by simonpoole** [comment]
Fixed in https://github.com/MarcusWolschon/osmeditor4android/commit/554b32d46464b9a653c91aa1df3571fbb907bf0f
